Repository tldr-pages/tldr, pull requests merged in 2018-12, with the labels that each got.

#2622 kompose: add page
  pages/common/kompose.md
Labels: new command

#2570 unset: add page
  pages/linux/unset.md
Labels: new command

#2617 kubens: add page
  pages/common/kubens.md
Labels: new command

#2545 tokei: add page
  pages/common/tokei.md
Labels: new command

#2624 knife: add page
  pages/common/knife.md
Labels: new command

#2623 kubetail: add page
  pages/common/kubetail.md
Labels: new command

#2630 tb: add page
  pages/common/tb.md
Labels: new command

#2621 yarn: make the install example more explicit
  pages/common/yarn.md
Labels: page edit

#2631 code: add compare two files example
  pages/common/code.md
Labels: page edit

#2634 getent: correct typo in group example
  pages/linux/getent.md
Labels: page edit

#2635 pyflakes: add page
  pages/common/pyflakes.md
Labels: new command

#2638 rg: add -v for invert matching
  pages/common/rg.md
Labels: page edit

#2632 abduco: add page
  pages/common/abduco.md
Labels: new command

#2642 thunar: add page
  pages/linux/thunar.md
Labels: new command

#2615 phpmd: add page
  pages/common/phpmd.md
Labels: new command

#2597 docker: simplify examples
  pages/common/docker.md
Labels: page edit

#2643 az: add page
  pages/common/az.md
Labels: new command

#2640 apt-file: add page
  pages/linux/apt-file.md
Labels: new command

#2651 git-branch: updated delete branch instructions
  pages/common/git-branch.md
Labels: page edit

#2652 Add another Go client
  README.md
Labels: clients

#2646 zstd: add page
  pages/common/zstd.md
Labels: new command

#2647 aws: add page
  pages/common/aws.md
Labels: new command

#2657 textutil: add page
  pages/osx/textutil.md
Labels: new command

#2656 tlp-stat: add page
  pages/linux/tlp-stat.md
Labels: new command

#2659 webtorrent: add page
  pages/common/webtorrent.md
Labels: new command

#2633 infection: add page
  pages/common/infection.md
Labels: new command, waiting

#2648 terminalizer: add page
  pages/common/terminalizer.md
Labels: new command

#2661 uprecords: add page
  pages/linux/uprecords.md
Labels: new command

#2668 brew: add cleanup example
  pages/osx/brew.md
Labels: page edit
