Repository tldr-pages/tldr, pull requests merged in 2018-11, with the labels that each got.

#2505 stolonctl: add page
  pages/common/stolonctl.md
Labels: new command

#2529 sm: add page
  pages/linux/sm.md
Labels: new command

#2514 ab: add new examples
  pages/common/ab.md
Labels: page edit

#2537 bw: add page
  pages/common/bw.md
Labels: new command

#2553 beep: Fix mismatched braces
  pages/linux/beep.md
Labels: page edit

#2522 pyenv virtualenv: add page
  pages/common/pyenv-virtualenv.md
Labels: new command

#2533 chromium: add page
  pages/common/chromium.md
Labels: new command

#2539 ansiweather: add page
  pages/common/ansiweather.md
Labels: new command

#2550 export: add -f flag
  pages/linux/export.md
Labels: page edit

#2540 brightness: add page
  pages/osx/brightness.md
Labels: new command

#2548 xfce4-terminal: add page
  pages/linux/xfce4-terminal.md
Labels: new command

#2544 noti: add page
  pages/common/noti.md
Labels: new command

#2542 lolcat: add page
  pages/common/lolcat.md
Labels: new command

#2512 Tamil pages proof of concept
  pages.ta/common/cp.md
  pages.ta/common/ls.md
  pages.ta/common/mkdir.md
  pages.ta/common/mv.md
  pages.ta/common/rm.md
  pages.ta/common/rmdir.md
Labels: architecture

#2549 tzutil: add page
  pages/windows/tzutil.md
Labels: new command

#2555 type: add page
  pages/windows/type.md
Labels: new command

#2552 xo: add page
  pages/common/xo.md
Labels: new command

#2543 lorem: add page
  pages/common/lorem.md
Labels: new command

#2551 tslint: add page
  pages/common/tslint.md
Labels: new command

#2559 title: add page
  pages/windows/title.md
Labels: new command

#2557 csc: add page
  pages/common/csc.md
Labels: new command

#2558 monodis: add page
  pages/common/monodis.md
Labels: new command

#2563 git-branch: add example to specify starting point
  pages/common/git-branch.md
Labels: page edit

#2565 svn: add `svn log` example, remove unnecessary `svn help` example
  pages/common/svn.md
Labels: page edit

#2531 ionic: add page
  pages/common/ionic.md
Labels: new command

#2567 TravisCI: include pages of all languages in archive
  scripts/build.sh
Labels: tooling

#2569 cradle-package: add page
  pages/common/cradle-package.md
Labels: new command

#2536 kube-fzf: add page
  pages/common/kube-fzf.md
Labels: new command

#2572 Add OCaml client
  README.md
Labels: clients

#2364 erl: add page
  pages/common/erl.md
Labels: new command, waiting

#2564 asciinema: add page
  pages/common/asciinema.md
Labels: new command

#2560 cradle: add page
  pages/common/cradle.md
Labels: new command

#2479 sudo: general revision of entry
  pages/common/sudo.md
Labels: page edit

#2573 pamac: add page
  pages/linux/pamac.md
Labels: new command

#2585 sudo: remove ambiguity in example
  pages/common/sudo.md
Labels: page edit

#2582 docker-machine: add page
  pages/common/docker-machine.md
Labels: new command

#2586 docker: pull image
  pages/common/docker.md
Labels: page edit

#2575 Update Contribution guidelines and PR template
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation

#2584 sbatch: add page
  pages/linux/sbatch.md
Labels: new command

#2581 cradle-sql: add page
  pages/common/cradle-sql.md
Labels: new command

#2588 cradle-elastic: add page
  pages/common/cradle-elastic.md
Labels: new command

#2591 yaourt: use token syntax
  pages/linux/yaourt.md
Labels: page edit

#2587 git-log: show branch graph
  pages/common/git-log.md
Labels: page edit

#2589 find: add searching multiple patterns simultaneously
  pages/common/find.md
Labels: page edit

#2593 PULL_REQUEST_TEMPLATE.md: use more robust links
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#2596 sed: add example to delete lines
  pages/common/sed.md
Labels: page edit

#2598 squeue: add page
  pages/linux/squeue.md
Labels: new command

#2561 cradle-install: add page
  pages/common/cradle-install.md
Labels: new command

#2535 poweroff: add pages
  pages/linux/poweroff.md
Labels: new command

#2600 drill: add page
  pages/common/drill.md
Labels: new command

#2528 jest: add page
  pages/common/jest.md
Labels: new command

#2566 netstat: add route print example
  pages/linux/netstat.md
  pages/osx/netstat.md
Labels: page edit

#2602 autorandr: add page
  pages/linux/autorandr.md
Labels: new command

#2604 timedatectl: tweak writing
  pages/linux/timedatectl.md
Labels: page edit

#2599 sinfo: add page
  pages/linux/sinfo.md
Labels: new command

#2590 ctest: add page
  pages/common/ctest.md
Labels: new command

#2568 monop: add page
  pages/common/monop.md
Labels: new command

#2605 restic: add how to restore a specific file
  pages/common/restic.md
Labels: page edit

#2609 psgrep: add page
  pages/common/psgrep.md
Labels: new command

#2346 php artisan: add page
  pages/common/php-artisan.md
Labels: new command

#2614 phpcpd: add page
  pages/common/phpcpd.md
Labels: new command

#2613 entr: add page
  pages/linux/entr.md
Labels: new command

#2571 csplit: add page
  pages/linux/csplit.md
Labels: new command

#2627 Move objdump to common
  pages/common/objdump.md
Labels: page edit

#2625 berks: add page
  pages/common/berks.md
Labels: new command
