Repository tldr-pages/tldr, pull requests merged in 2018-10, with the labels that each got.

#2359 wat2wasm: add page
  pages/common/wat2wasm.md
Labels: new command

#2363 docker: combine start/stop, add basic run example
  pages/common/docker.md
Labels: page edit

#2358 minikube: add page
  pages/common/minikube.md
Labels: new command

#2357 realpath: add page
  pages/linux/realpath.md
Labels: new command

#2362 mklink: add page
  pages/windows/mklink.md
Labels: new command

#2360 wasm2wat: add page
  pages/common/wasm2wat.md
Labels: new command

#2367 weasyprint: add page
  pages/common/weasyprint.md
Labels: new command

#2368 hyperfine: add page
  pages/common/hyperfine.md
Labels: new command

#2365 elm: add page
  pages/common/elm.md
Labels: new command

#2280 stty: add page
  pages/linux/stty.md
  pages/osx/stty.md
  pages/sunos/stty.md
Labels: new command

#2372 shards: add page
  pages/common/shards.md
Labels: new command

#2383 wasm-opt: add page
  pages/common/wasm-opt.md
Labels: new command

#2373 wasm-objdump: add page
  pages/common/wasm-objdump.md
Labels: new command

#2378 slapt-get: add page
  pages/linux/slapt-get.md
Labels: new command

#2387 fisher: add page
  pages/common/fisher.md
Labels: new command

#2386 numfmt: add page
  pages/linux/numfmt.md
Labels: new command

#2385 hyperfine: update basic example to include the minimum number of runs
  pages/common/hyperfine.md
Labels: page edit

#2390 MAINTAINERS.md: clarify visibility of the collaborators link
  MAINTAINERS.md
Labels: documentation

#2376 eventcreate: add page
  pages/windows/eventcreate.md
Labels: new command

#2389 sdk: add page
  pages/common/sdk.md
Labels: new command

#2384 groups: add page
  pages/linux/groups.md
Labels: new command

#2381 gibo: add page
  pages/common/gibo.md
Labels: new command

#2392 gpg-zip: add page
  pages/common/gpg-zip.md
Labels: new command

#2380 ndctl: add page
  pages/linux/ndctl.md
Labels: new command

#2402 MAINTAINERS.md: clarify; use semantic linebreaks
  MAINTAINERS.md
Labels: documentation

#2404 scripts: fix a typo
  scripts/pdf/render.py
Labels: tooling

#2413 bat: fix typo
  pages/common/bat.md
Labels: page edit

#2399 logname: add page
  pages/linux/logname.md
Labels: new command

#2403 p4 : add page
  pages/common/p4.md
Labels: new command

#2401 vncviewer: add page
  pages/linux/vncviewer.md
Labels: new command

#2397 clip: add page
  pages/windows/clip.md
Labels: new command

#2414 factor: add page
  pages/linux/factor.md
Labels: new command

#2400 printenv: add page
  pages/linux/printenv.md
Labels: new command

#2407 groups: move to common
  pages/common/groups.md
Labels: page edit

#2391 luac: add page
  pages/common/luac.md
Labels: new command

#2409 lsusb: add page
  pages/linux/lsusb.md
Labels: new command

#2420 hostid: add page
  pages/linux/hostid.md
Labels: new command

#2425 more: add page
  pages/windows/more.md
Labels: new command

#2427 namei: add page
  pages/linux/namei.md
Labels: new command

#2422 dircolors: add page
  pages/linux/dircolors.md
Labels: new command

#2432 enscript: add page
  pages/common/enscript.md
Labels: new command

#2428 print: add page
  pages/windows/print.md
Labels: new command

#2426 hr: add page
  pages/common/hr.md
Labels: new command

#2439 ghc: add evaluate expression example
  pages/common/ghc.md
Labels: page edit

#2433 rdpsign: add page
  pages/windows/rdpsign.md
Labels: new command

#2446 enscript: fix typos
  pages/common/enscript.md
Labels: page edit

#2440 banner: add page
  pages/common/banner.md
Labels: new command

#2447 dig: remove google's mention
  pages/common/dig.md
Labels: page edit

#2436 lrzip: add page
  pages/linux/lrzip.md
Labels: new command

#2290 wpa_supplicant: add page
  pages/common/wpa_supplicant.md
Labels: new command

#2424 gunicorn: add page
  pages/linux/gunicorn.md
  pages/osx/gunicorn.md
Labels: new command

#2435 host: add alternate dns server example
  pages/common/host.md
Labels: page edit

#2451 waitress-serve: add page
  pages/common/waitress-serve.md
Labels: new command

#2442 coreutils commands: move pages to common/ folder
  pages/common/b2sum.md
  pages/common/chroot.md
  pages/common/date.md
  pages/common/dd.md
  pages/common/dircolors.md
  pages/common/dirname.md
  pages/common/du.md
  pages/common/expand.md
  pages/common/expr.md
  pages/common/factor.md
  pages/common/head.md
  pages/common/hostid.md
  pages/common/link.md
  pages/common/logname.md
  pages/common/md5sum.md
  pages/common/nl.md
  pages/common/nproc.md
  pages/common/numfmt.md
  pages/common/pinky.md
  pages/common/printenv.md
  pages/common/realpath.md
  pages/common/sha1sum.md
  pages/common/sha224sum.md
  pages/common/sha256sum.md
  pages/common/sha384sum.md
  pages/common/sha512sum.md
  pages/common/shuf.md
  pages/common/sort.md
  pages/common/stat.md
  pages/common/stty.md
  pages/common/timeout.md
  pages/common/truncate.md
  pages/common/uname.md
  pages/common/unexpand.md
  pages/common/users.md
  pages/linux/sort.md
Labels: mass changes, page edit

#2448 update-alternatives: Added hint for showing all commands
  pages/linux/update-alternatives.md
Labels: page edit

#2449 shutdown: add page
  pages/windows/shutdown.md
Labels: new command

#2457 python: new examples
  pages/common/python.md
Labels: page edit

#2349 helm: add page
  pages/common/helm.md
Labels: new command

#2437 diff3: add page
  pages/linux/diff3.md
Labels: new command

#2455 minetest: add page
  pages/common/minetest.md
Labels: new command

#2462 diff: add -u (unified diff) example
  pages/common/diff.md
Labels: page edit

#2458 mkfile: add page
  pages/osx/mkfile.md
Labels: new command

#2454 bup: add page
  pages/common/bup.md
Labels: new command

#2453 lrztar: add page
  pages/linux/lrztar.md
Labels: new command

#2456 lrzuntar: add page
  pages/linux/lrzuntar.md
Labels: new command

#2468 fkill: add page
  pages/common/fkill.md
Labels: new command

#2465 pwlauncher: add page
  pages/windows/pwlauncher.md
Labels: new command

#2464 asr: add page
  pages/osx/asr.md
Labels: new command

#2475 snap: add refresh example
  pages/linux/snap.md
Labels: page edit

#2473 m: add page
  pages/osx/m.md
Labels: new command

#2366 xsv: add page
  pages/common/xsv.md
Labels: new command

#2482 mv: fix -i example and add -n example
  pages/common/mv.md
Labels: page edit

#2412 sqlmap: add page
  pages/common/sqlmap.md
Labels: new command

#2461 gocryptfs: add page
  pages/common/gocryptfs.md
Labels: new command

#2477 rsync: modify one example with more useful flags
  pages/common/rsync.md
Labels: page edit

#2486 cp: remove redundant example
  pages/common/cp.md
Labels: page edit

#2470 loc: add page
  pages/common/loc.md
Labels: new command

#2491 ag: add example
  pages/common/ag.md
Labels: page edit

#2483 pandoc: add example
  pages/common/pandoc.md
Labels: page edit

#2490 darkhttpd: add page
  pages/common/darkhttpd.md
Labels: new command

#2474 source: add page
  pages/common/source.md
Labels: new command

#2430 kafkacat: add page
  pages/common/kafkacat.md
Labels: new command

#2489 guix-package: add page
  pages/linux/guix-package.md
Labels: new command

#2494 git checkout: add example for creating new branch based on remote branch with different name
  pages/common/git-checkout.md
Labels: page edit

#2492 cp: fix typo in target folder path
  pages/common/cp.md
Labels: page edit

#2485 script: add page
  pages/common/script.md
Labels: new command

#2493 dot: fix typo
  pages/common/dot.md
Labels: page edit

#2508 COMMUNITY-ROLES: add links; clarify last section
  COMMUNITY-ROLES.md
Labels: community, documentation

#2507 MAINTAINERS.md: add missing dates and links
  MAINTAINERS.md
Labels: community, documentation

#2504 iperf3: fix spacing
  pages/common/iperf3.md
Labels: page edit

#2460 yay: add page
  pages/linux/yay.md
Labels: new command

#2472 gnomon: add page
  pages/common/gnomon.md
Labels: new command

#2487 guile: add page
  pages/common/guile.md
Labels: new command

#2517 units: add quotes to token
  pages/osx/units.md
Labels: page edit

#2518 mass change: apply snake case to tokens
  pages/common/ansible.md
  pages/common/arp.md
  pages/common/bosh.md
  pages/common/composer.md
  pages/common/cordova.md
  pages/common/cppcheck.md
  pages/common/passwd.md
  pages/common/vault.md
  pages/linux/flatpak.md
  pages/linux/strace.md
  pages/linux/xsetwacom.md
Labels: mass changes, page edit

#2515 aria2c: add new example
  pages/common/aria2c.md
Labels: page edit

#2520 apt-mark: add page
  pages/linux/apt-mark.md
Labels: new command

#2501 xtrlock: add page
  pages/linux/xtrlock.md
Labels: new command

#2480 gpasswd: add page
  pages/linux/gpasswd.md
Labels: new command

#2511 scheme: add page
  pages/common/scheme.md
Labels: new command

#2502 rfkill: add page
  pages/linux/rfkill.md
Labels: new command

#2495 kubeadm: add page
  pages/common/kubeadm.md
Labels: new command

#2478 command: add page
  pages/linux/command.md
  pages/osx/command.md
Labels: new command

#2506 renice: group to process group
  pages/common/renice.md
Labels: page edit

#2523 vol: add page
  pages/windows/vol.md
Labels: new command
