Repository tldr-pages/tldr, pull requests merged in 2019-10, with the labels that each got.

#3294 urxvt: add page
  pages/linux/urxvt.md
Labels: new command

#3289 shiori: add page
  pages/common/shiori.md
Labels: new command

#3284 mkfs: add page
  pages/linux/mkfs.md
Labels: new command

#3290 flask: add page
  pages/common/flask.md
Labels: new command

#3300 awk: add loops and conditions examples
  pages/common/awk.md
Labels: page edit

#3287 aws-google-auth: add page
  pages/common/aws-google-auth.md
Labels: new command

#3288 setxkbmap: add page
  pages/linux/setxkbmap.md
Labels: new command

#3301 wpa_passphrase: add page
  pages/linux/wpa_passphrase.md
Labels: new command

#3295 cryfs: add page
  pages/common/cryfs.md
Labels: new command

#3296 guacd: add page
  pages/common/guacd.md
Labels: new command

#3282 ul: add page
  pages/linux/ul.md
Labels: new command

#3303 iverilog: add page
  pages/common/iverilog.md
Labels: new command

#3292 blkdiscard: add page
  pages/linux/blkdiscard.md
Labels: new command

#3299 sbt: add page
  pages/common/sbt.md
Labels: new command

#3283 runuser: add page
  pages/linux/runuser.md
Labels: new command

#3285 cipher: add page
  pages/windows/cipher.md
Labels: new command

#3323 ctrlaltdel: add page
  pages/linux/ctrlaltdel.md
Labels: new command

#3302 git lfs: add page
  pages/common/git-lfs.md
Labels: new command

#3326 expand: clarify last command using a concrete example.
  pages/common/expand.md
Labels: page edit

#3321 qemu-img: add convert example
  pages/common/qemu-img.md
Labels: page edit

#3305 hping: add page
  pages/common/hping.md
Labels: new command

#3304 sdiff: add page
  pages/common/sdiff.md
Labels: new command

#3325 exec: correct and clarify example descriptions.
  pages/common/exec.md
Labels: page edit

#3319 git-checkout: add example to go to previous branch
  pages/common/git-checkout.md
Labels: page edit

#3316 ac: add page
  pages/linux/ac.md
Labels: new command

#3318 git-commands: add Italian translations
  pages.it/common/git-add.md
  pages.it/common/git-am.md
  pages.it/common/git-bisect.md
  pages.it/common/git-blame.md
  pages.it/common/git-branch.md
  pages.it/common/git-check-ignore.md
  pages.it/common/git-checkout.md
  pages.it/common/git-cherry-pick.md
  pages.it/common/git-clean.md
  pages.it/common/git.md
Labels: translation

#3330 qemu-img: fix typos
  pages/common/qemu-img.md
Labels: page edit

#3309 goreload: add page
  pages/common/goreload.md
Labels: new command

#3324 exiftool: reword and clarify page.
  pages/common/exiftool.md
Labels: page edit

#3334 powerstat: add page
  pages/common/powerstat.md
Labels: new command

#3331 xinput: add disable/enable commands
  pages/linux/xinput.md
Labels: page edit

#3332 Remove bullet for gianasista/tldr-viewer, an outdated project
  README.md
Labels: clients

#3312 cotton: add page
  pages/common/cotton.md
Labels: new command

#3286 explorer: add page
  pages/windows/explorer.md
Labels: new command

#3306 alacritty: add page
  pages/common/alacritty.md
Labels: new command

#3342 k8s-unused-secret-detector: add page
  pages/common/k8s-unused-secret-detector.md
Labels: new command

#3340 multiple pages: fix homepage tokens
  pages.pt_BR/common/ack.md
  pages.pt_BR/common/bundle.md
  pages.pt_BR/common/wordgrinder.md
  pages.pt_BR/common/xcv.md
  pages.pt_BR/linux/calcurse.md
  pages/common/nextflow.md
Labels: bug, translation

#3338 fish: add example for environmental variables
  pages/common/fish.md
Labels: page edit

#3343 chisel: add page
  pages/common/chisel.md
Labels: new command

#3335 gotty: add page
  pages/common/gotty.md
Labels: new command

#3358 unison: add page
  pages/common/unison.md
Labels: new command

#3347 btrfs: add page
  pages/linux/btrfs.md
Labels: new command

#3356 particle: add page
  pages/common/particle.md
Labels: new command

#3350 jwt: add page
  pages/common/jwt.md
Labels: new command

#3362 kafkacat: fix parameter bracket
  pages/common/kafkacat.md
Labels: page edit

#3333 lastcomm: add new page (#3086)
  pages/linux/lastcomm.md
Labels: new command

#3320 fnm: add page
  pages/common/fnm.md
Labels: new command

#3360 kustomize: add page
  pages/common/kustomize.md
Labels: new command

#3367 README: remove deprecated rust client
  README.md
Labels: documentation

#3336 tar: simplify extraction examples
  pages/common/tar.md
Labels: page edit

#3322 mcookie: add page
  pages/linux/mcookie.md
Labels: new command

#3315 sa: add page
  pages/linux/sa.md
Labels: new command

#3308 goimports: add page
  pages/common/goimports.md
Labels: new command

#3341 k8sec: add page
  pages/common/k8sec.md
Labels: new command

#3291 rpm: add install package example
  pages/linux/rpm.md
Labels: page edit

#3373 info: add page
  pages/common/info.md
Labels: new command

#3353 setxkbmap: add complex example and available values examples
  pages/linux/setxkbmap.md
Labels: page edit

#3375 java: added help argument
  pages/common/java.md
Labels: page edit

#3397 open: improve grammar
  pages/osx/open.md
Labels: page edit

#3406 man: improve grammar
  pages/common/man.md
Labels: page edit

#3380 aptitude: add search term and hold examples
  pages/linux/aptitude.md
Labels: page edit

#3409 kustomize: make minor improvements
  pages/common/kustomize.md
Labels: page edit

#3351 ceph: add page
  pages/linux/ceph.md
Labels: new command

#3410 chisel: fix typo
  pages/common/chisel.md
Labels: page edit

#3364 toilet: add page
  pages/linux/toilet.md
Labels: new command

#3378 k8sec: fix replacement of theses
  pages/common/k8sec.md
Labels: page edit

#3383 pdftk: add pt_BR translation
  pages.pt_BR/common/pdftk.md
Labels: translation

#3385 convert: add pt_BR translation
  pages.pt_BR/common/convert.md
Labels: translation

#3390 screencapture: add page
  pages/osx/screencapture.md
Labels: new command

#3379 showmount: add page
  pages/windows/showmount.md
Labels: new command

#3372 whatis: add osx page
  pages/osx/whatis.md
Labels: new command

#3401 reboot: improve grammar
  pages/linux/reboot.md
Labels: page edit

#3368 dhclient: add page
  pages/common/dhclient.md
Labels: new command

#3404 meteor: add pt_BR translation
  pages.pt_BR/common/meteor.md
Labels: translation

#3391 code: add pt_BR translation
  pages.pt_BR/common/code.md
Labels: translation

#3402 g++: add pt_BR translation
  pages.pt_BR/common/g++.md
Labels: translation

#3349 dockerd: add page
  pages/linux/dockerd.md
Labels: new command

#3363 mons: add page
  pages/linux/mons.md
Labels: new command

#3411 copyq: add page
  pages/common/ copyq.md
Labels: new command

#3374 netlify: add page
  pages/common/netlify.md
Labels: new command

#3417 whatis: fix typo and grammar issue
  pages/osx/whatis.md
Labels: page edit

#3381 wal: add page
  pages/common/wal.md
Labels: new command

#3429 copyd: fix space in filename
  pages/common/copyq.md
Labels: page edit

#3377 pageres: add page
  pages/common/pageres.md
Labels: new command

#3400 reboot: add page (for macOS)
  pages/osx/reboot.md
Labels: new command

#3432 toilet: edit page
  pages/linux/toilet.md
Labels: new command

#3414 rar: add page
  pages/common/rar.md
Labels: new command

#3419 arp: add pt_BR translation
  pages.pt_BR/common/arp.md
Labels: translation

#3388 xterm: add page
  pages/linux/xterm.md
Labels: new command

#3405 man: add pt_BR translation
  pages.pt_BR/common/man.md
Labels: translation

#3393 doxygen: add pt_BR translation
  pages.pt_BR/common/doxygen.md
Labels: translation

#3425 brew: remove unnecessary comments
  pages.zh/osx/brew.md
Labels: page edit

#3420 bat: add pt_BR translation
  pages.pt_BR/common/bat.md
Labels: translation

#3398 mongo: add pt_BR translation
  pages.pt_BR/common/mongo.md
Labels: translation

#3415 buzzphrase: add page
  pages/common/buzzphrase.md
Labels: new command

#3444 rar: fix example token
  pages/common/rar.md
Labels: page edit

#3421 at: add pt_BR translation
  pages.pt_BR/common/at.md
Labels: translation

#3395 docker: add pt_BR translation
  pages.pt_BR/common/docker.md
Labels: translation

#3387 lsof: add pt_BR translation
  pages.pt_BR/common/lsof.md
Labels: translation

#3384 curl: add pt_BR translation
  pages.pt_BR/common/curl.md
Labels: translation

#3408 uvcdynctrl : add page
  pages/linux/uvcdynctrl.md
Labels: new command

#3436 fc-list: add 2 new commands and examples
  pages/linux/fc-list.md
Labels: page edit

#3412 pr: add page
  pages/common/pr.md
Labels: new command

#3430 arc: add page
  pages/common/arc.md
Labels: new command

#3418 bg: add pt_BR translation
  pages.pt_BR/common/bg.md
Labels: translation

#3448 tar: update multiple file tokens
  pages/common/tar.md
Labels: page edit

#3452 fc-cache: add page
  pages/linux/fc-cache.md
Labels: new command

#3433 radare2: add page
  pages/common/radare2.md
Labels: new command

#3437 hexyl: add page
  pages/common/hexyl.md
Labels: new command

#3441 expect: add page
  pages/linux/expect.md
Labels: new command

#3440 pip3: add search command, mention 'user' flag
  pages/common/pip3.md
Labels: page edit

#3456 octo: add page
  pages/windows/octo.md
Labels: new command

#3439 oc: add page
  pages/common/oc.md
Labels: new command

#3454 iotop: add page
  pages/common/iotop.md
Labels: new command

#3438 csshX: add page
  pages/osx/csshX.md
Labels: new command

#3399 gcc: add pt_BR translation
  pages.pt_BR/common/gcc.md
Labels: translation

#3443 pastel: add page
  pages/common/pastel.md
Labels: new command

#3470 git-clone: correct and reword examples.
  pages/common/git-clone.md
Labels: bug, page edit

#3482 gedit: add page
  pages/linux/gedit.md
Labels: new command

#3462 cargo: Reword cargo build -j example
  pages/common/cargo.md
Labels: page edit

#3465 opam: add page
  pages/common/opam.md
Labels: new command

#3366 hping: add French translation
  pages.fr/common/hping.md
Labels: translation, waiting

#3459 iftop: add page
  pages/linux/iftop.md
Labels: new command

#3492 zola: add page
  pages/common/zola.md
Labels: new command

#3474 dmenu: add page
  pages/linux/dmenu.md
Labels: new command

#3297 runcon: add page
  pages/linux/runcon.md
Labels: new command

#3496 MAINTAINERS.MD: Add @einverne as contributor
  MAINTAINERS.md
Labels: community

#3493 wc (fr): remove additional trailing whitespace
  pages.fr/common/wc.md
Labels: bug, page edit

#3469 brew-bundle: add page
  pages/osx/brew-bundle.md
Labels: new command

#3480 hlint: add page
  pages/linux/hlint.md
Labels: new command

#3489 chars: add page
  pages/common/chars.md
Labels: new command

#3466 join: add -t example
  pages/common/join.md
Labels: page edit

#3507 docker-compose: add docker-compose ps
  pages/common/docker-compose.md
Labels: page edit

#3475 rpcinfo: add page
  pages/windows/rpcinfo.md
Labels: new command

#3505 tskill: add page
  pages/windows/tskill.md
Labels: new command

#3506 black: add page
  pages/common/black.md
Labels: new command

#3501 dunstify: add page
  pages/linux/dunstify.md
Labels: new command

#3503 clip: add examples, fix typos
  pages/windows/clip.md
Labels: page edit

#3520 exit: add page
  pages/common/exit.md
Labels: new command

#3521 pandoc: update markdown example
  pages/common/pandoc.md
Labels: page edit

#3508 ethtool: add page
  pages/linux/ethtool.md
Labels: new command
