Repository tldr-pages/tldr, pull requests merged in 2019-07, with the labels that each got.

#3144 ls: add French translation
  pages.fr/common/ls.md
Labels: translation

#3147 pickle: add page
  pages/common/pickle.md
Labels: new command

#3159 stern: add page
  pages/common/stern.md
Labels: new command

#3163 cat: add -v example
  pages/common/cat.md
Labels: page edit

#3162 kahlan: add page
  pages/common/kahlan.md
Labels: new command

#3167 snyk: add missing test command
  pages/common/snyk.md
Labels: page edit

#3156 wc: add French translation
  pages.fr/common/wc.md
Labels: translation

#3169 mimetype: add page
  pages/linux/mimetype.md
Labels: new command

#3172 gem: add examples for searching and uninstalling
  pages/common/gem.md
Labels: page edit

#3175 youtube-dl: fix format syntax
  pages/common/youtube-dl.md
Labels: page edit

#3165 rbac-lookup: add page
  pages/common/rbac-lookup.md
Labels: new command

#3166 rr: add page
  pages/common/rr.md
Labels: new command

#3170 hub: add hub pr usage for checkout someone created pull-request
  pages/common/hub.md
Labels: page edit

#3171 cpulimit: correct wrong examples
  pages/linux/cpulimit.md
Labels: page edit

#3176 lp: add resume a job example
  pages/common/lp.md
Labels: page edit

#3173 tsc: add page
  pages/common/tsc.md
Labels: new command

#3174 bitcoin-cli: add page
  pages/common/bitcoin-cli.md
Labels: new command

#3180 radeontop: add page
  pages/linux/radeontop.md
Labels: new command

#3157 ssh: add French translation
  pages.fr/common/ssh.md
Labels: translation

#3160 borg: add French translation
  pages.fr/common/borg.md
Labels: translation

#3158 install: add French tranlation
  pages.fr/common/install.md
Labels: translation

#3177 mysqldump: Add examples to backup/restore all databases with file redirection
  pages/common/mysqldump.md
Labels: page edit

#3178 crontab: Add example of editing crontab for a user using the -u flag
  pages/common/crontab.md
Labels: page edit

#3182 chmod: add french translation
  pages.fr/common/chmod.md
Labels: translation

#3184 renice: split description in two lines
  pages/common/renice.md
Labels: page edit

#3185 Travis: separate building from deployment
  .travis.yml
  scripts/build.sh
  scripts/deploy.sh
Labels: bug, tooling

#3191 README: add Vim client
  README.md
Labels: clients, documentation

#3189 pdflatex: add -output-directory example
  pages/common/pdflatex.md
Labels: page edit

#3186 awk: add french translation
  pages.fr/common/awk.md
Labels: translation

#3194 pt_br/axel: add Brazilian Portuguese translation
  pages.pt-BR/common/axel.md
Labels: new command, translation

#3196 vmware-checkvm: add page
  pages/linux/vmware-checkvm.md
Labels: new command

#3190 gixy: add page
  pages/common/gixy.md
Labels: new command

#3126 rename: fix 'rename' command has two different versions
  pages/linux/file-rename.md
  pages/linux/perl-rename.md
  pages/linux/prename.md
  pages/linux/rename.md
Labels: new command, page edit

#3203 git-grep: add new command
  pages/common/git-grep.md
Labels: page edit

#3200 snapper: snapshot creation
  pages/linux/snapper.md
Labels: page edit

#3205 man: clarify search example
  pages/common/man.md
Labels: page edit

#3204 astronomer: add page
  pages/common/astronomer.md
Labels: new command

#3208 7z: new example: extract archive to stdout
  pages/common/7z.md
Labels: page edit

#3210 pip3: add page
  pages/common/pip3.md
Labels: new command

#3213 git-shortlog: add -sne commands
  pages/common/git-shortlog.md
Labels: page edit

#3212 emacs: clarify examples
  pages/common/emacs.md
Labels: page edit

#3211 sphinx-build: add page
  pages/common/sphinx-build.md
Labels: new command

#3207 mat2: add page
  pages/common/mat2.md
Labels: new command
