Repository tldr-pages/tldr, pull requests merged in 2019-04, with the labels that each got.

#2836 choco-apikey: add page
  pages/windows/choco-apikey.md
Labels: new command

#2858 Rails commands translated to pt-BR
  pages.pt-BR/common/rails-generate.md
  pages.pt-BR/common/rails.md
Labels: translation

#2861 column: fix typo
  pages/common/column.md
Labels: page edit

#2863 convert: add one-liner for creating solid color images
  pages/common/convert.md
Labels: page edit

#2864 kube-capacity: add page
  pages/common/kube-capacity.md
Labels: new command

#2869 stdbuf: fix typo
  pages/common/stdbuf.md
Labels: page edit

#2833 git grep: add page
  pages/common/git-grep.md
Labels: new command

#2870 pax: add page
  pages/common/pax.md
Labels: new command

#2252 sed: get nth line of a file
  pages/common/sed.md
Labels: page edit

#2876 COMMUNITY-ROLES.md: tweak phrasing
  COMMUNITY-ROLES.md
Labels: documentation

#2875 arping: add page
  pages/common/arping.md
Labels: new command

#2882 MAINTAINERS.md: update @mebeim status
  MAINTAINERS.md
Labels: community

#2878 monodevelop: add page
  pages/common/monodevelop.md
Labels: new command

#2881 COMMUNITY-ROLES: streamline the How-to section
  COMMUNITY-ROLES.md
Labels: community, documentation

#2892 COMMUNITY-ROLES: tweak template messages to provide an explicit choice
  COMMUNITY-ROLES.md
Labels: community, documentation

#2890 wordgrinder (pt-BR): add articles
  pages.pt-BR/common/wordgrinder.md
Labels: page edit

#2895 chcon: add page
  pages/common/chcon.md
Labels: new command

#2887 bundle: add Brazilian Portuguese translation
  pages.pt-BR/common/bundle.md
Labels: translation

#2899 MAINTAINERS.MD: Add @schneiderl as contributor
  MAINTAINERS.md
Labels: community

#2893 trawl: add page
  pages/common/trawl.md
Labels: new command

#2891 multiple pages: add links to homepages
  pages/osx/sshuttle.md
  pages/osx/wacaw.md
  pages/osx/xctool.md
  pages/windows/scoop.md
Labels: page edit

#2903 unrar: add Brazilian Portuguese translation
  pages.pt-BR/common/unrar.md
Labels: translation

#2905 smartctl: Fix link to Wikipedia
  pages/common/smartctl.md
Labels: page edit

#2906 COMMUNITY-ROLES: remove mid-sentence line breaks
  COMMUNITY-ROLES.md
Labels: community, documentation

#2907 truss: add page
  pages/sunos/truss.md
Labels: new command

#2900 create_ap: tweak casing
  pages/linux/create_ap.md
Labels: page edit

#2904 xz: add Brazilian Portuguese translation
  pages.pt-BR/common/xz.md
Labels: translation

#2908 xz: add lzma format examples
  pages/common/xz.md
Labels: page edit

#2911 COMMUNITY-ROLES: fix usage of angle brackets
  COMMUNITY-ROLES.md
Labels: community, documentation

#2912 7z: add space after option -p and -o
  pages/common/7z.md
Labels: page edit

#2909 skaffold: add page
  pages/common/skaffold.md
Labels: new command

#2910 7z: add Brazilian Portuguese translation
  pages.pt-BR/common/7z.md
Labels: translation

#2913 7za: add Brazilian Portuguese translation
  pages.pt-BR/common/7za.md
Labels: translation

#2918 script: add page
  pages/linux/script.md
Labels: new command

#2889 wpa_supplicant (pt-BR): fix typos
  pages.pt-BR/common/wpa_supplicant.md
Labels: page edit

#2919 7z: remove spaces after options
  pages/common/7z.md
Labels: page edit

#2914 7zr: add Brazilian Portuguese translation
  pages.pt-BR/common/7zr.md
Labels: translation

#2921 7za: improve description and apply proper accenting
  pages.pt-BR/common/7za.md
Labels: page edit

#2917 jq: add 'combines multiple filters' example
  pages/common/jq.md
Labels: page edit

#2925 jq: fix typo
  pages/common/jq.md
Labels: page edit

#2932 pip: add show
  pages/common/pip.md
Labels: page edit

#2922 fossa: add page
  pages/common/fossa.md
Labels: new command

#2927 crystal: fix typos and add homepage
  pages/common/crystal.md
Labels: page edit

#2920 7z: remove spaces after options and fix characters
  pages.pt-BR/common/7z.md
Labels: page edit

#2933 gops: add page
  pages/common/gops.md
Labels: new command

#2924 cat: add Brazilian Portuguese translation
  pages.pt-BR/common/cat.md
Labels: translation

#2929 chfn: add page
  pages/linux/chfn.md
Labels: new command

#2926 cp: clarify and condense similar examples
  pages/common/cp.md
Labels: page edit

#2931 utmpdump: add page
  pages/linux/utmpdump.md
Labels: new command

#2853 ss: add listening socket example
  pages/linux/ss.md
Labels: page edit

#2915 ldapsearch: add page
  pages/common/ldapsearch.md
Labels: new command

#2928 scriptreplay: add page
  pages/linux/scriptreplay.md
Labels: new command

#2936 silentcast: add page
  pages/linux/silentcast.md
Labels: new command

#2934 mkcert: add page
  pages/common/mkcert.md
Labels: new command

#2923 glib-compile-resources: add page
  pages/common/glib-compile-resources.md
Labels: new command

#2939 mkcert: minor grammar fix
  pages/common/mkcert.md
Labels: page edit

#2937 cppcheck: simplify example
  pages/common/cppcheck.md
Labels: page edit

#2938 crontab: clarify and simplify job examples
  pages/common/crontab.md
Labels: page edit

#2916 jq: add 'output to string' example
  pages/common/jq.md
Labels: page edit

#2940 csc: clarify example
  pages/common/csc.md
Labels: page edit

#2945 apt: add package listing examples
  pages/linux/apt.md
Labels: page edit

#2944 newgrp: add page
  pages/linux/newgrp.md
Labels: new command

#2942 taskset: add page
  pages/linux/taskset.md
Labels: new command

#2943 nologin: add page
  pages/linux/nologin.md
Labels: new command

#2951 ect: add page
  pages/common/ect.md
Labels: new command

#2950 php: add info example
  pages/common/php.md
Labels: page edit

#2956 wifi-password: add page
  pages/osx/wifi-password.md
Labels: new command

#2946 openssl: add certificate expiry checking
  pages/common/openssl.md
Labels: page edit

#2961 vagrant: add halt
  pages/common/vagrant.md
Labels: page edit

#2958 nsenter: add page
  pages/linux/nsenter.md
Labels: new command

#2960 package.json: update dependencies
  package.json
Labels: tooling
