Repository tldr-pages/tldr, pull requests merged in 2019-12, with the labels that each got.

#3611 linkchecker: add page
  pages/common/linkchecker.md
Labels: new command

#3638 pdftotext: add -layout switch
  pages/common/pdftotext.md
Labels: page edit

#3634 makebuildserver: add page
  pages/common/makebuildserver.md
Labels: new command

#3630 e2label: add page
  pages/linux/e2label.md
Labels: new command

#3396 ls: add pt_BR translation
  pages.pt_BR/common/ls.md
Labels: translation

#3394 asdf: add pt_BR translation
  pages.pt_BR/common/asdf.md
Labels: hacktoberfest, translation

#3647 Solve Travis error
  pages.pt_BR/common/ls.md
Labels: page edit

#3625 photorec, ddrescue: add page
  pages/linux/ddrescue.md
  pages/linux/photorec.md
Labels: new command

#3645 ssh-keygen: add -R example
  pages/common/ssh-keygen.md
Labels: page edit

#3643 ipython: add page
  pages/common/ipython.md
Labels: new command

#3483 Add French translation for git basic commands
  pages.fr/common/git-add.md
  pages.fr/common/git-clone.md
  pages.fr/common/git-commit.md
  pages.fr/common/git-pull.md
  pages.fr/common/git-push.md
Labels: translation, waiting

#3457 snoop: add page
  pages/sunos/snoop.md
Labels: new command

#3652 afinfo: add page (en, zh)
  pages.zh/osx/afinfo.md
  pages/osx/afinfo.md
Labels: new command

#3655 deluge-console : Add Korean translation
  pages.ko/common/deluge-console.md
Labels: translation

#3653 magick: add page
  pages/common/magick.md
Labels: new command

#2469 shutdown: add force option
  pages/windows/shutdown.md
Labels: page edit

#2795 nkf: add page
  pages/common/nkf.md
Labels: new command

#3656 docker-logs: add page
  pages/common/docker-logs.md
Labels: new command

#3658 deluged : add Korean Translation
  pages.ko/common/deluged.md
Labels: translation

#3659 deluser : Add Korean Translation
  pages.ko/common/deluser.md
Labels: translation

#3654 Rework PDF script
  .gitignore
  scripts/pdf/README.md
  scripts/pdf/basic.css
  scripts/pdf/pt-serif-web-regular.ttf
  scripts/pdf/render.py
  scripts/pdf/requirements.txt
  scripts/pdf/solarized-dark.css
  scripts/pdf/solarized-light.css
Labels: tooling

#3660 dep : Add Korean Translation
  pages.ko/common/dep.md
Labels: translation

#3644 git-ls-tree, git-rev-list, git-rev-parse: add pages
  pages/common/git-ls-tree.md
  pages/common/git-rev-list.md
  pages/common/git-rev-parse.md
Labels: new command

#3661 magick: Fix title & add better description
  pages/common/magick.md
Labels: page edit

#3665 detox : Add Korean Translation
  pages.ko/common/detox.md
Labels: translation

#3671 dexter : Add Korean Translation
  pages.ko/common/dexter.md
Labels: translation

#3666 dexdump : Add Korean Translation
  pages.ko/common/dexdump.md
Labels: translation

#3674 Add organization owner: @mebeim
  MAINTAINERS.md
Labels: community

#3669 git-remote: add Spanish translation
  pages.es/common/git-remote.md
Labels: translation

#3673 README: Fix description of C client
  README.md
Labels: documentation

#3682 conky: add more information link
  pages/linux/conky.md
Labels: page edit

#3677 git-branch: add example to show current branch
  pages/common/git-branch.md
Labels: page edit

#3670 lsb_release: add Spanish translation
  pages.es/linux/lsb_release.md
Labels: translation

#3686 dhcpwn : Add Korean Translation
  pages.ko/common/dhcpwn.md
Labels: translation

#3679 dhclient : Add Korean Translation
  pages.ko/common/dhclient.md
Labels: translation

#3357 htpasswd: add direct generation of username/password
  pages/common/htpasswd.md
Labels: page edit, waiting

#3485 touch: add Portuguese translation
  pages.pt_BR/common/touch.md
Labels: translation

#3688 asdf: improve main description
  pages.pt_BR/common/asdf.md
Labels: page edit

#3487 xkill: add Brazilian Portuguese translation
  pages.pt_BR/common/xkill.md
Labels: translation

#3667 sops: add page
  pages/common/sops.md
Labels: new command

#3675 tar: add Spanish translation
  pages.es/common/tar.md
Labels: translation

#3680 apt* commands: add Spanish translation
  pages.es/linux/apt-add-repository.md
  pages.es/linux/apt-cache.md
  pages.es/linux/apt-file.md
  pages.es/linux/apt-get.md
  pages.es/linux/apt-key.md
  pages.es/linux/apt-mark.md
  pages.es/linux/apt.md
  pages.es/linux/aptitude.md
Labels: mass changes, translation

#3281 xargs: add example for multiple commands
  pages/common/xargs.md
Labels: page edit

#3516 ocamlc: add page
  pages/common/ocamlc.md
Labels: new command

#3687 Change main license to CC-BY 4.0
  LICENSE.md
Labels: community

#3453 wine: add page
  pages/linux/wine.md
Labels: new command

#3676 df : Add Korean Translation
  pages.ko/common/df.md
Labels: translation

#3693 Reformat LICENSE file
  LICENSE.md
Labels: documentation

#3694 stress: add page
  pages/linux/stress.md
Labels: new command

#3683 conky: add Spanish translation
  pages.es/linux/conky.md
Labels: translation

#3684 clear: add -x, -T and -V examples
  pages/common/clear.md
Labels: page edit

#3371 firefox: add extra flag options
  pages/common/firefox.md
Labels: page edit

#3695 xdg-user-dirs-update: add page
  pages/common/xdg-user-dirs-update.md
Labels: new command

#3697 cargo-doc: add page
  pages/common/cargo-doc.md
Labels: new command

#3691 Add collaborator: @ivanhercaz
  MAINTAINERS.md
Labels: community

#3700 sinfo: add link and improve examples
  pages/linux/sinfo.md
Labels: page edit

#3476 msfvenom: add page
  pages/common/msfvenom.md
Labels: new command

#2513 fuser: add new examples
  pages/linux/fuser.md
Labels: page edit

#3711 xdg-user-dirs-update: correct path syntax
  pages/common/xdg-user-dirs-update.md
Labels: page edit

#3710 Update truncate.md
  pages/common/truncate.md
Labels: page edit

#3699 tic: add page
  pages/linux/tic.md
Labels: new command

#3707 cloc: add --vcs example
  pages/common/cloc.md
Labels: page edit

#3692 diff : Add Korean Translation
  pages.ko/common/diff.md
Labels: translation

#3714 ls: pt-BR improving descriptions
  pages.pt_BR/common/ls.md
Labels: page edit

#3713 cpdf: add page
  pages/common/cpdf.md
Labels: new command

#3678 Trim .editorconfig
  .editorconfig
Labels: tooling

#3685 clear: add Spanish translation
  pages.es/common/clear.md
Labels: translation

#3703 git-merge: add Spanish translation
  pages.es/common/git-merge.md
Labels: translation

#3704 keybase: add Spanish translation
  pages.es/common/keybase.md
Labels: translation

#3705 chmod: add Spanish translation
  pages.es/common/chmod.md
Labels: translation

#3708 nano: add Spanish translation
  pages.es/common/nano.md
Labels: translation

#3668 pdfimages: add page
  pages/common/pdfimages.md
Labels: new command

#3712 qcp, qmv: small tweaks
  pages/common/qcp.md
  pages/common/qmv.md
Labels: mass changes, page edit
