Repository tldr-pages/tldr, pull requests merged in 2019-08, with the labels that each got.

#3197 trash: add page
  pages/linux/trash.md
Labels: new command

#3217 unalias: add page
  pages/common/unalias.md
Labels: new command

#3214 enca: clarify examples and fix tokens
  pages/common/enca.md
Labels: page edit

#3223 molecule: add page
  pages/common/molecule.md
Labels: new command

#3220 enscript: reword page
  pages/common/enscript.md
Labels: page edit

#3222 feedreader: fix homepage link
  pages/linux/feedreader.md
Labels: page edit

#3219 envoy: add page
  pages/common/envoy.md
Labels: new command

#3225 qlmangle: fix typo
  pages.zh/osx/qlmanage.md
Labels: page edit

#3221 envsubst: clarify examples and description
  pages/common/envsubst.md
Labels: page edit

#3226 phpbu: add page
  pages/common/phpbu.md
Labels: new command

#3229 apt-add-repository: add page
  pages/linux/apt-add-repository.md
Labels: new command

#3231 mosquitto: add page
  pages/common/mosquitto.md
Labels: new command

#3232 mosquitto_passwd: add page
  pages/common/mosquitto_passwd.md
Labels: new command

#3179 git-rebase: Examples with --skip and -X flags
  pages/common/git-rebase.md
Labels: page edit

#3234 xkill: add page
  pages/common/xkill.md
Labels: new command

#3235 chflags: add missing 'no' to clear hidden flag
  pages/osx/chflags.md
Labels: page edit

#3198 kubectl: edit page
  pages/common/kubectl.md
Labels: page edit

#3241 virsh: add page
  pages/common/virsh.md
Labels: new command

#3243 mssh: add page
  pages/linux/mssh.md
Labels: new command

#3238 bash: add zh translation
  pages.zh/common/bash.md
Labels: translation

#3215 journalctl: add options to filter by time
  pages/linux/journalctl.md
Labels: page edit

#3206 if: add if conditions with examples
  pages/common/if.md
Labels: page edit

#3244 colrm: add page
  pages/linux/colrm.md
Labels: new command

#3246 git-switch: add page
  pages/common/git-switch.md
Labels: new command

#3188 lsof: find the process listening on a local port
  pages/common/lsof.md
Labels: page edit

#3248 Update git-switch.md
  pages/common/git-switch.md
Labels: page edit

#3249 whoami: add Brazilian Portuguese translation
  pages.pt-BR/windows/whoami.md
Labels: translation

#3236 mount: add --bind example
  pages/common/mount.md
Labels: page edit

#3251 inxi: add inxi -r
  pages/linux/inxi.md
Labels: page edit

#3253 gcalcli: add page
  pages/common/gcalcli.md
Labels: new command

#3168 Client spec v1.2: new --language flag, BCP47 to POSIX and other clarifications
  CLIENT-SPECIFICATION.md
Labels: clients, documentation

#3252 takeown: add page
  pages/windows/takeown.md
Labels: new command

#3247 git-restore: add page
  pages/common/git-restore.md
Labels: new command

#3240 Update outdated `vue` document
  pages/common/vue-build.md
  pages/common/vue-init.md
  pages/common/vue-serve.md
  pages/common/vue.md
Labels: new command, page edit

#3233 rofi: added dmenu option, added homepage
  pages/linux/rofi.md
Labels: page edit
