Repository tldr-pages/tldr, pull requests merged in 2019-02, with the labels that each got.

#2739 web-ext: add page
  pages/common/web-ext.md
Labels: new command

#2747 [Security]: Moving to a secure way of uploading assets
  .travis.yml
  scripts/build.sh
  scripts/id_ed25519_tldr_asset_upload.enc
Labels: tooling

#2750 Cleaner deployment process (fixes #2749)
  .travis.yml
  scripts/deploy.sh
Labels: tooling

#2748 aria2: add page
  pages/common/aria2.md
Labels: new command

#2742 pathchk: add page
  pages/linux/pathchk.md
Labels: new command

#2752 TravisCI: don't clean build dir needed for deployment.
  .travis.yml
Labels: bug, tooling

#2744 sn: add page
  pages/common/sn.md
Labels: new command

#2701 clockwork-cli: add page
  pages/common/clockwork-cli.md
Labels: new command

#2727 Translate first 6 windows pages in Brazilian Portuguese
  pages.pt-BR/windows/cls.md
  pages.pt-BR/windows/cmd.md
  pages.pt-BR/windows/dir.md
  pages.pt-BR/windows/mkdir.md
  pages.pt-BR/windows/print.md
  pages.pt-BR/windows/type.md
Labels: translation

#2757 airpaste, dir: fix typo.
  pages.pt-BR/common/airpaste.md
  pages.pt-BR/windows/dir.md
Labels: page edit, syntax

#2755 gzip: correct example description
  pages/common/gzip.md
Labels: page edit

#2758 tshark: add page
  pages/linux/tshark.md
Labels: new command

#2753 Deploy: run all commands separately to avoid unnoticed errors.
  scripts/deploy.sh
Labels: bug, tooling

#2761 xargs: added parallel proc flag -P
  pages/common/xargs.md
Labels: page edit

#2772 apt-get: add apt-get purge
  pages/linux/apt-get.md
Labels: page edit

#2760 rsync: add -r example with trailing backslash
  pages/common/rsync.md
Labels: page edit

#2759 virtualboxvm: add page
  pages/common/virtualboxvm.md
Labels: new command

#2775 ls,rm: remove trailing whitespace from filenames
  pages.it/common/ls.md
  pages.it/common/rm.md
Labels: bug, page edit

#2777 guake: add page
  pages/linux/guake.md
Labels: new command

#2718 mosquitto_sub: add page
  pages/common/mosquitto_sub.md
Labels: new command

#2719 mosquitto_pub: add page
  pages/common/mosquitto_pub.md
Labels: new command

#2784 npm-why: add page
  pages/common/npm-why.md
Labels: new command

#2785 yarn-why: add page
  pages/common/yarn-why.md
Labels: new command

#2779 sam: add page
  pages/linux/sam.md
Labels: new command

#2791 pathchk: move to pages/common
  pages/common/pathchk.md
Labels: page edit

#2781 vdir: add page
  pages/common/vdir.md
Labels: new command

#2783 type: add page
  pages/linux/type.md
Labels: new command

#2792 satis: add page
  pages/common/satis.md
Labels: new command

#2789 rbt: add page
  pages/common/rbt.md
Labels: new command

#2787 ned: add page
  pages/common/ned.md
Labels: new command

#2794 rails-generate: add page
  pages/common/rails-generate.md
Labels: new command

#2788 paccache: add page
  pages/linux/paccache.md
Labels: new command

#2801 Refactor: remove superfluous white spaces.
  pages/common/autossh.md
  pages/common/bedtools.md
  pages/common/gnomon.md
  pages/common/hangups.md
  pages/common/last.md
  pages/common/logname.md
  pages/common/nc.md
  pages/common/printenv.md
  pages/common/pyenv.md
  pages/common/route.md
  pages/common/virtualenv.md
  pages/common/visudo.md
  pages/common/xargs.md
  pages/linux/compose.md
  pages/linux/fallocate.md
  pages/linux/getent.md
  pages/linux/htop.md
  pages/linux/mkfs.exfat.md
  pages/linux/print.md
  pages/linux/run-mailcap.md
  pages/osx/nm.md
Labels: mass changes, page edit

#2714 youtube-dl: add example for the --format option
  pages/common/youtube-dl.md
Labels: page edit

#2800 exec: add page
  pages/common/exec.md
Labels: new command

#2798 wget : add some options
  pages/common/wget.md
Labels: page edit

#2807 nix-env: add example of showing installed packages
  pages/common/nix-env.md
Labels: page edit
