Repository tldr-pages/tldr, pull requests merged in 2019-06, with the labels that each got.

#3073 xclip: add PNG image copying example
  pages/linux/xclip.md
Labels: page edit

#3067 cpulimit: add page
  pages/linux/cpulimit.md
Labels: new command

#3065 meld: add page
  pages/common/meld.md
Labels: new command

#3072 vboxmanage: add page
  pages/linux/vboxmanage.md
Labels: new command

#3074 gpg2: Add page
  pages/common/gpg2.md
Labels: new command

#3077 git-stash: replace deprecated git stash save
  pages/common/git-stash.md
Labels: page edit

#3070 rails-db: add page
  pages/common/rails-db.md
Labels: new command

#2975 fselect: add page
  pages/common/fselect.md
Labels: new command

#3092 patch: correct and add examples
  pages/common/patch.md
Labels: bug, page edit

#3088 w3m: fix typo and add additional examples
  pages/common/w3m.md
Labels: page edit

#3090 git commit: add example for committing specific files
  pages/common/git-commit.md
Labels: page edit

#3079 home-manager: add page
  pages/common/home-manager.md
Labels: new command

#3084 git-cherry-pick: add example for -n option
  pages/common/git-cherry-pick.md
Labels: page edit

#3076 etckeeper: add page
  pages/linux/etckeeper.md
Labels: new command

#3062 docker container: add page
  pages/common/docker-containers.md
Labels: new command

#3061 docker images: add page
  pages/common/docker-images.md
Labels: new command

#3093 sshuttle: add exclude example
  pages/linux/sshuttle.md
Labels: page edit

#3091 pihole: add page
  pages/linux/pihole.md
Labels: new command

#3080 pacman4console: add page
  pages/linux/pacman4console.md
Labels: new command

#3082 fcrackzip: add page
  pages/linux/fcrackzip.md
Labels: new command

#3095 do-release-upgrade: add page
  pages/linux/do-release-upgrade.md
Labels: new command

#3098 snyk: add page
  pages/common/snyk.md
Labels: new command

#3097 sqlmap: fix user token typo
  pages/common/sqlmap.md
Labels: bug, page edit

#3101 deluge: add page
  pages/common/deluge.md
Labels: new command

#3104 hyperfine: fix typo
  pages/common/hyperfine.md
Labels: page edit

#3103 faketime: add page
  pages/linux/faketime.md
Labels: new command

#3105 roave-backward-compatibility-check: add page
  pages/common/roave-backward-compatibility-check.md
Labels: new command

#3106 remove outdated android clients
  README.md
Labels: clients

#3108 deluged: add page
  pages/common/deluged.md
Labels: new command

#3078 screen: add kill from inside a screen example
  pages/common/screen.md
Labels: page edit

#3107 cowsay: simplify example
  pages.it/common/cowsay.md
  pages/common/cowsay.md
Labels: page edit

#3109 deluged, deluge-console: clarify description
  pages/common/deluge-console.md
  pages/common/deluged.md
Labels: page edit

#3113 git-check-ignore: add page
  pages/common/git-check-ignore.md
Labels: new command

#3110 hsw-cli: add page
  pages/common/hsw-cli.md
Labels: new command

#3112 rector: add page
  pages/common/rector.md
Labels: new command

#3117 phpstorm: add page
  pages/common/phpstorm.md
Labels: new command

#3118 psysh: add page
  pages/common/psysh.md
Labels: new command

#3116 mycli: add page
  pages/common/mycli.md
Labels: new command

#3122 echo: add one more example
  pages/common/echo.md
Labels: page edit

#2996 calcurse: add pt-br translation
  pages.pt-BR/linux/calcurse.md
Labels: translation

#3124 find: various improvements
  pages/common/find.md
Labels: page edit

#3119 fstrim: add page
  pages/linux/fstrim.md
Labels: new command

#3120 qpdf: add merge files example
  pages/common/qpdf.md
Labels: page edit

#3130 kotlin: add page
  pages/common/kotlin.md
Labels: new command

#3123 phpspec: add page
  pages/common/phpspec.md
Labels: new command

#3132 gcloud: add auth login example
  pages/common/gcloud.md
Labels: page edit

#3127 parallel-lint: add page
  pages/common/parallel-lint.md
Labels: new command

#3140 docker-containers: fix typo
  pages/common/docker-containers.md
Labels: page edit

#3141 README: remove broken file count badge
  README.md
Labels: community, documentation

#3133 jigsaw: add page
  pages/common/jigsaw.md
Labels: new command

#3139 pigz: added folder compression method
  pages/common/pigz.md
Labels: page edit

#3142 cat: add French translation
  pages.fr/common/cat.md
Labels: translation

#3146 solo: add page
  pages/common/solo.md
Labels: new command

#3150 astyle: reword description
  pages.it/common/astyle.md
Labels: page edit

#3149 kops: add page
  pages/common/kops.md
Labels: new command

#3152 entr: move from linux to common platform
  pages/common/entr.md
Labels: page edit

#3151 git-revert: add page
  pages/common/git-revert.md
Labels: new command
