Repository tldr-pages/tldr, pull requests merged in 2020-09, with the labels that each got.

#4282 systemctl: add is-active and is-enabled examples
  pages/linux/systemctl.md
Labels: new command

#4312 fastboot: add getvar example
  pages/common/fastboot.md
Labels: page edit

#4311 adb-shell: add getprop example
  pages/common/adb-shell.md
Labels: page edit

#4294 apt-get: add autoclean example
  pages.pt_BR/linux/apt-get.md
  pages/linux/apt-get.md
Labels: page edit

#4300 btm: add page
  pages/common/btm.md
Labels: new command

#4305 e4defrag: fix grammar
  pages/linux/e4defrag.md
Labels: page edit

#4296 resize2fs: add page
  pages/linux/resize2fs.md
Labels: new command

#4303 xpdf: add page
  pages/common/xpdf.md
Labels: new command

#4281 meson: add page
  pages/common/meson.md
Labels: new command

#4313 carbon-now : add page
  pages/common/carbon-now.md
Labels: new command

#4297 tune2fs: add page
  pages/linux/tune2fs.md
Labels: new command

#4302 cargo-build: add page
  pages/common/cargo-build.md
  pages/common/cargo-test.md
Labels: new command

#4306 docker-ps: add page
  pages/common/docker-ps.md
Labels: new command

#4308 nodemon: add page
  pages/common/nodemon.md
Labels: new command

#4318 carbon-now: add zh translation
  pages.zh/common/carbon-now.md
Labels: translation

#4307 arecord: add page
  pages/linux/arecord.md
Labels: new command

#4315 flutter: add channel and run all example
  pages/common/flutter.md
Labels: page edit

#4265 git-send-email: add page
  pages/common/git-send-email.md
Labels: new command, waiting

#4323 ascii: add page
  pages/linux/ascii.md
Labels: new command

#4327 extundelete: add page
  pages/linux/extundelete.md
Labels: new command

#4310 docker-system: add page
  pages/common/docker-system.md
Labels: new command

#4309 recsel: add page
  pages/common/recsel.md
Labels: new command

#4320 rustc: add target, target-cpu and print examples
  pages/common/rustc.md
Labels: page edit

#4321 dotnet-publish: add page
  pages/common/dotnet-publish.md
Labels: new command

#4293 git-log: update examples
  pages/common/git-log.md
Labels: page edit

#4328 ansible-playbook: fix --tags example
  pages/common/ansible-playbook.md
Labels: page edit

#4317 delta: add page
  pages/common/delta.md
Labels: new command

#4331 env: add multi var set example
  pages/common/env.md
Labels: page edit

#4329 pdfinfo: add page
  pages/common/pdfinfo.md
Labels: new command

#4316 cargo-clippy: add page
  pages/common/cargo-clippy.md
Labels: new command

#4324 flameshot: added page
  pages/linux/flameshot.md
Labels: new command

#4330 k6: add js compatibility mode and response bodies
  pages/common/k6.md
Labels: page edit

#4334 aria2c: how to specify destination filename
  pages/common/aria2c.md
Labels: page edit

#4326 emulator: add page
  pages/common/adb-install.md
  pages/common/emulator.md
Labels: new command

#4342 tldr: add --update example
  pages/common/tldr.md
Labels: page edit

#4338 docker-start: add page
  pages/common/docker-start.md
Labels: new command

#4343 plutil: add page
  pages/osx/plutil.md
Labels: new command

#4292 nativefier, scc: add brazilian portuguese translation
  pages.pt_BR/common/nativefier.md
  pages.pt_BR/common/scc.md
Labels: translation

#4335 pdffonts: add page
  pages/common/pdffonts.md
Labels: new command

#4266 java: add debug info
  pages/common/java.md
Labels: page edit

#4333 virt-install, virt-sparsify: add page
  pages/common/virt-install.md
  pages/common/virt-sparsify.md
Labels: new command

#4332 tree: add -C, --du and --prune examples
  pages/linux/tree.md
Labels: page edit

#4347 brew: use the term "formulae" for consistency
  pages/osx/brew.md
Labels: page edit

#4339 docker-rmi: add page
  pages/common/docker-rmi.md
Labels: new command

#4349 Readme: add devhints.io under similar projects
  README.md
Labels: community, documentation

#4350 xip: add page
  pages/osx/xip.md
Labels: new command

#4336 cargo-rustc: add page
  pages/common/cargo-rustc.md
Labels: new command

#4346 tcpdump: fixed negation example
  pages/common/tcpdump.md
Labels: page edit

#4337 docker-inspect: add page
  pages/common/docker-inspect.md
Labels: new command

#4348 pdfseparate: add page
  pages/common/pdfseparate.md
Labels: new command

#4212 mono: add page
  pages/linux/mono.md
Labels: new command, waiting

#4351 mdbook: add page
  pages/common/vagrant.md
  pages/linux/mdbook.md
Labels: new command

#4314 chezmoi: add page
  pages/common/chezmoi.md
Labels: new command, waiting

#4340 dotnet-build: add page
  pages/common/dotnet-build.md
Labels: new command

#4360 laravel: update to cover newest installer
  pages/common/laravel.md
Labels: page edit

#4367 svgo: add -o to second example
  pages/common/svgo.md
Labels: page edit

#4366 colordiff: add page
  pages/common/colordiff.md
Labels: new command

#4369 rustfmt: add zh-cn translation
  pages.zh/common/rustfmt.md
Labels: translation

#4368 git: update main page
  pages/common/git.md
Labels: page edit

#4365 xephyr: add page
  pages/common/xephyr.md
Labels: new command

#4362 git-archive: add page
  pages/common/git-archive.md
Labels: new command

#4341 dotnet restore: add page
  pages/common/dotnet-restore.md
Labels: new command
