Repository tldr-pages/tldr, pull requests merged in 2020-08, with the labels that each got.

#4232 pass-otp: add page
  pages/common/pass-otp.md
Labels: new command

#4233 plantuml: fix space was missing
  pages/common/plantuml.md
Labels: page edit

#4231 duperemove: add page
  pages/linux/duperemove.md
Labels: new command

#4237 mysql: mention mysqldump in backup restore example
  pages/common/mysql.md
Labels: page edit

#4220 node: add --inspect-brk example
  pages/common/node.md
Labels: page edit

#4238 google-chrome: add page
  pages/linux/google-chrome.md
Labels: new command

#4236 pt_BR/curl: small tweaks to the main description
  pages.pt_BR/common/curl.md
Labels: translation

#4234 7z, ansible-playbook, ansible-vault, plantuml: add german translation
  pages.de/common/7z.md
  pages.de/common/ansible-playbook.md
  pages.de/common/ansible-vault.md
  pages.de/common/plantuml.md
Labels: translation

#4219 netselect: add page
  pages/linux/netselect.md
Labels: new command

#4244 Topgrade: add-page
  pages/common/topgrade.md
Labels: new command

#4240 r2e: add page
  pages/common/r2e.md
Labels: new command

#4249 git-add: fix typos
  pages.fr/common/git-add.md
Labels: page edit, translation

#4208 pkgutil: add --expand-full
  pages/osx/pkgutil.md
Labels: page edit

#4247 awslogs: add page
  pages/common/awslogs.md
Labels: new command

#4242 streamlink: add page
  pages/common/streamlink.md
Labels: new command

#4239 lvextend, lvreduce, lvresize: add page
  pages/linux/lvextend.md
  pages/linux/lvreduce.md
  pages/linux/lvresize.md
Labels: new command

#4241 git-request-pull: add page
  pages/common/git-request-pull.md
Labels: new command

#4257 jq: fix jq syntax error
  pages/common/jq.md
Labels: page edit

#4248 scc: add page
  pages/common/scc.md
Labels: new command

#4256 zip, unzip, gzip, tar: add brazilian portuguese translation
  pages.pt_BR/common/gzip.md
  pages.pt_BR/common/tar.md
  pages.pt_BR/common/unzip.md
  pages.pt_BR/common/zip.md
Labels: translation

#4252 git-apply: add page
  pages/common/git-apply.md
Labels: new command

#4254 glab: add page
  pages/common/glab.md
Labels: new command

#4255 eix: add page
  pages/linux/eix.md
Labels: new command

#4260 zip (pt_BR): fix example
  pages.pt_BR/common/zip.md
Labels: translation

#4259 xcaddy: add page
  pages/common/xcaddy.md
Labels: new command

#4096 grep: regexp is used by default
  pages/common/grep.md
Labels: page edit

#4262 netselect-apt: add page
  pages/linux/netselect-apt.md
Labels: new command

#4278 konsole: add page
  pages/linux/konsole.md
Labels: new command

#4277 ksvgtopng5: add page
  pages/linux/ksvgtopng5.md
Labels: new command

#4261 nativefier: add page
  pages/common/nativefier.md
Labels: new command

#4279 inkscape: fix obsolete option, add -D example
  pages/common/inkscape.md
Labels: page edit

#4270 CONTRIBUTING: Include homepage in example
  CONTRIBUTING.md
Labels: community

#4280 ark: add page
  pages/linux/ark.md
Labels: new command

#4284 cf: add page
  pages/common/cf.md
Labels: new command

#4285 expose: add page
  pages/common/expose.md
Labels: new command

#4299 jq: correct description of example
  pages/common/jq.md
Labels: page edit

#4286 adb-install: add page
  pages/common/adb-install.md
Labels: new command

#4295 tree: add -C example
  pages/osx/tree.md
Labels: page edit

#4268 cargo-test: add page
  pages/common/cargo-test.md
Labels: new command

#4289 bitwise: add page
  pages/linux/bitwise.md
Labels: new command

#4288 adb-reverse: add page
  pages/common/adb-reverse.md
Labels: new command

#4287 adb-shell: add page
  pages/common/adb-shell.md
Labels: new command

#4298 e4defrag: add page
  pages/linux/e4defrag.md
Labels: new command

#4301 jekyll: add serve --verbose and clean examples
  pages/common/jekyll.md
Labels: page edit

#4283 bpytop: add page
  pages/linux/bpytop.md
Labels: new command
