Repository tldr-pages/tldr, pull requests merged in 2020-05, with the labels that each got.

#4010 virtualenvwrapper: add page
  pages/common/virtualenvwrapper.md
Labels: new command

#3980 ssh-keyscan: add known_hosts example
  pages/common/ssh-keyscan.md
Labels: page edit

#4000 at: add notify-send example
  pages/linux/at.md
Labels: page edit

#4012 git-subtree: add page
  pages/common/git-subtree.md
Labels: new command

#4027 apport-bug: add page
  pages/linux/apport-bug.md
Labels: new command

#4023 tea: add page
  pages/common/tea.md
Labels: new command

#4030 spfquery: add page
  pages/common/spfquery.md
Labels: new command

#4019 git-help: add page
  common/pages/git-help.md
Labels: new command

#4018 git-repack: add page
  pages/common/git-repack.md
Labels: new command

#4025 Add subcommand section to contributing guidelines
  CONTRIBUTING.md
Labels: documentation

#4029 vlc: add page
  pages/common/vlc.md
Labels: new command

#4017 git-instaweb: add page
  pages/common/git-instaweb.md
Labels: new command

#3990 john: apply suggestions
  pages/common/john.md
Labels: page edit

#4015 rsync: add French translation
  pages.fr/common/rsync.md
Labels: translation

#4016 git-show-branch: add page
  pages/common/git-show-branch.md
Labels: new command

#4033 icalbuddy: add page
  pages/osx/icalbuddy.md
Labels: new command

#4007 ack: add regex, single file search examples
  pages/common/ack.md
Labels: page edit

#3788 efibootmgr: add page
  pages/linux/efibootbgr.md
Labels: new command

#4039 readme: add ExTldr client
  README.md
Labels: clients

#4038 wmctrl: add page
  pages/linux/wmctrl.md
Labels: new command

#4040 plantuml: add page
  pages/common/plantuml.md
Labels: new command

#4034 git-help: fix location
  pages/common/git-help.md
Labels: page edit

#4024 dos2unix/unix2dos: add pages
  pages/linux/dos2unix.md
  pages/linux/mac2unix.md
  pages/linux/unix2dos.md
  pages/linux/unix2mac.md
Labels: new command

#4042 git notes: add page
  pages/common/git-notes.md
Labels: new command

#4041 unshadow: add page
  pages/linux/unshadow.md
Labels: new command

#4021 whence: add page
  pages/osx/whence.md
Labels: new command

#4022 debchange, debuild, dget, quilt: add pages
  pages/common/quilt.md
  pages/linux/debchange.md
  pages/linux/debuild.md
  pages/linux/dget.md
Labels: new command

#4045 pkg-config: add page
  pages/linux/pkg-config.md
Labels: new command

#4047 jhipster: add page
  pages/common/jhipster.md
Labels: new command

#4048 vlc: add --loop example
  pages/common/vlc.md
Labels: page edit

#4036 identify: add page
  pages/common/identify.md
Labels: new command

#4054 docker-run: add page
  pages/common/docker-run.md
Labels: new command

#4053 apktool: add page
  pages/common/apktool.md
Labels: new command

#4055 adguardhome: add page
  pages/common/adguardhome.md
Labels: new command

#4059 Change all occurrences of file_name to filename
  contributing-guides/style-guide.md
  pages/common/figlet.md
  pages/common/git-checkout.md
  pages/common/ignite.md
  pages/common/odps-resource.md
  pages/common/p4.md
  pages/common/sc-im.md
  pages/common/terminalizer.md
  pages/common/trash-cli.md
  pages/linux/dpkg.md
  pages/linux/toilet.md
  pages/linux/tshark.md
  pages/linux/uvcdynctrl.md
  pages/osx/mkfile.md
Labels: mass changes, page edit, syntax

#4062 julia: add -E example, fix link
  pages/common/julia.md
Labels: page edit

#4071 Update ls.md by adding ls -F
  pages/common/ls.md
Labels: page edit

#4065 nvidia-smi: add page
  pages/common/nvidia-smi.md
Labels: new command

#4066 django-admin: add page
  pages/common/django-admin.md
Labels: new command

#4061 watchexec: add page
  pages/common/watchexec.md
Labels: new command

#4072 jupytext: add page
  pages/common/jupytext.md
Labels: new command

#4076 sdk: fix documentation URL
  pages/common/sdk.md
Labels: page edit

#4077 sdkmanager: add page
  pages/common/sdkmanager.md
Labels: new command

#4050 openssl-genrsa: add page
  pages/common/openssl-genrsa.md
Labels: new command

#4073 trash: fix token syntax
  pages/linux/trash.md
Labels: page edit

#4063 dnf: add and reorder examples
  pages/linux/dnf.md
Labels: page edit

#4067 wc: add pipe example
  pages/common/wc.md
Labels: page edit
