Repository tldr-pages/tldr, pull requests merged in 2020-12, with the labels that each got.

#4997 dkms: add page
  pages/linux/dkms.md
Labels: new command

#5000 mc, jekyll, echo: add French translation and fix formatting in English version
  pages.fr/common/echo.md
  pages.fr/common/jekyll.md
  pages.fr/common/mc.md
  pages/common/jekyll.md
  pages/common/mc.md
Labels: page edit, translation

#4705 zmv: add page
  pages/common/zmv.md
Labels: hacktoberfest-accepted, new command

#5001 apt*, dotnet*: add Spanish translation
  pages.es/common/dotnet-build.md
  pages.es/common/dotnet-publish.md
  pages.es/common/dotnet-restore.md
  pages.es/common/dotnet.md
  pages.es/linux/apt-cache.md
  pages.es/linux/apt-file.md
  pages.es/linux/apt-get.md
  pages.es/linux/apt-key.md
  pages.es/linux/apt.md
  pages.es/linux/brew.md
  pages.es/linux/clamav.md
  pages.es/linux/cmus.md
  pages.es/linux/conky.md
  pages.es/linux/dmesg.md
  pages.es/linux/line.md
  pages.es/linux/lsb_release.md
  pages.es/linux/lsmod.md
Labels: translation

#4992 exenv: add page
  pages/common/exenv.md
Labels: new command

#4982 resolveip: add page
  pages/linux/resolveip.md
Labels: new command

#4422 openssl-prime: add page
  pages/common/openssl-genrsa.md
  pages/common/openssl-prime.md
Labels: new command, page edit

#4999 fisher: update page to comply with Fisher 4.0
  pages/common/fisher.md
Labels: page edit

#4815 lynx: add page
  pages/common/lynx.md
Labels: hacktoberfest-accepted, new command

#5012 htop: move from linux to common
  pages/common/htop.md
Labels: page edit

#5003 README: add keypirinha client
  README.md
Labels: community

#4978 flow: add page
  pages/common/flow.md
Labels: new command

#4993 pdf script: format & add datetime
  scripts/pdf/basic.css
  scripts/pdf/render.py
Labels: tooling

#5009 add sahilister in repo collaborators in MAINTAINERS.md
  MAINTAINERS.md
Labels: community

#4961 parted: add page
  pages/linux/parted.md
Labels: new command

#5020 flutter: fix example typo
  pages/common/flutter.md
Labels: page edit

#5004 *: fix typos
  pages/common/emulator.md
  pages/common/fgrep.md
  pages/common/git-lfs.md
  pages/common/git-prune.md
  pages/common/git-shortlog.md
  pages/common/iverilog.md
  pages/common/jhipster.md
  pages/common/kops.md
  pages/common/lzop.md
  pages/common/mr.md
  pages/common/nmap.md
  pages/common/pipx.md
  pages/common/reflac.md
  pages/common/scheme.md
  pages/common/thunderbird.md
  pages/common/twm.md
  pages/linux/cewl.md
  pages/linux/e2image.md
  pages/linux/guake.md
  pages/linux/htpdate.md
  pages/linux/isosize.md
  pages/linux/lastcomm.md
  pages/linux/lvextend.md
  pages/linux/lvresize.md
  pages/linux/medusa.md
  pages/linux/openfortivpn.md
  pages/linux/opkg.md
  pages/linux/rtcwake.md
  pages/linux/vipw.md
  pages/linux/x11vnc.md
  pages/osx/GetFileInfo.md
  pages/osx/whatis.md
Labels: mass changes, page edit

#5006 etcdctl: add page
  pages/common/etcdctl.md
Labels: new command

#5019 fd: add --exec
  pages/common/fd.md
Labels: page edit

#5022 redis-cli: add new argument -c
  pages/common/redis-cli.md
Labels: page edit

#5011 from: add page
  pages/common/from.md
Labels: new command

#5008 conan: add page
  pages/common/conan.md
Labels: new command

#5021 bg, fg, jobs: add a '%' before '{{job_id}}'
  pages.ko/common/bg.md
  pages.zh/common/bg.md
  pages/common/bg.md
  pages/common/fg.md
  pages/common/jobs.md
Labels: page edit

#5016 brotli: add page
  pages/common/brotli.md
Labels: new command

#5007 etcd: add page
  pages/common/etcd.md
Labels: new command

#5015 2to3: add page
  pages/common/2to3.md
Labels: new command

#5024 MAINTAINERS: add navarroaxel
  MAINTAINERS.md
Labels: community

#5014 slapt-src, spi: add page, slapt-get: fix example
  pages/linux/slapt-get.md
  pages/linux/slapt-src.md
  pages/linux/spi.md
Labels: new command

#4968 vimdiff: cleanup and update page
  pages/common/vimdiff.md
Labels: page edit

#5029 nmap: add Italian translation
  pages.it/common/nmap.md
Labels: translation

#5027 scp: add -P example
  pages/common/scp.md
Labels: page edit

#5026 tmpmail: add page
  pages/common/tmpmail.md
Labels: new command

#4959 mixxx: add common page
  pages/common/mixxx.md
Labels: new command

#5017 topydo: add page
  pages/common/topydo.md
Labels: new command

#5032 kubectl: add kubectl describe in header
  pages/common/kubectl.md
Labels: page edit

#5033 security: add page
  pages/osx/security.md
Labels: new command

#5025 tuir: add page
  pages/common/tuir.md
Labels: new command

#5039 lsblk: add custom output example
  pages/linux/lsblk.md
Labels: page edit

#4980 clj: add page
  pages/common/clj.md
Labels: new command

#5045 Improve role change message templates
  COMMUNITY-ROLES.md
Labels: community, documentation

#5052 openssl-req: fix typo in example description
  pages/common/openssl-req.md
Labels: page edit

#5041 direnv: fix direnv edit example
  pages/common/direnv.md
Labels: page edit

#4976 kde-inhibit: add page
  pages/linux/kde-inhibit.md
Labels: new command

#5054 tmutil: add page
  pages/osx/tmutil.md
Labels: new command

#5034 fastlane: add page
  pages/common/fastlane.md
Labels: new command

#4983 pip-install: add page
  pages/common/pip-install.md
  pages/common/pip.md
Labels: new command, page edit

#5051 clj: add pt_BR translation
  pages.pt_BR/common/clj.md
Labels: translation

#5042 README: add kb to similar projects
  README.md
Labels: community
