Repository tldr-pages/tldr, pull requests merged in 2020-02, with the labels that each got.

#3808 wapm: add page
  pages/common/wapm.md
Labels: new command

#3819 docker-machine : Add Korean Translation
  pages.ko/common/docker-machine.md
Labels: translation

#3829 docker : Add Korean Translation
  pages.ko/common/docker.md
Labels: translation

#3832 poetry: add page
  pages/common/poetry.md
Labels: new command

#3824 pdftocairo: add page
  pages/common/pdftocairo.md
Labels: new command

#3786 fls: add page
  pages/common/fls.md
Labels: new command

#3830 README: properly format Dash docset instructions
  README.md
Labels: documentation

#3833 initdb: Add new page for initdb
  pages/common/initdb.md
Labels: new command

#3828 mullvad: improve an example's wording
  pages/linux/mullvad.md
Labels: page edit

#3827 jar: add 'cf' example
  pages/common/jar.md
Labels: page edit

#3823 QREncode: add print to terminal examples
  pages/common/qrencode.md
Labels: page edit

#3826 xcode-select: add page
  pages/osx/xcode-select.md
Labels: new command

#3831 yabai: add page
  pages/osx/yabai.md
Labels: new command

#3804 progress: add page
  pages/linux/progress.md
Labels: new command

#3802 rsync: add -rauL option
  pages/common/rsync.md
Labels: page edit

#3843 ebook-convert: add TOC example
  pages/common/ebook-convert.md
Labels: page edit

#3842 pyenv-virtualenv: add activate/deactivate examples
  pages/common/pyenv-virtualenv.md
Labels: page edit

#3844 tac: add stdin example
  pages/common/tac.md
Labels: page edit

#3841 multiple pages: change user_name to username
  pages.pt_BR/linux/top.md
  pages/common/gist.md
  pages/common/htpasswd.md
  pages/common/last.md
  pages/common/odps-auth.md
  pages/common/sendmail.md
  pages/linux/chage.md
  pages/linux/htop.md
  pages/linux/smbpasswd.md
  pages/linux/top.md
Labels: mass changes, page edit

#3837 tree: ignore specific directories
  pages/linux/tree.md
  pages/osx/tree.md
Labels: page edit

#3810 enum4linux: add page
  pages/linux/enum4linux.md
Labels: new command

#3846 multiple pages: rephrase without adjectives
  pages/common/ag.md
  pages/common/bmaptool.md
  pages/common/bup.md
  pages/common/restic.md
  pages/common/zola.md
Labels: page edit

#3806 Tmux improvements
  pages/common/tmux.md
Labels: page edit

#3850 findfs: add page
  pages/linux/findfs.md
Labels: new command

#3853 dot : Add Korean Translation
  pages.ko/common/dot.md
Labels: translation

#3855 ls: fix typo
  pages.fr/common/ls.md
Labels: page edit

#3856 calibredb: add example
  pages/common/calibredb.md
Labels: page edit

#3854 gh: add page
  pages/common/gh.md
Labels: new command

#3861 sequelize: add page
  pages/common/sequelize.md
Labels: new command

#3851 dstat: add page
  pages/linux/dstat.md
Labels: new command

#3848 awk: simplify loop/fix missing filename
  pages/common/awk.md
Labels: page edit

#3857 jdupes: add page
  pages/common/jdupes.md
Labels: new command

#3849 tcptraceroute: add page
  pages/linux/tcptraceroute.md
Labels: new command

#3852 ctags: add page
  pages/common/ctags.md
Labels: new command

#3869 passwd: add base command
  pages/common/passwd.md
Labels: page edit

#3872 snap: add update package
  pages/linux/snap.md
Labels: page edit

#3878 dotnet : Add Korean Translation
  pages.ko/common/dotnet.md
Labels: translation

#3871 vault: add command
  pages/common/vault.md
Labels: page edit

#3882 powertop: add page
  pages/linux/powertop.md
Labels: new command

#3870 zramctl: improve module loading examples
  pages/linux/zramctl.md
Labels: page edit

#3880 middleman: add page
  pages/common/middleman.md
Labels: new command
