Repository tldr-pages/tldr, pull requests merged in 2020-03, with the labels that each got.

#3874 reflac: add page
  pages/common/reflac.md
Labels: new command

#3879 fin: add page
  pages/common/fin.md
Labels: new command

#3835 mysqldump: harmonize the examples
  pages/common/mysqldump.md
Labels: page edit

#3815 firewall-cmd: add zone change and arbitrary ports
  pages/linux/firewall-cmd.md
Labels: page edit

#3875 postfix: add page
  pages/linux/postfix.md
Labels: new command

#3866 wormhole: add page
  pages/common/wormhole.md
Labels: new command

#3891 prstat: fix casing
  pages/sunos/prstat.md
Labels: page edit

#3890 vmstat: add page
  pages/linux/vmstat.md
Labels: new command

#3888 packer: add packer to tldr
  pages/common/packer.md
Labels: new command

#3816 nmcli: add more server examples
  pages/linux/nmcli-connection.md
  pages/linux/nmcli-device.md
  pages/linux/nmcli.md
Labels: page edit

#3884 git-lfs: add fetch and checkout subcommands
  pages/common/git-lfs.md
Labels: page edit

#3895 godot: update the `--export` example
  pages/common/godot.md
Labels: page edit

#3898 laravel-zero: add page
  pages/common/laravel-zero.md
Labels: new command

#3900 Update Travis CI to run on Bionic Beaver
  .travis.yml
Labels: tooling

#3899 medusa: add page
  pages/linux/medusa.md
Labels: new command

#3903 df: fix typo
  pages.fr/common/df.md
Labels: page edit, translation

#3904 uncrustify: add page
  pages/common/uncrustify.md
Labels: new command

#3901 kaggle: add page
  pages/common/kaggle.md
Labels: new command

#3894 deno: add page
  pages/common/deno.md
Labels: new command

#3911 git-update-index: add page
  pages/common/git-update-index.md
Labels: new command

#3908 sed: minor syntax fix
  pages.zh/osx/sed.md
  pages/osx/sed.md
Labels: page edit

#3907 ssh-agent: add page
  pages/common/ssh-agent.md
Labels: new command

#3922 rails-routes: add page
  pages/common/rails-routes.md
Labels: new command

#3910 trash: add trash-rm examples
  pages/linux/trash.md
Labels: page edit

#3923 mktorrent: add page
  pages/common/mktorrent.md
Labels: new command

#3916 transmission-create: add page
  pages/common/transmission-create.md
Labels: new command

#3926 obs: add page
  pages/common/obs.md
Labels: new command

#3915 hdparm: add page
  pages/linux/hdparm.md
Labels: new command

#3917 croc: add page
  pages/common/croc.md
Labels: new command

#3925 zoxide: add page
  pages/common/zoxide.md
Labels: new command

#3859 Tar: Add extraction of file without folder structure
  pages/common/tar.md
Labels: page edit

#3927 vmstat: update page
  pages/linux/vmstat.md
Labels: page edit

#3928 brew: add leaves command
  pages/osx/brew.md
Labels: page edit

#3929 qpdf: fix merge documentation
  pages/common/qpdf.md
Labels: page edit

#3931 sensors: add page
  pages/linux/sensors.md
Labels: new command

#3935 go: add go modules
  pages/common/go.md
Labels: page edit

#3930 ip address: add page
  pages/linux/ip-address.md
Labels: new command

#3941 terraform: add fmt
  pages/common/terraform.md
Labels: page edit

#3942 Create FUNDING.yml
  FUNDING.yml
Labels: community

#3936 xbps: update page
  pages/linux/xbps.md
Labels: page edit

#3939 doas: add page
  pages/common/doas.md
Labels: new command

#3902 Add date RFC 3339
  pages/common/date.md
Labels: page edit

#3937 tcptraceroute: better wording
  pages/linux/tcptraceroute.md
Labels: page edit

#3947 git-mergetool: add page
  pages/common/git-mergetool.md
Labels: new command

#3949 dirsearch: add page
  pages/common/dirsearch.md
Labels: new command
