Repository tldr-pages/tldr, pull requests merged in 2020-01, with the labels that each got.

#3720 cpdf: applying tokens and fix more information label
  pages/common/cpdf.md
Labels: page edit

#3722 bison: add page
  pages/common/bison.md
Labels: new command

#3723 Update the OS list in README
  README.md
Labels: documentation

#3728 git-show: add example for --stat option
  pages/common/git-show.md
Labels: page edit

#3729 diffstat : Add Korean Translation
  pages.ko/common/diffstat.md
Labels: translation

#3721 cheat: add page
  pages/common/cheat.md
Labels: new command

#3717 cpdf: add Spanish translation
  pages.es/common/cpdf.md
Labels: translation

#3730 README: OSX -> macOS
  README.md
Labels: documentation

#3732 tar: add French translation
  pages.fr/common/tar.md
Labels: translation

#3735 dircolors : Add Korean Translation
  pages.ko/common/dircolors.md
Labels: translation

#3731 dig : Add Korean Translation
  pages.ko/common/dig.md
Labels: translation

#3709 cd: add Spanish translation
  pages.es/common/cd.md
Labels: translation

#3733 Create package-lock.json
  package-lock.json
Labels: tooling

#3719 dcfldd: add page
  pages/common/dcfldd.md
Labels: new command

#3361 top: add Brazilian Portuguese translation
  pages.pt_BR/linux/top.md
Labels: translation

#3741 dirname : Add Korean Translation
  pages.ko/common/dirname.md
Labels: translation

#3745 dirs : Add Korean Translation
  pages.ko/common/dirs.md
Labels: translation

#3740 README: add new web client
  README.md
Labels: documentation

#3734 Add extra installation instructions to clients which OS packaged versions
  README.md
Labels: documentation

#3739 numlockx: add page
  pages/linux/numlockx.md
Labels: new command

#3737 Add organization member: @ivanhercaz
  MAINTAINERS.md
Labels: community

#3744 top: update page
  pages/linux/top.md
Labels: page edit

#3748 chmod: remove all rights
  pages/common/chmod.md
Labels: page edit

#3751 dive : Add Korean Translation
  pages.ko/common/dive.md
Labels: translation

#3750 Add organization member: @einverne
  MAINTAINERS.md
Labels: community

#3749 README: fix the link to cheat's repository
  README.md
Labels: documentation

#3754 Fix tldr-bot messages
  scripts/send-to-bot.py
Labels: bug, tooling

#3279 ansible-vault: add page
  pages/common/ansible-vault.md
Labels: new command

#3757 docker-compose : Add Korean Translation
  pages.ko/common/docker-compose.md
Labels: translation

#3758 dcfldd: improve an example
  pages/common/dcfldd.md
Labels: page edit

#3747 badblocks: add more examples
  pages/common/badblocks.md
Labels: page edit

#3759 grep: add French translation (revived)
  pages.fr/common/grep.md
Labels: translation

#3760 docker-containers : Add Korean Translation
  pages.ko/common/docker-containers.md
Labels: translation

#3761 ab, ack: add Tamil translation (revived)
  pages.ta/common/ab.md
  pages.ta/common/ack.md
Labels: translation

#3762 tmux: add Spanish translation
  pages.es/common/tmux.md
Labels: translation

#3765 docker-images : Add Korean Translation
  pages.ko/common/docker-images.md
Labels: translation

#3768 maintainers: add surnames to @ivanhercaz
  MAINTAINERS.md
Labels: community

#3766 Add organization member: @schneiderl
  MAINTAINERS.md
Labels: community

#3769 qr: add page
  pages/common/qr.md
Labels: new command

#3755 pkgutil: add page (osx)
  pages/osx/pkgutil.md
Labels: new command

#3772 docker-logs : Add Korean Translation
  pages.ko/common/docker-logs.md
Labels: translation

#3778 git-add: add git add interactively for all changed files
  pages/common/git-add.md
Labels: page edit

#3784 git-switch: switch to previous branch
  pages/common/git-switch.md
Labels: page edit

#3780 emacs: open file at line number
  pages/common/emacs.md
Labels: page edit

#3785 atom: wait for git commit editor
  pages/common/atom.md
Labels: page edit

#3793 mullvad: add page
  pages/linux/mullvad.md
Labels: new command

#3789 iwconfig: add page
  pages/linux/iwconfig.md
Labels: new command

#3799 multiple pages: add missing periods
  pages.de/common/cat.md
  pages.de/common/whoami.md
Labels: page edit

#3790 youtube-dl: add download the best audio+video
  pages/common/youtube-dl.md
Labels: page edit

#3794 secrethub: add page
  pages/common/secrethub.md
Labels: new command

#3800 openrc, rc-status, rc-service, rc-update: add pages
  pages/linux/openrc.md
  pages/linux/rc-service.md
  pages/linux/rc-status.md
  pages/linux/rc-update.md
Labels: new command

#3797 tldr: change "linux" to "Linux"
  pages/common/tldr.md
Labels: page edit

#3791 lzop: add page
  pages/common/lzop.md
Labels: new command

#3805 ab: add POST request example
  pages/common/ab.md
Labels: page edit

#3657 Rework npm configuration
  package.json
Labels: decision, tooling

#3817 pg_ctl: clean up command list
  pages/common/pg_ctl.md
Labels: page edit

#3798 tldr: add hbs translation
  pages.hbs/common/tldr.md
Labels: translation

#3771 Update nano.md
  pages/common/nano.md
Labels: page edit

#3814 zstd: reworded a sentence (as discussed in PR #3791)
  pages/common/zstd.md
Labels: page edit

#3783 vim: helpful additions
  pages/common/vim.md
Labels: page edit

#3812 mmls: add page
  pages/common/mmls.md
Labels: new command

#3813 p7zip: add page
  pages/common/p7zip.md
Labels: new command

#3822 wrk: fix typo
  pages/common/wrk.md
Labels: page edit

#3775 git flow: add page
  pages/common/git-flow.md
Labels: new command
