Repository tldr-pages/tldr, pull requests merged in 2021-11, with the labels that each got.

#7346 pkginfo: add more information link
  pages/linux/pkginfo.md
Labels: page edit, hacktoberfest-accepted, review needed

#7284 fc, pwd: add examples
  pages/common/fc.md
  pages/common/pwd.md
Labels: page edit, hacktoberfest-accepted

#7233 zegrep: add page
  pages/linux/zegrep.md
Labels: new command, hacktoberfest-accepted

#7300 pass: add git command example
  pages/common/pass.md
Labels: page edit, hacktoberfest-accepted, review needed

#7230 common-arguments.md: add zh and zh_TW translation
  contributing-guides/translation-templates/common-arguments.md
Labels: documentation, hacktoberfest-accepted, review needed

#7058 am, bugreport, bugreportz, cmd: add pt_BR translation
  pages.pt_BR/android/am.md
  pages.pt_BR/android/bugreport.md
  pages.pt_BR/android/bugreportz.md
  pages.pt_BR/android/cmd.md
Labels: translation, hacktoberfest-accepted, review needed

#7271 diff: add Turkish translation
  pages.tr/common/diff.md
Labels: translation, hacktoberfest-accepted, review needed

#7339 apropos: fix German translation
  pages.de/common/apropos.md
Labels: translation, hacktoberfest-accepted, review needed

#7260 u3d: add page
  pages/common/u3d.md
Labels: new command, hacktoberfest-accepted, review needed

#7320 shutdown: add Italian translation
  pages.it/linux/shutdown.md
Labels: translation, hacktoberfest-accepted, review needed

#7315 powerprofilesctl: add page
  pages/linux/powerprofilesctl.md
Labels: new command, hacktoberfest-accepted, review needed

#7316 neofetch: add pt_BR translation
  pages.pt_BR/common/neofetch.md
Labels: translation, hacktoberfest-accepted, review needed

#7340 exit: add German translation
  pages.de/common/exit.md
Labels: translation, hacktoberfest-accepted, review needed

#7217 todo: add Italian translation
  pages.it/common/todo.md
Labels: translation, hacktoberfest-accepted

#7331 brew-cask: add German translation
  pages.de/common/brew-cask.md
Labels: translation, hacktoberfest-accepted, review needed

#7254 xrandr: add German translation
  pages.de/linux/xrandr.md
Labels: translation, hacktoberfest-accepted, review needed

#7202 add-apt-repository: add German translation
  pages.de/linux/add-apt-repository.md
Labels: translation, hacktoberfest-accepted, review needed

#7348 nmtui: add more information link
  pages/linux/nmtui.md
Labels: page edit, hacktoberfest-accepted, review needed

#7358 java: add classpath example and update link
  pages/common/java.md
Labels: page edit, hacktoberfest-accepted

#7366 set-more-info-link.py: improve Tamil translation
  scripts/set-more-info-link.py
Labels: tooling, translation, review needed

#7298 color: add German translation
  pages.de/windows/color.md
Labels: translation, hacktoberfest-accepted, review needed

#7309 bg: add Nepali translation
  pages.ne/common/bg.md
Labels: translation, hacktoberfest-accepted, review needed

#7297 emacs: add pt_BR translation
  pages.pt_BR/common/emacs.md
Labels: translation, hacktoberfest-accepted, review needed

#7232 clang-tidy: add page
  pages/common/clang-tidy.md
Labels: new command, hacktoberfest-accepted, review needed

#6556 ISSUE_TEMPLATE, PULL_REQUEST_TEMPLATE: refresh
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#7179 fprintd-list: add page
  pages/linux/fprintd-list.md
Labels: new command, hacktoberfest-accepted

#7181 fprintd-enroll: add page
  pages/linux/fprintd-enroll.md
Labels: new command, hacktoberfest-accepted, review needed

#7227 set-more-info-link: fix Turkish translation
  scripts/set-more-info-link.py
Labels: tooling, translation, hacktoberfest-accepted

#7154 textql: add page
  pages/common/textql.md
Labels: new command, hacktoberfest-accepted

#7279 handbrakecli: add rip DVD examples; use long arguments
  pages/common/handbrakecli.md
Labels: page edit, hacktoberfest-accepted

#7029 rtl_sdr: add page
  pages/common/rtl_sdr.md
Labels: new command, hacktoberfest-accepted

#7166 nixos-option: add page
  pages/linux/nixos-option.md
Labels: new command, hacktoberfest-accepted

#7204 qemu-img: specify format flag
  pages/common/qemu-img.md
Labels: page edit, hacktoberfest-accepted, review needed

#7159 apt: add pt_PT translation
  pages.pt_PT/linux/apt.md
Labels: translation, hacktoberfest-accepted, review needed

#7333 arch: add Chinese translation
  pages.zh/osx/arch.md
Labels: architecture, hacktoberfest-accepted, review needed

#7342 cp: add Polish translation
  pages.pl/common/cp.md
Labels: translation, hacktoberfest-accepted

#7290 google-chrome, ipcalc, nologin, nordvpn, numlockx, see: add German translation
  pages.de/linux/google-chrome.md
  pages.de/linux/ipcalc.md
  pages.de/linux/nologin.md
  pages.de/linux/nordvpn.md
  pages.de/linux/numlockx.md
  pages.de/linux/see.md
Labels: translation, hacktoberfest-accepted, review needed

#7369 unalias: add Chinese translation
  pages.zh/common/unalias.md
Labels: translation

#7277 zip: add Chinese translation
  pages.zh/common/zip.md
Labels: translation, hacktoberfest-accepted

#7264 kiwi-ng: add page
  pages/common/kiwi-ng.md
Labels: new command, hacktoberfest-accepted

#7368 osascript, xattr, pmset, say, screencapture: add link
  pages.zh/osx/osascript.md
  pages.zh/osx/pmset.md
  pages.zh/osx/say.md
  pages.zh/osx/xattr.md
  pages/osx/osascript.md
  pages/osx/pmset.md
  pages/osx/say.md
  pages/osx/screencapture.md
  pages/osx/xattr.md
Labels: page edit

#7321 shasum: add more information link
  pages/common/shasum.md
Labels: page edit, hacktoberfest-accepted, review needed

#7263 wsl: add German translation
  pages.de/windows/wsl.md
Labels: translation, hacktoberfest-accepted

#7210 reset, sensible-browser, sensors, ...: add Spanish translation
  pages.es/linux/reset.md
  pages.es/linux/sensible-browser.md
  pages.es/linux/sensors.md
  pages.es/linux/tcpflow.md
Labels: translation, hacktoberfest-accepted, review needed

#7278 newgrp, pkgadd, tcpkill, xfreerdp: add Spanish translation
  pages.es/linux/newgrp.md
  pages.es/linux/pkgadd.md
  pages.es/linux/tcpkill.md
  pages.es/linux/xfreerdp.md
Labels: translation, hacktoberfest-accepted, review needed

#7310 cpuid: add Spanish translation
  pages.es/linux/cpuid.md
Labels: translation, hacktoberfest-accepted, review needed

#7314 vmstat: add Spanish translation
  pages.es/linux/vmstat.md
Labels: translation, hacktoberfest-accepted, review needed

#7373 shopt: add more information link
  pages/common/shopt.md
Labels: page edit, review needed

#7323 phpdismod: add more information link
  pages/linux/phpdismod.md
Labels: page edit, hacktoberfest-accepted, review needed

#7324 phpenmod: add more information link
  pages/linux/phpenmod.md
Labels: page edit, hacktoberfest-accepted, review needed

#7185 python: update deprecated script/file path
  pages/common/python.md
Labels: page edit, hacktoberfest-accepted, review needed

#7352 zypper: add German translation
  pages.de/linux/zypper.md
Labels: translation, hacktoberfest-accepted, review needed

#7345 powertop: add more information link
  pages/linux/powertop.md
Labels: page edit, hacktoberfest-accepted, review needed

#7322 phar: add more information link
  pages/linux/phar.md
Labels: page edit, hacktoberfest-accepted, review needed

#7313 ufw: add Spanish translation
  pages.es/linux/ufw.md
Labels: translation, hacktoberfest-accepted, review needed

#7311 service: add Spanish translation
  pages.es/linux/service.md
Labels: translation, hacktoberfest-accepted, review needed

#7332 flatpak: update Chinese translation
  pages.zh/linux/flatpak.md
Labels: translation, hacktoberfest-accepted, review needed

#7334 sw_vers: update Chinese translation
  pages.zh/osx/sw_vers.md
Labels: translation, hacktoberfest-accepted, review needed

#7335 pmset: update Chinese translation
  pages.zh/osx/pmset.md
Labels: translation, hacktoberfest-accepted, review needed

#7343 chown: add Polish translation
  pages.pl/common/chown.md
Labels: translation, hacktoberfest-accepted, review needed

#7344 basename: add Polish translation
  pages.pl/common/basename.md
Labels: translation, hacktoberfest-accepted, review needed

#7341 export: add German translation
  pages.de/common/export.md
Labels: translation, hacktoberfest-accepted

#7377 common-argumens: add Polish translation
  contributing-guides/translation-templates/common-arguments.md
Labels: documentation, translation, review needed

#7370 alias-pages: fix Polish translation
  contributing-guides/translation-templates/alias-pages.md
Labels: documentation, translation, review needed

#7239 gh-codespace: add page
  pages/common/gh-codespace.md
  pages/common/gh-cs.md
Labels: new command, hacktoberfest-accepted

#7363 trash: add Turkish translation
  pages.tr/linux/trash.md
Labels: translation, hacktoberfest, review needed

#7362 cp: add Turkish translation
  pages.tr/linux/cp.md
Labels: translation, hacktoberfest, review needed

#7355 tldr-lint, tldrl: add Polish translations
  pages.pl/common/tldr-lint.md
  pages.pl/common/tldrl.md
Labels: translation, hacktoberfest-accepted, review needed

#7351 pulseaudio: add Italian translation
  pages.it/linux/pulseaudio.md
Labels: translation, hacktoberfest-accepted, review needed

#7317 windows/msg, windows/print, windows/ver: add Polish translation
  pages.pl/windows/msg.md
  pages.pl/windows/print.md
  pages.pl/windows/ver.md
Labels: translation, hacktoberfest-accepted, review needed

#7371 osx/m*: add more information link
  pages.zh/osx/m.md
  pages.zh/osx/md5.md
  pages.zh/osx/mdfind.md
  pages.zh/osx/mdutil.md
  pages.zh/osx/mkfile.md
  pages/osx/m.md
  pages/osx/md5.md
  pages/osx/mdfind.md
  pages/osx/mdls.md
  pages/osx/mdutil.md
  pages/osx/mkfile.md
Labels: page edit, review needed

#7329 steam: add console open command
  pages/common/steam.md
Labels: page edit, hacktoberfest-accepted, review needed

#7374 omz: add page
  pages/common/omz.md
Labels: new command

#7372 shc: add more information link
  pages/common/shc.md
Labels: page edit, review needed

#7186 az-pipelines: add page
  pages/common/az-pipelines.md
Labels: new command, hacktoberfest-accepted, review needed

#7302 stat: add more information link
  pages/common/stat.md
Labels: page edit, hacktoberfest-accepted, review needed

#7285 jupyter: add pt_BR translation
  pages.pt_BR/common/jupyter.md
Labels: translation, hacktoberfest-accepted, review needed

#7286 cmake: add French translation
  pages.fr/common/cmake.md
Labels: translation, hacktoberfest-accepted, review needed

#7282 banner: add Hindi translation
  pages.hi/common/banner.md
Labels: translation, hacktoberfest-accepted, review needed

#7327 w, wc: add Polish translation
  pages.pl/osx/w.md
  pages.pl/osx/wc.md
  pages/osx/w.md
  pages/osx/wc.md
Labels: translation, hacktoberfest-accepted, review needed

#7182 fprintd-delete: add page
  pages/linux/fprintd-delete.md
Labels: new command, hacktoberfest-accepted, review needed

#7226 cryptcat: add page
  pages/linux/cryptcat.md
Labels: new command, hacktoberfest-accepted

#7086 [: add Indonesian translation
  pages.id/common/[.md
Labels: translation, hacktoberfest-accepted, review needed

#7088 scutil, screencapture, systemsetup, readlink, softwareupdate: add pt_PT translation
  pages.pt_PT/osx/readlink.md
  pages.pt_PT/osx/screencapture.md
  pages.pt_PT/osx/scutil.md
  pages.pt_PT/osx/softwareupdate.md
  pages.pt_PT/osx/systemsetup.md
Labels: translation, hacktoberfest-accepted, review needed

#7138 thunar: add Malayalam translation
  pages.ml/linux/thunar.md
Labels: translation, hacktoberfest-accepted, review needed

#7187 am: add Turkish translation
  pages.tr/android/am.md
Labels: translation, hacktoberfest-accepted

#7222 zathura: add Italian translation
  pages.it/linux/zathura.md
Labels: translation, hacktoberfest-accepted, review needed

#6630 curl: add --fail in example
  pages/common/curl.md
Labels: page edit, hacktoberfest-accepted, review needed

#6979 iptables, nft: add masquerade example
  pages/linux/iptables.md
  pages/linux/nft.md
Labels: page edit, hacktoberfest-accepted, review needed

#7178 fprintd-verify: add page
  pages/linux/fprintd-verify.md
Labels: new command, hacktoberfest-accepted

#7353 README: fix grammar
  README.md
Labels: documentation, hacktoberfest-accepted, review needed

#7272 localectl: add page
  pages/linux/localectl.md
Labels: new command, hacktoberfest-accepted, review needed

#7047 apk: add French translation
  pages.fr/linux/apk.md
Labels: translation, hacktoberfest-accepted

#7209 rpmspec: add --querytags example
  pages/linux/rpmspec.md
Labels: page edit, hacktoberfest-accepted, review needed

#7208 docker-run: add --entrypoint and --network examples
  pages/common/docker-run.md
Labels: page edit, hacktoberfest-accepted

#7203 add-apt-repository: improve --enable-source example description
  pages/linux/add-apt-repository.md
Labels: page edit, hacktoberfest-accepted

#7359 git-changelog: add page
  pages/common/git-changelog.md
Labels: new command, hacktoberfest-accepted

#7228 set-more-info-link.py, translation-templates/*: add Nepali translation
  contributing-guides/translation-templates/alias-pages.md
  contributing-guides/translation-templates/subcommand-mention.md
  scripts/set-more-info-link.py
Labels: translation, hacktoberfest-accepted

#7350 *sum: add Tamil translation
  pages.ta/common/b2sum.md
  pages.ta/common/cksum.md
  pages.ta/common/md5sum.md
  pages.ta/common/sha1sum.md
  pages.ta/common/sha224sum.md
  pages.ta/common/sha256sum.md
  pages.ta/common/sha384sum.md
  pages.ta/common/sha512sum.md
  pages.ta/common/shasum.md
  pages.ta/common/sum.md
Labels: translation, hacktoberfest-accepted

#7367 translation-templates: add Tamil translation
  contributing-guides/translation-templates/common-arguments.md
  contributing-guides/translation-templates/subcommand-mention.md
Labels: translation

#7269 wasm-objdump, wasm-opt, wasm2c, wasm2wat: add link
  pages/common/wasm-objdump.md
  pages/common/wasm-opt.md
  pages/common/wasm2c.md
  pages/common/wasm2wat.md
Labels: page edit, hacktoberfest-accepted

#7140 time: add page
  pages/windows/time.md
Labels: new command, hacktoberfest-accepted

#7301 head, tail: add German translation
  pages.de/common/head.md
  pages.de/common/tail.md
Labels: translation, hacktoberfest-accepted

#7280 lxc-network, lxc-profile: add page
  pages/linux/lxc-network.md
  pages/linux/lxc-profile.md
Labels: new command, hacktoberfest-accepted

#7237 dolt-clone: add page
  pages/common/dolt-clone.md
Labels: new command, hacktoberfest-accepted

#7357 git-sync: add page
  pages/common/git-sync.md
Labels: new command, hacktoberfest-accepted, review needed

#7354 [, test: add Polish translation
  pages.pl/common/[.md
  pages.pl/common/test.md
  pages/common/[.md
  pages/common/test.md
Labels: translation, hacktoberfest-accepted, review needed

#7379 rsync: fix --delete example description
  pages/common/rsync.md
Labels: page edit

#7054 pacman-*: add French translation
  pages.fr/linux/pacman-database.md
  pages.fr/linux/pacman-deptest.md
  pages.fr/linux/pacman-files.md
  pages.fr/linux/pacman-key.md
  pages.fr/linux/pacman-mirrors.md
  pages.fr/linux/pacman-query.md
  pages.fr/linux/pacman-remove.md
  pages.fr/linux/pacman-sync.md
  pages.fr/linux/pacman-upgrade.md
Labels: translation, hacktoberfest-accepted, review needed

#7108 fossil-add: add page
  pages/linux/fossil-add.md
Labels: new command, hacktoberfest-accepted

#6605 pip: synchronize long options, formatting and add --user example
  pages.fr/common/pip.md
  pages.id/common/pip.md
  pages/common/pip.md
Labels: page edit, translation, review needed

#7141 style-guide.zh: refresh
  contributing-guides/style-guide.zh.md
Labels: documentation, hacktoberfest-accepted

#7235 mp3info: add page
  pages/common/mp3info.md
Labels: new command, hacktoberfest-accepted, review needed

#7242 subcommand-mention: add pt_PT translation
  contributing-guides/translation-templates/subcommand-mention.md
Labels: documentation, translation, hacktoberfest-accepted

#7384 notify-send: Add `--app-name` to example
  pages/linux/notify-send.md
Labels: page edit

#7224 nx: add page
  pages/common/nx.md
Labels: new command, hacktoberfest-accepted

#7115 fossil-delete, fossil-forget, fossil-rm: add page
  pages/linux/fossil-delete.md
  pages/linux/fossil-forget.md
  pages/linux/fossil-rm.md
Labels: new command, hacktoberfest-accepted

#7390 tail: fix wording
  pages/common/tail.md
Labels: page edit, minor change

#7385 pylint: add page
  pages/common/pylint.md
Labels: new command

#7214 pvecm: add page
  pages/common/pvecm.md
Labels: new command, hacktoberfest-accepted, review needed

#7289 curl: add traditional Chinese translation
  pages.zh_TW/common/curl.md
Labels: translation, hacktoberfest-accepted

#7090 set: add -e example
  pages/common/set.md
Labels: page edit, hacktoberfest-accepted, review needed

#7136 aws-ses: add page
  pages/common/aws-ses.md
Labels: new command, hacktoberfest-accepted, review needed

#7326 pactree: add page
  pages/linux/pactree.md
Labels: new command, hacktoberfest-accepted

#7213 pve-firewall: add page
  pages/common/pve-firewall.md
Labels: new command, hacktoberfest-accepted, review needed

#7393 shiny-mirrors: add page
  pages/linux/shiny-mirrors.md
Labels: new command, review needed

#7361 git-squash: add page
  pages/common/git-squash.md
Labels: new command, hacktoberfest-accepted, review needed

#7389 xrandr: remove duplicate example
  pages.de/linux/xrandr.md
  pages.tr/linux/xrandr.md
  pages/linux/xrandr.md
Labels: page edit, translation, minor change

#7175 a2disconf, a2enconf: add pt_PT translation
  pages.pt_PT/linux/a2disconf.md
  pages.pt_PT/linux/a2enconf.md
Labels: translation, hacktoberfest-accepted, review needed

#7177 a2dismod, a2enmod: add pt_PT translation
  pages.pt_PT/linux/a2dismod.md
  pages.pt_PT/linux/a2enmod.md
Labels: translation, hacktoberfest-accepted, review needed

#7125 vzdump: add page
  pages/common/vzdump.md
Labels: new command, hacktoberfest-accepted, review needed

#7356 git-sed: add page
  pages/common/git-sed.md
Labels: new command, hacktoberfest-accepted

#7381 README: remove list of clients
  README.md
Labels: documentation, review needed

#7391 wc: refresh
  pages.es/common/wc.md
  pages/common/wc.md
Labels: page edit, review needed

#6768 cgcreate: add page
  pages/linux/cgcreate.md
Labels: new command, hacktoberfest-accepted, stalebot ignore, review needed

#7212 pveperf: add page
  pages/common/pveperf.md
Labels: new command, hacktoberfest-accepted

#7216 gbp: add page
  pages/linux/gbp.md
Labels: new command, hacktoberfest-accepted

#7200 http-server: add page
  pages/common/http-server.md
Labels: new command, hacktoberfest-accepted

#7396 swc: add page
  pages/common/swc.md
Labels: new command, review needed

#7201 http-server-upload: add page
  pages/common/http-server-upload.md
Labels: new command, hacktoberfest-accepted

#7403 install: use long arguments format
  pages.fr/common/install.md
  pages/common/install.md
Labels: page edit, translation

#7378 strip: add page
  pages/linux/strip.md
Labels: new command

#7397 fsck: use partition instead of drive in examples
  pages/linux/fsck.md
Labels: page edit

#6763 git: add more subcommand examples
  pages/common/git.md
Labels: page edit, hacktoberfest-accepted, review needed

#7153 lsof: edit -iTCP example with -i6TCP, -n and -P
  pages/common/lsof.md
Labels: page edit, hacktoberfest-accepted, review needed, minor change

#7387 bluetoothctl: add power and help examples
  pages/linux/bluetoothctl.md
Labels: page edit

#7394 mozillavpn: add page
  pages/common/mozillavpn.md
Labels: new command, review needed

#7405 xplr: add more options to open paths
  pages/common/xplr.md
Labels: page edit, review needed

#7407 gh-issue-create: fix command name
  pages/common/gh-issue-create.md
Labels: page edit, minor change

#7401 i3exit: add page
  pages/linux/i3exit.md
Labels: new command, minor change
