Repository tldr-pages/tldr, pull requests merged in 2021-07, with the labels that each got.

#6185 nmcli-connection: add import VPN example
  pages/linux/nmcli-connection.md
Labels: page edit

#6041 mongoexport: add page
  pages/common/mongoexport.md
Labels: new command

#5724 *: replace dead more information links
  pages.it/common/blender.md
  pages.ko/common/blender.md
  pages.ko/common/dexdump.md
  pages/common/blender.md
  pages/common/deemix.md
  pages/common/dexdump.md
  pages/common/glab.md
  pages/common/httping.md
  pages/common/multitail.md
  pages/common/mytop.md
  pages/common/parquet-tools.md
  pages/common/redshift.md
  pages/common/timew.md
  pages/common/vela.md
  pages/linux/ark.md
  pages/linux/postfix.md
Labels: page edit, translation

#6189 pihole: add examples
  pages/linux/pihole.md
Labels: page edit

#6182 gcc: add long flag
  pages.de/common/gcc.md
  pages.pt_BR/common/gcc.md
  pages/common/gcc.md
Labels: page edit

#6178 w: add traditional Chinese translation
  pages.zh_TW/common/w.md
Labels: translation

#6164 git-show-tree: add page
  pages/common/git-show-tree.md
Labels: new command

#6193 gzip: add --keep example
  pages/common/gzip.md
Labels: page edit

#6051 histexpand: add `!N` and `!?string?` commands
  pages/common/histexpand.md
Labels: page edit

#6195 gpg: add --full-generate-key example
  pages/common/gpg.md
Labels: page edit

#6191 bash: add traditional Chinese translation
  pages.zh_TW/common/bash.md
Labels: translation

#6168 nmcli-monitor: add page
  pages/linux/nmcli-monitor.md
Labels: new command

#6199 podman: update more information link
  pages/common/podman.md
Labels: page edit

#6201 cp: add traditional Chinese translation
  pages.zh_TW/common/cp.md
Labels: translation

#6145 sdcv: add page
  pages/common/sdcv.md
Labels: new command

#6187 ansible-galaxy: add role info and collection info examples
  pages/common/ansible-galaxy.md
Labels: page edit

#6205 xinput: add list-props and set-prop examples
  pages/linux/xinput.md
Labels: page edit

#6206 sdcv: fix spelling error
  pages/common/sdcv.md
Labels: page edit

#6208 bc, figlet: add Spanish translation
  pages.es/common/bc.md
  pages.es/common/figlet.md
Labels: translation

#6207 deps: upgrade husky to v7.0.1
  .husky/.gitignore
  package-lock.json
  package.json
Labels: tooling

#6212 restic: replace -r by long argument --repo
  pages/common/restic.md
Labels: page edit

#6214 code: add traditional Chinese translation
  pages.zh_TW/common/code.md
Labels: translation

#6186 pio-ci: add page
  pages/common/pio-ci.md
Labels: new command

#6216 pwd, zsh: add Spanish translation
  pages.es/common/pwd.md
  pages.es/common/zsh.md
Labels: translation

#6190 linux/u*: add links
  pages/linux/ul.md
  pages/linux/unix2dos.md
  pages/linux/unix2mac.md
  pages/linux/unset.md
  pages/linux/update-alternatives.md
  pages/linux/update-rc.d.md
  pages/linux/updatedb.md
Labels: page edit

#6211 cmatrix, md5sum, more: add Italian translation
  pages.it/common/cmatrix.md
  pages.it/common/md5sum.md
  pages.it/common/more.md
Labels: translation

#6203 nmcli: refresh
  pages/linux/nmcli.md
Labels: page edit

#6218 ifconfig: add more information link
  pages.fr/common/ifconfig.md
  pages/common/ifconfig.md
Labels: page edit, translation

#6224 *: replace `java` with `Java` and `c++` with `C++`
  pages.it/common/astyle.md
  pages.ko/common/astyle.md
  pages.zh/linux/addr2line.md
  pages/common/astyle.md
  pages/common/jenv.md
  pages/common/jmap.md
  pages/common/jstack.md
  pages/common/swagger-codegen.md
Labels: page edit, translation

#6202 wifi-menu: add page
  pages/linux/wifi-menu.md
Labels: new command

#6225 zypper: add link and example about repos management
  pages/linux/zypper.md
Labels: page edit

#6217 showfigfonts: add page
  pages.es/common/figlet.md
  pages.es/common/showfigfonts.md
  pages/common/figlet.md
  pages/common/showfigfonts.md
Labels: new command, page edit, translation

#6192 prettier: add page
  pages/common/prettier.md
Labels: new command

#6183 ffuf: add page
  pages/linux/ffuf.md
Labels: new command

#6230 docker: add Chinese translation
  pages.zh/common/docker.md
  pages.zh_TW/common/docker.md
Labels: translation

#6236 PULL_REQUEST_TEMPLATE: repo - repository
  .github/PULL_REQUEST_TEMPLATE.md
Labels: decision, documentation

#6238 zypper, i3: add Spanish translation
  pages.es/linux/i3.md
  pages.es/linux/zypper.md
Labels: translation

#6222 az-vm: add page
  pages/common/az-vm.md
Labels: new command

#6223 jenv: add Chinese translation
  pages.zh/common/jenv.md
Labels: translation

#6215 scripts: add SPDX-License-Identifier in files
  scripts/build-index.js
  scripts/build.sh
  scripts/check-pr.sh
  scripts/deploy.sh
  scripts/pdf/basic.css
  scripts/pdf/render.py
  scripts/pdf/solarized-dark.css
  scripts/pdf/solarized-light.css
  scripts/send-to-bot.py
  scripts/set-more-info-link.py
  scripts/test.sh
Labels: architecture, documentation

#6229 az-logout: add page
  pages/common/az-logout.md
Labels: new command

#6240 restic: fix restore example
  pages/common/restic.md
Labels: page edit

#6175 vnstati: add page
  pages/linux/vnstati.md
Labels: new command

#6204 az-account: add page
  pages/common/az-account.md
Labels: new command

#6234 musescore: add German translation
  pages.de/common/musescore.md
Labels: translation

#6156 radeontop: update page
  pages/linux/radeontop.md
Labels: page edit

#6245 linux/arch: remove Chinese translation
  pages.zh/linux/arch.md
Labels: translation

#6226 7za, 7zr, ansible-galaxy, convert, dd, exa, fuck, git-*, gpg, ls, mv: sync German page
  pages.de/common/7za.md
  pages.de/common/7zr.md
  pages.de/common/ansible-galaxy.md
  pages.de/common/convert.md
  pages.de/common/dd.md
  pages.de/common/exa.md
  pages.de/common/fuck.md
  pages.de/common/git-clone.md
  pages.de/common/git-init.md
  pages.de/common/gpg.md
  pages.de/common/ls.md
  pages.de/common/mv.md
Labels: page edit, translation

#6188 git-commit: add gpg-sign example and sync German translation
  pages.de/common/git-commit.md
  pages/common/git-commit.md
Labels: page edit, translation

#6244 az-vm: use az instead of azure-cli
  pages/common/az-vm.md
Labels: page edit

#6239 vim, vimtutor, vimdiff: add Spanish translation
  pages.es/common/vim.md
  pages.es/common/vimdiff.md
  pages.es/common/vimtutor.md
Labels: translation

#6247 gunzip: add command to keep original files
  pages/common/gunzip.md
Labels: page edit

#6228 az-login: add page
  pages/common/az-login.md
Labels: new command

#6243 git-abort: add page
  pages/common/git-abort.md
Labels: new command

#6196 fdisk: refresh
  pages/linux/fdisk.md
Labels: page edit

#6221 am, alacritty, bastet, colordiff, dash, i3, nmtui, radeontop, ufw, zypper: add Italian translation
  pages.it/android/am.md
  pages.it/common/alacritty.md
  pages.it/common/bastet.md
  pages.it/common/colordiff.md
  pages.it/common/dash.md
  pages.it/linux/i3.md
  pages.it/linux/nmtui.md
  pages.it/linux/radeontop.md
  pages.it/linux/ufw.md
  pages.it/linux/zypper.md
Labels: translation

#6194 gradle: edit assembleRelease example to show Android Studio specificity
  pages.es/common/gradle.md
  pages/common/gradle.md
Labels: page edit, translation

#6251 gsettings: add page
  pages/linux/gsettings.md
Labels: new command

#6259 ocrmypdf: add page
  pages/common/ocrmypdf.md
Labels: new command

#6258 rtorrent: add link
  pages/linux/rtorrent.md
Labels: page edit

#6254 nettop: add page
  pages/osx/nettop.md
Labels: new command

#6242 uname: refresh
  pages/common/uname.md
  pages/osx/uname.md
Labels: page edit

#6121 fc-pattern, sv, tomb, xkill: add examples
  pages/common/sv.md
  pages/common/xkill.md
  pages/linux/fc-pattern.md
  pages/linux/tomb.md
Labels: mass changes, page edit

#6255 protonvpn-cli: add page
  pages/linux/protonvpn-cli-connect.md
  pages/linux/protonvpn-cli.md
Labels: new command

#6241 resume: add page
  pages/common/resume.md
Labels: new command

#6256 style-guide: add section on serial comma
  contributing-guides/style-guide.md
Labels: documentation

#6237 vim: update description
  pages/common/vim.md
Labels: page edit

#6267 wrong parameter in htop
  pages/common/htop.md
Labels: page edit

#6261 ffe: add page
  pages/common/ffe.md
Labels: new command

#6250 vim: update Spanish translation
  pages.es/common/vim.md
Labels: page edit, translation

#6264 synopkg: add page
  pages/linux/synopkg.md
Labels: new command

#6262 synoupgrade: add page
  pages/linux/synoupgrade.md
Labels: new command

#6235 nano: refresh
  pages/common/nano.md
Labels: page edit

#6271 figlet: fix typo in example description
  pages/common/figlet.md
Labels: page edit

#6272 nmap: fix example description
  pages/common/nmap.md
Labels: page edit

#6249 pwsh: add page
  pages/common/pwsh.md
Labels: new command

#6273 rustup: add doc example
  pages/common/rustup.md
Labels: page edit

#6279 line: add Chinese translation
  pages.zh/linux/line.md
Labels: translation
