Repository tldr-pages/tldr, pull requests merged in 2021-10, with the labels that each got.

#6640 tldr: add Ukrainian translation
  pages.uk/common/tldr.md
Labels: translation

#6638 pwd: add Hindi translation
  pages.hi/common/pwd.md
Labels: translation

#6626 CONTRIBUTING: fix link to alias-pages
  CONTRIBUTING.md
Labels: documentation

#6642 aws-s3: fix more information link
  pages/common/aws-s3.md
Labels: page edit

#6649 git-revert: use HEAD in example
  pages.es/common/git-revert.md
  pages.fr/common/git-revert.md
  pages.it/common/git-revert.md
  pages/common/git-revert.md
Labels: page edit

#6614 git-clear: add page
  pages/common/git-clear.md
Labels: new command

#5976 COMMUNITY-ROLES: fix typo
  COMMUNITY-ROLES.md
Labels: documentation, stalebot ignore

#6571 PULL_REQUEST_TEMPLATE: ask for command version number
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, tooling

#6647 az-storage: add page
  pages/common/az-storage.md
Labels: new command

#6635 npm-check: add German translation
  pages.de/common/npm-check.md
Labels: translation

#6634 nodenv: add German translation
  pages.de/common/nodenv.md
Labels: translation

#6628 solcjs: add page
  pages/common/solcjs.md
Labels: new command

#6636 nodemon: add German translation
  pages.de/common/nodemon.md
Labels: translation

#6637 node: add German translation
  pages.de/common/node.md
Labels: translation

#6631 nvm: add German translation
  pages.de/common/nvm.md
Labels: translation

#6656 unalias: replace alijas with pseudonim
  pages.bs/common/unalias.md
Labels: translation

#6657 shutdown: add more information link
  pages.es/linux/shutdown.md
  pages/linux/shutdown.md
Labels: page edit

#6655 *: add Bosnian translation for aliases
  pages.bs/common/aria2.md
  pages.bs/common/clang-cpp.md
  pages.bs/common/clojure.md
  pages.bs/common/cola.md
  pages.bs/common/llvm-ar.md
  pages.bs/common/llvm-g++.md
  pages.bs/common/llvm-gcc.md
  pages.bs/common/llvm-nm.md
  pages.bs/common/llvm-objdump.md
  pages.bs/common/llvm-strings.md
  pages.bs/common/mscore.md
  pages.bs/common/pio-init.md
  pages.bs/common/piodebuggdb.md
  pages.bs/common/platformio.md
  pages.bs/common/r2.md
  pages.bs/common/tldrl.md
  pages.bs/common/tlmgr-arch.md
  pages.bs/common/vi.md
Labels: translation

#6710 rvm: add Indonesian translation
  pages.id/common/rvm.md
Labels: translation

#6715 tar: add Chinese translation
  pages.zh/common/tar.md
Labels: translation

#6709 tldr: add German translation
  pages.de/common/tldr.md
Labels: translation

#6706 base64: fix French translation
  pages.fr/common/base64.md
Labels: translation

#6695 PULL_REQUEST_TEMPLATE: fix interline space
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, tooling

#6718 az-bicep: add page
  pages/common/az-bicep.md
Labels: new command

#6702 ps: add Indonesian translation
  pages.id/common/ps.md
Labels: translation

#6696 df: add German translation
  pages.de/common/df.md
Labels: translation

#6662 7zr: fix Japanese translation
  pages.ja/common/7zr.md
Labels: translation

#6663 7za: fix Japanese translation
  pages.ja/common/7za.md
Labels: translation

#6660 apktool: add Japanese translation
  pages.ja/common/apktool.md
Labels: translation

#6661 7z, 7za, 7zr: fix Japanese translation
  pages.ja/common/7z.md
  pages.ja/common/7za.md
  pages.ja/common/7zr.md
Labels: translation

#6686 rscript: add page
  pages/common/rscript.md
Labels: new command

#6604 ssh: add -t in example description
  pages/common/ssh.md
Labels: page edit

#6632 npx: add German translation
  pages.de/common/npx.md
Labels: translation

#6620 dir: add German translation
  pages.de/windows/dir.md
Labels: translation

#6693 du: add German translation
  pages.de/common/du.md
Labels: translation

#6633 npm-why: add German translation
  pages.de/common/npm-why.md
Labels: translation

#6615 csrutil: add page
  pages/osx/csrutil.md
Labels: new command

#6721 az-bicep: fix more information link
  pages/common/az-bicep.md
Labels: page edit

#6570 set-more-info-link.py, pages.hi/*: fix punctuation in Hindi translation
  pages.hi/common/cat.md
  pages.hi/common/cd.md
  pages.hi/common/chsh.md
  pages.hi/common/false.md
  pages.hi/common/ls.md
  pages.hi/common/mkdir.md
  pages.hi/common/tldr.md
  pages.hi/common/touch.md
  scripts/set-more-info-link.py
Labels: tooling, translation

#6669 shuf: add Indonesian translation
  pages.id/osx/shuf.md
Labels: translation

#6646 ego: add page
  pages/linux/ego.md
Labels: new command

#6650 go-run: add page
  pages/common/go-run.md
Labels: new command

#6629 nodemon: make --inspect a generic example
  pages/common/nodemon.md
Labels: page edit

#6673 tr: add French translation
  pages.fr/common/tr.md
Labels: translation

#6691 pip-install: add German translation
  pages.de/common/pip-install.md
Labels: translation

#6731 rsync: add Indonesian translation
  pages.id/common/rsync.md
Labels: translation

#6683 sysctl: add German translation
  pages.de/linux/sysctl.md
Labels: translation

#6740 cp: add Hindi translation
  pages.hi/common/cp.md
Labels: translation

#6745 git, git-add, git-status: add Ukrainian translation
  pages.uk/common/git-add.md
  pages.uk/common/git-status.md
  pages.uk/common/git.md
Labels: translation

#6741 alias: add Hindi translation
  pages.hi/common/alias.md
Labels: translation

#6752 *: remove unnecesary trailing .1 of manned.org links
  pages/linux/spectre-meltdown-checker.md
  pages/linux/timedatectl.md
  pages/linux/xcursorgen.md
Labels: page edit, mass changes

#6619 free, lsblk: add pt_BR translation
  pages.pt_BR/linux/free.md
  pages.pt_BR/linux/lsblk.md
Labels: translation

#6725 test: add Japanese translation
  pages.ja/common/test.md
Labels: translation

#6747 pwd: fix typo in Hindi translation
  pages.hi/common/pwd.md
Labels: translation

#6668 caffeinate: add Indonesian translation
  pages.id/osx/caffeinate.md
Labels: translation

#6746 fg: add Hindi translation
  pages.hi/common/fg.md
Labels: translation

#6735 ln: add Hindi translation
  pages.hi/common/ln.md
Labels: translation

#6758 zenity, zgrep, zramctl: add more information link
  pages/linux/zenity.md
  pages/linux/zgrep.md
  pages/linux/zramctl.md
Labels: page edit

#6690 adduser: add German translation
  pages.de/linux/adduser.md
Labels: translation

#6689 pip: add German translation
  pages.de/common/pip.md
Labels: translation

#6617 nvram: add page
  pages/osx/nvram.md
Labels: new command

#6729 rm: add Korean translation
  pages.ko/common/rm.md
Labels: translation

#6557 raw: add page
  pages/linux/raw.md
Labels: new command

#6755 cd: fix link and add Swedish translation
  pages.de/common/cd.md
  pages.es/common/cd.md
  pages.fa/common/cd.md
  pages.fr/common/cd.md
  pages.hi/common/cd.md
  pages.id/common/cd.md
  pages.it/common/cd.md
  pages.ko/common/cd.md
  pages.nl/common/cd.md
  pages.pt_PT/common/cd.md
  pages.sv/common/cd.md
  pages.zh/common/cd.md
  pages.zh_TW/common/cd.md
  pages/common/cd.md
Labels: translation

#6733 kwrite: add page
  pages/linux/kwrite.md
Labels: new command

#6610 sshd: add page
  pages/common/sshd.md
Labels: new command

#6776 docker, docker-run: fix Turkish translation
  pages.tr/common/docker-run.md
  pages.tr/common/docker.md
Labels: page edit, translation

#6774 ng: add Turkish translation
  pages.tr/common/ng.md
Labels: translation

#6664 common/x*: add more information link
  pages.es/common/xkill.md
  pages.it/common/xkill.md
  pages.it/common/xxd.md
  pages.pl/common/xkill.md
  pages.pt_BR/common/xkill.md
  pages.pt_PT/common/xkill.md
  pages/common/xar.md
  pages/common/xargs.md
  pages/common/xephyr.md
  pages/common/xkill.md
  pages/common/xmllint.md
  pages/common/xxd.md
Labels: page edit, mass changes

#6698 mount: add German translation
  pages.de/common/mount.md
Labels: translation

#6659 common/ssh*: add more information link
  pages.de/common/ssh-agent.md
  pages.de/common/ssh-copy-id.md
  pages.de/common/ssh-keygen.md
  pages.de/common/ssh-keyscan.md
  pages.de/common/sshpass.md
  pages.zh/common/ssh-add.md
  pages.zh/common/sshuttle.md
  pages/common/ssh-add.md
  pages/common/ssh-agent.md
  pages/common/ssh-copy-id.md
  pages/common/ssh-keygen.md
  pages/common/ssh-keyscan.md
  pages/common/sshpass.md
  pages/common/sshuttle.md
Labels: page edit, mass changes

#6759 aws-help: fix more information link
  pages/common/aws-help.md
Labels: page edit

#6754 rpm: add more information link
  pages/linux/rpm.md
Labels: page edit

#6771 apk: add German translation
  pages.de/linux/apk.md
Labels: translation

#6737 egrep: add page
  pages/common/egrep.md
Labels: new command

#6652 mongo: add French translation
  pages.fr/common/mongo.md
Labels: translation

#6732 pacstall: add page
  pages/linux/pacstall.md
Labels: new command

#6643 jhsdb: add page
  pages/common/jhsdb.md
Labels: new command

#6586 tlmgr-check: add page
  pages/common/tlmgr-check.md
Labels: new command

#6772 nginx: add Turkish translation
  pages.tr/common/nginx.md
Labels: translation

#6688 node: add French translation
  pages.fr/common/node.md
Labels: translation

#6726 ls: add Korean translation
  pages.ko/common/ls.md
Labels: translation

#6780 ansible: sync Italian translation
  pages.it/common/ansible.md
Labels: translation

#6724 [: add Japanese translation
  pages.ja/common/[.md
Labels: translation

#6716 android/*: add French translation
  pages.fr/android/am.md
  pages.fr/android/bugreport.md
  pages.fr/android/bugreportz.md
  pages.fr/android/cmd.md
  pages.fr/android/dalvikvm.md
  pages.fr/android/dumpsys.md
  pages.fr/android/getprop.md
  pages.fr/android/input.md
  pages.fr/android/logcat.md
  pages.fr/android/pm.md
  pages.fr/android/settings.md
  pages.fr/android/wm.md
Labels: new command

#6714 ruby: add Indonesian translation
  pages.id/common/ruby.md
Labels: translation

#6707 rbenv: add Indonesian translation
  pages.id/common/rbenv.md
Labels: translation

#6685 amass: add Chinese translation
  pages.zh/common/amass.md
Labels: translation

#6791 babel: fix Korean translation
  pages.ko/common/babel.md
Labels: page edit, translation

#6639 sbt: add clean example
  pages/common/sbt.md
Labels: page edit

#6734 setx: add page
  pages/windows/setx.md
Labels: new command

#6789 arch-chroot: add German translation
  pages.de/linux/arch-chroot.md
Labels: translation

#6792 docker: sync Turkish translation
  pages.tr/common/docker.md
Labels: translation

#6775 yes: add Turkish translation
  pages.tr/common/yes.md
Labels: translation

#6738 sbt: add compile example
  pages/common/sbt.md
Labels: page edit

#6785 alias-pages, subcommand-mention: add Ukrainian translation
  contributing-guides/translation-templates/alias-pages.md
  contributing-guides/translation-templates/subcommand-mention.md
Labels: documentation

#6784 wall, watch, whereis, whiptail, wipefs, wmctrl, wodim: add link
  pages.fa/common/whereis.md
  pages.pt_BR/linux/watch.md
  pages.zh/common/whereis.md
  pages/common/watch.md
  pages/common/whereis.md
  pages/linux/wall.md
  pages/linux/watch.md
  pages/linux/whiptail.md
  pages/linux/wipefs.md
  pages/linux/wmctrl.md
  pages/linux/wodim.md
Labels: page edit, mass changes

#6795 mail, mailx, mesg, mmv, monop, most, mscore: add link
  pages/common/mail.md
  pages/common/mailx.md
  pages/common/mesg.md
  pages/common/mmv.md
  pages/common/monop.md
  pages/common/most.md
  pages/common/mscore.md
Labels: page edit, mass changes

#6807 choco: fix subcommand mention in Japanese translation
  contributing-guides/translation-templates/subcommand-mention.md
  pages.ja/windows/choco.md
Labels: documentation, translation

#6788 mount: add more information link
  pages.de/common/mount.md
  pages.it/common/mount.md
  pages/common/mount.md
Labels: page edit

#6751 flatpak: add pt_BR translation
  pages.pt_BR/linux/flatpak.md
Labels: translation

#6644 az-storage-blob: add page
  pages/common/az-storage-blob.md
Labels: new command

#6757 pacman: add German translation
  pages.de/linux/pacman.md
Labels: translation, hacktoberfest-accepted

#6798 *: mention subcommands in pt_BR translation
  contributing-guides/translation-templates/subcommand-mention.md
  pages.pt_BR/common/aws.md
  pages.pt_BR/common/docker.md
  pages.pt_BR/common/fc.md
  pages.pt_BR/common/git.md
  pages.pt_BR/common/kubectl.md
  pages.pt_BR/linux/dpkg.md
  pages.pt_BR/windows/choco.md
Labels: documentation, translation

#6543 tldr: fix command description in Japanese translation
  pages.ja/common/tldr.md
Labels: translation

#6682 shutdown: add French translation
  pages.fr/linux/shutdown.md
Labels: translation

#6699 az-feedback: add page
  pages/common/az-feedback.md
Labels: new command

#6694 fscrypt: add page
  pages/linux/fscrypt.md
Labels: new command

#6672 xsel: add French translation
  pages.fr/linux/xsel.md
Labels: translation

#6680 adb: add French translation
  pages.fr/common/adb.md
Labels: translation

#6809 dir: add page
  pages/linux/dir.md
Labels: new command

#6675 systemctl: add French translation
  pages.fr/linux/systemctl.md
Labels: translation

#6678 sysctl: add French translation
  pages.fr/linux/sysctl.md
Labels: translation

#6812 *: fix period in Japanese translation
  pages.ja/common/7z.md
  pages.ja/common/7za.md
  pages.ja/common/7zr.md
  pages.ja/common/[.md
  pages.ja/common/apktool.md
  pages.ja/common/arch.md
  pages.ja/common/cp.md
  pages.ja/common/dig.md
  pages.ja/common/du.md
  pages.ja/common/echo.md
  pages.ja/common/less.md
  pages.ja/common/ls.md
  pages.ja/common/mysql.md
  pages.ja/common/pwd.md
  pages.ja/common/ranger.md
  pages.ja/common/sed.md
  pages.ja/common/tar.md
  pages.ja/common/test.md
  pages.ja/common/vim.md
  pages.ja/common/z.md
  pages.ja/windows/assoc.md
  pages.ja/windows/attrib.md
  pages.ja/windows/cd.md
  pages.ja/windows/choco-apikey.md
  pages.ja/windows/choco-feature.md
  pages.ja/windows/choco-info.md
  pages.ja/windows/choco.md
  pages.ja/windows/clip.md
  pages.ja/windows/cls.md
  pages.ja/windows/cmd.md
  pages.ja/windows/dir.md
  pages.ja/windows/find.md
  pages.ja/windows/ipconfig.md
  pages.ja/windows/mkdir.md
  pages.ja/windows/mklink.md
  scripts/set-more-info-link.py
Labels: mass changes, tooling, translation

#6622 repo-add: add page
  pages/linux/repo-add.md
Labels: new command

#6813 set-more-info-link.py: add Arabic translation
  scripts/set-more-info-link.py
Labels: tooling

#6701 az-config: add page
  pages/common/az-config.md
Labels: new command

#6625 cvs: add page
  pages/common/cvs.md
Labels: new command

#6742 exit: add Hindi translation
  pages.hi/common/exit.md
Labels: translation

#6736 mv: add Hindi translation
  pages.hi/common/mv.md
Labels: translation

#6666 goaccess: add page
  pages/linux/goaccess.md
Labels: new command

#6670 gh: add Indonesian translation
  pages.id/common/gh.md
Labels: translation

#6692 cd, echo, git, link, mkdir: add Serbian translation
  pages.sr/common/cd.md
  pages.sr/common/echo.md
  pages.sr/common/git.md
  pages.sr/common/link.md
  pages.sr/common/mkdir.md
Labels: translation

#6658 ping, ping6: add more information link
  pages/common/ping.md
  pages/common/ping6.md
Labels: page edit

#6782 aws-cur, aws-secretsmanager: add pt_BR translation
  pages.pt_BR/common/aws-cur.md
  pages.pt_BR/common/aws-secretsmanager.md
  pages/common/aws-cur.md
Labels: page edit, translation

#6817 dir: add page
  pages/linux/dir.md
Labels: new command

#6765 git-init: sync Hindi translation
  pages.hi/common/git-init.md
Labels: translation

#6744 bg: add Hindi translation
  pages.hi/common/bg.md
Labels: translation

#6728 py-spy: add page
  pages/common/py-spy.md
Labels: new command

#6779 rpmspec: add page
  pages/linux/rpmspec.md
Labels: new command

#6810 whoami: add Indonesia translation
  pages.id/windows/whoami.md
Labels: translation

#6822 dockerd: add Arabic translation
  pages.ar/linux/dockerd.md
Labels: translation

#6723 highlight: add page
  pages/common/highlight.md
Labels: new command

#6674 dune: add page
  pages/common/dune.md
Labels: new command

#6821 alias-pages, subcommand-mention: add Arabic translation
  contributing-guides/translation-templates/alias-pages.md
  contributing-guides/translation-templates/subcommand-mention.md
Labels: documentation

#6840 subcommand-mention: add Dutch translation
  contributing-guides/translation-templates/subcommand-mention.md
Labels: documentation

#7248 chntpw: add page
  pages/linux/chntpw.md
Labels: new command

#7281 iptables: add Italian translation
  pages.it/linux/iptables.md
Labels: translation, review needed

#7283 source: add alternative syntax example
  pages/common/source.md
Labels: page edit

#7215 bspc, bspwm: add page
  pages/linux/bspc.md
  pages/linux/bspwm.md
Labels: new command, review needed

#7118 plenv: add page
  pages/common/plenv.md
Labels: new command

#7157 qm, qmrestore: add page
  pages/linux/qm.md
  pages/linux/qmrestore.md
Labels: new command, review needed

#7294 anbox: add Norwegian translation
  pages.no/linux/anbox.md
Labels: translation

#7293 ack: add Norwegian translation
  pages.no/common/ack.md
Labels: translation

#7292 abduco: add Norwegian translation
  pages.no/common/abduco.md
Labels: translation

#7291 ab: add Norwegian translation
  pages.no/common/ab.md
Labels: translation

#7150 git-log: clarify date format with example
  pages.de/common/git-log.md
  pages.es/common/git-log.md
  pages.fr/common/git-log.md
  pages.it/common/git-log.md
  pages/common/git-log.md
Labels: page edit, translation

#7160 keyctl: add page
  pages/linux/keyctl.md
Labels: new command, hacktoberfest-accepted, review needed

#7296 bluetooth: move to correct directory
  pages.ml/linux/bluetoothctl.md
Labels: bug, translation, hacktoberfest-accepted, review needed

#7305 python: add http.server example
  pages/common/python.md
Labels: page edit
