Repository tldr-pages/tldr, pull requests merged in 2021-08, with the labels that each got.

#6281 gh-browse: add page
  pages/common/gh-browse.md
Labels: new command

#6282 gh-help: add formatting and mintty examples
  pages/common/gh-help.md
Labels: page edit

#6263 yacas: add page
  pages/common/yacas.md
Labels: new command

#6286 gml2gv, graphml2gv, gv2gml, gv2gxl, gxl2gv, mm2gv: add page
  pages/common/gml2gv.md
  pages/common/graphml2gv.md
  pages/common/gv2gml.md
  pages/common/gv2gxl.md
  pages/common/gxl2gv.md
  pages/common/mm2gv.md
Labels: new command

#6289 arecord: fix name of Chinese page
  pages.zh/linux/arecord.md
Labels: page edit

#6291 gh-mintty: add page
  pages/common/gh-mintty.md
Labels: new command

#6135 choose: add page
  pages/common/choose.md
Labels: new command

#6283 dict: add page
  pages/common/dict.md
Labels: new command

#6292 useradd, userdel, usermod: add Spanish translation
  pages.es/linux/useradd.md
  pages.es/linux/userdel.md
  pages.es/linux/usermod.md
Labels: translation

#6298 inotifywait: fix typo
  pages/linux/inotifywait.md
Labels: page edit

#6296 openscad: add page
  pages/common/openscad.md
Labels: new command

#6275 flake8: add page
  pages/common/flake8.md
Labels: new command

#6265 jhat: add Chinese translation
  pages.zh/common/jhat.md
Labels: translation

#6285 style-guide: add Chinese-specific rules
  contributing-guides/style-guide.md
Labels: documentation

#6274 procs: add page
  pages/linux/procs.md
Labels: new command

#6293 circup: add page
  pages/common/circup.md
Labels: new command

#6302 ul: add Chinese translation
  pages.zh/linux/ul.md
Labels: translation

#6304 dwebp: add page
  pages/common/dwebp.md
Labels: new command

#6313 xdelta: add page
  pages/common/xdelta.md
Labels: new command

#6290 gh-formatting: add page
  pages/common/gh-formatting.md
Labels: new command

#6338 rails-db: add more information link
  pages/common/rails-db.md
Labels: page edit

#6334 pdftotext: add more information link
  pages/common/pdftotext.md
Labels: page edit

#6329 PULL_REQUEST_TEMPLATE: add easy to copy links
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#6336 samtools: add more information link
  pages/common/samtools.md
Labels: page edit

#6332 miniserve: add page
  pages/common/miniserve.md
Labels: new command

#6312 [: add Swedish translation
  pages.sv/common/[.md
Labels: translation

#6337 qemu-img: add more information link
  pages/common/qemu-img.md
Labels: page edit

#6357 README: add JetBrains IDEs plugin
  README.md
Labels: documentation

#6278 cp, grub-install, grub-mkconfig, hexdump, readelf: add Chinese translation
  pages.zh/linux/cp.md
  pages.zh/linux/grub-install.md
  pages.zh/linux/grub-mkconfig.md
  pages.zh/linux/hexdump.md
  pages.zh/linux/readelf.md
Labels: translation

#6341 MAINTAINERS: add @blueskyson to collaborators
  MAINTAINERS.md
Labels: community

#6363 vim: reorder examples
  pages/common/vim.md
Labels: page edit

#6324 yay: add -Yc example
  pages/linux/yay.md
Labels: page edit

#6364 topgrade: fix typo in --disable example
  pages/common/topgrade.md
Labels: page edit

#6365 latex, pdflatex, pdftex, tex: replace 'halting' with 'exiting'
  pages/common/latex.md
  pages/common/pdflatex.md
  pages/common/pdftex.md
  pages/common/tex.md
Labels: page edit

#6321 xetex: add page
  pages/common/xetex.md
Labels: new command

#6314 docker-build: add Chinese translation
  pages.zh/common/docker-build.md
Labels: translation

#6335 platformio: add more information link
  pages/common/platformio.md
Labels: page edit

#6328 git-push: add command
  pages/common/git-push.md
Labels: page edit

#6306 lipo: add page
  pages/osx/lipo.md
Labels: new command

#6361 todoist: add page
  pages.ro/common/todoist.md
  pages/common/todoist.md
Labels: new command, translation

#6309 vcgencmd: add page
  pages/linux/vcgencmd.md
Labels: new command

#6323 2to3: add Chinese translation
  pages.zh/common/2to3.md
Labels: translation

#6311 hcitool: add page
  pages/linux/hcitool.md
Labels: new command

#6231 linux/[l-m]: add more information link
  pages.es/linux/line.md
  pages.es/linux/lsb_release.md
  pages.es/linux/lsmod.md
  pages.es/linux/lsusb.md
  pages.it/linux/lsmod.md
  pages.it/linux/lsusb.md
  pages.it/linux/modinfo.md
  pages.it/linux/modprobe.md
  pages.ml/linux/lsmod.md
  pages.zh/linux/mac2unix.md
  pages/linux/lastb.md
  pages/linux/lastlog.md
  pages/linux/ldconfig.md
  pages/linux/ldd.md
  pages/linux/light.md
  pages/linux/line.md
  pages/linux/locate.md
  pages/linux/logger.md
  pages/linux/login.md
  pages/linux/logwatch.md
  pages/linux/losetup.md
  pages/linux/lrunzip.md
  pages/linux/lrzip.md
  pages/linux/lrztar.md
  pages/linux/lrzuntar.md
  pages/linux/lsattr.md
  pages/linux/lsb_release.md
  pages/linux/lsblk.md
  pages/linux/lscpu.md
  pages/linux/lshw.md
  pages/linux/lslocks.md
  pages/linux/lsmod.md
  pages/linux/lspci.md
  pages/linux/lsscsi.md
  pages/linux/lsusb.md
  pages/linux/lxc.md
  pages/linux/mac2unix.md
  pages/linux/macchanger.md
  pages/linux/manpath.md
  pages/linux/mcookie.md
  pages/linux/medusa.md
  pages/linux/microcom.md
  pages/linux/mimetype.md
  pages/linux/mke2fs.md
  pages/linux/mkfs.cramfs.md
  pages/linux/mkfs.exfat.md
  pages/linux/mkfs.ext4.md
  pages/linux/mkfs.fat.md
  pages/linux/mkfs.md
  pages/linux/mkfs.minix.md
  pages/linux/mkfs.ntfs.md
  pages/linux/mkfs.vfat.md
  pages/linux/mkisofs.md
  pages/linux/mkswap.md
  pages/linux/modinfo.md
  pages/linux/modprobe.md
  pages/linux/mountpoint.md
  pages/linux/mpstat.md
  pages/linux/mssh.md
  pages/linux/mycli.md
Labels: page edit, mass changes

#6371 machine: add page
  pages/osx/machine.md
Labels: new command

#6377 flameshot: add examples and fix more info link
  pages.fr/linux/flameshot.md
  pages.zh/linux/flameshot.md
  pages/linux/flameshot.md
Labels: page edit

#6380 7z, 7za, 7zr: update Chinese translation
  pages.zh/common/7z.md
  pages.zh/common/7za.md
  pages.zh/common/7zr.md
Labels: translation

#6213 ssh-keygen: add key format conversion
  pages.de/common/ssh-keygen.md
  pages/common/ssh-keygen.md
Labels: page edit, translation

#6379 svgo: remove deprecated --enable=plugin_name example
  pages/common/svgo.md
Labels: page edit

#6375 vim: refresh
  pages.es/common/vim.md
  pages.fr/common/vim.md
  pages.ja/common/vim.md
  pages.pl/common/vim.md
  pages.zh/common/vim.md
Labels: page edit

#6322 updog: add page
  pages/common/updog.md
Labels: new command

#6359 dwebp: add more examples
  pages/common/dwebp.md
Labels: page edit

#6381 [: add Chinese translation
  pages.zh/common/[.md
Labels: translation

#6386 lsattr: add Chinese translation
  pages.zh/linux/lsattr.md
Labels: translation

#6384 alias-pages: add Swedish translation
  contributing-guides/alias-pages.md
Labels: documentation, translation

#5952 style-guide: add Chinese translation
  contributing-guides/style-guide.zh.md
Labels: documentation, translation

#6391 Update style-guide.zh.md
  contributing-guides/style-guide.zh.md
Labels: documentation, translation

#6393 nordvpn: add page
  pages/linux/nordvpn.md
Labels: new command

#6351 dart: add page
  pages/common/dart.md
Labels: new command

#6350 moe: add page
  pages/common/moe.md
Labels: new command

#6394 aurvote: add page
  pages/linux/aurvote.md
Labels: new command

#6404 jmap: add more information link
  pages/common/jmap.md
Labels: page edit

#6400 adduser, apt-*, apt, aptitude, at: update Chinese translation
  pages.zh/linux/adduser.md
  pages.zh/linux/apt-file.md
  pages.zh/linux/apt-get.md
  pages.zh/linux/apt.md
  pages.zh/linux/aptitude.md
  pages.zh/linux/at.md
Labels: translation

#6398 readpe: add page
  pages/linux/readpe.md
Labels: new command

#6355 zm: add page
  pages/common/zm.md
Labels: new command

#6403 jmap: add Chinese translation
  pages.zh/common/jmap.md
Labels: translation

#6414 pfetch: add page
  pages/common/pfetch.md
Labels: new command

#6438 figlet: fix language mixup
  pages.es/common/figlet.md
  pages/common/figlet.md
Labels: page edit, translation

#6435 vi: add page
  pages/common/vi.md
Labels: new command

#6423 grep: add Tamil translation
  pages.ta/common/grep.md
Labels: translation

#6436 r2: add page
  pages/common/r2.md
Labels: new command

#6396 ocrmypdf: updated command for in-place OCR
  pages/common/ocrmypdf.md
Labels: page edit

#6442 ncal: add page
  pages/linux/ncal.md
Labels: new command

#6437 pfetch: add example for running with defaults
  pages/common/pfetch.md
Labels: page edit

#6441 zathura: add page
  pages/linux/zathura.md
Labels: new command

#6374 style-guide: add one Chinese-specific rule
  contributing-guides/style-guide.md
Labels: documentation

#6440 cmd, hyperfine, neofetch: add Italian translation
  pages.it/android/cmd.md
  pages.it/common/hyperfine.md
  pages.it/common/neofetch.md
Labels: translation
