Repository tldr-pages/tldr, pull requests merged in 2021-04, with the labels that each got.

#5660 Add organization member: @MasterOdin
  MAINTAINERS.md
Labels: community

#5654 scripts: add set-more-info-link.py
  scripts/set-more-info-link.py
Labels: tooling

#5663 Update .gitattributes to force GH linguist to recognize pages
  .gitattributes
Labels: tooling

#5655 pamac: add note about AUR packages in the command description
  pages/linux/pamac.md
Labels: page edit

#5662 espanso: add page
  pages/common/espanso.md
Labels: new command

#5665 archinstall: add page
  pages/linux/archinstall.md
Labels: new command

#5666 gist: enhance list/update description
  pages/common/gist.md
Labels: page edit

#5645 autopep8: add page
  pages.nl/common/autopep8.md
  pages/common/autopep8.md
Labels: new command, translation

#5669 sha*sum: add more information link
  pages.hbs/common/sha224sum.md
  pages.hbs/common/sha256sum.md
  pages.hbs/common/sha384sum.md
  pages.hbs/common/sha512sum.md
  pages/common/sha224sum.md
  pages/common/sha256sum.md
  pages/common/sha384sum.md
  pages/common/sha512sum.md
Labels: page edit, translation

#5661 README: update clients' urls
  README.md
Labels: clients, documentation

#5670 spectre-meltdown-checker: add page
  pages/linux/spectre-meltdown-checker.md
Labels: new command

#5673 MAINTAINERS: update @yutyo's username casing
  MAINTAINERS.md
Labels: community

#5671 set-more-info-link.py: hbs -> sh
  scripts/set-more-info-link.py
Labels: tooling

#5674 mongodump: update more information link
  pages/common/mongodump.md
Labels: page edit

#5683 sindresorhus: add page
  pages/common/sindresorhus.md
Labels: new command

#5456 getprop: add page
  pages/android/getprop.md
Labels: new command

#5664 rename pages.hbs to pages.sh
  pages.sh/common/head.md
  pages.sh/common/sh.md
  pages.sh/common/sha1sum.md
  pages.sh/common/sha224sum.md
  pages.sh/common/sha256sum.md
  pages.sh/common/sha384sum.md
  pages.sh/common/sha512sum.md
  pages.sh/common/tail.md
  pages.sh/common/tldr-lint.md
  pages.sh/common/tldr.md
Labels: architecture, mass changes, translation

#5513 encfs: add page
  pages/common/encfs.md
Labels: new command

#5679 *: trim multiple spaces, fix line endings
  pages.de/common/g++.md
  pages.es/linux/apt-cache.md
  pages.fa/common/alias.md
  pages.fa/common/cat.md
  pages.fa/common/cd.md
  pages.fa/common/cp.md
  pages.fa/common/false.md
  pages.fa/common/logname.md
  pages.fa/common/ls.md
  pages.fa/common/nohup.md
  pages.fa/common/sleep.md
  pages.fa/common/tty.md
  pages.fa/common/uname.md
  pages.fa/common/users.md
  pages.fa/linux/whatis.md
  pages.fa/linux/whereis.md
  pages.fa/linux/yum.md
  pages.fr/linux/a2query.md
  pages.fr/linux/apt-get.md
  pages.id/common/yarn.md
  pages.it/common/autossh.md
  pages.it/common/cp.md
  pages.it/common/fastboot.md
  pages.ja/windows/choco-feature.md
  pages.ko/common/asciinema.md
  pages.ko/common/clang.md
  pages.ko/common/convert.md
  pages.ko/common/dig.md
  pages.ko/common/dirname.md
  pages.ta/common/ab.md
  pages.ta/common/ack.md
  pages.zh/common/case.md
  pages.zh/common/rsync.md
  pages.zh/osx/fsck.md
  pages/common/gdalbuildvrt.md
  pages/common/indent.md
  pages/common/recsel.md
  pages/linux/bitwise.md
  pages/linux/ctr.md
  pages/linux/paru.md
  pages/osx/pkgutil.md
Labels: mass changes, page edit, translation

#5678 set-more-info-link.py: remove leading space in Persian label
  scripts/set-more-info-link.py
Labels: tooling

#5680 mongorestore: update more information link
  pages/common/mongorestore.md
Labels: page edit

#5677 *: clean up token syntax delimiters
  pages.de/common/dd.md
  pages.de/common/g++.md
  pages.de/common/lolcat.md
  pages.de/common/nativefier.md
  pages.hi/common/cd.md
  pages.hi/common/mkdir.md
  pages.hi/common/touch.md
  pages.ko/common/apropos.md
  pages.ml/linux/cal.md
  pages.pt_BR/common/aws-s3.md
  pages.pt_BR/windows/dir.md
  pages.zh/common/adb-shell.md
  pages.zh/common/axel.md
  pages.zh/windows/more.md
  pages.zh/windows/repair-bde.md
  pages/common/apropos.md
  pages/common/gdalbuildvrt.md
  pages/common/handbrakecli.md
  pages/common/mp4box.md
  pages/linux/tcptraceroute.md
Labels: mass changes, page edit, translation

#5685 compsize: add page
  pages/linux/compsize.md
Labels: new command

#5667 zip: add list files example and update first example
  pages/common/zip.md
Labels: page edit

#5676 git-commit: add --file example
  pages/common/git-commit.md
Labels: page edit

#5686 getprop: change more information link
  pages/android/getprop.md
Labels: page edit

#5687 MAINTAINERS: fix typo
  MAINTAINERS.md
Labels: documentation

#5455 histexpand: add page
  pages/common/bash.md
  pages/common/histexpand.md
  pages/common/zsh.md
Labels: new command

#5682 vladimyr: add page
  pages/common/vladimyr.md
Labels: new command

#5695 cmark: fix capitalization of "LaTeX"
  pages.it/common/cmark.md
  pages/common/cmark.md
Labels: page edit

#5699 ss: add more info link
  pages/linux/ss.md
Labels: page edit

#5689 rails-destroy: add page
  pages/common/rails-destroy.md
Labels: new command

#5411 deps: update deps
  .husky/.gitignore
  .husky/pre-commit
  package-lock.json
  package.json
Labels: tooling

#5694 sic: add page
  pages/linux/sic.md
Labels: new command

#5697 ip-neighbour: add page
  pages/linux/ip-neighbour.md
Labels: new command

#5711 package.json: Move husky install to prepare run-script
  package.json
Labels: tooling

#5705 Add organization member: @yutyo
  MAINTAINERS.md
Labels: community

#5708 xxh: add page
  pages/common/xxh.md
Labels: new command

#5715 MAINTAINERS: normalize dates, reorder entries
  MAINTAINERS.md
Labels: documentation

#5721 histexpand: edit shells and more information link
  pages/common/histexpand.md
Labels: page edit

#5698 plesk: add page
  pages/common/plesk.md
Labels: new command

#5700 flashrom: add page
  pages/linux/flashrom.md
Labels: new command

#5696 ip-route: add page
  pages/linux/ip-route.md
Labels: new command

#5709 xonsh: add page
  pages/common/xonsh.md
Labels: new command

#5725 pio-device: add page
  pages/common/pio-device.md
Labels: new command

#5693 brew: make a common page for macOS, Linux and Windows
  pages/common/brew.md
  pages/linux/brew.md
  pages/osx/brew.md
Labels: new command, page edit

#5713 pio-package: add page
  pages/common/pio-package.md
Labels: new command

#5719 autopep8, openssl-req, safe, sn, lvm: fix typos
  pages/common/autopep8.md
  pages/common/openssl-req.md
  pages/common/safe.md
  pages/common/sn.md
  pages/linux/lvm.md
Labels: mass changes, page edit

#5720 dolt-config: add page
  pages/common/dolt-config.md
Labels: new command

#5717 ect: refresh
  pages/common/ect.md
Labels: page edit

#5704 peludna-prognoza: add page
  pages/common/peludna-prognoza.md
Labels: new command

#5675 fakedata: add page
  pages/common/fakedata.md
Labels: new command

#5723 MAINTAINERS: add organization member: @marchersimon
  MAINTAINERS.md
Labels: community

#5431 2to3: update grammar and examples
  pages/common/2to3.md
Labels: page edit

#5681 packtpub: add page
  pages/common/packtpub.md
Labels: new command

#5672 xcursorgen: add page
  pages/linux/xcursorgen.md
Labels: new command

#5656 base64: clarify example descriptions that do not edit files inplace
  pages/common/base64.md
Labels: page edit

#5651 ip-link: add page
  pages/linux/ip-link.md
Labels: new command

#5727 pio-platform: add page
  pages/common/pio-platform.md
Labels: new command

#5737 logcat: move to android/
  pages/android/logcat.md
Labels: page edit

#5684 docker-image: add page
  pages/common/docker-image.md
Labels: new command

#5688 homectl: add page
  pages/linux/homectl.md
Labels: new command

#5740 input: add page
  pages/android/input.md
Labels: new command

#5742 cowsay: fix commands for zsh
  pages.it/common/cowsay.md
  pages.ko/common/cowsay.md
  pages/common/cowsay.md
Labels: page edit, translation

#5747 dcode: add page
  pages/common/dcode.md
Labels: new command

#5733 cmus: update example description wording
  pages/linux/cmus.md
Labels: page edit

#5734 mocp: add page
  pages/linux/mocp.md
Labels: new command

#5714 bash, dash, fish, ksh, rbash, sh, zsh: refresh
  pages.sh/common/sh.md
  pages/common/bash.md
  pages/common/dash.md
  pages/common/fish.md
  pages/common/ksh.md
  pages/common/rbash.md
  pages/common/sh.md
  pages/common/zsh.md
  pages/linux/dash.md
Labels: mass changes, page edit, translation

#5748 bundle, mocp: fix typo
  pages/common/bundle.md
  pages/linux/mocp.md
Labels: mass changes, page edit

#5735 nautilus: add page
  pages/linux/nautilus.md
Labels: new command

#5728 pio-lib: add page
  pages/common/pio-lib.md
Labels: new command

#5739 dumpsys: add page
  pages/android/dumpsys.md
Labels: new command

#5736 steam: add page
  pages/common/steam.md
Labels: new command

#5731 gh-pr-merge: add page
  pages/common/gh-pr-merge.md
  pages/common/gh-pr.md
Labels: new command, page edit

#5763 tldrl: remove trailing whitespace
  pages.tr/common/tldrl.md
Labels: page edit, translation

#5760 CONTRIBUTING: improve wording about example count limit
  CONTRIBUTING.md
Labels: documentation

#5764 espanso: fix "edit config" command
  pages/common/espanso.md
Labels: page edit

#5751 stormlock: add page
  pages/common/stormlock.md
Labels: new command

#5762 tar: remove extra example
  pages.ru/common/tar.md
Labels: page edit, translation

#5761 ip: fix example formatting
  pages.fr/linux/ip.md
Labels: page edit, translation

#5755 ansible: add list groups in an inventory example
  pages/common/ansible.md
Labels: page edit

#5753 diskonaut: add page
  pages/common/diskonaut.md
Labels: new command

#5729 uuidgen: add page
  pages/osx/uuidgen.md
Labels: new command

#5759 Reference dirs builtin in pushd/popd
  pages/common/popd.md
  pages/common/pushd.md
  pages/linux/pushd.md
  pages/osx/popd.md
Labels: mass changes, page edit

#5772 sbcl: add page
  pages/common/sbcl.md
Labels: new command

#5756 ansible-inventory: add page
  pages/common/ansible-inventory.md
Labels: new command

#5771 ssh: remove -C and use SOCKS port
  pages.de/common/ssh.md
  pages.fr/common/ssh.md
  pages/common/ssh.md
Labels: page edit

#5765 openttd: add page
  pages/common/openttd.md
Labels: new command

#5746 shellcheck: refresh
  pages/common/shellcheck.md
Labels: page edit

#5528 multiple pages: replace all die.net links
  pages.de/common/pdflatex.md
  pages.de/linux/cfdisk.md
  pages.fr/linux/ifdown.md
  pages.fr/linux/ifup.md
  pages.zh/linux/logsave.md
  pages/common/iotop.md
  pages/common/pdflatex.md
  pages/common/sponge.md
  pages/common/transmission-create.md
  pages/linux/addpart.md
  pages/linux/aplay.md
  pages/linux/arecord.md
  pages/linux/cfdisk.md
  pages/linux/dumpe2fs.md
  pages/linux/e2freefrag.md
  pages/linux/e2image.md
  pages/linux/efibootmgr.md
  pages/linux/expect.md
  pages/linux/filefrag.md
  pages/linux/ifdown.md
  pages/linux/iftop.md
  pages/linux/ifup.md
  pages/linux/isosize.md
  pages/linux/iwconfig.md
  pages/linux/jpegtran.md
  pages/linux/lftp.md
  pages/linux/logsave.md
  pages/linux/ltrace.md
  pages/linux/mdadm.md
  pages/linux/named.md
  pages/linux/pmount.md
  pages/linux/semanage.md
  pages/linux/snmpwalk.md
  pages/linux/vipw.md
  pages/linux/vmstat.md
  pages/osx/xar.md
Labels: mass changes, page edit, translation

#5767 gh-workflow: add page
  pages/common/gh-workflow.md
Labels: new command

#5766 gh-run: add page
  pages/common/gh-run.md
Labels: new command

#5752 dex: add page
  pages/linux/dex.md
Labels: new command

#5744 tracepath: add page
  pages/linux/tracepath.md
Labels: new command

#5775 MAINTAINERS: add @Waples to collaborators
  MAINTAINERS.md
Labels: community

#5718 autossh: refresh
  pages/common/autossh.md
Labels: page edit

#5738 user*, group*, add*, group*: add more info links
  pages.es/linux/groupdel.md
  pages.es/linux/userdel.md
  pages.fr/linux/useradd.md
  pages.fr/linux/userdel.md
  pages.fr/linux/usermod.md
  pages.it/linux/adduser.md
  pages.it/linux/deluser.md
  pages.ko/linux/deluser.md
  pages.pt_BR/linux/adduser.md
  pages.zh/linux/adduser.md
  pages/linux/adduser.md
  pages/linux/deluser.md
  pages/linux/groupadd.md
  pages/linux/groupdel.md
  pages/linux/groupmod.md
  pages/linux/useradd.md
  pages/linux/userdel.md
  pages/linux/usermod.md
Labels: mass changes, page edit

#5710 apt-*: add more info links; apt-file: add regex search example
  pages.de/linux/apt-add-repository.md
  pages.de/linux/apt-get.md
  pages.de/linux/apt.md
  pages.es/linux/apt-add-repository.md
  pages.es/linux/apt-cache.md
  pages.es/linux/apt-file.md
  pages.es/linux/apt-get.md
  pages.es/linux/apt-key.md
  pages.es/linux/apt-mark.md
  pages.es/linux/apt.md
  pages.es/linux/aptitude.md
  pages.fr/linux/apt-add-repository.md
  pages.fr/linux/apt-cache.md
  pages.fr/linux/apt-file.md
  pages.fr/linux/apt-get.md
  pages.fr/linux/apt-mark.md
  pages.fr/linux/apt.md
  pages.it/linux/apt-add-repository.md
  pages.it/linux/apt-cache.md
  pages.it/linux/apt-file.md
  pages.it/linux/apt-get.md
  pages.it/linux/apt-key.md
  pages.it/linux/apt-mark.md
  pages.it/linux/apt.md
  pages.ml/linux/apt.md
  pages.pt_BR/linux/apt-cache.md
  pages.pt_BR/linux/apt-file.md
  pages.pt_BR/linux/apt-get.md
  pages.pt_BR/linux/apt-key.md
  pages.pt_BR/linux/apt-mark.md
  pages.pt_BR/linux/apt.md
  pages.pt_BR/linux/aptitude.md
  pages.tr/linux/apt-get.md
  pages.tr/linux/aptitude.md
  pages.zh/linux/apt-cache.md
  pages.zh/linux/apt-file.md
  pages.zh/linux/apt-get.md
  pages.zh/linux/apt-key.md
  pages.zh/linux/apt-mark.md
  pages.zh/linux/apt.md
  pages.zh/linux/aptitude.md
  pages/linux/apt-add-repository.md
  pages/linux/apt-cache.md
  pages/linux/apt-file.md
  pages/linux/apt-get.md
  pages/linux/apt-key.md
  pages/linux/apt-mark.md
  pages/linux/apt.md
  pages/linux/aptitude.md
  pages/linux/netselect-apt.md
Labels: mass changes, page edit, translation

#5778 docker*: add Italian translation
  pages.it/common/docker-build.md
  pages.it/common/docker-compose.md
  pages.it/common/docker-cp.md
  pages.it/common/docker-exec.md
  pages.it/common/docker-image.md
  pages.it/common/docker-inspect.md
  pages.it/common/docker-logs.md
  pages.it/common/docker-network.md
Labels: translation

#5776 rusnapshot: add page
  pages/linux/rusnapshot.md
Labels: new command

#5782 grep: edit more information link
  pages.de/common/grep.md
  pages.fr/common/grep.md
  pages/common/grep.md
Labels: page edit, translation

#5508 tldr: edit examples
  pages/common/tldr.md
Labels: page edit

#5754 chore(deps): update tldr-lint to 0.0.11
  package-lock.json
  package.json
  scripts/test.sh
Labels: tooling

#5757 minisign: add English and German pages
  pages.de/common/minisign.md
  pages/common/minisign.md
Labels: new command, translation

#5507 add new animated svg of tar command
  README.md
  images/screenshot.png
  images/tldr.svg
Labels: documentation

#5783 qjoypad: add page
  pages/linux/qjoypad.md
Labels: new command

#5784 systemd-analyze: add plot and dot examples
  pages/linux/systemd-analyze.md
Labels: page edit

#5793 pacman-files: fix typo
  pages/linux/pacman-files.md
Labels: page edit

#5794 pacman-files: fix typo #2
  pages/linux/pacman-files.md
Labels: page edit

#5750 bandwhich: add page
  pages/common/bandwhich.md
Labels: new command

#5745 sfill: add page
  pages/linux/sfill.md
Labels: new command

#5690 xh: add page
  pages/common/xh.md
Labels: new command

#5758 age: add page
  pages.de/common/age.md
  pages/common/age.md
Labels: new command, translation

#5795 genfstab, pacstrap: mention that these are Arch-specific tools
  pages/linux/genfstab.md
  pages/linux/pacstrap.md
Labels: mass changes, page edit

#5777 cut, grep, tee, wc: add Spanish translations
  pages.es/common/cut.md
  pages.es/common/grep.md
  pages.es/common/tee.md
  pages.es/common/wc.md
Labels: translation

#5716 firebase: refresh
  pages/common/firebase.md
Labels: page edit

#5797 atom, clear, convert, df: sync French translations with English pages
  pages.fr/common/atom.md
  pages.fr/common/clear.md
  pages.fr/common/convert.md
  pages.fr/common/df.md
  pages/common/df.md
Labels: page edit, translation

#5804 ansible: sync French translation with English page (list groups)
  pages.fr/common/ansible.md
Labels: page edit, translation

#5799 virt-install: add --name option to example
  pages/common/virt-install.md
Labels: page edit

#5800 virt-clone: add page
  pages/common/virt-clone.md
Labels: new command

#5805 cp: sync French translations with English page (remove "--parents")
  pages.fr/common/cp.md
Labels: page edit, translation

#5796 nmap: add Chinese translation
  pages.zh/common/nmap.md
Labels: translation

#5812 nmap: put command flags in example descriptions in backticks
  pages.es/common/nmap.md
  pages.it/common/nmap.md
  pages.zh/common/nmap.md
  pages/common/nmap.md
Labels: page edit, translation

#5807 android/*: fix command descriptions
  pages/android/dumpsys.md
  pages/android/getprop.md
  pages/android/input.md
  pages/android/logcat.md
  pages/android/wm.md
Labels: page edit

#5816 MAINTAINERS: add @aherst to collaborators
  MAINTAINERS.md
Labels: community

#5811 rolldice: add page
  pages/linux/rolldice.md
Labels: new command

#5822 bat: fix typos on French page
  pages.fr/common/bat.md
Labels: page edit, translation

#5825 histexpand, history: add Spanish translation
  pages.es/common/histexpand.md
  pages.es/common/history.md
  pages/common/history.md
Labels: page edit, translation

#5826 rolldice: add pt_BR translation
  pages.pt_BR/linux/rolldice.md
Labels: translation

#5803 dmenu: add Chinese translation
  pages.zh/linux/dmenu.md
Labels: translation

#5801 debuild: add Chinese translation
  pages.zh/linux/debuild.md
Labels: translation

#5808 android/*: add German translation
  pages.de/android/am.md
  pages.de/android/cmd.md
  pages.de/android/dalvikvm.md
  pages.de/android/dumpsys.md
  pages.de/android/getprop.md
  pages.de/android/input.md
  pages.de/android/logcat.md
  pages.de/android/pm.md
  pages.de/android/settings.md
  pages.de/android/wm.md
Labels: translation

#5802 debootstrap: add Chinese translation
  pages.zh/linux/debootstrap.md
Labels: translation

#5819 xplr: add page
  pages/common/xplr.md
Labels: new command

#5827 pio-run: add page
  pages/common/pio-run.md
Labels: new command

#5820 protector: add page
  pages/common/protector.md
Labels: new command

#5773 *: fix more information text in French translation
  pages.fr/common/ansible.md
  pages.fr/linux/a2disconf.md
  pages.fr/linux/a2dismod.md
  pages.fr/linux/a2dissite.md
  pages.fr/linux/a2ensite.md
  pages.fr/linux/a2query.md
  pages.fr/linux/apache2ctl.md
  pages.fr/linux/ifdown.md
  pages.fr/linux/ifup.md
  pages.fr/linux/ip-address.md
  pages.fr/linux/ip.md
Labels: mass changes, page edit, translation

#5829 pacman-files: include see also
  pages/linux/pacman-files.md
Labels: page edit

#5831 tlp, tlp-stat: fix description
  pages/linux/tlp-stat.md
  pages/linux/tlp.md
Labels: mass changes, page edit

#5828 chronyc, ntpq: add page
  pages/linux/chronyc.md
  pages/linux/ntpq.md
Labels: mass changes, new command

#5838 lua: add missing apostrophe in French translation
  pages.fr/common/lua.md
Labels: page edit, translation

#5813 qtcreator: add page
  pages/common/qtcreator.md
Labels: new command

#5834 kate: add page
  pages/common/kate.md
Labels: new command

#5818 nu: add page
  pages/common/nu.md
Labels: new command

#5824 virt-sysprep: add page
  pages/common/virt-sysprep.md
Labels: new command

#5835 x11docker: add page
  pages/common/x11docker.md
Labels: new command

#5833 dolphin: add page
  pages/linux/dolphin.md
Labels: new command

#5823 acme.sh: add page
  pages/common/acme.sh.md
Labels: new command

#5842 kate: improve remote document example
  pages/common/kate.md
Labels: page edit

#5691 passwd: remove invalid example
  pages/common/passwd.md
Labels: page edit
