Repository tldr-pages/tldr, pull requests merged in 2021-12, with the labels that each got.

#7424 a2disiste, a2ensite, a2query: add pt_PT translation
  pages.pt_PT/linux/a2dissite.md
  pages.pt_PT/linux/a2ensite.md
  pages.pt_PT/linux/a2query.md
Labels: translation

#7494 orca-c: add page
  pages/common/orca-c.md
Labels: new command

#7500 COMMUNITY-ROLES: fix link
  COMMUNITY-ROLES.md
Labels: documentation

#7439 vcvarsall: add page
  pages/windows/vcvarsall.md
Labels: new command

#7147 hping3: add page
  pages/common/hping3.md
Labels: new command, hacktoberfest-accepted

#7502 ftp: add example to connect via IP
  pages/common/ftp.md
Labels: page edit

#7114 vim: add German translation
  pages.de/common/vim.md
Labels: waiting, translation, hacktoberfest-accepted

#7484 resolvectl: add page
  pages/linux/resolvectl.md
Labels: new command

#7499 makepkg: refresh
  pages/linux/makepkg.md
Labels: page edit

#7111 go-install: add page
  pages/common/go-install.md
Labels: new command, waiting, hacktoberfest-accepted

#7402 windows/get-*: add PowerShell-only notice
  pages/windows/get-childitem.md
  pages/windows/get-content.md
  pages/windows/get-filehash.md
  pages/windows/get-history.md
Labels: page edit

#7474 typeorm: add page
  pages/common/typeorm.md
Labels: new command, review needed

#7452 xset: add page
  pages/linux/xset.md
Labels: new command, review needed

#7491 jadx: add page
  pages/common/jadx.md
Labels: new command

#6766 cgroups: add page
  pages/linux/cgroups.md
Labels: new command, hacktoberfest-accepted, review needed

#7495 style-guide: mention tldr-lint instead of tldrl
  contributing-guides/style-guide.de.md
  contributing-guides/style-guide.md
  contributing-guides/style-guide.zh.md
Labels: documentation

#7516 groff: add --RAW-CONTROL-CHARS to pager example
  pages/common/groff.md
Labels: page edit, review needed, minor change

#7520 vswhere: remove invalid quotes in example
  pages/windows/vswhere.md
Labels: page edit

#7519 nmtui: add link in Italian translation
  pages.it/linux/nmtui.md
Labels: translation

#7299 daps: add page
  pages/common/daps.md
Labels: new command, waiting

#7275 ddcutil: add page
  pages/linux/ddcutil.md
Labels: new command, waiting

#7523 MAINTAINERS: add @258204 to collaborators
  MAINTAINERS.md
Labels: community

#7443 if: add page
  pages/windows/if.md
Labels: new command, review needed

#7442 for: add page
  pages/windows/for.md
Labels: new command, review needed

#7518 nvm: update versions in command description
  pages.de/common/nvm.md
  pages.id/common/nvm.md
  pages/common/nvm.md
Labels: page edit, translation

#7435 ngs: add page
  pages/common/ngs.md
Labels: new command, review needed

#7489 age: add French translation
  pages.fr/common/age.md
Labels: translation, review needed

#7513 msiexec: add page
  pages/windows/msiexec.md
Labels: new command

#7542 MAINTAINERS: add organization owner: @CleanMachine1
  MAINTAINERS.md
Labels: community

#7543 taskset: fix syntax
  pages/linux/taskset.md
Labels: page edit

#7501 doctl-apps: add page
  pages/common/doctl-apps.md
Labels: new command, review needed

#7515 volta: add page
  pages/common/volta.md
Labels: new command

#7544 chcon: move from common to linux platform
  pages.it/linux/chcon.md
  pages.ko/linux/chcon.md
  pages/linux/chcon.md
Labels: page edit

#7509 git-terminal: update instructions to amend author
  contributing-guides/git-terminal.md
Labels: documentation, review needed

#7548 git-terminal: fix typos
  contributing-guides/git-terminal.md
Labels: documentation, minor change

#7529 declare, local, typeset: add pages
  pages/common/declare.md
  pages/common/local.md
  pages/common/typeset.md
Labels: new command

#7524 doctl-compute-droplet: add page
  pages/common/doctl-compute-droplet.md
Labels: new command, review needed

#7539 MAINTAINERS: remove @zlatanvasovic from organization owners
  MAINTAINERS.md
Labels: community

#7555 pridecat: add page
  pages/linux/pridecat.md
Labels: new command

#7535 for: page update
  pages/windows/for.md
Labels: page edit

#7527 doctl-balance: add page
  pages/common/doctl-balance.md
Labels: new command

#7565 spctl: add page
  pages/osx/spctl.md
Labels: new command

#7488 vegeta: add French translation
  pages.fr/common/vegeta.md
Labels: translation

#7498 virt-install: update page
  pages/common/virt-install.md
Labels: page edit

#7455 btrfs-restore: add page
  pages/linux/btrfs-restore.md
Labels: new command, waiting

#7508 abbr: add page
  pages/linux/abbr.md
Labels: new command, waiting, review needed

#7571 exercism: add page
  pages/common/exercism.md
Labels: new command

#7576 namcap: fix error
  pages/linux/namcap.md
Labels: page edit

#7481 if: update page
  pages/common/if.md
Labels: page edit

#7575 updpkgsums: add page
  pages/linux/updpkgsums.md
Labels: new command

#7547 dunstctl: add page
  pages/linux/dunstctl.md
Labels: new command

#7573 colorls: add page
  pages/common/colorls.md
Labels: new command, review needed

#7536 set-more-info-link.py, translation-templates/*: add Uzbek language
  contributing-guides/translation-templates/alias-pages.md
  contributing-guides/translation-templates/common-arguments.md
  contributing-guides/translation-templates/subcommand-mention.md
  scripts/set-more-info-link.py
Labels: documentation, tooling, review needed

#7577 makepkg: add commands
  pages/linux/makepkg.md
Labels: page edit

#7574 xbps: fix --sync and --update examples
  pages/linux/xbps.md
Labels: page edit, review needed, minor change

#7453 btrfs-balance: add page
  pages/linux/btrfs-balance.md
Labels: new command, review needed

#7579 makepkg: fix command to match standard
  pages/linux/makepkg.md
Labels: page edit, review needed, minor change

#7454 btrfs-property: add page
  pages/linux/btrfs-property.md
Labels: new command, review needed

#7364 print: add Turkish translation
  pages.tr/linux/print.md
Labels: translation

#7511 nvm: add page
  pages/windows/nvm.md
Labels: new command, review needed

#7493 git-filter-repo: add page
  pages/common/git-filter-repo.md
Labels: new command

#7558 glab-repo: add page
  pages/common/glab-repo.md
Labels: new command

#7589 git*: add Turkish translation II
  pages.tr/common/git-flow.md
  pages.tr/common/git-rev-list.md
  pages.tr/common/git-send-email.md
  pages.tr/common/github-label-sync.md
  pages.tr/common/gitlab-ctl.md
  pages.tr/common/gitlab-runner.md
  pages.tr/common/gitlab.md
Labels: translation, review needed

#7572 mu: add page
  pages/common/mu.md
Labels: new command, review needed

#7580 smalltalkci: add page
  pages/common/smalltalkci.md
Labels: new command, review needed

#7564 minicom: add page
  pages/linux/minicom.md
Labels: new command

#7537 msiexec: add Indonesian translation
  pages.id/windows/msiexec.md
Labels: translation

#7567 docker: add docker images example
  pages.es/common/docker.md
  pages.fr/common/docker.md
  pages/common/docker.md
Labels: page edit, translation

#7591 github-label-sync: use repo as more information link
  pages.tr/common/github-label-sync.md
  pages/common/github-label-sync.md
Labels: page edit, translation, minor change

#7588 sacctmgr: add Chinese translation
  pages.zh/linux/sacctmgr.md
  pages/linux/sacctmgr.md
Labels: page edit, translation

#7583 keychain: add page
  pages/common/keychain.md
Labels: new command

#7599 git-pr: fix grammar
  pages/common/git-pr.md
Labels: page edit, review needed, minor change

#7598 git-delete-tag: add backticks to git-extras
  pages/common/git-delete-tag.md
Labels: page edit, review needed, minor change
