Repository tldr-pages/tldr, pull requests merged in 2021-05, with the labels that each got.

#5864 gnome-extensions: fix typo
  pages/linux/gnome-extensions.md
Labels: page edit

#5815 pio-test: add page
  pages/common/pio-test.md
Labels: new command

#5432 7z, 7za, 7zr: updates
  pages/common/7z.md
  pages/common/7za.md
  pages/common/7zr.md
Labels: page edit

#5849 ical: add page
  pages/common/ical.md
Labels: new command

#5839 German pages: refresh outdated translations
  pages.de/common/ansible.md
  pages.de/common/cp.md
  pages.de/common/fish.md
  pages.de/common/git-add.md
  pages.de/common/git-apply.md
  pages.de/common/git-clone.md
  pages.de/common/git-commit.md
  pages.de/common/git-init.md
  pages.de/common/ls.md
  pages.de/common/zsh.md
  pages.de/linux/apt.md
Labels: mass changes, page edit, translation

#5861 yes: change verb 'uitvoeren' to 'printen' in Dutch translation
  pages.nl/common/yes.md
Labels: page edit, translation

#5857 uuencode: add page
  pages/common/uuencode.md
Labels: new command

#5862 xkill, xxd, nvim: add italian translation
  pages.it/common/nvim.md
  pages.it/common/xkill.md
  pages.it/common/xxd.md
Labels: translation

#5246 a2dismod to avahi-browse: add Chinese translation
  pages.zh/linux/a2disconf.md
  pages.zh/linux/a2dismod.md
  pages.zh/linux/a2dissite.md
  pages.zh/linux/a2enconf.md
  pages.zh/linux/a2enmod.md
  pages.zh/linux/a2ensite.md
  pages.zh/linux/a2query.md
  pages.zh/linux/ac.md
  pages.zh/linux/add-apt-repository.md
  pages.zh/linux/addpart.md
  pages.zh/linux/addr2line.md
  pages.zh/linux/amixer.md
  pages.zh/linux/apache2ctl.md
  pages.zh/linux/aplay.md
  pages.zh/linux/apport-bug.md
  pages.zh/linux/apt-add-repository.md
  pages.zh/linux/archlinux-java.md
  pages.zh/linux/arecored.md
  pages.zh/linux/arithmetic.md
  pages.zh/linux/ark.md
  pages.zh/linux/ascii.md
  pages.zh/linux/asterisk.md
  pages.zh/linux/auracle.md
  pages.zh/linux/authconfig.md
  pages.zh/linux/autorandr.md
  pages.zh/linux/avahi-browse.md
Labels: translation

#5859 tar: fix mnemonic for f
  pages/common/tar.md
Labels: page edit

#5865 pio-init: add alias page
  pages/common/pio-init.md
Labels: new command

#5870 more: add Spanish translation
  pages.es/common/more.md
Labels: translation

#5863 pnpm, pnpx: add page
  pages/common/pnpm.md
  pages/common/pnpx.md
Labels: new command

#5882 MAINTAINERS: add @nicokosi to collaborators
  MAINTAINERS.md
Labels: community

#5878 http: use long arguments
  pages.pl/common/http.md
  pages/common/http.md
Labels: page edit, translation

#5879 wget: use long arguments
  pages.it/common/wget.md
  pages.zh/common/wget.md
  pages/common/wget.md
Labels: page edit, translation

#5880 npm: use long argument --global
  pages.de/common/npm.md
  pages.id/common/npm.md
  pages/common/npm.md
Labels: page edit, translation

#5860 tar: add verbose argument to extract example
  pages/common/tar.md
Labels: page edit

#5847 virsh-undefine: add page
  pages/common/virsh-undefine.md
Labels: new command

#5872 curl: use long arguments
  pages.de/common/curl.md
  pages.id/common/curl.md
  pages.it/common/curl.md
  pages.ko/common/curl.md
  pages.pt_BR/common/curl.md
  pages.zh/common/curl.md
  pages/common/curl.md
Labels: page edit, translation

#5893 git-*: sync Spanish translation
  pages.es/common/git-config.md
  pages.es/common/git-lfs.md
  pages.es/common/git-log.md
  pages.es/common/git-remote.md
  pages.es/common/git-restore.md
  pages.es/common/git-show.md
  pages.es/common/git-status.md
  pages.es/common/git-switch.md
Labels: translation

#5899 apt: fix typo in German translation
  pages.de/linux/apt.md
Labels: translation

#5885 airmon-ng: add pt_BR translation
  pages.pt_BR/common/airmon-ng.md
Labels: translation

#5881 more: add examples and link
  pages.es/common/more.md
  pages/common/more.md
Labels: page edit, translation

#5889 gradle: add tasks examples
  pages/common/gradle.md
Labels: page edit

#5874 [, arduino-builder, arduino, bash, clear: add pt-BR translation
  pages.pt_BR/common/[.md
  pages.pt_BR/common/arduino-builder.md
  pages.pt_BR/common/arduino.md
  pages.pt_BR/common/bash.md
  pages.pt_BR/common/clear.md
Labels: translation

#5895 virsh-domblklist: add page
  pages/common/virsh-domblklist.md
Labels: new command

#5907 cp: add Japanese translation
  pages.ja/common/cp.md
Labels: translation

#5906 pwd: add Japanese translation
  pages.ja/common/pwd.md
Labels: translation

#5905 tar: add Japanese translation
  pages.ja/common/tar.md
Labels: translation

#5903 ls: add Japanese translation
  pages.ja/common/ls.md
Labels: translation

#5896 Add Discord Slash Command Bot
  README.md
Labels: clients, documentation

#5913 journalctl: emphasize command line argument in example descriptions
  pages/linux/journalctl.md
Labels: page edit

#5894 virsh-connect: add page
  pages/common/virsh-connect.md
Labels: new command

#5891 ibmcloud-login: add page
  pages/common/ibmcloud-login.md
Labels: new command

#5830 multiple pages: normalize `regular expression` instead of `regex`, `regexp` or `pattern`
  pages.fr/common/grep.md
  pages.fr/common/jest.md
  pages.fr/common/z.md
  pages.id/common/nvim.md
  pages.it/common/ag.md
  pages.it/common/csvgrep.md
  pages.it/common/vim.md
  pages.pl/common/ack.md
  pages.pt_BR/linux/csplit.md
  pages.pt_PT/common/history.md
  pages/android/logcat.md
  pages/common/csvgrep.md
  pages/common/fgrep.md
  pages/common/gem.md
  pages/common/grex.md
  pages/common/httpflow.md
  pages/common/jest.md
  pages/common/linkchecker.md
  pages/common/mlr.md
  pages/common/mocha.md
  pages/common/nvim.md
  pages/common/recsel.md
  pages/common/rg.md
  pages/common/sd.md
  pages/common/sed.md
  pages/common/stow.md
  pages/common/vim.md
  pages/common/z.md
  pages/common/zmv.md
  pages/linux/apt-file.md
  pages/linux/auracle.md
  pages/linux/csplit.md
  pages/linux/inotifywait.md
  pages/linux/pacman-files.md
  pages/linux/zgrep.md
  pages/osx/rename.md
  pages/osx/sed.md
Labels: mass changes, page edit, translation

#5781 speedtest, speedtest-cli: refresh
  pages/common/speedtest-cli.md
  pages/common/speedtest.md
  pages/linux/speedtest.md
Labels: page edit

#5922 steamcmd: add page
  pages/common/steamcmd.md
Labels: new command

#5876 mmcli: add page
  pages/linux/mmcli.md
Labels: new command

#5935 git-whatchanged: add page
  pages/common/git-whatchanged.md
Labels: new command

#5944 virsh-list: add page
  pages/common/virsh-list.md
Labels: new command

#5943 mkvmerge: add page
  pages/common/mkvmerge.md
Labels: new command

#5911 ts-node: add page
  pages/common/ts-node.md
Labels: new command

#5749 exa: add --header, --git and --git-ignore examples
  pages/common/exa.md
Labels: page edit

#5947 git-cp: add page
  pages/common/git-cp.md
Labels: new command

#5786 boltctl: add page
  pages.zh/linux/boltctl.md
  pages/linux/boltctl.md
Labels: new command, translation

#5948 git-delete-tag: add page
  pages/common/git-delete-tag.md
Labels: new command

#5950 git-rename-branch: add page
  pages/common/git-rename-branch.md
Labels: new command

#5866 kdeconnect-cli: add page
  pages/common/kdeconnect-cli.md
Labels: new command

#5900 hashcat: add page
  pages/linux/hashcat.md
Labels: new command

#5855 ls, touch: add examples
  pages/common/ls.md
  pages/common/touch.md
Labels: page edit

#5920 change `login`/`logout` to `log in`/`log out`
  pages/common/aws-google-auth.md
  pages/common/balena.md
  pages/common/bosh.md
  pages/common/firebase.md
  pages/common/gcloud.md
  pages/common/gh-auth.md
  pages/common/gist.md
  pages/common/heroku.md
  pages/common/k6.md
  pages/common/lpass.md
  pages/common/molecule.md
  pages/common/netlify.md
  pages/common/oc.md
  pages/common/packtpub.md
  pages/common/pio-account.md
  pages/common/rtv.md
  pages/common/snyk.md
  pages/common/youtube-viewer.md
  pages/linux/login.md
  pages/windows/azcopy.md
Labels: mass changes, page edit

#5852 acme.sh-dns: add page; acme.sh: remove example
  pages/common/acme.sh-dns.md
  pages/common/acme.sh.md
Labels: new command, page edit

#5901 starship: add page
  pages/common/starship.md
Labels: new command

#5789 pdfjam: add page
  pages/common/pdfjam.md
Labels: new command

#5912 distccd: add page
  pages/common/distccd.md
Labels: new command

#5892 uuid: add page, uuidgen: update description
  pages/linux/uuid.md
  pages/linux/uuidgen.md
Labels: new command, page edit

#5959 git-browse: add page
  pages/common/git-browse.md
Labels: new command

#5957 README: Remove tldr.ooops.me
  README.md
Labels: clients, documentation

#5963 MAINTAINERS: add @CleanMachine1 to collaborators
  MAINTAINERS.md
Labels: community

#5954 dmesg: add Chinese translation
  pages.zh/linux/dmesg.md
Labels: translation

#5966 git-brv: add page
  pages/common/git-brv.md
Labels: new command

#5968 git-commits-since: add page
  pages/common/git-commits-since.md
Labels: new command

#5946 git-verify-commit: add page
  pages/common/git-verify-commit.md
Labels: new command

#5967 dconf, dconf-write: add page
  pages/linux/dconf-write.md
  pages/linux/dconf.md
Labels: new command

#5973 find: add example to find and delete empty files
  pages/common/find.md
Labels: page edit

#5244 btrfs*: add Chinese translation
  pages.zh/linux/btrfs-device.md
  pages.zh/linux/btrfs-filesystem.md
  pages.zh/linux/btrfs-scrub.md
  pages.zh/linux/btrfs-subvolume.md
  pages.zh/linux/btrfs.md
Labels: translation

#5977 jar: add Chinese translation
  pages.zh/common/jar.md
Labels: translation

#5960 git-archive-file: add page
  pages/common/git-archive-file.md
Labels: new command

#5979 git-alias: add page
  pages/common/git-alias.md
Labels: new command

#5971 uudecode: add page
  pages/common/uudecode.md
Labels: new command

#5974 git-repl: add page
  pages/common/git-repl.md
Labels: new command

#5972 starship-init: add page
  pages/common/starship-init.md
Labels: new command

#5982 git-create-branch: add page
  pages/common/git-create-branch.md
Labels: new command

#5980 git-undo: add page
  pages/common/git-undo.md
Labels: new command

#5983 aria2: convert into page alias for aria2c
  pages/common/aria2.md
Labels: page edit

#5951 git-authors: add page
  pages/common/git-authors.md
Labels: new command

#5985 wp: add page
  pages/common/wp.md
Labels: new command

#5984 bfg: add page
  pages/common/bfg.md
Labels: new command

#5991 uuidd: add page
  pages/linux/uuidd.md
Labels: new command

#5970 git-count: add page
  pages/common/git-count.md
Labels: new command

#5995 rg: improved fixed string suggestion
  pages/common/rg.md
Labels: page edit

#5990 git-init: add --initial-branch example
  pages.es/common/git-init.md
  pages/common/git-init.md
Labels: page edit, translation

#5994 MAINTAINERS: add @SethFalco to collaborators
  MAINTAINERS.md
Labels: community

#5998 MAINTAINERS: add @Waples to org members
  MAINTAINERS.md
Labels: community

#5992 shuf: improve usage example and its description
  pages/common/shuf.md
Labels: page edit

#6001 shuf: expand short options to long ones
  pages/common/shuf.md
Labels: page edit

#5934 cowsay: refresh
  pages/common/cowsay.md
Labels: page edit

#5981 git-local-commits: add page
  pages/common/git-local-commits.md
Labels: new command

#6005 jarsigner: add Chinese translation
  pages.zh/common/jarsigner.md
Labels: translation

#5969 stl2gts: add page
  pages/common/stl2gts.md
Labels: new command

#5996 gh-secret-set: add page
  pages/common/gh-secret-set.md
  pages/common/gh-secret.md
Labels: new command

#6004 mv: add move multiple source paths to a directory example
  pages/common/mv.md
Labels: page edit

#6003 git-reset-file: add page
  pages/common/git-reset-file.md
Labels: new command

#6007 josm: add page
  pages/common/josm.md
Labels: new command

#6009 git-root: add page
  pages/common/git-root.md
Labels: new command

#6010 git-delta: add page
  pages/common/git-delta.md
Labels: new command

#6016 javadoc: add Chinese translation
  pages.zh/common/javadoc.md
Labels: translation

#5999 screenkey: add page
  pages/linux/screenkey.md
Labels: new command

#5902 pio-remote: add page
  pages/common/pio-remote.md
Labels: new command

#6015 git-touch: add page
  pages/common/git-touch.md
Labels: new command

#5939 git-mailinfo: add page
  pages/common/git-mailinfo.md
Labels: new command

#6017 jps: add more information link
  pages/common/jps.md
Labels: page edit

#6002 git-effort: add page
  pages/common/git-effort.md
Labels: new command

#6013 git-fork: add page
  pages/common/git-fork.md
Labels: new command

#6021 am: add Chinese translation
  pages.zh/android/am.md
Labels: translation

#6018 jps: add Chinese translation
  pages.zh/common/jps.md
Labels: translation

#6025 getprop: add Chinese translation
  pages.zh/android/getprop.md
Labels: translation

#6026 input: add Chinese translation
  pages.zh/android/input.md
Labels: translation

#6031 wm: add Chinese translation
  pages.zh/android/wm.md
Labels: translation

#6032 etcd: add Chinese translation
  pages.zh/common/etcd.md
Labels: translation

#6033 exit: add Chinese translation
  pages.zh/common/exit.md
Labels: translation

#6030 wm: add more information link
  pages/android/wm.md
Labels: page edit

#6029 settings: add Chinese translation
  pages.zh/android/settings.md
Labels: translation

#6023 dalvikvm: add Chinese translation
  pages.zh/android/dalvikvm.md
Labels: translation

#6022 cmd: add Chinese translation
  pages.zh/android/cmd.md
Labels: translation

#6020 mongod: add Chinese translation
  pages.zh/common/mongod.md
Labels: translation

#6014 watch: add pt_BR translation
  pages.pt_BR/linux/watch.md
Labels: translation

#6034 git-graft: add page
  pages/common/git-graft.md
Labels: new command

#5987 git-authors: fix example descriptions
  pages/common/git-authors.md
Labels: page edit

#6040 gh-pr-merge: add --help example
  pages/common/gh-pr-merge.md
Labels: page edit

#6038 truncate: add example
  pages/common/truncate.md
Labels: page edit

#6037 git-extras: add page
  pages/common/git-extras.md
Labels: new command

#6012 git-fame: add page
  pages/common/git-fame.md
Labels: new command

#6024 dumpsys: add Chinese translation
  pages.zh/android/dumpsys.md
Labels: translation

#6027 logcat: add Chinese translation
  pages.zh/android/logcat.md
Labels: translation

#6019 make: add Chinese translation
  pages.zh/common/make.md
Labels: translation

#6044 kdocker: add page
  pages/linux/kdocker.md
Labels: new command

#6048 offlineimap: add page
  pages/common/offlineimap.md
Labels: new command

#6043 conda-create: add page
  pages/common/conda-create.md
Labels: new command

#6011 git-delete-branch: add page
  pages/common/git-delete-branch.md
Labels: new command

#6054 mke2fs: replace ext3 duplicaded for new ext4
  pages/linux/mke2fs.md
Labels: page edit

#5953 fileicon: add page
  pages/osx/fileicon.md
Labels: new command

#6050 conda: fix examples
  pages/common/conda.md
Labels: page edit

#6000 idnits: add page
  pages/common/idnits.md
Labels: new command

#6046 snap: add example to update to another channel
  pages/linux/snap.md
Labels: page edit

#6045 ipconfig, scrcpy: add Indonesian translation
  pages.id/common/scrcpy.md
  pages.id/windows/ipconfig.md
Labels: translation

#6055 stty: fix typo
  pages.zh/common/stty.md
  pages/common/stty.md
Labels: page edit

#6006 git-reset: clarify patch example and use long option
  pages.es/common/git-reset.md
  pages.fr/common/git-reset.md
  pages.it/common/git-reset.md
  pages/common/git-reset.md
Labels: page edit, translation

#5701 git-range-diff: add page
  pages/common/git-range-diff.md
Labels: new command

#6060 2to3: add Indonesian translation
  pages.id/common/2to3.md
Labels: translation

#6061 7z, 7za, 7zr: add Indonesian translation
  pages.id/common/7z.md
  pages.id/common/7za.md
  pages.id/common/7zr.md
Labels: translation

#6066 find: add Indonesian translation
  pages.id/windows/find.md
Labels: translation

#6042 lxterminal: add page
  pages/linux/lxterminal.md
Labels: new command

#6058 git-info: add page
  pages/common/git-info.md
Labels: new command

#6067 chkdsk: add Indonesian translation
  pages.id/windows/chkdsk.md
Labels: translation

#6008 mongoimport: add page
  pages/common/mongoimport.md
Labels: new command

#6077 set-more-info-link.py: add shebang
  scripts/set-more-info-link.py
Labels: tooling

#6080 mvn: add Chinese translation
  pages.zh/common/mvn.md
Labels: translation

#6072 pulseaudio: add link
  pages.tr/linux/pulseaudio.md
  pages/linux/pulseaudio.md
Labels: page edit, translation
