Repository tldr-pages/tldr, pull requests merged in 2021-01, with the labels that each got.

#5062 MAINTAINERS: add @bl-ue
  MAINTAINERS.md
Labels: community

#5057 jq: remove example to bring it under the 8 example limit
  pages/common/jq.md
Labels: page edit

#5038 finch: add page
  pages/linux/finch.md
Labels: new command

#5055 dust: add page
  pages/common/dust.md
Labels: new command

#5058 nc: improve grammar; bring under the 8 example limit
  pages/common/nc.md
Labels: page edit

#5061 acpi, flatpak, i3, iptables: add Chinese translation
  pages.zh/linux/acpi.md
  pages.zh/linux/flatpak.md
  pages.zh/linux/i3.md
  pages.zh/linux/iptables.md
Labels: translation

#5030 minifab: add page
  pages.it/common/minifab.md
  pages/common/minifab.md
Labels: new command, translation

#5064 MAINTAINERS: add @glenacota
  MAINTAINERS.md
Labels: community

#5065 MAINTAINERS: Fix link to @zlatanvasovic's GH profile
  MAINTAINERS.md
Labels: community

#5059 CLIENT-SPECIFICATION: fix changelog links
  CLIENT-SPECIFICATION.md
Labels: documentation

#5067 docker-container: fix filename spelling
  pages/common/docker-container.md
Labels: page edit

#5037 youtube-dl: improve download a playlist and extract mp3
  pages/common/youtube-dl.md
Labels: page edit

#5076 windows/shutdown: remove extra example; improve restart example
  pages/windows/shutdown.md
Labels: page edit

#5072 ci: add tldr-pages/tldr before commit hash for auto gh linking
  scripts/deploy.sh
Labels: tooling

#5078 tar: remove last example to reduce count to 8
  pages/common/tar.md
Labels: page edit

#5075 brew: fix GitHub case in translations
  pages.es/linux/brew.md
  pages.it/osx/brew.md
Labels: translation

#5077 nmap: remove SSL example to reduce count to 8
  pages/common/nmap.md
Labels: page edit

#5079 yetris: reduce example count to 8
  pages/linux/yetris.md
Labels: page edit

#5082 chore(deps): update tldr-lint to 0.0.9
  package-lock.json
  package.json
Labels: tooling

#5040 sort: add output file example
  pages/common/sort.md
Labels: page edit

#5074 e2undo: add page
  pages/linux/e2undo.md
Labels: new command

#5044 yq: add page
  pages/common/yq.md
Labels: new command

#5084 rbenv: add example and improve page
  pages/common/rbenv.md
Labels: new command

#5083 tar: add brackets explaining mnemonics
  pages/common/tar.md
Labels: page edit

#5086 watson: add page
  pages/common/watson.md
Labels: new command

#5087 mdutil: add turn on/off indexing for all volumes
  pages/osx/mdutil.md
Labels: page edit

#5089 stolonctl: change page title to filename
  pages/common/stolonctl.md
Labels: page edit

#5090 gpg2: update page title to match file name
  pages/common/gpg.md
  pages/common/gpg2.md
Labels: page edit

#5093 MAINTAINERS: fix date @schneiderl became org member
  MAINTAINERS.md
Labels: community

#5091 rg: update title to match page name; improve examples
  pages/common/rg.md
Labels: page edit

#5081 conan-frogarian: add page
  pages/common/conan-frogarian.md
Labels: new command

#5073 mysqldump: add remote example
  pages/common/mysqldump.md
Labels: page edit

#5102 btrfs-filesystem: add page
  pages/linux/btrfs-filesystem.md
Labels: new command

#5104 btrfs-scrub: add page
  pages/linux/btrfs-scrub.md
Labels: new command

#5100 git-check-ref-format: add page
  pages/common/git-check-ref-format.md
Labels: new command

#5099 git-check-mailmap: add page
  pages/common/git-check-mailmap.md
Labels: new command

#5101 git-restore: add examples
  pages/common/git-restore.md
Labels: page edit

#5096 git-annotate: add page
  pages/common/git-annotate.md
Labels: new command

#5094 git-stripspace: add page
  pages/common/git-stripspace.md
Labels: new command

#5106 rename github to GitHub
  pages.fr/common/git-pr.md
  pages/common/hub.md
Labels: mass changes, page edit, translation

#5108 git-column: add page
  pages/common/git-column.md
Labels: new command

#5097 git-bugreport: add page
  pages/common/git-bugreport.md
Labels: new command

#5098 git-check-attr: add page
  pages/common/git-check-attr.md
Labels: new command

#5028 siege: add page
  pages/common/siege.md
Labels: new command

#5113 git-commit-tree: add page
  pages/common/git-commit-tree.md
Labels: new command

#5121 valet: update more information link
  pages/osx/valet.md
Labels: page edit

#5095 git-var: add page
  pages/common/git-var.md
Labels: new command

#5124 MAINTAINERS: add @MasterOdin
  MAINTAINERS.md
Labels: community

#5125 gh-alias: add page
  pages/common/gh-alias.md
Labels: new command

#5123 MAINTAINERS: clarify abilities of org members
  MAINTAINERS.md
Labels: community, documentation

#5118 svn-changelist: add page
  pages/common/svn-changelist.md
Labels: new command

#5135 jwt: add space in algorithm list in description
  pages/common/jwt.md
Labels: page edit

#5131 gh-environment: add page
  pages/common/gh-environment.md
Labels: new command

#5126 gh-pr: fix page title
  pages/common/gh-pr.md
Labels: page edit

#5129 gh-help: add page
  pages/common/gh-help.md
Labels: new command

#5134 gh-completion: add page
  pages/common/gh-completion.md
Labels: new command

#5107 git-checkout-index: add page
  pages/common/git-checkout-index.md
Labels: new command

#5138 takeout: add page
  pages/common/takeout.md
Labels: new command

#5144 dot_clean: add page
  pages/osx/dot_clean.md
Labels: new command

#5142 dexdump: add more information link
  pages.ko/common/dexdump.md
  pages/common/dexdump.md
Labels: page edit, translation

#5149 tty: add Persian translation
  pages.fa/common/tty.md
Labels: translation

#5151 multiple pages, MAINTAINERS: remove trailing whitespace at line ends
  MAINTAINERS.md
  pages.de/common/git-add.md
  pages.de/common/git-commit.md
  pages.fr/common/git-add.md
  pages.fr/common/ifconfig.md
  pages.fr/common/mkdir.md
  pages.fr/linux/xclip.md
  pages.fr/linux/yay.md
  pages.hi/common/tldr.md
  pages.it/common/man.md
  pages.it/osx/afplay.md
  pages.pt_BR/common/aws-ec2.md
  pages.pt_BR/common/docker-build.md
  pages.pt_BR/common/docker-run.md
  pages.pt_BR/common/docker-start.md
  pages.pt_BR/common/git-add.md
  pages.pt_BR/common/kill.md
Labels: mass changes, page edit, translation

#5114 git-count-objects: add page
  pages/common/git-count-objects.md
Labels: new command

#5115 git-credential: add page
  pages/common/git-credential.md
Labels: new command

#5130 gh-reference: add page
  pages/common/gh-reference.md
Labels: new command

#5133 gh-secret: add page
  pages/common/gh-secret.md
Labels: new command

#5127 gh-api: add page
  pages/common/gh-api.md
Labels: new command

#5145 ghcup: add page
  pages/common/ghcup.md
Labels: new command

#5156 gh-alias: close quoted string
  pages/common/gh-alias.md
Labels: bug, page edit

#5157 gh: small wording tweaks for extra clarity
  pages/common/gh.md
Labels: page edit

#5150 lvresize: add vg to positional arg and example extend
  pages/linux/lvresize.md
Labels: page edit

#5109 git-commit-graph: add page
  pages/common/git-commit-graph.md
Labels: new command

#5153 btrfs-subvolume: add page
  pages/linux/btrfs-subvolume.md
Labels: new command

#5139 lambo, lambo-new: add page
  pages/common/lambo-new.md
  pages/common/lambo.md
Labels: new command

#5161 false, logname, time, unclutter, view: add Persian translation
  pages.fa/common/false.md
  pages.fa/common/logname.md
  pages.fa/common/time.md
  pages.fa/common/unclutter.md
  pages.fa/common/view.md
Labels: translation

#5146 pacman: add more information link
  pages.fr/linux/pacman.md
  pages.ml/linux/pacman.md
  pages.zh/linux/pacman.md
  pages/linux/pacman.md
Labels: page edit, translation

#5165 cls, type, ver: add Persian translation
  pages.fa/windows/cls.md
  pages.fa/windows/type.md
  pages.fa/windows/ver.md
Labels: translation

#5162 scrot: add command to display a countdown before taking a screenshot
  pages/linux/scrot.md
Labels: page edit

#5166 promtool: add page
  pages/common/promtool.md
Labels: new command

#5163 lmms, SafeEjectGPU: add pages
  pages/common/lmms.md
  pages/osx/SafeEjectGPU.md
Labels: new command

#5167 numactl: add page
  pages/linux/numactl.md
Labels: new command

#5168 mupdf: add page
  pages/common/mupdf.md
Labels: new command

#5158 partx: add page
  pages/linux/partx.md
Labels: new command

#5173 chroot, cmake: add Turkish translation
  pages.tr/common/chroot.md
  pages.tr/common/cmake.md
Labels: translation

#5171 uname: add Persian translation
  pages.fa/common/uname.md
Labels: translation

#5179 uname: replace ' with `
  pages.fa/common/uname.md
Labels: translation

#5178 brew-bundle, caffeinate, open and tmutil: add German translation
  pages.de/osx/brew-bundle.md
  pages.de/osx/caffeinate.md
  pages.de/osx/open.md
  pages.de/osx/tmutil.md
Labels: translation

#5169 btrfs-filesystem: correct and improve
  pages/linux/btrfs-filesystem.md
Labels: page edit

#5183 unclutter: add colon in Persian example
  pages.fa/common/unclutter.md
Labels: translation

#5182 ls: remove ی
  pages.fa/common/ls.md
Labels: translation

#5180 README: add tldr Persian web client
  README.md
Labels: community

#5181 cat, ver: add Persian translation
  pages.fa/common/cat.md
  pages.fa/windows/ver.md
Labels: translation

#5189 cp: add Persian translation
  pages.fa/common/cp.md
Labels: translation

#5192 cp: fix Persian translation
  pages.fa/common/cp.md
Labels: translation

#5191 nmcli-device: add wifi show-password example
  pages/linux/nmcli-device.md
Labels: page edit

#5177 docker, docker-build, docker-compose: translate to Turkish (tr)
  pages.tr/common/docker-build.md
  pages.tr/common/docker-compose.md
  pages.tr/common/docker.md
Labels: translation

#5199 README: change tldr Persian web client address
  README.md
Labels: clients, community, documentation

#5193 gpg*: add Chinese translation
  pages.zh/common/gpg-zip.md
  pages.zh/common/gpg.md
  pages.zh/common/gpg2.md
  pages.zh/common/gpgv.md
Labels: translation

#5204 gdebi: add page
  pages/linux/gdebi.md
Labels: new command

#5188 gobuster: add page
  pages/common/gobuster.md
Labels: new command

#5203 hostnamectl: add --pretty and --static examples
  pages/linux/hostnamectl.md
Labels: page edit

#5202 sudo: add --login, --shell and --list examples
  pages/common/sudo.md
Labels: page edit

#5198 nmcli: add more information link
  pages.ml/linux/nmcli.md
  pages/linux/nmcli-connection.md
  pages/linux/nmcli-device.md
  pages/linux/nmcli.md
Labels: page edit

#5187 smbget: add page
  pages/linux/smbget.md
Labels: new command

#5210 fg, nohup, sleep, users: add Persian translation
  pages.fa/common/fg.md
  pages.fa/common/nohup.md
  pages.fa/common/sleep.md
  pages.fa/common/users.md
Labels: translation

#5160 cmake: update page
  pages/common/cmake.md
Labels: page edit

#5128 style-guide: add backticks guide
  contributing-guides/style-guide.md
Labels: documentation

#5206 scripts/pdf/render.py: fix typo
  scripts/pdf/render.py
Labels: tooling

#5213 multiple pages: trim trailing whitespace
  pages.fa/common/cat.md
  pages.pt_BR/common/docker-start.md
  pages/linux/partx.md
Labels: mass changes, page edit
