Repository tldr-pages/tldr, pull requests merged in 2021-09, with the labels that each got.

#6434 youtube-dl: extend the custom filenames example
  pages/common/youtube-dl.md
Labels: page edit

#6427 fgrep: remove incorrect use of 'regular expression'
  pages/common/fgrep.md
Labels: page edit

#6448 mvn: simplify skip unit tests
  pages.pt_BR/common/mvn.md
  pages.zh/common/mvn.md
  pages/common/mvn.md
Labels: page edit, translation

#6443 lvs: add Chinese translation
  pages.zh/linux/lvs.md
Labels: translation

#6401 acyclic, bcomps, ccomps, edgepaint, gvcolor, gvpack, mingle, nop, sccmap, unflatten: add page
  pages/common/acyclic.md
  pages/common/bcomps.md
  pages/common/ccomps.md
  pages/common/edgepaint.md
  pages/common/gvcolor.md
  pages/common/gvpack.md
  pages/common/mingle.md
  pages/common/nop.md
  pages/common/sccmap.md
  pages/common/tred.md
  pages/common/unflatten.md
Labels: new command, mass changes

#6449 xcopy: add Indonesian translation
  pages.id/windows/xcopy.md
Labels: translation

#6319 pip-install: add --find-links example
  pages/common/pip-install.md
Labels: page edit, waiting

#6445 common/z*: add more information link
  pages/common/zcat.md
  pages/common/zdb.md
  pages/common/zfs.md
  pages/common/zip.md
  pages/common/zless.md
  pages/common/zpool.md
Labels: page edit

#6453 ssh: fix typo in German translation
  pages.de/common/ssh.md
Labels: translation

#6432 adscript: add page
  pages/common/adscript.md
Labels: new command

#6227 linux/[h-k]: add more information link
  pages.de/linux/ip-address.md
  pages.fr/linux/ip-address.md
  pages/linux/hardinfo.md
  pages/linux/hdparm.md
  pages/linux/hexdump.md
  pages/linux/hostname.md
  pages/linux/hostnamectl.md
  pages/linux/http-prompt.md
  pages/linux/httpie.md
  pages/linux/hwclock.md
  pages/linux/i7z.md
  pages/linux/imgp.md
  pages/linux/inotifywait.md
  pages/linux/inxi.md
  pages/linux/iostat.md
  pages/linux/ip-address.md
  pages/linux/ipcalc.md
  pages/linux/ipcmk.md
  pages/linux/ipcrm.md
  pages/linux/isoinfo.md
  pages/linux/iw.md
  pages/linux/jobs.md
  pages/linux/journalctl.md
  pages/linux/kexec.md
  pages/linux/kpartx.md
Labels: page edit, mass changes

#6184 send-to-bot.py: use requests instead of urllib
  scripts/send-to-bot.py
Labels: tooling

#6450 print: add Indonesian translation
  pages.id/windows/print.md
Labels: translation

#6459 git-rev-list: add --count example
  pages/common/git-rev-list.md
Labels: page edit

#6420 raspinfo: add page
  pages/linux/raspinfo.md
Labels: new command

#6465 md5sum: replace filename by path/to/file
  pages.it/common/md5sum.md
  pages.zh/common/md5sum.md
  pages/common/md5sum.md
Labels: page edit, translation

#6419 raspi-config: add page
  pages/linux/raspi-config.md
Labels: new command

#6455 asciidoctor: add page
  pages/common/asciidoctor.md
Labels: new command

#6469 requirements.txt: add requests dependency
  requirements.txt
Labels: bug, tooling

#6470 merging commits to test branch
  pages/common/asciidoctor.md
  requirements.txt
Labels: invalid, stalebot ignore

#6457 chmod: add a+rX example
  pages/common/chmod.md
Labels: new command

#6444 git-bug, git-cola, gitlint: add page
  pages/common/git-bug.md
  pages/common/git-cola.md
  pages/common/gitlint.md
Labels: new command, mass changes

#6446 aws-help: add page
  pages/common/aws-help.md
Labels: new command

#6463 tlmgr-paper: add page
  pages.de/common/tlmgr.md
  pages/common/tlmgr-paper.md
  pages/common/tlmgr.md
Labels: new command

#6409 ldapdomaindump: add page
  pages/linux/ldapdomaindump.md
Labels: new command

#6392 resize2fs: remove false statement
  pages/linux/resize2fs.md
Labels: page edit

#6456 carp: add page
  pages/common/carp.md
Labels: new command

#6461 wp: add download and config examples
  pages/common/wp.md
Labels: page edit

#6421 pw-loopback: add page
  pages/linux/pw-loopback.md
Labels: new command

#6472 cola: add page
  pages/common/cola.md
Labels: new command

#6467 tlmgr-gui: add page
  pages/common/tlmgr-gui.md
Labels: new command

#6462 Reorganize translation templates
  contributing-guides/translation-templates/alias-pages.md
  contributing-guides/translation-templates/subcommand-mention.md
Labels: documentation, translation

#6475 st: add page
  pages/linux/st.md
Labels: new command

#6344 style-guide: add German translation
  contributing-guides/style-guide.de.md
Labels: documentation, translation

#6474 pacman-key: add page
  pages/linux/pacman-key.md
Labels: new command

#6479 alias-pages: add pt_BR translation
  contributing-guides/translation-templates/alias-pages.md
Labels: documentation, translation

#6473 clojure: add page
  pages.pt_BR/common/clojure.md
  pages/common/clojure.md
Labels: new command

#6480 tailscale: add page
  pages/common/tailscale.md
Labels: new command

#6316 log: add page
  pages/osx/log.md
Labels: new command

#6487 feh, hostname, fc, ssh-add: move to common
  pages.zh/common/fc.md
  pages.zh/common/feh.md
  pages.zh/common/hostname.md
  pages.zh/common/ssh-add.md
  pages/common/fc.md
  pages/common/feh.md
  pages/common/hostname.md
  pages/common/ssh-add.md
  pages/linux/ssh-add.md
  pages/osx/fc.md
  pages/osx/feh.md
  pages/osx/hostname.md
Labels: translation

#6417 needrestart: add page
  pages/linux/needrestart.md
Labels: new command

#6354 lb: add page
  pages/common/lb.md
Labels: new command

#6447 gdu: add page
  pages/common/gdu.md
Labels: new command

#6395 arp-scan: move to common platform
  pages.pt_BR/common/arp-scan.md
  pages.zh/common/arp-scan.md
  pages/common/arp-scan.md
Labels: new command

#6477 pinout: add page
  pages/linux/pinout.md
Labels: new command

#6490 brew: sync Spanish translation
  pages.es/common/brew.md
  pages.es/linux/brew.md
  pages.es/osx/brew.md
Labels: translation

#6483 avo: add page
  pages/common/avo.md
Labels: new command

#6492 brew: sync traditional Chinese translation
  pages.zh/common/brew.md
  pages.zh/linux/brew.md
  pages.zh/osx/brew.md
  pages.zh_TW/common/brew.md
Labels: translation

#6418 android/*: add traditional Chinese translations
  pages.zh_TW/android/am.md
  pages.zh_TW/android/bugreport.md
  pages.zh_TW/android/bugreportz.md
  pages.zh_TW/android/cmd.md
  pages.zh_TW/android/dalvikvm.md
  pages.zh_TW/android/dumpsys.md
  pages.zh_TW/android/getprop.md
  pages.zh_TW/android/input.md
  pages.zh_TW/android/logcat.md
  pages.zh_TW/android/pm.md
  pages.zh_TW/android/settings.md
  pages.zh_TW/android/wm.md
Labels: translation

#6497 llvm-gcc: add page
  pages/common/llvm-gcc.md
Labels: new command

#6494 clang: add -c example
  pages/common/clang.md
Labels: page edit

#6499 find: add -daystart argument in example
  pages/common/find.md
Labels: page edit

#6478 udevadm: add page
  pages/linux/udevadm.md
Labels: new command

#6502 cargo: use long argument --jobs
  pages.de/common/cargo.md
  pages.it/common/cargo.md
  pages.ko/common/cargo.md
  pages.nl/common/cargo.md
  pages/common/cargo.md
Labels: page edit, translation

#6501 clang++: add page
  pages/common/clang++.md
Labels: new command

#6200 style-guide: put token guidelines into sections & add varargs
  contributing-guides/style-guide.md
Labels: documentation

#6471 pages/common/*.md: REPL Normalization
  pages/common/cake.md
  pages/common/clj.md
  pages/common/coffee.md
  pages/common/ghc.md
  pages/common/guile.md
  pages/common/ipython.md
  pages/common/julia.md
  pages/common/python.md
  pages/common/r.md
  pages/common/ruby.md
  pages/common/sbcl.md
  pages/common/sbt.md
  pages/common/scala.md
  pages/common/scheme.md
  pages/common/swift.md
Labels: page edit, mass changes

#6485 corepack: add page
  pages/common/corepack.md
Labels: new command

#6503 cargo-clippy: use long arguments
  pages/common/cargo-clippy.md
Labels: page edit

#6507 brew*: move to common
  pages.de/common/brew-bundle.md
  pages.it/common/brew-bundle.md
  pages.it/common/brew-cask.md
  pages.it/common/brew.md
  pages.pt_BR/common/brew.md
  pages.zh/common/brew-cask.md
  pages.zh/common/brew-mas.md
  pages/common/brew-bundle.md
  pages/common/brew-cask.md
Labels: architecture, translation

#6511 tlmgr-info: add page
  pages/common/tlmgr-info.md
Labels: new command

#6505 man: correct syntax
  pages.it/common/man.md
  pages.pt_BR/common/man.md
  pages.tr/common/man.md
  pages/common/man.md
Labels: page edit

#6508 compgen, eval, export, file: move to common
  pages.pt_BR/common/compgen.md
  pages.zh/common/compgen.md
  pages.zh/common/eval.md
  pages.zh/common/export.md
  pages.zh/common/file.md
  pages/common/compgen.md
  pages/common/eval.md
  pages/common/export.md
  pages/common/file.md
  pages/osx/compgen.md
  pages/osx/eval.md
  pages/osx/export.md
  pages/osx/file.md
Labels: architecture, translation

#6510 fc*: move to common
  pages.pt_BR/common/fc-list.md
  pages.pt_BR/common/fc.md
  pages.zh/common/fc-cache.md
  pages.zh/common/fc-list.md
  pages/common/fc-cache.md
  pages/common/fc-list.md
  pages/common/fc-match.md
  pages/common/fc-pattern.md
Labels: architecture, translation

#6498 llvm-config: add page
  pages/common/llvm-config.md
Labels: new command

#6491 go-get: add page
  pages/common/go-get.md
Labels: new command

#6514 subcommand-mention: sync Spanish translation
  contributing-guides/translation-templates/subcommand-mention.md
Labels: translation

#6513 tailscale-up: add page
  pages/common/tailscale-up.md
  pages/common/tailscale.md
Labels: new command

#6529 cal, chage: add Chinese translation
  pages.zh/linux/cal.md
  pages.zh/linux/chage.md
Labels: translation

#6504 ip-rule: add page
  pages/linux/ip-rule.md
Labels: new command

#6530 script/test: ignore python checks if not available
  scripts/test.sh
Labels: tooling

#6405 set-more-information.py: add sync option
  scripts/set-more-info-link.py
Labels: tooling

#6526 *: shellcheck and fix typos
  MAINTAINERS.md
  contributing-guides/git-terminal.md
  contributing-guides/translation-templates/subcommand-mention.md
  pages/common/az-vm.md
  pages/common/git-summary.md
  pages/common/pio-platform.md
  pages/common/tlmgr-paper.md
  pages/linux/ffuf.md
  scripts/build.sh
  scripts/test.sh
Labels: documentation, mass changes

#6520 ybacklight: add page
  pages/common/ybacklight.md
Labels: new command

#6516 brightnessctl: add page
  pages/linux/brightnessctl.md
Labels: new command

#6536 exec, javac: add more information link
  pages.it/common/exec.md
  pages.ta/common/javac.md
  pages.zh/common/javac.md
  pages/common/exec.md
  pages/common/javac.md
Labels: page edit, translation

#6540 makepkg: add clean option
  pages/linux/makepkg.md
Labels: page edit

#6535 ganache-cli: add page
  pages/common/ganache-cli.md
Labels: new command

#6533 aura: add page
  pages/linux/aura.md
Labels: new command

#6542 clang-cpp, llvm-g++: add page
  pages/common/clang-cpp.md
  pages/common/llvm-g++.md
Labels: new command

#6495 xrdb: add page
  xrdb.md
Labels: new command

#6531 sup: add page
  pages/common/sup.md
Labels: new command

#6519 img2pdf: add page
  pages/common/img2pdf.md
Labels: new command

#6517 black: add --skip-string-normalization example
  pages.ko/common/black.md
  pages/common/black.md
Labels: page edit

#6429 xprop: add page
  pages/common/xprop.md
Labels: new command

#6506 transfersh: add page
  pages/common/transfersh.md
Labels: new command

#6493 po4a: add page
  pages/linux/po4a-gettextize.md
  pages/linux/po4a-translate.md
  pages/linux/po4a-updatepo.md
  pages/linux/po4a.md
Labels: new command

#6496 llvm-as: add page
  pages/common/llvm-as.md
Labels: new command

#6534 truffle: add page
  pages/common/truffle.md
Labels: new command

#6554 aura, brightnessctl: add Chinese translation
  pages.zh/linux/aura.md
  pages.zh/linux/brightnessctl.md
Labels: translation

#6549 hexdump, logger, netstat, n, nm, pdfgrep: move to common
  pages.zh/common/hexdump.md
  pages.zh/common/logger.md
  pages.zh/common/n.md
  pages.zh/common/netstat.md
  pages.zh/common/pdfgrep.md
  pages/common/hexdump.md
  pages/common/logger.md
  pages/common/n.md
  pages/common/netstat.md
  pages/common/nm.md
  pages/common/pdfgrep.md
  pages/osx/hexdump.md
  pages/osx/logger.md
  pages/osx/n.md
  pages/osx/netstat.md
  pages/osx/nm.md
  pages/osx/pdfgrep.md
Labels: architecture, translation

#6545 jobs, jstack, kill, killall: add more information link
  pages.pt_BR/common/kill.md
  pages/common/jobs.md
  pages/common/jstack.md
  pages/common/kill.md
  pages/common/killall.md
Labels: page edit

#6552 whereis, xar, yank: move to common
  pages.fa/common/whereis.md
  pages.zh/common/whereis.md
  pages.zh/common/yank.md
  pages/common/whereis.md
  pages/common/xar.md
  pages/common/yank.md
  pages/osx/whereis.md
  pages/osx/xar.md
  pages/osx/yank.md
Labels: architecture, translation

#6551 pwgen, sshuttle, trap, tree: move to common
  pages.it/common/tree.md
  pages.pt_BR/common/tree.md
  pages.tr/common/tree.md
  pages.zh/common/pwgen.md
  pages.zh/common/sshuttle.md
  pages.zh/common/trap.md
  pages.zh/common/tree.md
  pages/common/pwgen.md
  pages/common/sshuttle.md
  pages/common/trap.md
  pages/common/tree.md
  pages/osx/pwgen.md
  pages/osx/sshuttle.md
  pages/osx/trap.md
  pages/osx/tree.md
Labels: architecture, translation

#6558 llvm-bcanalyzer: add page
  pages/common/llvm-bcanalyzer.md
Labels: new command

#6484 diff: add -Naur create patch file example
  pages/common/diff.md
Labels: page edit

#6566 llvm-ar, llvm-nm, llvm-strings: add page
  pages/common/llvm-ar.md
  pages/common/llvm-nm.md
  pages/common/llvm-strings.md
Labels: new command

#6546 img2pdf: add pt_BR translation
  pages.pt_BR/common/img2pdf.md
Labels: translation

#6563 llvm-objdump: add page
  pages/common/llvm-objdump.md
Labels: new command

#6541 chage: fix examples and use long arguments
  pages.pt_BR/linux/chage.md
  pages.zh/linux/chage.md
  pages/linux/chage.md
Labels: page edit, translation

#6564 llvm-cat: add page
  pages/common/llvm-cat.md
Labels: new command

#6559 tlmgr-install: add page
  pages/common/tlmgr-install.md
Labels: new command

#6555 chsh: add interactive and --list-shells examples
  pages/common/chsh.md
Labels: page edit

#6572 tlmgr-shell: add page
  pages/common/tlmgr-shell.md
Labels: new command

#6574 tlmgr-path: add page
  pages/common/tlmgr-path.md
Labels: new command

#6561 tlmgr-platform, tlmgr-arch: add page
  pages/common/tlmgr-arch.md
  pages/common/tlmgr-platform.md
Labels: new command

#6562 fakeroot: add page
  pages/linux/fakeroot.md
Labels: new command

#6568 d8: add page
  pages/common/d8.md
Labels: new command

#6583 starship: mention subcommand page
  pages/common/starship-init.md
  pages/common/starship.md
Labels: page edit

#6577 common/l*: add more information link
  pages.pt_BR/common/lsof.md
  pages/common/last.md
  pages/common/ldapsearch.md
  pages/common/leave.md
  pages/common/lex.md
  pages/common/lorem.md
  pages/common/lp.md
  pages/common/lpstat.md
  pages/common/lsof.md
Labels: page edit

#6591 ipython: update more information link
  pages/common/ipython.md
Labels: page edit

#6581 tlmgr-backup: add page
  pages/common/tlmgr-backup.md
Labels: new command

#6582 tlmgr-candidates: add page
  pages/common/tlmgr-candidates.md
Labels: new command

#6578 gh-screensaver: add page
  pages/common/gh-screensaver.md
Labels: new command

#6585 zig: add page
  pages/common/zig.md
Labels: new command

#6587 tlmgr-update: add page
  pages/common/tlmgr-update.md
Labels: new command

#6592 git-blame-someone-else: add page
  pages/common/git-blame-someone-else.md
Labels: new command

#6590 docker-slim: add page
  pages/common/docker-slim.md
Labels: new command

#6580 sdk: add current example
  pages/common/sdk.md
Labels: page edit

#6567 debsecan: add page
  pages/linux/debsecan.md
Labels: new command

#6589 git-secret: add page
  pages/common/git-secret.md
Labels: new command

#6602 pw-cat, pw-play, pw-record: add page
  pages/linux/pw-cat.md
  pages/linux/pw-play.md
  pages/linux/pw-record.md
Labels: new command

#6603 vlc: use official wiki as link
  pages.it/common/vlc.md
  pages.zh/common/vlc.md
  pages/common/vlc.md
Labels: page edit

#6606 xrdb: move to linux directory
  pages/linux/xrdb.md
Labels: page edit

#6595 ex: add page
  pages/common/ex.md
Labels: new command

#5329 images: add medium font
  images/SometypeMono-Medium.ttf
Labels: documentation, community

#6579 gh-extension: add list and remove examples
  pages/common/gh-extension.md
Labels: page edit

#6593 *: normalized readthedocs.io more information links
  pages.de/linux/dnf.md
  pages.it/common/bedtools.md
  pages.ko/common/bedtools.md
  pages.pt_BR/linux/eyed3.md
  pages/common/bedtools.md
  pages/common/git-cola.md
  pages/common/jupytext.md
  pages/common/wormhole.md
  pages/linux/dnf.md
  pages/linux/eyed3.md
Labels: page edit

#6611 README: add install instructions to C++ client
  README.md
Labels: documentation, clients
