Repository tldr-pages/tldr, pull requests merged in 2022-02, with the labels that each got.

#7722 cwebp: add page
  pages.ru/common/cwebp.md
  pages/common/cwebp.md
Labels: new command, translation

#7733 socat, sn, slimrb, swig: add more information link
  pages/common/slimrb.md
  pages/common/sn.md
  pages/common/socat.md
  pages/common/swig.md
Labels: page edit

#7608 airportd, automountd, coreautha, coreauthd, nfcd: add page
  pages/osx/airportd.md
  pages/osx/automountd.md
  pages/osx/coreautha.md
  pages/osx/coreauthd.md
  pages/osx/nfcd.md
Labels: new command

#7727 webstorm: add page
  pages/common/webstorm.md
Labels: new command, review needed

#7732 gh-pr-merge: add --subject example
  pages/common/gh-pr-merge.md
Labels: page edit, review needed

#7710 dm-tool: add page
  pages/linux/dm-tool.md
Labels: new command

#7738 source: add Indonesian translation
  pages.id/common/source.md
Labels: translation

#7740 meson: add test example
  pages/common/meson.md
Labels: page edit, minor change

#7701 xfce4-terminal: add Indonesian translation
  pages.id/linux/xfce4-terminal.md
Labels: translation, review needed

#7726 df, dig, du, ln, tree: add Spanish translation
  pages.es/common/df.md
  pages.es/common/dig.md
  pages.es/common/du.md
  pages.es/common/ln.md
  pages.es/common/tree.md
Labels: translation

#7730 *: use author link instead of npm package
  pages.de/common/npm-check.md
  pages.de/common/npm-why.md
  pages.de/common/npm.md
  pages.de/common/npx.md
  pages.id/common/npm.md
  pages.ml/linux/bluetoothctl.md
  pages.pt_BR/common/yarn-why.md
  pages.sv/common/npm-why.md
  pages.sv/common/yarn-why.md
  pages.zh/common/yarn-why.md
  pages.zh/linux/bluetoothctl.md
  pages/common/hsw-cli.md
  pages/common/live-server.md
  pages/common/npm-check.md
  pages/common/npm-why.md
  pages/common/npm.md
  pages/common/npx.md
  pages/common/p5.md
  pages/common/ts-node.md
  pages/common/web-ext.md
  pages/common/yarn-why.md
  pages/linux/bluetoothctl.md
Labels: page edit, mass changes, translation

#7651 alien, abbr: add German translation
  pages.de/linux/abbr.md
  pages.de/linux/alien.md
Labels: translation

#7746 bird: fix capitalization in command description
  pages/osx/bird.md
Labels: page edit, minor change

#7742 lerna: add page
  pages/common/lerna.md
Labels: new command, review needed

#7688 tail: add page
  pages/osx/tail.md
Labels: new command, waiting

#7612 glab-auth: add page
  pages/common/glab-auth.md
Labels: new command

#7734 turbo: add page
  pages/common/turbo.md
Labels: new command, review needed

#7751 translation-templates/*: add Catalan translation
  contributing-guides/translation-templates/alias-pages.md
  contributing-guides/translation-templates/common-arguments.md
  contributing-guides/translation-templates/subcommand-mention.md
Labels: documentation

#7485 nu: update page
  pages/common/nu.md
Labels: page edit, waiting

#7748 nm-classic: add page
  pages/common/nm-classic.md
Labels: new command, review needed

#7759 maestral: add page
  pages/common/maestral.md
Labels: new command

#7762 docker-run: fix paths in -v example
  pages/common/docker-run.md
Labels: page edit, review needed

#7757 docker-compose, git-*, htop, ls, nano: sync Spanish translation
  pages.es/common/docker-compose.md
  pages.es/common/git-clone.md
  pages.es/common/git-commit.md
  pages.es/common/git-push.md
  pages.es/common/git-rev-list.md
  pages.es/common/htop.md
  pages.es/common/ls.md
  pages.es/common/nano.md
Labels: translation, review needed

#7764 pdftoppm: add page
  pages/linux/pdftoppm.md
Labels: new command

#7761 adduser: remove invalid example
  pages/linux/adduser.md
Labels: bug, page edit

#7741 serve: add page
  pages/common/serve.md
Labels: new command, review needed

#7754 networksetup, port, xcode-select, xcodebuild: add more information links
  pages/osx/networksetup.md
  pages/osx/port.md
  pages/osx/xcode-select.md
  pages/osx/xcodebuild.md
Labels: page edit, review needed, minor change

#7723 aapt, ab: add French translation
  pages.fr/common/aapt.md
  pages.fr/common/ab.md
Labels: translation, review needed

#7758 nm: update page
  pages/common/nm.md
Labels: page edit, review needed

#7766 dnf, youtube-dl: add Indonesian translation
  pages.id/common/youtube-dl.md
  pages.id/linux/dnf.md
Labels: translation, review needed

#7777 fnm: spell out the "list" subcommand
  pages/common/fnm.md
Labels: page edit, minor change

#7779 package.json: update dependencies
  package-lock.json
  package.json
Labels: tooling, minor change

#7780 composer, subl: add Indonesian translation
  pages.id/common/composer.md
  pages.id/common/subl.md
Labels: translation, review needed

#7482 for: refresh
  pages/common/for.md
Labels: page edit

#7550 chsh: page update
  pages/common/chsh.md
Labels: page edit, review needed

#7775 checkupdates-aur: add page
  pages/linux/checkupdates-aur.md
Labels: new command, review needed

#7774 checkupdates: add page
  pages/linux/checkupdates.md
Labels: new command, review needed

#7737 http: add --follow example
  pages/linux/httpie.md
Labels: page edit, minor change

#7756 mk: add page
  pages/common/mk.md
Labels: new command, review needed

#7788 openvpn3: add Chinese translation
  pages.zh/linux/openvpn3.md
Labels: translation

#7787 puppet-agent: add --disable and --enable examples
  pages/common/puppet-agent.md
Labels: page edit, review needed

#7514 CLIENT-SPECIFICATION: add macos recommendation
  CLIENT-SPECIFICATION.md
Labels: documentation, review needed

#7796 cd, cp: add Catalan translation
  pages.ca/common/cd.md
  pages.ca/common/cp.md
Labels: translation

#7526 doctl-auth: add page
  pages/common/doctl-auth.md
Labels: new command, review needed

#7755 systemsetup: fix more information link
  pages/osx/systemsetup.md
Labels: page edit

#7765 7z: add Persian translation
  pages.fa/common/7z.md
Labels: translation

#7561 CLIENT-SPECIFICATION: drop the special "all" platform
  CLIENT-SPECIFICATION.md
Labels: documentation

#7747 npx: add --no-install and --quiet examples
  pages/common/npx.md
Labels: page edit, review needed

#7678 xidel: add page
  pages/common/xidel.md
Labels: new command, review needed

#7797 set-more-info-link.py: add Catalan translation
  scripts/set-more-info-link.py
Labels: tooling, minor change

#7789 createrepo: add page
  pages/linux/createrepo.md
Labels: new command

#7804 kubectl-delete: fix typo
  pages/common/kubectl-delete.md
Labels: page edit, minor change

#7771 docker-volume: add page
  pages/common/docker-volume.md
Labels: new command, review needed

#7792 asciiart: update Chinese translation
  pages.zh/linux/asciiart.md
Labels: translation, review needed

#7799 go: add Chinese translation
  pages.zh/common/go.md
Labels: translation

#7795 rsync: fix remote_directory in -rauL example
  pages/common/rsync.md
Labels: page edit, minor change

#7628 yt-dlp: add page
  pages/common/yt-dlp.md
Labels: new command, tooling, review needed

#7753 standard-version: add page
  pages/common/standard-version.md
Labels: new command

#7763 git-rev-list: add -n example
  pages.es/common/git-rev-list.md
  pages/common/git-rev-list.md
Labels: page edit, waiting, translation, review needed

#7811 chromium: refresh
  pages/common/chromium.md
Labels: page edit, review needed

#7812 google-chrome: refresh
  pages/common/google-chrome.md
  pages/linux/google-chrome.md
Labels: page edit, new command, review needed

#7805 gow: add page
  pages/common/gow.md
Labels: new command

#7813 chrome: add page
  pages/windows/chrome.md
Labels: new command, review needed

#7816 pkg: add pt_BR translation
  pages.pt_BR/android/pkg.md
Labels: translation, review needed

#7817 am: fix pt_BR translation
  pages.pt_BR/android/am.md
Labels: translation

#7814 ncdu: move from linux to common
  pages/common/ncdu.md
Labels: page edit, minor change

#7808 gcc, g++: add Indonesian translation
  pages.id/common/g++.md
  pages.id/common/gcc.md
Labels: translation, review needed

#7807 ogr2ogr, ogrinfo: refresh
  pages/common/ogr2ogr.md
  pages/common/ogrinfo.md
Labels: page edit

#7818 rga: add page
  pages/common/rga.md
Labels: new command

#7823 subcommand-mention: fix formatting
  contributing-guides/translation-templates/subcommand-mention.md
Labels: documentation, minor change
