Repository tldr-pages/tldr, pull requests merged in 2022-09, with the labels that each got.

#8428 df: add Chinese translation
  pages.zh/common/df.md
Labels: translation

#8435 command: update Chinese translation
  pages.zh/common/command.md
Labels: translation

#8411 pixterm: add page
  pages/common/pixterm.md
Labels: new command, review needed

#8367 gnmic: add page and subpages
  pages/common/gnmic-get.md
  pages/common/gnmic-set.md
  pages/common/gnmic-sub.md
  pages/common/gnmic-subscribe.md
  pages/common/gnmic.md
Labels: new command

#8424 adb-logcat: add page
  pages/common/adb-logcat.md
Labels: new command

#8328 task: refresh page
  pages/common/task.md
Labels: page edit, review needed

#8437 ls: update French translation
  pages.fr/common/ls.md
Labels: translation

#8440 emacs: add `--script` example
  pages/common/emacs.md
Labels: page edit

#8433 tar: fix tense in French translation
  pages.fr/common/tar.md
Labels: translation

#8439 MAINTAINERS: add @CairnThePerson to collaborators
  MAINTAINERS.md
Labels: community

#8441 mg: add page
  pages/common/mg.md
Labels: new command

#8431 wal-telegram: add page
  pages/linux/wal-telegram.md
Labels: new command

#8448 mkdir: add Chinese translation
  pages.zh/common/mkdir.md
Labels: translation

#8449 more: add Chinese translation
  pages.zh/common/more.md
Labels: translation

#8436 ftp: update French translation
  pages.fr/common/ftp.md
Labels: translation

#8443 mkdir: update French translation
  pages.fr/common/mkdir.md
Labels: translation

#8446 atuin: add page
  pages/common/atuin.md
Labels: new command

#8451 gdaldem: add page
  pages/common/gdaldem.md
Labels: new command

#8423 adb-install: add -d example
  pages/common/adb-install.md
Labels: page edit

#8447 7z: fix a command explanation
  pages/common/7z.md
Labels: page edit

#8465 man: sort --locale example
  pages/linux/man.md
Labels: page edit, minor change

#8464 man: add French translation
  pages.fr/linux/man.md
Labels: translation

#8463 passwd: add French translation
  pages.fr/common/passwd.md
Labels: translation

#8462 vimdiff: fix jump to previous/next difference instructions
  pages.es/common/vimdiff.md
  pages/common/vimdiff.md
Labels: page edit, translation

#8460 git-bisect: add `log` example
  pages/common/git-bisect.md
Labels: page edit, review needed

#8456 rmdir: add Tamil translation
  pages.ta/windows/rmdir.md
Labels: translation

#8475 cargo: add example to compile using the nightly version
  pages/common/cargo.md
Labels: page edit

#8470 vigr: add page
  pages/linux/vigr.md
Labels: new command

#8476 npx: fix typo 'existis' -> 'it exists'
  pages/common/npx.md
Labels: page edit, minor change

#8473 lualatex: add page
  pages/common/lualatex.md
Labels: new command

#8479 asdf: remove hyphens from subcommands
  pages/common/asdf.md
Labels: page edit

#8480 pyats:add new page
  pages/common/pyats.md
Labels: new command

#8457 transmission-daemon: add page
  pages/common/transmission-daemon.md
Labels: new command

#8472 lxc: add execute example
  pages/linux/lxc.md
Labels: page edit, minor change

#8477 nsxiv: add page
  pages/linux/nsxiv.md
Labels: new command

#8459 transmission-show: add page
  pages/common/transmission-show.md
Labels: new command

#8481 docker-compose: update command to v2
  pages.de/common/docker-compose.md
  pages.es/common/docker-compose.md
  pages.fr/common/docker-compose.md
  pages.it/common/docker-compose.md
  pages.ko/common/docker-compose.md
  pages.pt_BR/common/docker-compose.md
  pages.tr/common/docker-compose.md
  pages/common/docker-compose.md
Labels: page edit, mass changes

#8485 env: add French translation
  pages.fr/common/env.md
Labels: translation

#8483 chmod: update French translation
  pages.fr/common/chmod.md
Labels: translation

#8484 diff: add French translation
  pages.fr/common/diff.md
Labels: translation

#8482 cd: update French translation
  pages.fr/common/cd.md
Labels: translation

#8408 tsv-filter: add page
  pages/common/tsv-filter.md
Labels: new command, review needed

#8434 woeusb: add page
  pages/linux/woeusb.md
Labels: new command

#8000 tldr: refresh page
  pages/common/tldr.md
Labels: page edit, stalebot ignore

#8486 gdb: add French translation
  pages.fr/common/gdb.md
Labels: translation

#8487 broot: add page
  pages/linux/broot.md
Labels: new command

#8498 rmdir: add Chinese translation
  pages.zh/common/rmdir.md
Labels: translation

#8494 git, git-rebase: add Chinese translation
  pages.zh/common/git-rebase.md
  pages.zh/common/git.md
Labels: translation

#8497 rm: add Chinese translation
  pages.zh/common/rm.md
Labels: translation

#8490 df: add Tamil translation
  pages.ta/common/df.md
Labels: translation

#8359 codespell.yml: add workflow
  .github/codespell-ignore
  .github/workflows/codespell.yml
Labels: new command, tooling, review needed

#8455 javac: fix path; java: update Tamil translation
  pages.pt_BR/common/javac.md
  pages.ta/common/java.md
  pages.ta/common/javac.md
  pages.zh/common/javac.md
  pages/common/javac.md
Labels: page edit, translation, review needed

#8489 brew: add Tamil translation
  pages.ta/common/brew.md
Labels: translation

#8492 protontricks: refresh page
  pages/linux/protontricks.md
Labels: page edit

#8495 npm-fund: add page
  pages/common/npm-fund.md
Labels: new command

#8496 style-guide: fix links
  contributing-guides/style-guide.md
Labels: documentation, page edit

#8458 transmission-edit: add page
  pages/common/transmission-edit.md
Labels: new command

#8499 git-clone, git-pull: add Chinese Translation
  pages.zh/common/git-clone.md
  pages.zh/common/git-pull.md
Labels: translation

#8493 clang-format: exhaustive style list
  pages/common/clang-format.md
Labels: page edit

#8503 cdk: fix typo in example
  pages/common/cdk.md
Labels: page edit, minor change

#8468 g++: add multiple file example
  pages/common/g++.md
Labels: page edit, minor change

#8290 tlmgr-dump-tlpdb, tlmgr-recreate-tlpdb: add page
  pages/common/tlmgr-dump-tlpdb.md
  pages/common/tlmgr-recreate-tlpdb.md
Labels: new command

#8504 [: update Chinese translation
  pages.zh/common/[.md
Labels: translation

#8505 [[: add Chinese translation
  pages.zh/common/[[.md
Labels: translation

#8511 llvd: add page
  pages/common/llvd.md
Labels: new command

#8506 ack: update Chinese translation
  pages.zh/common/ack.md
Labels: translation

#8508 autoconf: add page
  pages/common/autoconf.md
Labels: new command

#8510 fdupes: add example to replace dupes with hardlinks
  pages/common/fdupes.md
Labels: page edit

#8445 npm-query: add page
  pages/common/npm-query.md
Labels: new command

#7961 gsutil: add page
  pages/common/gsutil.md
Labels: new command

#8514 acme.sh-dns: add Chinese translation
  pages.zh/common/acme.sh-dns.md
Labels: translation

#8513 acme.sh: add Chinese translation
  pages.zh/common/acme.sh.md
Labels: translation

#8410 pulumi: add page
  pages/common/pulumi.md
Labels: new command, review needed

#7943 ed: add Russian translation
  pages.ru/common/ed.md
  pages.ru/osx/ed.md
Labels: translation, stalebot ignore, review needed

#8509 latexdiff: add page
  pages/common/latexdiff.md
Labels: new command

#8501 ISSUE_TEMPLATE/page-translation.yml: remove new command label
  .github/ISSUE_TEMPLATE/page-translation.yml
Labels: tooling, review needed

#8516 adb-install: update Chinese translation
  pages.zh/common/adb-install.md
Labels: translation

#8517 rfetch: add page
  rfetch.md
Labels: documentation, new command

#8519 mysqldump: fix example curly brackets placeholders
  pages/common/mysqldump.md
Labels: bug, page edit, minor change

#8527 rfetch: move to correct common directory
  pages/common/rfetch.md
Labels: page edit, minor change

#8520 csv-diff: add page
  pages/common/csv-diff.md
Labels: new command

#8518 workflows/*: add security hardening
  .github/workflows/ci.yml
  .github/workflows/mirror.yml
  .github/workflows/stale.yml
Labels: tooling

#8539 adscript: add Chinese translation
  pages.zh/common/adscript.md
Labels: translation

#8528 ruget: add page
  pages/linux/ruget.md
Labels: new command

#8535 osmium: add page
  pages/common/osmium.md
Labels: new command

#8529 docker-*: add French translation
  pages.fr/common/docker-build.md
  pages.fr/common/docker-commit.md
  pages.fr/common/docker-cp.md
  pages.fr/common/docker-exec.md
  pages.fr/common/docker-image.md
  pages.fr/common/docker-images.md
  pages.fr/common/docker-inspect.md
  pages.fr/common/docker-login.md
  pages.fr/common/docker-logs.md
  pages.fr/common/docker-machine.md
  pages.fr/common/docker-network.md
  pages.fr/common/docker-ps.md
  pages.fr/common/docker-rmi.md
  pages.fr/common/docker-run.md
  pages.fr/common/docker-save.md
  pages.fr/common/docker-secret.md
  pages.fr/common/docker-service.md
  pages.fr/common/docker-slim.md
  pages.fr/common/docker-start.md
  pages.fr/common/docker-stats.md
  pages.fr/common/docker-swarm.md
  pages.fr/common/docker-system.md
  pages.fr/common/docker-volume.md
Labels: mass changes, translation, review needed

#8534 gdaladdo: add page
  pages/common/gdaladdo.md
Labels: new command

#8546 az-version: add page
  pages/common/az-version.md
Labels: new command

#8547 pyenv: update Chinese translation
  pages.zh/common/pyenv.md
Labels: translation

#8467 pages.ta/*: update Tamil translation
  pages.ta/common/b2sum.md
  pages.ta/common/cd.md
  pages.ta/common/cksum.md
  pages.ta/common/cp.md
  pages.ta/common/git-add.md
  pages.ta/common/git-am.md
  pages.ta/common/git-annex.md
  pages.ta/common/git-apply.md
  pages.ta/common/git-archive.md
  pages.ta/common/git-branch.md
  pages.ta/common/git-bundle.md
  pages.ta/common/git-check-ignore.md
  pages.ta/common/git-clone.md
  pages.ta/common/git-commit.md
  pages.ta/common/grep.md
  pages.ta/common/md5sum.md
  pages.ta/common/mkdir.md
  pages.ta/common/mv.md
  pages.ta/common/rm.md
Labels: page edit, mass changes, translation, review needed
