Repository tldr-pages/tldr, pull requests merged in 2022-01, with the labels that each got.

#7590 ethtool: add example to show all features
  pages/linux/ethtool.md
Labels: page edit, review needed

#7438 go-build: add clarity
  pages/common/go-build.md
Labels: page edit, minor change

#7600 git-pr: add git-extras note in the command description
  pages/common/git-pr.md
Labels: page edit, minor change

#7593 pipwin: add page
  pages/windows/pipwin.md
Labels: new command, review needed

#7601 git-delete-merged-branches: fix title
  pages/common/git-delete-merged-branches.md
Labels: page edit, review needed, minor change

#7585 git-mr: add page
  pages/common/git-mr.md
Labels: new command, review needed

#7532 pabcnetcclear: update page
  pages/windows/pabcnetcclear.md
Labels: page edit

#7595 android/*: add Turkish translation
  pages.tr/android/bugreport.md
  pages.tr/android/bugreportz.md
  pages.tr/android/cmd.md
  pages.tr/android/dalvikvm.md
  pages.tr/android/dumpsys.md
  pages.tr/android/getprop.md
  pages.tr/android/logcat.md
  pages.tr/android/pkg.md
  pages.tr/android/pm.md
  pages.tr/android/settings.md
  pages.tr/android/wm.md
Labels: translation

#7594 wg: add example to show current configuration of an interface
  pages.fr/linux/wg.md
  pages/linux/wg.md
Labels: page edit, translation, review needed

#7610 enum4linux: fix typo
  pages/linux/enum4linux.md
Labels: page edit, review needed, minor change

#7490 topydo: add French translation
  pages.fr/common/topydo.md
Labels: translation

#7487 go: add French translation
  pages.fr/common/go.md
Labels: translation, review needed

#7525 doctl-account: add page
  pages/common/doctl-account.md
Labels: new command

#7609 sherlock: add page
  pages/linux/sherlock.md
Labels: new command

#7614 apt, dpkg: add Indonesian translation
  pages.id/linux/apt.md
  pages.id/linux/dpkg.md
Labels: translation

#7512 nvm.fish: add page
  pages/common/nvm.fish.md
Labels: new command, waiting

#7517 invoke-item: add page
  pages/windows/invoke-item.md
Labels: new command

#7618 file-rename: fix Debian package name
  pages/linux/file-rename.md
Labels: page edit, review needed, minor change

#7620 apt: add backticks to apt-get
  pages.de/linux/apt.md
  pages.es/linux/apt.md
  pages.fr/linux/apt.md
  pages.it/linux/apt.md
  pages.ml/linux/apt.md
  pages.tr/linux/apt.md
  pages.zh/linux/apt.md
  pages/linux/apt.md
Labels: page edit, translation, review needed, minor change

#7622 a2query, dpkg*, check-support-status, netselect-apt, reportbug: update Debian link
  pages.de/linux/a2query.md
  pages.de/linux/dpkg.md
  pages.fr/linux/a2query.md
  pages.id/linux/dpkg.md
  pages.it/linux/a2query.md
  pages.it/linux/dpkg-deb.md
  pages.it/linux/dpkg.md
  pages.pt_BR/linux/a2query.md
  pages.pt_BR/linux/dpkg.md
  pages.pt_PT/linux/a2query.md
  pages.zh/linux/a2query.md
  pages/linux/a2query.md
  pages/linux/check-support-status.md
  pages/linux/dpkg-deb.md
  pages/linux/dpkg.md
  pages/linux/netselect-apt.md
  pages/linux/reportbug.md
Labels: page edit, translation, review needed, minor change

#7625 ncdu: add `--color` example and link
  pages/linux/ncdu.md
Labels: page edit

#7623 mkfs.ext4: add Indonesian translation
  pages.id/linux/mkfs.ext4.md
Labels: translation, review needed

#7634 xfreerdp: add sound example
  pages/linux/xfreerdp.md
Labels: page edit

#7632 mkfs.btrfs: add Indonesian translation
  pages.id/linux/mkfs.btrfs.md
Labels: translation

#7619 terragrunt: add page
  pages/common/terragrunt.md
Labels: new command

#7635 glab-mr*: add pages
  pages/common/glab-mr-create.md
  pages/common/glab-mr-merge.md
  pages/common/glab-mr.md
Labels: new command, review needed

#7640 bat: fix typo in Chinese translation
  pages.zh/common/bat.md
Labels: translation, minor change

#7633 2to3: add French translation
  pages.fr/common/2to3.md
Labels: translation, review needed

#7631 archinstall: add pt_PT translation
  pages.pt_PT/linux/archinstall.md
Labels: translation, review needed

#7630 pacman: add pt_PT translation
  pages.pt_PT/linux/pacman.md
Labels: translation, review needed

#7545 pdbedit: add page; smbpasswd: improve comments & add `sudo`
  pages/linux/pdbedit.md
  pages/linux/smbpasswd.md
Labels: page edit, new command, waiting

#7644 check-language-support, faketime, pi, powerstat, rig, xdg-user-dirs-update: update links
  pages.es/linux/rig.md
  pages/linux/check-language-support.md
  pages/linux/faketime.md
  pages/linux/pi.md
  pages/linux/powerstat.md
  pages/linux/rig.md
  pages/linux/xdg-user-dirs-update.md
Labels: page edit, translation, review needed

#7629 textutil, top: add link
  pages.zh/osx/textutil.md
  pages.zh/osx/top.md
  pages/osx/textutil.md
  pages/osx/top.md
Labels: translation

#7641 glab-alias: add page
  pages/common/glab-alias.md
Labels: new command, review needed

#7653 package.json: update dependencies
  package-lock.json
  package.json
Labels: tooling, minor change

#7654 xrdb: add pt_PT translation
  pages.pt_PT/linux/xrdb.md
Labels: translation

#7658 pkg: add French translation
  pages.fr/android/pkg.md
Labels: translation, review needed

#7657 pkg: add Chinese translation
  pages.zh/android/pkg.md
Labels: translation

#7659 declare: fix -a example
  pages/common/declare.md
Labels: page edit, review needed, minor change

#7655 alias-pages: add pt_PT translation
  contributing-guides/translation-templates/alias-pages.md
Labels: documentation

#7656 alacritty: add pt_PT translation
  pages.pt_PT/common/alacritty.md
Labels: translation

#7666 ssh: fix typo
  pages/common/ssh.md
Labels: page edit

#7663 blender: use long arguments
  pages/common/blender.md
Labels: page edit

#7642 glab-pipeline: add page
  pages/common/glab-pipeline.md
Labels: new command, review needed

#7669 termdown: add page
  pages.de/common/termdown.md
  pages/common/termdown.md
Labels: new command, translation

#7113 prlimit: add page
  pages/linux/prlimit.md
Labels: new command, hacktoberfest-accepted

#7645 clifm: add page
  pages/common/clifm.md
Labels: new command

#7675 alias: page update
  pages/common/alias.md
Labels: page edit, review needed, minor change

#7672 scan-build: add page
  pages/common/scan-build.md
Labels: new command

#7674 alias: add Russian translation
  pages.ru/common/alias.md
Labels: translation

#7668 grep: add Russian translation
  pages.ru/common/grep.md
Labels: translation, review needed

#7617 xset: add enable/disable DPMS examples
  pages/linux/xset.md
Labels: page edit, review needed

#7615 glab-issue: add page
  pages/common/glab-issue.md
Labels: new command, review needed

#7667 adb-install, adb-reverse, adb-shell: add French translation
  pages.fr/common/adb-install.md
  pages.fr/common/adb-reverse.md
  pages.fr/common/adb-shell.md
Labels: translation, review needed

#7652 ntl: add page
  pages/common/netlify.md
  pages/common/ntl.md
Labels: page edit, new command, review needed

#7636 avifenc: add page
  pages/linux/avifenc.md
Labels: new command, review needed

#7676 core-validate-commit: add page
  pages/common/core-validate-commit.md
Labels: new command, review needed

#7643 glab-release: add page
  pages/common/glab-release.md
Labels: new command, review needed

#7682 vagrant: update init ubuntu example
  pages/common/vagrant.md
Labels: page edit

#7671 debootstrap: add Indonesian translation
  pages.id/linux/debootstrap.md
Labels: translation

#7679 MAINTAINERS: add @EmilySeville7cfg to collaborators
  MAINTAINERS.md
Labels: community

#7650 head: add Russian translation
  pages.ru/common/head.md
Labels: translation

#7553 color: add allowed color values
  pages/windows/color.md
Labels: page edit

#7638 distrobox: add page
  pages/linux/distrobox-create.md
  pages/linux/distrobox-enter.md
  pages/linux/distrobox-list.md
  pages/linux/distrobox-rm.md
Labels: new command, review needed

#7681 tail: refresh page
  pages/common/tail.md
Labels: page edit, review needed

#7689 mpg123: add page
  pages/linux/mpg123.md
Labels: new command

#7700 xterm: add more information link
  pages/linux/xterm.md
Labels: page edit, review needed, minor change

#7699 trust: add page
  pages/linux/trust.md
Labels: new command, review needed

#7696 yum: add Spanish translation
  pages.es/linux/yum.md
Labels: translation, review needed

#7707 swapoff: add more information link
  pages/linux/swapoff.md
Labels: page edit, minor change

#7706 swapon: add more information link
  pages/linux/swapon.md
Labels: page edit, minor change

#7705 su: add more information link
  pages.tr/common/su.md
  pages/common/su.md
Labels: page edit, translation, minor change

#7704 urxvt: add more information link
  pages/linux/urxvt.md
Labels: page edit, minor change

#7708 yum: use manned for more information link
  pages.fa/linux/yum.md
  pages/linux/yum.md
Labels: page edit, translation, minor change

#7698 xterm, st: add Indonesian translation
  pages.id/linux/st.md
  pages.id/linux/xterm.md
Labels: translation, review needed

#7549 mktemp: refresh page
  pages/common/mktemp.md
Labels: page edit

#7712 7za, 7zr: add French translation
  pages.fr/common/7za.md
  pages.fr/common/7zr.md
Labels: translation, review needed

#7715 rc-status: add more information link
  pages/linux/rc-status.md
Labels: page edit

#7716 rc-update: add more information link
  pages/linux/rc-update.md
Labels: page edit

#7720 xman: add more information link
  pages/linux/xman.md
Labels: page edit, minor change

#7721 xinput: add more information link
  pages/linux/xinput.md
Labels: page edit, minor change

#7719 xclock: add more information link
  pages/linux/xclock.md
Labels: page edit, minor change

#7714 rc-service: add more information link
  pages/linux/rc-service.md
Labels: page edit, minor change

#7711 diff-pdf: add page
  pages/common/diff-pdf.md
Labels: new command, review needed

#7717 code: add --new-window example
  pages/common/code.md
Labels: page edit, review needed

#7724 dig: fix more information link
  pages.it/common/dig.md
  pages.ja/common/dig.md
  pages.ko/common/dig.md
  pages.pt_BR/common/dig.md
  pages/common/dig.md
Labels: page edit, translation, minor change

#7713 git: add Spanish translation
  pages.es/common/git.md
Labels: translation, review needed

#7660 groupadd, groupdel, groupmod, groups: update page
  pages/common/groups.md
  pages/linux/groupadd.md
  pages/linux/groupdel.md
  pages/linux/groupmod.md
Labels: page edit, mass changes

#7661 useradd, userdel, usedmod, users: refresh page
  pages/common/users.md
  pages/linux/useradd.md
  pages/linux/userdel.md
  pages/linux/usermod.md
Labels: page edit, mass changes

#7728 ubuntu-security-status: add page
  pages/linux/ubuntu-security-status.md
Labels: new command

#7510 progress: add page
  pages/common/progress.md
Labels: page edit, review needed

#7531 if: update page
  pages/windows/if.md
Labels: page edit, waiting, review needed

#7703 pw-link: add page
  pages/linux/pw-link.md
Labels: new command, review needed

#7584 git-standup: add page
  pages/common/git-standup.md
Labels: new command, review needed
