Repository tldr-pages/tldr, pull requests merged in 2022-12, with the labels that each got.

#9562 virt-viewer: add page
  pages/linux/virt-viewer.md
Labels: new command

#9561 bully: add page
  pages/linux/bully.md
Labels: new command

#9565 calligra*: add pages
  pages/common/calligraflow.md
  pages/common/calligrasheets.md
  pages/common/calligrastage.md
  pages/common/calligrawords.md
Labels: new command

#9568 tshark: add Tamil translation, fix path
  pages.ta/linux/tshark.md
  pages/linux/tshark.md
Labels: page edit, translation

#9570 iverilog: add Tamil translation
  pages.ta/common/iverilog.md
Labels: translation

#9572 mount: add example of mounting for a specific user
  pages/common/mount.md
Labels: page edit, minor change

#9541 ark: refresh page
  pages/linux/ark.md
Labels: page edit

#9574 wm: add Spanish translation
  pages.es/android/wm.md
Labels: translation

#9573 pages.ta/*: refresh page; git-blame: update path
  pages.ta/common/ab.md
  pages.ta/common/ack.md
  pages.ta/common/cargo.md
  pages.ta/common/g++.md
  pages.ta/common/git-bisect.md
  pages.ta/common/git-blame.md
  pages.ta/common/ls.md
  pages.ta/common/sha1sum.md
  pages.ta/common/sha224sum.md
  pages.ta/common/sha256sum.md
  pages.ta/common/sha384sum.md
  pages.ta/common/sha512sum.md
  pages.ta/common/vt.md
  pages.ta/linux/flatpak.md
  pages.ta/linux/ruget.md
  pages.ta/windows/cd.md
  pages.ta/windows/choco-apikey.md
  pages.ta/windows/choco-info.md
  pages.ta/windows/choco-install.md
  pages.ta/windows/choco-list.md
  pages.ta/windows/choco-new.md
  pages.ta/windows/choco-outdated.md
  pages.ta/windows/choco-search.md
  pages.ta/windows/choco-source.md
  pages.ta/windows/choco-upgrade.md
  pages.ta/windows/cipher.md
  pages.ta/windows/curl.md
  pages/common/git-blame.md
Labels: page edit, mass changes, translation

#9421 android/*: add Russian translation
  pages.ru/android/am.md
  pages.ru/android/bugreport.md
  pages.ru/android/bugreportz.md
  pages.ru/android/cmd.md
  pages.ru/android/dalvikvm.md
  pages.ru/android/dumpsys.md
  pages.ru/android/getprop.md
  pages.ru/android/input.md
  pages.ru/android/logcat.md
  pages.ru/android/pkg.md
  pages.ru/android/pm.md
  pages.ru/android/screencap.md
  pages.ru/android/settings.md
  pages.ru/android/wm.md
Labels: translation, hacktoberfest-accepted

#9585 mkfile: move to common
  pages.zh/common/mkfile.md
  pages/common/mkfile.md
Labels: page edit, translation, review needed

#9507 linux package managers: add link to ArchWiki Rosetta
  pages/linux/apt.md
  pages/linux/dnf.md
  pages/linux/dpkg.md
  pages/linux/emerge.md
  pages/linux/pacman.md
  pages/linux/rpm.md
  pages/linux/yum.md
  pages/linux/zypper.md
Labels: page edit, waiting

#9590 bat: use long options
  pages/common/bat.md
Labels: page edit, minor change

#9542 konsole: refresh page
  pages/linux/konsole.md
Labels: page edit

#9576 arduino-builder: refresh page
  pages/common/arduino-builder.md
Labels: page edit

#9535 okular: refresh page
  pages/common/okular.md
Labels: page edit

#9423 rm: add German translation
  pages.de/common/rm.md
Labels: translation, hacktoberfest-accepted

#9597 img2txt: add page
  pages/linux/img2txt.md
Labels: new command

#9478 waifu2x-ncnn-vulkan: add page
  pages/common/waifu2x-ncnn-vulkan.md
Labels: new command

#9592 *: replace `file(s)` syntax and add `path/to/` to more things
  pages.it/common/rm.md
  pages/common/awk.md
  pages/common/axel.md
  pages/common/base32.md
  pages/common/base64.md
  pages/common/blender.md
  pages/common/ctags.md
  pages/common/curl.md
  pages/common/enca.md
  pages/common/espeak.md
  pages/common/exiftool.md
  pages/common/file.md
  pages/common/fortune.md
  pages/common/fzf.md
  pages/common/gh-gist.md
  pages/common/git-checkout.md
  pages/common/git-reset.md
  pages/common/hugo.md
  pages/common/ignite.md
  pages/common/ipfs.md
  pages/common/jmap.md
  pages/common/license.md
  pages/common/meshlabserver.md
  pages/common/mitmdump.md
  pages/common/mkfile.md
  pages/common/mongod.md
  pages/common/mp4box.md
  pages/common/mupdf.md
  pages/common/p4.md
  pages/common/pigz.md
  pages/common/readlink.md
  pages/common/rm.md
  pages/common/sc-im.md
  pages/common/shuf.md
  pages/common/sk.md
  pages/common/split.md
  pages/common/standard.md
  pages/common/terminalizer.md
  pages/common/tpp.md
  pages/common/tr.md
Labels: page edit, mass changes, translation

#9524 stty, tput: refresh pages
  pages/common/stty.md
  pages/common/tput.md
Labels: page edit

#9473 stty, tput, tty: add Russian translation
  pages.ru/common/stty.md
  pages.ru/common/tput.md
  pages.ru/common/tty.md
Labels: translation

#9424 pdfseparate: add German translation
  pages.de/common/pdfseparate.md
Labels: translation, hacktoberfest-accepted

#9041 braa: add page
  pages/linux/braa.md
Labels: new command, hacktoberfest-accepted

#9159 cipher, clip: add German translation
  pages.de/windows/cipher.md
  pages.de/windows/clip.md
Labels: translation, hacktoberfest-accepted

#9593 asciinema: update link
  pages/common/asciinema.md
Labels: page edit, minor change

#9594 procs: refresh page
  pages/linux/procs.md
Labels: page edit

#9591 fd: refresh
  pages/common/fd.md
Labels: page edit

#9426 vifm: add German translation
  pages.de/common/vifm.md
Labels: translation, hacktoberfest-accepted, review needed

#9526 trash-cli: refresh page
  pages/common/trash-cli.md
Labels: page edit, review needed

#9073 apt-file: update examples
  pages/linux/apt-file.md
Labels: page edit, hacktoberfest-accepted, review needed, minor change

#9375 lp, lpinfo, lpr, lpstat: add German translation
  pages.de/common/lp.md
  pages.de/common/lpinfo.md
  pages.de/common/lpr.md
  pages.de/common/lpstat.md
Labels: translation, hacktoberfest-accepted, review needed

#9587 devfsadm: add Russian translation
  pages.ru/sunos/devfsadm.md
Labels: translation

#9603 style-guide: fix typo in Option syntax
  contributing-guides/style-guide.md
Labels: documentation, minor change

#9575 krunvm: add page, add Spanish translation
  pages.es/common/krunvm.md
  pages/common/krunvm.md
Labels: new command, translation

#9384 khal: add German translation
  pages.de/common/khal.md
Labels: translation, hacktoberfest-accepted

#9382 git-merge-base: add page
  pages/common/git-merge-base.md
Labels: new command

#9615 am: add Spanish translation
  pages.es/android/am.md
Labels: translation

#9618 cmd: add Spanish translation
  pages.es/android/cmd.md
Labels: translation

#9619 dalvikvm: add Spanish translation
  pages.es/android/dalvikvm.md
Labels: translation

#9617 bugreportz: add Spanish translation
  pages.es/android/bugreportz.md
Labels: translation

#9613 gunzip: add `stdin` example
  pages/common/gunzip.md
Labels: page edit, minor change

#9536 dolphin: refresh page
  pages/linux/dolphin.md
Labels: page edit

#9529 style-guide.md: replace `token` with `placeholder` term
  contributing-guides/style-guide.md
Labels: documentation, review needed

#9608 abroot: add page
  pages/linux/abroot.md
Labels: new command

#9605 apx: refresh page
  pages/linux/apx.md
Labels: page edit

#9406 poetry: add German translation
  pages.de/common/poetry.md
Labels: translation, hacktoberfest-accepted

#9621 audacious: add page
  pages/common/audacious.md
Labels: new command

#9620 qmv: add -f do example
  pages/common/qmv.md
Labels: page edit, minor change

#9595 sd: refresh page
  pages/common/sd.md
Labels: page edit

#9626 MAINTAINERS: add @kbdharun to org
  MAINTAINERS.md
Labels: community

#7966 touch: refresh
  pages/common/touch.md
Labels: page edit, new command

#9627 pw-link: fix typo
  pages/linux/pw-link.md
Labels: page edit, minor change

#9369 aws-backup: add page
  pages/common/aws-backup.md
Labels: new command, hacktoberfest-accepted

#9571 git-stash: add option show
  pages/common/git-stash.md
Labels: page edit

#9633 tart: add page
  pages/osx/tart.md
Labels: new command

#9402 ansiweather: add German translation
  pages.de/common/ansiweather.md
Labels: translation, hacktoberfest-accepted

#9133 qm-guest-exec: add page
  pages/linux/qm-guest-exec.md
Labels: new command, waiting, hacktoberfest-accepted

#9177 ftxdiff: add page
  pages/osx/ftxdiff.md
Labels: new command, hacktoberfest-accepted

#9636 coproc: add page
  pages/common/coproc.md
  pages/linux/coproc.md
Labels: new command

#9638 README: fix GitHub actions badge
  README.md
Labels: documentation

#9256 bzip2: add examples
  pages/common/bzip2.md
Labels: page edit, hacktoberfest-accepted

#9545 kdenlive: add page
  pages/common/kdenlive.md
Labels: new command

#9567 ar: refresh page
  pages/common/ar.md
Labels: page edit

#9632 README: refresh page
  README.md
Labels: documentation

#9649 README: fix typo in link
  README.md
Labels: documentation, minor change

#9010 git-terminal.md: add instructions for CRLF on Windows
  contributing-guides/git-terminal.md
Labels: documentation, hacktoberfest-accepted

#9641 style-guide.md: fix broken path placeholders
  contributing-guides/style-guide.md
Labels: documentation

#9243 qm-showcmd: add page
  pages/linux/qm-showcmd.md
Labels: new command, hacktoberfest-accepted, review needed

#8746 kubectl-*: add German translation
  pages.de/common/kubectl-delete.md
  pages.de/common/kubectl-describe.md
  pages.de/common/kubectl-get.md
  pages.de/common/kubectl-logs.md
  pages.de/common/kubectl-rollout.md
  pages.de/common/kubectl-run.md
  pages.de/common/kubectl.md
Labels: translation, hacktoberfest-accepted

#9405 eslint: add German translation
  pages.de/common/eslint.md
Labels: translation, hacktoberfest-accepted

#8783 windows/*: add page
  pages/windows/get-acl.md
  pages/windows/get-date.md
  pages/windows/measure-command.md
  pages/windows/measure-object.md
  pages/windows/out-string.md
  pages/windows/pwsh-where.md
  pages/windows/resolve-path.md
  pages/windows/select-string.md
  pages/windows/set-acl.md
  pages/windows/set-date.md
  pages/windows/set-service.md
  pages/windows/show-markdown.md
  pages/windows/sls.md
  pages/windows/sort-object.md
  pages/windows/start-service.md
  pages/windows/stop-service.md
  pages/windows/tee-object.md
  pages/windows/test-json.md
  pages/windows/wait-process.md
  pages/windows/where-object.md
Labels: new command, hacktoberfest-accepted, review needed

#9650 MAINTAINERS: add @pixelcmtd to org
  MAINTAINERS.md
Labels: community

#9365 nix, nix-build, nix-env, nix-collect-garbage, nix-shell: add German translation
  pages.de/common/nix-build.md
  pages.de/common/nix-collect-garbage.md
  pages.de/common/nix-env.md
  pages.de/common/nix-shell.md
  pages.de/common/nix.md
  pages/common/nix-build.md
  pages/common/nix-collect-garbage.md
  pages/common/nix-shell.md
Labels: page edit, translation, hacktoberfest-accepted

#9644 dalvikvm: refresh page
  pages.ta/android/dalvikvm.md
  pages/android/dalvikvm.md
Labels: page edit, translation, minor change

#9653 id3v2: add page
  pages/linux/id3v2.md
Labels: new command

#8008 nemo: refresh page
  pages/linux/nemo.md
Labels: page edit

#9660 mumble: move to common
  pages/common/mumble.md
Labels: page edit, minor change

#9665 acme.sh-dns: add Spanish translation
  pages.es/common/acme.sh-dns.md
Labels: translation

#9662 pm: add Spanish translation
  pages.es/android/pm.md
Labels: translation

#9661 qmv: add -f do example
  pages/common/qmv.md
Labels: page edit

#9664 input: add Spanish translation
  pages.es/android/input.md
Labels: translation

#9657 pkg: add Spanish translation
  pages.es/android/pkg.md
Labels: translation

#9666 act: add Spanish translation
  pages.es/common/act.md
Labels: translation

#9663 settings: add Spanish translation
  pages.es/android/settings.md
Labels: translation

#9667 agate: add Spanish translation
  pages.es/common/agate.md
Labels: translation

#9477 czkawka-cli: add page
  pages/common/czkawka-cli.md
Labels: new command

#9656 README: add brew option
  README.md
Labels: documentation

#9454 git-setup: add German translation
  pages.de/common/git-setup.md
Labels: translation, hacktoberfest-accepted

#9669 scripts/deploy.sh: generate sha256sum of artifacts
  scripts/deploy.sh
Labels: tooling

#9674 scripts/deploy.sh: fix script syntax
  scripts/deploy.sh
Labels: bug, tooling, minor change

#9673 binwalk: move to common
  pages.it/common/binwalk.md
  pages.pt_BR/common/binwalk.md
  pages.zh/common/binwalk.md
  pages/common/binwalk.md
Labels: page edit, translation, minor change

#9677 poetry: remove list command
  pages/common/poetry.md
Labels: page edit

#9448 git-show-merged-branches: add German translation
  pages.de/common/git-show-merged-branches.md
Labels: translation, hacktoberfest-accepted

#9668 CLIENT-SPECIFICATION: Use main for asset link
  CLIENT-SPECIFICATION.md
Labels: documentation, review needed

#9230 pyrit: add page
  pages/linux/pyrit.md
Labels: new command, hacktoberfest-accepted, review needed

#9651 CLIENT-SPECIFICATION: Require support for long options
  CLIENT-SPECIFICATION.md
Labels: documentation, decision

#9658 pv: fix 'stop at' example
  pages/common/pv.md
Labels: page edit, minor change

#9659 ss: add -K example
  pages/linux/ss.md
Labels: page edit

#9549 useradd, userdel, usermod: update French translation
  pages.fr/linux/useradd.md
  pages.fr/linux/userdel.md
  pages.fr/linux/usermod.md
Labels: translation

#9676 autorandr: add change command
  pages/linux/autorandr.md
Labels: page edit

#9678 gcpdiag: add page
  pages/common/gcpdiag.md
Labels: documentation, new command

#7997 unzip: refresh page
  pages/common/unzip.md
Labels: page edit

#9689 airmon-ng: add Spanish translation
  pages.es/common/airmon-ng.md
Labels: translation

#9698 amass-enum: add Spanish translation
  pages.es/common/amass-enum.md
Labels: translation

#9691 ajson: add Spanish translation
  pages.es/common/ajson.md
Labels: translation

#9688 adscript: add Spanish translation
  pages.es/common/adscript.md
Labels: translation

#9686 ack: add Spanish translation
  pages.es/common/ack.md
Labels: translation
