Repository tldr-pages/tldr, pull requests merged in 2022-07, with the labels that each got.

#8168 abbr: add Chinese translation
  pages.zh/linux/abbr.md
Labels: translation

#8164 htop: add change tab command
  pages/common/htop.md
Labels: page edit, review needed, minor change

#8185 docsify: add page
  pages/common/docsify.md
Labels: new command, review needed

#8182 crontab: refresh
  pages/common/crontab.md
Labels: page edit

#8172 deb-get: add page
  pages/common/deb-get.md
Labels: new command, review needed

#8176 rpm: add --changelog example
  pages/linux/rpm.md
Labels: page edit, review needed

#8074 s3cmd: add page
  pages/common/s3cmd.md
Labels: new command

#8191 calc: move from `linux` to `common` #2
  pages.ca/common/calc.md
Labels: translation, review needed, minor change

#8186 nyxt: add page
  pages/common/nyxt.md
Labels: new command

#8193 tlmgr-key: add page
  pages/common/tlmgr-key.md
Labels: new command, review needed

#8199 alex: add pt_BR translation
  pages.pt_BR/common/alex.md
Labels: translation

#8177 invoke-webrequest: add page
  pages/windows/curl.md
  pages/windows/invoke-webrequest.md
  pages/windows/iwr.md
  pages/windows/wget.md
Labels: new command

#8207 code: fix typo in --user-data-dir example
  pages/common/code.md
Labels: page edit, minor change

#8206 mate: add page
  pages/osx/mate.md
Labels: new command

#8162 gdalinfo: add page
  pages/common/gdalinfo.md
Labels: new command

#8213 brightnessctl: fix typo in decrease example
  pages.zh/linux/brightnessctl.md
  pages/linux/brightnessctl.md
Labels: page edit, translation, minor change

#8197 adguardhome, adscript, ag: add French translation
  pages.fr/common/adguardhome.md
  pages.fr/common/adscript.md
  pages.fr/common/ag.md
Labels: translation

#7767 swaks: add page
  pages/linux/swaks.md
Labels: new command, stalebot ignore

#8175 fuser: add example to kill processes bound to a specific socket
  pages/linux/fuser.md
Labels: page edit

#8149 calc: set help example as lastest example
  pages.de/common/calc.md
  pages/common/calc.md
Labels: page edit, new command, translation

#8209 amass, amass-db, amass-enum: add French translation
  pages.fr/common/amass-db.md
  pages.fr/common/amass-enum.md
  pages.fr/common/amass.md
Labels: translation

#8210 amass-intel, amass-track, amass-viz: add French translation
  pages.fr/common/amass-intel.md
  pages.fr/common/amass-track.md
  pages.fr/common/amass-viz.md
Labels: translation

#8190 brew-mas: remove (wrong) Chinese translation
  pages.zh/common/brew-mas.md
Labels: page edit, translation

#8189 pkg: add German translation
  pages.de/android/pkg.md
Labels: translation, review needed

#8219 mv, whoami, whois: add Chinese translation
  pages.zh/common/mv.md
  pages.zh/common/whoami.md
  pages.zh/common/whois.md
Labels: translation

#8220 dnf: add history example
  pages/linux/dnf.md
Labels: page edit, review needed

#8179 zsh: add noglob example
  pages.de/common/zsh.md
  pages/common/zsh.md
Labels: page edit, translation, review needed

#8198 agate: add pt_BR translation
  pages.pt_BR/common/agate.md
Labels: translation, review needed

#8169 varnishlog: add page
  pages/common/varnishlog.md
Labels: new command, waiting, review needed

#8216 man: use long options in examples
  pages/linux/man.md
Labels: page edit, new command

#8226 MAINTAINERS: add @Nico385412 to collaborators
  MAINTAINERS.md
Labels: community

#8227 linux/*: fix typos
  pages/linux/create_ap.md
  pages/linux/ctr.md
  pages/linux/f5fpc.md
  pages/linux/htpdate.md
  pages/linux/ipcmk.md
  pages/linux/paru.md
  pages/linux/rc-service.md
Labels: page edit, mass changes, minor change

#8212 androguard, ani-cli: add French translation
  pages.fr/common/androguard.md
  pages.fr/common/ani-cli.md
Labels: translation

#8195 rpi-eeprom-update: add page
  pages/linux/rpi-eeprom-update.md
Labels: new command, review needed

#8194 acyclic: add French translation
  pages.fr/common/acyclic.md
Labels: translation, review needed

#8171 duf: add page
  pages/common/duf.md
Labels: new command

#8211 abbr: add pt_BR translation
  pages.pt_BR/linux/abbr.md
Labels: translation

#8223 ansiweather, ant: add French translation
  pages.fr/common/ansiweather.md
  pages.fr/common/ant.md
Labels: translation

#8204 licensor: add page
  pages/common/licensor.md
Labels: new command

#8228 dpkg-query: add --search option, use long form of short options
  pages/linux/dpkg-query.md
Labels: page edit, review needed

#8230 cmctl: add page
  pages/common/cmctl.md
Labels: new command

#8235 ac: add pt_BR translation
  pages.pt_BR/linux/ac.md
Labels: translation

#8205 cot: add page
  pages/osx/cot.md
Labels: new command

#8222 ansible-playbook, ansible-pull, ansible-vault: add French translation
  pages.fr/common/ansible-playbook.md
  pages.fr/common/ansible-pull.md
  pages.fr/common/ansible-vault.md
Labels: translation, review needed

#8202 agate, airmon-ng, airpaste: add French translation
  pages.fr/common/agate.md
  pages.fr/common/airmon-ng.md
  pages.fr/common/airpaste.md
Labels: translation

#8239 psql: clarify default host behaviour
  pages/common/psql.md
Labels: page edit, review needed

#8238 pyinfra: add page
  pages/common/pyinfra.md
Labels: new command

#8242 helix: fix command name, hx: add page
  pages/common/helix.md
  pages/common/hx.md
Labels: page edit, new command, minor change

#8240 ar, arc, arch: add French translation
  pages.fr/common/ar.md
  pages.fr/common/arc.md
  pages.fr/common/arch.md
Labels: translation

#8196 pdfxup: add page
  pages/linux/pdfxup.md
Labels: new command, review needed

#8243 awk, chmod, chown: add Chinese translation
  pages.zh/common/awk.md
  pages.zh/common/chmod.md
  pages.zh/common/chown.md
Labels: translation

#8217 ansible-doc, ansible-galaxy, ansible-inventory: add French translation
  pages.fr/common/ansible-doc.md
  pages.fr/common/ansible-galaxy.md
  pages.fr/common/ansible-inventory.md
Labels: translation

#8200 gdal_contour: add page
  pages/common/gdal_contour.md
Labels: new command, review needed

#8251 piactl: fix broken link
  pages/common/piactl.md
Labels: page edit, minor change

#8246 cargo-add: add page
  pages/common/cargo-add.md
Labels: new command

#8234 apktool, apm: add French translation, update
  pages.fr/common/apktool.md
  pages.fr/common/apm.md
  pages/common/apktool.md
  pages/common/apm.md
Labels: page edit, translation

#8215 xdg-settings: add page
  pages/linux/xdg-settings.md
Labels: new command

#8255 *: add/edit more information link
  pages.nl/common/visudo.md
  pages.sv/common/visudo.md
  pages/common/singularity.md
  pages/common/spatial.md
  pages/common/virt-sparsify.md
  pages/common/visudo.md
  pages/common/waitress-serve.md
Labels: page edit, translation

#8254 quarto: add page
  pages/common/quarto.md
Labels: new command

#8244 picom-trans: add page
  pages/common/picom-trans.md
Labels: new command

#8229 ern: add page
  pages/common/ern.md
Labels: new command, review needed

#8250 security: add trusted cert add/remove examples
  pages/osx/security.md
Labels: page edit

#8262 docker-run: use long options for examples
  pages.de/common/docker-run.md
  pages.pt_BR/common/docker-run.md
  pages.tr/common/docker-run.md
  pages/common/docker-run.md
Labels: page edit, translation, minor change

#8260 acpi: add pt_BR translation
  pages.pt_BR/linux/acpi.md
Labels: translation

#8259 rustup-init.sh: add page
  pages/common/rustup-init.sh.md
Labels: new command

#8249 make: add variable override example
  pages/common/make.md
Labels: page edit

#8261 arp, arp-scan: add French translation
  pages.fr/common/arp-scan.md
  pages.fr/common/arp.md
Labels: translation

#8265 ripgrep: add page
  pages/common/ripgrep.md
Labels: new command

#8263 arping, asar: add French translation
  pages.fr/common/arping.md
  pages.fr/common/asar.md
Labels: translation

#7822 cmp: refresh page
  pages/common/cmp.md
Labels: page edit, stalebot ignore

#8264 nmcli-general, nmcli-networking: add page
  pages/linux/nmcli-agent.md
  pages/linux/nmcli-connection.md
  pages/linux/nmcli-device.md
  pages/linux/nmcli-general.md
  pages/linux/nmcli-monitor.md
  pages/linux/nmcli-networking.md
  pages/linux/nmcli-radio.md
Labels: page edit, new command

#8267 pkg-config: move to common
  pages/common/pkg-config.md
Labels: page edit, minor change

#8248 uname: add page
  pages/linux/uname.md
Labels: new command

#8268 cal, calc, cd: add Tamil translation
  pages.ta/common/calc.md
  pages.ta/common/cd.md
  pages.ta/linux/cal.md
Labels: translation

#8266 go-*: add Chinese translation
  pages.zh/common/go-bug.md
  pages.zh/common/go-build.md
  pages.zh/common/go-clean.md
  pages.zh/common/go-doc.md
  pages.zh/common/go-env.md
Labels: translation

#7956 vgmstream_cli: add page
  pages/common/vgmstream_cli.md
Labels: new command

#8247 arduino, arduino-builder: add French translation
  pages.fr/common/arduino-builder.md
  pages.fr/common/arduino.md
Labels: translation
