Repository tldr-pages/tldr, pull requests merged in 2022-11, with the labels that each got.

#9415 common/*: fix Nepali translation
  pages.ne/common/at.md
  pages.ne/common/bg.md
  pages.ne/common/ffmpeg.md
  pages.ne/common/ls.md
Labels: translation, hacktoberfest-accepted, minor change

#9398 truss: add French translation
  pages.fr/sunos/truss.md
Labels: translation, hacktoberfest-accepted

#9391 dmesg: add French translation
  pages.fr/sunos/dmesg.md
Labels: translation, hacktoberfest-accepted

#9390 screencap: add French translation
  pages.fr/android/screencap.md
Labels: translation, hacktoberfest-accepted

#9393 prstat: add French translation
  pages.fr/sunos/prstat.md
Labels: translation, hacktoberfest-accepted

#9397 svcs: add French translation
  pages.fr/sunos/svcs.md
Labels: translation, hacktoberfest-accepted

#9389 devfsadm: add French translation
  pages.fr/sunos/devfsadm.md
Labels: translation, hacktoberfest-accepted

#9392 prctl: add French translation
  pages.fr/sunos/prctl.md
  pages.ta/sunos/prctl.md
  pages/sunos/prctl.md
Labels: page edit, translation, hacktoberfest-accepted

#9395 snoop: add French translation
  pages.fr/sunos/snoop.md
Labels: translation, hacktoberfest-accepted

#9471 ansible: add pt_BR translation
  pages.pt_BR/common/ansible.md
Labels: translation

#9407 chcon, curlie, dex: add French translation
  pages.fr/linux/chcon.md
  pages.fr/linux/curlie.md
  pages.fr/linux/dex.md
Labels: translation, hacktoberfest-accepted

#9428 jq: remove tokenization of dot operator
  pages.de/common/jq.md
  pages.ru/common/jq.md
  pages/common/jq.md
Labels: page edit, translation, hacktoberfest-accepted

#9394 svcadm: add French translation
  pages.fr/sunos/svcadm.md
Labels: translation, hacktoberfest-accepted

#9441 expect, newgrp, powertop: add Polish translation
  pages.pl/linux/expect.md
  pages.pl/linux/newgrp.md
  pages.pl/linux/powertop.md
Labels: translation, hacktoberfest-accepted

#9470 git-feature: add page
  pages/common/git-feature.md
Labels: new command

#9385 git-scp: add page
  pages/common/git-scp.md
Labels: new command, hacktoberfest-accepted

#9480 errno: fix grammar in example description
  pages/common/errno.md
Labels: page edit, minor change

#9451 [[: add pt_BR translation
  pages.pt_BR/common/[[.md
Labels: translation, hacktoberfest-accepted

#9482 git-feature: fix page title
  pages/common/git-feature.md
Labels: page edit, minor change

#9479 screencap: add Spanish translation
  pages.es/android/screencap.md
Labels: translation

#9103 cargo: add French translation
  pages.fr/common/cargo.md
Labels: translation, hacktoberfest-accepted

#9483 cls: add Spanish translation
  pages.es/windows/cls.md
Labels: translation

#9489 aws-pricing: add Spanish translation
  pages.es/common/aws-pricing.md
Labels: translation

#9438 stat: refresh page
  pages/common/stat.md
Labels: page edit, hacktoberfest-accepted

#9492 conky: fix align example
  pages/linux/conky.md
Labels: page edit

#9437 bg, fg: add Japanese translation
  pages.ja/common/bg.md
  pages.ja/common/fg.md
Labels: translation, hacktoberfest-accepted, review needed

#9494 pkcon: add page
  pages/linux/pkcon.md
Labels: new command

#9497 abduco: add Spanish translation
  pages.es/common/abduco.md
Labels: translation

#9488 railway: add page
  pages/common/railway.md
Labels: new command

#9499 xauth: add page
  pages/linux/xauth.md
Labels: new command, review needed

#9496 wacaw: rename to wacaw.md
  pages.es/osx/wacaw.md
Labels: translation, minor change

#9498 kill: add French translation
  pages.fr/common/kill.md
Labels: translation

#9465 stty: refresh page
  pages/common/stty.md
Labels: page edit

#9467 virt-xml-validate: add page
  pages/linux/virt-xml-validate.md
Labels: new command, review needed

#9503 cut: use `--delimiter` with `--fields`
  pages/common/cut.md
Labels: page edit

#9485 gprof: add page
  pages/common/gprof.md
Labels: new command

#9002 duf, ebook-convert: add German translation
  pages.de/common/duf.md
  pages.de/common/ebook-convert.md
  pages.de/common/ical.md
Labels: documentation, translation, hacktoberfest-accepted

#9312 cipher: edit page
  pages/windows/cipher.md
Labels: page edit, hacktoberfest-accepted

#9145 cockpit-*: add page
  pages/linux/cockpit-bridge.md
  pages/linux/cockpit-desktop.md
  pages/linux/cockpit-tls.md
Labels: new command, hacktoberfest-accepted, review needed

#9088 gcc: add -g to -Wall -Og example
  pages/common/gcc.md
Labels: page edit, hacktoberfest-accepted, review needed

#9501 apx: add page
  pages/linux/apx.md
Labels: new command

#9491 quarto: refresh page
  pages/common/quarto.md
Labels: page edit

#9452 say: update page
  pages/osx/say.md
Labels: page edit, hacktoberfest-accepted

#9490 aria2: update translations to match en page
  pages.it/common/aria2.md
  pages.ko/common/aria2.md
  pages.zh/common/aria2.md
Labels: translation

#7931 sed: refresh/add pages
  pages/common/sed.md
  pages/osx/sed.md
Labels: page edit

#9435 pbpaste: add German translation
  pages.de/osx/pbpaste.md
Labels: translation, hacktoberfest-accepted

#9516 acyclic: add Spanish translation
  pages.es/common/acyclic.md
Labels: translation

#9510 icalBuddy: add Spanish translation
  pages.es/osx/icalbuddy.md
Labels: translation

#9518 ag: add Spanish translation
  pages.es/common/ag.md
Labels: translation

#9517 btrfs*, mkfs.btrfs: update link to new website
  pages.fr/linux/btrfs-check.md
  pages.fr/linux/btrfs-device.md
  pages.fr/linux/btrfs-filesystem.md
  pages.fr/linux/btrfs-inspect-internal.md
  pages.fr/linux/btrfs-rescue.md
  pages.fr/linux/btrfs-restore.md
  pages.fr/linux/btrfs-scrub.md
  pages.fr/linux/btrfs-subvolume.md
  pages.fr/linux/btrfs-version.md
  pages.fr/linux/btrfs.md
  pages.id/linux/mkfs.btrfs.md
  pages.pt_BR/linux/btrfs-balance.md
  pages.pt_BR/linux/btrfs-check.md
  pages.pt_BR/linux/btrfs-device.md
  pages.pt_BR/linux/btrfs-filesystem.md
  pages.pt_BR/linux/btrfs-inspect-internal.md
  pages.pt_BR/linux/btrfs-property.md
  pages.pt_BR/linux/btrfs-rescue.md
  pages.pt_BR/linux/btrfs-subvolume.md
  pages.pt_BR/linux/btrfs.md
  pages.zh/linux/btrfs-device.md
  pages.zh/linux/btrfs-filesystem.md
  pages.zh/linux/btrfs-scrub.md
  pages.zh/linux/btrfs-subvolume.md
  pages.zh/linux/btrfs.md
  pages/linux/btrfs-balance.md
  pages/linux/btrfs-check.md
  pages/linux/btrfs-device.md
  pages/linux/btrfs-filesystem.md
  pages/linux/btrfs-inspect-internal.md
  pages/linux/btrfs-property.md
  pages/linux/btrfs-rescue.md
  pages/linux/btrfs-restore.md
  pages/linux/btrfs-scrub.md
  pages/linux/btrfs-subvolume.md
  pages/linux/btrfs-version.md
  pages/linux/btrfs.md
  pages/linux/mkfs.btrfs.md
Labels: page edit, mass changes, translation

#9505 apx: add Tamil translation
  pages.ta/linux/apx.md
Labels: translation

#9506 vt: add Tamil translation
  pages.ta/common/vt.md
Labels: translation

#9514 gem, ruby: add Tamil translation
  pages.ta/common/gem.md
  pages.ta/common/ruby.md
Labels: translation

#9512 jekyll: update link, add Tamil translation
  pages.fr/common/jekyll.md
  pages.ta/common/jekyll.md
  pages/common/jekyll.md
Labels: page edit, translation

#9508 scoop: improve example to update all packages
  pages/windows/scoop.md
Labels: page edit, minor change

#9504 ac: add Spanish translation
  pages.es/common/ac.md
Labels: translation

#9474 tput: refresh page
  pages/common/tput.md
Labels: page edit, minor change

#9511 tar: fix typo in Russian translation
  pages.ru/common/tar.md
Labels: translation, minor change

#9464 nohup: use variable number of arguments in token
  pages.ru/common/nohup.md
  pages/common/nohup.md
Labels: page edit, translation

#9519 snowsql: add page
  pages.pl/common/snowsql.md
  pages/common/snowsql.md
Labels: new command, translation

#9486 hexdump: refresh page and Chinese translation
  pages.zh/common/hexdump.md
  pages/common/hexdump.md
Labels: page edit, translation, review needed

#9176 esa-snap: add German page
  pages.de/linux/esa-snap.md
Labels: translation, hacktoberfest-accepted

#9500 bb: add page
  pages/common/bb.md
Labels: new command

#9129 hexdump: add Russian translation
  pages.ru/common/hexdump.md
Labels: translation, hacktoberfest-accepted

#9487 fg: refresh Russian translation
  pages.ru/common/fg.md
Labels: translation

#9525 pngquant: add page
  pages/common/pngquant.md
Labels: new command

#9495 osx/*: add pt_BR translations
  pages.pt_BR/osx/hdiutil.md
  pages.pt_BR/osx/hidd.md
  pages.pt_BR/osx/icalbuddy.md
  pages.pt_BR/osx/imgcat.md
  pages.pt_BR/osx/indent.md
  pages.pt_BR/osx/internetsharing.md
  pages.pt_BR/osx/istats.md
Labels: translation

#9522 exiftool: Add "-gps*=" removal example
  pages/common/exiftool.md
Labels: page edit

#9533 head: remove page from osx
  pages/osx/head.md
Labels: page edit

#9532 xmodmap: added closing single-quote
  pages/linux/xmodmap.md
Labels: page edit, minor change

#9509 qmmp: add page
  pages/common/qmmp.md
Labels: new command

#9534 icalbuddy: Add long options on examples
  pages/osx/icalbuddy.md
Labels: page edit

#9537 curl: update link to man page
  pages.de/common/curl.md
  pages.fr/common/curl.md
  pages.id/common/curl.md
  pages.it/common/curl.md
  pages.ko/common/curl.md
  pages.pt_BR/common/curl.md
Labels: translation, minor change

#9540 poetry: update "dev dependency" example
  pages/common/poetry.md
Labels: page edit, minor change

#9348 osx/caffeinate, say, uuidgen: add Polish translation
  pages.pl/osx/caffeinate.md
  pages.pl/osx/say.md
  pages.pl/osx/uuidgen.md
Labels: translation, hacktoberfest-accepted

#7731 read: fix missing backslash
  pages/common/read.md
Labels: page edit, minor change

#9273 k3d: add page
  pages/common/k3d.md
Labels: new command, hacktoberfest-accepted

#9521 mkvmerge: add subtitle track example
  pages/common/mkvmerge.md
Labels: page edit

#9547 choco: add traditional Chinese translation
  pages.zh_TW/windows/choco.md
Labels: translation

#9469 scripts/test.sh: add batching to markdownlint
  scripts/test.sh
Labels: tooling

#9443 verilator: add page
  pages/common/verilator.md
Labels: new command, hacktoberfest-accepted

#9539 pytest: add page
  pages/common/pytest.md
Labels: new command

#9456 virt-xml: add page
  pages/linux/virt-xml.md
Labels: new command

#9554 setfile: add page
  pages/osx/setfile.md
Labels: new command

#9544 feroxbuster: add page
  pages/common/feroxbuster.md
Labels: new command

#9551 iverilog: update page
  pages/common/iverilog.md
Labels: page edit

#9559 verilator: fix typo
  pages/common/verilator.md
Labels: page edit, minor change

#9555 mount: add --mkdir example
  pages/common/mount.md
Labels: page edit

#9548 tar, wc, zsh: update French translation
  pages.fr/common/tar.md
  pages.fr/common/wc.md
  pages.fr/common/zsh.md
Labels: translation

#9513 vim: Cross-reference pages
  pages/common/nvim.md
  pages/common/vim.md
  pages/common/vimdiff.md
  pages/common/vimtutor.md
Labels: page edit, decision, minor change

#9553 kdeconnect-cli: refresh page
  pages/common/kdeconnect-cli.md
Labels: page edit

#9546 kate: refresh page
  pages/common/kate.md
Labels: page edit

#9419 clangd: add page
  pages/common/clangd.md
Labels: new command, hacktoberfest-accepted

#9563 cbt: add page
  pages/common/cbt.md
Labels: new command

#9399 date: add German translation
  pages.de/common/date.md
Labels: translation, hacktoberfest-accepted

#9466 pdfunite: add German translation
  pages.de/common/pdfunite.md
Labels: translation

#9552 spectacle: add page
  pages/common/spectacle.md
Labels: new command

#9558 lspath: add page
  pages/common/lspath.md
Labels: new command
