Repository tldr-pages/tldr, pull requests merged in 2022-08, with the labels that each got.

#8272 gdal_translate: add page
  pages/common/gdal_translate.md
Labels: new command

#8188 tlmgr-conf: add page
  pages/common/tlmgr-conf.md
Labels: new command, review needed

#8269 osx/*: add pt_BR translations
  pages.pt_BR/osx/caffeinate.md
  pages.pt_BR/osx/cal.md
  pages.pt_BR/osx/carthage.md
  pages.pt_BR/osx/cfprefsd.md
  pages.pt_BR/osx/chflags.md
  pages.pt_BR/osx/cloudphotod.md
  pages.pt_BR/osx/codesign.md
  pages.pt_BR/osx/coreaudiod.md
  pages.pt_BR/osx/coreautha.md
  pages.pt_BR/osx/coreauthd.md
  pages.pt_BR/osx/cot.md
  pages.pt_BR/osx/csrutil.md
  pages.pt_BR/osx/csshx.md
  pages.pt_BR/osx/cut.md
Labels: translation, review needed

#8276 flameshot: fix time unit in --delay example
  pages/linux/flameshot.md
Labels: page edit, minor change

#8253 aria2, aria2c: add French translation & page edit
  pages.fr/common/aria2.md
  pages.fr/common/aria2c.md
  pages/common/aria2c.md
Labels: page edit, translation

#8273 PULL_REQUEST_TEMPLATE: reduce interline spacing
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, minor change

#8274 gdalwarp: add page
  pages/common/gdalwarp.md
Labels: new command, review needed

#8019 wine: refresh page
  pages/linux/wine.md
Labels: page edit, stalebot ignore

#8283 cc: add alias page
  pages/linux/cc.md
Labels: new command

#7984 powershell: refresh page
  pages/common/powershell.md
  pages/windows/powershell.md
Labels: page edit, stalebot ignore

#8291 fc: remove subcommand mention
  pages.pt_BR/common/fc.md
  pages/common/fc.md
Labels: page edit, translation, minor change

#8295 wine: add Tamil translation
  pages.ta/linux/wine.md
Labels: translation

#8302 hdparm: add read speed example
  pages/linux/hdparm.md
Labels: page edit

#8293 dnf: add Tamil translation
  pages.ta/linux/dnf.md
Labels: translation

#8294 apt: add Tamil translation
  pages.ta/linux/apt.md
Labels: translation

#8285 assimp, astronomer: add French translation
  pages.fr/common/assimp.md
  pages.fr/common/astronomer.md
Labels: translation

#8280 toolbox: add pages
  pages/linux/toolbox-create.md
  pages/linux/toolbox-enter.md
  pages/linux/toolbox-help.md
  pages/linux/toolbox-init-container.md
  pages/linux/toolbox-list.md
  pages/linux/toolbox-rm.md
  pages/linux/toolbox-rmi.md
  pages/linux/toolbox-run.md
  pages/linux/toolbox.md
Labels: new command, mass changes

#8299 grafana-cli: add page
  pages/common/grafana-cli.md
Labels: new command

#8292 cc, g++, gcc: add Tamil translation
  pages.ta/common/g++.md
  pages.ta/common/gcc.md
  pages.ta/linux/cc.md
Labels: translation

#8301 common-arguments: update Tamil translation
  contributing-guides/translation-templates/common-arguments.md
Labels: documentation

#8300 chmod: update placeholders in examples
  pages/common/chmod.md
Labels: page edit, minor change

#8279 asciidoctor, asciinema: add French translation
  pages.fr/common/asciidoctor.md
  pages.fr/common/asciinema.md
Labels: translation

#8311 MAINTAINERS: add @kbdharun to collaborators
  MAINTAINERS.md
Labels: community

#8282 uname: add Tamil translation
  pages.ta/common/uname.md
  pages.ta/linux/uname.md
  pages.ta/osx/uname.md
Labels: translation

#8225 antibody, apg: add French translation
  pages.fr/common/antibody.md
  pages.fr/common/apg.md
  pages/common/antibody.md
Labels: page edit, translation, stalebot ignore

#8289 tlmgr-repository: add page
  pages/common/tlmgr-repository.md
Labels: new command

#8303 pkg: add Indonesian translation
  pages.id/android/pkg.md
Labels: translation

#8208 ajson, alacritty, alex: add French translation
  pages.fr/common/ajson.md
  pages.fr/common/alacritty.md
  pages.fr/common/alex.md
Labels: waiting, translation

#8232 sdk: generalize for any SDKs and enhance explanations
  pages/common/sdk.md
Labels: page edit

#8316 atq, atrm, auditd: add French translation
  pages.fr/common/atq.md
  pages.fr/common/atrm.md
  pages.fr/common/auditd.md
Labels: translation

#8288 tlmgr-restore: add page
  pages/common/tlmgr-backup.md
  pages/common/tlmgr-restore.md
Labels: page edit, new command

#8318 flatpak: add Tamil translation
  pages.ta/linux/flatpak.md
Labels: translation

#8305 astyle, atoum: add French translation
  pages.fr/common/astyle.md
  pages.fr/common/atoum.md
Labels: translation

#8317 powershell: add Tamil translation
  pages.ta/common/powershell.md
Labels: translation

#8320 pages.ta/*: fix more information Tamil translation
  pages.ta/common/calc.md
  pages.ta/common/cd.md
  pages.ta/common/g++.md
  pages.ta/common/gcc.md
  pages.ta/common/powershell.md
  pages.ta/common/uname.md
  pages.ta/linux/apt.md
  pages.ta/linux/cal.md
  pages.ta/linux/cc.md
  pages.ta/linux/dnf.md
  pages.ta/linux/flatpak.md
  pages.ta/linux/uname.md
  pages.ta/linux/wine.md
  pages.ta/osx/uname.md
Labels: translation

#8315 grub-bios-setup: add page
  pages/linux/grub-bios-setup.md
Labels: new command

#8319 ufw: add Tamil translation
  pages.ta/linux/ufw.md
Labels: translation

#8312 flameshot: fix Chinese translation
  pages.zh/linux/flameshot.md
Labels: translation

#8313 addpart: add pt_BR translation
  pages.pt_BR/linux/addpart.md
Labels: translation

#8314 gum: add page
  pages/common/gum.md
Labels: new command

#8278 inotifywait: add --monitor command
  pages/linux/inotifywait.md
Labels: page edit

#8322 archinstall: add Tamil translation
  pages.ta/linux/archinstall.md
Labels: translation

#8325 autoflake, autojump, autopep8: add French translation
  pages.fr/common/autoflake.md
  pages.fr/common/autojump.md
  pages.fr/common/autopep8.md
Labels: translation

#8277 rpm-ostree: add page
  pages/linux/rpm-ostree.md
Labels: new command

#8326 MAINTAINERS: add organization owner: @marchersimon
  MAINTAINERS.md
Labels: community

#8330 prctl: refresh command description
  pages/sunos/prctl.md
Labels: page edit

#8324 termusic: add pages
  pages/linux/termusic.md
Labels: new command

#8334 sunos/*: add Tamil translations
  pages.ta/sunos/devfsadm.md
  pages.ta/sunos/dmesg.md
  pages.ta/sunos/prctl.md
  pages.ta/sunos/prstat.md
  pages.ta/sunos/snoop.md
  pages.ta/sunos/svcadm.md
  pages.ta/sunos/svccfg.md
  pages.ta/sunos/svcs.md
  pages.ta/sunos/truss.md
Labels: mass changes, translation

#8327 pyenv: add example to list all installable versions
  pages.it/common/pyenv.md
  pages/common/pyenv.md
Labels: page edit, translation

#8308 page-request.yml: reword and remove parts
  .github/ISSUE_TEMPLATE/page-request.yml
Labels: tooling

#8335 autossh, avo: add French translation
  pages.fr/common/autossh.md
  pages.fr/common/avo.md
Labels: translation

#8286 pacman: use short options only
  pages.de/linux/pacman.md
  pages.fr/linux/pacman.md
  pages.ml/linux/pacman.md
  pages.pt_BR/linux/pacman.md
  pages.pt_PT/linux/pacman.md
  pages.tr/linux/pacman.md
  pages.zh/linux/pacman.md
  pages/linux/pacman.md
Labels: page edit, decision, translation

#8329 rpm-ostree: add Tamil translation
  pages.ta/linux/rpm-ostree.md
Labels: translation

#8336 cargo: add Tamil translation
  pages.ta/common/cargo.md
Labels: translation

#8337 android/*: add Tamil translation
  pages.ta/android/am.md
  pages.ta/android/bugreport.md
  pages.ta/android/bugreportz.md
  pages.ta/android/cmd.md
  pages.ta/android/dalvikvm.md
  pages.ta/android/dumpsys.md
  pages.ta/android/getprop.md
  pages.ta/android/input.md
  pages.ta/android/logcat.md
  pages.ta/android/pkg.md
  pages.ta/android/pm.md
  pages.ta/android/settings.md
  pages.ta/android/wm.md
Labels: mass changes, translation

#8338 toolbox*: add Tamil translation
  pages.ta/linux/toolbox-create.md
  pages.ta/linux/toolbox-enter.md
  pages.ta/linux/toolbox-help.md
  pages.ta/linux/toolbox-init-container.md
  pages.ta/linux/toolbox-list.md
  pages.ta/linux/toolbox-rm.md
  pages.ta/linux/toolbox-rmi.md
  pages.ta/linux/toolbox-run.md
  pages.ta/linux/toolbox.md
Labels: translation

#8340 perl: fix -i option description
  pages/common/perl.md
Labels: page edit

#8343 toolbox: Reorder commands in page
  pages.ta/linux/toolbox.md
  pages/linux/toolbox.md
Labels: page edit, translation

#8341 addr2line: add pt_BR translation
  pages.pt_BR/linux/addr2line.md
Labels: translation

#8339 avrdude, axel: add French translation
  pages.fr/common/avrdude.md
  pages.fr/common/axel.md
Labels: translation

#8298 chmod: add Indonesian translation
  pages.id/common/chmod.md
Labels: translation, review needed

#8332 feh: add Spanish translation
  pages.es/common/feh.md
Labels: translation

#8323 inotifywait: refresh
  pages/linux/inotifywait.md
Labels: page edit

#8350 cd: update page
  pages/windows/cd.md
Labels: page edit

#8346 avrdude: edit French translation
  pages.fr/common/avrdude.md
Labels: translation

#8347 aws-cur, aws-ec2, aws-ecr: add French translation
  pages.fr/common/aws-cur.md
  pages.fr/common/aws-ec2.md
  pages.fr/common/aws-ecr.md
Labels: translation

#8348 todo,todoist,todoman: add Tamil translation
  pages.ta/common/todo.md
  pages.ta/common/todoist.md
  pages.ta/common/todoman.md
Labels: translation

#8352 retroarch: add page
  pages/linux/retroarch.md
Labels: new command

#8357 git-config: add --show-origin example
  pages/common/git-config.md
Labels: page edit

#8355 aws-ec2: Reorder commands in page
  pages.de/common/aws-ec2.md
  pages.fr/common/aws-ec2.md
  pages.pt_BR/common/aws-ec2.md
  pages/common/aws-ec2.md
Labels: page edit, translation

#8358 find: add Chinese translation
  pages.zh/common/find.md
Labels: translation

#8356 adduser: update Chinese translation
  pages.zh/linux/adduser.md
Labels: translation

#8361 aws-glue, aws-google-auth: add French translation
  pages.fr/common/aws-glue.md
  pages.fr/common/aws-google-auth.md
Labels: translation

#8360 ls: add Chinese translation
  pages.zh/common/ls.md
Labels: translation

#8362 MAINTAINERS: add @adrienthebo to collaborators
  MAINTAINERS.md
Labels: community

#8363 gedit: add Tamil translation
  pages.ta/linux/gedit.md
Labels: translation

#7980 bash: refresh page
  pages/common/bash.md
Labels: page edit, stalebot ignore

#8369 aws-help, aws-iam: add French translation
  pages.fr/common/aws-help.md
  pages.fr/common/aws-iam.md
Labels: translation

#8368 brew: fix simplified Chinese translation
  pages.zh/common/brew.md
Labels: translation

#8372 pbcopy: update page
  pages/osx/pbcopy.md
Labels: page edit, minor change

#8365 pwd: refresh page
  pages/common/pwd.md
Labels: page edit

#8371 fdisk, fwupdmgr: add Tamil translation
  pages.ta/linux/fdisk.md
  pages.ta/linux/fwupdmgr.md
Labels: translation

#8374 aws-kinesis, aws-lambda: add French translation
  pages.fr/common/aws-kinesis.md
  pages.fr/common/aws-lambda.md
Labels: translation

#8376 alien: add pt_BR translation
  pages.pt_BR/linux/alien.md
Labels: translation

#8375 cd: update Chinese translation
  pages.zh/common/cd.md
Labels: translation

#8384 pnpm: refresh page
  pages/common/pnpm.md
Labels: page edit

#8385 unzstd: add page
  pages/common/unzstd.md
Labels: new command

#8383 vgrep: add page
  pages/common/vgrep.md
Labels: new command

#8351 choice: update page
  pages/windows/choice.md
Labels: page edit, new command

#8345 flarectl: add page
  pages/common/flarectl.md
Labels: new command

#8381 gcc: mention -c compiles into object file
  pages/common/gcc.md
Labels: page edit

#8387 gcc: use short -o option for output
  pages/common/gcc.md
Labels: page edit

#8349 assoc, attrib: update page
  pages/windows/assoc.md
  pages/windows/attrib.md
Labels: page edit

#8394 vue: update Chinese translation
  pages.zh/common/vue.md
Labels: translation

#8393 uname: update Chinese translation
  pages.zh/osx/uname.md
Labels: translation

#8390 daemon: add page
  pages/linux/daemon.md
Labels: new command

#8366 CONTRIBUTING: add notes about placeholders and some examples
  CONTRIBUTING.md
Labels: documentation

#8392 silicon: add page
  pages/common/silicon.md
Labels: new command

#8391 jmeter: add page
  pages/common/jmeter.md
Labels: new command

#8397 style-guide: fix typo ' -> `
  contributing-guides/style-guide.md
Labels: documentation

#8396 pip, pip-install, pip-uninstall, touch: add pt_BR translation
  pages.pt_BR/common/pip-install.md
  pages.pt_BR/common/pip-uninstall.md
  pages.pt_BR/common/pip.md
  pages.pt_BR/common/touch.md
Labels: translation

#8377 distrobox-*: add Tamil translation
  pages.ta/linux/distrobox-create.md
  pages.ta/linux/distrobox-enter.md
  pages.ta/linux/distrobox-list.md
  pages.ta/linux/distrobox-rm.md
Labels: translation

#8400 nextclade: add page
  pages/common/nextclade.md
Labels: new command

#8402 objdump: add intel syntax command
  pages/common/objdump.md
Labels: page edit

#8404 gifdiff: add page
  pages/common/gifdiff.md
Labels: new command

#8420 contributing(doc): fix typo 'simpliest' -> 'simplest'
  CONTRIBUTING.md
Labels: documentation

#8415 ascii, asciiart: add Tamil translation
  pages.ta/linux/ascii.md
  pages.ta/linux/asciiart.md
Labels: translation

#8412 catimg: add page
  pages/common/catimg.md
Labels: new command

#8419 zless: mention supported compression types
  pages/common/zless.md
Labels: page edit

#8421 mpv: use path/to/file placeholder
  pages/common/mpv.md
Labels: page edit, minor change

#8407 csv2tsv: add page
  pages/common/csv2tsv.md
Labels: new command

#8413 chafa: add page
  pages/common/chafa.md
Labels: new command

#8422 anbox: add Tamil translation
  pages.ta/linux/anbox.md
Labels: translation

#8418 zstdless: add page
  pages/common/zstdless.md
Labels: new command

#8403 gifsicle: update page
  pages/common/gifsicle.md
Labels: page edit, review needed
