Repository tldr-pages/tldr, pull requests merged in 2022-10, with the labels that each got.

#8555 az-upgrade: add page
  pages/common/az-upgrade.md
Labels: new command, hacktoberfest, hacktoberfest-accepted, review needed

#8554 ahost: add page
  pages/linux/ahost.md
Labels: new command, hacktoberfest, hacktoberfest-accepted

#8561 htop: add Indonesian translation
  pages.id/common/htop.md
Labels: translation, hacktoberfest

#8570 adb-logcat, atuin: add French translation
  pages.fr/common/adb-logcat.md
  pages.fr/common/atuin.md
Labels: translation, hacktoberfest

#8551 curlie: add page
  pages/linux/curlie.md
Labels: new command, hacktoberfest

#8549 qrcp: add page
  pages/linux/qrcp.md
Labels: new command, hacktoberfest-accepted, review needed

#8545 adb-logcat: add Chinese translation
  pages.zh/common/adb-logcat.md
Labels: translation

#8556 clear: update Hindi translation
  pages.hi/common/clear.md
Labels: translation, hacktoberfest

#8558 pint: add page
  pages/common/pint.md
Labels: new command, hacktoberfest

#8568 cls: add Thai translation
  pages.th/windows/cls.md
Labels: translation, hacktoberfest

#8575 babel, balena: add French translation
  pages.fr/common/babel.md
  pages.fr/common/balena.md
Labels: translation, hacktoberfest

#8567 fio: add job file example
  pages/common/fio.md
Labels: page edit, hacktoberfest, hacktoberfest-accepted

#8563 podman: add Tamil translation
  pages.ta/common/podman.md
Labels: translation, hacktoberfest

#8579 cat: update placeholders
  pages/common/cat.md
Labels: page edit, hacktoberfest-accepted, minor change

#8587 b2sum: add French translation
  pages.fr/common/b2sum.md
Labels: translation

#8600 chsh: add French translation
  pages.fr/common/chsh.md
Labels: translation

#8589 bc: add French translation
  pages.fr/common/bc.md
Labels: translation

#8598 chroot: add French translation
  pages.fr/common/chroot.md
Labels: translation

#8569 aria2c: Add Indonesian translation
  pages.id/common/aria2c.md
Labels: translation, hacktoberfest, review needed

#8604 size: add page
  pages/linux/size.md
Labels: new command

#8601 pnpm: add Indonesian translation
  pages.id/common/pnpm.md
Labels: translation

#8596 view: fix typo in Hindi translation
  pages.hi/common/view.md
Labels: translation, minor change

#8559 soupault: add page
  pages/common/soupault.md
Labels: new command, hacktoberfest

#8538 qm-stop: add page
  pages/common/qm-stop.md
Labels: new command

#8603 az sshkey: add page
  pages/common/az-sshkey.md
Labels: new command

#8605 timedatectl: Add command to set hardware clock to use localtime
  pages/linux/timedatectl.md
Labels: page edit, minor change

#8595 chgrp: add French translation
  pages.fr/common/chgrp.md
Labels: translation

#8611 acountry: add page
  pages/linux/acountry.md
Labels: new command

#8616 gpgconf: add page
  pages/common/gpgconf.md
Labels: new command

#8590 projucer: add page
  pages/common/projucer.md
Labels: new command

#8566 pages.zh_TW/*: fix wrong term
  contributing-guides/translation-templates/alias-pages.md
  pages.zh_TW/common/clang-cpp.md
  pages.zh_TW/common/clojure.md
  pages.zh_TW/common/cola.md
  pages.zh_TW/common/llvm-ar.md
  pages.zh_TW/common/llvm-g++.md
  pages.zh_TW/common/llvm-gcc.md
  pages.zh_TW/common/llvm-nm.md
  pages.zh_TW/common/llvm-objdump.md
  pages.zh_TW/common/llvm-strings.md
  pages.zh_TW/common/mscore.md
  pages.zh_TW/common/pio-init.md
  pages.zh_TW/common/piodebuggdb.md
  pages.zh_TW/common/platformio.md
  pages.zh_TW/common/r2.md
  pages.zh_TW/common/tldrl.md
  pages.zh_TW/common/tlmgr-arch.md
  pages.zh_TW/common/vi.md
  pages.zh_TW/linux/ncal.md
  pages.zh_TW/windows/cinst.md
  pages.zh_TW/windows/clist.md
  pages.zh_TW/windows/cuninst.md
Labels: documentation, translation

#8577 php-cs-fixer: add page
  pages/common/php-cs-fixer.md
Labels: new command

#8612 ruget: add Hindi translation
  pages.hi/common/ruget.md
Labels: translation

#8552 rpi-imager: add page
  pages/common/rpi-imager.md
Labels: new command, hacktoberfest

#8614 ci: upgrade actions/setup-python to v4
  .github/workflows/ci.yml
Labels: tooling, hacktoberfest-accepted

#8583 [[: add German translation
  pages.de/common/[[.md
Labels: translation

#8580 cls: fix thai translation typo
  pages.th/windows/cls.md
Labels: translation, minor change

#8573 adb-install, cd: update French translation
  pages.fr/common/adb-install.md
  pages.fr/common/cd.md
Labels: translation, hacktoberfest

#8617 git-checkout*: add Ukrainian translation
  pages.uk/common/git-checkout-index.md
  pages.uk/common/git-checkout.md
Labels: translation

#8602 adig: add page
  pages/linux/adig.md
Labels: new command

#8586 yarn: add German translation
  pages.de/common/yarn.md
Labels: translation

#8564 protontricks: add Tamil translation
  pages.ta/linux/protontricks.md
Labels: translation, hacktoberfest

#8553 git-delete-submodule: add page
  pages/common/git-delete-submodule.md
Labels: new command, hacktoberfest

#8565 ruget: add Tamil translation
  pages.ta/linux/ruget.md
Labels: translation, hacktoberfest

#8607 cd: update Tamil translation
  pages.ta/common/cd.md
Labels: translation, minor change

#8597 brittany: add page
  pages/common/brittany.md
Labels: new command

#8630 azurite: add page
  pages/common/azurite.md
Labels: new command

#8608 htop: add Tamil translation
  pages.ta/common/htop.md
Labels: translation

#8578 getcap: add page
  pages/linux/getcap.md
Labels: new command, hacktoberfest

#8416 join: add stdin example
  pages/common/join.md
Labels: page edit

#8629 backupd, corebrightnessd, fontd, translationd, warmd: add page
  pages/osx/backupd.md
  pages/osx/corebrightnessd.md
  pages/osx/fontd.md
  pages/osx/translationd.md
  pages/osx/warmd.md
Labels: new command

#8474 pacdiff: add page
  pages/linux/pacdiff.md
Labels: new command

#8638 rmdir: add Hindi translation
  pages.hi/common/rmdir.md
Labels: translation

#8649 zypper: add pt_BR translation
  pages.pt_BR/linux/zypper.md
Labels: translation

#8562 man: add Tamil translation
  pages.ta/common/man.md
Labels: translation, hacktoberfest

#8626 df: add traditional Chinese translation
  pages.zh_TW/common/df.md
Labels: translation, hacktoberfest

#8657 btrfs-subvolume: add pt_BR translation
  pages.pt_BR/linux/btrfs-subvolume.md
Labels: translation

#8615 stale.yml: upgrade actions/stale to v6
  .github/workflows/stale.yml
Labels: tooling

#8585 pages.th/*: fix more information label
  pages.th/common/mscore.md
  pages.th/common/platformio.md
  pages.th/common/tldr.md
  pages.th/common/tldrl.md
  pages.th/common/tlmgr-arch.md
  pages.th/linux/ncal.md
  pages.th/windows/cinst.md
  pages.th/windows/clist.md
  pages.th/windows/cuninst.md
  scripts/set-more-info-link.py
Labels: page edit, tooling, translation

#8645 snapper: add pt_BR translation
  pages.pt_BR/linux/snapper.md
Labels: translation

#8662 btrfs: add pt_BR translation
  pages.pt_BR/linux/btrfs.md
Labels: translation

#8639 arch: add Hindi translation
  pages.hi/common/arch.md
Labels: translation

#8642 fuck: add Hindi translation
  pages.hi/common/fuck.md
Labels: translation

#8663 common-arguments: add Ukrainian translation
  contributing-guides/translation-templates/common-arguments.md
Labels: documentation

#8637 znew: add page
  pages/common/znew.md
Labels: new command

#8641 compare: add Hindi translation
  pages.hi/common/compare.md
Labels: translation

#8640 sleep: add Hindi translation
  pages.hi/common/sleep.md
Labels: translation

#8644 mosquitto: add pt_BR translation
  pages.pt_BR/common/mosquitto.md
Labels: translation

#8646 paru: add pt_BR translation
  pages.pt_BR/linux/paru.md
Labels: translation

#8666 CONTRIBUTING: fix typo caja to tar
  CONTRIBUTING.md
Labels: documentation, minor change

#8631 aws, aws-quicksight: add French translation
  pages.fr/common/aws-quicksight.md
  pages.fr/common/aws.md
Labels: translation

#8628 dotnet: add traditional Chinese translation
  pages.zh_TW/common/dotnet.md
Labels: translation, hacktoberfest

#8625 az: add traditional Chinese translation
  pages.zh_TW/common/az.md
Labels: translation, hacktoberfest

#8544 set: add traditional Chinese translation
  pages.zh_TW/windows/set.md
Labels: translation

#8574 halt, poweroff, reboot: add Indonesian translation
  pages.id/linux/halt.md
  pages.id/linux/poweroff.md
  pages.id/linux/reboot.md
Labels: translation

#8591 bundle, bundler: add French translation
  pages.fr/common/bundle.md
  pages.fr/common/bundler.md
  pages/common/bundler.md
Labels: page edit, translation

#8634 aws-rds, aws-s3: add French translation
  pages.fr/common/aws-rds.md
  pages.fr/common/aws-s3.md
Labels: translation

#8572 autoconf, az: add French translation
  pages.fr/common/autoconf.md
  pages.fr/common/az.md
Labels: translation, hacktoberfest

#8665 logcat: improve command description
  pages.es/android/logcat.md
  pages/android/logcat.md
Labels: page edit, translation

#8618 mdadm: add sudo, add --zero-superblock example
  pages/linux/mdadm.md
Labels: page edit

#8675 kool: add page
  pages/common/kool.md
Labels: new command, hacktoberfest-accepted

#8613 ddev: add page
  pages/common/ddev.md
Labels: new command

#8571 ruget: add Indonesian translation
  pages.id/linux/ruget.md
Labels: translation, hacktoberfest

#8661 git-remote: add get-url example
  pages/common/git-remote.md
Labels: page edit

#8677 fossil*: move all fossil commands to common vs linux
  pages.ca/common/fossil-ci.md
  pages.es/common/fossil-ci.md
  pages/common/fossil-add.md
  pages/common/fossil-ci.md
  pages/common/fossil-commit.md
  pages/common/fossil-delete.md
  pages/common/fossil-forget.md
  pages/common/fossil-rm.md
  pages/common/fossil.md
Labels: page edit, translation, hacktoberfest-accepted, minor change

#8679 qm-nbdstop: add page
  pages/common/qm-nbdstop.md
Labels: new command

#8672 docker-load: add page
  pages/common/docker-load.md
Labels: new command, hacktoberfest-accepted

#8670 autofsd, biomesyncd, biometrickitd, cloudd, coredatad, ctkd, deleted, InternetSharing, dhcp6d, hidd, systemsoundserverd, wps, webinspectord, watchdogd, watchlistd, symptomsd: add page
  pages/osx/autofsd.md
  pages/osx/biomesyncd.md
  pages/osx/biometrickitd.md
  pages/osx/cloudd.md
  pages/osx/coredatad.md
  pages/osx/ctkd.md
  pages/osx/deleted.md
  pages/osx/dhcp6d.md
  pages/osx/hidd.md
  pages/osx/internetsharing.md
  pages/osx/symptomsd.md
  pages/osx/systemsoundserverd.md
  pages/osx/watchdogd.md
  pages/osx/watchlistd.md
  pages/osx/webinspectord.md
  pages/osx/wps.md
Labels: new command, mass changes

#8647 gcc, g++: Clarify -Wall
  pages/common/g++.md
  pages/common/gcc.md
Labels: page edit, minor change

#8550 fastfetch: add page
  pages/linux/fastfetch.md
Labels: new command, hacktoberfest

#8658 git-pull: add Indonesian translation
  pages.id/common/git-pull.md
Labels: translation, hacktoberfest-accepted

#8690 android/*: use imperative mood on Indonesian translation
  pages.id/android/am.md
  pages.id/android/bugreport.md
  pages.id/android/bugreportz.md
  pages.id/android/cmd.md
  pages.id/android/dalvikvm.md
  pages.id/android/dumpsys.md
  pages.id/android/getprop.md
  pages.id/android/input.md
  pages.id/android/logcat.md
  pages.id/android/pkg.md
  pages.id/android/pm.md
  pages.id/android/settings.md
  pages.id/android/wm.md
Labels: translation

#8691 getcap: add -r example
  pages/linux/getcap.md
Labels: page edit

#8674 just-js: add page
  pages/linux/just-js.md
Labels: new command

#8681 brightnessctl: add Malayalam translation
  pages.ml/linux/brightnessctl.md
Labels: translation

#8687 date: add Polish translation
  pages.pl/osx/date.md
Labels: translation

#8654 battop: add page
  pages/linux/battop.md
Labels: new command

#8636 zdiff: add page
  pages/common/zdiff.md
Labels: new command

#8650 git-branch: update Indonesian translation
  pages.id/common/git-branch.md
Labels: translation

#8542 warpd: add page
  pages/linux/warpd.md
Labels: new command

#8541 plocate: add page
  pages/common/plocate.md
Labels: new command

#8698 az group: add page
  pages/common/az-group.md
Labels: new command

#8682 logoff: add traditional Chinese translation
  pages.zh_TW/windows/logoff.md
Labels: translation

#8655 gh-pr: mention subcommand pages in command description
  pages/common/gh-pr.md
Labels: page edit, hacktoberfest-accepted, minor change

#8673 gh-label: add page
  pages/common/gh-label.md
Labels: new command, hacktoberfest-accepted

#8709 bzegrep, bzfgrep, rgrep, zegrep, zgrep: move from linux to common
  pages/common/bzegrep.md
  pages/common/bzfgrep.md
  pages/common/rgrep.md
  pages/common/zegrep.md
  pages/common/zgrep.md
Labels: page edit

#8707 dnstracer: add page
  pages/linux/dnstracer.md
Labels: new command

#8031 dconf*: add/refresh pages
  pages/linux/dconf-read.md
  pages/linux/dconf-reset.md
  pages/linux/dconf-write.md
  pages/linux/dconf.md
Labels: page edit, new command, stalebot ignore, review needed

#8712 cd: update Chinese translation
  pages.zh/common/cd.md
Labels: translation, minor change

#8683 type: add traditional Chinese translation
  pages.zh_TW/windows/type.md
Labels: translation

#8684 whoami, ver: add traditional Chinese translation
  pages.zh_TW/windows/ver.md
  pages.zh_TW/windows/whoami.md
Labels: translation

#8599 zcmp: add page
  pages/common/zcmp.md
Labels: new command

#8706 dnsmap: add page
  pages/linux/dnsmap.md
Labels: new command

#8594 test: update condition example description
  pages/common/test.md
Labels: page edit, minor change

#8716 java: update Indonesian translation
  pages.id/common/java.md
Labels: translation

#8686 ipconfig, more, path, title: add traditional Chinese translation
  pages.zh_TW/windows/ipconfig.md
  pages.zh_TW/windows/more.md
  pages.zh_TW/windows/path.md
  pages.zh_TW/windows/title.md
Labels: translation

#8533 smalltalkci: remove superfluous space
  pages/common/smalltalkci.md
Labels: page edit

#8704 qm-start: add page
  pages/linux/qm-start.md
Labels: new command

#8693 [: update German translation
  pages.de/common/[.md
Labels: translation, minor change

#8710 fossil-init: add page
  pages/common/fossil-init.md
  pages/common/fossil-new.md
Labels: new command

#8708 zfgrep: add page
  pages/common/zfgrep.md
Labels: new command

#8699 zathura: add pt_BR translation
  pages.pt_BR/linux/zathura.md
Labels: translation

#8643 htop: update pt_BR translation
  pages.pt_BR/common/htop.md
Labels: translation

#7836 bat: refresh pt_BR translation
  pages.pt_BR/common/bat.md
Labels: translation

#8731 fastfetch: move to common
  pages/common/fastfetch.md
Labels: page edit, minor change

#8452 smartctl, e2fsck: improve disk checking commands
  pages/common/smartctl.md
  pages/linux/e2fsck.md
Labels: page edit

#8733 snakefmt: add page
  pages/common/snakefmt.md
Labels: new command

#8450 transmission: add page
  pages/common/transmission.md
Labels: new command

#8696 pipx: update page
  pages/common/pipx.md
Labels: page edit

#8737 az-storage-account: add page
  pages/common/az-storage-account.md
Labels: new command

#8651 az-redis: add page
  pages/common/az-redis.md
Labels: new command

#8751 bugreport: add Italian translation
  pages.it/android/bugreport.md
Labels: translation

#8548 links: add page
  pages/linux/links.md
Labels: new command, hacktoberfest

#8582 deno, flutter: add German translation
  pages.de/common/deno.md
  pages.de/common/flutter.md
Labels: translation

#8584 flatpak: replace remote-list with remove example
  pages/linux/flatpak.md
Labels: page edit

#8774 arp: add Turkish translation
  pages.tr/common/arp.md
Labels: translation

#8772 mkdir: add Turkish translation
  pages.tr/common/mkdir.md
Labels: translation

#8771 yes: improve Turkish translation
  pages.tr/common/yes.md
Labels: translation

#8766 helm: add Italian translation
  pages.it/common/helm.md
Labels: translation

#8743 sunos/*: add Dutch translation
  pages.nl/sunos/devfsadm.md
  pages.nl/sunos/dmesg.md
  pages.nl/sunos/prctl.md
  pages.nl/sunos/prstat.md
  pages.nl/sunos/snoop.md
  pages.nl/sunos/svcadm.md
  pages.nl/sunos/svccfg.md
  pages.nl/sunos/svcs.md
  pages.nl/sunos/truss.md
Labels: translation

#8769 caffeine: add page
  pages/linux/caffeine.md
Labels: new command

#8761 fastmod, gnmic-subscribe, renice, s3cmd, virt-install, toolbox-init-container: fix typo
  pages/common/fastmod.md
  pages/common/gnmic-subscribe.md
  pages/common/renice.md
  pages/common/s3cmd.md
  pages/common/virt-install.md
  pages/linux/toolbox-init-container.md
Labels: page edit

#8695 kmutil: add page
  pages/osx/kmutil.md
Labels: new command

#8760 pnpm: add German translation
  pages.de/common/pnpm.md
Labels: translation

#8777 agate: add Chinese translation
  pages.zh/common/agate.md
Labels: translation

#8719 find: add maxdepth in example
  pages/common/find.md
Labels: page edit

#8632 as, ark, gh, gh-alias, gcc, cal: add French translation
  pages.fr/common/gcc.md
  pages.fr/common/gh-alias.md
  pages.fr/common/gh.md
  pages.fr/linux/ark.md
  pages.fr/linux/as.md
  pages.fr/linux/cal.md
Labels: translation

#8748 cp: add pt_BR translation
  pages.pt_BR/common/cp.md
Labels: translation

#8739 7z: update pt_BR translation
  pages.pt_BR/common/7z.md
Labels: translation

#8755 pkg: add Italian translation
  pages.it/android/pkg.md
Labels: translation
