Repository tldr-pages/tldr, pull requests merged in 2023-09, with the labels that each got.

#10641 ropper: add page
  pages/common/ropper.md
Labels: new command

#10640 ROPgadget: add page
  pages/common/ropgadget.md
Labels: new command

#10654 uwfmgr: add page
  pages/windows/uwfmgr.md
Labels: new command

#10642 rustup: update page, rustup-{show,update,check,default,toolchain,target}: add page
  pages/common/rustup-check.md
  pages/common/rustup-default.md
  pages/common/rustup-show.md
  pages/common/rustup-target.md
  pages/common/rustup-toolchain.md
  pages/common/rustup-update.md
  pages/common/rustup.md
Labels: page edit, new command

#10656 systemd-tty-ask-password-agent: add page
  pages/linux/systemd-tty-ask-password-agent.md
Labels: new command

#10664 liquidctl: add page
  pages/common/liquidctl.md
Labels: new command

#10671 sf: rename command from sfdx
  pages/common/sf.md
  pages/common/sfdx.md
Labels: page edit, new command, minor change

#10660 cs, git, nix: remove "accessible via `tldr command subcommand`"
  pages/common/cs.md
  pages/common/git.md
  pages/common/nix.md
Labels: page edit, minor change

#10659 stressapptest: add page
  pages/common/stressapptest.md
Labels: new command

#10669 CI: bump actions/checkout to v4
  .github/workflows/ci.yml
  .github/workflows/codespell.yml
Labels: tooling

#10648 lima, limactl: add page
  pages/common/lima.md
  pages/common/limactl.md
Labels: new command

#10686 MAINTAINERS: add @Managor as collaborator
  MAINTAINERS.md
Labels: community

#10670 systemd-tmpfiles: add page
  pages/linux/systemd-tmpfiles.md
Labels: new command

#10683 zstd, unzstd: update page; zstd{cat,mt}: add alias page
  pages/common/unzstd.md
  pages/common/zstd.md
  pages/common/zstdcat.md
  pages/common/zstdmt.md
Labels: page edit, new command

#10687 ab: update Korean translation
  pages.ko/common/ab.md
Labels: translation

#10688 MAINTAINERS: remove @schneiderl from Organization Owners
  MAINTAINERS.md
Labels: community

#10691 atom: update Korean translation
  pages.ko/common/atom.md
Labels: translation

#10662 userdbctl: add page
  pages/linux/userdbctl.md
Labels: new command

#10666 abroot: update page
  pages/linux/abroot.md
Labels: page edit

#10667 ikaros: add page; vso: update page
  pages/linux/ikaros.md
  pages/linux/vso.md
Labels: page edit, new command

#10701 htop: add `--delay` example
  pages/common/htop.md
Labels: page edit

#10594 pages/*: add `< >` around links in example descriptions
  pages.es/common/apm.md
  pages.fr/common/apm.md
  pages.id/common/hugo.md
  pages.it/common/apm.md
  pages.it/common/calibre-server.md
  pages.it/common/elm.md
  pages.ko/common/calibre-server.md
  pages.pt_BR/common/apm.md
  pages.ta/common/jekyll.md
  pages.tr/common/gitsome.md
  pages.zh/common/apm.md
  pages.zh/common/etcd.md
  pages/common/apm.md
  pages/common/calibre-server.md
  pages/common/elm.md
  pages/common/etcd.md
  pages/common/gh-auth.md
  pages/common/gitsome.md
  pages/common/hugo.md
  pages/common/jhipster.md
  pages/common/linkchecker.md
  pages/common/wpscan.md
  pages/linux/gbp.md
  pages/linux/http-prompt.md
  pages/linux/mdbook.md
  pages/linux/pinout.md
Labels: page edit, mass changes, translation, review needed

#10296 7z, 7za, 7zr, aapt: add pt_PT translations
  contributing-guides/translation-templates/common-arguments.md
  pages.pt_PT/common/7z.md
  pages.pt_PT/common/7za.md
  pages.pt_PT/common/7zr.md
  pages.pt_PT/common/aapt.md
Labels: documentation, translation

#10148 CLIENT-SPECIFICATION (2.0): document removal of master branch, addition of support for individual translation archives
  CLIENT-SPECIFICATION.md
Labels: documentation, clients

#10702 csh: add French translation
  pages.fr/common/csh.md
Labels: translation

#10693 systemd-sysusers: add page
  pages/linux/systemd-sysusers.md
Labels: new command

#10711 l2ping: add page
  pages/common/l2ping.md
Labels: new command

#10708 htop: add missing placeholder
  pages/common/htop.md
Labels: page edit, minor change

#10712 cargo-{help,version}: add page
  pages/common/cargo-help.md
  pages/common/cargo-version.md
Labels: new command

#10713 iptables: update page
  pages/linux/iptables.md
Labels: page edit

#10714 eza: add page
  pages/common/eza.md
Labels: new command

#10707 CI/codespell: remove changed-files action, use point release of action
  .github/workflows/codespell.yml
Labels: tooling

#10717 op: add page
  pages/common/op.md
Labels: new command

#10514 mdfind: add Spanish translation
  pages.es/osx/mdfind.md
Labels: translation

#10515 nettop: add Spanish translation
  pages.es/osx/nettop.md
Labels: translation

#10516 lex: add Spanish translation
  pages.es/osx/lex.md
Labels: translation

#10603 2to3, 7za, 7zr, [, [[, android/*: add Farsi Translation; 7z: update Farsi Translation
  pages.fa/android/am.md
  pages.fa/android/bugreport.md
  pages.fa/android/bugreportz.md
  pages.fa/android/cmd.md
  pages.fa/android/dalvikvm.md
  pages.fa/android/dumpsys.md
  pages.fa/android/getprop.md
  pages.fa/android/input.md
  pages.fa/android/logcat.md
  pages.fa/android/pkg.md
  pages.fa/android/pm.md
  pages.fa/android/screencap.md
  pages.fa/android/settings.md
  pages.fa/android/wm.md
  pages.fa/common/2to3.md
  pages.fa/common/7z.md
  pages.fa/common/7za.md
  pages.fa/common/7zr.md
  pages.fa/common/[.md
  pages.fa/common/[[.md
Labels: translation

#10663 !: edit page
  pages/linux/!.md
Labels: page edit

#10720 !: move to common
  pages/common/!.md
Labels: page edit, minor change

#10703 alias-pages: add `:` to Farsi translation
  contributing-guides/translation-templates/alias-pages.md
Labels: documentation, minor change

#10673 act: update Korean translation
  pages.ko/common/act.md
Labels: translation

#10684 bzip2: update Korean translation
  pages.ko/common/bzip2.md
Labels: translation

#10718 xcodes, xcodes-runtimes: add page
  pages/osx/xcodes-runtimes.md
  pages/osx/xcodes.md
Labels: new command

#10727 stylua: add page
  pages/common/stylua.md
Labels: new command

#10724 systemd-sysext: add page
  pages/linux/systemd-sysext.md
Labels: new command

#10725 bun: add page
  pages/common/bun.md
Labels: new command

#10661 rustup-{install,run,which,help,man}: add page
  pages/common/rustup-help.md
  pages/common/rustup-install.md
  pages/common/rustup-man.md
  pages/common/rustup-run.md
  pages/common/rustup-which.md
Labels: new command, review needed

#10723 systemd-detect-virt: add page
  pages/linux/systemd-detect-virt.md
Labels: new command

#10715 iptables: update page; ip6tables, ip{6,}tables-{restore,save}: add page
  pages/linux/ip6tables-restore.md
  pages/linux/ip6tables-save.md
  pages/linux/ip6tables.md
  pages/linux/iptables-restore.md
  pages/linux/iptables-save.md
  pages/linux/iptables.md
Labels: page edit, new command

#10504 podman, podman-*: add pt_BR translation
  pages.pt_BR/common/podman-build.md
  pages.pt_BR/common/podman-compose.md
  pages.pt_BR/common/podman-image.md
  pages.pt_BR/common/podman-images.md
  pages.pt_BR/common/podman-machine.md
  pages.pt_BR/common/podman-ps.md
  pages.pt_BR/common/podman-rmi.md
  pages.pt_BR/common/podman-run.md
  pages.pt_BR/common/podman.md
Labels: mass changes, translation

#10505 virsh, virsh-*: add pt_BR translation
  pages.pt_BR/common/virsh-connect.md
  pages.pt_BR/common/virsh-domblklist.md
  pages.pt_BR/common/virsh-help.md
  pages.pt_BR/common/virsh-list.md
  pages.pt_BR/common/virsh-pool-autostart.md
  pages.pt_BR/common/virsh-pool-build.md
  pages.pt_BR/common/virsh-pool-define-as.md
  pages.pt_BR/common/virsh-pool-delete.md
  pages.pt_BR/common/virsh-pool-destroy.md
  pages.pt_BR/common/virsh-pool-info.md
  pages.pt_BR/common/virsh-pool-list.md
  pages.pt_BR/common/virsh-pool-start.md
  pages.pt_BR/common/virsh-pool-undefine.md
  pages.pt_BR/common/virsh-undefine.md
  pages.pt_BR/common/virsh.md
Labels: mass changes, translation

#10506 ssh*, autossh, pssh: add pt_BR translation
  pages.pt_BR/common/autossh.md
  pages.pt_BR/common/pssh.md
  pages.pt_BR/common/ssh-add.md
  pages.pt_BR/common/ssh-agent.md
  pages.pt_BR/common/ssh-copy-id.md
  pages.pt_BR/common/ssh-keygen.md
  pages.pt_BR/common/ssh-keyscan.md
  pages.pt_BR/common/ssh.md
  pages.pt_BR/common/sshd.md
  pages.pt_BR/common/sshfs.md
  pages.pt_BR/common/sshpass.md
Labels: mass changes, translation

#10706 socat: update page
  pages/common/socat.md
Labels: page edit

#10507 docker*, x11docker, kdocker: add pt_BR translation
  pages.pt_BR/common/docker-commit.md
  pages.pt_BR/common/docker-container.md
  pages.pt_BR/common/docker-exec.md
  pages.pt_BR/common/docker-image.md
  pages.pt_BR/common/docker-inspect.md
  pages.pt_BR/common/docker-load.md
  pages.pt_BR/common/docker-login.md
  pages.pt_BR/common/docker-machine.md
  pages.pt_BR/common/docker-network.md
  pages.pt_BR/common/docker-pull.md
  pages.pt_BR/common/docker-save.md
  pages.pt_BR/common/docker-secret.md
  pages.pt_BR/common/docker-service.md
  pages.pt_BR/common/docker-slim.md
  pages.pt_BR/common/docker-swarm.md
  pages.pt_BR/common/docker-system.md
  pages.pt_BR/common/docker-tag.md
  pages.pt_BR/common/docker-update.md
  pages.pt_BR/common/docker-volume.md
  pages.pt_BR/common/x11docker.md
  pages.pt_BR/linux/dockerd.md
  pages.pt_BR/linux/kdocker.md
Labels: mass changes, translation

#10605 xbps-install: add Russian translation
  pages.ru/linux/xbps-install.md
Labels: translation

#10635 dracut, lsinitrd: add page
  pages/linux/dracut.md
  pages/linux/lsinitrd.md
Labels: new command, review needed

#10631 bc: add Japanese translation
  pages.ja/common/bc.md
Labels: translation

#10665 apx: update page; apx-{pkgmanagers,stacks,subsystems}: add page
  pages/linux/apx-pkgmanagers.md
  pages/linux/apx-stacks.md
  pages/linux/apx-subsystems.md
  pages/linux/apx.md
Labels: page edit, new command, review needed

#10685 date: update Korean translation
  pages.ko/common/date.md
Labels: translation

#10690 ant: add Korean translation
  pages.ko/common/ant.md
Labels: translation

#10695 bugreport: add Korean translation
  pages.ko/android/bugreport.md
Labels: translation

#10694 am: add Korean translation
  pages.ko/android/am.md
Labels: translation

#10696 ac: add Korean translation
  pages.ko/common/ac.md
Labels: translation

#10697 aws-backup: add Korean translation
  pages.ko/common/aws-backup.md
Labels: translation

#10735 resolvectl: add cache flushing and statistics, remove openpgp
  pages/linux/resolvectl.md
Labels: page edit

#10739 MAINTAINERS: add @isaacvicente as collaborator
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: community

#10742 cargo: update page; cargo-{init,new}: add page
  pages/common/cargo-init.md
  pages/common/cargo-new.md
  pages/common/cargo.md
Labels: page edit, new command

#10740 devcontainer: add page
  pages/common/devcontainer.md
Labels: new command

#10745 cargo-update: add page
  pages/common/cargo-update.md
Labels: new command

#10736 logcat: update pt_BR translation
  pages.pt_BR/android/logcat.md
Labels: translation

#10746 trash: fix typo in Turkish translation
  pages.tr/linux/trash.md
Labels: translation, minor change

#10744 cargo-check: add page
  pages/common/cargo-check.md
Labels: new command

#10751 MAINTAINERS: add @kant as collaborator
  MAINTAINERS.md
Labels: community

#10753 !: add word designator example
  pages/common/!.md
Labels: page edit

#10728 grub-mkconfig: add Spanish translation
  pages.es/linux/grub-mkconfig.md
Labels: translation

#10750 shellcheck: fix typo
  pages/common/shellcheck.md
Labels: page edit, minor change

#10752 w3m: update page, fix invalid options
  pages/common/w3m.md
Labels: page edit

#10743 rustic: add page
  pages/common/rustic.md
Labels: new command

#10754 lchage: add page
  pages/linux/lchage.md
Labels: new command

#10721 mkosi: add page
  pages/linux/mkosi.md
Labels: new command, review needed

#10757 todo.sh: add page
  pages/common/todo.sh.md
Labels: new command

#10758 CODEOWNERS: add @kant for Spanish pages
  .github/CODEOWNERS
Labels: community, review needed

#10763 idea: add page
  pages/common/idea.md
Labels: new command

#10755 hwinfo: add page
  pages/linux/hwinfo.md
Labels: new command

#10766 hwinfo: update documentation link
  pages/linux/hwinfo.md
Labels: page edit, minor change
