Repository tldr-pages/tldr, pull requests merged in 2023-03, with the labels that each got.

#9845 Add Command Line Interface Pages project support
  pages/common/clip-view.md
  pages/common/md-to-clip.md
Labels: new command

#9888 docker-update: add page
  pages/common/docker-update.md
Labels: new command

#9903 arpspoof: add page
  pages/linux/arpspoof.md
Labels: new command

#9904 pyenv: add Japanese translation
  pages.ja/common/pyenv.md
Labels: translation

#9846 argocd, argocd-app: add page
  pages/common/argocd-app.md
  pages/common/argocd.md
Labels: new command

#9905 arch: add Spanish translation
  pages.es/common/arch.md
Labels: translation

#9907 argon2: add Spanish translation
  pages.es/common/argon2.md
Labels: translation

#9902 cut: update Spanish translation
  pages.es/common/cut.md
Labels: translation

#9377 prompt: add page
  pages/windows/prompt.md
Labels: new command, hacktoberfest-accepted

#9900 gummy: add page
  pages/linux/gummy.md
Labels: new command

#9909 openai: add page
  pages/common/openai.md
Labels: new command

#9887 split: update page
  pages/osx/split.md
Labels: page edit

#9916 gsettings: fix typo
  pages/linux/gsettings.md
Labels: page edit, minor change

#9809 README: mention Command Line Interface Pages project
  README.md
Labels: documentation

#9912 apropos: add Spanish translation
  pages.es/common/apropos.md
Labels: translation

#9914 grub-reboot: add page
  pages/linux/grub-reboot.md
Labels: new command

#9915 grub-set-default: add page
  pages/linux/grub-set-default.md
Labels: new command

#9913 aircrack-ng: add page
  pages/common/aircrack-ng.md
Labels: new command

#9917 grub-file: add page
  pages/linux/grub-file.md
Labels: new command

#9897 airodump-ng: add Chinese translation
  pages.zh/common/airodump-ng.md
Labels: translation

#9425 git-show-unmerged-branches: add German translation
  pages.de/common/git-show-unmerged-branches.md
Labels: waiting, translation, hacktoberfest-accepted

#9933 stegsnow: add page
  pages/linux/stegsnow.md
Labels: new command

#9924 openvpn: update command
  pages/common/openvpn.md
Labels: page edit, minor change

#9725 apx: refresh page
  pages.ta/linux/apx.md
  pages/linux/apx.md
Labels: page edit, translation, review needed

#9730 vso: add page
  pages/linux/vso.md
Labels: new command, review needed

#8785 podman-*: add page
  pages/common/podman-image.md
  pages/common/podman-images.md
  pages/common/podman-ps.md
  pages/common/podman-rmi.md
  pages/common/podman-run.md
Labels: page edit, new command, mass changes, hacktoberfest-accepted

#9922 handlr: add page
  pages/linux/handlr.md
Labels: new command

#9928 bird: add page
  pages/common/bird.md
Labels: new command

#9939 ajson: add Chinese translation
  pages.zh/common/ajson.md
Labels: translation

#9935 sed: improve description of -i option
  pages/linux/sed.md
Labels: page edit, minor change

#9927 ffmpeg: update syntax for the -codec switch
  pages/common/ffmpeg.md
Labels: page edit

#9943 xcopy: add Italian translation
  pages.it/windows/xcopy.md
Labels: translation

#9942 apm: add Spanish translation
  pages.es/common/apm.md
Labels: translation

#9941 docker-pull: add page
  pages/common/docker-pull.md
Labels: new command, review needed

#9932 fastd: add page
  pages/common/fastd.md
Labels: new command

#9931 babeld: add page
  pages/common/babeld.md
Labels: new command

#9944 dbclient: add page
  pages/linux/dbclient.md
Labels: new command

#9940 docker-tag: add page
  pages/common/docker-tag.md
Labels: new command, review needed

#9945 dropbearkey: add page
  pages/linux/dropbearkey.md
Labels: new command

#9929 birdc: add page
  pages/common/birdc.md
Labels: new command

#9923 cp: add Turkish translation
  pages.tr/common/cp.md
Labels: translation

#9918 rgpt: create page
  pages/common/rgpt.md
Labels: new command

#9934 airodump-ng: add Spanish translation
  pages.es/common/airodump-ng.md
Labels: translation

#9953 az-repos: add page
  pages/common/az-repos.md
Labels: new command

#9951 az-devops: add page
  pages/common/az-devops.md
Labels: new command

#9925 fzf: add Turkish translation
  pages.tr/common/fzf.md
Labels: translation

#9946 dropbearconvert: add page
  pages/linux/dropbearconvert.md
Labels: new command

#9948 argocd-app: add Spanish translation
  pages.es/common/argocd-app.md
Labels: translation

#9949 systemd-run: add page
  pages/linux/systemd-run.md
Labels: new command

#9955 [[: add Spanish translation
  pages.es/common/[[.md
Labels: translation

#9958 aria2c: add Spanish translation
  pages.es/common/aria2c.md
Labels: translation

#9960 astronomer: add Spanish translation
  pages.es/common/astronomer.md
Labels: translation

#9883 linux/a*: add Spanish translation
  pages.es/linux/a2disconf.md
  pages.es/linux/a2dismod.md
  pages.es/linux/a2dissite.md
  pages.es/linux/a2enconf.md
  pages.es/linux/a2enmod.md
  pages.es/linux/a2ensite.md
  pages.es/linux/a2query.md
  pages.es/linux/abbr.md
  pages.es/linux/abroot.md
  pages.es/linux/ac.md
Labels: mass changes, translation, review needed

#9962 insmod: add page
  pages/linux/insmod.md
Labels: new command

#9921 prqlc: add page
  pages/common/prqlc.md
Labels: new command

#9956 tftp: add page
  pages/linux/tftp.md
Labels: new command

#9978 md-to-clip: refresh page
  pages/common/md-to-clip.md
Labels: page edit

#9984 asar: add Spanish translation
  pages.es/common/asar.md/asar.md
Labels: translation

#9890 nala: add page
  pages/linux/nala.md
Labels: new command, review needed

#9898 Community: Update Gitter links to Matrix, Update Badges, Remove editor extensions
  .github/ISSUE_TEMPLATE/config.yml
  COMMUNITY-ROLES.md
  CONTRIBUTING.md
  GOVERNANCE.md
  MAINTAINERS.md
  README.md
  contributing-guides/maintainers-guide.md
Labels: documentation, decision, tooling, community

#9992 audacious: add Spanish translation
  pages.es/common/audacious.md
Labels: translation

#9990 vhs: add page
  pages/common/vhs.md
Labels: new command

#9938 aircrack-ng: add German translation
  pages.de/common/aircrack-ng.md
Labels: translation

#9973 rhash: add page
  pages/common/rhash.md
Labels: new command

#9967 stun: add page
  pages/common/stun.md
Labels: new command

#9968 pystun3: add page
  pages/common/pystun3.md
Labels: new command
