Repository tldr-pages/tldr, pull requests merged in 2023-12, with the labels that each got.

#11635 docker: fix typos in Spanish translation
  pages.es/common/docker.md
Labels: translation, minor change

#11634 cpdf: update Spanish translation
  pages.es/common/cpdf.md
Labels: translation

#11628 getfileinfo, goku, w, xip: add Indonesian translation
  pages.id/osx/getfileinfo.md
  pages.id/osx/goku.md
  pages.id/osx/w.md
  pages.id/osx/xip.md
Labels: translation

#11629 clang, clang++, gcc, g++: edit page
  pages/common/clang++.md
  pages/common/clang.md
  pages/common/g++.md
  pages/common/gcc.md
Labels: page edit

#11639 env: add Dutch translation
  pages.nl/common/env.md
Labels: translation

#11644 aws-s3: add subcommand mention
  pages/common/aws-s3.md
Labels: page edit, minor change

#11642 aws-s3-website: add page
  pages/common/aws-s3-website.md
Labels: new command

#11648 agate: add Korean translation
  pages.ko/common/agate.md
Labels: translation

#11653 acyclic: add Korean translation
  pages.ko/common/acyclic.md
Labels: translation

#11655 ps-nvm: update Dutch translation
  pages.nl/common/ps-nvm.md
Labels: translation, minor change

#11619 style-guide: add short option mnemonics, and windows- and powershell-specific rules
  contributing-guides/style-guide.md
Labels: documentation, decision

#11647 gcloud-version: add page
  pages/common/gcloud-version.md
Labels: new command

#11656 xteddy: add page
  pages/common/xteddy.md
Labels: new command

#11658 git-mv: fix typo in Spanish translation
  pages.es/common/git-mv.md
Labels: translation, minor change

#11657 git-checkout: fix typos in Spanish translation
  pages.es/common/git-checkout.md
Labels: translation

#11660 git-pull: fix typos in Spanish translation
  pages.es/common/git-pull.md
Labels: translation

#11663 git-reset: update Spanish translation
  pages.es/common/git-reset.md
Labels: translation

#11668 ipconfig: add German translation
  pages.de/windows/ipconfig.md
Labels: translation

#11677 tree: fix typo in Spanish translation
  pages.es/common/tree.md
Labels: translation, minor change

#11678 yes: fix typos in Spanish translation
  pages.es/common/yes.md
Labels: translation

#11675 nest: fix typo in Spanish translation
  pages.es/common/nest.md
Labels: translation, minor change

#11690 gcloud-info: new page
  pages/common/gcloud-info.md
Labels: new command

#11679 gcloud-{components-install, config-set}: add pages
  pages/common/gcloud-components-install.md
  pages/common/gcloud-config-set.md
Labels: new command

#11695 gcloud-{logging-logs-list, sql-export-sql}: add page
  pages/common/gcloud-logging-logs-list.md
  pages/common/gcloud-sql-export-sql.md
Labels: new command

#11669 CONTRIBUTING: update page, fix Markdown syntax
  CONTRIBUTING.md
Labels: documentation

#11704 clj: add Dutch translation
  pages.nl/common/clj.md
Labels: translation

#11707 ykman*: add Dutch translation
  pages.nl/common/ykman-config.md
  pages.nl/common/ykman-fido.md
  pages.nl/common/ykman-oath.md
  pages.nl/common/ykman-openpgp.md
  pages.nl/common/ykman.md
Labels: translation

#11711 man: update Spanish translation
  pages.es/linux/man.md
Labels: translation

#11712 raspinfo: fix Spanish typo
  pages.es/linux/raspinfo.md
Labels: translation

#11718 yum: translate placeholders to Spanish
  pages.es/linux/yum.md
Labels: translation

#11719 as: fix Spanish syntax issue
  pages.es/osx/as.md
Labels: translation

#11717 xdg-open: minor fix in Spanish translation
  pages.es/linux/xdg-open.md
Labels: translation

#11710 grub-mkconfig: fix typos in Spanish translation
  pages.es/linux/grub-mkconfig.md
Labels: translation

#11716 byzanz-record: add page
  pages/linux/byzanz-record.md
Labels: new command

#11721 androguard: add Korean translation
  pages.ko/common/androguard.md
Labels: translation

#11664 helm-install: fix typo in Spanish translation
  pages.es/common/helm-install.md
Labels: translation, minor change

#11697 llm: add page
  pages/common/llm.md
Labels: new command, review needed

#11709 !: add Chinese translation
  pages.zh/common/!.md
Labels: translation

#11726 chore(ci): bump `actions/setup-python` to v5, set version to 3.12; fix CODEOWNERS
  .github/CODEOWNERS
  .github/workflows/ci.yml
Labels: tooling

#11722 gcloud-sql-backups-describe: add page
  pages/common/gcloud-sql-backups-describe.md
Labels: new command

#11736 get-nodeversions: add Dutch translation
  pages.nl/common/get-nodeversions.md
Labels: translation

#11731 atuin: add Korean translation
  pages.ko/common/atuin.md
Labels: translation

#11738 7z: remove file extension in -t example
  pages.bn/common/7z.md
  pages.ca/common/7z.md
  pages.de/common/7z.md
  pages.es/common/7z.md
  pages.fa/common/7z.md
  pages.fr/common/7z.md
  pages.hi/common/7z.md
  pages.id/common/7z.md
  pages.it/common/7z.md
  pages.ja/common/7z.md
  pages.ko/common/7z.md
  pages.nl/common/7z.md
  pages.pl/common/7z.md
  pages.pt_BR/common/7z.md
  pages.pt_PT/common/7z.md
  pages.ru/common/7z.md
  pages.tr/common/7z.md
  pages.zh/common/7z.md
  pages/common/7z.md
Labels: page edit, translation

#11728 `test`: Use POSIX-compliant example for equals comparison
  pages.bn/common/[.md
  pages.de/common/[.md
  pages.es/common/[.md
  pages.fa/common/[.md
  pages.id/common/[.md
  pages.it/common/[.md
  pages.ja/common/[.md
  pages.ja/common/test.md
  pages.ko/common/[.md
  pages.nl/common/[.md
  pages.pl/common/[.md
  pages.pl/common/test.md
  pages.pt_BR/common/[.md
  pages.sv/common/[.md
  pages.zh/common/[.md
  pages/common/[.md
  pages/common/test.md
Labels: page edit, translation

#11733 docker-inspect: escape placeholders
  pages.de/common/docker-inspect.md
  pages.fr/common/docker-inspect.md
  pages.it/common/docker-inspect.md
  pages.pt_BR/common/docker-inspect.md
  pages.tr/common/docker-inspect.md
  pages/common/docker-inspect.md
Labels: page edit, translation

#11696 aws-kafka: add page
  pages/common/aws-kafka.md
Labels: new command

#11739 qm-import-disk: match with translations
  pages/linux/qm-import-disk.md
Labels: page edit, minor change

#11743 qm-move-disk: update Dutch translation
  pages.nl/linux/qm-move-disk.md
Labels: translation, minor change

#11640 pages.id/*: add and improve Indonesian translation
  pages.id/common/!.md
  pages.id/common/7z.md
  pages.id/common/7za.md
  pages.id/common/7zr.md
  pages.id/common/a2ping.md
  pages.id/common/ab.md
  pages.id/common/abduco.md
  pages.id/common/ac.md
  pages.id/common/accelerate.md
  pages.id/common/ack.md
  pages.id/common/acme.sh-dns.md
  pages.id/common/acme.sh.md
  pages.id/common/act.md
  pages.id/common/acyclic.md
  pages.id/common/adguardhome.md
  pages.id/common/adscript.md
  pages.id/common/afconvert.md
  pages.id/common/ag.md
  pages.id/common/agate.md
  pages.id/common/age-keygen.md
  pages.id/common/age.md
  pages.id/common/aircrack-ng.md
  pages.id/common/airdecap-ng.md
  pages.id/common/aireplay-ng.md
  pages.id/common/airmon-ng.md
  pages.id/common/airodump-ng.md
  pages.id/common/airpaste.md
  pages.id/common/airshare.md
  pages.id/common/ajson.md
  pages.id/common/alex.md
  pages.id/common/gcc.md
  pages.id/common/git-commit.md
  pages.id/common/history.md
  pages.id/common/laravel-zero.md
  pages.id/common/laravel.md
  pages.id/common/powershell.md
  pages.id/common/pwsh.md
  pages.id/common/rails-db.md
  pages.id/common/rubocop.md
  pages.id/linux/halt.md
  pages.id/linux/reboot.md
  pages.id/linux/shutdown.md
  pages.id/osx/pbpaste.md
  pages.id/windows/chkdsk.md
  pages.id/windows/powershell.md
Labels: translation

#11646 COMMUNITY-ROLES: document CODEOWNERS file
  COMMUNITY-ROLES.md
Labels: documentation

#11746 csrutil: fix Spanish typo
  pages.es/osx/csrutil.md
Labels: translation

#11749 aireplay-ng: fix typo in URL
  pages.id/common/aireplay-ng.md
Labels: translation

#11758 pnmshear: add page
  pages/common/pnmshear.md
Labels: new command

#11757 pnmsmooth: add page
  pages/common/pnmsmooth.md
Labels: new command

#11756 pampop9: add page
  pages/common/pampop9.md
Labels: new command

#11755 pnmtile: add page
  pages/common/pnmtile.md
Labels: new command

#11754 adscript: add Korean translation
  pages.ko/common/adscript.md
Labels: translation

#11753 pnmtoddif: add page
  pages/common/pnmtoddif.md
Labels: new command

#11748 scrot: add two examples
  pages/linux/scrot.md
Labels: page edit

#11763 kcat: fix typo
  pages/common/kcat.md
Labels: page edit

#11769 audacious: add Korean translation
  pages.ko/common/audacious.md
Labels: translation

#11767 nvm: update Spanish translation
  pages.es/windows/nvm.md
Labels: translation

#11745 cupsctl, lpq, lprm, lpadmin, lpoptions: add pages
  pages.pt_BR/common/cupsctl.md
  pages.pt_BR/common/lpadmin.md
  pages.pt_BR/common/lpoptions.md
  pages.pt_BR/common/lpq.md
  pages.pt_BR/common/lprm.md
  pages/common/cupsctl.md
  pages/common/lpadmin.md
  pages/common/lpoptions.md
  pages/common/lpq.md
  pages/common/lprm.md
Labels: new command, translation

#11770 style-guide: add Portuguese specific rules
  contributing-guides/style-guide.md
Labels: documentation

#11734 mpv, pw-cat: update page; mpv: add pt_BR translation
  pages.pt_BR/common/mpv.md
  pages/common/mpv.md
  pages/linux/pw-cat.md
Labels: page edit, translation

#11744 pw-mon: add page and pt_BR translation
  pages.pt_BR/linux/pw-mon.md
  pages/linux/pw-mon.md
Labels: new command, translation

#11732 7z{,a,r}, arduino, bundle, bzip2, chromium: update pt_BR translation
  pages.pt_BR/common/7z.md
  pages.pt_BR/common/7za.md
  pages.pt_BR/common/7zr.md
  pages.pt_BR/common/arduino.md
  pages.pt_BR/common/bundle.md
  pages.pt_BR/common/bzip2.md
  pages.pt_BR/common/chromium.md
Labels: translation

#11765 m: fix verb in Spanish translation
  pages.es/osx/m.md
Labels: translation, minor change

#11759 get-nodeinstalllocation: fix Dutch translation
  pages.nl/common/get-nodeinstalllocation.md
Labels: translation

#11760 install-nodeversion: add Dutch translation
  pages.nl/common/install-nodeversion.md
Labels: translation

#11772 argon2: add Korean translation
  pages.ko/common/argon2.md
Labels: translation

#11751 pnmtopalm: add page; palmtopnm: modify page
  pages/common/palmtopnm.md
  pages/common/pnmtopalm.md
Labels: page edit, new command

#11752 fiascotopnm, pnmtofiasco: add pages
  pages/common/fiascotopnm.md
  pages/common/pnmtofiasco.md
Labels: new command

#11774 qm-move-disk: add Dutch alias page
  pages.nl/linux/qm-move_disk.md
Labels: translation

#11776 objdump: add Dutch translation
  pages.nl/common/objdump.md
Labels: translation

#11775 strings: add Dutch translation
  pages.nl/common/strings.md
Labels: translation

#11787 pamtowinicon: add Dutch translation
  pages.nl/common/pamtowinicon.md
Labels: translation

#11786 winicontopam: add Dutch translation
  pages.nl/common/winicontopam.md
Labels: translation

#11785 pamtotiff: add Dutch translation
  pages.nl/common/pamtotiff.md
Labels: translation

#11784 pamtotga: add Dutch translation
  pages.nl/common/pamtotga.md
Labels: translation

#11783 pbmtoxbm: add Dutch translation
  pages.nl/common/pbmtoxbm.md
Labels: translation

#11782 xzmore: add Dutch translation
  pages.nl/common/xzmore.md
Labels: translation

#11781 netlify: add Dutch translation
  pages.nl/common/netlify.md
Labels: translation

#11651 salloc, sattach, sbcast, sdiag, sprio, sshare, strigger, sview, sh5util, scrun, scrontab: add pages
  pages/linux/salloc.md
  pages/linux/sattach.md
  pages/linux/sbcast.md
  pages/linux/scrontab.md
  pages/linux/sdiag.md
  pages/linux/sh5util.md
  pages/linux/sprio.md
  pages/linux/sshare.md
  pages/linux/strigger.md
  pages/linux/sview.md
Labels: new command

#11789 pamoil: add Dutch translation
  pages.nl/common/pamoil.md
Labels: translation

#11790 gradle: update Spanish translation
  pages.es/common/gradle.md
Labels: translation

#11779 pamscale, pnmscale, pnmscalefixed: add pages
  pages/common/pamscale.md
  pages/common/pnmscale.md
  pages/common/pnmscalefixed.md
Labels: new command

#11773 build-pdf: only build changed folders since last commit
  scripts/pdf/build-pdf.sh
Labels: tooling

#11777 pages*: remove bold and italic styling
  pages.ca/linux/conky.md
  pages.de/windows/cmd.md
  pages.es/common/git-pull.md
  pages.es/linux/conky.md
  pages.fr/common/git-reset.md
  pages.id/common/mongod.md
  pages.id/common/mv.md
  pages.it/common/csvcut.md
  pages.it/common/tac.md
  pages.ko/common/csvcut.md
  pages.pt_BR/common/clj.md
  pages/common/csvcut.md
  pages/common/strings.md
  pages/common/supervisorctl.md
Labels: page edit, translation

#11740 pw-link: update page; pw-*: add pt_BR translation
  pages.pt_BR/linux/pw-cat.md
  pages.pt_BR/linux/pw-cli.md
  pages.pt_BR/linux/pw-link.md
  pages.pt_BR/linux/pw-loopback.md
  pages.pt_BR/linux/pw-play.md
  pages.pt_BR/linux/pw-record.md
  pages/linux/pw-cat.md
  pages/linux/pw-link.md
Labels: page edit, translation

#11791 nixpkgs-review: add page
  pages/common/nixpkgs-review.md
Labels: new command

#11798 dig: remove inaccurate description of ANY
  pages.es/common/dig.md
  pages.it/common/dig.md
  pages.ja/common/dig.md
  pages.ko/common/dig.md
  pages.pt_BR/common/dig.md
  pages/common/dig.md
Labels: page edit, translation

#11778 pages.fr: fix descriptions missing a space before the semicolon
  pages.fr/common/age.md
  pages.fr/common/anki.md
  pages.fr/common/aria2c.md
  pages.fr/common/arp.md
  pages.fr/common/aws-quicksight.md
  pages.fr/common/az.md
  pages.fr/common/csh.md
  pages.fr/common/docker-machine.md
  pages.fr/common/docker-system.md
  pages.fr/common/gh.md
  pages.fr/common/ssh-keygen.md
  pages.fr/linux/cp.md
  pages.fr/sunos/svcadm.md
Labels: translation, review needed

#11543 systemd-resolve: add alias page
  pages/linux/systemd-resolve.md
Labels: new command

#11796 vboxmanage-movevm: add page
  pages/common/vboxmanage-movevm.md
Labels: new command

#11800 pamflip, pnmcolormap, pnmquant, pnmremap, pnmrotate, ppmquant: add pages
  pages/common/pamflip.md
  pages/common/pnmcolormap.md
  pages/common/pnmquant.md
  pages/common/pnmremap.md
  pages/common/pnmrotate.md
  pages/common/ppmquant.md
Labels: new command

#11804 python: remove placeholders
  pages.pt_BR/common/python.md
  pages.zh/common/python.md
  pages/common/python.md
Labels: page edit, translation

#11801 node: add Dutch translation
  pages.nl/common/remove-nodeversion.md
  pages.nl/common/set-nodeinstalllocation.md
  pages.nl/common/set-nodeversion.md
Labels: translation

#11802 ptpython: add Dutch translation
  pages.nl/common/ptpython.md
Labels: translation

#11807 systemd-resolve: add Dutch translation
  pages.nl/linux/resolvectl.md
  pages.nl/linux/systemd-resolve.md
Labels: translation

#11803 python: add Dutch translation
  pages.nl/common/python.md
Labels: translation

#11806 pnmscale, pamscale: add Dutch translation
  pages.nl/common/pamscale.md
  pages.nl/common/pnmscale.md
Labels: translation

#11809 ppmquant, pnmquant pnmremap: add Dutch translation
  pages.nl/common/pnmquant.md
  pages.nl/common/pnmremap.md
  pages.nl/common/ppmquant.md
Labels: translation

#11805 pw-cat: update page and pt_BR translation
  pages.pt_BR/linux/pw-cat.md
  pages/linux/pw-cat.md
Labels: page edit, translation, minor change

#11812 nix-classic: add Spanish translation
  pages.es/common/nix-classic.md
Labels: translation

#11808 cleanup: remove id_ed25519_tldr_asset_upload.enc file
  scripts/id_ed25519_tldr_asset_upload.enc
Labels: tooling

#11820 firefox, thunderbird: add Chinese translation
  pages.zh/common/firefox.md
  pages.zh/common/thunderbird.md
Labels: translation

#11818 mv: update Italian translation
  pages.it/common/mv.md
Labels: translation

#11633 chmod: update Spanish translation
  pages.es/common/chmod.md
Labels: translation

#11661 git-push: update Spanish translation
  pages.es/common/git-push.md
Labels: translation

#11814 vboxmanage-movevm: add Spanish translation
  pages.es/common/vboxmanage-movevm.md
  pages/common/vboxmanage-movevm.md
Labels: page edit, translation

#11632 calc: update Spanish translation
  pages.es/common/calc.md
Labels: translation, review needed

#11701 apt-get: update Spanish translation
  pages.es/linux/apt-get.md
Labels: translation

#11662 git-remote: update Spanish translation
  pages.es/common/git-remote.md
Labels: translation

#11822 scripts/deploy.sh: remove redundant paths from the sumfile
  scripts/deploy.sh
Labels: tooling

#11825 scripts: don't build archives when pages haven't been changed
  scripts/build.sh
  scripts/deploy.sh
Labels: tooling

#11622 mount.ddi: add page
  pages/linux/mount.ddi.md
Labels: new command

#11833 common-arguments: update pt-PT values; codeowners: remove waldyrious from pt-BR
  .github/CODEOWNERS
  contributing-guides/translation-templates/common-arguments.md
  pages.pt_PT/android/dalvikvm.md
  pages.pt_PT/android/logcat.md
  pages.pt_PT/common/7z.md
  pages.pt_PT/common/7za.md
  pages.pt_PT/common/7zr.md
  pages.pt_PT/common/alacritty.md
  pages.pt_PT/common/cd.md
  pages.pt_PT/common/chmod.md
Labels: documentation, translation

#11835 anki: add Korean translation
  pages.ko/common/anki.md
Labels: translation

#11836 scripts/deploy.sh: exit immediately if there aren't any changes
  scripts/deploy.sh
Labels: tooling

#11831 pages/*: fix small typos
  pages/common/ansible-inventory.md
  pages/common/gcloud.md
  pages/common/git-release.md
  pages/common/git-svn.md
  pages/common/kubectl-describe.md
  pages/common/kubectl-get.md
  pages/common/pip-install.md
  pages/common/ssh-copy-id.md
  pages/linux/cuyo.md
  pages/linux/genid.md
  pages/linux/ip.md
  pages/linux/lastlog.md
  pages/linux/rpm2cpio.md
  pages/linux/vgchange.md
  pages/linux/zathura.md
  pages/osx/fdesetup.md
  pages/osx/icalbuddy.md
Labels: page edit, minor change

#11853 MAINTAINERS: add @acuteenvy as org owner; update dead links
  MAINTAINERS.md
Labels: community

#11819 tac: update Italian translation
  pages.it/common/tac.md
Labels: translation

#11788 pipewire, pw-dump, pw-profiler: add pages
  pages.pt_BR/linux/pipewire.md
  pages.pt_BR/linux/pw-dump.md
  pages/linux/pipewire.md
  pages/linux/pw-dump.md
  pages/linux/pw-profiler.md
Labels: new command, translation

#11841 check-pr: add < and > as special cases and refactor
  scripts/check-pr.sh
Labels: tooling

#11849 git-stash: update Spanish translation
  pages.es/common/git-stash.md
Labels: translation

#11854 style-guide: add help and version commands section
  contributing-guides/style-guide.md
Labels: documentation

#11859 CODEOWNERS: remove waldyrious from pt_BR line
  .github/CODEOWNERS
Labels: translation

#11844 cups: add page
  pages/common/cups.md
Labels: new command

#11824 wikit: add page
  pages/linux/wikit.md
Labels: new command

#11867 yes: update pt_BR translation
  pages.pt_BR/common/yes.md
Labels: translation

#11829 pages.pt_BR: add and update several pages
  pages.pt_BR/common/adb-install.md
  pages.pt_BR/common/bc.md
  pages.pt_BR/common/clamav.md
  pages.pt_BR/common/command.md
  pages.pt_BR/common/dash.md
  pages.pt_BR/common/htop.md
  pages.pt_BR/common/transmission.md
  pages.pt_BR/common/units.md
  pages.pt_BR/common/unrar.md
  pages.pt_BR/linux/bluetoothd.md
  pages.pt_BR/linux/oomctl.md
  pages.pt_BR/linux/protontricks.md
Labels: translation

#11843 cancel, lpmove: add pages and pt_BR translation
  pages.pt_BR/common/cancel.md
  pages.pt_BR/common/lpmove.md
  pages/common/cancel.md
  pages/common/lpmove.md
Labels: new command, translation

#11876 auditd: add Korean translation
  pages.ko/common/auditd.md
Labels: translation

#11879 MAINTAINERS: add @cyqsimon to collaborators
  MAINTAINERS.md
Labels: community

#11847 awk: update Spanish translation
  pages.es/common/awk.md
Labels: translation

#11848 cargo: update Spanish translation
  pages.es/common/cargo.md
Labels: translation

#11852 histexpand: update Spanish translation
  pages.es/common/histexpand.md
Labels: translation

#11856 tmux: update page and Spanish translation
  pages.es/common/tmux.md
  pages.ja/common/tmux.md
  pages/common/tmux.md
Labels: page edit, translation

#11886 cups*: use OpenPrinting CUPS docs instead of Apple CUPS
  pages.pt_BR/common/cupsctl.md
  pages.pt_BR/common/lpadmin.md
  pages.pt_BR/common/lpoptions.md
  pages.pt_BR/common/lpq.md
  pages.pt_BR/common/lprm.md
  pages/common/cups-config.md
  pages/common/cupsctl.md
  pages/common/cupsd.md
  pages/common/lpadmin.md
  pages/common/lpinfo.md
  pages/common/lpoptions.md
  pages/common/lpq.md
  pages/common/lpr.md
  pages/common/lprm.md
Labels: page edit, translation

#11887 pw-cli: use a more clear description instead of a generic one
  pages.pt_BR/linux/pw-cli.md
  pages/linux/pw-cli.md
Labels: page edit, translation

#11652 docker-compose: update Spanish translation
  pages.es/common/docker-compose.md
Labels: translation

#11889 pages.*: update CUPS documentation URL
  pages.de/common/lpinfo.md
  pages.de/common/lpr.md
  pages.nl/common/cupsd.md
  pages.nl/common/lpadmin.md
  pages.nl/common/lprm.md
  pages.pt_BR/common/lpmove.md
Labels: translation

#11882 lpmove: update pt_BR translation
  pages.pt_BR/common/lpmove.md
Labels: translation

#11909 lsusb: remove obsolete command for Hindi
  pages.hi/linux/lsusb.md
Labels: translation

#11910 pages.id: update outdated pages
  pages.id/common/[.md
  pages.id/common/adb-install.md
  pages.id/common/aria2c.md
  pages.id/common/asar.md
  pages.id/common/clamscan.md
  pages.id/common/docker.md
  pages.id/common/git-clone.md
  pages.id/linux/dnf.md
  pages.id/linux/pacman.md
  pages.id/osx/date.md
  pages.id/osx/shuf.md
  pages.id/osx/xcodes.md
  pages.id/windows/find.md
  pages.id/windows/invoke-webrequest.md
  pages.id/windows/scoop.md
  pages.id/windows/set-location.md
  pages.id/windows/wget.md
Labels: translation

#11900 wpexec: add page
  pages/common/wpexec.md
Labels: new command

#11906 bash, fold: update link to match other pages
  pages.de/common/bash.md
  pages.es/common/bash.md
  pages.fr/common/bash.md
  pages.it/common/bash.md
  pages.ko/common/bash.md
  pages.nl/common/bash.md
  pages.pt_BR/common/bash.md
  pages.zh/common/bash.md
  pages.zh_TW/common/bash.md
  pages/common/bash.md
  pages/linux/fold.md
Labels: page edit, translation

#11826 cups{accept,reject,enable,disable}: add pages; lpstat: add pt_BR translation
  pages.pt_BR/common/cupsaccept.md
  pages.pt_BR/common/cupsdisable.md
  pages.pt_BR/common/cupsenable.md
  pages.pt_BR/common/cupsreject.md
  pages.pt_BR/common/lpstat.md
  pages/common/cupsaccept.md
  pages/common/cupsdisable.md
  pages/common/cupsenable.md
  pages/common/cupsreject.md
Labels: new command, translation

#11898 cupstestppd: add page
  pages/common/cupstestppd.md
Labels: new command
