Repository tldr-pages/tldr, pull requests merged in 2023-08, with the labels that each got.

#10544 nmcli*: update pages
  pages/linux/nmcli-agent.md
  pages/linux/nmcli-connection.md
  pages/linux/nmcli-device.md
  pages/linux/nmcli-radio.md
  pages/linux/nmcli.md
Labels: page edit

#10572 !: add page
  pages/linux/!.md
Labels: new command

#10203 imgcat: move from osx to common, update page
  pages.pt_BR/common/imgcat.md
  pages.zh/common/imgcat.md
  pages/common/imgcat.md
Labels: page edit, translation

#10446 polybar, polybar-msg: add page
  pages/common/polybar-msg.md
  pages/common/polybar.md
Labels: new command

#10574 wpctl: add page
  pages/linux/wpctl.md
Labels: new command

#10454 ed: add Spanish translation
  pages.es/osx/ed.md
Labels: translation

#10453 dhcp6d: add Spanish translation
  pages.es/osx/dhcp6d.md
Labels: translation

#10456 dot_clean: add Spanish translation
  pages.es/osx/dot_clean.md
Labels: translation

#10580 case: update description
  pages/common/case.md
Labels: page edit

#10578 select: add page
  pages/linux/select.md
Labels: new command

#10338 hexdump: add pt_BR translation
  pages.pt_BR/common/hexdump.md
Labels: translation

#10502 cargo-*: add pt_BR translation
  pages.pt_BR/common/cargo-add.md
  pages.pt_BR/common/cargo-build.md
  pages.pt_BR/common/cargo-clippy.md
  pages.pt_BR/common/cargo-doc.md
  pages.pt_BR/common/cargo-rustc.md
  pages.pt_BR/common/cargo-test.md
Labels: mass changes, translation

#10581 pop: add page
  pages/common/pop.md
Labels: new command

#10589 rsync: update page, link to the official documentation instead of manned.org
  pages.fr/common/rsync.md
  pages.id/common/rsync.md
  pages.pl/common/rsync.md
  pages.zh/common/rsync.md
  pages/common/rsync.md
Labels: page edit, translation

#10587 btrfs-version: fix syntax
  pages.pt_BR/linux/btrfs-version.md
Labels: translation, minor change

#10588 httpie: add osx page
  pages/osx/httpie.md
Labels: new command

#10577 mediamtx: add page
  pages/linux/mediamtx.md
Labels: new command

#10576 fluidsynth: add page
  pages/linux/fluidsynth.md
Labels: new command

#10575 pydoc: add page
  pages/common/pydoc.md
Labels: new command

#10579 while: replace incorrect link
  pages/common/while.md
Labels: page edit, review needed

#10573 pkgctl: add page
  pages/linux/pkgctl.md
Labels: new command

#10512 pwd: add Arabic translation
  pages.ar/common/pwd.md
Labels: translation

#10436 pages/*: add backticks around I/O streams
  pages/common/at.md
  pages/common/base32.md
  pages/common/base64.md
  pages/common/basenc.md
  pages/common/bat.md
  pages/common/batch.md
  pages/common/bison.md
  pages/common/bzip2.md
  pages/common/bzip3.md
  pages/common/carbon-now.md
  pages/common/cat.md
  pages/common/cmark.md
  pages/common/column.md
  pages/common/cpio.md
  pages/common/expand.md
  pages/common/fold.md
  pages/common/gh-auth.md
  pages/common/git-archive.md
  pages/common/git-bundle.md
  pages/common/git-column.md
  pages/common/git-stripspace.md
  pages/common/gnomon.md
  pages/common/goimports.md
  pages/common/gpg2.md
  pages/common/hashid.md
  pages/common/mail.md
  pages/common/msmtp.md
  pages/common/mutool.md
  pages/common/nl.md
  pages/common/pdftotext.md
  pages/common/pueue-follow.md
  pages/common/pygmentize.md
  pages/common/sops.md
  pages/common/stdbuf.md
  pages/common/tee.md
  pages/common/ts.md
  pages/common/unexpand.md
  pages/common/zcat.md
  pages/linux/aspell.md
  pages/linux/cat.md
  pages/linux/dmesg.md
  pages/linux/flameshot.md
  pages/linux/grub-script-check.md
  pages/linux/hardinfo.md
  pages/linux/keyctl.md
  pages/linux/logsave.md
  pages/linux/pridecat.md
  pages/linux/rmmod.md
  pages/linux/run-mailcap.md
  pages/linux/script.md
  pages/linux/scriptreplay.md
  pages/linux/slop.md
  pages/linux/sqfscat.md
  pages/linux/sxiv.md
  pages/linux/utmpdump.md
  pages/osx/cat.md
  pages/osx/dmesg.md
  pages/osx/pbpaste.md
  pages/osx/wc.md
  pages/sunos/dmesg.md
Labels: page edit, mass changes, review needed

#10273 xip: add Spanish translation
  pages.es/osx/xip.md
Labels: translation

#10289 valet: add Spanish translation
  pages.es/osx/valet.md
Labels: translation

#10295 xcode-select: add Spanish translation
  pages.es/osx/xcode-select.md
Labels: translation

#10303 webinspectord: add Spanish translation
  pages.es/osx/webinspectord.md
Labels: translation

#10412 ruby, gem: update page; irb, rake: add page
  pages/common/gem.md
  pages/common/irb.md
  pages/common/rake.md
  pages/common/ruby.md
Labels: page edit, new command, review needed

#10314 ping: add Spanish translation
  pages.es/osx/ping.md
Labels: translation

#10321 wps: add Spanish translation
  pages.es/osx/wps.md
Labels: translation

#10318 whatis: add Spanish translation
  pages.es/osx/whatis.md
Labels: translation

#10326 wwand: add Spanish translation
  pages.es/osx/wwand.md
Labels: translation

#10328 xartstorageremoted: add Spanish translation
  pages.es/osx/xartstorageremoted.md
Labels: translation

#10339 atoum: add Spanish translation
  pages.es/common/atoum.md
Labels: translation

#10381 top: add Spanish translation
  pages.es/osx/top.md
Labels: translation

#10374 sw_vers: add Spanish translation
  pages.es/osx/sw_vers.md
Labels: translation

#10365 shortcuts: add Spanish translation
  pages.es/osx/shortcuts.md
Labels: translation

#10345 xcrun: add Spanish translation
  pages.es/osx/xcrun.md
Labels: translation

#10400 llvm-lipo: add Spanish translation
  pages.es/osx/llvm-lipo.md
Labels: translation

#10401 lldb: add Spanish translation
  pages.es/osx/lldb.md
Labels: translation

#10403 pbpaste: add Spanish translation
  pages.es/osx/pbpaste.md
Labels: translation

#10408 safeejectgpu: add Spanish translation
  pages.es/osx/safeejectgpu.md
Labels: translation

#10543 chmod,chown,clear,cmp,dd,df,diff,echo,export,grep,head,ifconfig, translation-templates/*: add Farsi translation
  contributing-guides/translation-templates/alias-pages.md
  contributing-guides/translation-templates/common-arguments.md
  contributing-guides/translation-templates/subcommand-mention.md
  pages.fa/common/chmod.md
  pages.fa/common/chown.md
  pages.fa/common/clear.md
  pages.fa/common/cmp.md
  pages.fa/common/dd.md
  pages.fa/common/df.md
  pages.fa/common/diff.md
  pages.fa/common/echo.md
  pages.fa/common/export.md
  pages.fa/common/grep.md
  pages.fa/common/head.md
  pages.fa/common/ifconfig.md
Labels: documentation, translation, review needed

#10419 diskutil: add Spanish translation
  pages.es/osx/diskutil.md
Labels: translation

#10424 age-keygen: add page; age: update page
  pages/common/age-keygen.md
  pages/common/age.md
Labels: page edit, new command, review needed

#10426 nm-online: add page; nmtui-{connect,edit,hostname}: add alias pages
  pages/linux/nm-online.md
  pages/linux/nmtui-connect.md
  pages/linux/nmtui-edit.md
  pages/linux/nmtui-hostname.md
Labels: new command, review needed

#10269 git-annex: update help command description
  pages.fr/common/git-annex.md
  pages.ta/common/git-annex.md
  pages.tr/common/git-annex.md
  pages/common/git-annex.md
Labels: page edit, translation, review needed, minor change

#10435 popd: add '-n' option; pushd: add '-n' option
  pages/common/popd.md
  pages/common/pushd.md
Labels: page edit, review needed

#10427 internetsharing; add Spanish translation
  pages.es/osx/internetsharing.md
Labels: translation

#10434 sips: add Spanish translation
  pages.es/osx/sips.md
Labels: translation

#10438 nvram: add Spanish translation
  pages.es/osx/nvram.md
Labels: translation

#10501 colorls: add Japanese translation
  pages.ja/common/colorls.md
Labels: translation, review needed

#10447 terminal-notifier: add Spanish translation
  pages.es/osx/terminal-notifier.md
Labels: translation

#10451 photoanalysisd: add Spanish translation
  pages.es/osx/photoanalysisd.md
Labels: translation

#10443 time: update page
  pages/common/time.md
Labels: page edit, review needed

#10472 bc: add Spanish translation
  pages.es/osx/bc.md
Labels: translation

#10452 hidd: add Spanish translation
  pages.es/osx/hidd.md
Labels: translation

#10477 system_profiler: update page
  pages/osx/system_profiler.md
Labels: page edit

#10571 mkhomedir_helper: add page
  pages/linux/mkhomedir_helper.md
Labels: new command

#10592 qdbus: edit page
  pages/common/qdbus.md
Labels: page edit

#10593 dhcpig: add page
  pages/common/dhcpig.md
Labels: new command

#10549 duckdb: add page
  pages/common/duckdb.md
Labels: new command

#10595 pkgctl-auth: add page
  pages/linux/pkgctl-auth.md
Labels: new command

#10600 pkgctl-version: add page
  pages/linux/pkgctl-version.md
Labels: new command

#10583 reboot: add Spanish translation
  pages.es/osx/reboot.md
Labels: translation

#10582 readlink: add Spanish translation
  pages.es/osx/readlink.md
Labels: translation

#10569 cut: add Spanish translation
  pages.es/osx/cut.md
Labels: translation

#10568 ctkd: add Spanish translation
  pages.es/osx/ctkd.md
Labels: translation

#10567 csrutil: add Spanish translation
  pages.es/osx/csrutil.md
Labels: translation

#10566 csshx: add Spanish translation
  pages.es/osx/csshx.md
Labels: translation

#10565 bnepd: add Spanish translation
  pages.es/osx/bnepd.md
Labels: translation

#10559 bless: add Spanish translation
  pages.es/osx/bless.md
Labels: translation

#10564 appsleepd: add Spanish translation
  pages.es/osx/appsleepd.md
Labels: translation

#10553 emond: add Spanish translation
  pages.es/osx/emond.md
Labels: translation

#10554 fdesetup: add Spanish translation
  pages.es/osx/fdesetup.md
Labels: translation

#10555 feature support: provide translation archives
  scripts/build.sh
  scripts/deploy.sh
Labels: architecture, tooling, review needed

#10599 pkgctl-diff: add page
  pages/linux/pkgctl-diff.md
Labels: new command

#10471 jf: add page for JFrog CLI
  pages/common/jf.md
Labels: new command

#10591 aws-batch: add page
  pages/common/aws-batch.md
Labels: new command

#10606 kismet: add page
  pages/common/kismet.md
Labels: new command

#10550 semanage-fcontext, restorecon: add page
  pages/linux/restorecon.md
  pages/linux/semanage-fcontext.md
Labels: new command

#10609 auto-cpufreq: add page
  pages/linux/auto-cpufreq.md
Labels: new command

#10612 ffprobe: fix invalid command
  pages/common/ffprobe.md
Labels: page edit, minor change

#10601 powertop: add `--time` example
  pages/linux/powertop.md
Labels: page edit

#10541 ftxdiff: add Spanish translation
  pages.es/osx/ftxdiff.md
Labels: translation

#10607 mkswap, swap{on,off}: update page
  pages/linux/mkswap.md
  pages/linux/swapoff.md
  pages/linux/swapon.md
Labels: page edit

#10615 watchexec: fix --restart example
  pages/common/watchexec.md
Labels: page edit, minor change

#10618 systemd-notify: add page
  pages/linux/systemd-notify.md
Labels: new command

#10608 timetrap: add command to edit last entry
  pages/common/timetrap.md
Labels: page edit

#10597 docker-compose: run specifying a project name (#10596)
  pages.es/common/docker-compose.md
  pages/common/docker-compose.md
Labels: page edit, translation

#10540 dd: add Spanish translation
  pages.es/osx/dd.md
Labels: translation

#10620 nix3-run: add more examples
  pages/common/nix3-run.md
Labels: page edit

#10128 clamav, clamdscan, clamscan, freshclam: update Indonesian translations
  pages.id/common/clamav.md
  pages.id/common/clamdscan.md
  pages.id/common/clamscan.md
  pages.id/common/freshclam.md
Labels: translation

#10622 systemd-path: add page
  pages/linux/systemd-path.md
Labels: new command

#10621 watchexec: update page
  pages/common/watchexec.md
Labels: page edit, minor change

#10626 procs: add `--tree` example
  pages/common/procs.md
Labels: page edit

#10617 ncu: add page
  pages/common/ncu.md
Labels: new command

#10614 aws-cloudwatch: add page
  pages/common/aws-cloudwatch.md
Labels: new command

#10628 swaylock: add page
  pages/linux/swaylock.md
Labels: new command

#10627 aws-cloud9: add page
  pages/common/aws-cloud9.md
Labels: new command

#10632 mvn: fix typo
  pages/common/mvn.md
Labels: page edit, minor change

#10604 optimus-manager: add page
  pages/linux/optimus-manager.md
Labels: new command

#10638 checksec: add page
  pages/common/checksec.md
Labels: new command

#10639 objdump: add -x example
  pages/common/objdump.md
Labels: page edit

#10643 shar: add page
  pages/common/shar.md
  pages/linux/shar.md
Labels: new command

#10646 de/base64: replace kommando with befehl
  pages.de/common/base64.md
Labels: page edit, translation, minor change

#10645 packwiz: add page
  pages/common/packwiz.md
Labels: new command, review needed

#10647 docker-cp: add missing placeholders
  pages.fr/common/docker-cp.md
Labels: translation, minor change

#10649 /*: fix typos
  CLIENT-SPECIFICATION.md
  contributing-guides/maintainers-guide.md
  pages.fr/android/bugreport.md
  pages.fr/android/bugreportz.md
  pages.fr/android/dumpsys.md
  pages.fr/android/input.md
  pages.fr/android/pm.md
  pages.fr/android/wm.md
Labels: documentation, mass changes, translation

#10625 texcount: add page
  pages/common/texcount.md
Labels: new command, review needed

#10650 schroot: add session examples, move --list to the top
  pages/linux/schroot.md
Labels: page edit

#10652 mktemp(linux): improve examples
  pages/linux/mktemp.md
Labels: page edit
