Repository tldr-pages/tldr, pull requests merged in 2023-11, with the labels that each got.

#11349 cargo-*: add page
  pages/common/cargo-pkgid.md
  pages/common/cargo-tree.md
  pages/common/cargo-vendor.md
  pages/common/cargo-verify-project.md
Labels: new command

#11342 windows/*: add PowerShell pwd and mv equivalents
  pages/windows/get-location.md
  pages/windows/gl.md
  pages/windows/mi.md
  pages/windows/move-item.md
  pages/windows/move.md
  pages/windows/mv.md
  pages/windows/pwd.md
Labels: new command, hacktoberfest-accepted

#10942 git-stage: convert to alias page
  pages.fr/common/git-stage.md
  pages.it/common/git-stage.md
  pages.tr/common/git-stage.md
  pages/common/git-stage.md
Labels: page edit, translation, review needed

#11356 jar: add Korean translation
  pages.ko/common/jar.md
Labels: translation

#11334 ls: add Polish translation; rar, sass, youtube-dl: fix typos
  pages.pl/common/ls.md
  pages.pl/common/rar.md
  pages.pl/common/sass.md
  pages.pl/common/youtube-dl.md
Labels: translation

#11350 unimatrix: add page
  pages/common/unimatrix.md
Labels: new command

#11357 javadoc: add Korean translation
  pages.ko/common/javadoc.md
Labels: translation

#11333 aa-complain: add German translation
  pages.de/linux/aa-complain.md
Labels: translation

#11298 common/*: add ps-nvm commands
  pages/common/get-nodeinstalllocation.md
  pages/common/get-nodeversions.md
  pages/common/install-nodeversion.md
  pages/common/ps-nvm.md
  pages/common/remove-nodeversion.md
  pages/common/set-nodeinstalllocation.md
  pages/common/set-nodeversion.md
Labels: new command

#11366 subcommand-mention: add Polish translation
  contributing-guides/translation-templates/subcommand-mention.md
Labels: documentation

#11362 machine: add Spanish translation
  pages.es/osx/machine.md
Labels: translation

#11364 mas: add Spanish translation
  pages.es/osx/mas.md
Labels: translation

#11368 linode-cli-volumes: fix typo
  pages/common/linode-cli-volumes.md
Labels: page edit

#11367 linode-cli: fix typo
  pages/common/linode-cli.md
Labels: page edit

#11369 README: update Homebrew client to Rust client `tlrc`
  README.md
Labels: documentation

#11372 cli53: fix missing curly brace
  pages/common/cli53.md
Labels: page edit

#11359 bun: add Chinese translation
  pages.zh/common/bun.md
Labels: translation

#11377 ps: add Spanish translation
  pages.es/osx/ps.md
Labels: translation

#11371 accelerate: add Korean translation
  pages.ko/common/accelerate.md
Labels: translation

#11378 argocd, argocd-app: add Korean translation
  pages.ko/common/argocd-app.md
  pages.ko/common/argocd.md
Labels: translation

#11376 brew: update page; brew-*: add page; brew-cask: remove page
  pages/common/brew-autoremove.md
  pages/common/brew-cask.md
  pages/common/brew-install.md
  pages/common/brew-uninstall.md
  pages/common/brew.md
Labels: page edit, new command

#11380 eyuvtoppm, ppmtoeyuv, ppmtoyuv, ppmtoyufsplitm, yuvsplittoppm, yuvtoppm: add pages
  pages/common/eyuvtoppm.md
  pages/common/ppmtoeyuv.md
  pages/common/ppmtoyuv.md
  pages/common/ppmtoyuvsplit.md
  pages/common/yuvsplittoppm.md
  pages/common/yuvtoppm.md
Labels: new command

#11379 pamdepth, ppmdither, pamditherbw, pnmdepth: add pages
  pages/common/pamdepth.md
  pages/common/pamditherbw.md
  pages/common/pnmdepth.md
  pages/common/ppmdither.md
Labels: new command

#11375 rsync: update page
  pages/common/rsync.md
Labels: page edit

#11382 brew-cask: remove page
  pages.de/common/brew-cask.md
  pages.fr/common/brew-cask.md
  pages.it/common/brew-cask.md
  pages.zh/common/brew-cask.md
Labels: translation

#11384 apktool: add Korean translation
  pages.ko/common/apktool.md
Labels: translation

#11389 brew-{update,upgrade,list,outdated,search}: add page
  pages/common/brew-list.md
  pages/common/brew-outdated.md
  pages/common/brew-search.md
  pages/common/brew-update.md
  pages/common/brew-upgrade.md
Labels: new command

#11392 gcloud: add Spanish translation
  pages.es/common/gcloud.md
Labels: translation

#11398 systemd-nspawn: add page
  pages/linux/systemd-nspawn.md
Labels: new command

#11399 wl-copy: add image copying example
  pages/linux/wl-copy.md
Labels: page edit

#11400 btop: add Spanish translation
  pages.es/common/btop.md
Labels: translation

#11401 pamtoqoi, pbmtozinc, ppmtoarbtxt, qoitopam, rawtopgm, rawtoppm: add pages
  pages/common/pamtoqoi.md
  pages/common/pbmtozinc.md
  pages/common/ppmtoarbtxt.md
  pages/common/qoitopam.md
  pages/common/rawtopgm.md
  pages/common/rawtoppm.md
Labels: new command

#11402 gemtopbm, gemtopnm, pamtotga, ppmtotga, tgatoppm: add pages
  pages/common/gemtopbm.md
  pages/common/gemtopnm.md
  pages/common/pamtotga.md
  pages/common/ppmtotga.md
  pages/common/tgatoppm.md
Labels: new command

#11403 pamnoraw, pamtopam, pamtopnm, pnmtoplainpnm, pnmtopnm, ppmtoppm: add pages
  pages/common/pamnoraw.md
  pages/common/pamtopam.md
  pages/common/pamtopnm.md
  pages/common/pnmtoplainpnm.md
  pages/common/pnmtopnm.md
  pages/common/ppmtoppm.md
Labels: new command

#11411 bugreportz: add Korean translation
  pages.ko/android/bugreportz.md
Labels: translation

#11406 pamtoxvmini, pbmtoybm, pnmtoxwd, xvminitoppm, xwdtopnm, ybmtopbm: add pages
  pages/common/pamtoxvmini.md
  pages/common/pbmtoybm.md
  pages/common/pnmtoxwd.md
  pages/common/xvminitoppm.md
  pages/common/xwdtopnm.md
  pages/common/ybmtopbm.md
Labels: new command

#11409 pbmtolj, pjtoppm, pnmtopclxl, ppmtolj, ppmtopj, ppmtospu, sldtoppm, spctoppm, sputoppm, thinkjettopbm: add pages
  pages/common/pbmtolj.md
  pages/common/pjtoppm.md
  pages/common/pnmtopclxl.md
  pages/common/ppmtolj.md
  pages/common/ppmtopj.md
  pages/common/ppmtospu.md
  pages/common/sldtoppm.md
  pages/common/spctoppm.md
  pages/common/sputoppm.md
  pages/common/thinkjettopbm.md
Labels: new command

#11423 cmd: add Korean translation
  pages.ko/android/cmd.md
Labels: translation

#11414 systemd-dissect: add page
  pages/linux/systemd-dissect.md
Labels: new command

#11424 amass-track, amass-viz: remove page
  pages.es/common/amass-track.md
  pages.es/common/amass-viz.md
  pages.fr/common/amass-track.md
  pages.fr/common/amass-viz.md
  pages/common/amass-track.md
  pages/common/amass-viz.md
Labels: page edit, translation

#11418 amass-intel: add Dutch translation
  pages.nl/common/amass-intel.md
Labels: translation

#11417 amass-enum: add Dutch translation
  pages.nl/common/amass-enum.md
Labels: translation

#11415 amass: add Dutch translation
  pages.nl/common/amass.md
Labels: translation

#11416 amass-db: add Dutch translation
  pages.nl/common/amass-db.md
Labels: translation

#11428 pages.pl/*: add links
  pages.pl/common/azure-cli.md
  pages.pl/common/docker-container-diff.md
  pages.pl/common/docker-container-remove.md
  pages.pl/common/docker-container-rename.md
  pages.pl/common/docker-container-rm.md
  pages.pl/common/docker-container-top.md
  pages.pl/common/git-stage.md
  pages.pl/common/hd.md
  pages.pl/common/hping.md
Labels: translation

#11429 !: fix typo in German translation
  pages.de/common/!.md
Labels: translation, minor change

#11434 unp: add page
  pages/common/unp.md
Labels: new command

#11436 ps-nvm: fix typo
  pages/common/ps-nvm.md
Labels: page edit

#11430 CI/codespell: ignore non-English pages
  .github/workflows/codespell.yml
Labels: tooling

#11432 ilbmtoppm, pcxtoppm, ppmtoilbm, ppmtoleaf, ppmtomitsu, ppmtompeg, ppmtoneo, ppmtopcx: add pages
  pages/common/ilbmtoppm.md
  pages/common/pcxtoppm.md
  pages/common/ppmtoilbm.md
  pages/common/ppmtoleaf.md
  pages/common/ppmtomitsu.md
  pages/common/ppmtompeg.md
  pages/common/ppmtoneo.md
  pages/common/ppmtopcx.md
Labels: new command

#11433 pamoil, pgmbentley, pgmdeshadow, pgmoil, ppmrainbow, ppmrelief, ppmshadow, ppmshift, ppmspread, ppmtoacad, ppmtobmp, ppmtoicr: add pages
  pages/common/pamoil.md
  pages/common/pgmbentley.md
  pages/common/pgmdeshadow.md
  pages/common/pgmoil.md
  pages/common/ppmrainbow.md
  pages/common/ppmrelief.md
  pages/common/ppmshadow.md
  pages/common/ppmshift.md
  pages/common/ppmspread.md
  pages/common/ppmtoacad.md
  pages/common/ppmtobmp.md
  pages/common/ppmtoicr.md
Labels: new command

#11439 dalvikvm: add Korean translation
  pages.ko/android/dalvikvm.md
Labels: translation

#11427 linux/*: add Dutch translation
  pages.nl/linux/apport-bug.md
  pages.nl/linux/cal.md
  pages.nl/linux/cgcreate.md
  pages.nl/linux/cgexec.md
  pages.nl/linux/ip-route-show.md
  pages.nl/linux/megatools-dl.md
  pages.nl/linux/update-alternatives.md
Labels: page edit, new command, tooling, translation

#11453 dumpsys: add Korean translation
  pages.ko/android/dumpsys.md
Labels: translation

#11446 anki: add Dutch translation
  pages.nl/common/anki.md
Labels: translation

#11444 ani-cli: add Dutch translation
  pages.nl/common/ani-cli.md
Labels: translation

#11443 androguard: add Dutch translation
  pages.nl/common/androguard.md
Labels: translation

#11447 systemd-machine-id-setup: add page
  pages/linux/systemd-machine-id-setup.md
Labels: new command

#11458 rlogin: add page
  pages/linux/rlogin.md
Labels: new command

#11456 rcp: add page
  pages/linux/rcp.md
Labels: new command

#11451 !: add Spanish translation, fix placeholder in description
  pages.bn/common/!.md
  pages.de/common/!.md
  pages.es/common/!.md
  pages.hi/common/!.md
  pages.it/common/!.md
  pages.nl/common/!.md
  pages.pt_BR/common/!.md
  pages/common/!.md
Labels: page edit, translation

#11457 rexec: add page
  pages/linux/rexec.md
Labels: new command

#11459 rsh: add page
  pages/linux/rsh.md
Labels: new command

#11450 dnsdomainname: add page
  pages/linux/dnsdomainname.md
Labels: new command

#11462 pages*: remove curly braces from example descriptions
  pages.ca/linux/i3.md
  pages.de/common/!.md
  pages.es/linux/i3.md
  pages.es/osx/whence.md
  pages.fr/common/ghdl.md
  pages.fr/common/nano.md
  pages.it/common/bedtools.md
  pages.it/linux/i3.md
  pages.ja/linux/whatis.md
  pages.ko/common/bedtools.md
  pages.ru/common/cut.md
  pages.ru/osx/cut.md
  pages.zh/linux/cryptsetup.md
  pages.zh/linux/i3.md
  pages/common/!.md
  pages/common/bedtools.md
  pages/common/dep.md
  pages/common/ghdl.md
  pages/common/mosh.md
  pages/common/samtools.md
  pages/common/swig.md
  pages/linux/cryptsetup.md
  pages/linux/i3.md
  pages/linux/lsns.md
  pages/linux/ostree.md
  pages/linux/setcap.md
  pages/linux/uvcdynctrl.md
  pages/linux/whatis.md
  pages/osx/whence.md
Labels: page edit, mass changes, translation

#11461 tar: fix grammatical errors in the German translation
  pages.de/common/tar.md
Labels: page edit, translation

#11466 adb-logcat: add Indonesian translation; adb-install: update Indonesian translation
  pages.id/common/adb-install.md
  pages.id/common/adb-logcat.md
Labels: translation

#11467 cd: update Indonesian translation; set-location: add Indonesian translation
  pages.id/common/cd.md
  pages.id/windows/cd.md
  pages.id/windows/set-location.md
  pages.id/windows/sl.md
Labels: translation

#11441 deno: add Chinese translation
  pages.zh/common/deno.md
Labels: translation

#11465 powershell, pwsh, windows/*: fix PowerShell conventions
  pages.ar/windows/sls.md
  pages.bs/windows/sls.md
  pages.ca/windows/sls.md
  pages.da/windows/sls.md
  pages.de/windows/sls.md
  pages.es/windows/sls.md
  pages.fr/windows/sls.md
  pages.hi/windows/add-appxpackage.md
  pages.hi/windows/sls.md
  pages.id/windows/sls.md
  pages.it/windows/sls.md
  pages.ja/windows/sls.md
  pages.ko/windows/sls.md
  pages.lo/windows/sls.md
  pages.ml/windows/sls.md
  pages.ne/windows/sls.md
  pages.nl/windows/remove-item.md
  pages.nl/windows/sls.md
  pages.no/windows/sls.md
  pages.pl/windows/sls.md
  pages.pt_BR/windows/sls.md
  pages.pt_PT/windows/sls.md
  pages.ru/windows/sls.md
  pages.sv/windows/sls.md
  pages.ta/windows/sls.md
  pages.th/windows/sls.md
  pages.tr/windows/sls.md
  pages.uk/windows/sls.md
  pages.zh/windows/sls.md
  pages.zh_TW/windows/sls.md
  pages/common/powershell.md
  pages/common/pwsh.md
  pages/windows/add-appxpackage.md
  pages/windows/powershell.md
  pages/windows/remove-appxpackage.md
  pages/windows/remove-item.md
  pages/windows/sls.md
Labels: page edit, new command, mass changes, translation

#11475 set-location: fix tldr-lint issue
  pages.id/windows/set-location.md
Labels: translation, minor change

#11476 pkgin: fix more info link
  pages.id/netbsd/pkgin.md
Labels: translation

#11477 scripts: make set-alias-page.py runnable
  scripts/set-alias-page.py
Labels: tooling

#11454 libtool: add page
  pages/linux/libtool.md
Labels: new command

#11485 b2sum: fix typo in Tamil translation
  pages.ta/common/b2sum.md
Labels: translation, minor change

#11481 ansible: add Dutch translation
  pages.nl/common/ansible.md
Labels: translation

#11487 kdesrc-build, kdesrc-run: add page
  pages/linux/kdesrc-build.md
  pages/linux/kdesrc-run.md
Labels: new command

#11484 input: add Korean translation
  pages.ko/android/input.md
Labels: translation

#10844 screencap: add German translation
  pages.de/android/screencap.md
Labels: translation, hacktoberfest-accepted

#11479 systemd-confext: add page
  pages/linux/systemd-confext.md
Labels: new command

#11483 pod: add Spanish translation
  pages.es/osx/pod.md
Labels: translation

#11486 scripts/test.sh: remove TLDR005 from ignore list for languages
  scripts/test.sh
Labels: tooling

#11500 CI/codespell: ignore subfolders
  .github/workflows/codespell.yml
Labels: tooling, minor change

#11491 pages.ta: fix outdated translations
  pages.ta/common/cargo-doc.md
  pages.ta/common/cargo-test.md
  pages.ta/common/g++.md
  pages.ta/common/gcc.md
  pages.ta/common/git-apply.md
  pages.ta/common/git-cherry-pick.md
  pages.ta/common/git-clone.md
  pages.ta/common/git-commit.md
  pages.ta/common/grep.md
  pages.ta/common/md5sum.md
  pages.ta/common/mkdir.md
  pages.ta/common/podman.md
  pages.ta/common/powershell.md
  pages.ta/common/ruby.md
  pages.ta/linux/apx.md
  pages.ta/linux/flatpak.md
  pages.ta/linux/pacman-deptest.md
  pages.ta/linux/pacman-key.md
  pages.ta/linux/pacman-sync.md
  pages.ta/linux/pacman.md
  pages.ta/sunos/prstat.md
  pages.ta/windows/choco-new.md
  pages.ta/windows/cmd.md
  pages.ta/windows/dir.md
  pages.ta/windows/wget.md
Labels: translation, review needed

#11493 logcat: add Korean translation
  pages.ko/android/logcat.md
Labels: translation

#11507 pages/*: reword descriptions to comply with the style guide
  pages/common/accelerate.md
  pages/common/aws-codecommit.md
  pages/common/bq.md
  pages/common/cbonsai.md
  pages/common/colordiff.md
  pages/common/cron.md
  pages/common/daps.md
  pages/common/dolt.md
  pages/common/git-check-ref-format.md
  pages/common/gradle.md
  pages/common/helm.md
  pages/common/holehe.md
  pages/common/keytool.md
  pages/common/kiwi-ng.md
  pages/common/kustomize.md
  pages/common/ledger.md
  pages/common/lzip.md
  pages/common/micro.md
  pages/common/mix.md
  pages/common/mupdf.md
  pages/common/nc.md
  pages/common/nyxt.md
  pages/common/octave.md
  pages/common/passwd.md
  pages/common/pinta.md
  pages/common/postcss.md
  pages/common/sails.md
  pages/common/sf.md
  pages/common/sonar-scanner.md
  pages/common/soupault.md
  pages/common/timidity.md
  pages/common/transmission.md
  pages/common/vifm.md
  pages/linux/addpart.md
  pages/linux/cpupower.md
  pages/linux/curlie.md
  pages/linux/duc.md
  pages/linux/dunstify.md
  pages/linux/libtool.md
  pages/linux/lvcreate.md
  pages/linux/retroarch.md
  pages/linux/startx.md
  pages/linux/systemd-confext.md
  pages/linux/talk.md
  pages/linux/vmware-checkvm.md
  pages/linux/zile.md
  pages/osx/photoanalysisd.md
  pages/windows/test-json.md
Labels: page edit, mass changes

#11513 pages.ta: fix outdated translation, linter errors
  pages.ta/common/cargo-doc.md
  pages.ta/common/g++.md
  pages.ta/common/gcc.md
  pages.ta/common/md5sum.md
  pages.ta/common/ruby.md
  pages.ta/linux/flatpak.md
  pages.ta/windows/cmd.md
Labels: translation

#11469 subcommand-mention: add translations
  contributing-guides/translation-templates/subcommand-mention.md
Labels: documentation

#11516 style-guide: fix typo
  contributing-guides/style-guide.md
Labels: documentation

#11515 CI/codespell: skip non-English pages
  .github/workflows/codespell.yml
Labels: tooling

#11528 a2ping: fix typo
  pages/common/a2ping.md
Labels: page edit, minor change

#11527 screencap, settings, wm: add Korean translation
  pages.ko/android/screencap.md
  pages.ko/android/settings.md
  pages.ko/android/wm.md
Labels: translation

#11531 anki, anytopnm, argocd: add French translation
  pages.fr/common/anki.md
  pages.fr/common/anytopnm.md
  pages.fr/common/argocd.md
Labels: translation

#10730 CLIENT-SPECIFICATION: fix typo, add a way to escape the placeholder syntax
  CLIENT-SPECIFICATION.md
Labels: documentation, clients, review needed

#11525 check-pr: use better regex
  scripts/check-pr.sh
Labels: tooling

#11533 swaybg: add page
  pages/linux/swaybg.md
Labels: new command

#11537 test: skip symlinked English folder and optimise the script
  scripts/test.sh
Labels: tooling

#11540 tldr: update page
  pages/common/tldr.md
Labels: page edit

#11541 keepassxc-cli: replace invalid `lookup` command with `search`
  pages/common/keepassxc-cli.md
Labels: page edit

#11539 anytopnm: add Korean translation
  pages.ko/common/anytopnm.md
Labels: translation

#10851 curl, open, powershell, wget: remove "view in older versions of `tldr`"
  pages.bn/windows/curl.md
  pages.id/common/open.md
  pages.id/windows/curl.md
  pages.id/windows/wget.md
  pages.nl/common/open.md
  pages.nl/common/powershell.md
  pages.nl/windows/curl.md
  pages.nl/windows/wget.md
  pages.ta/common/powershell.md
  pages.ta/windows/curl.md
  pages.ta/windows/wget.md
  pages/common/open.md
  pages/common/powershell.md
  pages/windows/curl.md
  pages/windows/wget.md
Labels: page edit, mass changes, translation, hacktoberfest-accepted

#11551 bb: add Korean translation
  pages.ko/common/bb.md
Labels: translation

#11552 tldr: update Polish translation
  pages.pl/common/tldr.md
Labels: translation

#11553 lvextend: fix typo, update link
  pages/linux/lvextend.md
Labels: page edit, minor change

#11557 mysides: add Spanish translation
  pages.es/osx/mysides.md
Labels: translation

#11535 hut: add page
  pages/common/hut.md
Labels: new command

#11554 MAINTAINERS, CODEOWNERS: remove @marchersimon from Org
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: community

#11561 docker-{pull,rename,rm}: add French translation
  pages.fr/common/docker-pull.md
  pages.fr/common/docker-rename.md
  pages.fr/common/docker-rm.md
Labels: translation

#11556 case: update Japanese translation
  pages.ja/common/case.md
Labels: translation, minor change

#11566 django-admin: update link
  pages.ko/common/django-admin.md
  pages/common/django-admin.md
Labels: page edit, translation

#11575 ani-cli: fix flag for episode selection
  pages.de/common/ani-cli.md
  pages.es/common/ani-cli.md
  pages.fr/common/ani-cli.md
  pages.ml/common/ani-cli.md
  pages.nl/common/ani-cli.md
  pages.zh/common/ani-cli.md
  pages/common/ani-cli.md
Labels: page edit, translation

#11564 scutil: add Spanish translation
  pages.es/osx/scutil.md
Labels: translation

#11563 systemsoundserverd: add Spanish translation
  pages.es/osx/systemsoundserverd.md
Labels: translation

#11571 fossil-*: add Dutch translation
  pages.nl/common/fossil-add.md
  pages.nl/common/fossil-commit.md
  pages.nl/common/fossil-init.md
  pages.nl/common/fossil-rm.md
  pages.nl/common/fossil.md
  pages/common/fossil-rm.md
Labels: page edit, translation

#11532 ffsend: add Chinese translation
  pages.zh/common/ffsend.md
Labels: translation

#11548 tldr: add Tamil translation
  pages.ta/common/tldr.md
Labels: translation

#11572 pages/*: align "See also:" lines
  pages/common/docker-image.md
  pages/common/f3fix.md
  pages/common/f3probe.md
  pages/common/f3read.md
  pages/common/f3write.md
  pages/common/nvim.md
  pages/common/podman-image.md
  pages/common/vim.md
  pages/common/vimdiff.md
  pages/common/vimtutor.md
  pages/linux/lrunzip.md
  pages/linux/lrzip.md
  pages/linux/openrc.md
  pages/linux/vgscan.md
Labels: page edit

#11577 aws-eks: add page
  pages/common/aws-eks.md
Labels: new command

#11570 aws-dynamodb: add page
  pages/common/aws-dynamodb.md
Labels: new command

#11555 ncu: add use cases, use long options
  pages/common/ncu.md
Labels: page edit

#11583 asciitopgm: add Korean translation
  pages.ko/common/asciitopgm.md
Labels: translation

#11588 systemd-id128: fix typo; systemd-cryptenroll: update page
  pages/linux/systemd-cryptenroll.md
  pages/linux/systemd-id128.md
Labels: page edit

#11587 say: add Spanish translation
  pages.es/osx/say.md
Labels: translation

#11589 fish: add Chinese translation
  pages.zh/common/fish.md
Labels: translation

#11590 ollama: add page
  pages/common/ollama.md
Labels: new command

#11445 sg: add page
  pages/common/sg.md
Labels: new command

#11592 airportd: add Spanish translation
  pages.es/osx/airportd.md
Labels: translation

#11594 automountd: add Spanish translation
  pages.es/osx/automountd.md
Labels: translation

#11595 avbdeviced: add Spanish translation
  pages.es/osx/avbdeviced.md
Labels: translation

#11596 backupd: add Spanish translation
  pages.es/osx/backupd.md
Labels: translation

#11597 chatgpt: add page
  pages/linux/chatgpt.md
Labels: new command

#11599 arp-scan: add Korean translation
  pages.ko/common/arp-scan.md
Labels: translation

#11560 make: add pt_BR translation
  pages.pt_BR/common/make.md
Labels: translation

#11593 arch: add Spanish translation
  pages.es/osx/arch.md
  pages.pt_BR/osx/arch.md
  pages.pt_PT/osx/arch.md
  pages.zh/osx/arch.md
  pages/osx/arch.md
Labels: page edit, translation

#11565 exiqgrep: add page
  pages/linux/exiqgrep.md
Labels: new command

#11602 7zr: fix pt_PT translation
  pages.pt_PT/common/7zr.md
Labels: translation

#11598 vboxmanage-*: add page
  pages/common/vboxmanage-clonevm.md
  pages/common/vboxmanage-createvm.md
  pages/common/vboxmanage-export.md
  pages/common/vboxmanage-import.md
  pages/common/vboxmanage-registervm.md
  pages/common/vboxmanage-unregistervm.md
Labels: new command, mass changes

#11612 windows/*: add more PowerShell commands
  pages/windows/get-command.md
  pages/windows/get-help.md
  pages/windows/get-wuapiversion.md
  pages/windows/get-wuhistory.md
  pages/windows/get-wusettings.md
  pages/windows/install-module.md
  pages/windows/pswindowsupdate.md
Labels: page edit, new command

#11610 dotnet-publish: fix typo
  pages.es/common/dotnet-publish.md
Labels: translation

#11604 vboxmanage-*, exiqgrep: update page
  pages/common/vboxmanage-clonevm.md
  pages/common/vboxmanage-export.md
  pages/common/vboxmanage-import.md
  pages/common/vboxmanage-unregistervm.md
  pages/linux/exiqgrep.md
Labels: page edit

#11609 dotnet-restore: fix typos in Spanish translation
  pages.es/common/dotnet-restore.md
Labels: translation
