Repository tldr-pages/tldr, pull requests merged in 2024-06, with the labels that each got.

#12856 sed: add Chinese translation
  pages.zh/linux/sed.md
Labels: translation

#12863 zint: add page
  pages/common/zint.md
Labels: new command

#12868 toipe: add page
  pages/common/toipe.md
Labels: new command

#12870 MAINTAINERS: add @spageektti to Org
  MAINTAINERS.md
Labels: community

#12872 waybar: add page
  pages/common/waybar.md
Labels: new command

#12880 toipe: add example
  pages/common/toipe.md
Labels: page edit

#12876 waybar: add Spanish translation
  pages.es/common/waybar.md
Labels: translation

#12879 rsync: update page
  pages.fr/common/rsync.md
  pages.id/common/rsync.md
  pages.ko/common/rsync.md
  pages.pl/common/rsync.md
  pages.pt_BR/common/rsync.md
  pages.zh/common/rsync.md
  pages/common/rsync.md
Labels: page edit, translation

#12878 jf, pam*,pbmtosunicon, pcdovtoppm, pngtopam, pnm*, ruff-*, sunicontopnm: add Dutch translation, pcdovtoppm: fix typo
  pages.es/common/pcdovtoppm.md
  pages.nl/common/adscript.md
  pages.nl/common/base32.md
  pages.nl/common/base64.md
  pages.nl/common/clang++.md
  pages.nl/common/gcc.md
  pages.nl/common/jf.md
  pages.nl/common/pamarith.md
  pages.nl/common/pambrighten.md
  pages.nl/common/pamcomp.md
  pages.nl/common/pamcrater.md
  pages.nl/common/pamcut.md
  pages.nl/common/pamditherbw.md
  pages.nl/common/pamedge.md
  pages.nl/common/pamenlarge.md
  pages.nl/common/pamfile.md
  pages.nl/common/pamfix.md
  pages.nl/common/pamflip.md
  pages.nl/common/pamscale.md
  pages.nl/common/pamshadedrelief.md
  pages.nl/common/pamslice.md
  pages.nl/common/pamsplit.md
  pages.nl/common/pamstretch.md
  pages.nl/common/pamtofits.md
  pages.nl/common/pamtogif.md
  pages.nl/common/pamtopng.md
  pages.nl/common/pamtopnm.md
  pages.nl/common/pamtouil.md
  pages.nl/common/pbmtosunicon.md
  pages.nl/common/pbmtoxbm.md
  pages.nl/common/pcdovtoppm.md
  pages.nl/common/pngtopam.md
  pages.nl/common/pnmnorm.md
  pages.nl/common/pnmquantall.md
  pages.nl/common/pnmtojpeg.md
  pages.nl/common/ruff-check.md
  pages.nl/common/ruff-format.md
  pages.nl/common/sunicontopnm.md
  pages.nl/common/visudo.md
  pages.nl/osx/sed.md
  pages/common/pamfix.md
  pages/common/pcdovtoppm.md
Labels: page edit, translation

#12874 imagemagick: update pages
  pages/common/compare.md
  pages/common/convert.md
  pages/common/identify.md
  pages/common/import.md
  pages/common/magick-compare.md
  pages/common/magick-convert.md
  pages/common/magick-identify.md
  pages/common/magick-import.md
  pages/common/magick-mogrify.md
  pages/common/magick-montage.md
  pages/common/magick.md
  pages/common/mogrify.md
  pages/common/montage.md
Labels: page edit, new command

#12354 pages*: make "See also" conform to the new syntax (#12756)
  pages/common/age-keygen.md
  pages/common/age.md
  pages/common/apm.md
  pages/common/git-fsck.md
  pages/common/nix-build.md
  pages/common/nix-shell.md
  pages/common/nix-store.md
  pages/common/nix3-build.md
  pages/common/nix3-registry.md
  pages/common/nix3-run.md
  pages/common/nix3-search.md
  pages/common/nix3-shell.md
  pages/common/nix3-store.md
  pages/linux/mount.ddi.md
  pages/linux/setcap.md
Labels: page edit

#12883 pw-dot: update page
  pages/linux/pw-dot.md
Labels: page edit

#12884 pw-metadata: add page
  pages/linux/pw-metadata.md
Labels: new command

#12888 mpv: fix typo
  pages/common/mpv.md
Labels: page edit

#12887 compare, convert: rename to `magick-{compare,convert}`
  pages.de/common/magick-compare.md
  pages.de/common/magick-convert.md
  pages.fa/common/magick-compare.md
  pages.fr/common/magick-convert.md
  pages.hi/common/magick-compare.md
  pages.it/common/magick-convert.md
  pages.ko/common/convert.md
  pages.ko/common/magick-convert.md
  pages.pt_BR/common/magick-convert.md
Labels: translation

#12885 typeinc: add page
  pages/common/typeinc.md
Labels: new command

#12580 yt-dlp: update page
  pages/common/yt-dlp.md
Labels: page edit

#12891 cleanup: remove URL theme fragment from console image
  README.md
Labels: documentation

#12862 devenv: add page
  pages/common/devenv.md
Labels: new command

#12892 gzip: update page
  pages/common/gzip.md
Labels: page edit

#12881 audtool: add page
  pages/common/audtool.md
Labels: new command

#12896 ansible-playbook: add dryrun --check --diff example
  pages/common/ansible-playbook.md
Labels: page edit

#12899 audtool: add Spanish translation
  pages.es/common/audtool.md
Labels: translation

#12902 style-guide: fix typos
  contributing-guides/style-guide.md
Labels: documentation

#12901 grep: update page
  pages/common/grep.md
Labels: page edit

#12903 magick: update and add alias pages for Dutch
  pages.nl/common/compare.md
  pages.nl/common/convert.md
  pages.nl/common/identify.md
  pages.nl/common/import.md
  pages.nl/common/magick.md
  pages.nl/common/mogrify.md
  pages.nl/common/montage.md
Labels: translation

#12904 style-guide, pages/windows/*: add note for PowerShell descriptions
  contributing-guides/style-guide.md
  pages/windows/clear-host.md
  pages/windows/get-acl.md
  pages/windows/get-childitem.md
  pages/windows/get-content.md
  pages/windows/get-date.md
  pages/windows/get-filehash.md
  pages/windows/get-history.md
  pages/windows/invoke-item.md
  pages/windows/invoke-webrequest.md
  pages/windows/measure-command.md
  pages/windows/measure-object.md
  pages/windows/new-item.md
  pages/windows/out-string.md
  pages/windows/resolve-path.md
  pages/windows/select-string.md
  pages/windows/set-acl.md
  pages/windows/set-date.md
  pages/windows/set-location.md
  pages/windows/set-service.md
  pages/windows/show-markdown.md
  pages/windows/sort-object.md
  pages/windows/start-service.md
  pages/windows/stop-service.md
  pages/windows/tee-object.md
  pages/windows/test-json.md
  pages/windows/test-netconnection.md
  pages/windows/wait-process.md
  pages/windows/where-object.md
Labels: documentation, page edit

#12908 grep: fix typo in Spanish translation
  pages.es/common/grep.md
Labels: documentation, translation

#12861 hledger-balance: add Spanish translation
  pages.es/common/hledger-balance.md
Labels: translation

#12831 set-volume, enable-pnpdevice, get-dedupproperties: add pages
  pages/windows/enable-pnpdevice.md
  pages/windows/get-dedupproperties.md
  pages/windows/set-volume.md
Labels: new command

#12909 magick-*: add Dutch translation
  pages.nl/common/magick-compare.md
  pages.nl/common/magick-convert.md
  pages.nl/common/magick-identify.md
  pages.nl/common/magick-import.md
  pages.nl/common/magick-mogrify.md
  pages.nl/common/magick-montage.md
Labels: translation

#12913 magick-convert: fix typo
  pages.nl/common/magick-convert.md
  pages/common/magick-convert.md
Labels: page edit, translation

#12910 date: add Dutch translation and fix typo's
  pages.id/osx/date.md
  pages.ko/osx/date.md
  pages.nl/common/date.md
  pages.nl/osx/date.md
  pages.nl/windows/date.md
  pages.pl/osx/date.md
  pages.pt_BR/osx/date.md
  pages.zh/osx/date.md
  pages/osx/date.md
Labels: page edit, translation

#12900 typeinc: add Spanish translation, update page
  pages.es/common/typeinc.md
  pages/common/typeinc.md
Labels: page edit, translation

#12905 pwd, touch, mv, mkdir, rmdir, find, exa, eza, cat: add and update Korean translation
  pages.ko/common/cat.md
  pages.ko/common/exa.md
  pages.ko/common/eza.md
  pages.ko/common/find.md
  pages.ko/common/mkdir.md
  pages.ko/common/mv.md
  pages.ko/common/rmdir.md
  pages.ko/common/touch.md
  pages.ko/linux/pwd.md
Labels: translation, review needed

#12895 pacman*, pacman4console, yay, yaourt: add Korean translation
  pages.ko/linux/pacman-database.md
  pages.ko/linux/pacman-deptest.md
  pages.ko/linux/pacman-files.md
  pages.ko/linux/pacman-key.md
  pages.ko/linux/pacman-mirrors.md
  pages.ko/linux/pacman-query.md
  pages.ko/linux/pacman-remove.md
  pages.ko/linux/pacman-sync.md
  pages.ko/linux/pacman-upgrade.md
  pages.ko/linux/pacman.md
  pages.ko/linux/pacman4console.md
  pages.ko/linux/yaourt.md
  pages.ko/linux/yay.md
Labels: translation, review needed

#12915 rkdeveloptool: add new command
  pages/common/rkdeveloptool.md
Labels: new command

#12906 neo4j-admin: add page
  pages/common/neo4j-admin.md
Labels: new command

#12920 git-contrib: fix grammar
  pages/common/git-contrib.md
Labels: page edit, minor change

#12926 dd: update Spanish translation
  pages.es/osx/dd.md
Labels: translation

#12927 abbr: fix Spanish translation
  pages.es/linux/abbr.md
Labels: translation

#12923 pages*: add `/dev` to the placeholder
  pages.pt_BR/common/mpv.md
  pages.zh/common/mpv.md
  pages.zh/linux/blkdiscard.md
  pages/common/dcfldd.md
  pages/common/mpv.md
  pages/common/qemu.md
  pages/linux/blkdiscard.md
  pages/linux/hdparm.md
  pages/linux/losetup.md
  pages/linux/mlabel.md
  pages/linux/wodim.md
  pages/linux/zbarcam.md
Labels: page edit, translation

#12924 amass, amass-enum, amass-intel, androguard, ani-cli, anki: add Indonesian translation
  pages.id/common/amass-enum.md
  pages.id/common/amass-intel.md
  pages.id/common/amass.md
  pages.id/common/androguard.md
  pages.id/common/ani-cli.md
  pages.id/common/anki.md
Labels: translation

#12930 agetty: fix Spanish translation
  pages.es/linux/agetty.md
Labels: translation

#12917 turbostat: add Spanish translation
  pages.es/linux/turbostat.md
Labels: translation

#12933 ^: add Dutch translation
  pages.nl/common/^.md
Labels: translation

#12932 look: add Dutch translation, fix typos
  pages.es/freebsd/look.md
  pages.nl/common/look.md
  pages.nl/freebsd/look.md
  pages.nl/linux/look.md
  pages.nl/osx/look.md
  pages/freebsd/look.md
  pages/linux/look.md
  pages/osx/look.md
Labels: page edit, translation

#12944 ansiweather, apkleaks: use imperative descriptions
  pages/common/ansiweather.md
  pages/common/apkleaks.md
Labels: page edit

#12937 git-*: add and update Korean translation
  pages.ko/common/git-add.md
  pages.ko/common/git-bisect.md
  pages.ko/common/git-branch.md
  pages.ko/common/git-checkout.md
  pages.ko/common/git-clone.md
  pages.ko/common/git-commit.md
  pages.ko/common/git-diff.md
  pages.ko/common/git-fetch.md
  pages.ko/common/git-grep.md
  pages.ko/common/git-init.md
  pages.ko/common/git-log.md
  pages.ko/common/git-merge.md
  pages.ko/common/git-mv.md
  pages.ko/common/git-pull.md
  pages.ko/common/git-push.md
  pages.ko/common/git-rebase.md
  pages.ko/common/git-reset.md
  pages.ko/common/git-restore.md
  pages.ko/common/git-rm.md
  pages.ko/common/git-show.md
  pages.ko/common/git-status.md
  pages.ko/common/git-switch.md
  pages.ko/common/git-tag.md
Labels: translation

#12931 cal: add Dutch translation, gcal: add Dutch translation, fix placeholders
  pages.nl/common/cal.md
  pages.nl/common/gcal.md
  pages.nl/freebsd/cal.md
  pages.nl/netbsd/cal.md
  pages.nl/openbsd/cal.md
  pages.nl/osx/cal.md
  pages.pt_BR/common/gcal.md
  pages/common/gcal.md
Labels: page edit, translation

#12934 kill: fix highlighting long and short options according to guideline
  pages/linux/kill.md
Labels: page edit, minor change

#12941 brew, brew-*: add Indonesian translation
  pages.id/common/brew-autoremove.md
  pages.id/common/brew-bundle.md
  pages.id/common/brew-install.md
  pages.id/common/brew.md
Labels: translation

#12940 ansible, ansible-*: add Indonesian translation
  pages.id/common/ansible-doc.md
  pages.id/common/ansible-galaxy.md
  pages.id/common/ansible-inventory.md
  pages.id/common/ansible-playbook.md
  pages.id/common/ansible-pull.md
  pages.id/common/ansible-vault.md
  pages.id/common/ansible.md
Labels: translation

#12936 pages*: remove mnemonics when highlighting both long and short options
  pages.es/common/pydocstyle.md
  pages.es/linux/agetty.md
  pages.es/linux/blkpr.md
  pages.es/linux/showkey.md
  pages/common/azurite.md
  pages/common/diff.md
  pages/common/git-archive.md
  pages/common/pydocstyle.md
  pages/linux/agetty.md
  pages/linux/blkpr.md
  pages/linux/pw-dot.md
  pages/linux/showkey.md
Labels: page edit, translation

#12935 kubectx: add 2 command examples
  pages/common/kubectx.md
Labels: page edit

#12947 kubectl-logs: add logs for deployment
  pages/common/kubectl-logs.md
Labels: page edit

#12951 gcal: fix Dutch translation
  pages.nl/common/gcal.md
Labels: translation

#12956 bc, dd, nc, sed, tree, yacc: update links
  pages/common/bc.md
  pages/common/dd.md
  pages/common/nc.md
  pages/common/sed.md
  pages/common/tree.md
  pages/common/yacc.md
Labels: page edit, minor change

#12957 bc: update translations
  pages.es/common/bc.md
  pages.fr/common/bc.md
  pages.it/common/bc.md
  pages.ja/common/bc.md
  pages.ko/common/bc.md
  pages.pt_BR/common/bc.md
  pages.zh/common/bc.md
Labels: page edit, translation, minor change

#12961 tree: update translations
  pages.es/common/tree.md
  pages.it/common/tree.md
  pages.pt_BR/common/tree.md
  pages.tr/common/tree.md
  pages.zh/common/tree.md
Labels: translation

#12960 sed: update translations
  pages.da/common/sed.md
  pages.ja/common/sed.md
  pages.ko/common/sed.md
  pages.nl/common/sed.md
Labels: translation

#12959 nc: update translations
  pages.es/common/nc.md
  pages.ko/common/nc.md
  pages.nl/common/nc.md
Labels: translation

#12958 dd: update translations
  pages.de/common/dd.md
  pages.fa/common/dd.md
  pages.it/common/dd.md
  pages.nl/common/dd.md
  pages.pt_BR/common/dd.md
Labels: translation

#12962 grep: update translations
  pages.da/common/grep.md
  pages.de/common/grep.md
  pages.es/common/grep.md
  pages.fa/common/grep.md
  pages.fr/common/grep.md
  pages.ko/common/grep.md
  pages.pt_BR/common/grep.md
  pages.ru/common/grep.md
  pages.ta/common/grep.md
  pages.tr/common/grep.md
  pages.zh/common/grep.md
Labels: translation

#12965 atom: update Polish translation
  pages.pl/common/atom.md
Labels: translation

#12945 frp, frpc, frps: add page
  pages/common/frp.md
  pages/common/frpc.md
  pages/common/frps.md
Labels: new command

#12966 autoflake: update Polish translation
  pages.pl/common/autoflake.md
Labels: translation

#12967 babel: update Polish translation
  pages.pl/common/babel.md
Labels: translation

#12968 dotnet: update Polish translation
  pages.pl/common/dotnet.md
Labels: translation

#12963 7z: update Polish translation
  pages.pl/common/7z.md
Labels: translation

#12973 ag, bash: update Polish translation
  pages.pl/common/ag.md
  pages.pl/common/bash.md
Labels: translation

#12972 mysql: update Polish translation
  pages.pl/common/mysql.md
Labels: translation

#12970 yes: update Polish translation
  pages.pl/common/yes.md
Labels: translation

#12969 7za: update Polish translation
  pages.pl/common/7za.md
Labels: translation

#12977 common/*, osx/arch: add Indonesian translation
  pages.id/common/ansiweather.md
  pages.id/common/ant.md
  pages.id/common/antibody.md
  pages.id/common/anytopnm.md
  pages.id/common/apg.md
  pages.id/common/apkleaks.md
  pages.id/common/apm.md
  pages.id/common/apropos.md
  pages.id/common/ar.md
  pages.id/common/arc.md
  pages.id/common/arch.md
  pages.id/common/archwiki-rs.md
  pages.id/osx/arch.md
Labels: translation

#12948 mkdir: add Farsi translation
  pages.fa/common/mkdir.md
Labels: translation

#12946 rkdeveloptool: add Spanish translation
  pages.es/common/rkdeveloptool.md
Labels: translation

#12971 yacc: add Spanish translation
  pages.es/common/yacc.md
Labels: translation

#12974 hyprctl: add page
  pages/linux/hyprctl.md
Labels: new command

#12978 htop: add Chinese translation
  pages.zh/common/htop.md
Labels: translation

#12979 frp, frpc, frps: add Dutch translation, fix typo’s
  pages.nl/common/frp.md
  pages.nl/common/frpc.md
  pages.nl/common/frps.md
  pages/common/frpc.md
  pages/common/frps.md
Labels: page edit, translation

#12983 dd: fix incorrect math
  pages.fa/linux/dd.md
  pages.ko/linux/dd.md
  pages.nl/linux/dd.md
  pages/linux/dd.md
Labels: page edit, translation

#12996 *: change `command line` to `command-line`
  CLIENT-SPECIFICATION.md
  contributing-guides/style-guide.md
  pages/common/crystal.md
  pages/common/immich-cli.md
  pages/common/jbang.md
  pages/common/mods.md
  pages/common/set.md
  pages/common/sf.md
  pages/common/vboxmanage-registervm.md
  pages/common/wfuzz.md
  pages/common/wikit.md
  pages/linux/grub-editenv.md
  pages/linux/navi.md
Labels: documentation, page edit

#12950 pw-metadata: add Spanish translation
  pages.es/linux/pw-metadata.md
Labels: translation

#13000 diff: update more information link
  pages.de/common/diff.md
  pages.fa/common/diff.md
  pages.fr/common/diff.md
  pages.it/common/diff.md
  pages.ko/common/diff.md
  pages.pl/common/diff.md
  pages.pt_BR/common/diff.md
  pages.tr/common/diff.md
  pages.zh_TW/common/diff.md
  pages/common/diff.md
Labels: page edit, translation

#12998 arc, arch: update Indonesian translation
  pages.id/common/arc.md
  pages.id/osx/arch.md
Labels: translation

#13011 lsns: update more information link
  pages/linux/lsns.md
Labels: page edit

#13010 lslogins: update more information link
  pages/linux/lslogins.md
Labels: page edit

#13009 ip-rule: update more information link
  pages.tr/linux/ip-rule.md
  pages/linux/ip-rule.md
Labels: page edit, translation

#13008 ip-link: update more information link
  pages.tr/linux/ip-link.md
  pages/linux/ip-link.md
Labels: page edit, translation

#13007 e2undo: update more information link
  pages/linux/e2undo.md
Labels: page edit

#13005 chrt: update more information link
  pages/linux/chrt.md
Labels: page edit

#13001 cypher-shell: add page
  pages/common/cypher-shell.md
Labels: new command

#12981 common: add Indonesian translation
  pages.id/common/arduino-builder.md
  pages.id/common/arduino.md
  pages.id/common/argocd-app.md
  pages.id/common/argocd.md
  pages.id/common/argon2.md
  pages.id/common/arp-scan.md
  pages.id/common/arp.md
  pages.id/common/arping.md
Labels: translation

#13012 expand: add Dutch translation
  pages.nl/common/expand.md
  pages.nl/windows/expand.md
Labels: translation

#13014 ed: add Dutch translation
  pages.nl/common/ed.md
  pages.nl/osx/ed.md
Labels: translation

#13013 expr: add Dutch translation
  pages.nl/common/expr.md
Labels: translation

#13053 man: update more information link
  pages.it/common/man.md
  pages.ko/common/man.md
  pages.pt_BR/common/man.md
  pages.ta/common/man.md
  pages.tr/common/man.md
  pages/common/man.md
Labels: page edit, translation

#13057 ip: update more information link
  pages.de/linux/ip.md
  pages.fr/linux/ip.md
  pages.it/linux/ip.md
  pages.pt_BR/linux/ip.md
  pages.tr/linux/ip.md
  pages/linux/ip.md
Labels: page edit, translation

#13054 pgrep: update more information link
  pages/common/pgrep.md
Labels: page edit

#13064 mandb: update more information link
  pages/linux/mandb.md
Labels: page edit

#13059 lvdisplay: update more information link
  pages/linux/lvdisplay.md
Labels: page edit

#13060 lvm: update more information link
  pages/linux/lvm.md
Labels: page edit

#13062 lvresize: update more information link
  pages/linux/lvresize.md
Labels: page edit

#13056 ethtool: update more information link
  pages/linux/ethtool.md
Labels: page edit

#13058 lvcreate: update more information link
  pages/linux/lvcreate.md
Labels: page edit

#13055 pkill: update more information link
  pages.ko/common/pkill.md
  pages/common/pkill.md
Labels: page edit, translation

#13063 lvs: update more infomation link
  pages.zh/linux/lvs.md
  pages/linux/lvs.md
Labels: page edit, translation

#13065 numactl: update more infomation link
  pages/linux/numactl.md
Labels: page edit

#13066 partx: update more information link
  pages/linux/partx.md
Labels: page edit

#13045 split: add Dutch translation and align pages
  pages.es/osx/split.md
  pages.id/common/split.md
  pages.nl/common/split.md
  pages.nl/osx/split.md
  pages.zh/osx/split.md
  pages/common/split.md
  pages/osx/split.md
Labels: page edit, translation

#13051 prstat: fix placeholder
  pages.fr/sunos/prstat.md
  pages.id/sunos/prstat.md
  pages.nl/sunos/prstat.md
  pages.pl/sunos/prstat.md
  pages.ta/sunos/prstat.md
  pages.tr/sunos/prstat.md
  pages/sunos/prstat.md
Labels: page edit, translation

#13052 pages.nl: fix typos
  pages.nl/common/a2ping.md
  pages.nl/common/ac.md
  pages.nl/common/accelerate.md
  pages.nl/common/ack.md
  pages.nl/common/acme.sh.md
  pages.nl/common/arch.md
  pages.nl/common/cksum.md
  pages.nl/common/echo.md
  pages.nl/common/fossil-init.md
  pages.nl/common/fossil-rm.md
  pages.nl/common/just.1.md
  pages.nl/common/linode-cli-nodebalancers.md
  pages.nl/common/lp.md
  pages.nl/common/rm.md
  pages.nl/common/strings.md
  pages.nl/common/time.md
  pages.nl/common/transmission-cli.md
  pages.nl/common/tty.md
  pages.nl/common/vim.md
  pages.nl/common/xzgrep.md
  pages.nl/common/xzless.md
  pages.nl/common/yapf.md
  pages.nl/common/yes.md
  pages.nl/common/ykman-config.md
  pages.nl/common/ykman-openpgp.md
  pages.nl/linux/bspc.md
  pages.nl/linux/cgcreate.md
  pages.nl/linux/cp.md
  pages.nl/linux/iptables.md
  pages.nl/linux/mount.cifs.md
  pages.nl/osx/dd.md
  pages.nl/osx/launchctl.md
  pages.nl/sunos/prstat.md
Labels: translation

#13050 uname: add Dutch translation
  pages.nl/common/uname.md
  pages.nl/linux/uname.md
  pages.nl/osx/uname.md
Labels: translation

#13049 uptime: add Dutch translation
  pages.nl/common/uptime.md
  pages.nl/osx/uptime.md
Labels: translation

#13048 wc: add Dutch translation
  pages.nl/common/wc.md
  pages.nl/osx/wc.md
Labels: translation

#13046 stat: add Dutch translation
  pages.nl/common/stat.md
  pages.nl/osx/stat.md
Labels: translation

#13043 readlink: add Dutch translation
  pages.nl/common/readlink.md
  pages.nl/osx/readlink.md
Labels: translation

#13042 group*: add Dutch translation
  pages.nl/common/groups.md
  pages.nl/linux/groupadd.md
  pages.nl/linux/groupdel.md
  pages.nl/linux/groupmod.md
Labels: translation

#13015 bugreportz: update Polish translation
  pages.pl/android/bugreportz.md
Labels: translation

#13016 wm: update Polish translation
  pages.pl/android/wm.md
Labels: translation

#12993 import: add Polish translation
  pages.pl/common/import.md
Labels: translation

#12994 jfrog: add Polish translation
  pages.pl/common/jfrog.md
Labels: translation

#12992 identify: add Polish translation
  pages.pl/common/identify.md
Labels: translation

#12991 icontopbm: add Polish translation
  pages.pl/common/icontopbm.md
Labels: translation

#12990 gemtopbm: add Polish translation
  pages.pl/common/gemtopbm.md
Labels: translation

#12988 cups: add Polish translation
  pages.pl/common/cups.md
Labels: translation

#12987 convert: add Polish translation
  pages.pl/common/convert.md
Labels: translation

#12986 compare: add Polish translation
  pages.pl/common/compare.md
Labels: translation

#12985 bpmtoppm: add Polish translation
  pages.pl/common/bmptoppm.md
Labels: translation

#12995 lckdo: add Polish translation
  pages.pl/common/lckdo.md
Labels: translation

#12989 frp: add Polish translation
  pages.pl/common/frp.md
Labels: translation

#13030 grep: add Dutch translation and fix placeholder highlight
  pages.da/common/grep.md
  pages.de/common/grep.md
  pages.es/common/grep.md
  pages.fa/common/grep.md
  pages.fr/common/grep.md
  pages.ko/common/grep.md
  pages.nl/common/grep.md
  pages.pt_BR/common/grep.md
  pages.ru/common/grep.md
  pages.ta/common/grep.md
  pages.tr/common/grep.md
  pages.zh/common/grep.md
  pages/common/grep.md
Labels: page edit, translation

#12928 neo4j-admin: add Spanish translation
  pages.es/common/neo4j-admin.md
Labels: translation

#13003 dd: add Spanish translation
  pages.es/linux/dd.md
Labels: translation

#12980 hyprctl: add Spanish translation
  pages.es/linux/hyprctl.md
Labels: translation

#13004 diff: add Spanish translation
  pages.es/common/diff.md
Labels: translation

#13083 pvdisplay: update more information link
  pages/linux/pvdisplay.md
Labels: page edit

#13082 pvcreate: update more information link
  pages/linux/pvcreate.md
Labels: page edit

#13088 sntpd: update more information link
  pages/osx/sntpd.md
Labels: page edit

#13086 vgdisplay: update more information link
  pages/linux/vgdisplay.md
Labels: page edit

#13087 vgs: update more information link
  pages/linux/vgs.md
Labels: page edit

#13081 poweroff: update more information link
  pages.ca/linux/poweroff.md
  pages.es/linux/poweroff.md
  pages.id/linux/poweroff.md
  pages.it/linux/poweroff.md
  pages.pt_BR/linux/poweroff.md
  pages.zh/linux/poweroff.md
  pages/linux/poweroff.md
Labels: page edit, translation

#13069 sleep: add Dutch translation
  pages.nl/common/sleep.md
  pages.nl/linux/sleep.md
Labels: translation

#13073 talk: add Dutch translation
  pages.nl/linux/talk.md
Labels: translation

#13072 tftp: add Dutch translation
  pages.nl/linux/tftp.md
Labels: translation

#13071 updatedb: add Dutch translation
  pages.nl/linux/updatedb.md
Labels: translation

#13070 port: add Dutch translation
  pages.nl/osx/port.md
Labels: translation

#13068 tac: add Dutch translation
  pages.nl/common/tac.md
  pages.nl/linux/tac.md
Labels: translation

#13080 lvremove: update more information link
  pages/linux/lvremove.md
Labels: page edit
