Repository tldr-pages/tldr, pull requests merged in 2024-05, with the labels that each got.

#12692 ntpd: add Spanish translation
  pages.es/linux/ntpd.md
Labels: translation

#12691 type: add Spanish translation
  pages.es/common/type.md
Labels: translation

#12681 sslstrip: add page
  pages/linux/sslstrip.md
Labels: new command

#12700 archwiki-rs: add page
  pages/common/archwiki-rs.md
Labels: new command

#12703 pages*: replace "Véase" with "Vea" on some Spanish pages
  pages.es/common/figlet.md
  pages.es/common/git-am.md
  pages.es/common/git-checkout.md
  pages.es/common/git-cherry-pick.md
  pages.es/common/git-format-patch.md
  pages.es/common/git-restore.md
  pages.es/common/git-switch.md
  pages.es/common/showfigfonts.md
  pages.es/common/xkill.md
  pages.es/common/zsh.md
  pages.es/osx/arch.md
Labels: translation

#12699 feat: add `devcontainer.json`
  .devcontainer/devcontainer.json
Labels: tooling

#12702 tar: fix typos on Spanish page
  pages.es/common/tar.md
Labels: translation

#12680 common: update outdated Indonesian translations
  pages.id/common/!.md
  pages.id/common/^.md
  pages.id/common/airodump-ng.md
  pages.id/common/aria2.md
  pages.id/common/bat.md
  pages.id/common/cp.md
Labels: translation

#12679 common: add Indonesian translations for Git subcommands
  pages.id/common/git-clear-soft.md
  pages.id/common/git-coauthor.md
  pages.id/common/git-cola.md
  pages.id/common/git-column.md
  pages.id/common/git-commit-graph.md
Labels: translation

#12710 ppmtogif: add Spanish translation
  pages.es/common/ppmtogif.md
Labels: translation

#12678 gitleaks: add Spanish translation
  pages.es/common/gitleaks.md
Labels: translation

#12709 pamtogif: add Spanish translation
  pages.es/common/pamtogif.md
Labels: translation

#12701 pants: add page
  pages/common/pants.md
Labels: new command

#12677 quarkus: add Spanish translation, fix placeholder
  pages.es/common/quarkus.md
  pages/common/quarkus.md
Labels: page edit, translation

#12690 pages.nl: use " " instead of "=" to separate the options from their arguments
  pages.nl/android/logcat.md
  pages.nl/common/2to3.md
  pages.nl/common/ack.md
  pages.nl/common/adb-logcat.md
  pages.nl/common/chgrp.md
  pages.nl/common/chown.md
  pages.nl/common/cut.md
  pages/common/cut.md
Labels: page edit, translation

#12725 MAINTAINERS: add @Magrid0 as Org Member
  MAINTAINERS.md
Labels: community

#12721 logcat: update Polish translation; screencap: add Polish translation
  pages.pl/android/logcat.md
  pages.pl/android/screencap.md
Labels: translation

#12724 d2: add page
  pages/common/d2.md
Labels: new command

#12723 chrt: fix argument order when changing the scheduling policy
  pages/linux/chrt.md
Labels: page edit

#12733 cut: edit page
  pages/common/cut.md
Labels: page edit

#12722 fastfetch: add `--pipe` example
  pages/common/fastfetch.md
Labels: page edit

#12736 chrt: update page
  pages/linux/chrt.md
Labels: page edit

#12704 pages.{en, pt_BR}: replace the previous dockerd URL with the new one
  pages.ar/linux/dockerd.md
  pages.pt_BR/linux/dockerd.md
  pages/linux/dockerd.md
Labels: page edit, translation

#12738 dart: add fix subcommand example
  pages/common/dart.md
Labels: page edit

#12739 icontopbm: fix typo for alias page
  pages/common/icontopbm.md
Labels: page edit

#12696 immich-{cli,go}: add page and Spanish translation
  pages.es/common/immich-cli.md
  pages.es/common/immich-go.md
  pages/common/immich-cli.md
  pages/common/immich-go.md
Labels: new command, translation

#12740 prime-run: add page
  pages/linux/prime-run.md
Labels: new command

#12737 xsltproc, yaa: update Polish translation
  pages.pl/osx/xsltproc.md
  pages.pl/osx/yaa.md
Labels: translation

#12746 icontopbm: fix typo for alias page
  pages.nl/common/icontopbm.md
Labels: translation

#12741 getenforce: add page
  pages/linux/getenforce.md
Labels: new command

#12751 bmptopnm: add Dutch translation
  pages.nl/common/bmptopnm.md
Labels: translation

#12764 theharvester: edit page
  pages/common/theharvester.md
Labels: page edit, minor change

#12745 scripts/set-alias-page.py: add language option, fix script
  scripts/set-alias-page.py
Labels: tooling

#12730 pages.pl/sunos/*: add pages
  pages.pl/sunos/devfsadm.md
  pages.pl/sunos/dmesg.md
  pages.pl/sunos/prctl.md
  pages.pl/sunos/prstat.md
  pages.pl/sunos/snoop.md
  pages.pl/sunos/svcadm.md
  pages.pl/sunos/svccfg.md
  pages.pl/sunos/svcs.md
  pages.pl/sunos/truss.md
Labels: translation

#12756 style-guide: update the "See also" section
  contributing-guides/style-guide.md
Labels: documentation

#12766 pw-cli: fix link to the documentation
  pages/linux/pw-cli.md
Labels: page edit

#12748 systemctl: update page
  pages/linux/systemctl.md
Labels: page edit

#12765 objcopy: add page
  pages/linux/objcopy.md
Labels: new command

#12770 krfb-virtualmonitor: add page
  pages/linux/krfb-virtualmonitor.md
Labels: new command

#12636 dnsx: add Spanish translation
  pages.es/common/dnsx.md
Labels: translation

#12774 aur: add another automation option
  pages/linux/aur.md
Labels: page edit

#12779 MAINTAINERS: add @spageektti as a collaborator; CODEOWNERS: add Polish reviewer
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: community

#12778 pw-cli: fix link to the documentation
  pages.pt_BR/linux/pw-cli.md
  pages.tr/linux/pw-cli.md
Labels: translation

#12771 lastcomm: move to common
  pages.de/common/lastcomm.md
  pages/common/lastcomm.md
Labels: page edit, translation

#12780 texcount: add -sub example
  pages/common/texcount.md
Labels: page edit

#12775 vnstat*: fix flag, rename placeholder and add Spanish translation
  pages.es/linux/vnstat.md
  pages.es/linux/vnstati.md
  pages/linux/vnstat.md
  pages/linux/vnstati.md
Labels: page edit, translation

#12672 pambrighten: add Spanish translation
  pages.es/common/pambrighten.md
Labels: translation

#12783 readelf: update link
  pages/linux/readelf.md
Labels: page edit

#12784 gleam: add page
  pages/common/gleam.md
Labels: new command

#12720 bwa: add page
  pages/linux/bwa.md
Labels: new command

#12785 lstopo: add page
  pages/common/lstopo.md
Labels: new command

#12789 touch: update page
  pages/common/touch.md
Labels: page edit

#12782 a2disconf: add Polish translation
  pages.pl/linux/a2disconf.md
Labels: translation

#12787 lsar: add page; unar: update page
  pages/common/lsar.md
  pages/common/unar.md
Labels: page edit, new command

#12793 netstat: add osx page
  pages/osx/netstat.md
Labels: new command

#12796 pactl: add infodump example
  pages/common/pactl.md
Labels: page edit

#12761 getenforce: add Spanish translation
  pages.es/linux/getenforce.md
Labels: translation

#12798 apkleaks: add page
  pages/common/apkleaks.md
Labels: new command

#12714 archwiki-rs: add Spanish translation
  pages.es/common/archwiki-rs.md
Labels: translation

#12755 `scripts/_common.py`: add a shared Python file to move duplicated code
  .github/workflows/ci.yml
  .gitignore
  scripts/README.md
  scripts/_common.py
  scripts/set-alias-page.py
  scripts/set-more-info-link.py
  scripts/set-page-title.py
  scripts/test-requirements.txt
  scripts/test.sh
Labels: documentation, tooling

#12794 bwa: add Spanish translation
  pages.es/linux/bwa.md
Labels: translation

#12801 alacritty: update configs to .toml from deprecated .yml
  pages.de/common/alacritty.md
  pages.es/common/alacritty.md
  pages.fr/common/alacritty.md
  pages.id/common/alacritty.md
  pages.it/common/alacritty.md
  pages.ko/common/alacritty.md
  pages.nl/common/alacritty.md
  pages.pt_BR/common/alacritty.md
  pages.pt_PT/common/alacritty.md
  pages.zh/common/alacritty.md
  pages/common/alacritty.md
Labels: page edit, translation

#12788 lstopo: add Spanish translation
  pages.es/common/lstopo.md
Labels: translation

#12719 sops: update page
  pages/common/sops.md
Labels: page edit

#12804 CODEOWNERS: add @kbdharun as reviewer for scripts directory
  .github/CODEOWNERS
Labels: community

#12803 CODEOWNERS: add @spageektti as reviewer for common, linux, windows
  .github/CODEOWNERS
Labels: community

#12800 pw-config: add page
  pages/linux/pw-config.md
Labels: new command

#12742 d2: add Spanish translation
  pages.es/common/d2.md
Labels: translation

#12644 arecord, convert: edit pages
  pages/common/convert.md
  pages/linux/arecord.md
Labels: page edit

#12810 tor, torify: add pages
  pages/linux/tor.md
  pages/linux/torify.md
Labels: new command

#12812 ansible: add Spanish translation
  pages.es/common/ansible.md
Labels: translation

#12786 touch: add Simplified Chinese Translation
  pages.zh/common/touch.md
Labels: translation

#12795 gleam: add Spanish translation
  pages.es/common/gleam.md
Labels: translation

#12817 chezmoi: update page
  pages/common/chezmoi.md
Labels: page edit

#12819 pages.es/*: update placeholders with the word "id"
  pages.es/common/act.md
  pages.es/common/argocd-app.md
  pages.es/common/asciinema.md
  pages.es/common/aws-cognito-idp.md
  pages.es/common/aws-ec2.md
  pages.es/common/aws-route53.md
  pages.es/common/az-account.md
  pages.es/common/az-tag.md
  pages.es/common/kill.md
  pages.es/linux/apt-key.md
  pages.es/linux/pwdx.md
  pages.es/linux/top.md
  pages.es/osx/vpnd.md
Labels: translation

#12815 dotnet-test: add page
  pages/common/dotnet-test.md
Labels: new command

#12802 dnf: add Chinese translation
  pages.zh/linux/dnf.md
Labels: translation

#12816 style-guide: fix typos
  contributing-guides/style-guide.md
Labels: documentation

#12821 pages/common/*: fix broken links
  pages.de/common/docker-machine.md
  pages.es/common/bru.md
  pages.es/common/golangci-lint.md
  pages.fr/common/docker-machine.md
  pages.it/common/cabal.md
  pages.it/common/docker-machine.md
  pages.ko/common/cabal.md
  pages.ko/common/docker-machine.md
  pages.pt_BR/common/cabal.md
  pages.pt_BR/common/docker-machine.md
  pages.ru/common/cabal.md
  pages.tr/common/docker-machine.md
  pages/common/bru.md
  pages/common/cabal.md
  pages/common/clash.md
  pages/common/deemix.md
  pages/common/docker-machine.md
  pages/common/gcloud-info.md
  pages/common/golangci-lint.md
  pages/common/hub-browse.md
  pages/common/idnits.md
  pages/common/jdupes.md
  pages/common/nf-core.md
  pages/common/pnpx.md
  pages/common/qemu-img.md
Labels: page edit, translation

#12823 xset, xrandr: add example
  pages/linux/xrandr.md
  pages/linux/xset.md
Labels: page edit

#12825 git-lfs: update upstream link
  pages.es/common/git-lfs.md
  pages.fr/common/git-lfs.md
  pages.it/common/git-lfs.md
  pages.tr/common/git-lfs.md
  pages/common/git-lfs.md
Labels: page edit

#12814 arp: add Spanish translation
  pages.es/common/arp.md
Labels: translation

#12826 pages*/common/*: fix broken links
  pages.es/common/tree.md
  pages.it/common/tree.md
  pages.ko/common/virsh.md
  pages.pt_BR/common/virsh.md
  pages.tr/common/tree.md
  pages.zh/common/tree.md
  pages/common/sam2p.md
  pages/common/secrethub.md
  pages/common/slimrb.md
  pages/common/spfquery.md
  pages/common/tree.md
  pages/common/unison.md
  pages/common/virsh.md
  pages/common/wireplumber.md
  pages/common/wpexec.md
  pages/common/xdelta.md
Labels: page edit, translation

#12813 7z: update Spanish translation
  pages.es/common/7z.md
Labels: translation

#12827 arp: fix typo, tree: update link in translation
  pages.es/common/arp.md
  pages.pt_BR/common/tree.md
Labels: translation

#12832 semanage: rewrite page
  pages/linux/semanage.md
Labels: page edit

#12836 dconf-reset: fix examples
  pages.pt_BR/linux/dconf-reset.md
  pages/linux/dconf-reset.md
Labels: page edit, translation

#12834 setenforce, {get,set}sebool, semanage-{boolean,port,permissive}: add page
  pages/linux/getenforce.md
  pages/linux/getsebool.md
  pages/linux/semanage-boolean.md
  pages/linux/semanage-permissive.md
  pages/linux/semanage-port.md
  pages/linux/semanage.md
  pages/linux/setenforce.md
  pages/linux/setsebool.md
Labels: page edit, new command

#12840 togglesebool: add page
  pages/linux/togglesebool.md
Labels: new command

#12841 matchpathcon, secon: add page
  pages/linux/matchpathcon.md
  pages/linux/secon.md
Labels: new command

#12844 scripts/wrong-filename: resolve wrong filenames
  pages/linux/urpmi.addmedia.md
  pages/linux/urpmi.removemedia.md
  pages/linux/urpmi.update.md
  scripts/wrong-filename.sh
Labels: page edit, tooling

#12762 docker, ollama, history, tldr: fix mnemonics
  pages/common/docker.md
  pages/common/history.md
  pages/common/ollama.md
  pages/common/tldr.md
Labels: page edit

#12683 ctop: add page
  pages/linux/ctop.md
Labels: new command

#12845 dotnet-add-reference: add examples for multiple references
  pages/common/dotnet-add-reference.md
Labels: page edit

#12846 auditctl: add page
  pages/linux/auditctl.md
Labels: new command

#12847 mypy: add page
  pages/common/mypy.md
Labels: new command

#12850 pages/linux/*: replace broken links
  pages.zh/linux/asterisk.md
  pages/linux/asterisk.md
  pages/linux/eopkg.md
  pages/linux/feedreader.md
  pages/linux/genid.md
  pages/linux/gummy.md
  pages/linux/kdialog.md
  pages/linux/lxterminal.md
  pages/linux/ntpdate.md
  pages/linux/obabel.md
  pages/linux/rpmbuild.md
  pages/linux/swupd.md
  pages/linux/vrms.md
  pages/linux/warpd.md
Labels: page edit, translation

#12849 agetty: fix Spanish translation
  pages.es/linux/agetty.md
Labels: page edit, translation

#12853 spatial: delete page
  pages/common/spatial.md
Labels: page edit

#12854 ctop: add Spanish translation
  pages.es/linux/ctop.md
Labels: translation

#12855 tor: remove duplicate and update link
  pages/linux/tor.md
Labels: page edit

#12858 pylint: add package and module examples
  pages/common/pylint.md
Labels: page edit

#12837 tor: add Spanish translation
  pages.es/linux/tor.md
Labels: translation

#12838 torify: add Spanish translation
  pages.es/linux/torify.md
Labels: translation

#12859 virt-qemu-run: add page
  pages/common/virt-qemu-run.md
Labels: new command

#12851 feat/ci: add support for attesting release assets
  .github/workflows/ci.yml
  .github/workflows/copy-release-assets.yml
Labels: tooling, security

#12860 hledger-*: update pages
  pages/common/hledger-accounts.md
  pages/common/hledger-aregister.md
  pages/common/hledger-balance.md
  pages/common/hledger-balancesheet.md
  pages/common/hledger-incomestatement.md
  pages/common/hledger-ui.md
  pages/common/hledger-web.md
Labels: page edit
