Repository tldr-pages/tldr, pull requests merged in 2024-10, with the labels that each got.

#13914 feat: update clients wiki to new link
  README.md
  contributing-guides/style-guide.md
  contributing-guides/style-guide.zh.md
Labels: documentation

#13909 LICENSE: switch to https
  LICENSE.md
Labels: documentation

#13846 <, >, |, $: add page
  pages/common/$.md
  pages/common/greater-than.md
  pages/common/less-than.md
  pages/common/vertical-bar.md
Labels: new command

#13901 apt-clone: add page
  pages/linux/apt-clone.md
Labels: new command

#13919 vinmap: add page
  pages/common/vinmap.md
Labels: new command

#13920 yadm: add pages
  pages/common/yadm-alt.md
  pages/common/yadm-bootstrap.md
  pages/common/yadm-clone.md
  pages/common/yadm-config.md
  pages/common/yadm-decrypt.md
  pages/common/yadm-encrypt.md
  pages/common/yadm-enter.md
  pages/common/yadm-git-crypt.md
  pages/common/yadm-gitconfig.md
  pages/common/yadm-init.md
  pages/common/yadm-introsepct.md
  pages/common/yadm-list.md
  pages/common/yadm-perms.md
  pages/common/yadm-transcrypt.md
  pages/common/yadm-upgrade.md
  pages/common/yadm.md
Labels: new command

#13923 top: fix typo
  pages.zh_TW/linux/top.md
Labels: translation

#13819 cat: update Chinese translation
  pages.zh/common/cat.md
Labels: translation

#13936 maintainers-guide: simplify description of CODEOWNERS
  contributing-guides/maintainers-guide.md
Labels: documentation

#13928 lspci: add Hindi translation
  pages.hi/linux/lspci.md
Labels: translation

#13929 mkfs: add Hindi translation
  pages.hi/linux/mkfs.md
Labels: translation

#13930 resize2fs: add Hindi translation
  pages.hi/linux/resize2fs.md
Labels: translation

#13924 onefetch: add page
  pages/common/onefetch.md
Labels: new command

#13921 getfattr, setfattr, sysdig: add page
  pages/linux/getfattr.md
  pages/linux/setfattr.md
  pages/linux/sysdig.md
Labels: new command

#13800 pages.pt_BR/linux/*: update commands, descriptions, translations, and paths for multiple commands
  pages.pt_BR/linux/bluetoothd.md
  pages.pt_BR/linux/bspwm.md
  pages.pt_BR/linux/btrfs-version.md
  pages.pt_BR/linux/flatpak.md
  pages.pt_BR/linux/lsblk.md
  pages.pt_BR/linux/pi.md
  pages.pt_BR/linux/poweroff.md
  pages.pt_BR/linux/systemctl.md
  pages/linux/dunstify.md
Labels: page edit, translation

#13827 builtin: add page
  pages/common/builtin.md
Labels: new command

#13934 az-disk: add page
  pages/common/az-disk.md
Labels: new command

#13939 yadm-introspect: fix typo in filename
  pages/common/yadm-introspect.md
Labels: page edit

#13942 yadm-config: fix more info line
  pages/common/yadm-config.md
Labels: page edit

#13791 dotenvx: add Spanish translation
  pages.es/common/dotenvx.md
Labels: translation

#13953 man: remove `www.`
  pages.it/common/man.md
  pages.ko/common/man.md
  pages.nl/common/man.md
  pages.pt_BR/common/man.md
  pages.ta/common/man.md
  pages.tr/common/man.md
  pages/common/man.md
Labels: page edit, translation

#13949 gatsby: fix documentation link
  pages.pt_BR/common/gatsby.md
  pages/common/gatsby.md
Labels: page edit, translation

#13957 MAINTAINERS: add @Managor as Org member
  MAINTAINERS.md
Labels: community

#13966 CODEOWNERS: add @renie for pt_BR, MAINTAINERS: add @renie as collaborator
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: community

#13965 contributing-guides: fix pt_BR templates
  contributing-guides/translation-templates/alias-pages.md
  contributing-guides/translation-templates/subcommand-mention.md
Labels: documentation

#13937 eselect-{kernel,profile}: add page
  pages/linux/eselect-kernel.md
  pages/linux/eselect-profile.md
Labels: new command

#13961 ollama: update page
  pages/common/ollama.md
Labels: page edit

#13960 fping: update page
  pages/common/fping.md
Labels: page edit

#13933 choose, chroma, chronic: add Korean translation
  pages.ko/common/choose.md
  pages.ko/common/chroma.md
  pages.ko/common/chronic.md
Labels: translation

#13968 eselect: update page
  pages/linux/eselect.md
Labels: page edit

#13801 ceph: add Spanish translation
  pages.es/linux/ceph.md
Labels: translation

#13885 journalctl: add Spanish translation
  pages.es/linux/journalctl.md
Labels: translation

#13938 git-rebase, git-fetch: add Ukrainian translation
  pages.uk/common/git-fetch.md
  pages.uk/common/git-rebase.md
Labels: translation

#13972 pages.pt_BR/common/*: add Portuguese Brazilian translations
  pages.pt_BR/common/rc.md
  pages.pt_BR/common/strings.md
  pages.pt_BR/common/tldr-lint.md
  pages.pt_BR/common/tlmgr-platform.md
  pages.pt_BR/common/todo.md
  pages.pt_BR/common/transmission-cli.md
  pages.pt_BR/common/transmission-create.md
  pages.pt_BR/common/transmission-daemon.md
  pages.pt_BR/common/transmission-edit.md
  pages.pt_BR/common/transmission-remote.md
  pages.pt_BR/common/transmission-show.md
Labels: translation

#13976 pest: add examples for Pest 3.x
  pages/common/pest.md
Labels: page edit

#13978 chore: bump tldr-lint to v0.0.16, update lockfile
  package-lock.json
  package.json
Labels: tooling

#13951 pages.pt_BR/linux/*: add Portuguese Brazilian translations
  pages.pt_BR/linux/apport-bug.md
  pages.pt_BR/linux/cgclassify.md
  pages.pt_BR/linux/cgcreate.md
  pages.pt_BR/linux/cgexec.md
  pages.pt_BR/linux/ip-route-show.md
  pages.pt_BR/linux/megatools-dl.md
Labels: translation

#13992 scoop: add subcommand mention
  pages/windows/scoop.md
Labels: page edit

#13984 qm, qmrestore: edit page
  pages/linux/qm.md
  pages/linux/qmrestore.md
Labels: page edit

#13996 ollama: add link to model list
  pages/common/ollama.md
Labels: page edit

#13922 blockdev: add page
  pages/linux/blockdev.md
Labels: new command

#14005 waydroid: update page
  pages/linux/waydroid.md
Labels: page edit

#14007 shotcut: add page
  pages/common/shotcut.md
Labels: new command

#14017 zdump: add page
  pages/linux/zdump.md
Labels: new command

#14013 ifstat: add page
  pages/linux/ifstat.md
Labels: new command

#14024 {gif, img}2webp: add page
  pages/linux/gif2webp.md
  pages/linux/img2webp.md
Labels: new command

#14015 socat: add sudo
  pages/common/socat.md
Labels: page edit

#13969 az-vm: update Spanish translation
  pages.es/common/az-vm.md
Labels: translation

#13947 aws-ce: update Spanish translation
  pages.es/common/aws-ce.md
Labels: translation

#13948 awk: update Spanish translation
  pages.es/common/awk.md
Labels: translation

#13913 cut: update Spanish translation
  pages.es/common/cut.md
Labels: translation

#13941 afinfo: add German translation
  pages.de/osx/afinfo.md
Labels: translation

#13987 redshift: edit page
  pages/common/redshift.md
Labels: page edit

#13979 wget2: add page
  pages/common/wget2.md
Labels: new command

#14027 sdelete, sdelete64: add page
  pages/windows/sdelete.md
  pages/windows/sdelete64.md
Labels: new command

#14036 ^: add example
  pages/common/^.md
Labels: page edit

#14035 npm-{run, start, stop, restart, test}: add page
  pages/common/npm-restart.md
  pages/common/npm-run.md
  pages/common/npm-start.md
  pages/common/npm-stop.md
  pages/common/npm-test.md
Labels: new command

#14037 sestatus: add page
  pages/linux/sestatus.md
Labels: new command

#14019 fc: refresh page
  pages/common/fc.md
Labels: page edit

#14002 adb reboot: add page
  pages/common/adb-reboot.md
Labels: new command

#14042 speaker-test: add page
  pages/linux/speaker-test.md
Labels: new command

#13980 git-annotate, git-blame: add Ukrainian translation
  pages.uk/common/git-annotate.md
  pages.uk/common/git-blame.md
Labels: translation

#14049 pages.pt_BR/linux/*: add Portuguese Brazilian translations
  pages.pt_BR/linux/pacaur.md
  pages.pt_BR/linux/paccache.md
  pages.pt_BR/linux/pacdiff.md
  pages.pt_BR/linux/pacgraph.md
  pages.pt_BR/linux/pacman-database.md
  pages.pt_BR/linux/pacman-deptest.md
  pages.pt_BR/linux/pacman-files.md
  pages.pt_BR/linux/pacman-key.md
  pages.pt_BR/linux/pacman-query.md
  pages.pt_BR/linux/pacman4console.md
Labels: translation

#14006 ntfy: add page
  pages/common/ntfy.md
Labels: new command

#14040 7zr, aria2c, audacious, az-disk, cloudflared, cmatrix, cmuwmtopbm, codecrafters, codespell: update and add Korean translation
  pages.ko/common/7zr.md
  pages.ko/common/aria2c.md
  pages.ko/common/audacious.md
  pages.ko/common/az-disk.md
  pages.ko/common/cloudflared.md
  pages.ko/common/cmatrix.md
  pages.ko/common/cmuwmtopbm.md
  pages.ko/common/codecrafters.md
  pages.ko/common/codespell.md
Labels: translation

#14055 ^: update Dutch translation
  pages.nl/common/^.md
Labels: translation

#14056 fc: update Dutch translation
  pages.nl/common/fc.md
Labels: translation

#14057 sdelete, sdelete64: add Dutch translation
  pages.nl/windows/sdelete.md
  pages.nl/windows/sdelete64.md
Labels: translation

#14060 gpclient: add page
  pages/linux/gpclient.md
Labels: new command

#14010 !: add examples
  pages/common/!.md
Labels: page edit

#14016 mkfifo: add terminal share example
  pages/common/mkfifo.md
Labels: page edit

#14052 pulumi-stack: add page
  pages/common/pulumi-stack.md
Labels: new command

#14038 nice: edit page
  pages/common/nice.md
Labels: page edit

#14014 pandoc: adjust order and make the example what newbies would most likely use it for
  pages/common/pandoc.md
Labels: page edit

#14058 lz, caffeinate, ip6tables: add Polish translation
  pages.pl/linux/caffeinate.md
  pages.pl/linux/ip6tables.md
  pages.pl/linux/lz.md
Labels: translation

#14072 adb-device: add page
  pages/common/adb-devices.md
Labels: new command

#13991 animdl: add page
  pages/common/animdl.md
Labels: new command

#13977 whoami, winget, wmic: add Korean translation
  pages.ko/windows/whoami.md
  pages.ko/windows/winget.md
  pages.ko/windows/wmic.md
Labels: translation

#13993 where, where-object, wait-process: add Korean translation
  pages.ko/windows/wait-process.md
  pages.ko/windows/where-object.md
  pages.ko/windows/where.md
Labels: translation

#14079 pages.pt_BR/common/*: update out-of-date translations
  pages.pt_BR/common/7z.md
  pages.pt_BR/common/7za.md
  pages.pt_BR/common/7zr.md
  pages.pt_BR/common/awk.md
  pages.pt_BR/common/aws-codeartifact.md
  pages.pt_BR/common/aws-iam.md
  pages.pt_BR/common/aws-lambda.md
  pages.pt_BR/common/banner.md
  pages.pt_BR/common/chromium.md
  pages.pt_BR/common/cmatrix.md
  pages.pt_BR/common/cups-config.md
Labels: translation

#14078 wtype: add page
  pages/linux/wtype.md
Labels: new command

#14081 set: list all modes
  pages/common/set.md
Labels: page edit

#14088 npm-outdated: add page
  pages/common/npm-outdated.md
Labels: new command

#13994 alias-pages: adjust finnish wording
  contributing-guides/translation-templates/alias-pages.md
Labels: documentation

#14069 mkfifo: update Dutch translation
  pages.nl/common/mkfifo.md
Labels: translation

#14066 pages.nl/*: rephrase Dutch alias pages
  pages.nl/common/just.md
  pages.nl/common/lckdo.md
  pages.nl/common/moreutils.md
  pages.nl/common/mscore.md
  pages.nl/common/open.md
  pages.nl/common/pnmscale.md
  pages.nl/common/ppmquant.md
  pages.nl/common/ps-nvm.md
  pages.nl/common/vi.md
  pages.nl/common/ykman.md
  pages.nl/linux/eselect.md
  pages.nl/linux/lid.md
  pages.nl/linux/systemd-resolve.md
  pages.nl/linux/tailf.md
  pages.nl/linux/xbps.md
  pages.nl/windows/cd.md
  pages.nl/windows/chdir.md
  pages.nl/windows/mv.md
  pages.nl/windows/pwd.md
  pages.nl/windows/rmdir.md
Labels: translation

#14080 >: add file emptying example
  pages/common/greater-than.md
Labels: page edit

#14100 ver,virtualboxvm,vol,vswhere,w32tm: add Korean translation
  pages.ko/windows/ver.md
  pages.ko/windows/virtualboxvm.md
  pages.ko/windows/vol.md
  pages.ko/windows/vswhere.md
  pages.ko/windows/w32tm.md
Labels: translation

#14030 shotcut: add Spanish translation
  pages.es/common/shotcut.md
Labels: translation

#14089 look: update Spanish translation
  pages.es/osx/look.md
Labels: translation

#14097 chronyc: fix more info link
  pages/linux/chronyc.md
Labels: page edit

#14091 caffeinate: update Spanish translation
  pages.es/osx/caffeinate.md
Labels: translation

#14071 *-config-manager: add Dutch translation
  pages.nl/linux/dnf-config-manager.md
  pages.nl/linux/yum-config-manager.md
Labels: translation

#13554 rev: update page
  pages/common/rev.md
Labels: page edit, new command

#14101 launchd: improving main description
  pages/osx/launchd.md
Labels: page edit

#14118 gh,gh-*: add Korean translation
  pages.ko/common/gh-alias.md
  pages.ko/common/gh-api.md
  pages.ko/common/gh-auth.md
  pages.ko/common/gh-browse.md
  pages.ko/common/gh-codespace.md
  pages.ko/common/gh-completion.md
  pages.ko/common/gh-config.md
  pages.ko/common/gh-environment.md
  pages.ko/common/gh-extension.md
  pages.ko/common/gh-formatting.md
  pages.ko/common/gh-gist.md
  pages.ko/common/gh-help.md
  pages.ko/common/gh-issue-create.md
  pages.ko/common/gh-issue.md
  pages.ko/common/gh-label.md
  pages.ko/common/gh-mintty.md
  pages.ko/common/gh-pr-create.md
  pages.ko/common/gh-pr-merge.md
  pages.ko/common/gh-pr.md
  pages.ko/common/gh-reference.md
  pages.ko/common/gh-release.md
  pages.ko/common/gh-repo.md
  pages.ko/common/gh-run.md
  pages.ko/common/gh-screensaver.md
  pages.ko/common/gh-secret-set.md
  pages.ko/common/gh-secret.md
  pages.ko/common/gh-ssh-key.md
  pages.ko/common/gh-workflow.md
  pages.ko/common/gh.md
Labels: translation

#14120 cargo,rust*: add and update Korean translation
  pages.ko/common/cargo.md
  pages.ko/common/rustc.md
  pages.ko/common/rustdoc.md
  pages.ko/common/rustfmt.md
  pages.ko/common/rustic.md
  pages.ko/common/rustscan.md
  pages.ko/common/rustup-check.md
  pages.ko/common/rustup-completions.md
  pages.ko/common/rustup-component.md
  pages.ko/common/rustup-default.md
  pages.ko/common/rustup-doc.md
  pages.ko/common/rustup-help.md
  pages.ko/common/rustup-init.sh.md
  pages.ko/common/rustup-install.md
  pages.ko/common/rustup-man.md
  pages.ko/common/rustup-override.md
  pages.ko/common/rustup-run.md
  pages.ko/common/rustup-self.md
  pages.ko/common/rustup-set.md
  pages.ko/common/rustup-show.md
  pages.ko/common/rustup-target.md
  pages.ko/common/rustup-toolchain.md
  pages.ko/common/rustup-update.md
  pages.ko/common/rustup-which.md
  pages.ko/common/rustup.md
Labels: translation

#14113 pages.pt_BR/common/*: add Brazilian Portuguese translation
  pages.pt_BR/common/ar.md
  pages.pt_BR/common/clamdscan.md
  pages.pt_BR/common/clamscan.md
  pages.pt_BR/common/clang++.md
  pages.pt_BR/common/clang-format.md
  pages.pt_BR/common/clang-tidy.md
  pages.pt_BR/common/clang.md
  pages.pt_BR/common/clangd.md
  pages.pt_BR/common/crontab.md
  pages.pt_BR/common/fossil-add.md
  pages.pt_BR/common/fossil-commit.md
  pages.pt_BR/common/fossil-init.md
  pages.pt_BR/common/fossil-rm.md
  pages.pt_BR/common/fossil.md
  pages.pt_BR/common/freshclam.md
  pages.pt_BR/common/gh-codespace.md
Labels: translation

#14122 pkgfile: fix more info link
  pages/linux/pkgfile.md
Labels: page edit

#14127 awk, find, grep: add Ukrainian translation
  pages.uk/common/awk.md
  pages.uk/common/find.md
  pages.uk/common/grep.md
Labels: translation

#14126 dirsearch, diskonaut, disown, distccd, djxl, dlv, dmd, dnsx, doas: add Korean translation
  pages.ko/common/dirsearch.md
  pages.ko/common/diskonaut.md
  pages.ko/common/disown.md
  pages.ko/common/distccd.md
  pages.ko/common/djxl.md
  pages.ko/common/dlv.md
  pages.ko/common/dmd.md
  pages.ko/common/dnsx.md
  pages.ko/common/doas.md
Labels: translation

#14131 cups*: add Korean translation
  pages.ko/common/cups-config.md
  pages.ko/common/cups.md
  pages.ko/common/cupsaccept.md
  pages.ko/common/cupsctl.md
  pages.ko/common/cupsd.md
  pages.ko/common/cupsdisable.md
  pages.ko/common/cupsenable.md
  pages.ko/common/cupsreject.md
  pages.ko/common/cupstestppd.md
Labels: translation

#14076 nice: update Dutch translation
  pages.nl/common/nice.md
  pages/common/nice.md
Labels: page edit, translation

#14116 devcontainer, devenv, dfc, dhcpig, dict, diff-pdf, diffoscope, difft, dillo, direnv: add Korean translation
  pages.ko/common/devcontainer.md
  pages.ko/common/devenv.md
  pages.ko/common/dfc.md
  pages.ko/common/dhcpig.md
  pages.ko/common/dict.md
  pages.ko/common/diff-pdf.md
  pages.ko/common/diffoscope.md
  pages.ko/common/difft.md
  pages.ko/common/dillo.md
  pages.ko/common/direnv.md
Labels: translation

#14114 animdl, d*: add Korean translation
  pages.ko/common/animdl.md
  pages.ko/common/d2.md
  pages.ko/common/d8.md
  pages.ko/common/dalfox.md
  pages.ko/common/daps.md
  pages.ko/common/dart.md
  pages.ko/common/dash.md
  pages.ko/common/datashader_cli.md
  pages.ko/common/dc.md
  pages.ko/common/dcfldd.md
  pages.ko/common/dcg.md
  pages.ko/common/dcode.md
  pages.ko/common/dd.md
  pages.ko/common/ddev.md
  pages.ko/common/ddgr.md
  pages.ko/common/decaffeinate.md
  pages.ko/common/declare.md
  pages.ko/common/deemix.md
  pages.ko/common/delta.md
Labels: translation

#14085 adb-*, co-*, cpdf, crackle, crictl: add Korean translation
  pages.ko/common/adb-devices.md
  pages.ko/common/adb-reboot.md
  pages.ko/common/compopt.md
  pages.ko/common/composer-require-checker.md
  pages.ko/common/conan-frogarian.md
  pages.ko/common/conan.md
  pages.ko/common/conda-create.md
  pages.ko/common/conda-install.md
  pages.ko/common/cosign.md
  pages.ko/common/cpdf.md
  pages.ko/common/crackle.md
  pages.ko/common/crictl.md
Labels: translation

#14086 cr*, cs-*: add Korean translation
  pages.ko/common/croc.md
  pages.ko/common/cronic.md
  pages.ko/common/crunch.md
  pages.ko/common/cs-complete-dep.md
  pages.ko/common/cs-fetch.md
  pages.ko/common/cs-install.md
  pages.ko/common/cs-java.md
  pages.ko/common/cs-launch.md
  pages.ko/common/cs-resolve.md
  pages.ko/common/cs.md
Labels: translation

#14095 git-cherry, git-cherry-pick: add Ukrainian translation
  pages.uk/common/git-cherry-pick.md
  pages.uk/common/git-cherry.md
Labels: translation

#14099 !, ^, cs*, ctags, cvs, cwebp, cypher-shell, czkawka-cli: update and add Korean translation
  pages.ko/common/!.md
  pages.ko/common/^.md
  pages.ko/common/csh.md
  pages.ko/common/csv-diff.md
  pages.ko/common/csv2tsv.md
  pages.ko/common/csvkit.md
  pages.ko/common/csvsql.md
  pages.ko/common/csvtool.md
  pages.ko/common/ctags.md
  pages.ko/common/cvs.md
  pages.ko/common/cwebp.md
  pages.ko/common/cypher-shell.md
  pages.ko/common/czkawka-cli.md
Labels: translation

#14104 7z, 7za, tar: add Ukrainian translation
  pages.uk/common/7z.md
  pages.uk/common/7za.md
  pages.uk/common/tar.md
Labels: translation

#14083 insmod, ip6tables-restore, tailf, unmount: add Polish translation
  pages.pl/linux/insmod.md
  pages.pl/linux/ip6tables-restore.md
  pages.pl/linux/tailf.md
  pages.pl/linux/unmount.md
Labels: translation

#14109 unopkg: add page
  pages/linux/unopkg.md
Labels: new command

#14115 aws-sso: add page
  pages/common/aws-sso.md
Labels: new command

#14110 pdfattach: add page
  pages/linux/pdfattach.md
Labels: new command

#14108 abrt-action-analyze-backtrace: add page
  pages/linux/abrt-action-analyze-backtrace.md
Labels: new command

#14105 diffimg: add page
  pages/linux/diffimg.md
Labels: new command

#14107 abrt-action-analyze-c: add page
  pages/linux/abrt-action-analyze-c.md
Labels: new command

#14112 pdfdetach: add page
  pages/linux/pdfdetach.md
Labels: new command

#14130 onionsearch: add page
  pages/common/onionsearch.md
Labels: new command

#13988 <: add here strings and documents
  pages/common/less-than.md
Labels: page edit

#14137 aws-sso, bind: add Korean translation
  pages.ko/common/aws-sso.md
  pages.ko/common/bind.md
Labels: translation

#14043 wait: add an example for jobs
  pages/common/wait.md
Labels: page edit

#14133 Iw-dev: add page iw: information link {dev, phy, reg, help examples}
  pages/linux/iw-dev.md
  pages/linux/iw.md
Labels: page edit, new command

#14138 crane*, createdb: add Korean translation
  pages.ko/common/crane-append.md
  pages.ko/common/crane-auth.md
  pages.ko/common/crane-blob.md
  pages.ko/common/crane-catalog.md
  pages.ko/common/crane-config.md
  pages.ko/common/crane-copy.md
  pages.ko/common/crane-delete.md
  pages.ko/common/crane-digest.md
  pages.ko/common/crane-export.md
  pages.ko/common/crane-flatten.md
  pages.ko/common/crane-index-append.md
  pages.ko/common/crane-index-filter.md
  pages.ko/common/crane-index.md
  pages.ko/common/crane-ls.md
  pages.ko/common/crane-manifest.md
  pages.ko/common/crane-mutate.md
  pages.ko/common/crane-pull.md
  pages.ko/common/crane-push.md
  pages.ko/common/crane-rebase.md
  pages.ko/common/crane-registry.md
  pages.ko/common/crane-tag.md
  pages.ko/common/crane-validate.md
  pages.ko/common/crane-version.md
  pages.ko/common/crane.md
  pages.ko/common/createdb.md
Labels: translation

#14141 common/*, freebsd/cal: add Indonesian translations
  pages.id/common/adb-devices.md
  pages.id/common/adb-reboot.md
  pages.id/common/asciitopgm.md
  pages.id/common/atktopbm.md
  pages.id/common/cal.md
  pages.id/common/gemtopbm.md
  pages.id/common/gemtopnm.md
  pages.id/common/pbmtoatk.md
  pages.id/freebsd/cal.md
Labels: translation

#14147 betterlockscreen: fix link
  pages/linux/betterlockscreen.md
Labels: page edit

#14136 logcat,del: replace simplified Chinese words with traditional Chinese words
  pages.zh_TW/android/logcat.md
  pages.zh_TW/windows/del.md
Labels: translation

#14135 ^: update Chinese translation
  pages.zh/common/^.md
Labels: translation

#14134 logcat: update Chinese translation
  pages.zh/android/logcat.md
Labels: translation

#14170 bspwm: remove wrong auto-generated alias pages
  pages.de/linux/bspwm.md
  pages.fr/linux/bspwm.md
  pages.hi/linux/bspwm.md
  pages.id/linux/bspwm.md
  pages.it/linux/bspwm.md
  pages.ko/linux/bspwm.md
  pages.ne/linux/bspwm.md
  pages.pl/linux/bspwm.md
  pages.pt_PT/linux/bspwm.md
  pages.ta/linux/bspwm.md
  pages.th/linux/bspwm.md
  pages.tr/linux/bspwm.md
  pages.zh/linux/bspwm.md
  pages.zh_TW/linux/bspwm.md
Labels: translation

#14169 cgroups: remove wrong auto-generated alias pages
  pages.de/linux/cgroups.md
  pages.es/linux/cgroups.md
  pages.fr/linux/cgroups.md
  pages.hi/linux/cgroups.md
  pages.id/linux/cgroups.md
  pages.it/linux/cgroups.md
  pages.ko/linux/cgroups.md
  pages.ne/linux/cgroups.md
  pages.pl/linux/cgroups.md
  pages.pt_PT/linux/cgroups.md
  pages.th/linux/cgroups.md
  pages.tr/linux/cgroups.md
  pages.zh/linux/cgroups.md
  pages.zh_TW/linux/cgroups.md
Labels: translation

#14129 cargo-add, cargo-bench, cargo-build, cargo-init: add French translation
  pages.fr/common/cargo-add.md
  pages.fr/common/cargo-bench.md
  pages.fr/common/cargo-build.md
  pages.fr/common/cargo-init.md
Labels: tooling, translation

#14168 windows/curl: remove wrong auto-generated alias pages
  pages.ar/windows/curl.md
  pages.bs/windows/curl.md
  pages.ca/windows/curl.md
  pages.da/windows/curl.md
  pages.es/windows/curl.md
  pages.fr/windows/curl.md
  pages.hi/windows/curl.md
  pages.it/windows/curl.md
  pages.ja/windows/curl.md
  pages.ko/windows/curl.md
  pages.lo/windows/curl.md
  pages.ml/windows/curl.md
  pages.ne/windows/curl.md
  pages.no/windows/curl.md
  pages.pt_PT/windows/curl.md
  pages.ru/windows/curl.md
  pages.sv/windows/curl.md
  pages.th/windows/curl.md
  pages.tr/windows/curl.md
  pages.uk/windows/curl.md
  pages.zh/windows/curl.md
  pages.zh_TW/windows/curl.md
Labels: translation

#14187 npm-unpublish: add page
  pages/common/npm-unpublish.md
Labels: new command

#14181 vim, nvim: add ZZ in save and exit example
  pages/common/nvim.md
  pages/common/vim.md
Labels: page edit

#14173 zapier: add page
  pages/common/zapier.md
Labels: new command

#14193 windows/choco*: add Korean translation
  pages.ko/windows/choco-apikey.md
  pages.ko/windows/choco-feature.md
  pages.ko/windows/choco-info.md
  pages.ko/windows/choco-install.md
  pages.ko/windows/choco-list.md
  pages.ko/windows/choco-new.md
  pages.ko/windows/choco-outdated.md
  pages.ko/windows/choco-pack.md
  pages.ko/windows/choco-pin.md
  pages.ko/windows/choco-push.md
  pages.ko/windows/choco-search.md
  pages.ko/windows/choco-source.md
  pages.ko/windows/choco-uninstall.md
  pages.ko/windows/choco-upgrade.md
  pages.ko/windows/choco.md
Labels: translation

#14189 faillock: add non-root commands
  pages/linux/faillock.md
Labels: page edit

#14143 time: update Dutch translation and titlecase Bash
  pages.nl/common/time.md
  pages/common/time.md
Labels: page edit, translation

#14144 base64: update Dutch translation
  pages.nl/osx/base64.md
Labels: translation

#14145 bleachbit: add Dutch translation
  pages.nl/linux/bleachbit.md
  pages.nl/windows/bleachbit.md
Labels: translation

#14197 sha*sum: add Korean translation
  pages.ko/common/sha1sum.md
  pages.ko/common/sha224sum.md
  pages.ko/common/sha256sum.md
  pages.ko/common/sha384sum.md
  pages.ko/common/sha512sum.md
  pages.ko/common/shasum.md
Labels: translation

#14198 apt: add purge command
  pages/linux/dpkg.md
Labels: page edit

#14177 zapier-build: add page
  pages/common/zapier-build.md
Labels: new command

#14176 zapier-analytics: add page
  pages/common/zapier-analytics.md
Labels: new command

#14174 zapier-scaffold: add page
  pages/common/zapier-scaffold.md
Labels: new command

#14230 gcrane: fix typo
  pages/common/gcrane.md
Labels: page edit

#14234 az-image: add page
  pages/common/az-image.md
Labels: new command

#14236 az-logicapp: add page
  pages/common/az-logicapp.md
Labels: new command

#14218 docker: update Chinese translations
  pages.zh/common/docker.md
  pages.zh_TW/common/docker.md
Labels: translation
