Repository tldr-pages/tldr, pull requests merged in 2024-02, with the labels that each got.

#12174 ISSUE-TEMPLATES: set the type of the VCS link to `input`
  .github/ISSUE_TEMPLATE/lets-document.yml
  .github/ISSUE_TEMPLATE/page-modification-request.yml
  .github/ISSUE_TEMPLATE/page-request.yml
Labels: tooling

#12152 ccache: add page
  pages/common/ccache.md
Labels: new command

#12190 umount, unmount: add Dutch translation
  pages.nl/linux/umount.md
  pages.nl/linux/unmount.md
  pages/linux/unmount.md
Labels: page edit, translation

#12191 cut, tail: use keith.github.io for Dutch pages
  pages.nl/osx/cut.md
  pages.nl/osx/tail.md
Labels: translation

#12167 mesg: split util-linux and POSIX pages
  pages/common/mesg.md
  pages/linux/mesg.md
Labels: page edit, new command

#12161 moreutils: add page
  pages/common/moreutils.md
Labels: new command

#12194 pacstrap: update page
  pages/linux/pacstrap.md
Labels: page edit

#12195 pages.*: standardize capitalization in note term
  pages.ko/common/virsh.md
  pages/common/cupsaccept.md
  pages/common/cupsdisable.md
  pages/common/cupsreject.md
  pages/common/cupstestppd.md
  pages/common/flex.md
  pages/common/kosmorro.md
  pages/common/lex.md
  pages/common/look.md
  pages/common/prosodyctl.md
  pages/common/q.md
  pages/common/tidy.md
  pages/common/virsh.md
  pages/common/virt-sparsify.md
  pages/linux/file-rename.md
  pages/linux/lid.md
  pages/linux/look.md
  pages/linux/perl-rename.md
  pages/linux/prename.md
  pages/linux/quickget.md
  pages/linux/rename.md
  pages/linux/switch_root.md
  pages/linux/urpmi-addmedia.md
  pages/linux/urpmi-removemedia.md
  pages/linux/urpmi-update.md
  pages/linux/virt-viewer.md
  pages/linux/virt-xml.md
  pages/osx/chpass.md
  pages/osx/launchctl.md
  pages/windows/wget.md
Labels: page edit, translation, minor change

#12188 pnmpsnr: add Spanish translation
  pages.es/common/pnmpsnr.md
Labels: translation

#12205 man: update page
  pages/linux/man.md
Labels: page edit

#12202 pbmnoise, pgmhist, pgmkernel, pgmnoise, pgmramp, pgmtexture: add pages; ppmhist: modify page
  pages/common/pbmnoise.md
  pages/common/pgmhist.md
  pages/common/pgmkernel.md
  pages/common/pgmnoise.md
  pages/common/pgmramp.md
  pages/common/pgmtexture.md
  pages/common/ppmhist.md
Labels: page edit, new command

#12169 {get,set}facl: update & unify style
  pages/linux/getfacl.md
  pages/linux/setfacl.md
Labels: page edit

#12193 rsync: update Chinese translation
  pages.zh/common/rsync.md
Labels: translation

#12197 pamcomp, pnmcomp, pnmconvol, pnmcrop, pnmgamma: add pages
  pages/common/pamcomp.md
  pages/common/pnmcomp.md
  pages/common/pnmconvol.md
  pages/common/pnmcrop.md
  pages/common/pnmgamma.md
Labels: new command

#12189 pnmhisteq, pnmhistmap, pnmindex, pnminvert: add pages
  pages/common/pnmhisteq.md
  pages/common/pnmhistmap.md
  pages/common/pnmindex.md
  pages/common/pnminvert.md
Labels: new command

#12208 pkg: add Spanish translation
  pages.es/freebsd/pkg.md
Labels: translation

#12203 bru: add page
  pages/common/bru.md
Labels: new command

#12138 alien: add debtap to see also section
  pages/linux/alien.md
Labels: page edit, minor change

#12206 naabu: add page
  pages/common/naabu.md
Labels: new command

#12213 minikube: update documentation link
  pages/common/minikube.md
Labels: page edit

#12210 kdesrc-build: update page
  pages/linux/kdesrc-build.md
Labels: page edit, minor change

#12207 look: add Spanish translation
  pages.es/freebsd/look.md
Labels: translation

#12211 redshift: edit page
  pages/common/redshift.md
Labels: page edit

#12215 parallel: fix example
  pages/common/parallel.md
Labels: page edit

#12218 naabu: fix typo
  pages/common/naabu.md
Labels: page edit, minor change

#12216 mat2: add example
  pages/common/mat2.md
Labels: page edit

#12221 zip: follow style guide for compression level placeholder
  pages/common/zip.md
  pages/linux/zip.md
Labels: page edit

#12163 common/nl: update page; linux/nl: add page
  pages/common/nl.md
  pages/linux/nl.md
Labels: page edit, new command

#12187 pnmmargin, pnmmontage, pnmnlfilt, pnmnorm, pnmpad, pnmpaste: add pages
  pages/common/pnmmargin.md
  pages/common/pnmmontage.md
  pages/common/pnmnlfilt.md
  pages/common/pnmnorm.md
  pages/common/pnmpad.md
  pages/common/pnmpaste.md
Labels: new command

#12132 pages*: refine wording
  pages/common/ab.md
  pages/common/adguardhome.md
  pages/common/alacritty.md
  pages/common/ani-cli.md
  pages/common/cavif.md
  pages/common/chezmoi.md
  pages/common/cmatrix.md
  pages/common/cs-java.md
  pages/common/csslint.md
  pages/common/dc.md
  pages/common/dhcpig.md
  pages/common/dua.md
  pages/common/dvc-config.md
  pages/common/fastfetch.md
  pages/common/feh.md
  pages/common/gitui.md
  pages/common/gladtex.md
  pages/common/gnomon.md
  pages/common/goreload.md
  pages/common/gource.md
  pages/common/kdenlive.md
  pages/common/montage.md
  pages/common/msbuild.md
  pages/common/nkf.md
  pages/common/phing.md
  pages/common/ppmtomitsu.md
  pages/common/scrcpy.md
  pages/common/streamlink.md
  pages/common/timeout.md
  pages/common/transmission-cli.md
  pages/common/waitress-serve.md
  pages/common/ybacklight.md
  pages/linux/bmon.md
  pages/linux/compress.md
  pages/linux/cryptcat.md
  pages/linux/handlr.md
  pages/osx/brightness.md
Labels: page edit

#12220 gdal2tils.py: fix zoom placeholders
  pages/common/gdal2tiles.py.md
Labels: page edit

#12222 chcpu: improve example descriptions
  pages/linux/chcpu.md
Labels: page edit

#12143 pages*: add missing mnemonics (part 1)
  pages/android/dumpsys.md
  pages/android/logcat.md
  pages/android/pm.md
  pages/common/ac.md
  pages/common/adb-install.md
  pages/common/adb-logcat.md
  pages/common/ag.md
  pages/common/age-keygen.md
  pages/common/airdecap-ng.md
  pages/common/alacritty.md
  pages/common/amass-db.md
  pages/common/amass-enum.md
  pages/common/amass-intel.md
  pages/common/anki.md
  pages/common/ansible-playbook.md
  pages/common/ansible.md
  pages/common/ant.md
  pages/common/apropos.md
  pages/common/arp.md
  pages/common/arping.md
  pages/common/asciinema.md
  pages/common/atom.md
  pages/common/atoum.md
  pages/common/atq.md
  pages/common/atuin.md
  pages/common/autossh.md
  pages/common/avrdude.md
  pages/common/aws-google-auth.md
  pages/common/axel.md
  pages/common/az-lock.md
  pages/common/az-storage-blob.md
  pages/common/az-storage.md
  pages/common/babeld.md
  pages/common/badblocks.md
Labels: page edit

#12229 tailscale-up: fix page description and improve examples
  pages/common/tailscale-up.md
Labels: page edit

#12226 ncat: add examples
  pages/linux/ncat.md
Labels: page edit

#12228 gammastep: add Spanish translation
  pages.es/common/gammastep.md
Labels: translation

#12233 MAINTAINERS: add @fazlearefin as collaborator
  MAINTAINERS.md
Labels: community

#12232 meshnamed: add page
  pages/common/meshnamed.md
Labels: new command

#12217 bru: add Spanish translation
  pages.es/common/bru.md
Labels: translation

#12157 sed: add Spanish translation
  pages.es/netbsd/sed.md
Labels: translation

#12239 yes: add example
  pages/common/yes.md
Labels: page edit, minor change

#12236 pamditherbw: edit page; atktopbm, pamenlarge, pbmreduce, pbmtext, pbmtextps, pbmtoatk, pbmtobbnbg; add pages
  pages/common/atktopbm.md
  pages/common/pamditherbw.md
  pages/common/pamenlarge.md
  pages/common/pbmreduce.md
  pages/common/pbmtext.md
  pages/common/pbmtextps.md
  pages/common/pbmtoatk.md
  pages/common/pbmtobbnbg.md
Labels: page edit, new command

#12241 naabu: add example
  pages/common/naabu.md
Labels: page edit

#12235 cmuwmtopbm, escp2topbm, pbmtocmuwm, pbmtoepsi, ebmtoepson, pbmtoescp2, pbmtogo: add pages
  pages/common/cmuwmtopbm.md
  pages/common/escp2topbm.md
  pages/common/pbmtocmuwm.md
  pages/common/pbmtoepsi.md
  pages/common/pbmtoepson.md
  pages/common/pbmtoescp2.md
  pages/common/pbmtogo.md
Labels: new command

#12242 git-diff: clarify description of git diff
  pages/common/git-diff.md
Labels: page edit, minor change

#12238 terminalizer, asciinema: update page
  pages/common/asciinema.md
  pages/common/terminalizer.md
Labels: page edit

#12237 pambackground, pamstretch-gen, pamstretch, pbmclean, pbmmask, pbmpage, pbmpscale: add pages
  pages/common/pambackground.md
  pages/common/pamstretch-gen.md
  pages/common/pamstretch.md
  pages/common/pbmclean.md
  pages/common/pbmmask.md
  pages/common/pbmpage.md
  pages/common/pbmpscale.md
Labels: new command

#12246 yabai: use GitHub wiki in more info link and improve examples
  pages/osx/yabai.md
Labels: page edit

#12181 rclone: update page
  pages/common/rclone.md
Labels: page edit

#12248 dd: use -x in pgrep
  pages.de/common/dd.md
  pages.es/osx/dd.md
  pages.it/common/dd.md
  pages.ko/linux/dd.md
  pages.pt_BR/common/dd.md
  pages/linux/dd.md
Labels: page edit, translation

#12247 gifsicle: improve description and examples
  pages/common/gifsicle.md
Labels: page edit

#12183 scripts: use pathlib and avoid page iteration
  scripts/set-more-info-link.py
Labels: tooling

#12250 aria2c: fix multiple url use syntax and add checksum usage
  pages/common/aria2c.md
Labels: page edit

#12251 bless: fix manual section in more info link
  pages/osx/bless.md
Labels: page edit, minor change

#12231 pcapfix: add page
  pages/common/pcapfix.md
Labels: new command

#12256 docs: use switch instead of checkout and fix header levels in contributing-guides/git-terminal
  contributing-guides/git-terminal.md
Labels: documentation

#12260 aws-quicksight: improve page description
  pages/common/aws-quicksight.md
Labels: page edit

#12254 meshnamed: add German translation
  pages.de/common/meshnamed.md
Labels: translation

#12265 jfrog: add alias page
  pages/common/jfrog.md
Labels: new command

#12264 aws-codeartifact: improve page description and examples
  pages/common/aws-codeartifact.md
Labels: page edit

#12262 gouldtoppm, mtvtoppm, pamstack: add pages
  pages/common/gouldtoppm.md
  pages/common/mtvtoppm.md
  pages/common/pamstack.md
Labels: new command

#12261 simplehttpserver: add page
  pages/common/simplehttpserver.md
Labels: new command

#12270 docs: mention PR title in the commit message section
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation

#12269 bless, more, yabai: update more info link
  pages.es/common/more.md
  pages.es/osx/bless.md
  pages.es/osx/yabai.md
  pages.it/common/more.md
  pages.pt_BR/osx/bless.md
  pages.zh/common/more.md
Labels: translation

#12278 subfinder: edit page
  pages/common/subfinder.md
Labels: page edit, minor change

#12252 nuclei: add page
  pages/common/nuclei.md
Labels: new command

#12266 pacman: add Italian translation
  pages.it/linux/pacman.md
Labels: translation

#12283 alien: add Hindi Translation
  pages.hi/linux/alien.md
Labels: translation

#12284 pages*: fix developer.android.com links
  pages/android/am.md
  pages/android/dalvikvm.md
  pages/android/dumpsys.md
  pages/android/logcat.md
  pages/android/pm.md
  pages/android/screencap.md
  pages/common/adb-install.md
  pages/common/adb-logcat.md
  pages/common/adb-reverse.md
  pages/common/adb-shell.md
  pages/common/adb.md
  pages/common/bundletool-dump.md
  pages/common/bundletool-validate.md
  pages/common/bundletool.md
  pages/common/sdkmanager.md
  pages/common/zipalign.md
Labels: page edit

#12279 httpx: add page
  pages/common/httpx.md
Labels: new command

#12282 cal: update Dutch translation
  pages.nl/linux/cal.md
Labels: translation

#12292 golangci-lint: add page
  pages/common/golangci-lint.md
Labels: new command

#12151 pages*: add missing mnemonics
  pages/android/am.md
  pages/common/banner.md
  pages/common/bash.md
  pages/common/batch.md
  pages/common/bb.md
  pages/common/beanstalkd.md
  pages/common/bedtools.md
  pages/common/bindkey.md
  pages/common/black.md
  pages/common/bmaptool.md
  pages/common/bosh.md
  pages/common/box.md
  pages/common/boxes.md
  pages/common/brotli.md
  pages/common/bup.md
  pages/common/bzip2.md
  pages/common/bzip3.md
  pages/common/c99.md
  pages/common/calc.md
  pages/common/calibredb.md
  pages/common/cancel.md
  pages/common/carbon-now.md
  pages/common/cat.md
  pages/common/cdk.md
  pages/common/certutil.md
  pages/common/chafa.md
Labels: page edit

#12295 vcpkg: add page
  pages/common/vcpkg.md
Labels: new command

#12297 strace: update page
  pages/linux/strace.md
Labels: page edit

#12275 usql: add page
  pages/common/usql.md
Labels: new command

#12302 id3v2: use hyphen minus (U+002D) instead of hyphen (U+2010)
  pages/linux/id3v2.md
Labels: page edit, minor change

#12133 CLIENT-SPECIFICATION: remove redirect indicators, use autolinks
  CLIENT-SPECIFICATION.md
Labels: documentation, review needed

#12303 warp-cli: improve page description, add "See also" and add example
  pages/common/warp-cli.md
Labels: page edit

#12212 nextclade: add alignment example
  pages/common/nextclade.md
Labels: page edit

#12276 qmmp: improve examples and page description
  pages/common/qmmp.md
Labels: page edit

#12286 git-gui: add Spanish translation
  pages.es/common/git-gui.md
Labels: translation

#12294 gocr: add page
  pages/common/gocr.md
Labels: new command

#12091 ":": add page
  pages/common/colon.md
Labels: new command

#12311 feat: add reference to other PDFs
  README.md
Labels: documentation

#12310 searchsploit: edit page
  pages/common/searchsploit.md
Labels: page edit

#12298 clementine: improve examples, more info link, and add example
  pages/common/clementine.md
Labels: page edit

#12305 tail: replace "the file" with "it"
  pages/common/tail.md
  pages/osx/tail.md
Labels: page edit, minor change

#12296 fitstopnm, pamcut, pamdeinterlace, pamdice, pammixinterlace, pamtofits, pamundice, pnmtofits: add pages
  pages/common/fitstopnm.md
  pages/common/pamcut.md
  pages/common/pamdeinterlace.md
  pages/common/pamdice.md
  pages/common/pammixinterlace.md
  pages/common/pamtofits.md
  pages/common/pamundice.md
  pages/common/pnmtofits.md
Labels: new command

#12321 hexyl: add French translation
  pages.fr/common/hexyl.md
Labels: translation

#12319 btop: add French translation
  pages.fr/common/btop.md
Labels: translation

#12322 mktemp: add French translation
  pages.fr/common/mktemp.md
Labels: translation

#12338 wm: remove wrong placeholder marks
  pages/android/wm.md
Labels: page edit, minor change

#12333 aur: add page
  pages/linux/aur.md
Labels: new command

#12336 pages*: use "an SQL" instead of "a SQL"
  pages/common/dolt-sql.md
  pages/common/dotnet-ef.md
  pages/common/duckdb.md
  pages/common/gcloud-sql-export-sql.md
  pages/common/mysqlsh.md
  pages/common/textql.md
  pages/linux/dnsrecon.md
Labels: page edit, minor change

#12304 style-guide: update page
  contributing-guides/style-guide.md
Labels: documentation

#12339 repo-add: add barebones example
  pages/linux/repo-add.md
Labels: page edit

#12334 git-clean: add all mnemonics and improve wording
  pages/common/git-clean.md
Labels: page edit

#12341 ^: add page
  pages/common/^.md
Labels: new command

#12326 bats: add page
  pages/common/bats.md
Labels: new command

#12332 ffuf: add French translation
  pages.fr/common/ffuf.md
  pages/common/ffuf.md
Labels: page edit, translation

#12323 fzf: add French translation
  pages.fr/common/fzf.md
Labels: translation

#12345 mpc: update page
  pages/common/mpc.md
Labels: page edit

#12344 jq: fix description and url
  pages/common/jq.md
Labels: page edit

#12340 aur: update page
  pages/linux/aur.md
Labels: page edit, minor change

#12156 df: add Spanish translation
  pages.es/netbsd/df.md
Labels: translation

#12358 docker-rm: fix example
  pages/common/docker-rm.md
Labels: page edit, minor change

#12347 navi: add page
  pages/linux/navi.md
Labels: new command

#12348 trufflehog: add page
  pages/common/trufflehog.md
Labels: new command

#12353 bspwm, bspc: improve descriptions, add "See also" and add example
  pages/linux/bspc.md
  pages/linux/bspwm.md
Labels: page edit

#12355 pages.*: improve pages descriptions conciseness and usefulness
  pages/common/aws-google-auth.md
  pages/common/blackfire.md
  pages/common/convert.md
  pages/common/git-secret.md
  pages/common/gyb.md
  pages/common/jenv.md
  pages/common/json5.md
  pages/common/k8s-unused-secret-detector.md
  pages/common/k8sec.md
  pages/common/lpr.md
  pages/common/minifab.md
  pages/common/nativefier.md
  pages/common/nest.md
  pages/common/tokei.md
  pages/common/zip2john.md
  pages/linux/ausyscall.md
  pages/linux/betterdiscordctl.md
  pages/linux/btrbk.md
  pages/linux/cfdisk.md
  pages/linux/cpufreq-info.md
  pages/linux/dpkg-query.md
  pages/linux/fdisk.md
  pages/linux/fwupdmgr.md
  pages/linux/gdebi.md
  pages/linux/ipset.md
  pages/linux/minicom.md
  pages/linux/update-alternatives.md
  pages/osx/archey.md
  pages/osx/shuf.md
  pages/osx/wacaw.md
  pages/windows/gpupdate.md
Labels: page edit, mass changes

#12314 CONTRIBUTING: document the directory structure
  CONTRIBUTING.md
Labels: documentation

#12346 grubby: add page
  pages/linux/grubby.md
Labels: new command

#12325 select: update page
  pages/linux/select.md
Labels: page edit

#12315 gocr: add Spanish translation
  pages.es/common/gocr.md
Labels: translation

#12373 ncdu: add pt_BR translation
  pages.pt_BR/common/ncdu.md
Labels: translation

#12374 npm: add pt_BR translation
  pages.pt_BR/common/npm.md
Labels: translation

#12378 !: edit page
  pages/common/!.md
Labels: page edit

#12377 ruff, ruff-{check,format}: add page
  pages/common/ruff-check.md
  pages/common/ruff-format.md
  pages/common/ruff.md
Labels: new command

#12394 apt-get: add recommendation for apt
  pages/linux/apt-get.md
Labels: page edit

#12388 poetry: edit page
  pages/common/poetry.md
Labels: page edit

#12369 debuginfod-find: add page
  pages/linux/debuginfod-find.md
Labels: new command

#12329 tgpt: add Spanish translation
  pages.es/common/tgpt.md
Labels: translation

#12330 hexyl: add Spanish translation
  pages.es/common/hexyl.md
Labels: translation

#12362 yuy2topam: add page
  pages/common/yuy2topam.md
Labels: new command

#12342 aur: add Spanish translation
  pages.es/linux/aur.md
Labels: translation

#12350 bats: add Spanish translation
  pages.es/common/bats.md
Labels: translation

#12379 micro: add pt_BR translation
  pages.pt_BR/common/micro.md
Labels: translation

#12381 makepkg: add pt_BR translation
  pages.pt_BR/linux/makepkg.md
Labels: translation
