Repository tldr-pages/tldr, pull requests merged in 2024-11, with the labels that each got.

#14534 cleanup: update README
  README.md
Labels: documentation

#14540 wireplumber: fix typo
  pages/common/wireplumber.md
Labels: page edit, minor change

#14526 tlmgr*: add Korean translation
  pages.ko/common/tlmgr-backup.md
  pages.ko/common/tlmgr-candidates.md
  pages.ko/common/tlmgr-check.md
  pages.ko/common/tlmgr-conf.md
  pages.ko/common/tlmgr-dump-tlpdb.md
  pages.ko/common/tlmgr-generate.md
  pages.ko/common/tlmgr-gui.md
  pages.ko/common/tlmgr-info.md
  pages.ko/common/tlmgr-install.md
  pages.ko/common/tlmgr-key.md
  pages.ko/common/tlmgr-option.md
  pages.ko/common/tlmgr-paper.md
  pages.ko/common/tlmgr-path.md
  pages.ko/common/tlmgr-pinning.md
  pages.ko/common/tlmgr-platform.md
  pages.ko/common/tlmgr-recreate-tlpdb.md
  pages.ko/common/tlmgr-remove.md
  pages.ko/common/tlmgr-repository.md
  pages.ko/common/tlmgr-restore.md
  pages.ko/common/tlmgr-search.md
  pages.ko/common/tlmgr-shell.md
  pages.ko/common/tlmgr-update.md
  pages.ko/common/tlmgr.md
Labels: translation

#14527 xml*: add Korean translation
  pages.ko/common/xml-canonic.md
  pages.ko/common/xml-depyx.md
  pages.ko/common/xml-edit.md
  pages.ko/common/xml-elements.md
  pages.ko/common/xml-escape.md
  pages.ko/common/xml-format.md
  pages.ko/common/xml-list.md
  pages.ko/common/xml-pyx.md
  pages.ko/common/xml-select.md
  pages.ko/common/xml-transform.md
  pages.ko/common/xml-unescape.md
  pages.ko/common/xml-validate.md
  pages.ko/common/xml.md
  pages.ko/common/xmllint.md
  pages.ko/common/xmlstarlet.md
  pages.ko/common/xmlto.md
Labels: translation

#14525 pueue*: add Korean translation
  pages.ko/common/pueue-add.md
  pages.ko/common/pueue-clean.md
  pages.ko/common/pueue-completions.md
  pages.ko/common/pueue-edit.md
  pages.ko/common/pueue-enqueue.md
  pages.ko/common/pueue-follow.md
  pages.ko/common/pueue-group.md
  pages.ko/common/pueue-help.md
  pages.ko/common/pueue-kill.md
  pages.ko/common/pueue-log.md
  pages.ko/common/pueue-parallel.md
  pages.ko/common/pueue-pause.md
  pages.ko/common/pueue-remove.md
  pages.ko/common/pueue-reset.md
  pages.ko/common/pueue-restart.md
  pages.ko/common/pueue-send.md
  pages.ko/common/pueue-shutdown.md
  pages.ko/common/pueue-start.md
  pages.ko/common/pueue-stash.md
  pages.ko/common/pueue-status.md
  pages.ko/common/pueue-switch.md
  pages.ko/common/pueue.md
Labels: translation

#14522 common/u*: add and update Korean translation
  pages.ko/common/u3d.md
  pages.ko/common/ufraw-batch.md
  pages.ko/common/ugrep.md
  pages.ko/common/ulimit.md
  pages.ko/common/umask.md
  pages.ko/common/unalias.md
  pages.ko/common/unar.md
  pages.ko/common/unclutter.md
  pages.ko/common/uncrustify.md
  pages.ko/common/unexpand.md
  pages.ko/common/unflatten.md
  pages.ko/common/unimatrix.md
  pages.ko/common/uniq.md
  pages.ko/common/unison.md
  pages.ko/common/units.md
  pages.ko/common/unlink.md
  pages.ko/common/unp.md
  pages.ko/common/unrar.md
  pages.ko/common/unset.md
  pages.ko/common/unzip.md
  pages.ko/common/unzstd.md
  pages.ko/common/updog.md
  pages.ko/common/upt.md
  pages.ko/common/upx.md
  pages.ko/common/users.md
  pages.ko/common/usql.md
  pages.ko/common/uudecode.md
  pages.ko/common/uuencode.md
  pages.ko/common/uv-python.md
  pages.ko/common/uv-tool.md
  pages.ko/common/uv.md
  pages.ko/common/uvicorn.md
Labels: translation

#14521 common/y*: add Korean translation
  pages.ko/common/ya.md
  pages.ko/common/yacas.md
  pages.ko/common/yacc.md
  pages.ko/common/yadm-alt.md
  pages.ko/common/yadm-bootstrap.md
  pages.ko/common/yadm-clone.md
  pages.ko/common/yadm-config.md
  pages.ko/common/yadm-decrypt.md
  pages.ko/common/yadm-encrypt.md
  pages.ko/common/yadm-enter.md
  pages.ko/common/yadm-git-crypt.md
  pages.ko/common/yadm-gitconfig.md
  pages.ko/common/yadm-init.md
  pages.ko/common/yadm-introspect.md
  pages.ko/common/yadm-list.md
  pages.ko/common/yadm-perms.md
  pages.ko/common/yadm-transcrypt.md
  pages.ko/common/yadm-upgrade.md
  pages.ko/common/yadm.md
  pages.ko/common/yank.md
  pages.ko/common/yapf.md
  pages.ko/common/yard.md
  pages.ko/common/yazi.md
  pages.ko/common/ybacklight.md
  pages.ko/common/ybmtopbm.md
  pages.ko/common/yes.md
  pages.ko/common/yesod.md
  pages.ko/common/ykinfo.md
  pages.ko/common/ykman-config.md
  pages.ko/common/ykman-fido.md
  pages.ko/common/ykman-oath.md
  pages.ko/common/ykman-openpgp.md
  pages.ko/common/ykman.md
  pages.ko/common/yolo.md
  pages.ko/common/you-get.md
  pages.ko/common/youtube-dl.md
  pages.ko/common/youtube-viewer.md
  pages.ko/common/yq.md
  pages.ko/common/yt-dlp.md
  pages.ko/common/yuvsplittoppm.md
  pages.ko/common/yuvtoppm.md
  pages.ko/common/yuy2topam.md
Labels: translation

#14544 MAINTAINERS: add @karthik-script as collaborator
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: community

#14520 common/z*: add Korean translation
  pages.ko/common/z.md
  pages.ko/common/zapier-analytics.md
  pages.ko/common/zapier-build.md
  pages.ko/common/zapier-convert.md
  pages.ko/common/zapier-init.md
  pages.ko/common/zapier-push.md
  pages.ko/common/zapier-scaffold.md
  pages.ko/common/zapier.md
  pages.ko/common/zbarimg.md
  pages.ko/common/zcat.md
  pages.ko/common/zcmp.md
  pages.ko/common/zdb.md
  pages.ko/common/zdiff.md
  pages.ko/common/zeek.md
  pages.ko/common/zegrep.md
  pages.ko/common/zeisstopnm.md
  pages.ko/common/zek.md
  pages.ko/common/zellij.md
  pages.ko/common/zfgrep.md
  pages.ko/common/zfs.md
  pages.ko/common/zgrep.md
  pages.ko/common/zig.md
  pages.ko/common/zint.md
  pages.ko/common/zip.md
  pages.ko/common/zip2john.md
  pages.ko/common/zipalign.md
  pages.ko/common/zipcloak.md
  pages.ko/common/zipgrep.md
  pages.ko/common/zipinfo.md
  pages.ko/common/zipnote.md
  pages.ko/common/zless.md
  pages.ko/common/zlib-flate.md
  pages.ko/common/zm.md
  pages.ko/common/zmore.md
  pages.ko/common/zmv.md
  pages.ko/common/znew.md
  pages.ko/common/zopflipng.md
  pages.ko/common/zotero.md
  pages.ko/common/zoxide.md
  pages.ko/common/zpool.md
  pages.ko/common/zrun.md
  pages.ko/common/zsh.md
  pages.ko/common/zstd.md
  pages.ko/common/zstdcat.md
  pages.ko/common/zstdless.md
  pages.ko/common/zstdmt.md
  pages.ko/common/zsteg.md
Labels: translation

#14519 ssh*: add and update Korean translation
  pages.ko/common/ssh-add.md
  pages.ko/common/ssh-agent.md
  pages.ko/common/ssh-copy-id.md
  pages.ko/common/ssh-keygen.md
  pages.ko/common/ssh-keyscan.md
  pages.ko/common/ssh.md
  pages.ko/common/sshd.md
  pages.ko/common/sshfs.md
  pages.ko/common/sshpass.md
  pages.ko/common/sshuttle.md
Labels: translation

#14518 npm*: add and update Korean translation
  pages.ko/common/npm-access.md
  pages.ko/common/npm-adduser.md
  pages.ko/common/npm-audit.md
  pages.ko/common/npm-cache.md
  pages.ko/common/npm-dedupe.md
  pages.ko/common/npm-doctor.md
  pages.ko/common/npm-find-dupes.md
  pages.ko/common/npm-home.md
  pages.ko/common/npm-init.md
  pages.ko/common/npm-install.md
  pages.ko/common/npm-name.md
  pages.ko/common/npm-outdated.md
  pages.ko/common/npm-restart.md
  pages.ko/common/npm-run-script.md
  pages.ko/common/npm-run.md
  pages.ko/common/npm-search.md
  pages.ko/common/npm-start.md
  pages.ko/common/npm-stop.md
  pages.ko/common/npm-team.md
  pages.ko/common/npm-test.md
  pages.ko/common/npm-token.md
  pages.ko/common/npm-uninstall.md
  pages.ko/common/npm-unpublish.md
  pages.ko/common/npm-update.md
  pages.ko/common/npm-version.md
  pages.ko/common/npm-view.md
  pages.ko/common/npm-why.md
  pages.ko/common/npm.md
Labels: translation

#14516 nix*: add Korean translation
  pages.ko/common/nix-build.md
  pages.ko/common/nix-classic.md
  pages.ko/common/nix-collect-garbage.md
  pages.ko/common/nix-env.md
  pages.ko/common/nix-shell.md
  pages.ko/common/nix-store.md
  pages.ko/common/nix.md
  pages.ko/common/nix3-build.md
  pages.ko/common/nix3-develop.md
  pages.ko/common/nix3-edit.md
  pages.ko/common/nix3-flake.md
  pages.ko/common/nix3-profile.md
  pages.ko/common/nix3-registry.md
  pages.ko/common/nix3-repl.md
  pages.ko/common/nix3-run.md
  pages.ko/common/nix3-search.md
  pages.ko/common/nix3-shell.md
  pages.ko/common/nix3-store.md
  pages.ko/common/nix3-why-depends.md
  pages.ko/common/nixpkgs-review.md
Labels: translation

#14515 dotnet*: add and update Korean translation
  pages.ko/common/dotnet-add-package.md
  pages.ko/common/dotnet-add-reference.md
  pages.ko/common/dotnet-build.md
  pages.ko/common/dotnet-ef.md
  pages.ko/common/dotnet-publish.md
  pages.ko/common/dotnet-restore.md
  pages.ko/common/dotnet-run.md
  pages.ko/common/dotnet-test.md
  pages.ko/common/dotnet-tool.md
  pages.ko/common/dotnet.md
Labels: translation

#14504 ifconfig: correct placeholders
  pages/common/ifconfig.md
Labels: page edit

#14433 bats: update Spanish translation
  pages.es/common/bats.md
Labels: translation, hacktoberfest-accepted

#14445 az: update Spanish translation
  pages.es/common/az.md
Labels: translation, hacktoberfest-accepted

#14446 chown: update Spanish translation
  pages.es/common/chown.md
Labels: translation, hacktoberfest-accepted

#14447 chsh: update Spanish translation
  pages.es/common/chsh.md
Labels: translation, hacktoberfest-accepted

#14533 ne*,nfstat,ni,nvm,o*: add Korean translation
  pages.ko/windows/net.md
  pages.ko/windows/netsh-interface-portproxy.md
  pages.ko/windows/new-item.md
  pages.ko/windows/nfsstat.md
  pages.ko/windows/ni.md
  pages.ko/windows/nvm.md
  pages.ko/windows/octo.md
  pages.ko/windows/ospp.vbs.md
  pages.ko/windows/out-string.md
Labels: translation

#14427 windows/reg*: add Korean translation
  pages.ko/windows/reg-add.md
  pages.ko/windows/reg-compare.md
  pages.ko/windows/reg-copy.md
  pages.ko/windows/reg-delete.md
  pages.ko/windows/reg-export.md
  pages.ko/windows/reg-import.md
  pages.ko/windows/reg-load.md
  pages.ko/windows/reg-query.md
  pages.ko/windows/reg-restore.md
  pages.ko/windows/reg-save.md
  pages.ko/windows/reg-unload.md
  pages.ko/windows/reg.md
Labels: translation, hacktoberfest-accepted

#14514 common/q*: add Korean translation; qemu: add missing placeholders
  pages.ko/common/q.md
  pages.ko/common/qalc.md
  pages.ko/common/qc.md
  pages.ko/common/qcp.md
  pages.ko/common/qdbus.md
  pages.ko/common/qemu-img.md
  pages.ko/common/qemu.md
  pages.ko/common/qmmp.md
  pages.ko/common/qmv.md
  pages.ko/common/qoitopam.md
  pages.ko/common/qownnotes.md
  pages.ko/common/qr.md
  pages.ko/common/qrencode.md
  pages.ko/common/qrttoppm.md
  pages.ko/common/qtcreator.md
  pages.ko/common/quarkus.md
  pages.ko/common/quarto.md
  pages.ko/common/quilt.md
  pages.ko/common/quota.md
  pages.ko/common/qutebrowser.md
  pages/common/qemu.md
Labels: page edit, translation

#14319 tar: update page
  pages/common/tar.md
Labels: page edit, hacktoberfest-accepted

#14549 sed: add Hindi translation
  pages.hi/openbsd/sed.md
Labels: translation

#14548 pkg: add Hindi translation
  pages.hi/openbsd/pkg.md
Labels: translation

#14547 pkg_info: add Hindi translation
  pages.hi/openbsd/pkg_info.md
Labels: translation

#14546 pkg_delete: add Hindi translation
  pages.hi/openbsd/pkg_delete.md
Labels: translation

#14545 pkg_add: add Hindi translation
  pages.hi/openbsd/pkg_add.md
Labels: translation

#14560 common/k*: add Korean translation
  pages.ko/common/k3d.md
  pages.ko/common/k6.md
  pages.ko/common/k8s-unused-secret-detector.md
  pages.ko/common/k8sec.md
  pages.ko/common/k9s.md
  pages.ko/common/kaggle.md
  pages.ko/common/kahlan.md
  pages.ko/common/kak.md
  pages.ko/common/katana.md
  pages.ko/common/kate.md
  pages.ko/common/kcadm.sh.md
  pages.ko/common/kcat.md
  pages.ko/common/kdeconnect-cli.md
  pages.ko/common/kdenlive.md
  pages.ko/common/kdig.md
  pages.ko/common/keep-header.md
  pages.ko/common/keepass2.md
  pages.ko/common/keepassxc-cli.md
  pages.ko/common/keybase.md
  pages.ko/common/keychain.md
  pages.ko/common/keytool.md
  pages.ko/common/khal.md
  pages.ko/common/killall.md
  pages.ko/common/kind.md
  pages.ko/common/kinit.md
  pages.ko/common/kismet.md
  pages.ko/common/kitex.md
  pages.ko/common/kitty.md
  pages.ko/common/kiwi-ng.md
  pages.ko/common/knife.md
  pages.ko/common/knotc.md
  pages.ko/common/kompose.md
  pages.ko/common/kool.md
  pages.ko/common/kopia.md
  pages.ko/common/kops.md
  pages.ko/common/kosmorro.md
  pages.ko/common/kotlin.md
  pages.ko/common/kotlinc.md
  pages.ko/common/krita.md
  pages.ko/common/krunvm.md
  pages.ko/common/ksh.md
Labels: translation

#14559 py*: add Korean translation
  pages.ko/common/py-spy.md
  pages.ko/common/pyats-shell.md
  pages.ko/common/pyats-version.md
  pages.ko/common/pyats.md
  pages.ko/common/pycodestyle.md
  pages.ko/common/pydoc.md
  pages.ko/common/pydocstyle.md
  pages.ko/common/pyenv-virtualenv.md
  pages.ko/common/pyenv.md
  pages.ko/common/pyflakes.md
  pages.ko/common/pygmentize.md
  pages.ko/common/pyinfra.md
  pages.ko/common/pylint.md
  pages.ko/common/pypy.md
  pages.ko/common/pystun3.md
  pages.ko/common/pytest.md
  pages.ko/common/python.md
Labels: translation

#14573 m*: add and update Korean translation
  pages.ko/windows/measure-command.md
  pages.ko/windows/measure-object.md
  pages.ko/windows/mi.md
  pages.ko/windows/microsoft-edge.md
  pages.ko/windows/mkdir.md
  pages.ko/windows/mklink.md
  pages.ko/windows/more.md
  pages.ko/windows/mount.md
  pages.ko/windows/move-item.md
  pages.ko/windows/move.md
  pages.ko/windows/msedge.md
  pages.ko/windows/msg.md
  pages.ko/windows/msiexec.md
  pages.ko/windows/mv.md
Labels: translation

#14554 pio*: add Korean translation
  pages.ko/common/pio-access.md
  pages.ko/common/pio-account.md
  pages.ko/common/pio-boards.md
  pages.ko/common/pio-check.md
  pages.ko/common/pio-ci.md
  pages.ko/common/pio-debug.md
  pages.ko/common/pio-device.md
  pages.ko/common/pio-home.md
  pages.ko/common/pio-lib.md
  pages.ko/common/pio-org.md
  pages.ko/common/pio-package.md
  pages.ko/common/pio-platform.md
  pages.ko/common/pio-project.md
  pages.ko/common/pio-remote.md
  pages.ko/common/pio-run.md
  pages.ko/common/pio-settings.md
  pages.ko/common/pio-system.md
  pages.ko/common/pio-team.md
  pages.ko/common/pio-test.md
  pages.ko/common/pio-update.md
  pages.ko/common/pio-upgrade.md
  pages.ko/common/pio.md
Labels: translation

#14578 MAINTAINERS: add @Zamoca42 as collaborator
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: community

#14572 ypchsh: add Hindi translation
  pages.hi/freebsd/ypchsh.md
Labels: translation

#14571 ypchpass: add Hindi translation
  pages.hi/freebsd/ypchpass.md
Labels: translation

#14570 ypchfn: add Hindi translation
  pages.hi/freebsd/ypchfn.md
Labels: translation

#14580 npm-whoami: add page
  pages/common/npm-whoami.md
Labels: new command

#14531 npm-star: add page
  pages/common/npm-star.md
Labels: new command

#14581 npm-root: add page
  pages/common/npm-root.md
Labels: new command

#14535 bdfr: add page
  pages/common/bdfr.md
Labels: new command

#14583 npm-unstar: add page
  pages/common/npm-unstar.md
Labels: new command

#14566 df: add Hindi translation
  pages.hi/freebsd/df.md
Labels: translation

#14567 look: add Hindi translation
  pages.hi/freebsd/look.md
Labels: translation

#14564 chfn: add Hindi translation
  pages.hi/freebsd/chfn.md
Labels: translation

#14562 base64: add Hindi translation
  pages.hi/freebsd/base64.md
Labels: translation

#14563 cal: add Hindi translation
  pages.hi/freebsd/cal.md
Labels: translation

#14565 chsh: add Hindi translation
  pages.hi/freebsd/chsh.md
Labels: translation

#14505 chromium: add Dutch translation
  pages.nl/windows/chromium.md
Labels: translation

#14496 atom: add Hindi translation
  pages.hi/common/atom.md
Labels: translation, hacktoberfest-accepted

#14495 bfs: add Hindi translation
  pages.hi/common/bfs.md
Labels: translation, hacktoberfest-accepted

#14494 npm-init: add Hindi translation
  pages.hi/common/npm-init.md
Labels: translation, hacktoberfest-accepted

#14543 git-tag: update Spanish translation
  pages.es/common/git-tag.md
Labels: translation

#14511 htop: update Spanish translation
  pages.es/common/htop.md
Labels: translation

#14510 kill: update Spanish translation
  pages.es/common/kill.md
Labels: translation

#14508 mkfifo: update Spanish translation
  pages.es/common/mkfifo.md
Labels: translation

#14456 nnn: update Spanish translation
  pages.es/common/nnn.md
Labels: translation, hacktoberfest-accepted

#14584 bear, brave, bundler, hi*, hn, holehe: add Korean translation
  pages.ko/common/bear.md
  pages.ko/common/brave.md
  pages.ko/common/bundler.md
  pages.ko/common/highlight.md
  pages.ko/common/hipstopgm.md
  pages.ko/common/histexpand.md
  pages.ko/common/history.md
  pages.ko/common/hive.md
  pages.ko/common/hn.md
  pages.ko/common/holehe.md
Labels: translation

#14582 at, bugreportz, bundle: update Korean translation
  pages.ko/android/bugreportz.md
  pages.ko/common/at.md
  pages.ko/common/bundle.md
Labels: translation

#14569 sockstat: add Hindi translation
  pages.hi/freebsd/sockstat.md
Labels: translation

#14493 findstr: add Hindi Translation
  pages.hi/windows/findstr.md
Labels: translation, hacktoberfest-accepted, review needed

#14586 tar: update page
  pages/common/tar.md
Labels: page edit, minor change

#14524 windows/get*: add Korean translation
  pages.ko/windows/get-acl.md
  pages.ko/windows/get-alias.md
  pages.ko/windows/get-childitem.md
  pages.ko/windows/get-command.md
  pages.ko/windows/get-content.md
  pages.ko/windows/get-date.md
  pages.ko/windows/get-dedupproperties.md
  pages.ko/windows/get-filehash.md
  pages.ko/windows/get-help.md
  pages.ko/windows/get-history.md
  pages.ko/windows/get-location.md
  pages.ko/windows/get-wuapiversion.md
  pages.ko/windows/get-wuhistory.md
  pages.ko/windows/get-wusettings.md
  pages.ko/windows/getmac.md
Labels: page edit, translation

#14598 ho*, hp*, hr, hs*, html5validator: add Korean translation
  pages.ko/common/home-manager.md
  pages.ko/common/host.md
  pages.ko/common/hostapd.md
  pages.ko/common/hostess.md
  pages.ko/common/hostid.md
  pages.ko/common/hostname.md
  pages.ko/common/hping.md
  pages.ko/common/hping3.md
  pages.ko/common/hr.md
  pages.ko/common/hsd-cli.md
  pages.ko/common/hsw-cli.md
  pages.ko/common/html5validator.md
Labels: translation

#14432 bat: update Spanish translation
  pages.es/common/bat.md
Labels: translation, hacktoberfest-accepted

#14557 common/v*: add and update Korean translation
  pages.ko/common/vagrant.md
  pages.ko/common/vala.md
  pages.ko/common/valac.md
  pages.ko/common/vale.md
  pages.ko/common/valgrind.md
  pages.ko/common/var-dump-server.md
  pages.ko/common/varnishlog.md
  pages.ko/common/vault.md
  pages.ko/common/vcpkg.md
  pages.ko/common/vcsh.md
  pages.ko/common/vdir.md
  pages.ko/common/vectorize-pixelart.md
  pages.ko/common/vegeta.md
  pages.ko/common/vela.md
  pages.ko/common/velero.md
  pages.ko/common/venv.md
  pages.ko/common/verilator.md
  pages.ko/common/vertical-bar.md
  pages.ko/common/vf.md
  pages.ko/common/vgmstream_cli.md
  pages.ko/common/vgrep.md
  pages.ko/common/vhs.md
  pages.ko/common/vidir.md
  pages.ko/common/view.md
  pages.ko/common/vifm.md
  pages.ko/common/vim.md
  pages.ko/common/vimdiff.md
  pages.ko/common/vimtutor.md
  pages.ko/common/vinmap.md
  pages.ko/common/vipe.md
  pages.ko/common/virt-clone.md
  pages.ko/common/virt-install.md
  pages.ko/common/virt-qemu-run.md
  pages.ko/common/virt-sparsify.md
  pages.ko/common/virt-sysprep.md
  pages.ko/common/virtualenv.md
  pages.ko/common/virtualenvwrapper.md
  pages.ko/common/visudo.md
  pages.ko/common/viu.md
  pages.ko/common/vivaldi.md
  pages.ko/common/vladimyr.md
  pages.ko/common/vlc.md
  pages.ko/common/volta.md
  pages.ko/common/vsce.md
  pages.ko/common/vt.md
  pages.ko/common/vue-build.md
  pages.ko/common/vue-init.md
  pages.ko/common/vue-serve.md
  pages.ko/common/vue.md
  pages.ko/common/vulkaninfo.md
Labels: translation

#14449 du: update Spanish translation
  pages.es/common/du.md
Labels: translation, hacktoberfest-accepted

#14610 hatch: add page
  pages/common/hatch.md
Labels: new command

#14605 npm-{owner, author}: add page
  pages/common/npm-author.md
  pages/common/npm-owner.md
Labels: new command

#14594 stripe: update documentation link
  pages/common/stripe.md
Labels: page edit

#14595 go-test: update documentation link
  pages.ko/common/go-test.md
  pages.tr/common/go-test.md
  pages/common/go-test.md
Labels: page edit, translation

#14592 terraform-plan: update documentation link
  pages.de/common/terraform-plan.md
  pages/common/terraform-plan.md
Labels: page edit, translation

#14574 set-alias-page: use translated regex
  scripts/set-alias-page.py
Labels: tooling

#14552 git-add: update Spanish translation
  pages.es/common/git-add.md
Labels: translation

#14568 sed: add Hindi translation
  pages.hi/freebsd/sed.md
Labels: translation

#14608 http*: add Korean translation
  pages.ko/common/http-server-upload.md
  pages.ko/common/http-server.md
  pages.ko/common/http.md
  pages.ko/common/httpflow.md
  pages.ko/common/httpie.md
  pages.ko/common/httping.md
  pages.ko/common/httprobe.md
  pages.ko/common/httpry.md
  pages.ko/common/https.md
  pages.ko/common/httpx.md
Labels: translation

#14609 hub*: add Korean translation
  pages.ko/common/hub-branch.md
  pages.ko/common/hub-browse.md
  pages.ko/common/hub-ci-status.md
  pages.ko/common/hub-clone.md
  pages.ko/common/hub-create.md
  pages.ko/common/hub-delete.md
  pages.ko/common/hub-fork.md
  pages.ko/common/hub-init.md
  pages.ko/common/hub-issue.md
  pages.ko/common/hub.md
Labels: translation

#14606 netstat,logoff,i*: add Korean translation
  pages.ko/windows/if.md
  pages.ko/windows/install-module.md
  pages.ko/windows/invoke-item.md
  pages.ko/windows/invoke-webrequest.md
  pages.ko/windows/ipconfig.md
  pages.ko/windows/iscc.md
  pages.ko/windows/logoff.md
  pages.ko/windows/netstat.md
Labels: translation

#14596 atuin: add Chinese translation
  pages.zh/common/atuin.md
Labels: translation

#14590 terraform-fmt: update documentation link
  pages.de/common/terraform-fmt.md
  pages/common/terraform-fmt.md
Labels: page edit, translation

#14589 rails-db: update documentation link
  pages.id/common/rails-db.md
  pages/common/rails-db.md
Labels: page edit, translation

#14507 get-history: add Dutch translation
  pages.nl/windows/get-history.md
Labels: translation

#14506 color: add Dutch translation
  pages.nl/windows/color.md
Labels: translation

#14604 npm-org: add page
  pages/common/npm-org.md
Labels: new command

#14619 basename: fix typo
  pages/common/basename.md
Labels: page edit, minor change

#14617 ia, ib*, ic*: add Korean translation
  pages.ko/common/ia.md
  pages.ko/common/ibmcloud-login.md
  pages.ko/common/ibmcloud.md
  pages.ko/common/ical.md
  pages.ko/common/icontopbm.md
  pages.ko/common/iconv.md
Labels: translation

#14615 hu*, hy*: add Korean translation
  pages.ko/common/huggingface-cli.md
  pages.ko/common/hugo-server.md
  pages.ko/common/hugo.md
  pages.ko/common/hunspell.md
  pages.ko/common/hut.md
  pages.ko/common/hydra.md
  pages.ko/common/hyperfine.md
Labels: translation

#14611 ghcid: add page
  pages/common/ghcid.md
Labels: new command

#14630 php*: add Korean translation
  pages.ko/common/php-artisan.md
  pages.ko/common/php-coveralls.md
  pages.ko/common/php-cs-fixer.md
  pages.ko/common/php-yii.md
  pages.ko/common/php.md
  pages.ko/common/phpbu.md
  pages.ko/common/phpcbf.md
  pages.ko/common/phpcpd.md
  pages.ko/common/phpcs.md
  pages.ko/common/phpdox.md
  pages.ko/common/phpenv.md
  pages.ko/common/phpize.md
  pages.ko/common/phploc.md
  pages.ko/common/phpmd.md
  pages.ko/common/phpspec.md
  pages.ko/common/phpstan.md
  pages.ko/common/phpstorm.md
  pages.ko/common/phpunit.md
Labels: translation

#14631 pgm*: add Korean translation
  pages.ko/common/pgmbentley.md
  pages.ko/common/pgmcrater.md
  pages.ko/common/pgmdeshadow.md
  pages.ko/common/pgmedge.md
  pages.ko/common/pgmenhance.md
  pages.ko/common/pgmhist.md
  pages.ko/common/pgmkernel.md
  pages.ko/common/pgmmake.md
  pages.ko/common/pgmnoise.md
  pages.ko/common/pgmnorm.md
  pages.ko/common/pgmoil.md
  pages.ko/common/pgmramp.md
  pages.ko/common/pgmslice.md
  pages.ko/common/pgmtexture.md
  pages.ko/common/pgmtofs.md
  pages.ko/common/pgmtolispm.md
  pages.ko/common/pgmtopbm.md
  pages.ko/common/pgmtopgm.md
  pages.ko/common/pgmtoppm.md
  pages.ko/common/pgmtosbig.md
  pages.ko/common/pgmtost4.md
Labels: translation

#14632 ppm*: add Korean translation
  pages.ko/common/ppmbrighten.md
  pages.ko/common/ppmchange.md
  pages.ko/common/ppmcie.md
  pages.ko/common/ppmcolormask.md
  pages.ko/common/ppmdim.md
  pages.ko/common/ppmdist.md
  pages.ko/common/ppmdither.md
  pages.ko/common/ppmfade.md
  pages.ko/common/ppmflash.md
  pages.ko/common/ppmforge.md
  pages.ko/common/ppmhist.md
  pages.ko/common/ppmlabel.md
  pages.ko/common/ppmmake.md
  pages.ko/common/ppmmix.md
  pages.ko/common/ppmnorm.md
  pages.ko/common/ppmntsc.md
  pages.ko/common/ppmpat.md
  pages.ko/common/ppmquant.md
  pages.ko/common/ppmquantall.md
  pages.ko/common/ppmrainbow.md
  pages.ko/common/ppmrelief.md
  pages.ko/common/ppmshadow.md
  pages.ko/common/ppmshift.md
  pages.ko/common/ppmspread.md
  pages.ko/common/ppmtoacad.md
  pages.ko/common/ppmtoarbtxt.md
  pages.ko/common/ppmtoascii.md
  pages.ko/common/ppmtobmp.md
  pages.ko/common/ppmtoeyuv.md
  pages.ko/common/ppmtogif.md
  pages.ko/common/ppmtoicr.md
  pages.ko/common/ppmtoilbm.md
  pages.ko/common/ppmtojpeg.md
  pages.ko/common/ppmtoleaf.md
  pages.ko/common/ppmtolj.md
  pages.ko/common/ppmtomap.md
  pages.ko/common/ppmtomitsu.md
  pages.ko/common/ppmtompeg.md
  pages.ko/common/ppmtoneo.md
  pages.ko/common/ppmtopcx.md
  pages.ko/common/ppmtopgm.md
  pages.ko/common/ppmtopi1.md
  pages.ko/common/ppmtopict.md
  pages.ko/common/ppmtopj.md
  pages.ko/common/ppmtoppm.md
  pages.ko/common/ppmtopuzz.md
  pages.ko/common/ppmtosixel.md
  pages.ko/common/ppmtospu.md
  pages.ko/common/ppmtoterm.md
  pages.ko/common/ppmtotga.md
  pages.ko/common/ppmtouil.md
  pages.ko/common/ppmtowinicon.md
  pages.ko/common/ppmtoxpm.md
  pages.ko/common/ppmtoyuv.md
  pages.ko/common/ppmtoyuvsplit.md
  pages.ko/common/ppmtv.md
Labels: translation

#14635 common/x*: add Korean translation
  pages.ko/common/x11docker.md
  pages.ko/common/x_x.md
  pages.ko/common/xar.md
  pages.ko/common/xargs.md
  pages.ko/common/xbmtopbm.md
  pages.ko/common/xcaddy.md
  pages.ko/common/xcv.md
  pages.ko/common/xdelta.md
  pages.ko/common/xe.md
  pages.ko/common/xephyr.md
  pages.ko/common/xetex.md
  pages.ko/common/xev.md
  pages.ko/common/xgettext.md
  pages.ko/common/xh.md
  pages.ko/common/xidel.md
  pages.ko/common/ximtoppm.md
  pages.ko/common/xkcdpass.md
  pages.ko/common/xkill.md
  pages.ko/common/xmake.md
  pages.ko/common/xo.md
  pages.ko/common/xonsh.md
  pages.ko/common/xplr.md
  pages.ko/common/xpmtoppm.md
  pages.ko/common/xprop.md
  pages.ko/common/xsp.md
  pages.ko/common/xsv.md
  pages.ko/common/xteddy.md
  pages.ko/common/xvminitoppm.md
  pages.ko/common/xwdtopnm.md
  pages.ko/common/xwininfo.md
  pages.ko/common/xxd.md
  pages.ko/common/xxh.md
  pages.ko/common/xz.md
  pages.ko/common/xzcmp.md
  pages.ko/common/xzdiff.md
  pages.ko/common/xzegrep.md
  pages.ko/common/xzfgrep.md
  pages.ko/common/xzgrep.md
  pages.ko/common/xzless.md
  pages.ko/common/xzmore.md
Labels: translation

#14638 style-guide.zh: fix unnecessary spaces in examples
  contributing-guides/style-guide.zh.md
Labels: documentation

#14576 ifconfig: update Dutch translation
  pages.nl/common/ifconfig.md
Labels: translation

#14634 pnm*: add Korean translation
  pages.ko/common/pnmalias.md
  pages.ko/common/pnmarith.md
  pages.ko/common/pnmcolormap.md
  pages.ko/common/pnmcomp.md
  pages.ko/common/pnmconvol.md
  pages.ko/common/pnmcrop.md
  pages.ko/common/pnmcut.md
  pages.ko/common/pnmdepth.md
  pages.ko/common/pnmenlarge.md
  pages.ko/common/pnmfile.md
  pages.ko/common/pnmflip.md
  pages.ko/common/pnmgamma.md
  pages.ko/common/pnmhisteq.md
  pages.ko/common/pnmhistmap.md
  pages.ko/common/pnmindex.md
  pages.ko/common/pnminterp.md
  pages.ko/common/pnminvert.md
  pages.ko/common/pnmmargin.md
  pages.ko/common/pnmmontage.md
  pages.ko/common/pnmnlfilt.md
  pages.ko/common/pnmnorm.md
  pages.ko/common/pnmpad.md
  pages.ko/common/pnmpaste.md
  pages.ko/common/pnmpsnr.md
  pages.ko/common/pnmquant.md
  pages.ko/common/pnmquantall.md
  pages.ko/common/pnmremap.md
  pages.ko/common/pnmrotate.md
  pages.ko/common/pnmscale.md
  pages.ko/common/pnmscalefixed.md
  pages.ko/common/pnmshear.md
  pages.ko/common/pnmsmooth.md
  pages.ko/common/pnmsplit.md
  pages.ko/common/pnmtile.md
  pages.ko/common/pnmtoddif.md
  pages.ko/common/pnmtofiasco.md
  pages.ko/common/pnmtofits.md
  pages.ko/common/pnmtojpeg.md
  pages.ko/common/pnmtopalm.md
  pages.ko/common/pnmtopclxl.md
  pages.ko/common/pnmtoplainpnm.md
  pages.ko/common/pnmtopng.md
  pages.ko/common/pnmtopnm.md
  pages.ko/common/pnmtops.md
  pages.ko/common/pnmtorast.md
  pages.ko/common/pnmtorle.md
  pages.ko/common/pnmtosgi.md
  pages.ko/common/pnmtosir.md
  pages.ko/common/pnmtotiff.md
  pages.ko/common/pnmtotiffcmyk.md
  pages.ko/common/pnmtoxwd.md
Labels: translation

#14633 pam*: add Korean translation
  pages.ko/common/pamarith.md
  pages.ko/common/pambackground.md
  pages.ko/common/pambrighten.md
  pages.ko/common/pamcomp.md
  pages.ko/common/pamcrater.md
  pages.ko/common/pamcut.md
  pages.ko/common/pamdeinterlace.md
  pages.ko/common/pamdepth.md
  pages.ko/common/pamdice.md
  pages.ko/common/pamditherbw.md
  pages.ko/common/pamedge.md
  pages.ko/common/pamenlarge.md
  pages.ko/common/pamexec.md
  pages.ko/common/pamfile.md
  pages.ko/common/pamfix.md
  pages.ko/common/pamfixtrunc.md
  pages.ko/common/pamflip.md
  pages.ko/common/pamfunc.md
  pages.ko/common/pamixer.md
  pages.ko/common/pammixinterlace.md
  pages.ko/common/pamnoraw.md
  pages.ko/common/pamoil.md
  pages.ko/common/pampick.md
  pages.ko/common/pampop9.md
  pages.ko/common/pamrgbatopng.md
  pages.ko/common/pamscale.md
  pages.ko/common/pamshadedrelief.md
  pages.ko/common/pamslice.md
  pages.ko/common/pamsplit.md
  pages.ko/common/pamstack.md
  pages.ko/common/pamstretch-gen.md
  pages.ko/common/pamstretch.md
  pages.ko/common/pamtofits.md
  pages.ko/common/pamtogif.md
  pages.ko/common/pamtopam.md
  pages.ko/common/pamtopng.md
  pages.ko/common/pamtopnm.md
  pages.ko/common/pamtoqoi.md
  pages.ko/common/pamtotga.md
  pages.ko/common/pamtotiff.md
  pages.ko/common/pamtouil.md
  pages.ko/common/pamtowinicon.md
  pages.ko/common/pamtoxvmini.md
  pages.ko/common/pamundice.md
  pages.ko/common/pamvalidate.md
Labels: translation

#14642 common/o*: add Korean translation
  pages.ko/common/oathtool.md
  pages.ko/common/objdump.md
  pages.ko/common/obs.md
  pages.ko/common/oc.md
  pages.ko/common/ocaml.md
  pages.ko/common/ocamlc.md
  pages.ko/common/ocamlfind.md
  pages.ko/common/ocamlopt.md
  pages.ko/common/octave.md
  pages.ko/common/octez-client.md
  pages.ko/common/od.md
  pages.ko/common/odps-auth.md
  pages.ko/common/odps-func.md
  pages.ko/common/odps-inst.md
  pages.ko/common/odps-resource.md
  pages.ko/common/odps-table.md
  pages.ko/common/odps-tunnel.md
  pages.ko/common/odps.md
  pages.ko/common/offlineimap.md
  pages.ko/common/ogr2ogr.md
  pages.ko/common/ogrinfo.md
  pages.ko/common/ogrmerge.py.md
  pages.ko/common/ohdear-cli.md
  pages.ko/common/okular.md
  pages.ko/common/ollama.md
  pages.ko/common/omf.md
  pages.ko/common/omz.md
  pages.ko/common/onefetch.md
  pages.ko/common/onionsearch.md
  pages.ko/common/ooniprobe.md
  pages.ko/common/op.md
  pages.ko/common/opam.md
  pages.ko/common/open.fish.md
  pages.ko/common/open.md
  pages.ko/common/openai.md
  pages.ko/common/openconnect.md
  pages.ko/common/openscad.md
  pages.ko/common/openttd.md
  pages.ko/common/openvpn.md
  pages.ko/common/opera.md
  pages.ko/common/opt.md
  pages.ko/common/optipng.md
  pages.ko/common/opusenc.md
  pages.ko/common/orca-c.md
  pages.ko/common/osage.md
  pages.ko/common/osmium.md
  pages.ko/common/osv-scanner.md
  pages.ko/common/ouch.md
  pages.ko/common/oxipng.md
Labels: translation

#14643 common/j*: add and update Korean translation
  pages.ko/common/jadx.md
  pages.ko/common/jarsigner.md
  pages.ko/common/java.md
  pages.ko/common/javap.md
  pages.ko/common/jbang.md
  pages.ko/common/jc.md
  pages.ko/common/jcal.md
  pages.ko/common/jdeps.md
  pages.ko/common/jdupes.md
  pages.ko/common/jekyll.md
  pages.ko/common/jello.md
  pages.ko/common/jenv.md
  pages.ko/common/jest.md
  pages.ko/common/jetifier.md
  pages.ko/common/jf.md
  pages.ko/common/jfrog.md
  pages.ko/common/jhat.md
  pages.ko/common/jhipster.md
  pages.ko/common/jhsdb.md
  pages.ko/common/jigsaw.md
  pages.ko/common/jmap.md
  pages.ko/common/jmeter.md
  pages.ko/common/jmtpfs.md
  pages.ko/common/jobs.md
  pages.ko/common/joe.md
  pages.ko/common/john.md
  pages.ko/common/join.md
  pages.ko/common/josm.md
  pages.ko/common/jp2a.md
  pages.ko/common/jpegoptim.md
  pages.ko/common/jpegtopnm.md
  pages.ko/common/jps.md
  pages.ko/common/jq.md
  pages.ko/common/jrnl.md
  pages.ko/common/json5.md
  pages.ko/common/jstack.md
  pages.ko/common/jtbl.md
  pages.ko/common/julia.md
  pages.ko/common/jupyter.md
  pages.ko/common/jupytext.md
  pages.ko/common/just.1.md
  pages.ko/common/just.md
  pages.ko/common/jwt.md
Labels: translation

#14613 windows/g*: add Korean translation
  pages.ko/windows/gal.md
  pages.ko/windows/gcrane-completion.md
  pages.ko/windows/gl.md
  pages.ko/windows/gpupdate.md
Labels: translation

#14640 id*: add Korean translation
  pages.ko/common/id.md
  pages.ko/common/id3tag.md
  pages.ko/common/idea.md
  pages.ko/common/identify.md
  pages.ko/common/idevice_id.md
  pages.ko/common/idevicebackup.md
  pages.ko/common/idevicebackup2.md
  pages.ko/common/idevicecrashreport.md
  pages.ko/common/idevicedate.md
  pages.ko/common/idevicediagnostics.md
  pages.ko/common/ideviceimagemounter.md
  pages.ko/common/ideviceinfo.md
  pages.ko/common/idevicename.md
  pages.ko/common/idevicepair.md
  pages.ko/common/idevicescreenshot.md
  pages.ko/common/idevicesetlocation.md
  pages.ko/common/idevicesyslog.md
Labels: translation

#14659 MAINTAINERS: add @CodePsy-2001 as collaborator
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: community

#14656 2to3: update outdated links
  pages.bn/common/2to3.md
  pages.fa/common/2to3.md
  pages.fr/common/2to3.md
  pages.ko/common/2to3.md
  pages.zh/common/2to3.md
Labels: translation

#14652 bdfr, cdecl, cfssl, clamav, cron: add Korean translation
  pages.ko/common/bdfr.md
  pages.ko/common/cdecl.md
  pages.ko/common/cfssl.md
  pages.ko/common/clamav.md
  pages.ko/common/cron.md
Labels: translation

#14660 dvc,dvc-*: add Korean translation
  pages.ko/common/dvc-add.md
  pages.ko/common/dvc-checkout.md
  pages.ko/common/dvc-commit.md
  pages.ko/common/dvc-config.md
  pages.ko/common/dvc-dag.md
  pages.ko/common/dvc-destroy.md
  pages.ko/common/dvc-diff.md
  pages.ko/common/dvc-fetch.md
  pages.ko/common/dvc-freeze.md
  pages.ko/common/dvc-gc.md
  pages.ko/common/dvc-init.md
  pages.ko/common/dvc-unfreeze.md
  pages.ko/common/dvc.md
Labels: translation

#14661 hg,hg-*: add Korean translation
  pages.ko/common/hg-add.md
  pages.ko/common/hg-branch.md
  pages.ko/common/hg-clone.md
  pages.ko/common/hg-commit.md
  pages.ko/common/hg-init.md
  pages.ko/common/hg-log.md
  pages.ko/common/hg-pull.md
  pages.ko/common/hg-push.md
  pages.ko/common/hg-remove.md
  pages.ko/common/hg-root.md
  pages.ko/common/hg-serve.md
  pages.ko/common/hg-status.md
  pages.ko/common/hg-update.md
  pages.ko/common/hg.md
Labels: translation

#14662 hledger,hledger-*: add Korean translation
  pages.ko/common/hledger-accounts.md
  pages.ko/common/hledger-add.md
  pages.ko/common/hledger-aregister.md
  pages.ko/common/hledger-balance.md
  pages.ko/common/hledger-balancesheet.md
  pages.ko/common/hledger-import.md
  pages.ko/common/hledger-incomestatement.md
  pages.ko/common/hledger-print.md
  pages.ko/common/hledger-ui.md
  pages.ko/common/hledger-web.md
  pages.ko/common/hledger.md
Labels: translation

#14667 if*, ignite, ilbmtoppm, im*: add Korean translation
  pages.ko/common/ifconfig.md
  pages.ko/common/ifdata.md
  pages.ko/common/ifne.md
  pages.ko/common/ifs.md
  pages.ko/common/ignite.md
  pages.ko/common/ilbmtoppm.md
  pages.ko/common/imapsync.md
  pages.ko/common/imgcat.md
  pages.ko/common/imgtoppm.md
  pages.ko/common/immich-cli.md
  pages.ko/common/immich-go.md
  pages.ko/common/import.md
Labels: translation

#14620 adb-devices: add Chinese translation
  pages.zh/common/adb-devices.md
Labels: translation

#14675 helix: add example to open multiple files and tutorial
  pages/common/helix.md
Labels: page edit

#14655 pages.*: update outdated links
  pages.fr/linux/iwctl.md
  pages.pl/common/http.md
  pages.zh/linux/cryptsetup.md
Labels: translation

#14651 idnits, iex, if: add Korean translation
  pages.ko/common/idnits.md
  pages.ko/common/iex.md
  pages.ko/common/if.md
Labels: translation

#14669 fatrace: add page
  pages/linux/fatrace.md
Labels: new command

#14691 z: remove unnecessary dot
  pages/common/z.md
Labels: page edit

#14408 bmptopnm: add Portuguese Brazilian translation
  pages.pt_BR/common/bmptopnm.md
Labels: translation, hacktoberfest-accepted

#14694 aws-s3-rm: add example
  pages/common/aws-s3-rm.md
Labels: page edit

#14678 networkQuality: update documentation link
  pages/osx/networkquality.md
Labels: page edit

#14681 linux/b*: add Korean translation
  pages.ko/linux/backlight_control.md
  pages.ko/linux/balooctl.md
  pages.ko/linux/battop.md
  pages.ko/linux/bcachefs-device.md
  pages.ko/linux/bcachefs.md
  pages.ko/linux/bchunk.md
  pages.ko/linux/beep.md
  pages.ko/linux/betterdiscordctl.md
  pages.ko/linux/betterlockscreen.md
  pages.ko/linux/bitwise.md
  pages.ko/linux/blastn.md
  pages.ko/linux/blastp.md
  pages.ko/linux/bleachbit.md
  pages.ko/linux/blight.md
  pages.ko/linux/blkdiscard.md
  pages.ko/linux/blkid.md
  pages.ko/linux/blkpr.md
  pages.ko/linux/blockdev.md
  pages.ko/linux/bluetoothctl.md
  pages.ko/linux/bluetoothd.md
  pages.ko/linux/blurlock.md
  pages.ko/linux/bmon.md
  pages.ko/linux/boltctl.md
  pages.ko/linux/bootctl.md
  pages.ko/linux/bpftool.md
  pages.ko/linux/bpftrace.md
  pages.ko/linux/br.md
  pages.ko/linux/braa.md
  pages.ko/linux/brctl.md
  pages.ko/linux/brightnessctl.md
  pages.ko/linux/broot.md
  pages.ko/linux/bspc.md
  pages.ko/linux/bspwm.md
  pages.ko/linux/btrbk.md
  pages.ko/linux/bully.md
  pages.ko/linux/burpsuite.md
  pages.ko/linux/busctl.md
  pages.ko/linux/bwa.md
  pages.ko/linux/byzanz-record.md
Labels: translation

#14692 infection, influx, info, initdb, inkmake, inkscape: add Korean translation
  pages.ko/common/infection.md
  pages.ko/common/influx.md
  pages.ko/common/info.md
  pages.ko/common/initdb.md
  pages.ko/common/inkmake.md
  pages.ko/common/inkscape.md
Labels: translation

#14685 in2csv, indent: add Korean translation
  pages.ko/common/in2csv.md
  pages.ko/common/indent.md
Labels: translation

#14684 linux/e*: add Korean translation
  pages.ko/linux/e2freefrag.md
  pages.ko/linux/e2fsck.md
  pages.ko/linux/e2image.md
  pages.ko/linux/e2label.md
  pages.ko/linux/e2undo.md
  pages.ko/linux/e4defrag.md
  pages.ko/linux/ebuild.md
  pages.ko/linux/edit.md
  pages.ko/linux/edquota.md
  pages.ko/linux/efibootmgr.md
  pages.ko/linux/ego.md
  pages.ko/linux/einfo.md
  pages.ko/linux/eix.md
  pages.ko/linux/eject.md
  pages.ko/linux/elink.md
  pages.ko/linux/emerge.md
  pages.ko/linux/engrampa.md
  pages.ko/linux/enum4linux.md
  pages.ko/linux/envycontrol.md
  pages.ko/linux/eopkg.md
  pages.ko/linux/equery.md
  pages.ko/linux/esa-snap.md
  pages.ko/linux/esearch.md
  pages.ko/linux/eselect-kernel.md
  pages.ko/linux/eselect-locale.md
  pages.ko/linux/eselect-news.md
  pages.ko/linux/eselect-profile.md
  pages.ko/linux/eselect-repository.md
  pages.ko/linux/eselect.md
  pages.ko/linux/etckeeper.md
  pages.ko/linux/ethtool.md
  pages.ko/linux/eu-readelf.md
  pages.ko/linux/evtest.md
  pages.ko/linux/exec.md
  pages.ko/linux/exif.md
  pages.ko/linux/exiqgrep.md
  pages.ko/linux/expect.md
  pages.ko/linux/export.md
  pages.ko/linux/extrace.md
  pages.ko/linux/extrepo.md
  pages.ko/linux/extundelete.md
  pages.ko/linux/eyed3.md
Labels: translation

#14668 bugreportz: update Chinese translation
  pages.zh/android/bugreportz.md
Labels: translation

#14054 aws-cloudformation: add pt_BR translation
  pages.pt_BR/common/aws-cloudformation.md
Labels: translation, hacktoberfest-accepted

#14731 gzip: fix parameters formatting
  pages/common/gzip.md
Labels: page edit

#14707 linux/j*: add Korean translation
  pages.ko/linux/jhead.md
  pages.ko/linux/jobs.md
  pages.ko/linux/journalctl.md
  pages.ko/linux/jpegtran.md
  pages.ko/linux/just.js.md
Labels: translation

#14708 linux/k*: add Korean translation
  pages.ko/linux/kde-builder.md
  pages.ko/linux/kde-inhibit.md
  pages.ko/linux/kdesrc-build.md
  pages.ko/linux/kdialog.md
  pages.ko/linux/kdocker.md
  pages.ko/linux/kernel-install.md
  pages.ko/linux/kexec.md
  pages.ko/linux/keyctl.md
  pages.ko/linux/kill.md
  pages.ko/linux/killall.md
  pages.ko/linux/kjv.md
  pages.ko/linux/knock.md
  pages.ko/linux/knockd.md
  pages.ko/linux/konsave.md
  pages.ko/linux/konsole.md
  pages.ko/linux/kpackagetool5.md
  pages.ko/linux/kpartx.md
  pages.ko/linux/kreadconfig5.md
  pages.ko/linux/krfb-virtualmonitor.md
  pages.ko/linux/kscreen-console.md
  pages.ko/linux/kscreen-doctor.md
  pages.ko/linux/ksvgtopng5.md
  pages.ko/linux/kwrite.md
  pages.ko/linux/kwriteconfig5.md
Labels: translation

#14711 linux/o*: add Korean translation
  pages.ko/linux/obabel.md
  pages.ko/linux/objcopy.md
  pages.ko/linux/oomctl.md
  pages.ko/linux/openfortivpn.md
  pages.ko/linux/openrc.md
  pages.ko/linux/openvpn3.md
  pages.ko/linux/opera-stable.md
  pages.ko/linux/opkg.md
  pages.ko/linux/optimus-manager.md
  pages.ko/linux/ostree.md
Labels: translation

#14710 linux/n*: add Korean translation
  pages.ko/linux/nala.md
  pages.ko/linux/namcap.md
  pages.ko/linux/named.md
  pages.ko/linux/namei.md
  pages.ko/linux/nautilus.md
  pages.ko/linux/navi.md
  pages.ko/linux/ncat.md
  pages.ko/linux/ndctl.md
  pages.ko/linux/needrestart.md
  pages.ko/linux/nemo.md
  pages.ko/linux/nethogs.md
  pages.ko/linux/netselect-apt.md
  pages.ko/linux/netselect.md
  pages.ko/linux/networkctl.md
  pages.ko/linux/newgrp.md
  pages.ko/linux/nft.md
  pages.ko/linux/nitch.md
  pages.ko/linux/nitrogen.md
  pages.ko/linux/nixos-container.md
  pages.ko/linux/nixos-option.md
  pages.ko/linux/nixos-rebuild.md
  pages.ko/linux/nl.md
  pages.ko/linux/nm-online.md
  pages.ko/linux/nmcli-agent.md
  pages.ko/linux/nmcli-connection.md
  pages.ko/linux/nmcli-device.md
  pages.ko/linux/nmcli-general.md
  pages.ko/linux/nmcli-monitor.md
  pages.ko/linux/nmcli-networking.md
  pages.ko/linux/nmcli-radio.md
  pages.ko/linux/nmcli.md
  pages.ko/linux/nmon.md
  pages.ko/linux/nmtui-connect.md
  pages.ko/linux/nmtui-edit.md
  pages.ko/linux/nmtui-hostname.md
  pages.ko/linux/nmtui.md
  pages.ko/linux/nologin.md
  pages.ko/linux/nordvpn.md
  pages.ko/linux/notify-send.md
  pages.ko/linux/nova.md
  pages.ko/linux/nsenter.md
  pages.ko/linux/nsnake.md
  pages.ko/linux/nsxiv.md
  pages.ko/linux/ntfsfix.md
  pages.ko/linux/ntpd.md
  pages.ko/linux/ntpdate.md
  pages.ko/linux/ntpq.md
  pages.ko/linux/numactl.md
  pages.ko/linux/numlockx.md
Labels: translation

#14703 linux/f*: add Korean translation
  pages.ko/linux/f5fpc.md
  pages.ko/linux/factorio.md
  pages.ko/linux/fail2ban-client.md
  pages.ko/linux/faillock.md
  pages.ko/linux/fakeroot.md
  pages.ko/linux/faketime.md
  pages.ko/linux/fallocate.md
  pages.ko/linux/farge.md
  pages.ko/linux/fatlabel.md
  pages.ko/linux/fatrace.md
  pages.ko/linux/fcrackzip.md
  pages.ko/linux/fdisk.md
  pages.ko/linux/feedreader.md
  pages.ko/linux/file-rename.md
  pages.ko/linux/filefrag.md
  pages.ko/linux/finch.md
  pages.ko/linux/findfs.md
  pages.ko/linux/findmnt.md
  pages.ko/linux/firejail.md
  pages.ko/linux/firewall-cmd.md
  pages.ko/linux/fixfiles.md
  pages.ko/linux/flameshot.md
  pages.ko/linux/flash.md
  pages.ko/linux/flashrom.md
  pages.ko/linux/fluidsynth.md
  pages.ko/linux/fold.md
  pages.ko/linux/foreman.md
  pages.ko/linux/fprintd-delete.md
  pages.ko/linux/fprintd-enroll.md
  pages.ko/linux/fprintd-list.md
  pages.ko/linux/fprintd-verify.md
  pages.ko/linux/fprintd.md
  pages.ko/linux/fpsync.md
  pages.ko/linux/free.md
  pages.ko/linux/fsck.md
  pages.ko/linux/fscrypt.md
  pages.ko/linux/fstrim.md
  pages.ko/linux/fuser.md
  pages.ko/linux/fwupdmgr.md
Labels: translation

#14705 linux/h*: add Korean translation
  pages.ko/linux/halt.md
  pages.ko/linux/handlr.md
  pages.ko/linux/hardinfo.md
  pages.ko/linux/hcitool.md
  pages.ko/linux/hdparm.md
  pages.ko/linux/head.md
  pages.ko/linux/hlint.md
  pages.ko/linux/homectl.md
  pages.ko/linux/homeshick.md
  pages.ko/linux/hostnamectl.md
  pages.ko/linux/htpdate.md
  pages.ko/linux/http-prompt.md
  pages.ko/linux/http_load.md
  pages.ko/linux/hwclock.md
  pages.ko/linux/hwinfo.md
  pages.ko/linux/hyprctl.md
  pages.ko/linux/hyprpm.md
Labels: translation

#14706 ifstat: fix typo, linux/i*: add Korean translation
  pages.ko/linux/i3-scrot.md
  pages.ko/linux/i3.md
  pages.ko/linux/i3exit.md
  pages.ko/linux/i3lock.md
  pages.ko/linux/i3status.md
  pages.ko/linux/i7z.md
  pages.ko/linux/ico.md
  pages.ko/linux/id3v2.md
  pages.ko/linux/ifdown.md
  pages.ko/linux/ifmetric.md
  pages.ko/linux/ifstat.md
  pages.ko/linux/iftop.md
  pages.ko/linux/ifup.md
  pages.ko/linux/ikaros.md
  pages.ko/linux/img2txt.md
  pages.ko/linux/img2webp.md
  pages.ko/linux/imgp.md
  pages.ko/linux/init.md
  pages.ko/linux/inotifywait.md
  pages.ko/linux/insmod.md
  pages.ko/linux/instaloader.md
  pages.ko/linux/inxi.md
  pages.ko/linux/ionice.md
  pages.ko/linux/iostat.md
  pages.ko/linux/ip-address.md
  pages.ko/linux/ip-link.md
  pages.ko/linux/ip-neighbour.md
  pages.ko/linux/ip-route-get.md
  pages.ko/linux/ip-route-show.md
  pages.ko/linux/ip-route.md
  pages.ko/linux/ip-rule.md
  pages.ko/linux/ip.md
  pages.ko/linux/ip6tables-restore.md
  pages.ko/linux/ip6tables-save.md
  pages.ko/linux/ip6tables.md
  pages.ko/linux/ipcalc.md
  pages.ko/linux/ipcmk.md
  pages.ko/linux/ipcrm.md
  pages.ko/linux/ipcs.md
  pages.ko/linux/ipset.md
  pages.ko/linux/iptables-restore.md
  pages.ko/linux/iptables-save.md
  pages.ko/linux/iptables.md
  pages.ko/linux/isoinfo.md
  pages.ko/linux/isosize.md
  pages.ko/linux/iw-dev.md
  pages.ko/linux/iw.md
  pages.ko/linux/iwconfig.md
  pages.ko/linux/iwctl.md
  pages.ko/linux/iwlist.md
  pages/linux/ifstat.md
Labels: page edit, translation

#14709 linux/man: update Korean translation, linux/m*: add Korean translation
  pages.ko/linux/mac2unix.md
  pages.ko/linux/macchanger.md
  pages.ko/linux/machinectl.md
  pages.ko/linux/maim.md
  pages.ko/linux/makepkg.md
  pages.ko/linux/man.md
  pages.ko/linux/mandb.md
  pages.ko/linux/manpath.md
  pages.ko/linux/mashtree.md
  pages.ko/linux/matchpathcon.md
  pages.ko/linux/mate-about.md
  pages.ko/linux/mate-calc-cmd.md
  pages.ko/linux/mate-calc.md
  pages.ko/linux/mate-screenshot.md
  pages.ko/linux/mate-search-tool.md
  pages.ko/linux/mcookie.md
  pages.ko/linux/mdadm.md
  pages.ko/linux/mdbook.md
  pages.ko/linux/mediamtx.md
  pages.ko/linux/megatools-dl.md
  pages.ko/linux/mesg.md
  pages.ko/linux/microcom.md
  pages.ko/linux/mimetype.md
  pages.ko/linux/minicom.md
  pages.ko/linux/mke2fs.md
  pages.ko/linux/mkhomedir_helper.md
  pages.ko/linux/mkinitcpio.md
  pages.ko/linux/mkisofs.md
  pages.ko/linux/mklost+found.md
  pages.ko/linux/mknod.md
  pages.ko/linux/mkosi.md
  pages.ko/linux/mksquashfs.md
  pages.ko/linux/mkswap.md
  pages.ko/linux/mktemp.md
  pages.ko/linux/mlabel.md
  pages.ko/linux/mmcli.md
  pages.ko/linux/mmdebstrap.md
  pages.ko/linux/mocp.md
  pages.ko/linux/modinfo.md
  pages.ko/linux/modprobe.md
  pages.ko/linux/module.md
  pages.ko/linux/mokutil.md
  pages.ko/linux/mono.md
  pages.ko/linux/mons.md
  pages.ko/linux/mopac.md
  pages.ko/linux/more.md
  pages.ko/linux/mount.cifs.md
  pages.ko/linux/mount.ddi.md
  pages.ko/linux/mount.smb3.md
  pages.ko/linux/mountpoint.md
  pages.ko/linux/mpg123.md
  pages.ko/linux/mpicc.md
  pages.ko/linux/mpstat.md
  pages.ko/linux/mssh.md
  pages.ko/linux/mt.md
  pages.ko/linux/mycli.md
Labels: translation

#14713 qrcp: fix typo, linux/q*: add Korean translation
  pages.ko/linux/qjoypad.md
  pages.ko/linux/qrcp.md
  pages.ko/linux/qsub.md
  pages.ko/linux/qtchooser.md
  pages.ko/linux/qtile.md
  pages.ko/linux/quickemu.md
  pages.ko/linux/quickget.md
  pages.ko/linux/quotacheck.md
  pages/linux/qrcp.md
Labels: page edit, translation

#14676 cradle: add Farsi translation
  pages.fa/common/cradle.md
Labels: translation, review needed

#14733 mc: add Spanish translation
  pages.es/common/mc.md
Labels: translation

#14732 crontab: add Spanish translation
  pages.es/common/crontab.md
Labels: translation

#14673 gcc: add Spanish translation
  pages.es/common/gcc.md
Labels: translation

#14674 ar: add Spanish translation
  pages.es/common/ar.md
Labels: translation

#14672 dnf-config-manager: add Spanish translation
  pages.es/linux/dnf-config-manager.md
Labels: translation

#14671 apport-bug: add Spanish translation
  pages.es/linux/apport-bug.md
Labels: translation

#14649 qm-disk-resize: add Spanish translation
  pages.es/linux/qm-disk-resize.md
Labels: translation

#14556 common/*: update Indonesian translations, git-credential-store: standardize other translations
  pages.id/common/act.md
  pages.id/common/ansible-galaxy.md
  pages.id/common/aria2c.md
  pages.id/common/asdf.md
  pages.id/common/aspell.md
  pages.id/common/assimp.md
  pages.id/common/astronomer.md
  pages.id/common/at.md
  pages.id/common/aws-acm.md
  pages.id/common/bq.md
  pages.id/common/brew-search.md
  pages.id/common/brew-uninstall.md
  pages.id/common/git-credential-cache.md
  pages.id/common/git-credential-store.md
  pages.id/common/git-credential.md
  pages.id/common/history.md
  pages.id/common/hsw-cli.md
  pages.id/common/html5validator.md
  pages.id/common/htop.md
  pages.id/common/htpasswd.md
  pages.ko/common/git-credential-store.md
  pages/common/git-credential-store.md
Labels: page edit, translation

#14647 qm-disk-move: add Spanish translation
  pages.es/linux/qm-disk-move.md
Labels: translation

#14646 qm-disk-import: add Spanish translation
  pages.es/linux/qm-disk-import.md
Labels: translation

#14637 hashcat: add Chinese translation
  pages.zh/common/hashcat.md
Labels: translation

#14627 nmtui: add Spanish translation
  pages.es/linux/nmtui.md
Labels: translation

#14626 systemd-mount: add Spanish translation
  pages.es/linux/systemd-mount.md
Labels: translation

#14624 megatools-dl: add Spanish translation
  pages.es/linux/megatools-dl.md
Labels: translation

#14623 ip-route-show: add Spanish translation
  pages.es/linux/ip-route-show.md
Labels: translation

#14753 termusic: fix typo, linux/t*: add Korean translation
  pages.ko/linux/tac.md
  pages.ko/linux/tailf.md
  pages.ko/linux/talk.md
  pages.ko/linux/taskset.md
  pages.ko/linux/tc.md
  pages.ko/linux/tcpflow.md
  pages.ko/linux/tcpick.md
  pages.ko/linux/tcpkill.md
  pages.ko/linux/tcptraceroute.md
  pages.ko/linux/telinit.md
  pages.ko/linux/terminator.md
  pages.ko/linux/termusic.md
  pages.ko/linux/terraria.md
  pages.ko/linux/tftp.md
  pages.ko/linux/thunar.md
  pages.ko/linux/tic.md
  pages.ko/linux/timedatectl.md
  pages.ko/linux/timeshift.md
  pages.ko/linux/tlp-stat.md
  pages.ko/linux/tlp.md
  pages.ko/linux/tod.md
  pages.ko/linux/togglesebool.md
  pages.ko/linux/toilet.md
  pages.ko/linux/tomb.md
  pages.ko/linux/toolbox-create.md
  pages.ko/linux/toolbox-enter.md
  pages.ko/linux/toolbox-help.md
  pages.ko/linux/toolbox-init-container.md
  pages.ko/linux/toolbox-list.md
  pages.ko/linux/toolbox-rm.md
  pages.ko/linux/toolbox-rmi.md
  pages.ko/linux/toolbox-run.md
  pages.ko/linux/toolbox.md
  pages.ko/linux/top.md
  pages.ko/linux/tor.md
  pages.ko/linux/torify.md
  pages.ko/linux/torsocks.md
  pages.ko/linux/trace-cmd.md
  pages.ko/linux/tracepath.md
  pages.ko/linux/trap.md
  pages.ko/linux/trash.md
  pages.ko/linux/trashy.md
  pages.ko/linux/trayer.md
  pages.ko/linux/treetime.md
  pages.ko/linux/trizen.md
  pages.ko/linux/trust.md
  pages.ko/linux/tshark.md
  pages.ko/linux/ttyplot.md
  pages.ko/linux/tune2fs.md
  pages.ko/linux/tuned-adm.md
  pages.ko/linux/tunelp.md
  pages.ko/linux/turbostat.md
  pages.ko/linux/tuxi.md
  pages.ko/linux/tzselect.md
  pages/linux/termusic.md
Labels: page edit, translation

#14759 freebsd/base64: add Korean translation
  pages.ko/freebsd/base64.md
Labels: translation

#14760 ~: add Korean translation
  pages.ko/common/~.md
Labels: translation

#14756 linux/w*: add Korean translation
  pages.ko/linux/w.md
  pages.ko/linux/waitpid.md
  pages.ko/linux/wajig.md
  pages.ko/linux/wal-telegram.md
  pages.ko/linux/wall.md
  pages.ko/linux/wami.md
  pages.ko/linux/warpd.md
  pages.ko/linux/watch.md
  pages.ko/linux/waydroid.md
  pages.ko/linux/waypipe.md
  pages.ko/linux/wdctl.md
  pages.ko/linux/wg-quick.md
  pages.ko/linux/wg.md
  pages.ko/linux/whatis.md
  pages.ko/linux/whiptail.md
  pages.ko/linux/wifi-menu.md
  pages.ko/linux/wine.md
  pages.ko/linux/winetricks.md
  pages.ko/linux/wipefs.md
  pages.ko/linux/wl-copy.md
  pages.ko/linux/wl-paste.md
  pages.ko/linux/wmctrl.md
  pages.ko/linux/wodim.md
  pages.ko/linux/woeusb.md
  pages.ko/linux/wofi.md
  pages.ko/linux/wol.md
  pages.ko/linux/wpa_cli.md
  pages.ko/linux/wpa_passphrase.md
  pages.ko/linux/wpctl.md
  pages.ko/linux/wtf.md
  pages.ko/linux/wtype.md
Labels: translation
