Repository tldr-pages/tldr, pull requests merged in 2024-03, with the labels that each got.

#12380 kate: add pt_BR translation
  pages.pt_BR/common/kate.md
Labels: translation

#12385 xrandr: add pt_BR translation
  pages.pt_BR/linux/xrandr.md
Labels: translation

#12416 opkg: remove upgrade command
  pages/linux/opkg.md
Labels: page edit

#12376 check-dfsg-status: add page
  pages/linux/check-dfsg-status.md
Labels: new command

#12375 eza: add pt_BR translation
  pages.pt_BR/common/eza.md
Labels: translation

#12352 pwn: add page
  pages/linux/pwn.md
Labels: new command

#12429 colorls: add French translation
  pages.fr/common/colorls.md
Labels: translation

#12430 entr: edit page
  pages/common/entr.md
Labels: page edit

#12427 deno: add French translation
  pages.fr/common/deno.md
Labels: translation

#12382 find: add pt_BR translation
  pages.pt_BR/common/find.md
Labels: translation

#12405 trivy: edit page
  pages/common/trivy.md
Labels: page edit

#12428 exa: add French translation
  pages.fr/common/exa.md
Labels: translation

#12384 grubby: add Spanish translation
  pages.es/linux/grubby.md
Labels: translation

#12426 ppmtoterm, ppmtoascii, pbmto4425: add pages; pbmtoascii: edit page
  pages/common/pbmto4425.md
  pages/common/pbmtoascii.md
  pages/common/ppmtoascii.md
  pages/common/ppmtoterm.md
Labels: page edit, new command

#12386 trufflehog: add Spanish translation
  pages.es/common/trufflehog.md
Labels: translation

#12441 duf: edit page
  pages/common/duf.md
Labels: page edit

#12422 pnmarith, pamarith: add pages
  pages/common/pamarith.md
  pages/common/pnmarith.md
Labels: new command

#12407 pnmquantall, ppmquantall: add pages; pnmquant: edit page
  pages/common/pnmquant.md
  pages/common/pnmquantall.md
  pages/common/ppmquantall.md
Labels: page edit, new command

#12408 icontopbm, pbmtoicon, pbmtosunicon, sunicontopbm: add pages
  pages/common/icontopbm.md
  pages/common/pbmtoicon.md
  pages/common/pbmtosunicon.md
  pages/common/sunicontopbm.md
Labels: new command

#12402 checkov: add page
  pages/common/checkov.md
Labels: new command

#12393 mise: add page
  pages/common/mise.md
Labels: new command

#12446 select: move to common, fix placeholders
  pages/common/select.md
Labels: page edit

#12449 printf: edit page
  pages/common/printf.md
Labels: page edit

#12440 btop: edit page
  pages/common/btop.md
Labels: page edit

#12444 nmap: edit page
  pages/common/nmap.md
Labels: page edit

#12450 nmap: edit page
  pages/common/nmap.md
Labels: page edit, minor change

#12435 pwn: add Spanish translation
  pages.es/linux/pwn.md
Labels: translation

#12351 vcpkg: add Spanish translation
  pages.es/common/vcpkg.md
Labels: translation

#12442 dd: update page
  pages/common/dd.md
  pages/linux/dd.md
Labels: page edit

#12399 pamrgbatopng, pamtopng, pngtopam: add pages
  pages/common/pamrgbatopng.md
  pages/common/pamtopng.md
  pages/common/pngtopam.md
Labels: new command

#12401 pgmcrater, pamcrater, pamshadedrelief: add pages
  pages/common/pamcrater.md
  pages/common/pamshadedrelief.md
  pages/common/pgmcrater.md
Labels: new command

#12412 pnmsplit, pamsplit, pamexec, pampick: add pages
  pages/common/pamexec.md
  pages/common/pampick.md
  pages/common/pamsplit.md
  pages/common/pnmsplit.md
Labels: new command

#12410 pgmtopbm: add page
  pages/common/pgmtopbm.md
Labels: new command

#12409 ppmtogif, pamtogif: add pages
  pages/common/pamtogif.md
  pages/common/ppmtogif.md
Labels: new command

#12392 pgmslice: add page
  pages/common/pgmslice.md
Labels: new command

#12391 pnmenlarge: add page
  pages/common/pnmenlarge.md
Labels: new command

#12390 ppmtomap: add page
  pages/common/ppmtomap.md
Labels: new command

#12389 pcdindex, pcdovtoppm: add pages
  pages/common/pcdindex.md
  pages/common/pcdovtoppm.md
Labels: new command

#12363 pambrighten, ppmbrighten: add pages
  pages/common/pambrighten.md
  pages/common/ppmbrighten.md
Labels: new command

#12413 pnmflip: add page
  pages/common/pnmflip.md
Labels: new command

#12414 ppmtouil, pamtouil: add pages
  pages/common/pamtouil.md
  pages/common/ppmtouil.md
Labels: new command

#12415 pgmedge, pamedge: add pages
  pages/common/pamedge.md
  pages/common/pgmedge.md
Labels: new command

#12417 pnmfile: add page
  pages/common/pnmfile.md
Labels: new command

#12418 ppmnorm, pgmnorm: add pages
  pages/common/pgmnorm.md
  pages/common/ppmnorm.md
Labels: new command

#12419 bmptoppm: add page
  pages/common/bmptoppm.md
Labels: new command

#12420 ppmtojpeg: add page
  pages/common/ppmtojpeg.md
Labels: new command

#12421 pnminterp: add page
  pages/common/pnminterp.md
Labels: new command

#12411 pnmcut: add page
  pages/common/pnmcut.md
Labels: new command

#12424 bootctl: add Chinese translation
  pages.zh/linux/bootctl.md
Labels: translation

#12328 aws-*: rephrase page descriptions to avoid CLI when unnedeed
  pages/common/aws-cognito-idp.md
  pages/common/aws-dynamodb.md
  pages/common/aws-ec2.md
  pages/common/aws-eks.md
  pages/common/aws-iam.md
  pages/common/aws-kinesis.md
  pages/common/aws-lambda.md
  pages/common/aws-rds.md
Labels: page edit

#12436 check-dfsg-status: add Spanish translation
  pages.es/linux/check-dfsg-status.md
Labels: translation

#12343 usql: add Spanish translation
  pages.es/common/usql.md
Labels: translation

#12461 iwconfig: fix example parameter
  pages/linux/iwconfig.md
Labels: page edit, minor change

#12464 pnmtojpeg: add Spanish translation
  pages.es/common/pnmtojpeg.md
Labels: translation

#12451 bat: edit page
  pages/common/bat.md
Labels: page edit

#12459 macchanger: edit page
  pages/linux/macchanger.md
Labels: page edit

#12439 pipes.sh: add page
  pages/common/pipes.sh.md
Labels: new command

#12400 pngtopnm: add page
  pages/common/pngtopnm.md
Labels: new command

#12462 dolt-gc: add page
  pages/common/dolt-gc.md
Labels: new command

#12460 iwlist: add page
  pages/linux/iwlist.md
Labels: new command

#12320 b3sum: add French translation
  pages.fr/common/b3sum.md
Labels: translation

#12458 golangci-lint: add Spanish translation
  pages.es/common/golangci-lint.md
Labels: translation

#12447 checkov: add Spanish translation
  pages.es/common/checkov.md
Labels: translation

#12453 mise: add Spanish translation
  pages.es/common/mise.md
Labels: translation

#12456 pnminterp: add Spanish translation
  pages.es/common/pnminterp.md
Labels: translation

#12457 repo-remove: add Spanish translation
  pages.es/linux/repo-remove.md
Labels: translation

#12465 airodump-ng: edit page
  pages/common/airodump-ng.md
Labels: page edit

#12263 audacious: improve examples and page description and add example
  pages/common/audacious.md
Labels: page edit

#12301 reg*: improve pages
  pages/windows/reg-add.md
  pages/windows/reg-compare.md
  pages/windows/reg-copy.md
  pages/windows/reg-delete.md
  pages/windows/reg-export.md
  pages/windows/reg-flags.md
  pages/windows/reg-import.md
  pages/windows/reg-load.md
  pages/windows/reg-query.md
  pages/windows/reg-restore.md
  pages/windows/reg-save.md
  pages/windows/reg.md
Labels: page edit

#12474 ncmpcpp, youtube-viewer, aplay: remove "command-line" from description
  pages/common/ncmpcpp.md
  pages/common/youtube-viewer.md
  pages/linux/aplay.md
Labels: page edit

#12470 pnmcut: add Spanish translation
  pages.es/common/pnmcut.md
Labels: translation

#12471 go-tool: edit page
  pages/common/go-tool.md
Labels: page edit

#12469 pngtopnm: add Spanish translation
  pages.es/common/pngtopnm.md
Labels: translation

#12472 virt-manager: edit page
  pages/linux/virt-manager.md
Labels: page edit

#12467 diskutil-partitiondisk: add page
  pages/osx/diskutil-partitiondisk.md
  pages/osx/diskutil.md
Labels: page edit, new command

#12359 apt-get: add Indonesian translation
  pages.id/linux/apt-get.md
Labels: translation

#12357 add-apt-repository, apt-cache: add Indonesian translation
  pages.id/linux/add-apt-repository.md
  pages.id/linux/apt-cache.md
Labels: translation

#12473 kdeconnect-cli: expand description
  pages/common/kdeconnect-cli.md
Labels: page edit

#12360 apt-file: add Indonesian translation
  pages.id/linux/apt-file.md
Labels: translation

#12479 cat: fix more information link
  pages.nl/common/cat.md
Labels: translation

#12476 waypipe: add page
  pages/linux/waypipe.md
Labels: new command

#12475 bpkg: add page
  pages/common/bpkg.md
Labels: new command

#12455 ppmtojpeg: add Spanish translation
  pages.es/common/ppmtojpeg.md
Labels: translation

#12477 traefik: add German translation; update page
  pages.de/common/traefik.md
  pages/common/traefik.md
Labels: page edit, translation

#12481 pages*: fix Bash, Zsh and fish names
  pages.de/common/bash.md
  pages.de/common/fish.md
  pages.de/common/omz.md
  pages.de/common/zsh.md
  pages.de/linux/arch-chroot.md
  pages.es/common/histexpand.md
  pages.fr/common/clear.md
  pages.fr/common/sudo.md
  pages.fr/common/zsh.md
  pages.fr/linux/abbr.md
  pages.id/common/history.md
  pages.id/common/open.fish.md
  pages.id/common/open.md
  pages.it/common/bash.md
  pages.it/common/clear.md
  pages.it/common/docker-exec.md
  pages.it/common/sudo.md
  pages.ja/common/history.md
  pages.ko/common/bash.md
  pages.ko/common/clear.md
  pages.nl/common/open.fish.md
  pages.nl/common/open.md
  pages.nl/common/pio-system.md
  pages.pl/common/open.md
  pages.pl/common/sudo.md
  pages.pt_BR/common/history.md
  pages.pt_BR/common/sudo.md
  pages.pt_BR/common/zsh.md
  pages.ru/common/histexpand.md
  pages.ru/common/history.md
  pages.ru/common/zsh.md
  pages.tr/common/docker-exec.md
  pages.zh/linux/arch-chroot.md
  pages/common/histexpand.md
  pages/common/history.md
  pages/common/msfvenom.md
  pages/common/nvm.fish.md
  pages/common/open.fish.md
  pages/common/open.md
  pages/common/pio-system.md
  pages/common/printf.md
  pages/common/procs.md
  pages/common/pueue-completions.md
  pages/common/sudo.md
  pages/linux/arch-chroot.md
  pages/linux/faketime.md
  pages/osx/whence.md
Labels: page edit, mass changes, translation

#12483 bpkg: add Spanish translation
  pages.es/common/bpkg.md
Labels: translation

#12484 bmptoppm: add Spanish translation
  pages.es/common/bmptoppm.md
Labels: translation

#12487 waymore: add page
  pages/common/waymore.md
Labels: new command

#12493 expand: fix short option `-t` argument separator
  pages.it/common/expand.md
  pages/common/expand.md
Labels: page edit, translation

#12488 dd: add Farsi translation
  pages.fa/linux/dd.md
Labels: translation

#12489 gau: add page
  pages/common/gau.md
Labels: new command

#12491 shellcheck: edit page
  pages/common/shellcheck.md
Labels: page edit

#12503 a2ensite: add Indonesian translation
  pages.id/linux/a2ensite.md
Labels: translation

#12502 acpi: add Indonesian translation
  pages.id/linux/acpi.md
Labels: translation

#12501 adduser: add Indonesian translation
  pages.id/linux/adduser.md
Labels: translation

#12496 tlp-stat: edit page
  pages/linux/tlp-stat.md
Labels: page edit

#12312 cargo*: add Chinese translation
  pages.zh/common/cargo-add.md
  pages.zh/common/cargo-bench.md
  pages.zh/common/cargo-build.md
  pages.zh/common/cargo-check.md
  pages.zh/common/cargo-clean.md
  pages.zh/common/cargo-clippy.md
  pages.zh/common/cargo-doc.md
  pages.zh/common/cargo-fetch.md
  pages.zh/common/cargo-fix.md
  pages.zh/common/cargo-fmt.md
  pages.zh/common/cargo-generate-lockfile.md
  pages.zh/common/cargo-help.md
  pages.zh/common/cargo-init.md
  pages.zh/common/cargo-install.md
  pages.zh/common/cargo-locate-project.md
  pages.zh/common/cargo-login.md
  pages.zh/common/cargo-logout.md
  pages.zh/common/cargo-metadata.md
  pages.zh/common/cargo-new.md
  pages.zh/common/cargo-owner.md
  pages.zh/common/cargo-package.md
  pages.zh/common/cargo-pkgid.md
  pages.zh/common/cargo-publish.md
  pages.zh/common/cargo-remove.md
  pages.zh/common/cargo-report.md
  pages.zh/common/cargo-run.md
  pages.zh/common/cargo-rustc.md
  pages.zh/common/cargo-rustdoc.md
  pages.zh/common/cargo-search.md
  pages.zh/common/cargo-test.md
  pages.zh/common/cargo-tree.md
  pages.zh/common/cargo-uninstall.md
  pages.zh/common/cargo-update.md
  pages.zh/common/cargo-vendor.md
  pages.zh/common/cargo-verify-project.md
  pages.zh/common/cargo-version.md
  pages.zh/common/cargo-yank.md
  pages.zh/common/cargo.md
Labels: mass changes, translation

#12162 colima: add page
  pages/common/colima.md
Labels: new command

#12466 dolt-gc: add Spanish translation
  pages.es/common/dolt-gc.md
Labels: translation

#12313 cleanup/style guide: update descriptions section
  contributing-guides/style-guide.md
Labels: documentation

#12507 wdiff: add page
  pages/common/wdiff.md
Labels: new command

#12499 choom: add page
  pages/linux/choom.md
Labels: new command

#12498 ln: add Farsi translation
  pages.fa/common/ln.md
Labels: translation

#12505 figlet: 2 more commands and Spanish translation
  pages.es/common/figlet.md
  pages/common/figlet.md
Labels: page edit, translation

#12513 reg-query: add missing placeholder; iptables-save: fix typo
  pages/linux/iptables-save.md
  pages/windows/reg-query.md
Labels: page edit

#12281 simplehttpserver: add Spanish translation
  pages.es/common/simplehttpserver.md
Labels: translation

#12514 base*: edit pages
  pages/common/base32.md
  pages/common/base64.md
Labels: page edit

#12509 diff: edit page
  pages/common/diff.md
Labels: page edit

#12504 amass*: edit pages
  pages/common/amass-db.md
  pages/common/amass-enum.md
  pages/common/amass-intel.md
  pages/common/amass.md
Labels: page edit

#12516 dig: edit page
  pages/common/dig.md
Labels: page edit

#12522 hashcat: add example
  pages/common/hashcat.md
Labels: page edit

#11725 git-mktree: add page
  pages/common/git-mktree.md
Labels: new command, review needed

#12255 pcapfix: add German translation
  pages.de/common/pcapfix.md
  pages/common/pcapfix.md
Labels: page edit, translation

#12308 sc_*, scamper: add German translation
  pages.de/common/sc_analysis_dump.md
  pages.de/common/sc_tracediff.md
  pages.de/common/sc_ttlexp.md
  pages.de/common/sc_warts2csv.md
  pages.de/common/sc_warts2json.md
  pages.de/common/sc_warts2pcap.md
  pages.de/common/sc_warts2text.md
  pages.de/common/sc_wartscat.md
  pages.de/common/sc_wartsdump.md
  pages.de/common/sc_wartsfilter.md
  pages.de/common/sc_wartsfix.md
  pages.de/common/scamper.md
Labels: translation

#12527 pi3topbm, pbmtopi3: add pages
  pages/common/pbmtopi3.md
  pages/common/pi3topbm.md
Labels: new command

#12525 curl: add Farsi translation
  pages.fa/common/curl.md
Labels: translation

#12519 wfuzz: edit page
  pages/common/wfuzz.md
Labels: page edit

#12510 colima: add Spanish translation
  pages.es/common/colima.md
Labels: translation

#12511 choom: add Spanish translation
  pages.es/linux/choom.md
Labels: translation

#12521 dhcpcd: add Spanish translation
  pages.es/linux/dhcpcd.md
Labels: translation

#12523 pnmfile: add Spanish translation
  pages.es/common/pnmfile.md
Labels: translation

#12443 ffmpeg: update page
  pages/common/ffmpeg.md
Labels: page edit

#12452 CLIENT-SPECIFICATION: deprecate the old asset URL
  CLIENT-SPECIFICATION.md
Labels: documentation

#12536 chisel: edit page
  pages/common/chisel.md
Labels: page edit

#12526 pi1toppm, ppmtopi1: add pages
  pages/common/pi1toppm.md
  pages/common/ppmtopi1.md
Labels: new command

#12534 pnmenlarge: add Spanish translation
  pages.es/common/pnmenlarge.md
Labels: translation

#12538 ppmtopi1: add Spanish translation
  pages.es/common/ppmtopi1.md
Labels: translation

#12537 pi1toppm: add Spanish translation
  pages.es/common/pi1toppm.md
Labels: translation

#12539 gitk, kitex, rclone, venv: edit pages
  pages/common/gitk.md
  pages/common/kitex.md
  pages/common/rclone.md
  pages/common/venv.md
Labels: page edit, minor change

#12533 ppmtomap: add Spanish translation
  pages.es/common/ppmtomap.md
Labels: translation

#12515 gau: add Spanish translation
  pages.es/common/gau.md
Labels: translation

#12532 git-mktree: add Spanish translation
  pages.es/common/git-mktree.md
Labels: translation

#12544 zipsplit: improve page
  pages/linux/zipsplit.md
Labels: page edit

#12406 pamfixtrunc, pamfix, pamvalidate: add pages
  pages/common/pamfix.md
  pages/common/pamfixtrunc.md
  pages/common/pamvalidate.md
Labels: new command

#12543 zipcloak: move to `common` and replace "zipfile"
  pages/common/zipcloak.md
Labels: page edit

#12500 agetty: add page
  pages/linux/agetty.md
Labels: new command

#12541 fclones: add page
  pages/common/fclones.md
Labels: new command

#12547 torsocks: add page
  pages/linux/torsocks.md
Labels: new command

#12528 waymore: add Spanish translation
  pages.es/common/waymore.md
Labels: translation

#12551 torsocks: add Spanish translation
  pages.es/linux/torsocks.md
Labels: translation

#12492 waypipe: add Spanish translation
  pages.es/linux/waypipe.md
Labels: translation

#12542 tunelp: add page
  pages/linux/tunelp.md
Labels: new command

#12555 firejail: edit page
  pages/linux/firejail.md
Labels: page edit

#12550 showkey: add page
  pages/linux/showkey.md
Labels: new command

#12561 agetty: add missing hyphen in placeholder
  pages/linux/agetty.md
Labels: page edit, minor change

#12557 MAINTAINERS: update file, COMMUNITY-ROLES: add notice for 2FA
  COMMUNITY-ROLES.md
  MAINTAINERS.md
Labels: documentation, community

#12559 gist, vboxmanage-cloud: fix typos
  pages/common/gist.md
  pages/common/vboxmanage-cloud.md
Labels: page edit, minor change

#12564 mkfs.f2fs: add page
  pages/linux/mkfs.f2fs.md
Labels: new command

#12579 pydocstyle: add page
  pages/common/pydocstyle.md
Labels: new command
