Repository tldr-pages/tldr, pull requests merged in 2024-12, with the labels that each got.

#15003 xcowsay: add Spanish translation
  pages.es/linux/xcowsay.md
Labels: translation

#14989 fzf: add Spanish translation
  pages.es/common/fzf.md
Labels: translation

#14983 pulumi-install: add page
  pages/common/pulumi-install.md
Labels: new command

#15010 cdrdao: add page
  pages/linux/cdrdao.md
Labels: new command

#15028 printenv: update documentation link
  pages.ko/common/printenv.md
  pages.nl/common/printenv.md
  pages/common/printenv.md
Labels: page edit, translation

#15026 brew-list: add `--pinned` example
  pages/common/brew-list.md
Labels: page edit

#14773 common/z*: add Chinese translation
  pages.zh/common/zapier-analytics.md
  pages.zh/common/zapier-build.md
  pages.zh/common/zapier-convert.md
  pages.zh/common/zapier-init.md
  pages.zh/common/zapier-push.md
  pages.zh/common/zapier-scaffold.md
  pages.zh/common/zapier.md
  pages.zh/common/zbarimg.md
  pages.zh/common/zcat.md
  pages.zh/common/zcmp.md
  pages.zh/common/zdb.md
  pages.zh/common/zdiff.md
  pages.zh/common/zeek.md
  pages.zh/common/zegrep.md
  pages.zh/common/zeisstopnm.md
  pages.zh/common/zek.md
  pages.zh/common/zellij.md
  pages.zh/common/zfgrep.md
  pages.zh/common/zfs.md
  pages.zh/common/zgrep.md
  pages.zh/common/zig.md
  pages.zh/common/zint.md
  pages.zh/common/zip2john.md
  pages.zh/common/zipalign.md
  pages.zh/common/zipcloak.md
  pages.zh/common/zipgrep.md
  pages.zh/common/zipinfo.md
  pages.zh/common/zipnote.md
  pages.zh/common/zless.md
  pages.zh/common/zlib-flate.md
  pages.zh/common/zm.md
  pages.zh/common/zmore.md
  pages.zh/common/zmv.md
  pages.zh/common/znew.md
  pages.zh/common/zola.md
  pages.zh/common/zopflipng.md
  pages.zh/common/zotero.md
  pages.zh/common/zoxide.md
  pages.zh/common/zpool.md
  pages.zh/common/zrun.md
  pages.zh/common/zstdcat.md
  pages.zh/common/zstdless.md
  pages.zh/common/zstdmt.md
  pages.zh/common/zsteg.md
Labels: mass changes, translation, review needed

#14962 tmt, tmt-run, tmt-try: add Chinese translation
  pages.zh/linux/tmt-run.md
  pages.zh/linux/tmt-try.md
  pages.zh/linux/tmt.md
Labels: translation

#15023 flexget: add page
  pages/common/flexget.md
Labels: new command

#15034 pages.*/*: replace `{{" "}}` with `"{{ }}"`
  pages.bn/common/acme.sh.md
  pages.es/common/acme.sh.md
  pages.es/common/mkfifo.md
  pages.es/common/read.md
  pages.fr/common/acme.sh.md
  pages.id/common/acme.sh.md
  pages.ko/common/acme.sh.md
  pages.ko/common/gh-config.md
  pages.ko/common/licensor.md
  pages.ko/common/mkfifo.md
  pages.ko/common/nuclei.md
  pages.ko/common/openai.md
  pages.ko/common/read.md
  pages.ko/common/rich.md
  pages.ko/common/semver.md
  pages.ko/common/trivy.md
  pages.ko/common/virt-install.md
  pages.ko/common/wfuzz.md
  pages.ko/linux/kwriteconfig5.md
  pages.ko/linux/swaybg.md
  pages.ko/windows/show-markdown.md
  pages.nl/common/acme.sh.md
  pages.nl/common/mkfifo.md
  pages.nl/common/read.md
  pages.pt_BR/common/acme.sh.md
  pages.zh/common/acme.sh.md
  pages/common/acme.sh.md
  pages/common/gh-config.md
  pages/common/licensor.md
  pages/common/mkfifo.md
  pages/common/nuclei.md
  pages/common/openai.md
  pages/common/read.md
  pages/common/rich.md
  pages/common/semver.md
  pages/common/trivy.md
  pages/common/virt-install.md
  pages/common/wfuzz.md
  pages/linux/kwriteconfig5.md
  pages/linux/swaybg.md
  pages/windows/show-markdown.md
Labels: page edit, mass changes, translation

#15038 fd: update page
  pages/common/fd.md
Labels: page edit

#15009 euse: add page
  pages/linux/euse.md
Labels: new command

#15040 tesseract: fix `--psm` parameter name
  pages.ko/common/tesseract.md
  pages/common/tesseract.md
Labels: page edit, translation

#15060 arch: update documentation link
  pages.bn/common/arch.md
  pages.es/common/arch.md
  pages.fr/common/arch.md
  pages.hi/common/arch.md
  pages.id/common/arch.md
  pages.it/common/arch.md
  pages.ja/common/arch.md
  pages.ko/common/arch.md
  pages.nl/common/arch.md
  pages.no/common/arch.md
  pages.pt_BR/common/arch.md
  pages.sv/common/arch.md
  pages.tr/common/arch.md
  pages.zh/common/arch.md
  pages/common/arch.md
Labels: page edit, translation

#15068 apt-moo: add Spanish translation
  pages.es/linux/apt-moo.md
Labels: translation

#15065 adb-devices: add Spanish translation
  pages.es/common/adb-devices.md
Labels: translation

#15066 adb-reboot: add Spanish translation
  pages.es/common/adb-reboot.md
Labels: translation

#15067 apt-clone: add Spanish translation
  pages.es/linux/apt-clone.md
Labels: translation

#15050 podman-image: add Spanish translation
  pages.es/common/podman-image.md
Labels: translation

#15049 podman-compose: add Spanish translation
  pages.es/common/podman-compose.md
Labels: translation

#15051 podman-images: add Spanish translation
  pages.es/common/podman-images.md
Labels: translation

#15048 podman-build: add Spanish translation
  pages.es/common/podman-build.md
Labels: translation

#15052 podman-login: add Spanish translation
  pages.es/common/podman-login.md
Labels: translation

#15053 podman-machine: add Spanish translation
  pages.es/common/podman-machine.md
Labels: translation

#15054 podman-ps: add Spanish translation
  pages.es/common/podman-ps.md
Labels: translation

#15055 podman-rmi: add Spanish translation
  pages.es/common/podman-rmi.md
Labels: translation

#15056 podman-run: add Spanish translation
  pages.es/common/podman-run.md
Labels: translation

#15057 wl-copy: add Spanish translation
  pages.es/linux/wl-copy.md
Labels: translation

#15058 wl-paste: add Spanish translation
  pages.es/linux/wl-paste.md
Labels: translation

#15024 zpaq: add page
  pages/common/zpaq.md
Labels: new command

#15007 eclean: add page
  pages/linux/eclean.md
Labels: new command

#15064 systemd-cryptsetup: add page
  pages/linux/systemd-cryptsetup.md
Labels: new command

#15035 while: add conditional repeat of command example
  pages/common/while.md
Labels: page edit

#15016 protontricks: add launch command
  pages/linux/protontricks.md
Labels: page edit

#15081 nmcli-radio: add Spanish translation
  pages.es/linux/nmcli-radio.md
Labels: translation

#15080 nmcli-networking: add Spanish translation
  pages.es/linux/nmcli-networking.md
Labels: translation

#15079 nmcli-monitor: add Spanish translation
  pages.es/linux/nmcli-monitor.md
Labels: translation

#15078 nmcli-general: add Spanish translation
  pages.es/linux/nmcli-general.md
Labels: translation

#15077 nmcli-device: add Spanish translation
  pages.es/linux/nmcli-device.md
Labels: translation

#15076 nmcli-connection: add Spanish translation
  pages.es/linux/nmcli-connection.md
Labels: translation

#15075 nmcli-agent: add Spanish translation
  pages.es/linux/nmcli-agent.md
Labels: translation

#15074 nmcli: add Spanish translation
  pages.es/linux/nmcli.md
Labels: translation

#15037 fd: add Chinese translation
  pages.zh/common/fd.md
Labels: translation

#15044 trdsql: add Spanish translation
  pages.es/common/trdsql.md
Labels: translation

#15046 zola: add Spanish translation
  pages.es/common/zola.md
Labels: translation

#15069 nm-online: add Spanish translation
  pages.es/linux/nm-online.md
Labels: translation

#15047 podman: add Spanish translation
  pages.es/common/podman.md
Labels: translation

#15032 fabric: add Spanish translation
  pages.es/common/fabric.md
Labels: translation

#15031 incus: add Spanish translation
  pages.es/common/incus.md
Labels: translation

#15030 readcd: add Spanish translation
  pages.es/linux/readcd.md
Labels: translation

#15029 cdrdao: add Spanish translation
  pages.es/linux/cdrdao.md
Labels: translation

#15021 imv: add Spanish translation
  pages.es/linux/imv.md
Labels: translation

#15020 wf-recorder: add Spanish translation
  pages.es/linux/wf-recorder.md
Labels: translation

#15019 darling: add Spanish translation
  pages.es/linux/darling.md
Labels: translation

#15018 hatch: add Spanish translation
  pages.es/common/hatch.md
Labels: translation

#15017 vgremove: add Spanish translation
  pages.es/linux/vgremove.md
Labels: translation

#15012 farge: add Spanish translation
  pages.es/linux/farge.md
Labels: translation

#15011 xsel: add Spanish translation
  pages.es/linux/xsel.md
Labels: translation

#14968 caret: add Spanish translation
  pages.es/common/^.md
Labels: translation

#15070 docker-context: add page
  pages/common/docker-context.md
Labels: new command

#14933 pamflip: add Spanish translation
  pages.es/common/pamflip.md
Labels: translation

#15073 b2sum,md5sum,sha*sum: update Dutch translation
  pages.nl/common/b2sum.md
  pages.nl/common/md5sum.md
  pages.nl/common/sha1sum.md
  pages.nl/common/sha224sum.md
  pages.nl/common/sha384sum.md
  pages.nl/common/sha512sum.md
Labels: translation

#15071 jobs: update Dutch more info link; pwd: update Dutch translation
  pages.nl/linux/jobs.md
  pages/common/pwd.md
Labels: page edit, translation

#15072 dnf5-group,pacman-f: add Dutch alias pages
  pages.nl/linux/dnf5-group.md
  pages.nl/linux/pacman-f.md
Labels: translation

#15043 tex-fmt: add page
  pages/common/tex-fmt.md
Labels: new command

#15104 basenc: update documentation link
  pages.ko/common/basenc.md
  pages.nl/common/basenc.md
  pages/common/basenc.md
Labels: page edit, translation

#15103 basename: update documentation link
  pages.de/common/basename.md
  pages.es/common/basename.md
  pages.fr/common/basename.md
  pages.it/common/basename.md
  pages.ko/common/basename.md
  pages.nl/common/basename.md
  pages.pl/common/basename.md
  pages.pt_BR/common/basename.md
  pages.zh/common/basename.md
  pages/common/basename.md
Labels: page edit, translation

#15022 rmdir, shutdown, whoami, winget: update Chinese translation
  pages.zh/windows/rmdir.md
  pages.zh/windows/shutdown.md
  pages.zh/windows/whoami.md
  pages.zh/windows/winget.md
Labels: translation

#15113 git-branch: update page
  pages/common/git-branch.md
Labels: page edit

#15042 pulumi-config: add Spanish translation
  pages.es/common/pulumi-config.md
Labels: translation

#15085 dnf-group: add Spanish translation
  pages.es/linux/dnf-group.md
Labels: translation

#15086 complete: add Spanish translation
  pages.es/common/complete.md
Labels: translation

#15087 compgen: add Spanish translation
  pages.es/common/compgen.md
Labels: translation

#15088 qm: add Spanish translation
  pages.es/linux/qm.md
Labels: translation

#15089 qm-cleanup: add Spanish translation
  pages.es/linux/qm-cleanup.md
Labels: translation

#15091 ip-address: add Spanish translation
  pages.es/linux/ip-address.md
Labels: translation

#15092 ip-link: add Spanish translation
  pages.es/linux/ip-link.md
Labels: translation

#15093 ip-neighbour: add Spanish translation
  pages.es/linux/ip-neighbour.md
Labels: translation

#15105 tex-fmt: add Spanish translation
  pages.es/common/tex-fmt.md
Labels: translation

#15101 qm-create: add Spanish translation
  pages.es/linux/qm-create.md
Labels: translation

#15100 qm-config: add Spanish translation
  pages.es/linux/qm-config.md
Labels: translation

#15099 qm-cloudinit-dump: add Spanish translation
  pages.es/linux/qm-cloudinit-dump.md
Labels: translation

#15098 qm-cloud-init: add Spanish translation
  pages.es/linux/qm-cloud-init.md
Labels: translation

#15097 qm-clone: add Spanish translation
  pages.es/linux/qm-clone.md
Labels: translation

#15096 ip-rule: add Spanish translation
  pages.es/linux/ip-rule.md
Labels: translation

#15094 ip-route: add Spanish translation
  pages.es/linux/ip-route.md
Labels: translation

#15112 qm-destroy: add Spanish translation
  pages.es/linux/qm-destroy.md
Labels: translation

#15114 gum: add Spanish translation
  pages.es/common/gum.md
Labels: translation

#15115 whiptail: add Spanish translation
  pages.es/linux/whiptail.md
Labels: translation

#15117 zenity: add Spanish translation
  pages.es/linux/zenity.md
Labels: translation

#15118 qm-guest-cmd: add Spanish translation
  pages.es/linux/qm-guest-cmd.md
Labels: translation

#15119 qm-guest-exec: add Spanish translation
  pages.es/linux/qm-guest-exec.md
Labels: translation

#15120 qm-guest-exec-status: add Spanish translation
  pages.es/linux/qm-guest-exec-status.md
Labels: translation

#15121 qm-guest-passwd: add Spanish translation
  pages.es/linux/qm-guest-passwd.md
Labels: translation

#15110 gh-skyline: add page
  pages/common/gh-skyline.md
Labels: new command

#15124 tag: add page
  pages/osx/tag.md
Labels: new command

#15036 loginctl: add user logout example
  pages/linux/loginctl.md
Labels: page edit

#15125 qm-list: add Spanish translation
  pages.es/linux/qm-list.md
Labels: translation

#15128 qm-mtunnel: add Spanish translation
  pages.es/linux/qm-mtunnel.md
Labels: translation

#15129 qm-monitor: add Spanish translation
  pages.es/linux/qm-monitor.md
Labels: translation

#15127 qm-migrate: add Spanish translation
  pages.es/linux/qm-migrate.md
Labels: translation

#15130 qm-nbdstop: add Spanish translation
  pages.es/linux/qm-nbdstop.md
Labels: translation

#15132 qm-reboot: add Spanish translation
  pages.es/linux/qm-reboot.md
Labels: translation

#15134 qm-reset: add Spanish translation
  pages.es/linux/qm-reset.md
Labels: translation

#15135 qm-resume: add Spanish translation
  pages.es/linux/qm-resume.md
Labels: translation

#15131 qm-pending: add Spanish translation
  pages.es/linux/qm-pending.md
Labels: translation

#15133 qm-rescan: add Spanish translation
  pages.es/linux/qm-rescan.md
Labels: translation

#15140 qmmp: add Spanish translation
  pages.es/common/qmmp.md
Labels: translation

#15136 qm-rollback: add Spanish translation
  pages.es/linux/qm-rollback.md
Labels: translation

#15138 qmv: add Spanish translation
  pages.es/common/qmv.md
Labels: translation

#15139 chgrp: update documentation link
  pages.fr/common/chgrp.md
  pages.it/common/chgrp.md
  pages.ko/common/chgrp.md
  pages.nl/common/chgrp.md
  pages/common/chgrp.md
Labels: page edit, translation

#15141 chroot: update documentation link
  pages.de/common/chroot.md
  pages.fr/common/chroot.md
  pages.it/common/chroot.md
  pages.ko/common/chroot.md
  pages.nl/common/chroot.md
  pages.tr/common/chroot.md
  pages/common/chroot.md
Labels: page edit, translation

#15144 cp: update documentation link
  pages.ca/common/cp.md
  pages.ca/linux/cp.md
  pages.de/common/cp.md
  pages.de/linux/cp.md
  pages.es/common/cp.md
  pages.es/linux/cp.md
  pages.fa/common/cp.md
  pages.fr/common/cp.md
  pages.fr/linux/cp.md
  pages.hi/common/cp.md
  pages.id/common/cp.md
  pages.it/common/cp.md
  pages.it/linux/cp.md
  pages.ja/common/cp.md
  pages.ko/common/cp.md
  pages.ko/linux/cp.md
  pages.ne/common/cp.md
  pages.nl/common/cp.md
  pages.nl/linux/cp.md
  pages.pl/common/cp.md
  pages.pt_BR/common/cp.md
  pages.pt_BR/linux/cp.md
  pages.ta/common/cp.md
  pages.tr/common/cp.md
  pages.tr/linux/cp.md
  pages.uk/linux/cp.md
  pages.zh/common/cp.md
  pages.zh/linux/cp.md
  pages.zh_TW/common/cp.md
  pages.zh_TW/linux/cp.md
  pages/common/cp.md
  pages/linux/cp.md
Labels: page edit, translation

#15142 cksum: update documentation link
  pages.hi/common/cksum.md
  pages.it/common/cksum.md
  pages.ko/common/cksum.md
  pages.nl/common/cksum.md
  pages.ta/common/cksum.md
  pages/common/cksum.md
Labels: page edit, translation

#15157 qm-wait: add Spanish translation
  pages.es/linux/qm-wait.md
Labels: translation

#15143 comm: update documentation link
  pages.it/common/comm.md
  pages.ko/common/comm.md
  pages.nl/common/comm.md
  pages/common/comm.md
Labels: page edit, translation

#15163 batch: revert changes
  pages/common/batch.md
Labels: page edit

#15164 emerge: update page
  pages/linux/emerge.md
Labels: page edit

#15145 vitest: add page
  pages/common/vitest.md
Labels: new command

#15162 kwallet-query: add page
  pages/linux/kwallet-query.md
Labels: new command

#15109 ruff: add Spanish translation
  pages.es/common/ruff.md
Labels: translation

#15146 qm-sendkey: add Spanish translation
  pages.es/linux/qm-sendkey.md
Labels: translation

#15147 qm-showcmd: add Spanish translation
  pages.es/linux/qm-showcmd.md
Labels: translation

#15148 qm-shutdown: add Spanish translation
  pages.es/linux/qm-shutdown.md
Labels: translation

#15150 qm-start: add Spanish translation
  pages.es/linux/qm-start.md
Labels: translation

#15151 qm-status: add Spanish translation
  pages.es/linux/qm-status.md
Labels: translation

#15152 qm-stop: add Spanish translation
  pages.es/linux/qm-stop.md
Labels: translation

#15155 qm-unlock: add Spanish translation
  pages.es/linux/qm-unlock.md
Labels: translation

#15156 qm-vncproxy: add Spanish translation
  pages.es/linux/qm-vncproxy.md
Labels: translation

#15123 !, ipconfig: update Chinese translation
  pages.zh/common/!.md
  pages.zh/windows/ipconfig.md
Labels: translation

#15149 qm-snapshot: add Spanish translation
  pages.es/linux/qm-snapshot.md
Labels: translation

#15158 obs: add Spanish translation
  pages.es/common/obs.md
Labels: translation

#15159 tilde: add Spanish translation
  pages.es/common/~.md
Labels: translation

#15168 ls: update documentation link
  pages.ar/common/ls.md
  pages.ca/common/ls.md
  pages.de/common/ls.md
  pages.es/common/ls.md
  pages.fa/common/ls.md
  pages.fr/common/ls.md
  pages.hi/common/ls.md
  pages.id/common/ls.md
  pages.it/common/ls.md
  pages.ja/common/ls.md
  pages.ko/common/ls.md
  pages.ne/common/ls.md
  pages.nl/common/ls.md
  pages.pl/common/ls.md
  pages.pt_BR/common/ls.md
  pages.ru/common/ls.md
  pages.ta/common/ls.md
  pages.th/common/ls.md
  pages.zh/common/ls.md
  pages.zh_TW/common/ls.md
  pages/common/ls.md
Labels: page edit, translation

#15172 pdftohtml: add Spanish translation
  pages.es/linux/pdftohtml.md
Labels: translation

#15171 pdfdetach: add Spanish translation
  pages.es/linux/pdfdetach.md
Labels: translation

#15169 pdfattach: add Spanish translation
  pages.es/linux/pdfattach.md
Labels: translation

#15167 gh-skyline: add Spanish translation
  pages.es/common/gh-skyline.md
Labels: translation

#15176 cidr: add page
  pages/common/cidr.md
Labels: new command

#15027 grub2-mkpasswd-pbkdf2: add page
  pages/linux/grub2-mkpasswd-pbkdf2.md
Labels: new command

#15174 pdfxup: add Spanish translation
  pages.es/linux/pdfxup.md
Labels: translation

#15188 patch: add Spanish translation
  pages.es/common/patch.md
Labels: translation

#15187 pgrep: add Spanish translation
  pages.es/common/pgrep.md
Labels: translation

#15186 pg_isready: add Spanish translation
  pages.es/common/pg_isready.md
Labels: translation

#15185 pg_restore: add Spanish translation
  pages.es/common/pg_restore.md
Labels: translation

#15184 pg_dumpall: add Spanish translation
  pages.es/common/pg_dumpall.md
Labels: translation

#15183 pg_dump: add Spanish translation
  pages.es/common/pg_dump.md
Labels: translation

#15181 pgbench: add Spanish translation
  pages.es/common/pgbench.md
Labels: translation

#15182 pg_ctl: add Spanish translation
  pages.es/common/pg_ctl.md
Labels: translation

#15165 btop: add `--update` example
  pages/common/btop.md
Labels: page edit
