Repository tldr-pages/tldr, pull requests merged in 2024-09, with the labels that each got.

#13541 codecrafters: add page
  pages/common/codecrafters.md
Labels: new command

#13515 nxc-ftp: add Spanish translation
  pages.es/common/nxc-ftp.md
Labels: translation

#13505 mkfifo: add Spanish translation
  pages.es/common/mkfifo.md
Labels: translation

#13503 ipscan, pacgraph: add Spanish translation
  pages.es/common/ipscan.md
  pages.es/linux/pacgraph.md
Labels: translation

#13567 pages*: convert long-short to short-long syntax
  pages.id/common/bat.md
  pages.nl/common/bat.md
  pages.nl/common/http.md
  pages/common/bat.md
  pages/common/git-add.md
  pages/common/git-annotate.md
  pages/common/git-archive.md
  pages/common/git-blame.md
  pages/common/git-branch.md
  pages/common/git-cherry.md
  pages/common/git-clean.md
  pages/common/git-diff-tree.md
  pages/common/git-lfs.md
  pages/common/git-log.md
  pages/common/git-rebase.md
  pages/common/git-reflog.md
  pages/common/git-remote.md
  pages/common/git-rev-list.md
  pages/common/git-revert.md
  pages/common/git-shortlog.md
  pages/common/git-svn.md
  pages/common/git-tag.md
  pages/common/http.md
  pages/common/mitmproxy.md
Labels: page edit, translation

#13566 CI: check if the more info link is up-to-date
  scripts/check-pr.sh
Labels: tooling

#13582 CODEOWNERS: add @debghs for Hindi pages
  .github/CODEOWNERS
Labels: community

#13546 am: update Polish translation
  pages.pl/android/am.md
Labels: translation

#13547 bugreportz, cmd: update Polish translation
  pages.pl/android/bugreportz.md
  pages.pl/android/cmd.md
Labels: translation

#13551 input: update Polish translation
  pages.pl/android/input.md
Labels: translation

#13553 settings: update Polish translation
  pages.pl/android/settings.md
Labels: translation

#13552 logcat, pm: update Polish translation
  pages.pl/android/logcat.md
  pages.pl/android/pm.md
Labels: translation

#13557 7z: update Polish translation
  pages.pl/common/7z.md
Labels: translation

#13558 7za: update Polish translation
  pages.pl/common/7za.md
Labels: translation

#13562 adb-install: update Polish translation
  pages.pl/common/adb-install.md
Labels: translation

#13560 [: update Polish translation
  pages.pl/common/[.md
Labels: translation

#13561 ack: update Polish translation
  pages.pl/common/ack.md
Labels: translation

#13563 adb: update Polish translation
  pages.pl/common/adb.md
Labels: translation

#13523 kde-builder: add Spanish translation
  pages.es/linux/kde-builder.md
Labels: translation

#13526 flatpak: add Spanish translation
  pages.es/linux/flatpak.md
Labels: translation

#13527 flatpak-run: add Spanish translation
  pages.es/linux/flatpak-run.md
Labels: translation

#13549 mitmproxy: add Spanish translation
  pages.es/common/mitmproxy.md
Labels: translation

#13594 ab, ack, acme.sh-dns, acme.sh: update Korean translation
  pages.ko/common/ab.md
  pages.ko/common/ack.md
  pages.ko/common/acme.sh-dns.md
  pages.ko/common/acme.sh.md
Labels: translation

#13589 at: update Polish translation
  pages.pl/common/at.md
Labels: translation

#13588 astronomer: update Polish translation
  pages.pl/common/astronomer.md
Labels: translation

#13587 arp: update Polish translation
  pages.pl/common/arp.md
Labels: translation

#13585 adb-shell: update Polish translation
  pages.pl/common/adb-shell.md
Labels: translation

#13584 adb-reverse: update Polish translation
  pages.pl/common/adb-reverse.md
Labels: translation

#13591 atq: update Polish translation
  pages.pl/common/atq.md
Labels: translation

#13586 ag: update Polish translation
  pages.pl/common/ag.md
Labels: translation

#13592 truss, svcs: update Polish translation
  pages.pl/sunos/svcs.md
  pages.pl/sunos/truss.md
Labels: translation

#13590 atom: update page and Polish translation
  pages.pl/common/atom.md
  pages/common/atom.md
Labels: page edit, translation

#13597 rm: add safe directory removal example
  pages/linux/rm.md
Labels: page edit

#13595 passwd: add longform options
  pages/common/passwd.md
Labels: page edit

#13601 adb-shell, adguardgome: update Korean translation
  pages.ko/common/adb-shell.md
  pages.ko/common/adguardhome.md
Labels: translation

#13538 bfs: add Spanish translation
  pages.es/common/bfs.md
Labels: translation

#13610 hugo-server: add page
  pages/common/hugo-server.md
Labels: new command

#13593 chown: add example to French translation
  pages.fr/common/chown.md
Labels: translation

#13608 deb-get: correct examples and move to linux section
  pages/linux/deb-get.md
Labels: page edit

#13596 wofi: add page
  pages/linux/wofi.md
Labels: new command

#13622 mkdir: add longform options
  pages.es/common/mkdir.md
  pages.fa/common/mkdir.md
  pages.fr/common/mkdir.md
  pages.hi/common/mkdir.md
  pages.id/common/mkdir.md
  pages.it/common/mkdir.md
  pages.ko/common/mkdir.md
  pages.nl/common/mkdir.md
  pages.sr/common/mkdir.md
  pages.ta/common/mkdir.md
  pages.tr/common/mkdir.md
  pages.zh/common/mkdir.md
  pages.zh_TW/common/mkdir.md
  pages/common/mkdir.md
Labels: page edit, translation

#13621 cjxl, djxl: move to common
  pages.es/common/cjxl.md
  pages.es/common/djxl.md
  pages/common/cjxl.md
  pages/common/djxl.md
Labels: page edit, translation

#13603 CI: mute output from Python script
  scripts/check-pr.sh
Labels: tooling

#13623 pg_dumpall: update page
  pages/common/pg_dumpall.md
Labels: page edit

#13620 ani-cli: add Korean translation
  pages.ko/common/ani-cli.md
Labels: translation

#13617 amass*: add Korean translation
  pages.ko/common/amass-enum.md
  pages.ko/common/amass-intel.md
  pages.ko/common/amass.md
Labels: translation

#13599 dos2unix: add French translation
  pages.fr/linux/dos2unix.md
Labels: translation

#13612 audit2allow: add page
  pages/linux/audit2allow.md
Labels: new command

#13636 git-commit, rubocop: use grouped parameters
  pages/common/git-commit.md
  pages/common/rubocop.md
Labels: page edit

#13635 trash: adjust wording, trash-cli: make into an alias of trash
  pages/common/trash-cli.md
  pages/linux/trash.md
Labels: page edit

#13634 npm: add --yes to init and add shortform options
  pages.de/common/npm.md
  pages.es/common/npm.md
  pages.id/common/npm.md
  pages.ko/common/npm.md
  pages.pt_BR/common/npm.md
  pages/common/npm.md
Labels: page edit, translation

#13624 azure-cli, musl-gcc, nc: add French translation; nc: update page
  pages.fr/common/azure-cli.md
  pages.fr/common/musl-gcc.md
  pages.fr/common/netcat.md
  pages/common/netcat.md
Labels: page edit, translation

#13607 quickget: fix correct examples and update changed options
  pages/linux/quickget.md
Labels: page edit

#13638 apkleaks, arduino*, aspell, archwiki-rs, atktopbm, audtool, autojump, autopep8: add Korean translation
  pages.ko/common/apkleaks.md
  pages.ko/common/archwiki-rs.md
  pages.ko/common/arduino-builder.md
  pages.ko/common/arduino.md
  pages.ko/common/aspell.md
  pages.ko/common/atktopbm.md
  pages.ko/common/audtool.md
  pages.ko/common/autojump.md
  pages.ko/common/autopep8.md
Labels: translation

#13643 docker-build: update documentation link
  pages.de/common/docker-build.md
  pages.fr/common/docker-build.md
  pages.id/common/docker-build.md
  pages.it/common/docker-build.md
  pages.ja/common/docker-build.md
  pages.ko/common/docker-build.md
  pages.pt_BR/common/docker-build.md
  pages.tr/common/docker-build.md
  pages.zh/common/docker-build.md
  pages/common/docker-build.md
Labels: page edit, translation

#13648 pngcheck: add Dutch translation and fix placeholder
  pages.nl/common/pngcheck.md
  pages.nl/linux/pngcheck.md
  pages/common/pngcheck.md
Labels: page edit, translation

#13655 bc, netcat, touch: update Dutch more info link, trash-cli: add Dutch translation
  pages.nl/common/bc.md
  pages.nl/common/netcat.md
  pages.nl/common/touch.md
  pages.nl/common/trash-cli.md
Labels: translation

#13639 git-*: add and update Indonesian translations
  pages.id/common/git-add.md
  pages.id/common/git-bulk.md
  pages.id/common/git-bundle.md
  pages.id/common/git-cherry-pick.md
  pages.id/common/git-clean.md
  pages.id/common/git-clear.md
  pages.id/common/git-count.md
  pages.id/common/git-cp.md
  pages.id/common/git-create-branch.md
  pages.id/common/git-format-patch.md
  pages.id/common/git-init.md
  pages.id/common/git-push.md
  pages.id/common/git-remote.md
  pages.id/common/git-rm.md
  pages.id/common/git-status.md
Labels: translation

#13665 sfdisk: add page
  pages/linux/sfdisk.md
Labels: new command

#13644 mkdir: update Chinese translation
  pages.zh/common/mkdir.md
Labels: translation

#13674 pulumi-up: add --continue-on-error example
  pages/common/pulumi-up.md
Labels: page edit

#13675 docker-commit: update documentation link
  pages.fr/common/docker-commit.md
  pages.pt_BR/common/docker-commit.md
  pages/common/docker-commit.md
Labels: page edit, translation

#13657 trash: add Dutch translation and fix placeholder
  pages.nl/linux/trash.md
  pages.tr/linux/trash.md
  pages/linux/trash.md
Labels: page edit, translation

#13678 xh: update page
  pages/common/xh.md
Labels: page edit

#13693 reboot: add Dutch translation
  pages.nl/linux/reboot.md
  pages.nl/osx/reboot.md
Labels: translation

#13681 babel: update Polish translation
  pages.pl/common/babel.md
Labels: translation

#13679 atrm, autoflake, awk: update Polish translation
  pages.pl/common/atrm.md
  pages.pl/common/autoflake.md
  pages.pl/common/awk.md
Labels: translation

#13695 README: add Mastodon badge
  README.md
Labels: documentation

#13698 ls: refresh descriptions
  pages/common/ls.md
Labels: page edit

#13677 az: add examples
  pages/common/az.md
Labels: page edit

#13666 dircolors: add example to print the colors
  pages/common/dircolors.md
Labels: page edit

#13700 docker-compose: update documentation link
  pages.de/common/docker-compose.md
  pages.es/common/docker-compose.md
  pages.fr/common/docker-compose.md
  pages.id/common/docker-compose.md
  pages.it/common/docker-compose.md
  pages.ja/common/docker-compose.md
  pages.ko/common/docker-compose.md
  pages.ne/common/docker-compose.md
  pages.pt_BR/common/docker-compose.md
  pages.tr/common/docker-compose.md
  pages/common/docker-compose.md
Labels: page edit, translation

#13703 docker-container-diff: update documentation link
  pages.fr/common/docker-diff.md
  pages.nl/common/docker-container-diff.md
  pages.nl/common/docker-diff.md
  pages.pl/common/docker-container-diff.md
  pages/common/docker-container-diff.md
  pages/common/docker-diff.md
Labels: page edit, translation

#13704 mkfs.xfs: add page
  pages/linux/mkfs.xfs.md
Labels: new command

#13708 az-*: add Korean translation
  pages.ko/common/az-account.md
  pages.ko/common/az-acr.md
  pages.ko/common/az-advisor.md
  pages.ko/common/az-aks.md
  pages.ko/common/az-apim.md
  pages.ko/common/az-appconfig.md
  pages.ko/common/az-bicep.md
  pages.ko/common/az-config.md
  pages.ko/common/az-devops.md
  pages.ko/common/az-feedback.md
Labels: translation

#13710 mysql_secure_installation: add page
  pages/common/mysql_secure_installation.md
Labels: new command

#13709 az serial-console: add page, az: improve command
  pages/common/az-serial-console.md
  pages/common/az-vm.md
Labels: page edit, new command

#13712 unzip: improve example clarity
  pages/common/unzip.md
Labels: page edit

#13713 chat: add page
  pages/linux/chat.md
Labels: new command

#13722 docker-rm: update documentation link
  pages.fr/common/docker-rm.md
  pages.nl/common/docker-container-remove.md
  pages.nl/common/docker-container-rm.md
  pages.nl/common/docker-rm.md
  pages.pl/common/docker-container-remove.md
  pages.pl/common/docker-container-rm.md
  pages/common/docker-container-remove.md
  pages/common/docker-container-rm.md
  pages/common/docker-rm.md
Labels: page edit, translation

#13737 docker-container: update documentation link
  pages.de/common/docker-container.md
  pages.fr/common/docker-container.md
  pages.it/common/docker-container.md
  pages.ko/common/docker-container.md
  pages.pt_BR/common/docker-container.md
  pages/common/docker-container.md
Labels: page edit, translation

#13745 aws-ce: update page
  pages/common/aws-ce.md
Labels: page edit

#13733 lychee: add page
  pages/common/lychee.md
Labels: new command

#13739 CODEOWNERS: remove @spageektti as CODEOWNER from `pages/`
  .github/CODEOWNERS
Labels: community

#13746 chsh: remove sudo where not needed
  pages.nl/linux/chsh.md
  pages/linux/chsh.md
Labels: page edit, translation

#13776 ffmpeg: update page
  pages/common/ffmpeg.md
Labels: page edit

#13772 brittany, brotli, bru: add Korean translation
  pages.ko/common/brittany.md
  pages.ko/common/brotli.md
  pages.ko/common/bru.md
Labels: translation

#13771 firewall-cmd: clarify runtime/permanent configuration and add commands
  pages/linux/firewall-cmd.md
Labels: page edit

#13770 bcachefs: update header; bcachefs-device: add page
  pages/linux/bcachefs-device.md
  pages/linux/bcachefs.md
Labels: page edit, new command

#13691 rm: add Dutch translation
  pages.nl/linux/rm.md
Labels: translation, review needed

#13692 rename: add Dutch translation
  pages.nl/linux/rename.md
  pages.nl/osx/rename.md
Labels: translation, review needed

#13694 read: add Dutch translation
  pages.nl/common/read.md
Labels: translation, review needed

#13718 az: update Dutch translation
  pages.nl/common/az.md
Labels: translation

#13719 dircolors: update Dutch translation
  pages.nl/common/dircolors.md
Labels: translation

#13750 CONTRIBUTING: mention Translation Status Dashboard
  CONTRIBUTING.md
Labels: documentation

#13752 ceph: fix link
  pages/linux/ceph.md
Labels: page edit

#13734 betty, bfg, bgpgrep, bindkey, binwalk, bioradtopgm, bird, birdc, bison, bitconid: add Korean translation
  pages.ko/common/betty.md
  pages.ko/common/bfg.md
  pages.ko/common/bgpgrep.md
  pages.ko/common/bindkey.md
  pages.ko/common/binwalk.md
  pages.ko/common/bioradtopgm.md
  pages.ko/common/bird.md
  pages.ko/common/birdc.md
  pages.ko/common/bison.md
  pages.ko/common/bitcoind.md
Labels: translation

#13743 bmptopnm, bmptoppm, bob: add Korean translation
  pages.ko/common/bmptopnm.md
  pages.ko/common/bmptoppm.md
  pages.ko/common/bob.md
Labels: translation

#13749 bpkg, bpytop, bq: add Korean translation
  pages.ko/common/bpkg.md
  pages.ko/common/bpytop.md
  pages.ko/common/bq.md
Labels: translation

#13755 brew-*: add Korean translation
  pages.ko/common/brew-autoremove.md
  pages.ko/common/brew-bundle.md
  pages.ko/common/brew-install.md
  pages.ko/common/brew-list.md
  pages.ko/common/brew-outdated.md
  pages.ko/common/brew-search.md
  pages.ko/common/brew-uninstall.md
  pages.ko/common/brew-update.md
  pages.ko/common/brew-upgrade.md
Labels: translation

#13778 brushtopbm, bshell, bssh, btm, btop, buku: add Korean translation
  pages.ko/common/brushtopbm.md
  pages.ko/common/bshell.md
  pages.ko/common/bssh.md
  pages.ko/common/btm.md
  pages.ko/common/btop.md
  pages.ko/common/buku.md
Labels: translation

#13727 b2-tools, b3sum, babeld, bandwhich, basenc, bash-it, bastet, bats, bazel, bcomps: add Korean translation
  pages.ko/common/b2-tools.md
  pages.ko/common/b3sum.md
  pages.ko/common/babeld.md
  pages.ko/common/bandwhich.md
  pages.ko/common/basenc.md
  pages.ko/common/bash-it.md
  pages.ko/common/bastet.md
  pages.ko/common/bats.md
  pages.ko/common/bazel.md
  pages.ko/common/bcomps.md
Labels: translation

#13714 az-*: add Korean translation
  pages.ko/common/az-group.md
  pages.ko/common/az-lock.md
  pages.ko/common/az-login.md
  pages.ko/common/az-logout.md
  pages.ko/common/az-network.md
  pages.ko/common/az-pipelines.md
  pages.ko/common/az-provider.md
  pages.ko/common/az-redis.md
  pages.ko/common/az-repos.md
  pages.ko/common/az-sshkey.md
  pages.ko/common/az-storage-account.md
  pages.ko/common/az-storage-blob.md
  pages.ko/common/az-storage-container.md
  pages.ko/common/az-storage-entity.md
  pages.ko/common/az-storage-queue.md
  pages.ko/common/az-storage-table.md
  pages.ko/common/az-storage.md
  pages.ko/common/az-tag.md
  pages.ko/common/az-term.md
  pages.ko/common/az-upgrade.md
  pages.ko/common/az-version.md
  pages.ko/common/az-vm.md
  pages.ko/common/az-webapp.md
  pages.ko/common/azure-cli.md
  pages.ko/common/azurite.md
Labels: translation

#13702 aws*: add Korean translation
  pages.ko/common/aws-kafka.md
  pages.ko/common/aws-kendra.md
  pages.ko/common/aws-s3-cp.md
  pages.ko/common/aws-s3-ls.md
  pages.ko/common/aws-s3-mb.md
  pages.ko/common/aws-s3-mv.md
  pages.ko/common/aws-s3-presign.md
  pages.ko/common/aws-s3-rb.md
  pages.ko/common/aws-s3-website.md
  pages.ko/common/aws-s3api.md
  pages.ko/common/aws-secretsmanager.md
  pages.ko/common/aws-ses.md
  pages.ko/common/aws-sns.md
  pages.ko/common/aws-sqs.md
  pages.ko/common/aws-sts.md
  pages.ko/common/aws-vault.md
  pages.ko/common/aws-workmail.md
  pages.ko/common/awslogs.md
Labels: translation

#13696 aws-*: add Korean translation
  pages.ko/common/aws-configure.md
  pages.ko/common/aws-cur.md
  pages.ko/common/aws-dynamodb.md
  pages.ko/common/aws-ec2.md
  pages.ko/common/aws-ecr.md
  pages.ko/common/aws-eks.md
  pages.ko/common/aws-glue.md
  pages.ko/common/aws-help.md
  pages.ko/common/aws-history.md
  pages.ko/common/aws-iam.md
Labels: translation

#13647 pulumi-login: add Spanish translation
  pages.es/common/pulumi-login.md
Labels: translation

#13531 ya, yazi: add Spanish translation
  pages.es/common/ya.md
  pages.es/common/yazi.md
Labels: translation, review needed

#13600 read: add Spanish translation
  pages.es/common/read.md
Labels: translation, review needed

#13604 passwd: add Spanish translation
  pages.es/common/passwd.md
Labels: translation, review needed

#13659 sslstrip: add Spanish translation
  pages.es/linux/sslstrip.md
Labels: translation

#13660 pants: add Spanish translation
  pages.es/common/pants.md
Labels: translation

#13669 aws*: add Korean translation
  pages.ko/common/aws-cloudformation.md
  pages.ko/common/aws-codeartifact.md
  pages.ko/common/aws-codecommit.md
  pages.ko/common/aws-cognito-idp.md
Labels: translation

#13682 pwd: add Dutch translation
  pages.nl/common/pwd.md
  pages.nl/linux/pwd.md
Labels: translation, review needed

#13683 ps: add Dutch translation
  pages.nl/common/ps.md
  pages.nl/osx/ps.md
Labels: translation, review needed

#13684 print: add Dutch translation
  pages.nl/linux/print.md
  pages.nl/windows/print.md
Labels: translation, review needed

#13685 powershell: add Dutch translation
  pages.nl/windows/powershell.md
Labels: translation, review needed

#13686 pushd: add Dutch translation
  pages.nl/common/pushd.md
  pages.nl/windows/pushd.md
Labels: translation, review needed

#13687 popd: add Dutch translation
  pages.nl/common/popd.md
  pages.nl/windows/popd.md
Labels: translation, review needed

#13688 rpcinfo: add Dutch translation
  pages.nl/linux/rpcinfo.md
  pages.nl/windows/rpcinfo.md
Labels: translation, review needed

#13689 rmdir, route: add Dutch translation
  pages.nl/common/rmdir.md
  pages.nl/common/route.md
  pages.nl/linux/rmdir.md
  pages.nl/osx/route.md
Labels: translation, review needed

#13690 renice: add Dutch translation
  pages.nl/common/renice.md
  pages.nl/linux/renice.md
Labels: translation, review needed

#13671 toipe: fix verbs in Spanish translation
  pages.es/common/toipe.md
Labels: translation

#13769 pulumi-preview: add page
  pages/common/pulumi-preview.md
Labels: new command

#13768 pulumi-about: add page
  pages/common/pulumi-about.md
Labels: new command

#13759 lsd: update page
  pages/common/lsd.md
Labels: page edit

#13731 xfs_repair: add page
  pages/linux/xfs_repair.md
Labels: new command

#13715 timedatectl: add Chinese translation
  pages.zh/linux/timedatectl.md
Labels: translation

#13782 MAINTAINERS: add @nelsonfigueroa as collaborator
  MAINTAINERS.md
Labels: community

#13738 dotenvx: add page
  pages/common/dotenvx.md
Labels: new command

#13785 mknod: add Chinese translation
  pages.zh/linux/mknod.md
Labels: translation

#13777 pages*: fix placeholder
  pages.zh_TW/common/mkdir.md
  pages/common/cs-resolve.md
  pages/common/git-log.md
  pages/common/vboxmanage-cloud.md
  pages/linux/mt.md
  pages/linux/urpmi.addmedia.md
Labels: page edit, translation

#13748 bspc: add Brazilian Portuguese translation
  pages.pt_BR/linux/bspc.md
Labels: translation

#13751 clang, clang++, gcc, g++: standardize English page and Indonesian translation
  pages.id/common/clang++.md
  pages.id/common/clang.md
  pages.id/common/g++.md
  pages.id/common/gcc.md
  pages/common/clang++.md
  pages/common/clang.md
  pages/common/g++.md
  pages/common/gcc.md
Labels: page edit, translation

#13797 MAINTAINERS: add @LiLittleCat as collaborator
  MAINTAINERS.md
Labels: community

#13747 gdal*: fix broken links
  pages/common/gdal_translate.md
  pages/common/gdaladdo.md
  pages/common/gdaldem.md
  pages/common/gdalwarp.md
Labels: page edit

#13716 poweroff: update Spanish translation
  pages.es/linux/poweroff.md
Labels: translation

#13805 docker-load: update documentation link
  pages.fr/common/docker-load.md
  pages.pt_BR/common/docker-load.md
  pages/common/docker-load.md
Labels: page edit, translation

#13804 docker-inspect: update documentation link
  pages.de/common/docker-inspect.md
  pages.fr/common/docker-inspect.md
  pages.it/common/docker-inspect.md
  pages.pt_BR/common/docker-inspect.md
  pages.tr/common/docker-inspect.md
  pages/common/docker-inspect.md
Labels: page edit, translation

#13803 docker-images: update documentation link
  pages.de/common/docker-images.md
  pages.fr/common/docker-images.md
  pages.it/common/docker-images.md
  pages.ko/common/docker-images.md
  pages.pl/common/docker-images.md
  pages.pt_BR/common/docker-images.md
  pages.tr/common/docker-images.md
  pages/common/docker-images.md
Labels: page edit, translation

#13786 aws-*: add Korean translation
  pages.ko/common/aws-kinesis.md
  pages.ko/common/aws-lambda.md
  pages.ko/common/aws-lightsail.md
  pages.ko/common/aws-pricing.md
  pages.ko/common/aws-quicksight.md
  pages.ko/common/aws-rds.md
  pages.ko/common/aws-route53.md
  pages.ko/common/aws-s3-rm.md
Labels: translation

#13802 mkfs.bcachefs: add page
  pages/linux/mkfs.bcachefs.md
Labels: new command

#13813 tail: fix link
  pages.nl/osx/tail.md
  pages/osx/tail.md
Labels: page edit, translation

#13828 journalctl: add quotation marks around space-separated timestamps
  pages.pl/linux/journalctl.md
  pages.uk/linux/journalctl.md
  pages/linux/journalctl.md
Labels: page edit, translation

#13814 doggo: fix link
  pages.es/common/doggo.md
  pages/common/doggo.md
Labels: page edit, translation

#13811 clang: update Dutch translation
  pages.nl/common/clang.md
Labels: translation

#13812 gcc: update Dutch translation
  pages.nl/common/gcc.md
Labels: translation

#13810 clang++: update Dutch translation
  pages.nl/common/clang++.md
Labels: translation

#13764 git-remote: update Spanish translation
  pages.es/common/git-remote.md
Labels: translation

#13763 git-rev-list: update Spanish translation
  pages.es/common/git-rev-list.md
Labels: translation

#13728 secret-tool: add page
  pages/linux/secret-tool.md
Labels: new command
