Repository tldr-pages/tldr, pull requests merged in 2025-09, with the labels that each got.

#17892 systemctl-restart: add page
  pages/linux/systemctl-restart.md
Labels: new command, review needed

#17926 rpm-ostree: add Italian translation
  pages.it/linux/rpm-ostree.md
Labels: new translation

#17924 pwd: add Italian translation
  pages.it/common/pwd.md
Labels: new translation

#17923 retroarch: add italian translation
  pages.it/linux/retroarch.md
Labels: new translation

#17921 wget: add Italian translation
  pages.it/windows/wget.md
Labels: new translation

#17865 crontab: updated Spanish translation
  pages.es/common/crontab.md
Labels: translation edit

#17898 helm: updated Spanish translation
  pages.es/common/helm.md
Labels: translation edit

#17922 rankmirrors: add Italian translation
  pages.it/linux/rankmirrors.md
Labels: new translation

#17943 history: remove unnecessary placeholder
  pages/common/history.md
Labels: page edit, review needed

#17927 nuclei: refresh page
  pages/common/nuclei.md
Labels: page edit, review needed

#17944 file: update page
  pages/common/file.md
Labels: page edit, review needed

#17906 systemctl-cat: add page
  pages/linux/systemctl-cat.md
Labels: new command, review needed

#17907 updatectl: simplify page
  pages/linux/updatectl.md
Labels: page edit

#17942 aur-sync: add page
  pages/linux/aur-sync.md
Labels: new command, review needed

#17934 lvconvert: add page
  pages/linux/lvconvert.md
Labels: new command, review needed

#17931 gksu, gksudo: add pages
  pages/linux/gksu.md
  pages/linux/gksudo.md
Labels: new command, review needed

#17958 ts-node: update more info link and update options
  pages/common/ts-node.md
Labels: page edit, review needed

#17956 choose: update more info link and short options
  pages/common/choose.md
Labels: page edit, review needed

#17970 pacman-sync: fix description
  pages/linux/pacman-sync.md
Labels: page edit, review needed

#17966 pngcheck: use manned
  pages/common/pngcheck.md
Labels: page edit, review needed

#17945 npm-docs: add page and Spanish translation
  pages.es/common/npm-docs.md
  pages/common/npm-docs.md
Labels: new command, new translation

#17954 tsc: add initialization example and short options
  pages/common/tsc.md
Labels: page edit, review needed

#17962 lp{rm, q, options}: remove optionality
  pages/common/lpoptions.md
  pages/common/lpq.md
  pages/common/lprm.md
Labels: page edit, review needed

#17976 ruby: refresh pages
  pages.fr/common/ruby.md
  pages.id/common/ruby.md
  pages.ko/common/ruby.md
  pages.ta/common/ruby.md
Labels: translation edit

#17972 a2ping: update Spanish page
  pages.es/common/a2ping.md
Labels: translation edit

#17815 dict: add Farsi translation
  pages.fa/common/airmon-ng.md
  pages.fa/common/dict.md
Labels: review needed, new translation

#17990 gpg: refresh pages
  pages.ar/common/gpg.md
  pages.de/common/gpg.md
  pages.ja/common/gpg.md
  pages.ko/common/gpg.md
  pages.pt_BR/common/gpg.md
  pages.zh/common/gpg.md
Labels: translation edit

#17982 comp, mimikatz-crypto: Add Spanish Translation
  pages.es/windows/comp.md
  pages.es/windows/mimikatz-crypto.md
Labels: new translation

#17948 clock, configure, crypto, delete, dir, enable, erase, interface, ip, line, login, question, reload, show, transport, username, write: add Spanish translation
  pages.es/cisco-ios/clock.md
  pages.es/cisco-ios/configure.md
  pages.es/cisco-ios/crypto.md
  pages.es/cisco-ios/delete.md
  pages.es/cisco-ios/dir.md
  pages.es/cisco-ios/enable.md
  pages.es/cisco-ios/erase.md
  pages.es/cisco-ios/interface.md
  pages.es/cisco-ios/ip.md
  pages.es/cisco-ios/line.md
  pages.es/cisco-ios/login.md
  pages.es/cisco-ios/question-mark.md
  pages.es/cisco-ios/reload.md
  pages.es/cisco-ios/show.md
  pages.es/cisco-ios/transport.md
  pages.es/cisco-ios/username.md
  pages.es/cisco-ios/write.md
Labels: mass changes, new translation

#17987 file: update page and add Dutch translation
  pages.nl/common/file.md
  pages/common/file.md
Labels: page edit, new translation

#17986 pages.nl/*: update Dutch translations
  pages.nl/common/alacritty.md
  pages.nl/common/ffmpeg.md
  pages.nl/common/lprm.md
  pages.nl/common/npm-ls.md
  pages.nl/common/pngcheck.md
Labels: translation edit

#17989 ghcup: update page and add Dutch translation
  pages.nl/common/ghcup.md
  pages/common/ghcup.md
Labels: page edit, new translation

#17997 uname: fix typo
  pages/common/uname.md
Labels: page edit, review needed

#17984 history: update page and add Dutch translation
  pages.nl/common/history.md
  pages/common/history.md
Labels: page edit, new translation

#17973 brew: remove deprecated `--devel` flag
  pages.es/common/brew.md
  pages.fr/common/brew.md
  pages.id/common/brew.md
  pages.it/common/brew.md
  pages.ja/common/brew.md
  pages.ko/common/brew.md
  pages.pt_BR/common/brew.md
  pages.ta/common/brew.md
  pages.zh/common/brew.md
  pages.zh_TW/common/brew.md
  pages/common/brew.md
Labels: page edit, review needed, translation edit

#17983 Aws-s3-cp: Add spanish translation
  pages.es/common/aws-s3-cp.md
Labels: new translation

#18005 pest: update more info link
  pages/common/pest.md
Labels: page edit, review needed

#18010 kubectl-describe: refresh page description
  pages/common/kubectl-describe.md
Labels: page edit, review needed

#18016 gnome-software: update more info link
  pages/linux/gnome-software.md
Labels: page edit, review needed

#18014 mdbook: update more info link
  pages/linux/mdbook.md
Labels: page edit, review needed

#17993 conda-doctor: Add spanish translation
  pages.es/common/conda-doctor.md
Labels: new translation

#18023 zip: refresh pages
  pages.ar/common/zip.md
  pages.fa/common/zip.md
  pages.fr/common/zip.md
  pages.ja/common/zip.md
  pages.ko/common/zip.md
  pages.pt_BR/common/zip.md
  pages.ru/common/zip.md
  pages.uk/common/zip.md
  pages.zh/common/zip.md
Labels: translation edit

#18020 flameshot: add short options
  pages/linux/flameshot.md
Labels: page edit, review needed

#18009 ufw: update page
  pages/linux/ufw.md
Labels: page edit, review needed

#17888 fonttools-subset: add page
  pages/linux/fonttools-subset.md
  pages/linux/fonttools.md
Labels: new command, review needed

#18030 yes: add backticks to apt-get
  pages.es/common/yes.md
  pages.ko/common/yes.md
  pages.nl/common/yes.md
  pages.pl/common/yes.md
  pages.pt_BR/common/yes.md
  pages.tr/common/yes.md
  pages.zh/common/yes.md
  pages/common/yes.md
Labels: page edit, translation edit

#18007 systemctl-*: add user unit examples
  pages/linux/systemctl-cat.md
  pages/linux/systemctl-disable.md
  pages/linux/systemctl-edit.md
  pages/linux/systemctl-enable.md
  pages/linux/systemctl-mask.md
  pages/linux/systemctl-restart.md
  pages/linux/systemctl-start.md
  pages/linux/systemctl-status.md
  pages/linux/systemctl-stop.md
Labels: page edit, mass changes, review needed

#18040 tldr: refresh pages
  pages.es/common/tldr.md
  pages.id/common/tldr.md
Labels: translation edit

#18041 trufflehog: remove unnecessary `=` sign
  pages.es/common/trufflehog.md
  pages.ko/common/trufflehog.md
Labels: translation edit

#18032 createdb: add short options and add Dutch translation
  pages.nl/common/createdb.md
  pages/common/createdb.md
Labels: page edit, new translation

#17985 cmatrix: add screensaver example
  pages/common/cmatrix.md
Labels: page edit, review needed

#18002 systemctl-suspend: add page
  pages/linux/systemctl-suspend.md
Labels: new command, review needed

#18057 dropdb: update page and add Dutch translation
  pages.nl/common/dropdb.md
  pages/common/dropdb.md
Labels: page edit, new translation

#17891 dnf, pacman: enhance Turkish translations; dnf*, pacman*: add Turkish translations
  pages.tr/linux/dnf-builddep.md
  pages.tr/linux/dnf-changelog.md
  pages.tr/linux/dnf-config-manager.md
  pages.tr/linux/dnf-deplist.md
  pages.tr/linux/dnf-download.md
  pages.tr/linux/dnf-group.md
  pages.tr/linux/dnf-install.md
  pages.tr/linux/dnf-module.md
  pages.tr/linux/dnf-repoquery.md
  pages.tr/linux/dnf.md
  pages.tr/linux/dnf5-group.md
  pages.tr/linux/dnf5.md
  pages.tr/linux/pacman-d.md
  pages.tr/linux/pacman-database.md
  pages.tr/linux/pacman-deptest.md
  pages.tr/linux/pacman-f.md
  pages.tr/linux/pacman-files.md
  pages.tr/linux/pacman-key.md
  pages.tr/linux/pacman-q.md
  pages.tr/linux/pacman-r.md
  pages.tr/linux/pacman-s.md
  pages.tr/linux/pacman-t.md
  pages.tr/linux/pacman-u.md
  pages.tr/linux/pacman-upgrade.md
  pages.tr/linux/pacman.md
  pages.tr/linux/pacman4console.md
Labels: mass changes, new translation, translation edit

#17964 xteddy: fix keypress syntax
  pages/common/xteddy.md
Labels: page edit, review needed

#17965 piper: fix more info link
  pages/common/piper.md
Labels: page edit, review needed

#17981 kde-builder: group options
  pages/linux/kde-builder.md
Labels: page edit, review needed

#17968 mamba, mamba-repoquery: update pages
  pages/common/mamba-repoquery.md
  pages/common/mamba.md
Labels: page edit, review needed

#17971 lvm_import_vdo: add page
  pages/linux/lvm_import_vdo.md
Labels: new command, review needed

#18060 hyprshot: add page
  pages/linux/hyprshot.md
Labels: new command, review needed

#18053 runas: add page
  pages/windows/runas.md
Labels: new command, review needed

#17996 pvesh: add usage instructions
  pages/linux/pvesh.md
Labels: page edit, review needed

#18048 lvmdiskscan: add page
  pages/linux/lvmdiskscan.md
Labels: new command, review needed

#18066 tqdm: update Spanish translation
  pages.es/common/tqdm.md
Labels: translation edit

#18068 grub-mkconfig: updated Spanish translation
  pages.es/linux/grub-mkconfig.md
Labels: translation edit

#18021 hexyl: remove unsupported examples
  pages/common/hexyl.md
Labels: page edit, review needed

#17979 $: update Spanish page
  pages.es/common/$.md
Labels: translation edit

#18089 g++: update page and add Dutch translation
  pages.nl/common/g++.md
  pages/common/g++.md
Labels: page edit, new translation

#18086 git-bisect: update page and add Dutch translation
  pages.nl/common/git-bisect.md
  pages/common/git-bisect.md
Labels: page edit, new translation

#17998 qm-agent: add Spanish translation
  pages.es/linux/qm-agent.md
Labels: new translation

#17999 avahi-browse: updated Spanish translation
  pages.es/linux/avahi-browse.md
Labels: translation edit

#18000 fzf: updated Spanish translation
  pages.es/common/fzf.md
Labels: translation edit

#18091 qdbus: fix syntax
  pages/common/qdbus.md
Labels: page edit, review needed

#18085 dbeaver: update page
  pages/common/dbeaver.md
Labels: page edit, review needed

#18078 ruby: add Dutch translation
  pages.nl/common/ruby.md
Labels: new translation

#18095 systemctl-suspend-then-hibernate: add page
  pages/linux/systemctl-suspend-then-hibernate.md
Labels: new command, review needed

#18088 pulumi-stack-history, pulumi-stack-hist: add page and alias
  pages/common/pulumi-stack-hist.md
  pages/common/pulumi-stack-history.md
Labels: new command, review needed

#18092 mkvpropedit: add page
  pages/linux/mkvpropedit.md
Labels: new command, review needed

#18101 wine: update Spanish translation
  pages.es/linux/wine.md
Labels: translation edit

#18087 feh: update page
  pages/common/feh.md
Labels: page edit, review needed

#18100 pivpn: update Spanish translation
  pages.es/linux/pivpn.md
Labels: translation edit

#18107 josm: update Spanish translation
  pages.es/common/josm.md
Labels: translation edit

#18111 git-diff: fix issues
  pages.es/common/git-diff.md
  pages.fr/common/git-diff.md
  pages.it/common/git-diff.md
  pages.ko/common/git-diff.md
  pages.pt_BR/common/git-diff.md
  pages.tr/common/git-diff.md
  pages.zh/common/git-diff.md
Labels: translation edit

#18098 omz: add enabled plugins example
  pages/common/omz.md
Labels: page edit, review needed

#18076 lvmpersist: add page
  pages/linux/lvmpersist.md
Labels: new command, review needed

#18056 poetry-env: change virtualenv verbiage
  pages/common/poetry-env.md
Labels: page edit, review needed

#17095 asciinema: add option placeholders
  pages/common/asciinema.md
Labels: page edit, review needed

#18006 style-guide: add argument order suggestion
  contributing-guides/style-guide.md
Labels: documentation

#18110 transmission-*: refresh pages
  pages.ko/common/transmission-create.md
  pages.ko/common/transmission-daemon.md
  pages.ko/common/transmission-show.md
  pages.pt_BR/common/transmission-create.md
  pages.pt_BR/common/transmission-daemon.md
  pages.pt_BR/common/transmission-show.md
Labels: translation edit

#18097 lvmpolld: add page
  pages/linux/lvmpolld.md
Labels: new command, review needed

#18130 git-show: reorder examples
  pages/common/git-show.md
Labels: page edit, review needed

#18129 git-subtree: refresh page
  pages/common/git-subtree.md
Labels: page edit, review needed

#18106 mkdir: Add Russian translation
  pages.ru/common/mkdir.md
Labels: review needed, new translation

#18137 gem: refresh pages
  pages.fr/common/gem.md
  pages.ko/common/gem.md
  pages.ta/common/gem.md
Labels: translation edit

#18138 sudo: Use imperative mood in description
  pages/common/sudo.md
Labels: page edit, review needed

#18104 sudo: Add Russian translation
  pages.ru/common/sudo.md
Labels: review needed, new translation

#18105 man: Add Russian translation
  pages.ru/common/man.md
Labels: review needed, new translation

#18025 brew-{autoremove, install, list, bundle}: add Chinese translation
  pages.zh/common/brew-autoremove.md
  pages.zh/common/brew-bundle.md
  pages.zh/common/brew-install.md
  pages.zh/common/brew-list.md
Labels: new translation

#18124 ansible: refresh pages
  pages.de/common/ansible.md
  pages.fr/common/ansible.md
  pages.id/common/ansible.md
  pages.it/common/ansible.md
  pages.ko/common/ansible.md
  pages.pt_BR/common/ansible.md
  pages.zh/common/ansible.md
Labels: translation edit

#18038 rpmkeys: add page and German translation
  pages.de/linux/rpmkeys.md
  pages/linux/rpmkeys.md
Labels: new command, new translation

#18159 asciinema: update Spanish translation
  pages.es/common/asciinema.md
Labels: review needed, translation edit

#18149 dropuser: add page
  pages/common/dropuser.md
Labels: new command, review needed

#18150 systemctl-emergency: add page
  pages/linux/systemctl-emergency.md
Labels: new command, review needed

#18165 bg, hostname, mcs, tty, which: add Spanish translation
  pages.es/common/bg.md
  pages.es/common/hostname.md
  pages.es/common/mcs.md
  pages.es/common/tty.md
  pages.es/common/which.md
Labels: review needed, new translation

#18167 batch: updated Spanish translation
  pages.es/common/batch.md
Labels: review needed, translation edit

#18120 gh-*: update pages
  pages/common/gh-alias.md
  pages/common/gh-codespace.md
  pages/common/gh-completion.md
  pages/common/gh-config.md
  pages/common/gh-extension.md
  pages/common/gh-gist.md
  pages/common/gh-help.md
  pages/common/gh-issue-create.md
  pages/common/gh-issue.md
  pages/common/gh-label.md
  pages/common/gh-pr-create.md
  pages/common/gh-pr-merge.md
  pages/common/gh-pr.md
  pages/common/gh-release.md
  pages/common/gh-repo-create.md
  pages/common/gh-repo.md
  pages/common/gh-screensaver.md
  pages/common/gh-secret.md
  pages/common/gh-ssh-key.md
  pages/common/gh-workflow.md
  pages/common/gh.md
Labels: page edit, mass changes, review needed

#18093 fuser: add page
  pages/osx/fuser.md
Labels: new command, review needed

#18170 sdelete64: updated Spanish translation
  pages.es/windows/sdelete64.md
Labels: review needed, translation edit

#18026 duti: add reference to osascript
  pages/osx/duti.md
Labels: page edit, review needed

#18168 lvmsadc: add page
  pages/linux/lvmsadc.md
Labels: new command, review needed

#18160 createuser: add Bosnian translation
  pages.bs/common/createuser.md
Labels: review needed, new translation

#18176 gh: update page and add Dutch translation
  pages.nl/common/gh.md
  pages/common/gh.md
Labels: page edit, new translation

#18185 *: improve more info links, org domain
  pages/common/behat.md
  pages/common/cf.md
  pages/common/scrapy.md
  pages/common/supervisorctl.md
  pages/common/supervisord.md
  pages/common/telegram-desktop.md
  pages/common/valgrind.md
  pages/common/you-get.md
  pages/common/zig.md
  pages/linux/postfix.md
  pages/osx/port.md
Labels: page edit, mass changes, review needed

#18187 adduser: add Dutch translation
  pages.nl/linux/adduser.md
Labels: new translation

#17977 ibmcloud: remove unsupported CF command
  pages.ko/common/ibmcloud.md
  pages/common/ibmcloud.md
Labels: page edit, translation edit

#18225 b2sum: updated Spanish translation
  pages.es/common/b2sum.md
Labels: review needed, translation edit

#18224 sfc: updated Spanish translation
  pages.es/windows/sfc.md
Labels: review needed, translation edit

#18222 vol: updated Spanish translation
  pages.es/windows/vol.md
Labels: review needed, translation edit

#18227 wget: updated Spanish translation
  pages.es/windows/wget.md
Labels: review needed, translation edit

#18228 tree: updated Spanish translation
  pages.es/windows/tree.md
Labels: review needed, translation edit

#18215 pulumi-stack-hist: add Spanish translation
  pages.es/common/pulumi-stack-hist.md
Labels: review needed, new translation

#18218 docker-stats: refresh pages
  pages.de/common/docker-stats.md
  pages.fr/common/docker-stats.md
  pages.ko/common/docker-stats.md
  pages.pt_BR/common/docker-stats.md
  pages.tr/common/docker-stats.md
Labels: translation edit

#18217 xkcdpass: refresh pages
  pages.ko/common/xkcdpass.md
  pages.pl/common/xkcdpass.md
Labels: translation edit

#18196 git-blame: fix filepath
  pages/common/git-blame.md
Labels: page edit, review needed

#18207 dbeaver, picotool: remove execution permissions from pages
  pages/common/dbeaver.md
  pages/common/picotool.md
Labels: page edit, review needed

#18184 *: improve more info links, com domain
  pages/common/caddy.md
  pages/common/ember.md
  pages/common/gatsby.md
  pages/common/git-annex.md
  pages/common/ngrok.md
  pages/common/pgcli.md
  pages/common/plesk.md
  pages/common/pre-commit.md
  pages/common/pyinfra.md
  pages/common/sails.md
  pages/common/svgr.md
  pages/common/terminalizer.md
  pages/linux/ddcutil.md
  pages/linux/xfreerdp.md
  pages/osx/herd-list.md
  pages/osx/herd.md
Labels: page edit, mass changes, review needed

#18180 env: updated Spanish translation
  pages.es/common/env.md
Labels: review needed, translation edit

#18189 magick: add percentage resize example
  pages/common/magick.md
Labels: page edit, review needed

#18245 git-commit-tree: refresh pages
  pages.id/common/git-commit-tree.md
  pages.ko/common/git-commit-tree.md
  pages.tr/common/git-commit-tree.md
  pages.uk/common/git-commit-tree.md
  pages.zh/common/git-commit-tree.md
Labels: translation edit

#18232 agg: add `--cols`,`--rows`, `--help` examples
  pages/common/agg.md
Labels: page edit, review needed

#18239 where: updated Spanish translation
  pages.es/windows/where.md
Labels: review needed, translation edit

#18233 bash: add Russian translation
  pages.ru/common/bash.md
Labels: review needed, new translation

#18251 gzip: add Russian translation
  pages.ru/common/gzip.md
Labels: review needed, new translation

#18247 netstat: add Russian translation
  pages.ru/common/netstat.md
Labels: review needed, new translation

#18248 ss: add Russian translation
  pages.ru/linux/ss.md
Labels: review needed, new translation

#18246 dig: add Russian translation
  pages.ru/common/dig.md
Labels: review needed, new translation

#18240 query: updated Spanish translation
  pages.es/windows/query.md
Labels: review needed, translation edit

#18161 poetry-add: add page
  pages/common/poetry-add.md
Labels: new command, review needed

#18238 Scoop: updated Spanish translation
  pages.es/windows/scoop.md
Labels: review needed, translation edit

#18260 playerctl: update page and add Dutch translation
  pages.nl/linux/playerctl.md
  pages/linux/playerctl.md
Labels: page edit, new translation

#18264 git-reset: refresh pages
  pages.es/common/git-reset.md
  pages.fr/common/git-reset.md
  pages.it/common/git-reset.md
  pages.ko/common/git-reset.md
  pages.pt_BR/common/git-reset.md
  pages.tr/common/git-reset.md
Labels: translation edit

#18140 split: add read from stdin example
  pages/common/split.md
Labels: page edit, review needed

#18270 brew-autoremove: refresh pages
  pages.id/common/brew-autoremove.md
  pages.ko/common/brew-autoremove.md
Labels: translation edit

#18269 brew-install: refresh pages
  pages.id/common/brew-install.md
  pages.ko/common/brew-install.md
Labels: translation edit

#18268 docker-rm: refresh pages
  pages.es/common/docker-rm.md
  pages.fr/common/docker-rm.md
  pages.ko/common/docker-rm.md
Labels: translation edit

#18265 pg_dump: refresh pages
  pages.es/common/pg_dump.md
  pages.ko/common/pg_dump.md
Labels: translation edit

#18263 git-restore: refresh pages
  pages.es/common/git-restore.md
  pages.ko/common/git-restore.md
  pages.tr/common/git-restore.md
Labels: translation edit

#18261 *: conform to the style guide
  pages/common/chainctl.md
  pages/common/django-admin.md
  pages/common/fastd.md
  pages/common/hg.md
  pages/common/npm-version.md
  pages/common/puppet.md
  pages/common/rails.md
Labels: page edit, mass changes, review needed

#18154 systemctl-add-requires: add page
  pages/linux/systemctl-add-requires.md
Labels: new command, review needed

#18153 systemctl-bind: add page
  pages/linux/systemctl-bind.md
Labels: new command, review needed
