Repository tldr-pages/tldr, pull requests merged in 2025-02, with the labels that each got.

#15510 ping: update page, add Chinese translation
  pages.zh/common/ping.md
  pages/common/ping.md
Labels: page edit, new translation

#15508 linux/*: add and update Indonesian translations
  pages.id/linux/a2disconf.md
  pages.id/linux/a2dismod.md
  pages.id/linux/a2dissite.md
  pages.id/linux/a2enconf.md
  pages.id/linux/a2enmod.md
  pages.id/linux/a2ensite.md
  pages.id/linux/a2query.md
Labels: review needed, new translation, translation edit

#15632 paxs: add page
  pages/linux/paxs.md
Labels: new command

#15661 pulumi-env: add page
  pages/common/pulumi-env.md
Labels: new command, review needed

#15663 lxc-ls: add page
  pages/linux/lxc-ls.md
Labels: new command

#15650 vagrant-box: add page
  pages/common/vagrant-box.md
Labels: new command, review needed

#15542 find: clarify description
  pages/common/find.md
Labels: page edit, review needed

#15501 docker: add Russian translation
  pages.ru/common/docker.md
Labels: review needed, new translation

#15533 readarray: add Spanish translation
  pages.es/common/readarray.md
Labels: new translation

#15548 libinput: add Spanish translation
  pages.es/linux/libinput.md
Labels: new translation

#15560 tune.exfat: add Spanish translation
  pages.es/linux/tune.exfat.md
Labels: new translation

#15561 dump.exfat: add Spanish translation
  pages.es/linux/dump.exfat.md
Labels: new translation

#15563 7z: add Arabic translation
  pages.ar/common/7z.md
Labels: review needed, new translation

#15565 tar: add Arabic translation
  pages.ar/common/tar.md
Labels: review needed, new translation

#15566 zip: add Arabic translation
  pages.ar/common/zip.md
Labels: review needed, new translation

#15574 trip: add page
  pages/common/trip.md
Labels: new command, review needed

#15577 lxc-create: add Spanish translation
  pages.es/linux/lxc-create.md
Labels: new translation

#15578 ufw: add Arabic translation
  pages.ar/linux/ufw.md
Labels: review needed, new translation

#15580 fincore: add Spanish translation
  pages.es/linux/fincore.md
Labels: new translation

#15581 dbx: add Spanish translation
  pages.es/common/dbx.md
Labels: new translation

#15584 go: add Arabic translation
  pages.ar/common/go.md
Labels: review needed, new translation

#15586 uv-add: add Spanish translation
  pages.es/common/uv-add.md
Labels: new translation

#15587 uv-tree: add Spanish translation
  pages.es/common/uv-tree.md
Labels: new translation

#15592 alacritty: update Spanish translation
  pages.es/common/alacritty.md
Labels: translation edit

#15599 insmod: add Spanish translation
  pages.es/linux/insmod.md
Labels: new translation

#15600 kmod: add Spanish translation
  pages.es/linux/kmod.md
Labels: new translation

#15601 modinfo: add Spanish translation
  pages.es/linux/modinfo.md
Labels: new translation

#15602 modprobe: add Spanish translation
  pages.es/linux/modprobe.md
Labels: new translation

#15603 rmmod: add Spanish translation
  pages.es/linux/rmmod.md
Labels: new translation

#15610 filebrowser: add page
  pages/common/filebrowser.md
Labels: new command, review needed

#15640 pgrep: add Arabic translation
  pages.ar/common/pgrep.md
Labels: review needed, new translation

#15380 rmlint: include some more advanced flags
  pages/common/rmlint.md
Labels: page edit, review needed

#15658 opkg: add examples
  pages/linux/opkg.md
Labels: page edit

#15648 stty: add examples
  pages/common/stty.md
Labels: page edit, review needed

#15685 pacman: add Arabic translation
  pages.ar/linux/pacman.md
Labels: review needed, new translation

#15572 cut: add chinese translation
  pages.zh/common/cut.md
  pages/common/cut.md
Labels: page edit, new translation

#15569 aider: add page
  pages/common/aider.md
Labels: new command, review needed

#15644 watch: merge common and linux, add examples
  pages/common/watch.md
  pages/linux/watch.md
Labels: page edit

#15631 es: add page
  pages/windows/es.md
Labels: new command, review needed

#15657 ifstatus: add page
  pages/linux/ifstatus.md
Labels: new command

#15684 img2sixel: add page
  pages/common/img2sixel.md
Labels: new command, review needed

#15691 dtrx: add page
  pages/common/dtrx.md
Labels: new command, review needed

#15702 snmpget: add page
  pages/common/snmpget.md
Labels: new command, review needed

#15701 snmpwalk: move to common, update page
  pages/common/snmpwalk.md
Labels: page edit

#15670 scoop, scoop-bucket: add Polish translation
  pages.pl/windows/scoop-bucket.md
  pages.pl/windows/scoop.md
Labels: new translation

#15674 rails: add `generate`, `db:migrate`, and `routes` examples
  pages/common/rails.md
Labels: page edit, review needed

#15672 eglinfo: add page
  pages/linux/eglinfo.md
Labels: new command

#15682 vagrant-plugin: add page
  pages/common/vagrant-plugin.md
Labels: new command, review needed

#15683 trap: simplify example and add example
  pages/linux/trap.md
Labels: page edit

#15643 bwrap: add page
  pages/linux/bwrap.md
Labels: new command

#15534 function: add Spanish translation
  pages.es/common/function.md
Labels: new translation

#15612 rails-new: add Spanish translation
  pages.es/common/rails-new.md
Labels: new translation

#15614 chisel: add Arabic translation
  pages.ar/common/chisel.md
Labels: review needed, new translation

#15613 rails-server: add Spanish translation
  pages.es/common/rails-server.md
Labels: new translation

#15615 tr: add Arabic translation
  pages.ar/common/tr.md
Labels: review needed, new translation

#15616 openssl-req: add Arabic translation
  pages.ar/common/openssl-req.md
Labels: review needed, new translation

#15617 openssl-x509: add Arabic translation
  pages.ar/common/openssl-x509.md
Labels: review needed, new translation

#15618 systemctl: add Arabic translation
  pages.ar/linux/systemctl.md
Labels: review needed, new translation

#15698 stty: add Spanish translation
  pages.es/common/stty.md
Labels: new translation

#15680 git-cliff: add Spanish translation
  pages.es/common/git-cliff.md
Labels: new translation

#15693 pages.ja/*: add Japanese translation pages
  pages.ja/common/arp.md
  pages.ja/common/awk.md
  pages.ja/common/column.md
  pages.ja/common/df.md
  pages.ja/common/find.md
  pages.ja/common/gpg.md
  pages.ja/common/gpg2.md
  pages.ja/common/grep.md
  pages.ja/common/kubectl.md
  pages.ja/common/netstat.md
  pages.ja/common/ping.md
  pages.ja/common/podman.md
  pages.ja/common/psql.md
  pages.ja/common/ssh-keygen.md
  pages.ja/common/ssh.md
  pages.ja/common/svn.md
  pages.ja/common/tee.md
  pages.ja/common/terraform.md
  pages.ja/common/traceroute.md
  pages.ja/common/wget.md
  pages.ja/linux/df.md
  pages.ja/linux/ip.md
  pages.ja/linux/lsb_release.md
  pages.ja/linux/sed.md
  pages.ja/linux/systemctl.md
  pages.ja/windows/diskpart.md
  pages.ja/windows/more.md
  pages.ja/windows/net.md
  pages.ja/windows/reg.md
  pages.ja/windows/robocopy.md
  pages.ja/windows/tracert.md
  pages.ja/windows/type.md
  pages.ja/windows/vol.md
  pages.ja/windows/wget.md
  pages.ja/windows/where.md
  pages.ja/windows/wsl.md
  pages.ja/windows/xcopy.md
Labels: mass changes, review needed, new translation

#15628 bloodhound-python: add Spanish translation
  pages.es/common/bloodhound-python.md
Labels: new translation

#15627 ip-maddress: add Spanish translation
  pages.es/linux/ip-maddress.md
Labels: new translation

#15625 htmlq: add page
  pages/common/htmlq.md
Labels: new command, review needed

#15623 byobu: add Spanish translation
  pages.es/common/byobu.md
Labels: new translation

#15620 rails-console: add Spanish translation
  pages.es/common/rails-console.md
Labels: new translation

#15707 filebrowser: add Spanish translation
  pages.es/common/filebrowser.md
Labels: new translation

#15706 aider: add Spanish translation
  pages.es/common/aider.md
Labels: new translation

#15426 pocount: add page & Spanish translation
  pages.es/common/pocount.md
  pages/common/pocount.md
Labels: new command, new translation

#15576 grep: add Traditional Chinese translation
  pages.zh_TW/common/grep.md
Labels: new translation

#14404 !: update Portuguese Brazilian translation
  pages.pt_BR/common/!.md
Labels: hacktoberfest-accepted, new translation, translation edit

#15637 bluebuild: add page
  pages/linux/bluebuild.md
Labels: new command

#15699 rmlint: add Spanish translation
  pages.es/common/rmlint.md
Labels: new translation

#15709 docker: improve example, docker-image: add a pointer towards docker-rmi
  pages/common/docker-image.md
  pages/common/docker.md
Labels: page edit, review needed

#15689 mariadb-install-db: add page
  pages/common/mariadb-install-db.md
Labels: new command, review needed

#15708 growpart: add page
  pages/linux/growpart.md
Labels: new command, review needed

#15710 ftp: add Arabic translation
  pages.ar/common/ftp.md
Labels: review needed, new translation

#15677 gpg: add Arabic translation
  pages.ar/common/gpg.md
Labels: review needed, new translation

#15669 rkhunter: add Arabic translation
  pages.ar/linux/rkhunter.md
Labels: review needed, new translation

#15662 dialog: add Arabic translation
  pages.ar/linux/dialog.md
Labels: review needed, new translation

#15695 kill: fix incorrect `-L` to `-l` option
  pages/linux/kill.md
Labels: page edit

#15687 bpython: add Spanish translation
  pages.es/common/bpython.md
Labels: new translation

#15686 fadvise: add Spanish translation
  pages.es/linux/fadvise.md
Labels: new translation

#15678 lxc-ls: add Spanish translation
  pages.es/linux/lxc-ls.md
Labels: new translation

#15675 paxs: add Spanish translation
  pages.es/linux/paxs.md
Labels: new translation

#15654 common/j*: add Chinese translation
  pages.zh/common/jadx.md
  pages.zh/common/javap.md
  pages.zh/common/jbang.md
  pages.zh/common/jc.md
  pages.zh/common/jcal.md
  pages.zh/common/jdeps.md
  pages.zh/common/jdupes.md
  pages.zh/common/jekyll.md
  pages.zh/common/jello.md
  pages.zh/common/jest.md
  pages.zh/common/jetifier.md
  pages.zh/common/jf.md
  pages.zh/common/jfrog.md
  pages.zh/common/jhipster.md
  pages.zh/common/jhsdb.md
  pages.zh/common/jigsaw.md
  pages.zh/common/jmeter.md
  pages.zh/common/jmtpfs.md
  pages.zh/common/jobs.md
  pages.zh/common/joe.md
  pages.zh/common/john.md
  pages.zh/common/join.md
  pages.zh/common/josm.md
  pages.zh/common/jp2a.md
  pages.zh/common/jpegoptim.md
  pages.zh/common/jpegtopnm.md
  pages.zh/common/jq.md
  pages.zh/common/jrnl.md
  pages.zh/common/json5.md
  pages.zh/common/jstack.md
  pages.zh/common/jtbl.md
  pages.zh/common/julia.md
  pages.zh/common/jupyter-lab.md
  pages.zh/common/jupyter.md
  pages.zh/common/jupyterlab.md
  pages.zh/common/jupytext.md
  pages.zh/common/just.1.md
  pages.zh/common/just.md
  pages.zh/common/jwt.md
Labels: mass changes, new translation

#15653 kubeadm: add Spanish translation
  pages.es/common/kubeadm.md
Labels: new translation

#15651 dialog: add Spanish translation
  pages.es/linux/dialog.md
Labels: new translation

#15641 gt: add Spanish translation
  pages.es/common/gt.md
Labels: new translation

#15660 common/y*: add Chinese translation
  pages.zh/common/ya.md
  pages.zh/common/yacas.md
  pages.zh/common/yacc.md
  pages.zh/common/yadm-alt.md
  pages.zh/common/yadm-bootstrap.md
  pages.zh/common/yadm-clone.md
  pages.zh/common/yadm-config.md
  pages.zh/common/yadm-decrypt.md
  pages.zh/common/yadm-encrypt.md
  pages.zh/common/yadm-enter.md
  pages.zh/common/yadm-git-crypt.md
  pages.zh/common/yadm-gitconfig.md
  pages.zh/common/yadm-init.md
  pages.zh/common/yadm-introspect.md
  pages.zh/common/yadm-list.md
  pages.zh/common/yadm-perms.md
  pages.zh/common/yadm-transcrypt.md
  pages.zh/common/yadm-upgrade.md
  pages.zh/common/yadm.md
  pages.zh/common/yapf.md
  pages.zh/common/yard.md
  pages.zh/common/yazi.md
  pages.zh/common/ybacklight.md
  pages.zh/common/ybmtopbm.md
  pages.zh/common/yes.md
  pages.zh/common/yesod.md
  pages.zh/common/ykinfo.md
  pages.zh/common/ykman-config.md
  pages.zh/common/ykman-fido.md
  pages.zh/common/ykman-oath.md
  pages.zh/common/ykman-openpgp.md
  pages.zh/common/ykman.md
  pages.zh/common/yolo.md
  pages.zh/common/you-get.md
  pages.zh/common/youtube-dl.md
  pages.zh/common/youtube-viewer.md
  pages.zh/common/yq.md
  pages.zh/common/yt-dlp.md
  pages.zh/common/yuvsplittoppm.md
  pages.zh/common/yuvtoppm.md
  pages.zh/common/yuy2topam.md
Labels: mass changes, new translation

#15692 opkg: add Spanish translation
  pages.es/linux/opkg.md
Labels: new translation

#15673 waypipe: add skip vulkan check example
  pages/linux/waypipe.md
Labels: page edit

#15638 tput: add examples
  pages/common/tput.md
Labels: page edit, review needed

#15639 less-than: add examples
  pages/common/less-than.md
Labels: page edit, review needed

#15659 pw-cat, pw-record: convert to alias; pw-cat: update more information link
  pages/linux/pw-cat.md
  pages/linux/pw-play.md
  pages/linux/pw-record.md
Labels: page edit

#15667 inxi: add examples
  pages/linux/inxi.md
Labels: page edit

#15712 picotool: add page
  pages/common/picotool.md
Labels: new command, review needed

#15671 pacman-sync: update page
  pages/linux/pacman-sync.md
Labels: page edit

#15597 print: add page
  pages/common/print.md
Labels: new command, review needed

#15715 style-guide: minor grammar correction
  contributing-guides/style-guide.md
Labels: documentation, minor change

#15721 pages.zh/common/*: update Chinese translation
  pages.zh/common/btop.md
  pages.zh/common/case.md
  pages.zh/common/compgen.md
  pages.zh/common/fc-list.md
  pages.zh/common/helix.md
  pages.zh/common/hexdump.md
  pages.zh/common/hostname.md
  pages.zh/common/htop.md
  pages.zh/common/java.md
  pages.zh/common/jmap.md
Labels: translation edit

#15720 alacritty: update Chinese translation
  pages.zh/common/alacritty.md
Labels: translation edit

#15719 adb: update Chinese translation
  pages.zh/common/adb.md
Labels: translation edit

#15718 pages.pl/freebsd/*: add Polish translations
  pages.pl/freebsd/base64.md
  pages.pl/freebsd/cal.md
  pages.pl/freebsd/chpass.md
  pages.pl/freebsd/df.md
  pages.pl/freebsd/look.md
  pages.pl/freebsd/pkg.md
  pages.pl/freebsd/sed.md
  pages.pl/freebsd/sockstat.md
Labels: new translation

#15713 apk: add Japanese translation
  pages.ja/linux/apk.md
Labels: review needed, new translation

#15711 chsh: remove linux distro dependant command
  pages.ko/linux/chsh.md
  pages.nl/linux/chsh.md
  pages/linux/chsh.md
Labels: page edit, translation edit

#15722 fswatch: fix flag
  pages/common/fswatch.md
Labels: page edit, review needed

#15714 nhentai: add page
  pages/common/nhentai.md
Labels: new command, review needed

#15582 fuzzel: add page
  pages/linux/fuzzel.md
Labels: new command

#15724 print: fix typo in line 13
  pages/common/print.md
Labels: page edit, review needed

#15727 gdb, coredumpctl: add prompt skip examples
  pages/common/gdb.md
  pages/linux/coredumpctl.md
Labels: page edit, review needed

#15726 ani-cli: add two examples
  pages/common/ani-cli.md
Labels: page edit, review needed

#15723 htmlq: add Spanish translation
  pages.es/common/htmlq.md
Labels: new translation

#15734 protoc: add encode/decode commands
  pages/common/protoc.md
Labels: page edit, review needed

#15737 udevadm: fix wrong reload command flag
  pages.ko/linux/udevadm.md
  pages/linux/udevadm.md
Labels: page edit, translation edit

#15732 git, git-*: add Polish translations
  pages.pl/common/git-abort.md
  pages.pl/common/git-add.md
  pages.pl/common/git-alias.md
  pages.pl/common/git-am.md
  pages.pl/common/git.md
Labels: new translation

#15736 pulumi-state: add page
  pages/common/pulumi-state.md
Labels: new command, review needed

#15642 kde-builder: update Spanish translation
  pages.es/linux/kde-builder.md
Labels: translation edit

#15389 scripts/set-alias-page.py: Improve sync translations
  scripts/_common.py
  scripts/set-alias-page.py
Labels: documentation, tooling

#15739 nhentai: fix issues
  pages/common/nhentai.md
Labels: page edit, review needed

#15731 lspci,lsblk: typos fix in Russian translation
  pages.ru/linux/lsblk.md
  pages.ru/linux/lspci.md
Labels: review needed, translation edit

#15738 procstat: add page
  pages/freebsd/procstat.md
Labels: new command, review needed

#15729 docker-build: add Traditional Chinese translation
  pages.zh_TW/common/docker-build.md
Labels: review needed, new translation

#15748 pages.nl/*: add/update translations, pacman-sync: rewrite
  pages.nl/common/$.md
  pages.nl/common/..md
  pages.nl/common/alacritty.md
  pages.nl/common/ani-cli.md
  pages.nl/common/read.md
  pages.nl/common/stty.md
  pages.nl/linux/kill.md
  pages.nl/linux/pacman-sync.md
  pages.nl/linux/pw-play.md
  pages.nl/linux/pw-record.md
  pages/linux/pacman-sync.md
Labels: page edit, new translation, translation edit

#15744 style-guide: do not translate example.com
  contributing-guides/style-guide.md
Labels: documentation

#15435 {: add Spanish translation
  pages.es/common/{.md
Labels: new translation

#15741 growpart: add Spanish translation
  pages.es/linux/growpart.md
Labels: new translation

#15745 fuzzel: add Spanish translation
  pages.es/linux/fuzzel.md
Labels: new translation

#15740 dtrx: add Spanish translation
  pages.es/common/dtrx.md
Labels: new translation

#15759 snmpwalk: move Korean translation to common
  pages.ko/common/snmpwalk.md
Labels: translation edit

#15767 vagrant-plugin: fix uninstall command
  pages/common/vagrant-plugin.md
Labels: page edit, review needed

#15761 ghostty: add page
  pages/common/ghostty.md
Labels: new command, review needed

#15769 chronyc: move from linux to common
  pages.ko/common/chronyc.md
  pages/common/chronyc.md
Labels: page edit, translation edit

#15758 mariadb-install-db: add Spanish translation
  pages.es/common/mariadb-install-db.md
Labels: new translation

#15757 bwrap: add Spanish translation
  pages.es/linux/bwrap.md
Labels: new translation

#15756 bluebuild: add Spanish translation
  pages.es/linux/bluebuild.md
Labels: new translation

#15755 eglinfo: add Spanish translation
  pages.es/linux/eglinfo.md
Labels: new translation

#15754 picotool: add Spanish translation
  pages.es/common/picotool.md
Labels: new translation

#15753 nhentai: add Spanish translation
  pages.es/common/nhentai.md
Labels: new translation

#15760 snmp{getnext, bulkget, set, test, status, table, df}: add page
  pages/common/snmpbulkget.md
  pages/common/snmpdf.md
  pages/common/snmpgetnext.md
  pages/common/snmpset.md
  pages/common/snmpstatus.md
  pages/common/snmptable.md
  pages/common/snmptest.md
Labels: new command, mass changes, review needed

#15749 style-guide: add disambiguation page documentation
  contributing-guides/style-guide.md
Labels: documentation

#15253 CLIENT-SPECIFICATION, style-guide: add longform/shortform specifications
  CLIENT-SPECIFICATION.md
  contributing-guides/style-guide.md
Labels: documentation, review needed

#15772 CLIENT-SPECIFICATION: rephrase requirement to implement option variants
  CLIENT-SPECIFICATION.md
Labels: documentation

#15766 vagrant-plugin: add Spanish translation
  pages.es/common/vagrant-plugin.md
Labels: new translation

#15765 chsh: add Spanish translation
  pages.es/linux/chsh.md
Labels: new translation

#15764 procstat: add Spanish translation
  pages.es/freebsd/procstat.md
Labels: new translation

#15746 print: add disambiguation page
  pages/common/print.md
  pages/common/print.zsh.md
  pages/linux/print.runmailcap.md
  pages/windows/print.win.md
Labels: page edit, new command, decision

#15742 pages.es/linux/a*: add Spanish translations
  pages.es/linux/aa-enforce.md
  pages.es/linux/abrt-action-analyze-backtrace.md
  pages.es/linux/abrt-action-analyze-c.md
  pages.es/linux/acpi.md
  pages.es/linux/add-apt-repository.md
  pages.es/linux/addpart.md
  pages.es/linux/adig.md
  pages.es/linux/ahost.md
  pages.es/linux/alien.md
  pages.es/linux/alpine.md
  pages.es/linux/amixer.md
  pages.es/linux/anbox.md
  pages.es/linux/apache2ctl.md
  pages.es/linux/aplay.md
  pages.es/linux/apx-pkgmanagers.md
  pages.es/linux/apx-stacks.md
  pages.es/linux/apx-subsystems.md
  pages.es/linux/apx.md
  pages.es/linux/arch-chroot.md
  pages.es/linux/archivemount.md
  pages.es/linux/archlinux-java.md
  pages.es/linux/arecord.md
  pages.es/linux/arithmetic.md
  pages.es/linux/ark.md
  pages.es/linux/arpaname.md
  pages.es/linux/arpspoof.md
  pages.es/linux/as.md
  pages.es/linux/asterisk.md
  pages.es/linux/atool.md
  pages.es/linux/atop.md
  pages.es/linux/aura.md
  pages.es/linux/auracle.md
  pages.es/linux/aurman.md
  pages.es/linux/aurvote.md
  pages.es/linux/ausyscall.md
  pages.es/linux/authconfig.md
  pages.es/linux/auto-cpufreq.md
  pages.es/linux/autopkgtest.md
  pages.es/linux/autorandr.md
  pages.es/linux/autorecon.md
  pages.es/linux/avahi-browse.md
  pages.es/linux/avahi-resolve.md
  pages.es/linux/avifenc.md
Labels: mass changes, new translation

#15775 pw-loopback: update more information
  pages.ko/linux/pw-loopback.md
  pages.pt_BR/linux/pw-loopback.md
  pages.tr/linux/pw-loopback.md
  pages/linux/pw-loopback.md
Labels: page edit, translation edit

#15797 style-guide: fix table of contents
  contributing-guides/style-guide.md
Labels: documentation
