Repository tldr-pages/tldr, pull requests merged in 2025-10, with the labels that each got.

#18309 agg: add --font-size example
  pages/common/agg.md
Labels: page edit, review needed

#18313 cargo-deb: add page
  pages/common/cargo-deb.md
Labels: new command, review needed

#18314 cargo-msrv: add page
  pages/common/cargo-msrv.md
Labels: new command, review needed

#18320 btop: add a more direct more info link
  pages/common/btop.md
Labels: page edit, review needed

#18331 pulumi-login: fix URL in command description
  pages.es/common/pulumi-login.md
  pages.ko/common/pulumi-login.md
  pages/common/pulumi-login.md
Labels: page edit, translation edit

#18333 pip-install: update page and add Dutch translation
  pages.nl/common/pip-install.md
  pages/common/pip-install.md
Labels: page edit, new translation

#18334 pip-uninstall: update link and add Dutch translation
  pages.nl/common/pip-uninstall.md
  pages/common/pip-uninstall.md
Labels: page edit, new translation

#18343 ping6: add a note
  pages/common/ping6.md
Labels: page edit, review needed

#18311 srun: add page
  pages/common/srun.md
Labels: new command, review needed

#18321 hg: update page
  pages/common/hg.md
Labels: page edit, review needed

#18355 mysql: add short/long options
  pages.es/common/mysql.md
  pages.ja/common/mysql.md
  pages.ko/common/mysql.md
  pages.pl/common/mysql.md
  pages.zh/common/mysql.md
  pages.zh_TW/common/mysql.md
Labels: translation edit

#18351 pip: update more info link
  pages/common/pip.md
Labels: page edit, review needed

#18344 bun: change the more info link to be more precise
  pages/common/bun.md
Labels: page edit, review needed

#18354 docker-pull: add short/long options
  pages.fr/common/docker-pull.md
  pages.ko/common/docker-pull.md
  pages.pt_BR/common/docker-pull.md
Labels: translation edit

#18328 flex: add Spanish translation
  pages.es/linux/flex.md
Labels: review needed, new translation

#18327 fgrep: add Spanish translation
  pages.es/common/fgrep.md
Labels: review needed, new translation

#18323 dirname: add Spanish translation
  pages.es/common/dirname.md
Labels: review needed, new translation

#18300 gcrane: update page
  pages/common/gcrane.md
Labels: page edit, review needed

#18318 htop: add readonly example
  pages/common/htop.md
Labels: page edit, review needed

#18356 pip-cache : add page
  pages/common/pip-cache.md
Labels: new command, review needed

#18379 duc, pip: update Dutch more info link
  pages.nl/common/duc.md
  pages.nl/common/pip.md
Labels: translation edit

#18380 pages.nl/common/*: add missing Dutch alias pages
  pages.nl/common/brew-remove.md
  pages.nl/common/brew-rm.md
  pages.nl/common/gh-agent.md
  pages.nl/common/npx.md
  pages.nl/common/pulumi-stack-hist.md
Labels: new translation

#18369 nix-collect-garbage: remove `sudo`
  pages.de/common/nix-collect-garbage.md
  pages.es/common/nix-collect-garbage.md
  pages.ko/common/nix-collect-garbage.md
  pages/common/nix-collect-garbage.md
Labels: page edit, translation edit

#18382 nixos-*: add italian translation
  pages.it/linux/nixos-container.md
  pages.it/linux/nixos-option.md
  pages.it/linux/nixos-rebuild.md
Labels: new translation

#18377 cargo-verify-project: add deprecation notice
  pages/common/cargo-verify-project.md
Labels: page edit, review needed

#18360 style-guide: add subcommand instructions
  contributing-guides/style-guide.md
Labels: documentation

#18400 wget, curl: add see also section
  pages/common/curl.md
  pages/common/wget.md
Labels: page edit, review needed

#18403 pages.*/*: add option placeholders to alias pages
  pages.es/common/file-rename.md
  pages.es/common/perl-rename.md
  pages.es/common/prename.md
  pages.nl/common/file-rename.md
  pages.nl/common/perl-rename.md
  pages.nl/common/prename.md
  pages/common/file-rename.md
  pages/common/perl-rename.md
  pages/common/prename.md
  pages/linux/rename.md
Labels: page edit, translation edit

#18366 btm, top, htop, btop, glances, atop: refresh pages
  pages/common/btm.md
  pages/common/btop.md
  pages/common/glances.md
  pages/common/htop.md
  pages/linux/atop.md
  pages/linux/top.md
Labels: page edit, mass changes, review needed

#18410 wcurl: add Polish translation
  pages.pl/common/wcurl.md
Labels: new translation

#18408 alpine: fix examples
  pages.de/linux/alpine.md
  pages.es/linux/alpine.md
  pages.ko/linux/alpine.md
  pages.pt_BR/linux/alpine.md
  pages.zh/linux/alpine.md
Labels: translation edit

#18424 radare2: replace broken links
  pages.es/common/radare2.md
  pages.ko/common/radare2.md
  pages.nl/common/radare2.md
  pages/common/radare2.md
Labels: page edit, translation edit

#18420 brave: replace broken link
  pages.es/common/brave.md
  pages.id/common/brave.md
  pages.ko/common/brave.md
  pages.nl/common/brave.md
  pages.pl/common/brave.md
  pages/common/brave.md
Labels: page edit, translation edit

#18418 asciinema: replace broken link
  pages.es/common/asciinema.md
  pages.fr/common/asciinema.md
  pages.id/common/asciinema.md
  pages.it/common/asciinema.md
  pages.ko/common/asciinema.md
  pages.nl/common/asciinema.md
  pages.zh/common/asciinema.md
  pages/common/asciinema.md
Labels: page edit, translation edit

#18365 systemctl-halt: add page
  pages/linux/systemctl-halt.md
Labels: new command, review needed

#18427 dstat: replace broken links
  pages.ko/linux/dstat.md
  pages/linux/dstat.md
Labels: page edit, translation edit

#18419 atuin: replace broken link
  pages.fa/common/atuin.md
  pages.fr/common/atuin.md
  pages.ko/common/atuin.md
  pages.zh/common/atuin.md
  pages/common/atuin.md
Labels: page edit, translation edit

#18398 nvm, py, whoami, wsl, wsl-open: add Bengali translation
  pages.bn/windows/nvm.md
  pages.bn/windows/py.md
  pages.bn/windows/whoami.md
  pages.bn/windows/wsl-open.md
  pages.bn/windows/wsl.md
Labels: review needed, new translation

#18347 systemctl-daemon-reload: add page
  pages/linux/systemctl-daemon-reload.md
Labels: new command, review needed

#18404 MAINTAINERS: add @Sadeeed as collaborator
  MAINTAINERS.md
Labels: community

#18388 pip-lock, pip-search: add page
  pages/common/pip-lock.md
  pages/common/pip-search.md
Labels: new command, review needed

#18371 cargo-binstall: add page
  pages/common/cargo-binstall.md
Labels: new command, review needed

#18375 dos: add platform, dos/cd: add page
  CONTRIBUTING.md
  README.md
  pages/dos/cd.md
Labels: documentation, architecture, new command

#18431 vela, whatweb: replace broken links
  pages.es/common/whatweb.md
  pages.ko/common/vela.md
  pages/common/vela.md
  pages/common/whatweb.md
Labels: page edit, translation edit

#18401 gh-variable: add page
  pages/common/gh-variable.md
Labels: new command, review needed

#18491 style-guide: refine argument order
  contributing-guides/style-guide.md
Labels: documentation

#18451 paccapability: add page
  pages/linux/paccapability.md
Labels: new command, review needed

#18486 pg_archivecleanup: add page
  pages/common/pg_archivecleanup.md
Labels: new command, review needed

#18485 pg_walsummary: add page
  pages/common/pg_walsummary.md
Labels: new command, review needed

#18481 pg_test_timing: add page
  pages/common/pg_test_timing.md
Labels: new command, review needed

#18490 git-fast-export: add page
  pages/common/git-fast-export.md
Labels: new command, review needed

#18521 st-flash: adjust formatting
  pages/common/st-flash.md
Labels: page edit, review needed

#18514 curl: improve wording
  pages/common/curl.md
Labels: page edit, review needed

#18370 vacuumdb: add page
  pages/common/vacuumdb.md
Labels: new command, review needed

#18387 pip-{index, inspect, wheel}: add page
  pages/common/pip-index.md
  pages/common/pip-inspect.md
  pages/common/pip-wheel.md
Labels: new command, review needed

#18415 kubectl-{api-versions, version}: add page
  pages/common/kubectl-api-versions.md
  pages/common/kubectl-version.md
Labels: new command, review needed

#18499 uname: add Russian translation
  pages.ru/common/uname.md
Labels: review needed, new translation

#18503 ssh: add Russian translation
  pages.ru/common/ssh.md
Labels: review needed, new translation

#18510 paclog: add page
  pages/linux/paclog.md
Labels: new command, review needed

#18508 st-flash: add Czech translation
  pages.cs/common/st-flash.md
Labels: review needed, new translation

#18525 git-fast-export: update page
  pages/common/git-fast-export.md
Labels: page edit, review needed

#18523 PULL_REQUEST_TEMPLATE: Update template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, review needed

#18476 systemctl-list-unit-files: add page
  pages/linux/systemctl-list-unit-files.md
Labels: new command, review needed

#18540 crond: add Russian translation
  pages.ru/linux/crond.md
Labels: review needed, new translation

#18526 git-sparse-checkout: add page
  pages/common/git-sparse-checkout.md
Labels: new command, review needed

#18519 poetry-install: add page
  pages/common/poetry-install.md
Labels: new command, review needed

#18542 mvn-site: add page
  pages/common/mvn-site.md
Labels: new command, review needed

#18534 mhwd: add page
  pages/linux/mhwd.md
Labels: new command, review needed

#18532 systemctl-preset: add page
  pages/linux/systemctl-preset.md
Labels: new command, review needed

#18396 ip-monitor, rtmon: add page
  pages/linux/ip-monitor.md
  pages/linux/rtmon.md
Labels: new command, review needed

#18518 tesseract: update page
  pages/common/tesseract.md
Labels: page edit, review needed

#18341 grub-mkrescue: add page
  pages/linux/grub-mkrescue.md
Labels: new command, review needed

#18441 npm-dist-tag: add page
  pages/common/npm-dist-tag.md
Labels: new command, review needed

#18536 free: add Russian translation
  pages.ru/linux/free.md
Labels: review needed, new translation

#18448 semodule: add page
  pages/linux/semodule.md
Labels: new command, review needed

#18480 reindexdb: add page
  pages/common/reindexdb.md
Labels: new command, review needed

#18517 npm-sbom: add page
  pages/common/npm-sbom.md
Labels: new command, review needed

#18456 sealert: add page
  pages/linux/sealert.md
Labels: new command, review needed

#18457 newrole: add page
  pages/linux/newrole.md
Labels: new command, review needed

#18459 run_init: add page
  pages/linux/run_init.md
Labels: new command, review needed

#18460 semanage-interface: add page
  pages/linux/semanage-interface.md
Labels: new command, review needed

#18473 setfiles: add page
  pages/linux/setfiles.md
Labels: new command, review needed

#18497 kubectl-top: add page
  pages/common/kubectl-top.md
Labels: new command, review needed

#18546 brew-uninstall: add Dutch translation
  pages.nl/common/brew-uninstall.md
Labels: new translation

#18483 pg_test_fsync: add page
  pages/common/pg_test_fsync.md
Labels: new command, review needed

#18484 ibmcloud-{api,config,logout,regions,target}: add pages
  pages/common/ibmcloud-api.md
  pages/common/ibmcloud-config.md
  pages/common/ibmcloud-logout.md
  pages/common/ibmcloud-regions.md
  pages/common/ibmcloud-target.md
Labels: new command, review needed

#18544 tail: add Portuguese translation
  pages.pt_BR/common/tail.md
Labels: new translation

#18391 kubectl-port-forward: add page
  pages/common/kubectl-port-forward.md
Labels: new command, review needed

#18551 systemctl-get-default: add page
  pages/linux/systemctl-get-default.md
Labels: new command, review needed
