Repository tldr-pages/tldr, pull requests merged in 2025-07, with the labels that each got.

#17054 lsdev: add page
  pages/linux/lsdev.md
Labels: new command, review needed

#17033 fastapi: add page and Chinese and Korean translation
  pages.ko/common/fastapi.md
  pages.zh/common/fastapi.md
  pages/common/fastapi.md
Labels: new command, new translation

#17050 stow: add Dutch translation
  pages.nl/common/stow.md
Labels: new translation

#17073 style-guide: link to IANA
  contributing-guides/style-guide.md
Labels: documentation

#17085 tzconfig: add page
  pages/common/tzconfig.md
Labels: new command, review needed

#17083 tcpdump: add mnemonics and sudo
  pages/common/tcpdump.md
Labels: page edit, review needed

#17079 dex: fix typo
  pages/linux/dex.md
Labels: page edit, review needed

#17087 style-guide: give instructions on sudo usage
  contributing-guides/style-guide.md
Labels: documentation

#17092 fwupdmgr: add update history example
  pages/linux/fwupdmgr.md
Labels: page edit, review needed

#17090 nano: update more information links
  pages.es/common/nano.md
  pages.fr/common/nano.md
  pages.ko/common/nano.md
  pages.pt_BR/common/nano.md
  pages.zh/common/nano.md
Labels: translation edit

#17089 gobuster: update outdated translations
  pages.de/common/gobuster.md
  pages.ko/common/gobuster.md
Labels: translation edit

#17100 zellij: add option placeholders
  pages/common/zellij.md
Labels: page edit, review needed

#17105 gron: add page
  pages/common/gron.md
Labels: new command, review needed

#17067 gdm-binary: add page
  pages/common/gdm-binary.md
Labels: new command, review needed

#17060 pkcs11-tool: add page
  pages/common/pkcs11-tool.md
Labels: new command, review needed

#17086 steamcmd: add example on how to delete credential cache
  pages/common/steamcmd.md
Labels: page edit, review needed

#17104 jj, jj-status, jj-bookmark: add option placeholder for aliases
  pages/common/jj-bookmark.md
  pages/common/jj-status.md
  pages/common/jj.md
Labels: page edit, review needed

#17099 dnf-{group, config-manager}: edit more info link and add option placeholders
  pages/linux/dnf-config-manager.md
  pages/linux/dnf-group.md
Labels: page edit, review needed

#17068 gdmsetup: add page
  pages/common/gdmsetup.md
Labels: new command, review needed

#17038 nix-channel: add page
  pages/common/nix-channel.md
Labels: new command, review needed

#17009 spf: add page and Chinese translation
  pages.zh/common/spf.md
  pages.zh_TW/common/spf.md
  pages/common/spf.md
Labels: new command, new translation

#17117 xlsclients: add missing placeholders
  pages/common/xlsclients.md
Labels: page edit, review needed

#17055 jj-{abandon, revert, show, simplify-parents}: add pages
  pages/common/jj-abandon.md
  pages/common/jj-revert.md
  pages/common/jj-show.md
  pages/common/jj-simplify-parents.md
Labels: new command, review needed

#17115 expac: add missing hyphens
  pages/linux/expac.md
Labels: page edit, review needed

#17126 brightnessctl: update outdated translations
  pages.es/linux/brightnessctl.md
  pages.ko/linux/brightnessctl.md
  pages.ml/linux/brightnessctl.md
  pages.tr/linux/brightnessctl.md
Labels: translation edit

#17123 elasticsearch-keystore: add page
  pages/common/elasticsearch-keystore.md
Labels: new command, review needed

#17096 dnf-install: add page
  pages/linux/dnf-install.md
Labels: new command, review needed

#17131 pgcli: add page
  pages/common/pgcli.md
Labels: new command, review needed

#17136 nagios, nagios2, nagios3, nagios4: add pages
  pages/common/nagios.md
  pages/common/nagios2.md
  pages/common/nagios3.md
  pages/common/nagios4.md
Labels: new command, review needed

#17142 scrcpy: update examples
  pages/common/scrcpy.md
Labels: page edit, review needed

#17097 dnf-module: add page
  pages/linux/dnf-module.md
Labels: new command, review needed

#17081 run-mailcap: conform with style guide
  pages/linux/run-mailcap.md
Labels: page edit, review needed

#17148 subl: update outdated translations
  pages.id/common/subl.md
  pages.ko/common/subl.md
Labels: translation edit

#17147 add-apt-repository: update outdated translations
  pages.ca/linux/add-apt-repository.md
  pages.de/linux/add-apt-repository.md
  pages.es/linux/add-apt-repository.md
  pages.id/linux/add-apt-repository.md
  pages.it/linux/add-apt-repository.md
  pages.ko/linux/add-apt-repository.md
  pages.pt_BR/linux/add-apt-repository.md
  pages.zh/linux/add-apt-repository.md
Labels: translation edit

#16968 dnswalk: add page
  pages/common/dnswalk.md
Labels: new command, review needed

#17163 CONTRIBUTING: reword name collission instructions
  CONTRIBUTING.md
Labels: documentation

#17144 filen: add page
  pages/common/filen.md
Labels: new command, review needed

#17162 gdm: add Dutch translation
  pages.nl/common/gdm.md
Labels: new translation

#17061 sccache: add page
  pages/common/sccache.md
Labels: new command, review needed

#17143 jj-git-*: add pages
  pages/common/jj-git-clone.md
  pages/common/jj-git-fetch.md
  pages/common/jj-git-init.md
  pages/common/jj-git-push.md
  pages/common/jj-git-remote.md
Labels: new command, review needed

#17164 dnf changelog: add page
  pages/linux/dnf-changelog.md
Labels: new command, review needed

#17175 ocrmypdf: replace semi-duplicate with optimization
  pages/common/ocrmypdf.md
Labels: page edit, review needed

#17161 dnf builddep: add page
  pages/linux/dnf-builddep.md
Labels: new command, review needed

#17158 dnf-config-manager: add remarks over `dnf`
  pages/linux/dnf-config-manager.md
Labels: page edit, review needed

#17152 i2c-tools: add page
  pages/linux/i2cdetect.md
  pages/linux/i2cdump.md
  pages/linux/i2cget.md
  pages/linux/i2cset.md
Labels: new command, review needed

#17174 mailsy: add page
  pages/common/mailsy.md
Labels: new command, review needed

#17133 bugreportz: update Polish translation
  pages.pl/android/bugreportz.md
Labels: translation edit

#17149 dnf-config-manager: update Spanish translation
  pages.es/linux/dnf-config-manager.md
Labels: translation edit

#17008 cp, mv, rm, rmdir, mkdir: add Czech translation
  pages.cs/common/cp.md
  pages.cs/common/mkdir.md
  pages.cs/common/mv.md
  pages.cs/common/rm.md
  pages.cs/common/rmdir.md
Labels: review needed, new translation

#17179 ls: update Czech translation
  pages.cs/common/ls.md
Labels: review needed, translation edit

#17178 rsql: add page
  pages/common/rsql.md
Labels: new command, review needed

#17165 jj-absorb: clarify move semantics
  pages/common/jj-absorb.md
Labels: page edit, review needed

#17134 !: update Polish translation
  pages.pl/common/!.md
Labels: review needed, translation edit

#17130 dtc: add more examples
  pages/common/dtc.md
Labels: page edit, review needed

#17137 mpic++, mpiexec, mpirun: add pages; mpicc: move to `common/`
  pages/common/mpic++.md
  pages/common/mpicc.md
  pages/common/mpiexec.md
  pages/common/mpirun.md
Labels: page edit, new command, review needed

#17141 ip-route-{list,show}: update and add Arabic translation
  pages.ar/linux/ip-route-list.md
  pages.ar/linux/ip-route-show.md
Labels: review needed, new translation, translation edit

#17184 minicom: add more examples
  pages/linux/minicom.md
Labels: page edit, review needed

#17190 ollama: add Dutch translation
  pages.nl/common/ollama.md
  pages/common/ollama.md
Labels: page edit, new translation

#17193 helm-install: add option placeholders
  pages/common/helm-install.md
Labels: page edit, review needed

#17166 docker: update Chinese translation
  pages.zh_TW/common/docker.md
Labels: translation edit

#17204 btop: add option placeholders
  pages.es/common/btop.md
  pages.fr/common/btop.md
  pages.ko/common/btop.md
  pages.zh/common/btop.md
  pages/common/btop.md
Labels: page edit, translation edit

#17195 flutter: add an example
  pages/common/flutter.md
Labels: page edit, review needed

#17209 ncspot: add page
  pages/common/ncspot.md
Labels: new command, review needed

#17191 yt-dlp: add Arabic translation, apt: refesh Arabic translation
  pages.ar/common/yt-dlp.md
  pages.ar/linux/apt.md
Labels: review needed, new translation, translation edit

#17212 zed: add page
  pages/common/zed.md
  pages/common/zeditor.md
Labels: new command, review needed

#17216 MAINTAINERS: remove @marchersimon as collaborator
  MAINTAINERS.md
Labels: community

#17222 deno: update more information links
  pages.de/common/deno.md
  pages.es/common/deno.md
  pages.fa/common/deno.md
  pages.fr/common/deno.md
  pages.id/common/deno.md
  pages.ko/common/deno.md
  pages.zh/common/deno.md
Labels: translation edit

#17200 pulumi-plugin: add page
  pages/common/pulumi-plugin.md
Labels: new command, review needed

#17202 audit2why: add page
  pages/common/audit2why.md
Labels: new command, review needed

#17223 spotify_player: add page
  pages/common/spotify_player.md
Labels: new command, review needed

#17236 ko/gpg-tui: correct the description
  pages.ko/common/gpg-tui.md
Labels: minor change, translation edit

#17210 *: fix curly brace syntax, nested placeholders and mismatched brackets
  pages/common/aws-eks.md
  pages/common/coproc.md
  pages/common/d8.md
  pages/common/dropdb.md
  pages/common/for.md
  pages/common/highlight.md
  pages/common/hyperfine.md
  pages/common/jello.md
  pages/common/kubetail.md
  pages/common/linode-cli-linodes.md
  pages/common/mamba-repoquery.md
  pages/common/phpcbf.md
  pages/common/quarto.md
  pages/common/swig.md
  pages/common/trdsql.md
  pages/common/vagrant-validate.md
  pages/linux/keyd.md
  pages/linux/pstoedit.md
  pages/linux/rpicam-still.md
  pages/linux/sfdisk.md
  pages/linux/unzipsfx.md
Labels: page edit, mass changes, review needed

#17188 mpicxx: add page
  pages/common/mpicxx.md
Labels: new command, review needed

#17218 chainctl: add page
  pages/common/chainctl.md
Labels: new command, review needed

#17243 tldr: add Dutch translation
  pages.nl/common/tldr.md
Labels: new translation

#17246 docker: add long and short options to commands in translations
  pages.de/common/docker.md
  pages.es/common/docker.md
  pages.fr/common/docker.md
  pages.id/common/docker.md
  pages.it/common/docker.md
  pages.ja/common/docker.md
  pages.ko/common/docker.md
  pages.pt_BR/common/docker.md
  pages.ru/common/docker.md
  pages.tr/common/docker.md
  pages.zh/common/docker.md
Labels: mass changes, translation edit

#17150 hwinfo: refresh page
  pages/linux/hwinfo.md
Labels: page edit, review needed

#17186 openocd: add page
  pages/common/openocd.md
Labels: new command, review needed

#17256 style-guide: instruct to avoid nested placeholders
  contributing-guides/style-guide.md
Labels: documentation

#17255 in-toto-run, pueue-add, x8, ippeveps, pasuspender, screenkey: fix nested placeholders
  pages/common/in-toto-run.md
  pages/common/ippeveps.md
  pages/common/pueue-add.md
  pages/common/x8.md
  pages/linux/pasuspender.md
  pages/linux/screenkey.md
Labels: page edit, mass changes, review needed

#17262 links: fix missing angle brackets
  pages/linux/links.md
Labels: page edit, review needed

#17251 which: add long and short options to commands in translations
  pages.fr/common/which.md
  pages.ko/common/which.md
  pages.pt_BR/common/which.md
  pages.ru/common/which.md
  pages.zh/common/which.md
Labels: translation edit

#17250 fzf: add long and short options to commands in translations
  pages.ar/common/fzf.md
  pages.es/common/fzf.md
  pages.fr/common/fzf.md
  pages.ko/common/fzf.md
  pages.tr/common/fzf.md
  pages.zh/common/fzf.md
Labels: translation edit

#17254 rabbitmqctl-{cluster,users,vhosts}: add page
  pages/common/rabbitmqctl-cluster.md
  pages/common/rabbitmqctl-users.md
  pages/common/rabbitmqctl-vhosts.md
Labels: new command, review needed

#17252 factorio, terraria, counter-strike-2, minecraft: capitalize title
  pages/common/minecraft.md
  pages/linux/counter-strike-2.md
  pages/linux/factorio.md
  pages/linux/terraria.md
Labels: page edit, review needed

#17253 rabbitmqctl: add page
  pages/common/rabbitmqctl.md
Labels: new command, review needed

#17273 hexyl, od, xxd, hexdump: add see also information
  pages/common/hexdump.md
  pages/common/hexyl.md
  pages/common/od.md
  pages/common/xxd.md
  pages/linux/hexdump.md
Labels: page edit, review needed, minor change

#17267 zypper: add aliases
  pages/linux/zypper.md
Labels: page edit, review needed

#17264 trace-cmd-{list, record, report}: add page, tracecmd: refresh page
  pages/linux/trace-cmd-list.md
  pages/linux/trace-cmd-record.md
  pages/linux/trace-cmd-report.md
  pages/linux/trace-cmd.md
Labels: page edit, new command, review needed

#17268 btrfs: add aliases
  pages/linux/btrfs-balance.md
  pages/linux/btrfs-check.md
  pages/linux/btrfs-device.md
  pages/linux/btrfs-filesystem.md
  pages/linux/btrfs-inspect-internal.md
  pages/linux/btrfs-property.md
  pages/linux/btrfs-rescue.md
  pages/linux/btrfs-restore.md
  pages/linux/btrfs-scrub.md
  pages/linux/btrfs-subvolume.md
  pages/linux/btrfs-version.md
  pages/linux/btrfs.md
Labels: page edit, mass changes, review needed

#17258 nmcli*: refresh pages
  pages/linux/nmcli-agent.md
  pages/linux/nmcli-connection.md
  pages/linux/nmcli-device.md
  pages/linux/nmcli-general.md
  pages/linux/nmcli-monitor.md
  pages/linux/nmcli-networking.md
  pages/linux/nmcli-radio.md
  pages/linux/nmcli.md
Labels: page edit, mass changes, review needed

#17275 source: fix typo in Dutch translation
  pages.nl/common/source.md
Labels: minor change, translation edit

#17272 counter-strike-2: capitalize Dutch title
  pages.nl/linux/counter-strike-2.md
Labels: translation edit

#17274 kerl: add page
  pages/common/kerl.md
Labels: new command, review needed

#17154 kdash: add page
  pages.ja/common/kdash.md
  pages/common/kdash.md
Labels: new command, review needed, new translation

#17281 objdump: add -t | --syms example
  pages/common/objdump.md
Labels: page edit, review needed

#17285 cargo-uninstall: fix command
  pages.ko/common/cargo-uninstall.md
  pages.zh/common/cargo-uninstall.md
  pages/common/cargo-uninstall.md
Labels: page edit, translation edit

#17287 gst-inspect-1.0: fix typo
  pages/common/gst-inspect-1.0.md
Labels: page edit, review needed

#17284 function: add short example
  pages/common/function.md
Labels: page edit, review needed

#17279 docker-login: add long & short options to commands in translations
  pages.de/common/docker-login.md
  pages.fr/common/docker-login.md
  pages.ko/common/docker-login.md
  pages.pt_BR/common/docker-login.md
Labels: translation edit

#17278 node: add long and short options to commands in translations
  pages.ar/common/node.md
  pages.de/common/node.md
  pages.fa/common/node.md
  pages.fr/common/node.md
  pages.id/common/node.md
  pages.it/common/node.md
  pages.ja/common/node.md
  pages.ko/common/node.md
  pages.pt_BR/common/node.md
  pages.tr/common/node.md
  pages.zh/common/node.md
Labels: mass changes, translation edit

#17294 qm-disk-import: fix typo
  pages/linux/qm-disk-import.md
Labels: page edit, review needed

#17295 fish: refresh page
  pages/common/fish.md
Labels: page edit, review needed

#17307 cargo-rustc: fix typo
  pages/common/cargo-rustc.md
Labels: page edit, review needed

#17304 sc-im: rename to scim
  pages/common/scim.md
Labels: page edit, review needed

#17301 mid3v2: fix typo
  pages/common/mid3v2.md
Labels: page edit, review needed

#17302 mke2fs: fix examples
  pages/linux/mke2fs.md
Labels: page edit, review needed

#17322 k9s: add short options
  pages/common/k9s.md
Labels: page edit, review needed

#17320 ippevepcl: delete page in favor of ippeveps
  pages/common/ippevepcl.md
Labels: page edit, review needed

#17315 pamditherbw: fix typo
  pages/common/pamditherbw.md
Labels: page edit, review needed

#17314 immich-cli: rename to immich
  pages/common/immich.md
Labels: page edit, review needed

#17297 docker-logs: add long and short options to commands in translations
  pages.de/common/docker-logs.md
  pages.fr/common/docker-logs.md
  pages.it/common/docker-logs.md
  pages.ko/common/docker-logs.md
  pages.pt_BR/common/docker-logs.md
  pages.tr/common/docker-logs.md
Labels: translation edit

#17329 *: unify apostrophes
  pages/common/cargo-bench.md
  pages/common/cargo-fix.md
  pages/common/django-admin.md
  pages/common/docker-commit.md
  pages/common/doctl-databases-sql-mode.md
  pages/common/git-mktree.md
  pages/common/git-replace.md
  pages/common/home-manager.md
  pages/common/ipcs.md
  pages/common/npm-audit.md
  pages/common/secretsdump.py.md
  pages/common/zgrep.md
  pages/linux/wireplumber.md
Labels: page edit, mass changes, review needed

#17331 brew-{autoremove, install, upgrade}: add short options
  pages/common/brew-autoremove.md
  pages/common/brew-install.md
  pages/common/brew-upgrade.md
Labels: page edit, review needed

#17333 aplay, wol, unlzma: remove `=` and add short options
  pages/common/unlzma.md
  pages/linux/aplay.md
  pages/linux/wol.md
Labels: page edit, review needed

#17292 dmypy: add page
  pages/common/dmypy.md
Labels: new command, review needed

#17334 speedtest: remove `=` and add short options
  pages/common/speedtest.md
Labels: page edit, review needed

#17228 impacket-psexec: update Spanish translation
  pages.es/common/impacket-psexec.md
Labels: new translation

#17239 zeditor: add Spanish translation
  pages.es/common/zeditor.md
Labels: new translation

#17241 mpicxx: add Spanish translation
  pages.es/common/mpicxx.md
Labels: new translation

#17293 Terraria: update Spanish translation
  pages.es/linux/terraria.md
Labels: translation edit

#17335 cli53: add proper option placeholders and fix example link
  pages/common/cli53.md
Labels: page edit, review needed

#17196 zip, unzip, 7z, gzip, tar: add Czech translation
  pages.cs/common/7z.md
  pages.cs/common/gzip.md
  pages.cs/common/tar.md
  pages.cs/common/unzip.md
  pages.cs/common/zip.md
Labels: review needed, new translation

#17321 ip, nmcli, nmcli-device, nmcli-general, nmcli-monitor: add Czech translation
  pages.cs/linux/ip.md
  pages.cs/linux/nmcli-device.md
  pages.cs/linux/nmcli-general.md
  pages.cs/linux/nmcli-monitor.md
  pages.cs/linux/nmcli.md
Labels: review needed, new translation

#17339 tar: remove `=` and add short options
  pages/common/tar.md
Labels: page edit, review needed

#17341 docker-rmi: add long and short options to translations
  pages.de/common/docker-rmi.md
  pages.fr/common/docker-rmi.md
  pages.ko/common/docker-rmi.md
  pages.pt_BR/common/docker-rmi.md
  pages.tr/common/docker-rmi.md
Labels: translation edit

#17310 pacman-key: add short options
  pages/linux/pacman-key.md
Labels: page edit, review needed

#17354 CONTRIBUTING: update name collision link
  CONTRIBUTING.md
Labels: documentation

#17368 pct: add aliases
  pages/linux/pct.md
Labels: page edit, review needed

#17367 qm*: add aliases
  pages/linux/qm-cleanup.md
  pages/linux/qm-cloudinit-dump.md
  pages/linux/qm-config.md
  pages/linux/qm-create.md
  pages/linux/qm-delsnapshot.md
  pages/linux/qm-destroy.md
  pages/linux/qm-disk-import.md
  pages/linux/qm-disk-move.md
  pages/linux/qm-disk-resize.md
  pages/linux/qm-guest-cmd.md
  pages/linux/qm-guest-exec-status.md
  pages/linux/qm-guest-exec.md
  pages/linux/qm-guest-passwd.md
  pages/linux/qm-help.md
  pages/linux/qm-listsnapshot.md
  pages/linux/qm-migrate.md
  pages/linux/qm-monitor.md
  pages/linux/qm-mtunnel.md
  pages/linux/qm-nbdstop.md
  pages/linux/qm-pending.md
  pages/linux/qm-reboot.md
  pages/linux/qm-resume.md
  pages/linux/qm-rollback.md
  pages/linux/qm-sendkey.md
  pages/linux/qm-showcmd.md
  pages/linux/qm-shutdown.md
  pages/linux/qm-snapshot.md
  pages/linux/qm-status.md
  pages/linux/qm-suspend.md
  pages/linux/qm-template.md
  pages/linux/qm-unlock.md
  pages/linux/qm-vncproxy.md
  pages/linux/qm-wait.md
  pages/linux/qm.md
Labels: page edit, mass changes, review needed

#17372 fastfetch: be explicit on what the structure looks like
  pages/common/fastfetch.md
Labels: page edit, review needed

#17349 nmtui, nmcli: refer to each other
  pages/linux/nmcli.md
  pages/linux/nmtui.md
Labels: page edit, review needed

#17348 nmcli-device: add example
  pages/linux/nmcli-device.md
Labels: page edit, review needed

#17343 hddtemp: add page
  pages/linux/hddtemp.md
Labels: new command, review needed

#17346 systemctl*: add Dutch translation
  pages.nl/linux/systemctl-disable.md
  pages.nl/linux/systemctl-enable.md
  pages.nl/linux/systemctl-reboot.md
  pages.nl/linux/systemctl.md
Labels: new translation

#17353 apt-install: add page
  pages/linux/apt-install.md
Labels: new command, review needed

#17347 exrex: add short options
  pages/common/exrex.md
Labels: page edit, review needed

#17377 fish: refresh translation pages
  pages.de/common/fish.md
  pages.fr/common/fish.md
  pages.ko/common/fish.md
  pages.nl/common/fish.md
  pages.zh/common/fish.md
Labels: translation edit

#17374 pages.*: move translations to the correct location
  pages.es/linux/qm-cloudinit.md
  pages.ko/common/qemu.md
  pages.ko/linux/qm-cloudinit.md
  pages.ko/linux/wireplumber.md
  pages.ko/linux/wpexec.md
  pages.zh/common/qemu.md
  pages/linux/qm-cloudinit.md
Labels: page edit, translation edit

#17369 qwen: add page
  pages/common/qwen.md
Labels: new command, review needed

#17257 manim: add page
  pages.ko/common/manim.md
  pages.zh/common/manim.md
  pages/common/manim.md
Labels: new command, new translation

#17382 sbctl: add option placeholders
  pages.es/linux/sbctl.md
  pages.ko/linux/sbctl.md
  pages/linux/sbctl.md
Labels: page edit, translation edit

#17380 pages.nl/*: update Dutch translations
  pages.nl/common/git-switch.md
  pages.nl/common/objdump.md
  pages.nl/common/tar.md
  pages.nl/linux/nmcli-device.md
  pages.nl/linux/pacman-upgrade.md
  pages.nl/linux/qm-disk-import.md
  pages.nl/linux/qm-disk-move.md
  pages.nl/linux/qm-disk-resize.md
  pages.nl/linux/systemd-mount.md
Labels: translation edit

#17237 slocate: add page
  pages/common/slocate.md
Labels: new command, review needed

#17397 cisco-ios: fix platform name
  pages/cisco-ios/enable.md
Labels: page edit, review needed

#17400 cmus: update page and add Dutch translation
  pages.nl/linux/cmus.md
  pages/linux/cmus.md
Labels: page edit, new translation

#17365 papermc: add page
  pages/common/papermc.md
Labels: new command, review needed

#17391 certtool: add page
  pages/linux/certtool.md
Labels: new command, review needed

#17206 %: add Hindi translation
  pages.hi/common/%.md
Labels: new translation

#17406 elasticsearch-croneval: add page
  pages/common/elasticsearch-croneval.md
Labels: new command, new translation
