Repository tldr-pages/tldr, pull requests merged in 2025-08, with the labels that each got.

#17451 nordvpn: add aliases
  pages/linux/nordvpn.md
Labels: page edit, review needed

#17410 cat: update Russian translation
  pages.ru/common/cat.md
Labels: review needed, translation edit

#17459 pdftocairo: fix broken links
  pages.ko/common/pdftocairo.md
  pages/common/pdftocairo.md
Labels: page edit, translation edit

#17455 fdisk: update page
  pages/linux/fdisk.md
Labels: page edit, review needed

#17436 gpu-screen-recorder: add page
  pages/linux/gpu-screen-recorder.md
Labels: new command, review needed

#17483 whence: fix broken links
  pages.es/osx/whence.md
  pages.ko/osx/whence.md
  pages/osx/whence.md
Labels: page edit, translation edit

#17482 numlockx: fix broken links
  pages.de/linux/numlockx.md
  pages.ko/linux/numlockx.md
  pages/linux/numlockx.md
Labels: page edit, translation edit

#17480 jbang: fix broken links
  pages.es/common/jbang.md
  pages.ko/common/jbang.md
  pages.zh/common/jbang.md
  pages/common/jbang.md
Labels: page edit, translation edit

#17478 f5fpc: fix broken links
  pages.ko/linux/f5fpc.md
  pages/linux/f5fpc.md
Labels: page edit, translation edit

#17476 chainctl: fix broken links
  pages/common/chainctl.md
Labels: page edit, review needed

#17485 partclone: add page
  pages/linux/partclone.md
Labels: new command, review needed

#17488 common-arguments: update Russian placeholders
  contributing-guides/translation-templates/common-arguments.md
Labels: documentation

#17486 whence: move to common
  pages.es/common/whence.md
  pages.ko/common/whence.md
  pages/common/whence.md
Labels: page edit, translation edit

#17324 android/*: add Japanese translation
  pages.ja/android/am.md
  pages.ja/android/bugreport.md
  pages.ja/android/bugreportz.md
  pages.ja/android/cmd.md
  pages.ja/android/dalvikvm.md
  pages.ja/android/dumpsys.md
  pages.ja/android/getprop.md
  pages.ja/android/input.md
  pages.ja/android/logcat.md
  pages.ja/android/pkg.md
  pages.ja/android/pm.md
  pages.ja/android/screencap.md
  pages.ja/android/settings.md
  pages.ja/android/wm.md
Labels: mass changes, review needed, new translation

#17340 avrdude, picotool, esptool.py, i3, cmatrix: add Czech translation
  pages.cs/common/avrdude.md
  pages.cs/common/cmatrix.md
  pages.cs/common/esptool.py.md
  pages.cs/common/i3.md
  pages.cs/common/picotool.md
Labels: review needed, new translation

#17446 elasticsearch-create-enrollment-token: add page
  pages/common/elasticsearch-create-enrollment-token.md
Labels: new command, review needed

#17505 bootctl: simplify command
  pages/linux/bootctl.md
Labels: page edit, review needed

#17469 dir: add sort example
  pages/windows/dir.md
Labels: page edit, review needed

#17525 syncthing: refresh page
  pages/common/syncthing.md
Labels: page edit, review needed

#17519 yaourt: update more info link
  pages/linux/yaourt.md
Labels: page edit, review needed

#17518 vhs: update page
  pages/common/vhs.md
Labels: page edit, review needed

#17521 qm: match options with manual page
  pages/linux/qm.md
Labels: page edit, review needed

#17517 npm-owner: updated Spanish translation
  pages.es/common/npm-owner.md
Labels: translation edit

#17516 npm-ls: updated Spanish translation
  pages.es/common/npm-ls.md
Labels: translation edit

#17534 findmnt: expand to multiple types
  pages/linux/findmnt.md
Labels: page edit, review needed

#17453 cp: refresh translation pages
  pages.es/common/cp.md
  pages.id/common/cp.md
  pages.pt_BR/common/cp.md
  pages.ta/common/cp.md
  pages.zh/common/cp.md
Labels: translation edit

#17526 pacman-key: simplify command
  pages/linux/pacman-key.md
Labels: page edit, review needed

#17536 pct-resize: add page
  pages/linux/pct-resize.md
Labels: new command, review needed

#17520 qm-cloudinit: remove page
  pages.es/linux/qm-cloudinit.md
  pages.ko/linux/qm-cloudinit.md
  pages/linux/qm-cloudinit.md
Labels: page edit, translation edit

#17515 qm*: add missing alias pages
  pages/linux/qm-agent.md
  pages/linux/qm-disk-rescan.md
  pages/linux/qm-rescan.md
  pages/linux/qm-unlink.md
Labels: page edit, new command, review needed

#17511 qm-guest: add page
  pages/linux/qm-guest.md
Labels: new command, review needed

#17500 qm-{import-disk, move-disk}: fix incorrect aliases
  pages/linux/qm-importdisk.md
  pages/linux/qm-move-disk.md
Labels: page edit, review needed

#17490 pvesm: add page
  pages/linux/pvesm.md
Labels: new command, review needed

#17498 devenv, gt: conform with style guide and fix typo
  pages/common/devenv.md
  pages/common/gt.md
Labels: page edit, review needed

#17494 pveum: add page
  pages/linux/pveum.md
Labels: new command, review needed

#17538 pct-status: add page
  pages/linux/pct-status.md
Labels: new command, review needed

#17418 grub-install: add simplified example, sudo, and help
  pages/linux/grub-install.md
Labels: page edit, review needed

#17497 kubectl-delete, kubectl-describe: refresh pages
  pages.de/common/kubectl-delete.md
  pages.de/common/kubectl-describe.md
  pages.ko/common/kubectl-delete.md
  pages.ko/common/kubectl-describe.md
Labels: translation edit

#17539 airport: fix broken More Information link
  pages.es/osx/airport.md
  pages.it/osx/airport.md
  pages.ko/osx/airport.md
  pages.pt_BR/osx/airport.md
  pages.th/osx/airport.md
  pages.zh/osx/airport.md
  pages/osx/airport.md
Labels: page edit, translation edit

#17358 aws-google-auth: update Spanish translation
  pages.es/common/aws-google-auth.md
Labels: translation edit

#17360 dnsx: update Spanish translation
  pages.es/common/dnsx.md
Labels: translation edit

#17399 minecraft, crond, fail2ban-client, firewall-cmd: add Italian translation
  pages.it/common/minecraft.md
  pages.it/linux/crond.md
  pages.it/linux/fail2ban-client.md
  pages.it/linux/firewall-cmd.md
Labels: new translation

#17552 update-initramfs: add page
  pages/linux/update-initramfs.md
Labels: new command, review needed

#17507 minidlna: add page
  pages/common/minidlna.md
Labels: new command, review needed

#17561 shuf: fix broken links
  pages.es/osx/shuf.md
  pages.id/osx/shuf.md
  pages.ko/osx/shuf.md
  pages.nl/osx/shuf.md
  pages.zh/osx/shuf.md
  pages/osx/shuf.md
Labels: page edit, translation edit

#17550 pct-set: add page
  pages/linux/pct-set.md
Labels: new command, review needed

#17542 *: remove placeholders from descriptions
  pages/common/crane-index-filter.md
  pages/common/crane-mutate.md
  pages/common/crane.md
  pages/common/gcrane.md
  pages/linux/aide.md
Labels: page edit, review needed

#17512 elasticsearch-node: add page
  pages/common/elasticsearch-node.md
Labels: new command, review needed

#17463 *: fix title issues and a couple of typos
  pages/common/b2.md
  pages/common/chezmoi.md
  pages/common/consul-kv.md
  pages/common/cs-complete-dep.md
  pages/common/gammastep.md
  pages/common/git-grep.md
  pages/common/git-imerge.md
  pages/common/git-maintenance.md
  pages/common/ipython.md
  pages/common/php-cs-fixer.md
  pages/common/pint.md
  pages/common/pyats.md
  pages/common/qownnotes.md
  pages/common/stormlock.md
  pages/common/vboxmanage-clonevm.md
  pages/common/vboxmanage-cloud.md
  pages/common/vboxmanage-controlvm.md
  pages/common/vboxmanage-createvm.md
  pages/common/vboxmanage-export.md
  pages/common/vboxmanage-extpack.md
  pages/common/vboxmanage-import.md
  pages/common/vboxmanage-list.md
  pages/common/vboxmanage-movevm.md
  pages/common/vboxmanage-registervm.md
  pages/common/vboxmanage-showvminfo.md
  pages/common/vboxmanage-startvm.md
  pages/common/vboxmanage-unregistervm.md
  pages/common/virsh-connect.md
  pages/common/virsh-domblklist.md
  pages/common/virsh-help.md
  pages/common/virsh-list.md
  pages/common/yadm-alt.md
  pages/common/yadm-bootstrap.md
  pages/common/yadm-clone.md
  pages/common/yadm-config.md
  pages/common/yadm-decrypt.md
  pages/common/yadm-encrypt.md
  pages/common/yadm-enter.md
  pages/common/yadm-gitconfig.md
  pages/common/yadm-init.md
  pages/common/yadm-introspect.md
  pages/common/yadm-list.md
  pages/common/yadm-perms.md
  pages/common/yadm-transcrypt.md
  pages/common/yadm-upgrade.md
  pages/linux/fprintd-verify.md
  pages/linux/gnome-extensions.md
  pages/osx/autoraise.md
  pages/windows/choco-push.md
Labels: page edit, mass changes, review needed

#17464 csvkit: remove page
  pages.fa/common/csvkit.md
  pages.ko/common/csvkit.md
  pages/common/csvkit.md
Labels: page edit, translation edit

#17551 lspci: add device ID example
  pages/linux/lspci.md
Labels: page edit, review needed

#17565 sfdk-emulator-{exec, list, set, show, start, status, stop}: prune pages
  pages/common/sfdk-emulator-exec.md
  pages/common/sfdk-emulator-list.md
  pages/common/sfdk-emulator-set.md
  pages/common/sfdk-emulator-show.md
  pages/common/sfdk-emulator-start.md
  pages/common/sfdk-emulator-status.md
  pages/common/sfdk-emulator-stop.md
  pages/common/sfdk-emulator.md
Labels: page edit, mass changes, review needed

#17560 emond: fix broken links
  pages.es/osx/emond.md
  pages.ko/osx/emond.md
  pages.pt_BR/osx/emond.md
  pages/osx/emond.md
Labels: page edit, translation edit

#17576 wps: fix broken links
  pages.es/osx/wps.md
  pages.ko/osx/wps.md
  pages/osx/wps.md
Labels: page edit, translation edit

#17574 bnepd: fix broken links
  pages.es/osx/bnepd.md
  pages.ko/osx/bnepd.md
  pages.pt_BR/osx/bnepd.md
  pages/osx/bnepd.md
Labels: page edit, translation edit

#17578 wwand: fix broken links
  pages.es/osx/wwand.md
  pages.ko/osx/wwand.md
  pages/osx/wwand.md
Labels: page edit, translation edit

#17549 kodi-send: add page
  pages/common/kodi-send.md
Labels: new command, review needed

#17514 elasticsearch-users: add page
  pages/common/elasticsearch-users.md
Labels: new command, review needed

#17563 parted.interactive: rename page
  pages/linux/parted.interactive.md
  pages/linux/parted.md
Labels: page edit, review needed

#17572 pct-exec: add page
  pages/linux/pct-exec.md
Labels: new command, review needed

#17570 bindfs: add page
  pages/linux/bindfs.md
Labels: new command, review needed

#17407 common/h~m*: fix outdated Brazilian Portuguese pages
  pages.pt_BR/common/history.md
  pages.pt_BR/common/htop.md
  pages.pt_BR/common/id.md
  pages.pt_BR/common/join.md
  pages.pt_BR/common/kill.md
  pages.pt_BR/common/magick-convert.md
  pages.pt_BR/common/man.md
Labels: translation edit

#17555 lsfd: remove leading slash in file path
  pages/linux/lsfd.md
Labels: page edit, minor change

#17402 terraria: update Korean translation
  pages.ko/linux/terraria.md
Labels: translation edit

#17585 style-guide: add instructions to shorten the link
  contributing-guides/style-guide.md
Labels: documentation

#17558 pve*, qm*: add missing option placeholders
  pages/linux/pct-clone.md
  pages/linux/pct-template.md
  pages/linux/pve-firewall.md
  pages/linux/pveam.md
  pages/linux/pvecm.md
  pages/linux/pvesh.md
  pages/linux/pvesm.md
  pages/linux/pveum.md
  pages/linux/qm-disk-rescan.md
  pages/linux/qm-list.md
  pages/linux/qm-terminal.md
Labels: page edit, mass changes, review needed

#17415 php: add pt_BR translation
  pages.pt_BR/common/php.md
  pages/common/php.md
Labels: page edit, new translation

#17540 unzip: fix Chinese translation
  pages.zh/common/unzip.md
Labels: translation edit

#17573 partclone: fix manpage link
  pages/linux/partclone.md
Labels: page edit, review needed

#17596 systemd-cgtop: fix page
  pages/linux/systemd-cgtop.md
Labels: page edit, review needed

#17462 lid*: refresh pages
  pages/linux/libuser-lid.md
  pages/linux/lid.libuser.md
  pages/linux/lid.md
Labels: page edit, new command, review needed

#17595 lxc-top: add page
  pages/linux/lxc-top.md
Labels: new command, review needed

#17594 repo-add: fix incorrect description, add manual addition and a see also section
  pages/linux/repo-add.md
  pages/linux/repo-remove.md
Labels: page edit, review needed

#17569 qm-{import-disk.move-disk}: rename translations, fix titles
  pages.es/linux/qm-importdisk.md
  pages.es/linux/qm-move-disk.md
  pages.ko/linux/qm-importdisk.md
  pages.ko/linux/qm-move-disk.md
  pages.nl/linux/qm-importdisk.md
  pages.nl/linux/qm-move-disk.md
  pages.pl/linux/qm-importdisk.md
  pages.pl/linux/qm-move-disk.md
Labels: translation edit

#17564 surfraw: refresh page, sr: add alias page
  pages/common/sr.md
  pages/common/surfraw.md
Labels: page edit, new command, review needed

#17473 pwd: update Russian translation
  pages.ru/common/pwd.md
Labels: review needed, translation edit

#17472 cd: add Russian translation
  pages.ru/common/cd.md
Labels: review needed, new translation

#17591 rmdir: add cleanup example
  pages/common/rmdir.md
Labels: page edit, review needed

#17547 qm-create: simplify example and add install media
  pages/linux/qm-create.md
Labels: page edit, review needed

#17620 b2-tools: rename translations to b2
  pages.es/common/b2.md
  pages.ko/common/b2.md
Labels: translation edit

#17628 hg*: fixing broken links
  pages.ko/common/hg-add.md
  pages.ko/common/hg-branch.md
  pages.ko/common/hg-clone.md
  pages.ko/common/hg-commit.md
  pages.ko/common/hg-init.md
  pages.ko/common/hg-log.md
  pages.ko/common/hg-pull.md
  pages.ko/common/hg-push.md
  pages.ko/common/hg-remove.md
  pages.ko/common/hg-root.md
  pages.ko/common/hg-serve.md
  pages.ko/common/hg-status.md
  pages.ko/common/hg-update.md
  pages.ko/common/hg.md
  pages/common/hg-add.md
  pages/common/hg-branch.md
  pages/common/hg-clone.md
  pages/common/hg-commit.md
  pages/common/hg-init.md
  pages/common/hg-log.md
  pages/common/hg-pull.md
  pages/common/hg-push.md
  pages/common/hg-remove.md
  pages/common/hg-root.md
  pages/common/hg-serve.md
  pages/common/hg-status.md
  pages/common/hg-update.md
  pages/common/hg.md
Labels: page edit, mass changes, translation edit

#17625 audit2{allow,why}: add Dutch translation
  pages.nl/common/audit2allow.md
  pages.nl/common/audit2why.md
Labels: new translation

#17640 cbonsai: add examples
  pages/common/cbonsai.md
Labels: page edit, review needed

#17581 vboxmanage-modifyvm: add page
  pages/common/vboxmanage-modifyvm.md
Labels: new command, review needed

#17644 python: update more info link
  pages/common/python.md
Labels: page edit, review needed

#17626 audit2allow: remove duplicate page and move translations to common
  pages.es/common/audit2allow.md
  pages.ko/common/audit2allow.md
  pages/linux/audit2allow.md
Labels: page edit, translation edit

#17659 kubectl-{describe, delete, create, taint}: add option placeholders
  pages/common/kubectl-create.md
  pages/common/kubectl-delete.md
  pages/common/kubectl-describe.md
  pages/common/kubectl-taint.md
Labels: page edit, review needed

#17660 monolith: add page
  pages/common/monolith.md
Labels: new command, review needed

#17618 openstack-flavor: add page
  pages/common/openstack-flavor.md
Labels: new command, review needed

#17612 crypto: add page
  pages/cisco-ios/crypto.md
Labels: new command, review needed

#17474 zbarimg: update Spanish translation
  pages.es/common/zbarimg.md
Labels: translation edit

#17655 modprobe: add short options
  pages/linux/modprobe.md
Labels: page edit, review needed

#17664 flake8: fix link
  pages/common/flake8.md
Labels: page edit, review needed

#17571 pct-destroy: add page
  pages/linux/pct-destroy.md
Labels: new command, review needed

#17583 mpijavac: add page
  pages/common/mpijavac.md
Labels: new command, review needed

#17603 dir: add page
  pages/cisco-ios/dir.md
Labels: new command, review needed

#17602 delete: add page
  pages/cisco-ios/delete.md
Labels: new command, review needed

#17613 configure: add page
  pages/cisco-ios/configure.md
Labels: new command, review needed

#17604 reload: add page
  pages/cisco-ios/reload.md
Labels: new command, review needed

#17671 pvesm: add storage set and file remove example
  pages/linux/pvesm.md
Labels: page edit, review needed

#17615 line: add page
  pages/cisco-ios/line.md
Labels: new command, review needed

#17637 systemctl-status: add page
  pages/linux/systemctl-status.md
Labels: new command, review needed

#17682 systemctl: edit page
  pages/linux/systemctl.md
Labels: page edit, review needed

#17675 *: use a more specific more info link
  pages/common/alr.md
  pages/common/bird.md
  pages/common/birdc.md
  pages/common/browsh.md
  pages/common/crontab.md
  pages/common/devcontainer.md
  pages/common/gnuplot.md
  pages/common/go.md
  pages/common/helm.md
  pages/common/htop.md
  pages/common/multipass.md
  pages/common/nxc-vnc.md
  pages/common/railway.md
  pages/common/rtmpdump.md
  pages/common/testssl.md
  pages/common/trip.md
Labels: page edit, mass changes, review needed

#17614 username: add page
  pages/cisco-ios/username.md
Labels: new command, review needed

#17656 modetest: add page
  pages/linux/modetest.md
Labels: new command, review needed

#17654 chvt: add page
  pages/linux/chvt.md
Labels: new command, review needed

#17652 kubectl-apply: refresh page
  pages/common/kubectl-apply.md
Labels: page edit, review needed

#17646 nmcli-device: updated Spanish translation
  pages.es/linux/nmcli-device.md
Labels: translation edit

#17645 nmcli-monitor: updated Spanish translation
  pages.es/linux/nmcli-monitor.md
Labels: translation edit

#17643 nmcli-radio: updated Spanish translation
  pages.es/linux/nmcli-radio.md
Labels: translation edit

#17641 GNU tools: use single page documentation
  pages/common/bash.md
  pages/common/cmp.md
  pages/common/complete.md
  pages/common/envsubst.md
  pages/common/gettext.md
  pages/common/hello.md
  pages/common/history.md
  pages/common/ifs.md
  pages/common/msgcat.md
  pages/common/msgfmt.md
  pages/common/msginit.md
  pages/common/msgmerge.md
  pages/common/msgunfmt.md
  pages/common/popd.md
  pages/common/pushd.md
  pages/common/rbash.md
  pages/common/shopt.md
  pages/common/stow.md
  pages/common/wdiff.md
  pages/common/xgettext.md
  pages/linux/datamash.md
  pages/linux/diff3.md
  pages/linux/dnsdomainname.md
  pages/linux/grub-install.md
  pages/linux/grub-mkconfig.md
  pages/linux/grub-script-check.md
  pages/linux/guix-package.md
  pages/linux/parted.md
  pages/linux/rcp.md
  pages/linux/rexec.md
  pages/linux/rlogin.md
  pages/linux/rsh.md
  pages/linux/talk.md
Labels: page edit, mass changes, review needed

#17676 *: use a more specific more info link, io domain
  pages/common/babel.md
  pages/common/bower.md
  pages/common/codecrafters.md
  pages/common/conan.md
  pages/common/ctags.md
  pages/common/esbuild.md
  pages/common/hexo.md
  pages/common/hugo.md
  pages/common/packer.md
  pages/common/prettier.md
  pages/common/streamlit.md
  pages/common/todoman.md
  pages/common/tqdm.md
  pages/common/typeorm.md
  pages/linux/abrt-cli.md
  pages/linux/pivpn.md
Labels: page edit, mass changes, review needed

#17642 devenv: updated Spanish translation
  pages.es/common/devenv.md
Labels: translation edit

#17484 apk: add Russian translation
  pages.ru/linux/apk.md
Labels: review needed, new translation

#17635 cage: add examples
  pages/linux/cage.md
Labels: page edit, review needed

#17479 pages.ru/apt-*, apt, add-apt-repository: add Russian translation
  pages.ru/linux/add-apt-repository.md
  pages.ru/linux/apt-add-repository.md
  pages.ru/linux/apt-cache.md
  pages.ru/linux/apt-file.md
  pages.ru/linux/apt-get.md
  pages.ru/linux/apt-install.md
  pages.ru/linux/apt-key.md
  pages.ru/linux/apt-mark.md
  pages.ru/linux/apt-moo.md
  pages.ru/linux/apt.md
Labels: review needed, new translation

#17685 declare: add example
  pages/common/declare.md
Labels: page edit, review needed

#17475 cmus: update Spanish translation
  pages.es/linux/cmus.md
Labels: translation edit

#17290 magick-{,convert,compare,identity,import,mogrify,montage}: add Chinese translation
  pages.zh/common/magick-compare.md
  pages.zh/common/magick-convert.md
  pages.zh/common/magick-identify.md
  pages.zh/common/magick-import.md
  pages.zh/common/magick-mogrify.md
  pages.zh/common/magick-montage.md
  pages.zh/common/magick.md
Labels: new translation

#17677 conan-frogarian: delete page
  pages.ko/common/conan-frogarian.md
  pages/common/conan-frogarian.md
Labels: page edit, translation edit

#17672 qm: use scsi instead of ide
  pages/linux/qm.md
Labels: page edit, review needed

#17661 {: add placeholders
  pages/common/{.md
Labels: page edit, review needed

#17650 kubectl-edit: refresh page
  pages/common/kubectl-edit.md
Labels: page edit, review needed

#17690 git-push: refresh pages
  pages.de/common/git-push.md
  pages.es/common/git-push.md
  pages.fr/common/git-push.md
  pages.id/common/git-push.md
  pages.it/common/git-push.md
  pages.ko/common/git-push.md
  pages.pt_BR/common/git-push.md
  pages.tr/common/git-push.md
  pages.uk/common/git-push.md
Labels: translation edit

#17691 git-apply: refresh pages
  pages.de/common/git-apply.md
  pages.fr/common/git-apply.md
  pages.id/common/git-apply.md
  pages.ko/common/git-apply.md
  pages.ta/common/git-apply.md
  pages.tr/common/git-apply.md
  pages.zh/common/git-apply.md
Labels: translation edit

#17556 sudoedit: add Spanish translation
  pages.es/common/sudoedit.md
Labels: new translation

#17611 show: add page
  pages/cisco-ios/show.md
Labels: new command, review needed

#17653 fbset: add page
  pages/linux/fbset.md
Labels: new command, review needed

#17605 umount: add sudo
  pages/linux/umount.md
Labels: page edit, review needed

#17663 kubectl-label: add option placeholders
  pages/common/kubectl-label.md
Labels: page edit, review needed

#17699 *: use a more specific more info link, org domain
  pages/common/clangd.md
  pages/common/composer.md
  pages/common/cryfs.md
  pages/common/dillo.md
  pages/common/espanso.md
  pages/common/fossil-commit.md
  pages/common/fossil-delete.md
  pages/common/fossil-rm.md
  pages/common/fossil.md
  pages/common/godoc.md
  pages/common/godot.md
  pages/common/haxelib.md
  pages/common/lzop.md
  pages/common/meld.md
  pages/common/mpd.md
  pages/common/newsboat.md
  pages/common/opam.md
  pages/common/pngquant.md
  pages/common/pytest.md
  pages/common/qutebrowser.md
  pages/common/rr.md
  pages/common/sbcl.md
  pages/common/svn-changelist.md
  pages/common/svn.md
  pages/common/swipl.md
  pages/common/tofu.md
  pages/common/vala.md
  pages/common/valac.md
  pages/common/weasyprint.md
  pages/common/wkhtmltopdf.md
  pages/common/wp.md
  pages/common/yard.md
  pages/linux/avahi-browse.md
  pages/linux/avahi-resolve.md
  pages/linux/rpm.md
  pages/linux/terminator.md
  pages/linux/wine.md
Labels: page edit, mass changes, review needed

#17647 tig: add blame example
  pages/common/tig.md
Labels: page edit, review needed

#17634 ip: add page
  pages/cisco-ios/ip.md
Labels: new command, review needed

#17694 *: use a more specific more info link, com domain
  pages/common/argos-translate.md
  pages/common/flake8.md
  pages/common/heroku.md
  pages/common/linkchecker.md
  pages/common/monodevelop.md
  pages/common/pinta.md
  pages/common/serverless.md
  pages/common/tcpreplay.md
  pages/linux/etckeeper.md
  pages/linux/links.md
  pages/linux/links2.md
  pages/osx/cot.md
Labels: page edit, mass changes, review needed

#17689 complete: simplify builtin option
  pages/common/complete.md
Labels: page edit, review needed

#17649 kubectl-config: add default namespace switching example
  pages/common/kubectl-config.md
Labels: page edit, review needed

#17648 git-blame: add an example to blame similar to github UI
  pages/common/git-blame.md
Labels: page edit, review needed

#17639 openstack-{network, port, subnet}: add page
  pages/common/openstack-network.md
  pages/common/openstack-port.md
  pages/common/openstack-subnet.md
Labels: new command, review needed

#17632 pct-config: add page
  pages/linux/pct-config.md
Labels: new command, review needed

#17673 clock: add page
  pages/cisco-ios/clock.md
Labels: new command, review needed

#17610 write: add page
  pages/cisco-ios/write.md
Labels: new command, review needed

#17701 line: update more information link
  pages/cisco-ios/line.md
Labels: page edit, review needed

#17706 git-cherry-pick: refresh pages
  pages.bn/common/git-cherry-pick.md
  pages.es/common/git-cherry-pick.md
  pages.fr/common/git-cherry-pick.md
  pages.id/common/git-cherry-pick.md
  pages.it/common/git-cherry-pick.md
  pages.ko/common/git-cherry-pick.md
  pages.ta/common/git-cherry-pick.md
  pages.tr/common/git-cherry-pick.md
  pages.uk/common/git-cherry-pick.md
  pages.zh/common/git-cherry-pick.md
Labels: translation edit

#17702 show: fix example
  pages/cisco-ios/show.md
Labels: page edit, review needed

#17589 qm-snapshot: specify name format and add related commands examples
  pages/linux/qm-snapshot.md
Labels: page edit, review needed

#17705 git-checkout: add short options
  pages.es/common/git-checkout.md
  pages.fr/common/git-checkout.md
  pages.id/common/git-checkout.md
  pages.it/common/git-checkout.md
  pages.ko/common/git-checkout.md
  pages.pt_BR/common/git-checkout.md
  pages.ta/common/git-checkout.md
  pages.tr/common/git-checkout.md
  pages.uk/common/git-checkout.md
  pages.zh/common/git-checkout.md
Labels: translation edit

#17704 git-am: refresh pages
  pages.de/common/git-am.md
  pages.es/common/git-am.md
  pages.id/common/git-am.md
  pages.ko/common/git-am.md
  pages.pl/common/git-am.md
  pages.ta/common/git-am.md
Labels: translation edit

#17703 git-check-ignore: add short options
  pages.es/common/git-check-ignore.md
  pages.fr/common/git-check-ignore.md
  pages.id/common/git-check-ignore.md
  pages.it/common/git-check-ignore.md
  pages.ko/common/git-check-ignore.md
  pages.ta/common/git-check-ignore.md
  pages.tr/common/git-check-ignore.md
  pages.zh/common/git-check-ignore.md
Labels: translation edit

#17713 MAINTAINERS: add @TheRootDaemon as a collaborator
  MAINTAINERS.md
Labels: community
