Repository tldr-pages/tldr, pull requests merged in 2025-01, with the labels that each got.

#15315 pacman-q, pacman-query: add Dutch translation
  pages.nl/linux/pacman-q.md
  pages.nl/linux/pacman-query.md
Labels: translation

#15316 dnf-group: add Dutch translation
  pages.nl/linux/dnf-group.md
Labels: translation

#15317 batch: update Dutch translation
  pages.nl/common/batch.md
Labels: translation

#15318 pacman-files: add Dutch translation
  pages.nl/linux/pacman-files.md
Labels: translation

#15386 x86_64, uname26, linux32, linux64, i386: add Dutch translation
  pages.nl/linux/i386.md
  pages.nl/linux/linux32.md
  pages.nl/linux/linux64.md
  pages.nl/linux/uname26.md
  pages.nl/linux/x86_64.md
Labels: translation

#15384 semanage-port: add port range example
  pages/linux/semanage-port.md
Labels: page edit

#15404 kpackagetool6: add page; kpackagetool5: update link
  pages/linux/kpackagetool5.md
  pages/linux/kpackagetool6.md
Labels: page edit, new command

#15403 lookandfeeltool: add page
  pages/linux/lookandfeeltool.md
Labels: new command

#13975 pct, pveversion: add page
  pages/linux/pct.md
  pages/linux/pveversion.md
Labels: new command, hacktoberfest-accepted

#14702 common/c~d*: fix outdated Brazilian Portuguese pages
  pages.pt_BR/common/chown.md
  pages.pt_BR/common/cut.md
  pages.pt_BR/common/dart.md
  pages.pt_BR/common/diff.md
  pages.pt_BR/common/dig.md
  pages.pt_BR/common/docker-run.md
  pages.pt_BR/common/du.md
Labels: waiting, translation, review needed

#15421 pages.nl/*: uniform translation for 'package manager'
  pages.nl/common/npm.md
  pages.nl/freebsd/pkg.md
  pages.nl/linux/apx-pkgmanagers.md
  pages.nl/linux/apx-stacks.md
  pages.nl/linux/distrobox-upgrade.md
  pages.nl/linux/dnf.md
  pages.nl/linux/xbps.md
  pages.nl/openbsd/pkg.md
  pages.nl/osx/port.md
Labels: translation edit

#15418 pages.nl/*: uniform translation for 'See also'
  pages.nl/common/bc.md
  pages.nl/common/httpie.md
  pages.nl/common/mesg.md
  pages.nl/common/more.md
  pages.nl/common/nvm.md
  pages.nl/common/popd.md
  pages.nl/common/pushd.md
  pages.nl/common/renice.md
  pages.nl/common/rmdir.md
  pages.nl/common/uname.md
  pages.nl/linux/groupmod.md
  pages.nl/linux/ipcs.md
  pages.nl/linux/iptables.md
  pages.nl/linux/mesg.md
  pages.nl/linux/more.md
  pages.nl/linux/pacman-sync.md
  pages.nl/linux/renice.md
  pages.nl/linux/rm.md
  pages.nl/linux/rmdir.md
  pages.nl/linux/secon.md
  pages.nl/linux/semanage-boolean.md
  pages.nl/linux/semanage-fcontext.md
  pages.nl/linux/semanage-permissive.md
  pages.nl/linux/semanage-port.md
  pages.nl/osx/arch.md
  pages.nl/osx/bc.md
  pages.nl/osx/netstat.md
  pages.nl/windows/pushd.md
Labels: mass changes, translation edit

#15427 scripts/set-more-info-link: remove duplicated key, pages.*: update more info link
  pages.es/common/declare.md
  pages.ko/common/batch.md
  pages.ko/common/declare.md
  pages.ko/common/home-manager.md
  pages.ko/linux/jobs.md
  pages.ko/linux/kpackagetool5.md
  pages.pl/common/batch.md
  pages.pt_BR/common/batch.md
  scripts/set-more-info-link.py
Labels: tooling, script runs, translation edit

#15408 %: add Korean translation
  pages.ko/common/%.md
Labels: new translation

#15419 pacman-*: update pages and add Dutch translations
  pages.nl/linux/pacman-d.md
  pages.nl/linux/pacman-database.md
  pages.nl/linux/pacman-deptest.md
  pages.nl/linux/pacman-files.md
  pages.nl/linux/pacman-query.md
  pages.nl/linux/pacman-t.md
  pages.nl/linux/pacman-u.md
  pages.nl/linux/pacman-upgrade.md
  pages/linux/pacman-database.md
  pages/linux/pacman-deptest.md
  pages/linux/pacman-upgrade.md
Labels: page edit, new translation, translation edit

#15417 jupyterlab: add Dutch translation
  pages.nl/common/jupyterlab.md
Labels: new translation

#15416 mapfile, readarray: add Dutch translation
  pages.nl/common/mapfile.md
  pages.nl/common/readarray.md
Labels: new translation

#15414 tldr: update Spanish translation
  pages.es/common/tldr.md
Labels: translation edit

#15437 jupyter-lab: add Dutch translation
  pages.nl/common/jupyter-lab.md
Labels: new translation

#15364 $: add Chinese translation
  pages.zh/common/$.md
Labels: new translation

#15441 kubectl wait: add page
  pages/common/kubectl-wait.md
Labels: new command, review needed

#15446 case: remove unnecessary semicolon
  pages/common/case.md
Labels: page edit, review needed

#15450 CODEOWNERS: add Managor for finnish pages
  .github/CODEOWNERS
Labels: community, review needed

#15084 a2enconf, a2enmod, aa-disable, alien: add Bengali translation
  pages.bn/linux/a2enconf.md
  pages.bn/linux/a2enmod.md
  pages.bn/linux/aa-disable.md
  pages.bn/linux/alien.md
Labels: review needed, new translation

#15398 makepkg: add Chinese translation
  pages.zh/linux/makepkg.md
Labels: new translation

#15396 seq: add Chinese translation
  pages.zh/common/seq.md
Labels: new translation

#15399 paste: add Chinese translation
  pages.zh/common/paste.md
Labels: new translation

#15451 false: add Spanish translation
  pages.es/common/false.md
Labels: new translation

#15449 steamos-chroot: add page
  pages/linux/steamos-chroot.md
Labels: new command

#15442 glow: add Chinese translation
  pages.zh/common/glow.md
Labels: new translation

#15444 lookandfeeltool: convert to alias, plasma-apply-lookandfeel: add page
  pages/linux/lookandfeeltool.md
  pages/linux/plasma-apply-lookandfeel.md
Labels: page edit, new command

#15422 chsh, echo, mkdir, mv, tldr: add and improve Indonesian translations
  pages.id/common/chsh.md
  pages.id/common/echo.md
  pages.id/common/mkdir.md
  pages.id/common/mv.md
  pages.id/common/tldr.md
Labels: review needed, new translation, translation edit

#15390 tuc: add Spanish translation
  pages.es/common/tuc.md
Labels: new translation

#15445 plasma-apply-colorscheme, plasma-apply-cursortheme, plasma-apply-desktoptheme, plasma-apply-wallpaperimage: add page
  pages/linux/plasma-apply-colorscheme.md
  pages/linux/plasma-apply-cursortheme.md
  pages/linux/plasma-apply-desktoptheme.md
  pages/linux/plasma-apply-wallpaperimage.md
Labels: new command

#15462 kubeadm: update page
  pages/common/kubeadm.md
Labels: page edit, review needed

#15433 FileCheck: add page
  pages/common/filecheck.md
Labels: new command, review needed

#15452 cat: add Arabic translation
  pages.ar/common/cat.md
Labels: review needed, new translation

#15470 mkdir: update documentation link
  pages.es/common/mkdir.md
  pages.fa/common/mkdir.md
  pages.fr/common/mkdir.md
  pages.hi/common/mkdir.md
  pages.id/common/mkdir.md
  pages.it/common/mkdir.md
  pages.ko/common/mkdir.md
  pages.nl/common/mkdir.md
  pages.sr/common/mkdir.md
  pages.ta/common/mkdir.md
  pages.tr/common/mkdir.md
  pages.zh/common/mkdir.md
  pages.zh_TW/common/mkdir.md
  pages/common/mkdir.md
Labels: page edit, mass changes, translation edit

#15456 scriptlive: add Spanish translation
  pages.es/linux/scriptlive.md
Labels: translation, new translation

#15472 reflector: add config file example
  pages/linux/reflector.md
Labels: page edit

#15478 dirname: update documentation link
  pages.it/common/dirname.md
  pages.ko/common/dirname.md
  pages.nl/common/dirname.md
  pages.tr/common/dirname.md
  pages/common/dirname.md
Labels: page edit, translation edit

#15465 kpackagetool6: add Spanish translation
  pages.es/linux/kpackagetool6.md
Labels: new translation

#15482 if: update Dutch translation
  pages.nl/common/if.md
Labels: translation edit

#15481 pages.nl/*: uniform 'Display help' translation
  pages.nl/common/crane-append.md
  pages.nl/common/crane-auth.md
  pages.nl/common/crane-blob.md
  pages.nl/common/crane-catalog.md
  pages.nl/common/crane-config.md
  pages.nl/common/crane-copy.md
  pages.nl/common/crane-delete.md
  pages.nl/common/crane-digest.md
  pages.nl/common/crane-flatten.md
  pages.nl/common/crane-index-append.md
  pages.nl/common/crane-index-filter.md
  pages.nl/common/crane-index.md
  pages.nl/common/crane-ls.md
  pages.nl/common/crane-manifest.md
  pages.nl/common/crane-mutate.md
  pages.nl/common/crane-pull.md
  pages.nl/common/crane-push.md
  pages.nl/common/crane-rebase.md
  pages.nl/common/crane-tag.md
  pages.nl/common/crane-validate.md
  pages.nl/common/crane-version.md
  pages.nl/common/fc.md
  pages.nl/common/gcrane-copy.md
  pages.nl/common/gcrane-gc.md
  pages.nl/common/gcrane-help.md
  pages.nl/common/gcrane-ls.md
  pages.nl/common/gcrane.md
  pages.nl/linux/dir.md
  pages.nl/linux/dnf-config-manager.md
  pages.nl/linux/gcrane-completion.md
  pages.nl/osx/gcrane-completion.md
  pages.nl/windows/ftp.md
  pages.nl/windows/gcrane-completion.md
  pages.nl/windows/more.md
Labels: mass changes, translation edit

#15464 steamos-chroot: add Spanish translation
  pages.es/linux/steamos-chroot.md
Labels: new translation

#15473 filecheck: add Spanish translation
  pages.es/common/filecheck.md
Labels: new translation

#15498 contributing-guides, common/*: revise subcommand mention notices
  contributing-guides/translation-templates/subcommand-mention.md
  pages.id/common/adb.md
  pages.id/common/ansible.md
  pages.id/common/argocd.md
  pages.id/common/aws-s3.md
  pages.id/common/docker.md
  pages.id/common/git.md
  pages.id/common/pip.md
  pages.id/common/vue.md
Labels: documentation, review needed, translation edit

#15471 aurpublish: add page
  pages/linux/aurpublish.md
Labels: new command

#15488 df: add Chinese translation
  pages.zh/linux/df.md
Labels: new translation

#15507 qmake: add page
  pages/linux/qmake.md
Labels: new command, review needed

#15506 informant: add page
  pages/linux/informant.md
Labels: new command

#15259 tqdm: add page
  pages/common/tqdm.md
Labels: new command, review needed

#14502 diff: add Japanese translation
  pages.ja/common/diff.md
Labels: review needed, new translation

#15491 cat: add Chinese translation
  pages.zh/linux/cat.md
Labels: new translation

#15493 head: add Chinese translation
  pages.zh/linux/head.md
Labels: new translation

#15466 du: add Chinese translation
  pages.zh/common/du.md
  pages/common/du.md
Labels: page edit, new translation

#15475 smbcacls: add page
  pages/linux/smbcacls.md
Labels: new command

#15497 pages.id/common/*, pages.id/windows/*: add and update Indonesian translations
  pages.id/common/curl.md
  pages.id/common/docker-ps.md
  pages.id/common/rsync.md
  pages.id/common/tar.md
  pages.id/common/vim.md
  pages.id/linux/ruget.md
  pages.id/windows/choco-info.md
  pages.id/windows/choco.md
  pages.id/windows/cmd.md
  pages.id/windows/scoop-bucket.md
Labels: review needed, new translation, translation edit

#15424 pre-commit: update page, add Spanish translation
  pages.es/common/pre-commit.md
  pages/common/pre-commit.md
Labels: page edit, new translation

#15521 pages.pl/netbsd/*: add Polish translations
  pages.pl/netbsd/cal.md
  pages.pl/netbsd/chpass.md
  pages.pl/netbsd/df.md
  pages.pl/netbsd/pkgin.md
  pages.pl/netbsd/sed.md
  pages.pl/netbsd/sockstat.md
Labels: review needed, new translation

#15526 pages.pl/*: replace `zobacz też` with `zobacz także`
  pages.pl/common/ack.md
  pages.pl/common/xkill.md
  pages.pl/linux/groupadd.md
  pages.pl/linux/groupdel.md
  pages.pl/linux/links2.md
  pages.pl/linux/uuid.md
  pages.pl/linux/uuidgen.md
Labels: translation edit

#15535 systemd-analyze: add baseline command
  pages/linux/systemd-analyze.md
Labels: page edit

#15541 cut: add Arabic translation
  pages.ar/common/cut.md
Labels: review needed, new translation

#15544 libinput: add page
  pages/linux/libinput.md
Labels: new command

#15489 dmidecode: add Chinese translation
  pages.zh/linux/dmidecode.md
Labels: new translation

#15511 ip: add Chinese translation
  pages.zh/linux/ip.md
Labels: new translation

#15512 npm: add Chinese translation
  pages.zh/common/npm.md
Labels: new translation

#15513 ssh,ssh-copy-id: add Chinese translation
  pages.zh/common/ssh-copy-id.md
  pages.zh/common/ssh.md
Labels: new translation

#15517 scp: add Chinese translation
  pages.zh/common/scp.md
Labels: new translation

#15523 gzip: add Chinese translation
  pages.zh/common/gzip.md
Labels: new translation

#15546 alacritty: update page
  pages/common/alacritty.md
Labels: page edit, review needed

#15545 kmod: add page, *mod*: add 'See also'
  pages/linux/insmod.md
  pages/linux/kmod.md
  pages/linux/lsmod.md
  pages/linux/modinfo.md
  pages/linux/modprobe.md
  pages/linux/rmmod.md
Labels: page edit, new command, mass changes

#15550 pw-dump: add object dump example
  pages/linux/pw-dump.md
Labels: page edit

#15530 ifconfig: add Arabic translation
  pages.ar/common/ifconfig.md
Labels: review needed, new translation

#15528 vnstat: add Arabic translation
  pages.ar/linux/vnstat.md
Labels: review needed, new translation

#15531 openssl: add Arabic translation
  pages.ar/common/openssl.md
Labels: review needed, new translation

#15559 git-maintenance: clarify description
  pages/common/git-maintenance.md
Labels: page edit, review needed

#15558 git-blame: add examples
  pages/common/git-blame.md
Labels: page edit, review needed

#15505 gprof: add instructions for named binary
  pages/common/gprof.md
Labels: page edit, review needed

#15557 git-config: update page
  pages/common/git-config.md
Labels: page edit, review needed

#15551 lxc-create: add page
  pages/linux/lxc-create.md
Labels: new command

#15486 mbw: add page and Chinese translation
  pages.zh/linux/mbw.md
  pages/linux/mbw.md
Labels: new command, new translation

#15579 MAINTAINERS: add @MachiavelliII as collaborator
  MAINTAINERS.md
Labels: community

#15552 uv-{add, tree}: Add page
  pages/common/uv-add.md
  pages/common/uv-tree.md
  pages/common/uv.md
Labels: page edit, new command, review needed

#15567 exa: update documentation link
  pages.de/common/exa.md
  pages.fr/common/exa.md
  pages.it/common/exa.md
  pages.ko/common/exa.md
  pages.pl/common/exa.md
  pages/common/exa.md
Labels: page edit, translation edit

#15487 arthas, arthas-{trace,watch}: add page and Chinese translation
  pages.zh/common/arthas-trace.md
  pages.zh/common/arthas-watch.md
  pages.zh/common/arthas.md
  pages/common/arthas-trace.md
  pages/common/arthas-watch.md
  pages/common/arthas.md
Labels: new command, new translation

#15527 xkill: add Chinese translation
  pages.zh/common/xkill.md
Labels: new translation

#15589 pulumi-*: update documentation links
  pages.es/common/pulumi-login.md
  pages.ko/common/pulumi-destroy.md
  pages.ko/common/pulumi-login.md
  pages.ko/common/pulumi-up.md
  pages.ko/common/pulumi.md
  pages/common/pulumi-destroy.md
  pages/common/pulumi-login.md
  pages/common/pulumi-logout.md
  pages/common/pulumi-up.md
  pages/common/pulumi.md
Labels: page edit, translation edit

#15604 socat: add multicast example
  pages/common/socat.md
Labels: page edit, review needed

#15598 kde-builder: update initialization
  pages/linux/kde-builder.md
Labels: page edit

#15606 ., %: add Polish translation
  pages.pl/common/%.md
  pages.pl/common/..md
Labels: review needed, new translation

#15573 mpremote: add page
  pages/common/mpremote.md
Labels: new command, review needed

#15549 proxify: add page
  pages/common/proxify.md
Labels: new command, review needed

#15590 rails-server: add page
  pages/common/rails-server.md
Labels: new command, review needed

#15607 rails-new: add page
  pages/common/rails-new.md
Labels: new command, review needed

#15608 rails-console: add page
  pages/common/rails-console.md
Labels: new command, review needed

#15609 proxify: update page
  pages/common/proxify.md
Labels: page edit, review needed, minor change

#15595 ip-maddress: add page
  pages/linux/ip-maddress.md
Labels: new command

#15596 gt: update more information and more commands
  pages/common/gt.md
Labels: page edit, review needed

#15624 whatweb: add page
  pages/common/whatweb.md
Labels: new command, review needed

#15378 %: add Arabic translation
  pages.ar/common/%.md
Labels: review needed, new translation

#15515 informant: add Spanish translation
  pages.es/linux/informant.md
Labels: new translation

#15516 aurpublish: add Spanish translation
  pages.es/linux/aurpublish.md
Labels: new translation

#15518 qmake: add Spanish translation
  pages.es/linux/qmake.md
Labels: new translation

#15525 jupyter-lab: add Spanish translation
  pages.es/common/jupyter-lab.md
Labels: new translation

#15636 $: add examples
  pages/common/$.md
Labels: page edit, review needed

#15630 dialog: add page
  pages/linux/dialog.md
Labels: new command, review needed

#15649 read: update more information link
  pages/common/read.md
Labels: page edit, review needed

#15646 {: update more information link
  pages/common/{.md
Labels: page edit, review needed

#15645 local: update more information link
  pages/common/local.md
Labels: page edit, review needed

#15647 pulumi-config: add `--stack` example
  pages/common/pulumi-config.md
Labels: page edit, review needed

#15611 git-cliff: add page
  pages/common/git-cliff.md
Labels: new command, review needed

#15629 gtk-launch: add page
  pages/linux/gtk-launch.md
Labels: new command
