Repository tldr-pages/tldr, pull requests merged in 2025-03, with the labels that each got.

#15811 style-guide: fix grammar
  contributing-guides/style-guide.md
Labels: documentation

#15773 style-guide: add grouping documentation
  contributing-guides/style-guide.md
Labels: documentation

#15802 style-guide: remove trailing whitespaces
  contributing-guides/style-guide.md
Labels: documentation

#15801 CLIENT-SPECIFICATION: clarify highlighting
  CLIENT-SPECIFICATION.md
Labels: documentation

#15795 CLIENT-SPECIFICATION: remove `-S` and `-E`
  CLIENT-SPECIFICATION.md
Labels: documentation

#15823 ubus: add page
  pages/linux/ubus.md
Labels: new command

#15814 pulumi-refresh: add page
  pages/common/pulumi-refresh.md
Labels: new command, review needed

#15828 composer-audit: add page
  pages/common/composer-audit.md
Labels: new command, review needed

#15807 style-guide: clarify placeholders
  contributing-guides/style-guide.md
Labels: documentation

#15837 man: clarify example
  pages/linux/man.md
Labels: page edit

#15834 yakuake: add page
  pages/linux/yakuake.md
Labels: new command, review needed

#15836 mangohud: add Spanish translation
  pages.es/linux/mangohud.md
Labels: new translation

#15826 lazygit: add Spanish translation
  pages.es/common/lazygit.md
Labels: new translation

#15824 bootc-switch: add Spanish translation
  pages.es/linux/bootc-switch.md
Labels: new translation

#15818 virsh: add Spanish translation
  pages.es/common/virsh.md
Labels: new translation

#15817 exa: add Spanish translation
  pages.es/common/exa.md
Labels: new translation

#15805 gtk-launch: add Spanish translation
  pages.es/linux/gtk-launch.md
Labels: new translation

#15804 protoc: add Spanish translation
  pages.es/common/protoc.md
Labels: new translation

#15852 gcrane-completition: fix broken syntax
  pages.ko/linux/gcrane-completion.md
  pages.ko/osx/gcrane-completion.md
  pages.nl/linux/gcrane-completion.md
  pages.nl/osx/gcrane-completion.md
  pages/linux/gcrane-completion.md
  pages/osx/gcrane-completion.md
Labels: page edit, translation edit

#15847 uci: add page
  pages/linux/uci.md
Labels: new command

#15854 CLIENT-SPECIFICATION: remove useless newlines
  CLIENT-SPECIFICATION.md
Labels: documentation

#15798 style-guide: add keypress documentation instructions.
  contributing-guides/style-guide.md
Labels: documentation, review needed

#15855 CLIENT-SPECIFICATION: require support for common as an arg in platform flag
  CLIENT-SPECIFICATION.md
Labels: documentation

#15851 grim: fix style issues
  pages.es/linux/grim.md
  pages.ko/linux/grim.md
  pages/linux/grim.md
Labels: page edit, translation edit

#15846 pulumi-stack: update example
  pages/common/pulumi-stack.md
Labels: page edit, review needed

#15833 GetNPUsers.py, impacket-GetNPUsers: add page
  pages/common/getnpusers.py.md
  pages/common/impacket-getnpusers.md
Labels: new command, review needed

#15816 GetADUsers.py, impacket-GetADUsers: add page
  pages/common/getadusers.py.md
  pages/common/impacket-getadusers.md
Labels: new command, review needed

#15730 pages.ja/*: add Japanese translation pages
  pages.ja/common/brew.md
  pages.ja/common/cargo.md
  pages.ja/common/chmod.md
  pages.ja/common/chown.md
  pages.ja/common/dotnet.md
  pages.ja/common/ffmpeg.md
  pages.ja/common/ffprobe.md
  pages.ja/common/gcc.md
  pages.ja/common/go.md
  pages.ja/common/gradle.md
  pages.ja/common/java.md
  pages.ja/common/magick.md
  pages.ja/common/make.md
  pages.ja/common/msbuild.md
  pages.ja/common/mvn.md
  pages.ja/common/nginx.md
  pages.ja/common/node.md
  pages.ja/common/npm.md
  pages.ja/common/nslookup.md
  pages.ja/common/rustup.md
  pages.ja/common/time.md
  pages.ja/common/uname.md
  pages.ja/common/zip.md
  pages.ja/linux/dnf.md
  pages.ja/linux/flatpak.md
  pages.ja/linux/iw.md
  pages.ja/linux/snap.md
  pages.ja/linux/ufw.md
  pages.ja/windows/chkdsk.md
  pages.ja/windows/findstr.md
  pages.ja/windows/scoop.md
  pages.ja/windows/winget.md
Labels: mass changes, review needed, new translation

#15865 CLIENT-SPECIFICATION: remove trailing whitespace
  CLIENT-SPECIFICATION.md
Labels: documentation

#15862 CLIENT-SPECIFICATION: add the date of removal of the old asset website
  CLIENT-SPECIFICATION.md
Labels: documentation, review needed

#15871 README: remove trailing whitespace
  README.md
Labels: documentation

#15866 CLIENT-SPECIFICATION: 2.3 release
  CLIENT-SPECIFICATION.md
Labels: documentation

#15856 uname: add shortform options
  pages/linux/uname.md
Labels: page edit

#15868 snmp*: fix example mistakes
  pages/common/snmpdf.md
  pages/common/snmpgetnext.md
  pages/common/snmpset.md
  pages/common/snmpstatus.md
  pages/common/snmptable.md
  pages/common/snmptest.md
Labels: page edit, mass changes, review needed

#15849 mkfs, git-feature: fix GitHub preview rendering
  pages/common/git-feature.md
  pages/linux/mkfs.md
Labels: page edit

#15848 iwinfo: add page
  pages/linux/iwinfo.md
Labels: new command

#15844 apachectl: add page
  pages/linux/apachectl.md
Labels: new command

#15838 zoxide: remove nonexistent --interactive option
  pages.de/common/zoxide.md
  pages.fr/common/zoxide.md
  pages.ko/common/zoxide.md
  pages.zh/common/zoxide.md
  pages/common/zoxide.md
Labels: page edit, translation edit

#15656 common/m*: fix outdated Chinese pages
  pages.zh/common/make.md
  pages.zh/common/md5sum.md
  pages.zh/common/mongod.md
  pages.zh/common/more.md
  pages.zh/common/mpv.md
  pages.zh/common/mv.md
  pages.zh/common/mvn.md
Labels: translation edit

#15867 MAINTAINERS-GUIDE: add info on publishing a client spec release
  contributing-guides/maintainers-guide.md
Labels: documentation

#15794 *: fix style guide issues part 8
  pages.de/linux/ip-address.md
  pages.es/linux/ip-address.md
  pages.es/linux/ip-link.md
  pages.es/linux/ip-maddress.md
  pages.es/linux/ip-neighbour.md
  pages.es/linux/ip-route-get.md
  pages.es/linux/ip-route.md
  pages.es/linux/ip-rule.md
  pages.fr/linux/ip-address.md
  pages.ko/linux/ip-address.md
  pages.ko/linux/ip-link.md
  pages.ko/linux/ip-neighbour.md
  pages.ko/linux/ip-route-get.md
  pages.ko/linux/ip-route.md
  pages.ko/linux/ip-rule.md
  pages.tr/linux/ip-address.md
  pages.tr/linux/ip-link.md
  pages.tr/linux/ip-neighbour.md
  pages.tr/linux/ip-route.md
  pages.tr/linux/ip-rule.md
  pages/linux/ip-address.md
  pages/linux/ip-link.md
  pages/linux/ip-maddress.md
  pages/linux/ip-neighbour.md
  pages/linux/ip-route-get.md
  pages/linux/ip-route.md
  pages/linux/ip-rule.md
Labels: page edit, mass changes, translation edit

#15793 *: fix style guide issues part 7
  pages.de/linux/ip.md
  pages.es/linux/ip.md
  pages.fr/linux/ip.md
  pages.hi/linux/makepkg.md
  pages.it/linux/ip.md
  pages.ja/linux/ip.md
  pages.ko/linux/ip.md
  pages.ko/linux/makepkg.md
  pages.ko/linux/pactree.md
  pages.ko/linux/pw-link.md
  pages.ko/linux/swaplabel.md
  pages.ko/linux/usbip.md
  pages.ko/linux/v4l2-ctl.md
  pages.ko/linux/wall.md
  pages.ko/linux/wol.md
  pages.pl/linux/makepkg.md
  pages.pl/linux/wall.md
  pages.pt_BR/linux/ip.md
  pages.pt_BR/linux/locale.md
  pages.pt_BR/linux/makepkg.md
  pages.pt_BR/linux/pw-link.md
  pages.tr/linux/ip.md
  pages.tr/linux/pw-link.md
  pages.uk/linux/locale.md
  pages.zh/linux/ip.md
  pages.zh/linux/makepkg.md
  pages/common/iotop.md
  pages/linux/ip.md
  pages/linux/locale.md
  pages/linux/makepkg.md
  pages/linux/pactree.md
  pages/linux/pw-link.md
  pages/linux/swaplabel.md
  pages/linux/usbip.md
  pages/linux/v4l2-ctl.md
  pages/linux/wall.md
  pages/linux/wol.md
Labels: page edit, mass changes, translation edit

#15792 *: fix style guide issues part 6
  pages.de/common/git-tag.md
  pages.de/linux/xrandr.md
  pages.es/common/git-shortlog.md
  pages.es/common/git-svn.md
  pages.es/common/git-tag.md
  pages.es/linux/aur.md
  pages.es/linux/dhcpcd.md
  pages.es/linux/eu-readelf.md
  pages.es/linux/journalctl.md
  pages.fr/common/git-shortlog.md
  pages.fr/common/git-svn.md
  pages.fr/common/git-tag.md
  pages.it/common/git-shortlog.md
  pages.it/common/git-svn.md
  pages.it/common/git-tag.md
  pages.ko/common/git-shortlog.md
  pages.ko/common/git-svn.md
  pages.ko/common/git-tag.md
  pages.ko/linux/aur.md
  pages.ko/linux/cam.md
  pages.ko/linux/dhcpcd.md
  pages.ko/linux/eu-readelf.md
  pages.ko/linux/journalctl.md
  pages.ko/linux/pkgctl-repo.md
  pages.ko/linux/repo-add.md
  pages.ko/linux/xrandr.md
  pages.nl/linux/pkgctl-repo.md
  pages.pl/linux/journalctl.md
  pages.pt_BR/common/git-tag.md
  pages.pt_BR/linux/xrandr.md
  pages.tr/common/git-svn.md
  pages.tr/common/git-tag.md
  pages.tr/linux/xrandr.md
  pages.uk/linux/journalctl.md
  pages/common/git-shortlog.md
  pages/common/git-svn.md
  pages/common/git-tag.md
  pages/linux/aur.md
  pages/linux/cam.md
  pages/linux/dhcpcd.md
  pages/linux/eu-readelf.md
  pages/linux/journalctl.md
  pages/linux/pkgctl-repo.md
  pages/linux/repo-add.md
  pages/linux/xrandr.md
Labels: page edit, mass changes, translation edit

#15789 *: fix style guide issues part 5
  pages.de/common/git-log.md
  pages.de/common/git-rebase.md
  pages.de/common/git-remote.md
  pages.es/common/git-clean.md
  pages.es/common/git-lfs.md
  pages.es/common/git-log.md
  pages.es/common/git-rebase.md
  pages.es/common/git-reflog.md
  pages.es/common/git-remote.md
  pages.es/common/git-rev-list.md
  pages.es/common/git-revert.md
  pages.fr/common/git-clean.md
  pages.fr/common/git-lfs.md
  pages.fr/common/git-log.md
  pages.fr/common/git-rebase.md
  pages.fr/common/git-reflog.md
  pages.fr/common/git-remote.md
  pages.id/common/git-clean.md
  pages.id/common/git-remote.md
  pages.it/common/git-clean.md
  pages.it/common/git-lfs.md
  pages.it/common/git-log.md
  pages.it/common/git-rebase.md
  pages.it/common/git-reflog.md
  pages.it/common/git-remote.md
  pages.ko/common/git-clean.md
  pages.ko/common/git-diff-tree.md
  pages.ko/common/git-lfs.md
  pages.ko/common/git-log.md
  pages.ko/common/git-rebase.md
  pages.ko/common/git-reflog.md
  pages.ko/common/git-remote.md
  pages.ko/common/git-rev-list.md
  pages.ko/common/git-revert.md
  pages.pt_BR/common/git-log.md
  pages.pt_BR/common/git-rebase.md
  pages.pt_BR/common/git-remote.md
  pages.ta/common/git-clean.md
  pages.tr/common/git-clean.md
  pages.tr/common/git-lfs.md
  pages.tr/common/git-log.md
  pages.tr/common/git-rebase.md
  pages.tr/common/git-reflog.md
  pages.tr/common/git-remote.md
  pages.uk/common/git-rebase.md
  pages.zh/common/git-log.md
  pages.zh/common/git-rebase.md
  pages.zh/common/git-remote.md
  pages/common/git-clean.md
  pages/common/git-diff-tree.md
  pages/common/git-lfs.md
  pages/common/git-log.md
  pages/common/git-rebase.md
  pages/common/git-reflog.md
  pages/common/git-remote.md
  pages/common/git-rev-list.md
  pages/common/git-revert.md
Labels: page edit, mass changes, translation edit

#15788 *: fix style guide issues part 4
  pages.de/common/git-branch.md
  pages.de/common/git-status.md
  pages.es/common/git-branch.md
  pages.es/common/git-stash.md
  pages.es/common/git-status.md
  pages.fr/common/git-branch.md
  pages.fr/common/git-cherry.md
  pages.fr/common/git-stash.md
  pages.fr/common/git-status.md
  pages.fr/common/rsync.md
  pages.hi/common/git-status.md
  pages.id/common/git-branch.md
  pages.id/common/git-cherry.md
  pages.id/common/git-status.md
  pages.id/common/rsync.md
  pages.it/common/git-branch.md
  pages.it/common/git-stash.md
  pages.it/common/git-status.md
  pages.ko/common/git-branch.md
  pages.ko/common/git-cherry.md
  pages.ko/common/git-stash.md
  pages.ko/common/git-status.md
  pages.ko/common/rsync.md
  pages.pl/common/rsync.md
  pages.pt_BR/common/git-branch.md
  pages.pt_BR/common/git-status.md
  pages.pt_BR/common/rsync.md
  pages.ta/common/git-branch.md
  pages.ta/common/git-cherry.md
  pages.tr/common/git-branch.md
  pages.tr/common/git-cherry.md
  pages.tr/common/git-stash.md
  pages.tr/common/git-status.md
  pages.uk/common/git-cherry.md
  pages.uk/common/git-status.md
  pages.zh/common/rsync.md
  pages/common/git-branch.md
  pages/common/git-cherry.md
  pages/common/git-stash.md
  pages/common/git-status.md
  pages/common/rsync.md
Labels: page edit, mass changes, translation edit

#15777 *: fix style guide issues part 2
  pages.ar/linux/rm.md
  pages.de/common/npm.md
  pages.es/common/mail.md
  pages.es/common/mkdir.md
  pages.es/common/npm.md
  pages.fa/common/mkdir.md
  pages.fr/common/mkdir.md
  pages.hi/common/mkdir.md
  pages.id/common/fping.md
  pages.id/common/mkdir.md
  pages.id/common/npm.md
  pages.it/common/mkdir.md
  pages.ja/linux/df.md
  pages.ko/common/fping.md
  pages.ko/common/mail.md
  pages.ko/common/mkdir.md
  pages.ko/common/mysql_secure_installation.md
  pages.ko/common/nice.md
  pages.ko/common/npm.md
  pages.ko/linux/df.md
  pages.ko/linux/ifstat.md
  pages.ko/linux/mkfs.bcachefs.md
  pages.ko/linux/rm.md
  pages.ko/linux/sfdisk.md
  pages.ko/linux/speaker-test.md
  pages.nl/common/mkdir.md
  pages.nl/common/nice.md
  pages.nl/common/npm.md
  pages.nl/linux/df.md
  pages.nl/linux/rm.md
  pages.pt_BR/common/npm.md
  pages.pt_BR/linux/rm.md
  pages.sr/common/mkdir.md
  pages.ta/common/mkdir.md
  pages.tr/common/mkdir.md
  pages.uk/linux/rm.md
  pages.zh/common/mkdir.md
  pages.zh/common/npm.md
  pages.zh/linux/df.md
  pages.zh_TW/common/mkdir.md
  pages/common/fping.md
  pages/common/mail.md
  pages/common/mkdir.md
  pages/common/mysql_secure_installation.md
  pages/common/nice.md
  pages/common/npm.md
  pages/common/set.md
  pages/linux/df.md
  pages/linux/ifstat.md
  pages/linux/mkfs.bcachefs.md
  pages/linux/pveversion.md
  pages/linux/rm.md
  pages/linux/sfdisk.md
  pages/linux/speaker-test.md
Labels: page edit, mass changes, translation edit

#15873 wezterm: add page
  pages/common/wezterm.md
Labels: new command, review needed

#15858 pages*/osx/*: apply keypress specifications
  pages.de/osx/caffeinate.md
  pages.es/osx/caffeinate.md
  pages.es/osx/nettop.md
  pages.es/osx/pbcopy.md
  pages.es/osx/pbpaste.md
  pages.es/osx/tail.md
  pages.es/osx/top.md
  pages.id/osx/caffeinate.md
  pages.it/osx/caffeinate.md
  pages.ko/osx/caffeinate.md
  pages.ko/osx/nettop.md
  pages.ko/osx/pbcopy.md
  pages.ko/osx/pbpaste.md
  pages.ko/osx/tail.md
  pages.ko/osx/top.md
  pages.nl/osx/caffeinate.md
  pages.nl/osx/tail.md
  pages.pl/osx/caffeinate.md
  pages.pt_BR/osx/caffeinate.md
  pages.th/osx/pbcopy.md
  pages.th/osx/pbpaste.md
  pages.zh/osx/caffeinate.md
  pages.zh/osx/pbcopy.md
  pages.zh/osx/pbpaste.md
  pages.zh/osx/top.md
  pages/osx/caffeinate.md
  pages/osx/nettop.md
  pages/osx/pbcopy.md
  pages/osx/pbpaste.md
  pages/osx/tail.md
  pages/osx/top.md
Labels: page edit, mass changes, review needed, translation edit

#15857 histexpand: delete page
  pages.es/common/histexpand.md
  pages.fr/common/histexpand.md
  pages.ko/common/histexpand.md
  pages.ru/common/histexpand.md
  pages/common/!.md
  pages/common/histexpand.md
  scripts/wrong-filename.sh
Labels: page edit, tooling, translation edit

#15835 lxc-{checkconfig, destroy, start, stop, info, attach}: add page; lxc-ls: add an example and sudo
  pages/linux/lxc-attach.md
  pages/linux/lxc-checkconfig.md
  pages/linux/lxc-destroy.md
  pages/linux/lxc-info.md
  pages/linux/lxc-ls.md
  pages/linux/lxc-start.md
  pages/linux/lxc-stop.md
Labels: page edit, new command, mass changes

#15796 dhclient: add Arabic translation
  pages.ar/common/dhclient.md
Labels: review needed, new translation

#15885 pages*/{windows, osx, freebsd}/*: add option placeholders
  pages.es/freebsd/look.md
  pages.es/osx/base64.md
  pages.es/osx/look.md
  pages.hi/freebsd/base64.md
  pages.hi/freebsd/look.md
  pages.hi/osx/base64.md
  pages.id/freebsd/base64.md
  pages.id/osx/base64.md
  pages.it/osx/base64.md
  pages.ko/freebsd/base64.md
  pages.ko/freebsd/look.md
  pages.ko/osx/base64.md
  pages.ko/osx/gcrane-completion.md
  pages.ko/osx/look.md
  pages.ko/windows/gcrane-completion.md
  pages.nl/freebsd/base64.md
  pages.nl/freebsd/look.md
  pages.nl/osx/base64.md
  pages.nl/osx/gcrane-completion.md
  pages.nl/osx/look.md
  pages.nl/windows/gcrane-completion.md
  pages.pl/freebsd/base64.md
  pages.pl/freebsd/look.md
  pages.pt_BR/freebsd/base64.md
  pages.pt_BR/freebsd/look.md
  pages.pt_BR/osx/base64.md
  pages.zh/osx/base64.md
  pages.zh/osx/look.md
  pages/freebsd/base64.md
  pages/freebsd/look.md
  pages/osx/base64.md
  pages/osx/gcrane-completion.md
  pages/osx/look.md
  pages/windows/gcrane-completion.md
Labels: page edit, mass changes, review needed, translation edit

#15863 pihole: update page
  pages.es/linux/pihole.md
  pages.ko/linux/pihole.md
  pages/linux/pihole.md
Labels: page edit, translation edit

#15882 pages/common/*: add option placeholders part 1
  pages/common/animdl.md
  pages/common/ansible-galaxy.md
  pages/common/asciinema.md
  pages/common/azurite.md
  pages/common/base32.md
  pages/common/base64.md
  pages/common/bat.md
  pages/common/calibredb.md
  pages/common/clang++.md
  pages/common/clang.md
  pages/common/crane-append.md
  pages/common/crane-auth.md
  pages/common/crane-blob.md
  pages/common/crane-catalog.md
  pages/common/crane-config.md
  pages/common/crane-copy.md
  pages/common/crane-delete.md
  pages/common/crane-digest.md
  pages/common/crane-flatten.md
  pages/common/crane-index-append.md
  pages/common/crane-index-filter.md
  pages/common/crane-index.md
  pages/common/crane-ls.md
  pages/common/crane-manifest.md
  pages/common/crane-mutate.md
  pages/common/crane-pull.md
  pages/common/crane-push.md
  pages/common/crane-rebase.md
  pages/common/crane-registry.md
  pages/common/crane-tag.md
  pages/common/crane-validate.md
  pages/common/crane-version.md
  pages/common/crane.md
  pages/common/diff.md
  pages/common/ffsend.md
  pages/common/filebrowser.md
  pages/common/frpc.md
  pages/common/frps.md
  pages/common/g++.md
  pages/common/gcc.md
Labels: page edit, mass changes, review needed

#15883 pages/common/*: add option placeholders part 2
  pages/common/gcrane-copy.md
  pages/common/gcrane-gc.md
  pages/common/gcrane-help.md
  pages/common/gcrane-ls.md
  pages/common/gcrane.md
  pages/common/git-bugreport.md
  pages/common/git-cliff.md
  pages/common/git-commit.md
  pages/common/git-pull.md
  pages/common/git-switch.md
  pages/common/grep.md
  pages/common/gzip.md
  pages/common/http.md
  pages/common/img2sixel.md
  pages/common/lsar.md
  pages/common/mitmproxy.md
  pages/common/nettacker.md
  pages/common/npm-audit.md
  pages/common/npm-install.md
  pages/common/ntfyme.md
  pages/common/onefetch.md
  pages/common/pandoc.md
  pages/common/pg_dumpall.md
  pages/common/podman-compose.md
  pages/common/pulumi-login.md
  pages/common/pulumi-logout.md
  pages/common/pulumi-version.md
  pages/common/pulumi-whoami.md
  pages/common/pulumi.md
  pages/common/pydocstyle.md
  pages/common/toipe.md
  pages/common/typeinc.md
  pages/common/uv-tree.md
  pages/common/waybar.md
  pages/common/zapier-analytics.md
  pages/common/zapier-build.md
  pages/common/zapier-convert.md
  pages/common/zapier-init.md
  pages/common/zapier-push.md
  pages/common/zapier-scaffold.md
Labels: page edit, mass changes, review needed

#15884 pages/linux/*: add option placeholders
  pages/linux/agetty.md
  pages/linux/blkpr.md
  pages/linux/dos2unix.md
  pages/linux/efibootmgr.md
  pages/linux/emerge.md
  pages/linux/fatrace.md
  pages/linux/fuzzel.md
  pages/linux/gcrane-completion.md
  pages/linux/getsebool.md
  pages/linux/grub2-mkpasswd-pbkdf2.md
  pages/linux/hyprpm.md
  pages/linux/ip-route-show.md
  pages/linux/look.md
  pages/linux/mac2unix.md
  pages/linux/protonvpn-connect.md
  pages/linux/pw-dot.md
  pages/linux/pw-metadata.md
  pages/linux/run0.md
  pages/linux/sbctl.md
  pages/linux/semanage-boolean.md
  pages/linux/semanage-permissive.md
  pages/linux/semanage-port.md
  pages/linux/semanage.md
  pages/linux/setsebool.md
  pages/linux/showkey.md
  pages/linux/size.md
  pages/linux/ss.md
  pages/linux/tc.md
  pages/linux/tlp-stat.md
  pages/linux/tune.exfat.md
  pages/linux/unix2dos.md
  pages/linux/unix2mac.md
  pages/linux/unopkg.md
  pages/linux/useradd.md
  pages/linux/userdel.md
  pages/linux/usermod.md
Labels: page edit, mass changes

#15891 tor: add Arabic translation
  pages.ar/linux/tor.md
Labels: review needed, new translation

#15861 pages*/windows/*: apply keypress specifications
  pages.ko/windows/get-content.md
  pages/windows/get-content.md
Labels: page edit, review needed, translation edit

#15803 pages.tr/common/*: add Node.js-related commands
  pages.tr/common/node.md
  pages.tr/common/nodemon.md
  pages.tr/common/npm-install.md
  pages.tr/common/npm-run.md
  pages.tr/common/npm-start.md
  pages.tr/common/npx.md
Labels: new translation

#15860 pages/linux/*: apply keypress specifications
  pages/linux/arecord.md
  pages/linux/atop.md
  pages/linux/caffeinate.md
  pages/linux/cmus.md
  pages/linux/cu.md
  pages/linux/cuyo.md
  pages/linux/expect.md
  pages/linux/fdisk.md
  pages/linux/finch.md
  pages/linux/guake.md
  pages/linux/i3.md
  pages/linux/iftop.md
  pages/linux/kill.md
  pages/linux/killall.md
  pages/linux/konsole.md
  pages/linux/links.md
  pages/linux/more.md
  pages/linux/mpg123.md
  pages/linux/nmtui.md
  pages/linux/nsnake.md
  pages/linux/nsxiv.md
  pages/linux/quickemu.md
  pages/linux/rdesktop.md
  pages/linux/rtcwake.md
  pages/linux/rtorrent.md
  pages/linux/sar.md
  pages/linux/scrot.md
  pages/linux/showkey.md
  pages/linux/snake4.md
  pages/linux/speedread.md
  pages/linux/st.md
  pages/linux/talk.md
  pages/linux/terminator.md
  pages/linux/top.md
  pages/linux/warpd.md
  pages/linux/wf-recorder.md
  pages/linux/xclip.md
  pages/linux/xdotool.md
  pages/linux/xmodmap.md
  pages/linux/xsel.md
  pages/linux/ydotool.md
  pages/linux/yetris.md
  pages/linux/zathura.md
  pages/linux/zile.md
Labels: page edit, mass changes

#15874 style-guide: simplify range placeholder
  contributing-guides/style-guide.md
Labels: documentation

#15908 mssqlclient.py, impacket-mssqlclient: add page
  pages/common/impacket-mssqlclient.md
  pages/common/mssqlclient.py.md
Labels: new command, review needed

#15911 style-guide: rework option syntax instructions
  contributing-guides/style-guide.md
Labels: documentation

#15839 ulimit: add Arabic translation
  pages.ar/common/ulimit.md
Labels: review needed, new translation

#15791 fluidsynth: refresh pages
  pages.ko/linux/fluidsynth.md
  pages/linux/fluidsynth.md
Labels: page edit, translation edit

#15813 printf, print.zsh, print, printenv: add Chinese translation
  pages.zh/common/print.md
  pages.zh/common/print.zsh.md
  pages.zh/common/printenv.md
  pages.zh/common/printf.md
Labels: new translation

#15832 cryptsetup-luksformat: add Chinese translation
  pages.zh/linux/cryptsetup-luksformat.md
Labels: new translation

#15840 gcc, g++: add Arabic translation
  pages.ar/common/g++.md
  pages.ar/common/gcc.md
Labels: review needed, new translation

#15841 ubus: add Spanish translation
  pages.es/linux/ubus.md
Labels: new translation

#15842 pulumi-refresh: add Spanish translation
  pages.es/common/pulumi-refresh.md
Labels: new translation

#15881 GetUserSPNs.py, impacket-GetUserSPNs: add page
  pages/common/getuserspns.py.md
  pages/common/impacket-getuserspns.md
Labels: new command, review needed

#15872 resize: add page
  pages/linux/resize.md
Labels: new command

#15904 btop: add exit example
  pages/common/btop.md
Labels: page edit, review needed

#15894 lbu: add option placeholders
  pages/linux/lbu.md
Labels: page edit

#15887 ack: fix typo in Spanish translation
  pages.es/common/ack.md
Labels: translation edit

#15888 o: add page
  pages/common/o.md
Labels: new command, review needed

#15889 rsync: move trailing slash inside placeholder
  pages.fr/common/rsync.md
  pages.id/common/rsync.md
  pages.ko/common/rsync.md
  pages.pl/common/rsync.md
  pages.pt_BR/common/rsync.md
  pages.zh/common/rsync.md
  pages/common/rsync.md
Labels: page edit, review needed, translation edit

#15914 git-restore: fix default to restore from staging
  pages/common/git-restore.md
Labels: page edit, review needed

#15912 gettext, msginit, msgmerge: add page; msgfmt, xgettext: edit page
  pages/common/gettext.md
  pages/common/msgfmt.md
  pages/common/msginit.md
  pages/common/msgmerge.md
  pages/common/xgettext.md
Labels: page edit, new command

#15917 pw-reserve, pw-v4l2: add page
  pages/linux/pw-reserve.md
  pages/linux/pw-v4l2.md
Labels: new command

#15915 man, sudo, mount, file, curl, ps, seq, gdb, cat, upower, cal: add option placeholders
  pages/common/curl.md
  pages/common/file.md
  pages/common/gdb.md
  pages/common/mount.md
  pages/common/ps.md
  pages/common/seq.md
  pages/common/sudo.md
  pages/linux/cal.md
  pages/linux/cat.md
  pages/linux/man.md
  pages/linux/upower.md
Labels: page edit, mass changes

#15920 trash-{list, restore, empty, rm, put}: add page
  pages/linux/trash-empty.md
  pages/linux/trash-list.md
  pages/linux/trash-put.md
  pages/linux/trash-restore.md
  pages/linux/trash-rm.md
Labels: new command

#15870 minicom, picocom, cu: add examples, sudo and generalize TTY names
  pages/common/picocom.md
  pages/linux/cu.md
  pages/linux/minicom.md
Labels: page edit, review needed

#15869 snmpnetstat: add page
  pages/common/snmpnetstat.md
Labels: new command, review needed

#15822 nstat: add page
  pages/linux/nstat.md
Labels: new command

#15820 ip-link: add promisc mode example
  pages/linux/ip-link.md
Labels: page edit

#15821 bridge: add page
  pages/linux/bridge.md
Labels: new command

#15923 *: add more option placeholders
  pages/common/htop.md
  pages/common/id.md
  pages/common/picocom.md
  pages/common/su.md
  pages/common/tcpdump.md
  pages/common/uniq.md
  pages/common/wc.md
  pages/common/xargs.md
  pages/linux/cu.md
  pages/linux/dmesg.md
  pages/linux/halt.md
  pages/linux/iostat.md
  pages/linux/iptables.md
  pages/linux/minicom.md
  pages/linux/reboot.md
  pages/linux/rmdir.md
  pages/linux/shutdown.md
  pages/linux/strace.md
  pages/linux/systemctl.md
Labels: page edit, mass changes

#15676 share: add page
  pages/sunos/share.md
Labels: new command, review needed

#15910 tldr: add option placeholders
  pages.de/common/tldr.md
  pages.es/common/tldr.md
  pages.fr/common/tldr.md
  pages.hi/common/tldr.md
  pages.id/common/tldr.md
  pages.ja/common/tldr.md
  pages.ko/common/tldr.md
  pages.pl/common/tldr.md
  pages.pt_BR/common/tldr.md
  pages.ru/common/tldr.md
  pages.sh/common/tldr.md
  pages.ta/common/tldr.md
  pages.th/common/tldr.md
  pages.tr/common/tldr.md
  pages.uk/common/tldr.md
  pages.zh/common/tldr.md
  pages.zh_TW/common/tldr.md
  pages/common/tldr.md
Labels: page edit, mass changes, translation edit

#15909 ip*: add more shortforms to translations
  pages.de/linux/ip-address.md
  pages.de/linux/ip.md
  pages.es/linux/ip-address.md
  pages.es/linux/ip-link.md
  pages.es/linux/ip-maddress.md
  pages.es/linux/ip-neighbour.md
  pages.es/linux/ip-route-get.md
  pages.es/linux/ip-route-show.md
  pages.es/linux/ip-route.md
  pages.es/linux/ip-rule.md
  pages.es/linux/ip.md
  pages.fr/linux/ip-address.md
  pages.fr/linux/ip-route-show.md
  pages.fr/linux/ip.md
  pages.it/linux/ip.md
  pages.ja/linux/ip.md
  pages.ko/linux/ip-address.md
  pages.ko/linux/ip-link.md
  pages.ko/linux/ip-neighbour.md
  pages.ko/linux/ip-route-get.md
  pages.ko/linux/ip-route-show.md
  pages.ko/linux/ip-route.md
  pages.ko/linux/ip-rule.md
  pages.ko/linux/ip.md
  pages.nl/linux/ip-route-show.md
  pages.pt_BR/linux/ip-route-show.md
  pages.pt_BR/linux/ip.md
  pages.tr/linux/ip-address.md
  pages.tr/linux/ip-link.md
  pages.tr/linux/ip-neighbour.md
  pages.tr/linux/ip-route.md
  pages.tr/linux/ip-rule.md
  pages.tr/linux/ip.md
  pages.zh/linux/ip.md
  pages/linux/ip-neighbour.md
Labels: page edit, mass changes, translation edit

#15931 bacon: add page
  pages/common/bacon.md
Labels: new command, review needed

#15930 getArch.py, impacket-getArch: add page
  pages/common/getarch.py.md
  pages/common/impacket-getarch.md
Labels: new command, review needed

#15880 herd-list: add page
  pages/osx/herd-list.md
Labels: new command, review needed

#15941 style-guide: reorder instructions
  contributing-guides/style-guide.md
Labels: documentation

#15922 lxc-console: add page
  pages/linux/lxc-console.md
Labels: new command

#15919 lxc-{start, ls, create}: edit page
  pages/linux/lxc-create.md
  pages/linux/lxc-start.md
Labels: page edit

#15825 tcpreplay: add Spanish translation
  pages.es/common/tcpreplay.md
Labels: new translation

#15886 iwinfo: add Spanish translation
  pages.es/linux/iwinfo.md
Labels: new translation

#15893 wezterm: add Spanish translation
  pages.es/common/wezterm.md
Labels: new translation

#15895 cargo, cargo-{build,check,doc,run,test}: add option placeholders
  pages.de/common/cargo.md
  pages.es/common/cargo-build.md
  pages.es/common/cargo.md
  pages.fr/common/cargo-build.md
  pages.fr/common/cargo.md
  pages.it/common/cargo.md
  pages.ja/common/cargo.md
  pages.ko/common/cargo-build.md
  pages.ko/common/cargo-check.md
  pages.ko/common/cargo-doc.md
  pages.ko/common/cargo-run.md
  pages.ko/common/cargo-test.md
  pages.ko/common/cargo.md
  pages.nl/common/cargo.md
  pages.pt_BR/common/cargo-build.md
  pages.pt_BR/common/cargo-doc.md
  pages.pt_BR/common/cargo-test.md
  pages.pt_BR/common/cargo.md
  pages.ta/common/cargo-build.md
  pages.ta/common/cargo-doc.md
  pages.ta/common/cargo-test.md
  pages.ta/common/cargo.md
  pages.zh/common/cargo-build.md
  pages.zh/common/cargo-check.md
  pages.zh/common/cargo-doc.md
  pages.zh/common/cargo-run.md
  pages.zh/common/cargo-test.md
  pages.zh/common/cargo.md
  pages/common/cargo-build.md
  pages/common/cargo-check.md
  pages/common/cargo-doc.md
  pages/common/cargo-run.md
  pages/common/cargo-test.md
  pages/common/cargo.md
Labels: page edit, mass changes, translation edit

#15938 phpstan: edit page
  pages/common/phpstan.md
Labels: page edit, review needed

#15936 tailscale*: update page
  pages/common/tailscale-file.md
  pages/common/tailscale-ssh.md
  pages/common/tailscale-up.md
  pages/common/tailscale.md
Labels: page edit, review needed

#15925 expac: add page
  pages/linux/expac.md
Labels: new command

#15815 osascript: fix single and double quotes
  pages.es/osx/osascript.md
  pages.id/osx/osascript.md
  pages.ko/osx/osascript.md
  pages.zh/osx/osascript.md
  pages/osx/osascript.md
Labels: page edit, translation edit

#15945 sniff.py, sniffer.py, impacket-{sniff, sniffer}: add page
  pages/common/impacket-sniff.md
  pages/common/impacket-sniffer.md
  pages/common/sniff.py.md
  pages/common/sniffer.py.md
Labels: new command, review needed

#15948 parted-interactive: add reference to parted
  pages/linux/parted-interactive.md
Labels: page edit

#15953 systemd-ask-password: refresh page
  pages/linux/systemd-ask-password.md
Labels: page edit

#15955 ubuntu-drivers: add page
  pages/linux/ubuntu-drivers.md
Labels: new command

#15932 node: add Arabic translation
  pages.ar/common/node.md
Labels: review needed, new translation

#15935 byobu: add exit instructions
  pages/common/byobu.md
Labels: page edit, review needed

#15952 docker*: add option placeholders
  pages/common/docker-exec.md
  pages/common/docker-images.md
  pages/common/docker-logs.md
  pages/common/docker-ps.md
  pages/common/docker-pull.md
  pages/common/docker-rm.md
  pages/common/docker-run.md
  pages/common/docker-start.md
  pages/common/docker.md
Labels: page edit, mass changes, review needed

#15954 systemctl-{enable, disable}: add page
  pages/linux/systemctl-enable.md
  pages/linux/systemd-disable.md
Labels: new command

#15958 hostname: remove non-functional example and add option placeholders
  pages/common/hostname.md
Labels: page edit, review needed

#15879 herd: add page
  pages/osx/herd.md
Labels: new command, review needed

#15939 vagrant-halt: add page
  pages/common/vagrant-halt.md
Labels: new command, review needed

#15949 rg, style-guide: improve heading wording
  contributing-guides/style-guide.md
  pages/common/rg.md
Labels: documentation, page edit

#15924 npm-config: add page
  pages/common/npm-config.md
Labels: new command, review needed

#15956 *: add option placeholders
  pages/common/cpio.md
  pages/common/cut.md
  pages/common/git-am.md
  pages/common/git-clone.md
  pages/common/git-push.md
  pages/common/killall.md
  pages/common/llm.md
  pages/common/look.md
  pages/common/lstopo.md
  pages/common/shred.md
  pages/linux/asterisk.md
  pages/linux/cal.md
  pages/linux/ionice.md
  pages/linux/kde-builder.md
  pages/linux/loginctl.md
  pages/linux/pw-config.md
  pages/linux/pw-dump.md
  pages/linux/shutdown.md
  pages/linux/systemd-analyze.md
  pages/linux/xsel.md
  pages/linux/zip.md
Labels: page edit, mass changes

#15957 browsh: add page
  pages/common/browsh.md
Labels: new command, review needed

#15944 comma: add page
  pages/common/,.md
  pages/common/comma.md
  scripts/wrong-filename.sh
Labels: new command, tooling, review needed

#15951 style-guide: instruct option grouping and clarify option instructions
  contributing-guides/style-guide.md
Labels: documentation

#15974 apt: update page
  pages/linux/apt.md
Labels: page edit

#15966 gpg: update page, gpg2: convert to alias of gpg
  pages.ar/common/gpg.md
  pages.de/common/gpg.md
  pages.de/common/gpg2.md
  pages.ja/common/gpg.md
  pages.ja/common/gpg2.md
  pages.ko/common/gpg.md
  pages.ko/common/gpg2.md
  pages.pt_BR/common/gpg.md
  pages.zh/common/gpg.md
  pages.zh/common/gpg2.md
  pages/common/gpg.md
  pages/common/gpg2.md
Labels: page edit, translation edit

#15982 suspend: clarify description
  pages/common/suspend.md
Labels: page edit, review needed

#15975 home-manager: remove test, add --flake example
  pages/common/home-manager.md
Labels: page edit, review needed

#15899 grep: add mnemonics to a description
  pages/common/grep.md
Labels: page edit, review needed

#15985 type: improve more information link
  pages/common/type.md
Labels: page edit, review needed

#15973 npm-deprecate: add page
  pages/common/npm-deprecate.md
Labels: new command, review needed

#15976 ip-{route-show, route}: fix command and clarify
  pages/linux/ip-route-show.md
  pages/linux/ip-route.md
Labels: page edit

#15984 smbmap: merge pages
  pages/common/smbmap.md
  pages/linux/smbmap.md
Labels: page edit

#15983 *: remove and merge duplicate pages
  pages/common/chsh.md
  pages/common/coproc.md
  pages/common/cp.md
  pages/common/duc.md
  pages/common/ed.md
  pages/common/flex.md
  pages/common/last.md
  pages/common/lex.md
  pages/common/man.md
  pages/common/mycli.md
  pages/common/pngcheck.md
  pages/common/renice.md
  pages/common/rm.md
  pages/common/rmdir.md
  pages/common/script.md
  pages/common/tac.md
  pages/common/uname.md
  pages/common/w.md
  pages/common/zip.md
  pages/linux/chsh.md
  pages/linux/coproc.md
  pages/linux/cp.md
  pages/linux/duc.md
  pages/linux/flex.md
  pages/linux/killall.md
  pages/linux/last.md
  pages/linux/lex.md
  pages/linux/man.md
  pages/linux/mesg.md
  pages/linux/mktemp.md
  pages/linux/mycli.md
  pages/linux/nl.md
  pages/linux/pngcheck.md
  pages/linux/renice.md
  pages/linux/rm.md
  pages/linux/rmdir.md
  pages/linux/script.md
  pages/linux/tac.md
  pages/linux/uname.md
  pages/linux/w.md
  pages/linux/zip.md
  pages/osx/ed.md
  pages/osx/gnumfmt.md
  pages/osx/readlink.md
Labels: page edit, new command, mass changes

#15998 yakuake: fix typo
  pages/linux/yakuake.md
Labels: page edit

#15988 hollywood: add page
  pages/linux/hollywood.md
Labels: new command

#15993 gitlab-ctl: edit page
  pages/common/gitlab-ctl.md
Labels: page edit, review needed

#16000 compgen: add examples
  pages/common/compgen.md
Labels: page edit, review needed

#15996 ip-route*: swap from show to list
  pages/linux/ip-route-list.md
  pages/linux/ip-route-show.md
  pages/linux/ip-route.md
Labels: page edit

#15959 lldpctl: add page
  pages/linux/lldpctl.md
Labels: new command

#15964 eject: add option placeholders and eject prevention
  pages/linux/eject.md
Labels: page edit

#15980 ip-rule: fix example description and add generic table creation example
  pages/linux/ip-rule.md
Labels: page edit

#15994 ip-route-add: add page
  pages/linux/ip-route-add.md
Labels: new command

#15997 dockdiver: add page
  pages/common/dockdiver.md
Labels: new command, review needed

#16004 $, doppler, openai, picotool, pip, tldr, uv, who: add Arabic translation
  pages.ar/common/$.md
  pages.ar/common/doppler.md
  pages.ar/common/openai.md
  pages.ar/common/picotool.md
  pages.ar/common/pip.md
  pages.ar/common/tldr.md
  pages.ar/common/uv.md
  pages.ar/common/who.md
Labels: review needed, new translation

#16016 style-guide: further clarify option grouping and move keypress order instructions
  contributing-guides/style-guide.md
Labels: documentation

#15876 timew: add Spanish translation
  pages.es/common/timew.md
  pages/common/timew.md
Labels: page edit, new translation

#15960 expac: add Spanish translation
  pages.es/linux/expac.md
Labels: new translation

#15971 bacon: add Spanish translation
  pages.es/common/bacon.md
Labels: new translation

#15977 comma: add Spanish translation
  pages.es/common/comma.md
Labels: new translation

#15991 npm-config: add Spanish translation
  pages.es/common/npm-config.md
Labels: new translation

#15961 fzf: add Arabic translation
  pages.ar/common/fzf.md
Labels: review needed, new translation
